-- =====================================================
-- 财务共享系统 - 数据库初始化脚本
-- 创建日期：2025-10-21
-- 说明：创建第一阶段所需的所有表
-- =====================================================

-- 1. 影响因素表
CREATE TABLE IF NOT EXISTS T_INFLUENCE_FACTOR (
    FACTOR_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '影响因素ID',
    FACTOR_CODE VARCHAR(50) NOT NULL COMMENT '影响因素编码',
    FACTOR_NAME VARCHAR(200) NOT NULL COMMENT '影响因素名称',
    FACTOR_TYPE INT NOT NULL COMMENT '影响因素类型(1业务类型2科目类型3辅助核算4其他)',
    DATA_TYPE INT COMMENT '数据类型(1字符串2数值3日期4布尔)',
    DATA_LENGTH INT COMMENT '数据长度',
    DECIMAL_PLACES INT COMMENT '小数位数',
    IS_REQUIRED INT DEFAULT 0 COMMENT '是否必填(0否1是)',
    DEFAULT_VALUE VARCHAR(500) COMMENT '默认值',
    VALUE_RANGE VARCHAR(500) COMMENT '取值范围',
    VALIDATION_RULE VARCHAR(500) COMMENT '验证规则',
    DESCRIPTION VARCHAR(500) COMMENT '描述',
    IS_ENABLED INT DEFAULT 1 COMMENT '是否启用(0否1是)',
    SORT_ORDER INT DEFAULT 0 COMMENT '排序号',
    BOOK_ID BIGINT NOT NULL COMMENT '账簿ID',
    TENANT_ID BIGINT NOT NULL COMMENT '租户ID',
    VERSION INT DEFAULT 1 COMMENT '版本号',
    IS_DELETED INT DEFAULT 0 COMMENT '删除标识(0否1是)',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CREATOR BIGINT COMMENT '创建人',
    UPDATER BIGINT COMMENT '更新人',
    UNIQUE KEY UK_FACTOR_CODE (FACTOR_CODE, BOOK_ID, TENANT_ID),
    KEY IDX_BOOK_ID (BOOK_ID),
    KEY IDX_TENANT_ID (TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='影响因素表';

-- 2. 会计科目表
CREATE TABLE IF NOT EXISTS T_ACCOUNT_SUBJECT (
    SUBJECT_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '科目ID',
    SUBJECT_CODE VARCHAR(50) NOT NULL COMMENT '科目编码',
    SUBJECT_NAME VARCHAR(200) NOT NULL COMMENT '科目名称',
    SUBJECT_LEVEL INT COMMENT '科目级次',
    PARENT_SUBJECT_ID BIGINT COMMENT '上级科目ID',
    SUBJECT_TYPE INT COMMENT '科目类型(1资产2负债3权益4收入5费用)',
    BALANCE_DIRECTION INT COMMENT '余额方向(1借方2贷方)',
    IS_LEAF INT DEFAULT 1 COMMENT '是否末级(0否1是)',
    IS_ENABLED INT DEFAULT 1 COMMENT '是否启用(0否1是)',
    IS_CASH INT DEFAULT 0 COMMENT '是否现金科目(0否1是)',
    IS_BANK INT DEFAULT 0 COMMENT '是否银行科目(0否1是)',
    AUXILIARY_TYPES VARCHAR(500) COMMENT '辅助核算类型',
    BOOK_ID BIGINT NOT NULL COMMENT '账簿ID',
    TENANT_ID BIGINT NOT NULL COMMENT '租户ID',
    VERSION INT DEFAULT 1 COMMENT '版本号',
    IS_DELETED INT DEFAULT 0 COMMENT '删除标识(0否1是)',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CREATOR BIGINT COMMENT '创建人',
    UPDATER BIGINT COMMENT '更新人',
    UNIQUE KEY UK_SUBJECT_CODE (SUBJECT_CODE, BOOK_ID, TENANT_ID),
    KEY IDX_BOOK_ID (BOOK_ID),
    KEY IDX_TENANT_ID (TENANT_ID),
    KEY IDX_PARENT_ID (PARENT_SUBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会计科目表';

-- 3. 币种汇率表
CREATE TABLE IF NOT EXISTS T_CURRENCY_RATE (
    RATE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '汇率ID',
    CURRENCY_CODE VARCHAR(10) NOT NULL COMMENT '币种编码',
    CURRENCY_NAME VARCHAR(50) COMMENT '币种名称',
    BASE_CURRENCY VARCHAR(10) COMMENT '本位币',
    EXCHANGE_RATE DECIMAL(18,6) NOT NULL COMMENT '汇率',
    RATE_DATE DATE COMMENT '汇率日期',
    IS_BASE_CURRENCY INT DEFAULT 0 COMMENT '是否本位币(0否1是)',
    IS_ENABLED INT DEFAULT 1 COMMENT '是否启用(0否1是)',
    BOOK_ID BIGINT NOT NULL COMMENT '账簿ID',
    TENANT_ID BIGINT NOT NULL COMMENT '租户ID',
    VERSION INT DEFAULT 1 COMMENT '版本号',
    IS_DELETED INT DEFAULT 0 COMMENT '删除标识(0否1是)',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CREATOR BIGINT COMMENT '创建人',
    UPDATER BIGINT COMMENT '更新人',
    UNIQUE KEY UK_CURRENCY_DATE (CURRENCY_CODE, RATE_DATE, BOOK_ID, TENANT_ID),
    KEY IDX_BOOK_ID (BOOK_ID),
    KEY IDX_TENANT_ID (TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='币种汇率表';

-- 4. 辅助核算项表
CREATE TABLE IF NOT EXISTS T_AUXILIARY_ITEM (
    ITEM_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '辅助项目ID',
    ITEM_CODE VARCHAR(50) NOT NULL COMMENT '辅助项目编码',
    ITEM_NAME VARCHAR(200) NOT NULL COMMENT '辅助项目名称',
    ITEM_TYPE VARCHAR(50) COMMENT '辅助项目类型',
    ITEM_VALUE VARCHAR(500) COMMENT '辅助项目值',
    IS_ENABLED INT DEFAULT 1 COMMENT '是否启用(0否1是)',
    SORT_ORDER INT DEFAULT 0 COMMENT '排序号',
    DESCRIPTION VARCHAR(500) COMMENT '描述',
    BOOK_ID BIGINT NOT NULL COMMENT '账簿ID',
    TENANT_ID BIGINT NOT NULL COMMENT '租户ID',
    VERSION INT DEFAULT 1 COMMENT '版本号',
    IS_DELETED INT DEFAULT 0 COMMENT '删除标识(0否1是)',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CREATOR BIGINT COMMENT '创建人',
    UPDATER BIGINT COMMENT '更新人',
    UNIQUE KEY UK_ITEM_CODE (ITEM_CODE, BOOK_ID, TENANT_ID),
    KEY IDX_BOOK_ID (BOOK_ID),
    KEY IDX_TENANT_ID (TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='辅助核算项表';

