-- 账期设置表
CREATE TABLE T_PAYMENT_TERMS (
    TERMS_ID            BIGINT          NOT NULL,
    TERMS_CODE          VARCHAR(50)     NOT NULL,
    TERMS_NAME          VARCHAR(200)    NOT NULL,
    SUPPLIER_ID         BIGINT          NULL,
    PAYMENT_DAYS        INT             DEFAULT 0,
    DISCOUNT_DAYS       INT             DEFAULT 0,
    DISCOUNT_RATE       DECIMAL(10,4)   DEFAULT 0,
    STATUS              TINYINT         DEFAULT 1,
    BOOK_ID             BIGINT          NULL,
    TENANT_ID           BIGINT          NOT NULL,
    VERSION             INT             DEFAULT 1,
    IS_DELETED          TINYINT         DEFAULT 0,
    CREATE_TIME         DATETIME        DEFAULT SYSDATE,
    UPDATE_TIME         DATETIME        DEFAULT SYSDATE,
    CREATOR             BIGINT          NULL,
    UPDATER             BIGINT          NULL,
    REMARK              VARCHAR(500)    NULL,
    PRIMARY KEY (TERMS_ID)
);

-- 创建索引
CREATE INDEX IDX_PAYMENT_TERMS_CODE ON T_PAYMENT_TERMS(TERMS_CODE);
CREATE INDEX IDX_PAYMENT_TERMS_TENANT ON T_PAYMENT_TERMS(TENANT_ID);
CREATE INDEX IDX_PAYMENT_TERMS_STATUS ON T_PAYMENT_TERMS(STATUS);

-- 添加注释
COMMENT ON TABLE T_PAYMENT_TERMS IS '账期设置表';
COMMENT ON COLUMN T_PAYMENT_TERMS.TERMS_ID IS '账期ID';
COMMENT ON COLUMN T_PAYMENT_TERMS.TERMS_CODE IS '账期编码';
COMMENT ON COLUMN T_PAYMENT_TERMS.TERMS_NAME IS '账期名称';
COMMENT ON COLUMN T_PAYMENT_TERMS.SUPPLIER_ID IS '供应商ID';
COMMENT ON COLUMN T_PAYMENT_TERMS.PAYMENT_DAYS IS '付款天数';
COMMENT ON COLUMN T_PAYMENT_TERMS.DISCOUNT_DAYS IS '折扣天数';
COMMENT ON COLUMN T_PAYMENT_TERMS.DISCOUNT_RATE IS '折扣率';
COMMENT ON COLUMN T_PAYMENT_TERMS.STATUS IS '状态: 1-启用, 0-停用';
COMMENT ON COLUMN T_PAYMENT_TERMS.BOOK_ID IS '账簿ID';
COMMENT ON COLUMN T_PAYMENT_TERMS.TENANT_ID IS '租户ID';
COMMENT ON COLUMN T_PAYMENT_TERMS.VERSION IS '版本号';
COMMENT ON COLUMN T_PAYMENT_TERMS.IS_DELETED IS '删除标识(0否1是)';
COMMENT ON COLUMN T_PAYMENT_TERMS.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_PAYMENT_TERMS.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN T_PAYMENT_TERMS.CREATOR IS '创建人';
COMMENT ON COLUMN T_PAYMENT_TERMS.UPDATER IS '更新人';
COMMENT ON COLUMN T_PAYMENT_TERMS.REMARK IS '备注';

-- 插入测试数据
INSERT INTO T_PAYMENT_TERMS (TERMS_ID, TERMS_CODE, TERMS_NAME, SUPPLIER_ID, PAYMENT_DAYS, DISCOUNT_DAYS, DISCOUNT_RATE, STATUS, TENANT_ID, CREATE_TIME, UPDATE_TIME)
VALUES (1, 'TERMS001', '标准账期', NULL, 45, 10, 0.02, 1, 1, SYSDATE, SYSDATE);

INSERT INTO T_PAYMENT_TERMS (TERMS_ID, TERMS_CODE, TERMS_NAME, SUPPLIER_ID, PAYMENT_DAYS, DISCOUNT_DAYS, DISCOUNT_RATE, STATUS, TENANT_ID, CREATE_TIME, UPDATE_TIME)
VALUES (2, 'TERMS002', '快速账期', NULL, 30, 7, 0.03, 1, 1, SYSDATE, SYSDATE);

INSERT INTO T_PAYMENT_TERMS (TERMS_ID, TERMS_CODE, TERMS_NAME, SUPPLIER_ID, PAYMENT_DAYS, DISCOUNT_DAYS, DISCOUNT_RATE, STATUS, TENANT_ID, CREATE_TIME, UPDATE_TIME)
VALUES (3, 'TERMS003', '延期账期', NULL, 60, 15, 0.015, 1, 1, SYSDATE, SYSDATE);

INSERT INTO T_PAYMENT_TERMS (TERMS_ID, TERMS_CODE, TERMS_NAME, SUPPLIER_ID, PAYMENT_DAYS, DISCOUNT_DAYS, DISCOUNT_RATE, STATUS, TENANT_ID, CREATE_TIME, UPDATE_TIME)
VALUES (4, 'TERMS004', '现金账期', NULL, 0, 0, 0.0, 1, 1, SYSDATE, SYSDATE);

INSERT INTO T_PAYMENT_TERMS (TERMS_ID, TERMS_CODE, TERMS_NAME, SUPPLIER_ID, PAYMENT_DAYS, DISCOUNT_DAYS, DISCOUNT_RATE, STATUS, TENANT_ID, CREATE_TIME, UPDATE_TIME)
VALUES (5, 'TERMS005', '特殊账期', NULL, 90, 30, 0.01, 0, 1, SYSDATE, SYSDATE);

