-- 为代理委托权限表添加权限级别和金额限制字段
-- V3__add_permission_level_and_amount_limit.sql

-- 添加权限级别字段 (READ/EDIT/FULL)
ALTER TABLE TBL_PROXY_DELEGATION_PERMISSION
ADD PERMISSION_LEVEL VARCHAR(50);

-- 添加金额限制字段
ALTER TABLE TBL_PROXY_DELEGATION_PERMISSION
ADD AMOUNT_LIMIT DECIMAL(18,2);

-- 为现有数据设置默认值
UPDATE TBL_PROXY_DELEGATION_PERMISSION
SET PERMISSION_LEVEL = 'READ'
WHERE PERMISSION_LEVEL IS NULL;

UPDATE TBL_PROXY_DELEGATION_PERMISSION
SET AMOUNT_LIMIT = 0
WHERE AMOUNT_LIMIT IS NULL;

