-- =====================================================
-- 财务共享系统 - 业务单据统计所需表建表及测试数据
-- 创建日期：2026-06-16
-- 数据库：达梦(DM)
-- 说明：document-stats 接口依赖的4张表
-- =====================================================

-- =====================================================
-- 1. 报销单表 TBL_EXPENSE_REPORT
-- =====================================================
CREATE TABLE IF NOT EXISTS TBL_EXPENSE_REPORT (
    REPORT_ID           VARCHAR2(50)   NOT NULL PRIMARY KEY,
    REPORT_CODE         VARCHAR2(100),
    REPORT_TITLE        VARCHAR2(200),
    REPORT_TYPE         VARCHAR2(50),
    REPORT_STATUS       VARCHAR2(30),
    APPLICANT_ID        VARCHAR2(50),
    APPLICANT_NAME      VARCHAR2(50),
    APPLICANT_DEPT_ID   VARCHAR2(50),
    APPLICANT_DEPT_NAME VARCHAR2(100),
    PROJECT_ID          VARCHAR2(50),
    PROJECT_NAME        VARCHAR2(200),
    TOTAL_AMOUNT        DECIMAL(18,2),
    PAYMENT_AMOUNT      DECIMAL(18,2),
    REPORT_DATE         TIMESTAMP,
    REPORT_REASON       VARCHAR2(500),
    APPROVER_ID         VARCHAR2(50),
    APPROVER_NAME       VARCHAR2(50),
    APPROVE_TIME        TIMESTAMP,
    APPROVE_OPINION     VARCHAR2(500),
    PAYMENT_STATUS      VARCHAR2(30),
    PAYMENT_TIME        TIMESTAMP,
    PAYMENT_VOUCHER_NO  VARCHAR2(100),
    CREATE_TIME         TIMESTAMP     DEFAULT SYSDATE,
    CREATE_USER         VARCHAR2(50),
    UPDATE_TIME         TIMESTAMP     DEFAULT SYSDATE,
    UPDATE_USER         VARCHAR2(50),
    REMARK              VARCHAR2(500)
);

COMMENT ON TABLE  TBL_EXPENSE_REPORT                    IS '报销单表';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.REPORT_ID            IS '报销单ID';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.REPORT_CODE          IS '报销单号';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.REPORT_TITLE         IS '报销单标题';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.REPORT_TYPE          IS '报销单类型';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.REPORT_STATUS        IS '报销单状态(DRAFT-草稿,PENDING-待审批,APPROVED-已审批,REJECTED-已拒绝,PAID-已付款)';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.APPLICANT_ID         IS '申请人ID';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.APPLICANT_NAME       IS '申请人姓名';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.APPLICANT_DEPT_ID    IS '申请人部门ID';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.APPLICANT_DEPT_NAME  IS '申请人部门名称';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.PROJECT_ID           IS '项目ID';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.PROJECT_NAME         IS '项目名称';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.TOTAL_AMOUNT         IS '报销总金额';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.PAYMENT_AMOUNT       IS '已支付金额';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.REPORT_DATE          IS '报销日期';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.REPORT_REASON        IS '报销事由';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.APPROVER_ID          IS '审批人ID';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.APPROVER_NAME        IS '审批人姓名';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.APPROVE_TIME         IS '审批时间';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.APPROVE_OPINION      IS '审批意见';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.PAYMENT_STATUS       IS '付款状态(UNPAID-未付款,PAID-已付款)';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.PAYMENT_TIME         IS '付款时间';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.PAYMENT_VOUCHER_NO   IS '付款凭证号';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.CREATE_TIME          IS '创建时间';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.CREATE_USER          IS '创建人';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.UPDATE_TIME          IS '更新时间';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.UPDATE_USER          IS '更新人';
COMMENT ON COLUMN TBL_EXPENSE_REPORT.REMARK               IS '备注';

-- =====================================================
-- 2. 借款单表 TBL_LOAN_APPLICATION
-- =====================================================
CREATE TABLE IF NOT EXISTS TBL_LOAN_APPLICATION (
    LOAN_ID             VARCHAR2(50)   NOT NULL PRIMARY KEY,
    LOAN_CODE           VARCHAR2(100),
    LOAN_TITLE          VARCHAR2(200),
    LOAN_TYPE           VARCHAR2(50),
    LOAN_STATUS         VARCHAR2(30),
    APPLICANT_ID        VARCHAR2(50),
    APPLICANT_NAME      VARCHAR2(50),
    APPLICANT_DEPT_ID   VARCHAR2(50),
    APPLICANT_DEPT_NAME VARCHAR2(100),
    LOAN_AMOUNT         DECIMAL(18,2),
    LOAN_DATE           TIMESTAMP,
    LOAN_REASON         VARCHAR2(500),
    EXPECT_RETURN_DATE  TIMESTAMP,
    APPROVER_ID         VARCHAR2(50),
    APPROVER_NAME       VARCHAR2(50),
    APPROVE_TIME        TIMESTAMP,
    APPROVE_OPINION     VARCHAR2(500),
    DISBURSE_STATUS     VARCHAR2(30),
    DISBURSE_TIME       TIMESTAMP,
    DISBURSE_VOUCHER_NO VARCHAR2(100),
    RETURN_STATUS       VARCHAR2(30),
    RETURNED_AMOUNT     DECIMAL(18,2),
    CREATE_TIME         TIMESTAMP     DEFAULT SYSDATE,
    CREATE_USER         VARCHAR2(50),
    UPDATE_TIME         TIMESTAMP     DEFAULT SYSDATE,
    UPDATE_USER         VARCHAR2(50),
    REMARK              VARCHAR2(500)
);

COMMENT ON TABLE  TBL_LOAN_APPLICATION                    IS '借款单主表';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.LOAN_ID            IS '借款单ID';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.LOAN_CODE          IS '借款单号';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.LOAN_TITLE         IS '借款单标题';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.LOAN_TYPE          IS '借款类型(TRAVEL-差旅借款,BUSINESS-业务借款,EMERGENCY-紧急借款,OTHER-其他)';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.LOAN_STATUS        IS '借款单状态(DRAFT-草稿,SUBMITTED-已提交,APPROVING-审批中,APPROVED-已审批,REJECTED-已驳回,DISBURSED-已放款,RETURNED-已归还,CANCELLED-已取消)';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.APPLICANT_ID       IS '申请人ID';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.APPLICANT_NAME     IS '申请人姓名';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.APPLICANT_DEPT_ID  IS '申请人部门ID';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.APPLICANT_DEPT_NAME IS '申请人部门名称';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.LOAN_AMOUNT        IS '借款金额';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.LOAN_DATE          IS '借款日期';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.LOAN_REASON        IS '借款事由';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.EXPECT_RETURN_DATE IS '预计归还日期';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.APPROVER_ID        IS '审批人ID';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.APPROVER_NAME      IS '审批人姓名';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.APPROVE_TIME       IS '审批时间';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.APPROVE_OPINION    IS '审批意见';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.DISBURSE_STATUS    IS '放款状态(UNDISBURSED-未放款,DISBURSED-已放款)';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.DISBURSE_TIME      IS '放款时间';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.DISBURSE_VOUCHER_NO IS '放款凭证号';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.RETURN_STATUS      IS '归还状态(UNRETURNED-未归还,PARTIAL-部分归还,RETURNED-已归还)';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.RETURNED_AMOUNT    IS '已归还金额';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.CREATE_TIME        IS '创建时间';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.CREATE_USER        IS '创建人';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.UPDATE_TIME        IS '更新时间';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.UPDATE_USER        IS '更新人';
COMMENT ON COLUMN TBL_LOAN_APPLICATION.REMARK             IS '备注';

-- =====================================================
-- 3. 预付款表 TBL_PREPAYMENT
-- =====================================================
CREATE TABLE IF NOT EXISTS TBL_PREPAYMENT (
    PREPAYMENT_ID       VARCHAR2(50)   NOT NULL PRIMARY KEY,
    PREPAYMENT_CODE     VARCHAR2(100),
    PREPAYMENT_TITLE    VARCHAR2(200),
    PREPAYMENT_TYPE     VARCHAR2(50),
    PREPAYMENT_STATUS   VARCHAR2(30),
    APPLICANT_ID        VARCHAR2(50),
    APPLICANT_NAME      VARCHAR2(50),
    APPLICANT_DEPT_ID   VARCHAR2(50),
    APPLICANT_DEPT_NAME VARCHAR2(100),
    SUPPLIER_ID         VARCHAR2(50),
    SUPPLIER_NAME       VARCHAR2(200),
    CONTRACT_ID         VARCHAR2(50),
    CONTRACT_CODE       VARCHAR2(100),
    PREPAYMENT_AMOUNT   DECIMAL(18,2),
    PREPAYMENT_DATE     TIMESTAMP,
    PREPAYMENT_REASON   VARCHAR2(500),
    APPROVER_ID         VARCHAR2(50),
    APPROVER_NAME       VARCHAR2(50),
    APPROVE_TIME        TIMESTAMP,
    APPROVE_OPINION     VARCHAR2(500),
    PAYMENT_STATUS      VARCHAR2(30),
    PAYMENT_TIME        TIMESTAMP,
    PAYMENT_VOUCHER_NO  VARCHAR2(100),
    WRITEOFF_STATUS     VARCHAR2(30),
    WRITEOFF_AMOUNT     DECIMAL(18,2),
    CREATE_TIME         TIMESTAMP     DEFAULT SYSDATE,
    CREATE_USER         VARCHAR2(50),
    UPDATE_TIME         TIMESTAMP     DEFAULT SYSDATE,
    UPDATE_USER         VARCHAR2(50),
    REMARK              VARCHAR2(500)
);

COMMENT ON TABLE  TBL_PREPAYMENT                    IS '预付款单主表';
COMMENT ON COLUMN TBL_PREPAYMENT.PREPAYMENT_ID      IS '预付款单ID';
COMMENT ON COLUMN TBL_PREPAYMENT.PREPAYMENT_CODE    IS '预付款单号';
COMMENT ON COLUMN TBL_PREPAYMENT.PREPAYMENT_TITLE   IS '预付款单标题';
COMMENT ON COLUMN TBL_PREPAYMENT.PREPAYMENT_TYPE    IS '预付款类型(PURCHASE-采购预付款,SERVICE-服务预付款,RENT-租金预付款,OTHER-其他)';
COMMENT ON COLUMN TBL_PREPAYMENT.PREPAYMENT_STATUS  IS '预付款单状态(DRAFT-草稿,SUBMITTED-已提交,APPROVING-审批中,APPROVED-已审批,REJECTED-已驳回,PAID-已支付,WRITEOFF-已核销,CANCELLED-已取消)';
COMMENT ON COLUMN TBL_PREPAYMENT.APPLICANT_ID       IS '申请人ID';
COMMENT ON COLUMN TBL_PREPAYMENT.APPLICANT_NAME     IS '申请人姓名';
COMMENT ON COLUMN TBL_PREPAYMENT.APPLICANT_DEPT_ID  IS '申请人部门ID';
COMMENT ON COLUMN TBL_PREPAYMENT.APPLICANT_DEPT_NAME IS '申请人部门名称';
COMMENT ON COLUMN TBL_PREPAYMENT.SUPPLIER_ID        IS '供应商ID';
COMMENT ON COLUMN TBL_PREPAYMENT.SUPPLIER_NAME      IS '供应商名称';
COMMENT ON COLUMN TBL_PREPAYMENT.CONTRACT_ID        IS '合同ID';
COMMENT ON COLUMN TBL_PREPAYMENT.CONTRACT_CODE      IS '合同编号';
COMMENT ON COLUMN TBL_PREPAYMENT.PREPAYMENT_AMOUNT  IS '预付金额';
COMMENT ON COLUMN TBL_PREPAYMENT.PREPAYMENT_DATE    IS '预付款日期';
COMMENT ON COLUMN TBL_PREPAYMENT.PREPAYMENT_REASON  IS '预付款事由';
COMMENT ON COLUMN TBL_PREPAYMENT.APPROVER_ID        IS '审批人ID';
COMMENT ON COLUMN TBL_PREPAYMENT.APPROVER_NAME      IS '审批人姓名';
COMMENT ON COLUMN TBL_PREPAYMENT.APPROVE_TIME       IS '审批时间';
COMMENT ON COLUMN TBL_PREPAYMENT.APPROVE_OPINION    IS '审批意见';
COMMENT ON COLUMN TBL_PREPAYMENT.PAYMENT_STATUS     IS '支付状态(UNPAID-未支付,PAID-已支付)';
COMMENT ON COLUMN TBL_PREPAYMENT.PAYMENT_TIME       IS '支付时间';
COMMENT ON COLUMN TBL_PREPAYMENT.PAYMENT_VOUCHER_NO IS '支付凭证号';
COMMENT ON COLUMN TBL_PREPAYMENT.WRITEOFF_STATUS    IS '核销状态(UNWRITEOFF-未核销,PARTIAL-部分核销,WRITEOFF-已核销)';
COMMENT ON COLUMN TBL_PREPAYMENT.WRITEOFF_AMOUNT    IS '已核销金额';
COMMENT ON COLUMN TBL_PREPAYMENT.CREATE_TIME        IS '创建时间';
COMMENT ON COLUMN TBL_PREPAYMENT.CREATE_USER        IS '创建人';
COMMENT ON COLUMN TBL_PREPAYMENT.UPDATE_TIME        IS '更新时间';
COMMENT ON COLUMN TBL_PREPAYMENT.UPDATE_USER        IS '更新人';
COMMENT ON COLUMN TBL_PREPAYMENT.REMARK             IS '备注';

-- =====================================================
-- 4. 合同表 TBL_CONTRACT
-- =====================================================
CREATE TABLE IF NOT EXISTS TBL_CONTRACT (
    CONTRACT_ID         VARCHAR2(50)   NOT NULL PRIMARY KEY,
    CONTRACT_CODE       VARCHAR2(100),
    CONTRACT_NAME       VARCHAR2(200),
    CONTRACT_TYPE       VARCHAR2(50),
    CONTRACT_STATUS     VARCHAR2(30),
    PARTY_A             VARCHAR2(200),
    PARTY_B             VARCHAR2(200),
    SUPPLIER_ID         VARCHAR2(50),
    SUPPLIER_NAME       VARCHAR2(200),
    CONTRACT_AMOUNT     DECIMAL(18,2),
    SIGNED_DATE         TIMESTAMP,
    START_DATE          TIMESTAMP,
    END_DATE            TIMESTAMP,
    APPLICANT_ID        VARCHAR2(50),
    APPLICANT_NAME      VARCHAR2(50),
    APPLICANT_DEPT_ID   VARCHAR2(50),
    APPLICANT_DEPT_NAME VARCHAR2(100),
    APPROVER_ID         VARCHAR2(50),
    APPROVER_NAME       VARCHAR2(50),
    APPROVE_TIME        TIMESTAMP,
    APPROVE_OPINION     VARCHAR2(500),
    CONTRACT_CONTENT    CLOB,
    ATTACHMENT_URL      VARCHAR2(500),
    CREATE_TIME         TIMESTAMP     DEFAULT SYSDATE,
    CREATE_USER         VARCHAR2(50),
    UPDATE_TIME         TIMESTAMP     DEFAULT SYSDATE,
    UPDATE_USER         VARCHAR2(50),
    REMARK              VARCHAR2(500)
);

COMMENT ON TABLE  TBL_CONTRACT                    IS '合同主表';
COMMENT ON COLUMN TBL_CONTRACT.CONTRACT_ID        IS '合同ID';
COMMENT ON COLUMN TBL_CONTRACT.CONTRACT_CODE      IS '合同编号';
COMMENT ON COLUMN TBL_CONTRACT.CONTRACT_NAME      IS '合同名称';
COMMENT ON COLUMN TBL_CONTRACT.CONTRACT_TYPE      IS '合同类型(PURCHASE-采购合同,SALES-销售合同,SERVICE-服务合同,OTHER-其他)';
COMMENT ON COLUMN TBL_CONTRACT.CONTRACT_STATUS    IS '合同状态(DRAFT-草稿,SUBMITTED-已提交,APPROVING-审批中,APPROVED-已审批,REJECTED-已驳回,EXECUTING-执行中,COMPLETED-已完成,CANCELLED-已取消)';
COMMENT ON COLUMN TBL_CONTRACT.PARTY_A            IS '甲方';
COMMENT ON COLUMN TBL_CONTRACT.PARTY_B            IS '乙方';
COMMENT ON COLUMN TBL_CONTRACT.SUPPLIER_ID        IS '供应商ID';
COMMENT ON COLUMN TBL_CONTRACT.SUPPLIER_NAME      IS '供应商名称';
COMMENT ON COLUMN TBL_CONTRACT.CONTRACT_AMOUNT    IS '合同金额';
COMMENT ON COLUMN TBL_CONTRACT.SIGNED_DATE        IS '签订日期';
COMMENT ON COLUMN TBL_CONTRACT.START_DATE         IS '开始日期';
COMMENT ON COLUMN TBL_CONTRACT.END_DATE           IS '结束日期';
COMMENT ON COLUMN TBL_CONTRACT.APPLICANT_ID       IS '申请人ID';
COMMENT ON COLUMN TBL_CONTRACT.APPLICANT_NAME     IS '申请人姓名';
COMMENT ON COLUMN TBL_CONTRACT.APPLICANT_DEPT_ID  IS '申请人部门ID';
COMMENT ON COLUMN TBL_CONTRACT.APPLICANT_DEPT_NAME IS '申请人部门名称';
COMMENT ON COLUMN TBL_CONTRACT.APPROVER_ID        IS '审批人ID';
COMMENT ON COLUMN TBL_CONTRACT.APPROVER_NAME      IS '审批人姓名';
COMMENT ON COLUMN TBL_CONTRACT.APPROVE_TIME       IS '审批时间';
COMMENT ON COLUMN TBL_CONTRACT.APPROVE_OPINION    IS '审批意见';
COMMENT ON COLUMN TBL_CONTRACT.CONTRACT_CONTENT   IS '合同内容';
COMMENT ON COLUMN TBL_CONTRACT.ATTACHMENT_URL     IS '附件URL';
COMMENT ON COLUMN TBL_CONTRACT.CREATE_TIME        IS '创建时间';
COMMENT ON COLUMN TBL_CONTRACT.CREATE_USER        IS '创建人';
COMMENT ON COLUMN TBL_CONTRACT.UPDATE_TIME        IS '更新时间';
COMMENT ON COLUMN TBL_CONTRACT.UPDATE_USER        IS '更新人';
COMMENT ON COLUMN TBL_CONTRACT.REMARK             IS '备注';

-- =====================================================
-- 5. TBL_EXPENSE_REPORT 测试数据 (10条)
-- =====================================================

INSERT INTO TBL_EXPENSE_REPORT (REPORT_ID, REPORT_CODE, REPORT_TITLE, REPORT_TYPE, REPORT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, PROJECT_ID, PROJECT_NAME, TOTAL_AMOUNT, PAYMENT_AMOUNT, REPORT_DATE, REPORT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('RPT20260601001', 'BX20260601001', '6月差旅费报销', 'TRAVEL', 'PAID', 'USER001', '张三', 'DEPT001', '销售部', 'PROJ001', '华北销售项目', 3850.00, 3850.00, TO_DATE('2026-06-01','YYYY-MM-DD'), '北京出差3天差旅费', 'APV001', '王经理', TO_DATE('2026-06-03 10:30:00','YYYY-MM-DD HH24:MI:SS'), '同意报销', 'PAID', TO_DATE('2026-06-05 14:00:00','YYYY-MM-DD HH24:MI:SS'), 'PAY20260601001', SYSDATE, 'USER001', SYSDATE, 'USER001', '含机票、住宿、餐饮');

INSERT INTO TBL_EXPENSE_REPORT (REPORT_ID, REPORT_CODE, REPORT_TITLE, REPORT_TYPE, REPORT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, PROJECT_ID, PROJECT_NAME, TOTAL_AMOUNT, PAYMENT_AMOUNT, REPORT_DATE, REPORT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('RPT20260601002', 'BX20260601002', '办公用品采购报销', 'OFFICE', 'PENDING', 'USER002', '李四', 'DEPT002', '技术部', 'PROJ002', '办公系统升级', 2680.50, 0.00, TO_DATE('2026-06-02','YYYY-MM-DD'), '采购打印纸、墨盒等办公用品', NULL, NULL, NULL, NULL, 'UNPAID', NULL, NULL, SYSDATE, 'USER002', SYSDATE, 'USER002', '待审批');

INSERT INTO TBL_EXPENSE_REPORT (REPORT_ID, REPORT_CODE, REPORT_TITLE, REPORT_TYPE, REPORT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, PROJECT_ID, PROJECT_NAME, TOTAL_AMOUNT, PAYMENT_AMOUNT, REPORT_DATE, REPORT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('RPT20260601003', 'BX20260601003', '客户招待费报销', 'ENTERTAINMENT', 'PENDING', 'USER003', '王五', 'DEPT003', '市场部', 'PROJ003', '新客户拓展', 1580.00, 0.00, TO_DATE('2026-06-03','YYYY-MM-DD'), '招待潜在客户用餐', NULL, NULL, NULL, NULL, 'UNPAID', NULL, NULL, SYSDATE, 'USER003', SYSDATE, 'USER003', '待审批');

INSERT INTO TBL_EXPENSE_REPORT (REPORT_ID, REPORT_CODE, REPORT_TITLE, REPORT_TYPE, REPORT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, PROJECT_ID, PROJECT_NAME, TOTAL_AMOUNT, PAYMENT_AMOUNT, REPORT_DATE, REPORT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('RPT20260601004', 'BX20260601004', '技术培训费报销', 'TRAINING', 'APPROVED', 'USER004', '赵六', 'DEPT002', '技术部', 'PROJ004', '技术培训项目', 5600.00, 0.00, TO_DATE('2026-06-04','YYYY-MM-DD'), '参加外部技术培训费用', 'APV002', '刘总监', TO_DATE('2026-06-06 09:00:00','YYYY-MM-DD HH24:MI:SS'), '同意，安排付款', 'UNPAID', NULL, NULL, SYSDATE, 'USER004', SYSDATE, 'USER004', '已审批待付款');

INSERT INTO TBL_EXPENSE_REPORT (REPORT_ID, REPORT_CODE, REPORT_TITLE, REPORT_TYPE, REPORT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, PROJECT_ID, PROJECT_NAME, TOTAL_AMOUNT, PAYMENT_AMOUNT, REPORT_DATE, REPORT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('RPT20260601005', 'BX20260601005', '交通费报销', 'TRANSPORT', 'PAID', 'USER005', '孙七', 'DEPT004', '管理部', 'PROJ005', '管理优化项目', 420.00, 420.00, TO_DATE('2026-06-05','YYYY-MM-DD'), '市内交通费', 'APV001', '王经理', TO_DATE('2026-06-06 11:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', 'PAID', TO_DATE('2026-06-07 10:00:00','YYYY-MM-DD HH24:MI:SS'), 'PAY20260601002', SYSDATE, 'USER005', SYSDATE, 'USER005', '出租车及地铁');

INSERT INTO TBL_EXPENSE_REPORT (REPORT_ID, REPORT_CODE, REPORT_TITLE, REPORT_TYPE, REPORT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, PROJECT_ID, PROJECT_NAME, TOTAL_AMOUNT, PAYMENT_AMOUNT, REPORT_DATE, REPORT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('RPT20260601006', 'BX20260601006', '展会参展费报销', 'MARKETING', 'REJECTED', 'USER003', '王五', 'DEPT003', '市场部', 'PROJ003', '新客户拓展', 12500.00, 0.00, TO_DATE('2026-06-06','YYYY-MM-DD'), '参加行业展会费用', 'APV002', '刘总监', TO_DATE('2026-06-07 16:00:00','YYYY-MM-DD HH24:MI:SS'), '预算超支，驳回', 'UNPAID', NULL, NULL, SYSDATE, 'USER003', SYSDATE, 'USER003', '已驳回');

INSERT INTO TBL_EXPENSE_REPORT (REPORT_ID, REPORT_CODE, REPORT_TITLE, REPORT_TYPE, REPORT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, PROJECT_ID, PROJECT_NAME, TOTAL_AMOUNT, PAYMENT_AMOUNT, REPORT_DATE, REPORT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('RPT20260601007', 'BX20260601007', '软件许可费报销', 'SOFTWARE', 'PAID', 'USER002', '李四', 'DEPT002', '技术部', 'PROJ002', '办公系统升级', 28000.00, 28000.00, TO_DATE('2026-06-07','YYYY-MM-DD'), '年度软件许可续费', 'APV003', '张总', TO_DATE('2026-06-08 14:00:00','YYYY-MM-DD HH24:MI:SS'), '同意报销，紧急付款', 'PAID', TO_DATE('2026-06-09 09:30:00','YYYY-MM-DD HH24:MI:SS'), 'PAY20260601003', SYSDATE, 'USER002', SYSDATE, 'USER002', 'IDE及数据库许可');

INSERT INTO TBL_EXPENSE_REPORT (REPORT_ID, REPORT_CODE, REPORT_TITLE, REPORT_TYPE, REPORT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, PROJECT_ID, PROJECT_NAME, TOTAL_AMOUNT, PAYMENT_AMOUNT, REPORT_DATE, REPORT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('RPT20260601008', 'BX20260601008', '电话费报销', 'COMMUNICATION', 'PENDING', 'USER006', '周八', 'DEPT005', '财务部', 'PROJ006', '财务数字化', 580.00, 0.00, TO_DATE('2026-06-08','YYYY-MM-DD'), '6月工作电话费', NULL, NULL, NULL, NULL, 'UNPAID', NULL, NULL, SYSDATE, 'USER006', SYSDATE, 'USER006', '待审批');

INSERT INTO TBL_EXPENSE_REPORT (REPORT_ID, REPORT_CODE, REPORT_TITLE, REPORT_TYPE, REPORT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, PROJECT_ID, PROJECT_NAME, TOTAL_AMOUNT, PAYMENT_AMOUNT, REPORT_DATE, REPORT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('RPT20260601009', 'BX20260601009', '住宿费报销', 'ACCOMMODATION', 'PAID', 'USER001', '张三', 'DEPT001', '销售部', 'PROJ001', '华北销售项目', 2100.00, 2100.00, TO_DATE('2026-06-09','YYYY-MM-DD'), '客户拜访住宿', 'APV001', '王经理', TO_DATE('2026-06-10 10:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', 'PAID', TO_DATE('2026-06-11 14:00:00','YYYY-MM-DD HH24:MI:SS'), 'PAY20260601004', SYSDATE, 'USER001', SYSDATE, 'USER001', '3晚酒店');

INSERT INTO TBL_EXPENSE_REPORT (REPORT_ID, REPORT_CODE, REPORT_TITLE, REPORT_TYPE, REPORT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, PROJECT_ID, PROJECT_NAME, TOTAL_AMOUNT, PAYMENT_AMOUNT, REPORT_DATE, REPORT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('RPT20260601010', 'BX20260601010', '快递费报销', 'EXPRESS', 'DRAFT', 'USER007', '吴九', 'DEPT004', '管理部', 'PROJ005', '管理优化项目', 180.00, 0.00, TO_DATE('2026-06-10','YYYY-MM-DD'), '文件快递费用', NULL, NULL, NULL, NULL, 'UNPAID', NULL, NULL, SYSDATE, 'USER007', SYSDATE, 'USER007', '草稿状态');

-- =====================================================
-- 6. TBL_LOAN_APPLICATION 测试数据 (10条)
-- =====================================================

INSERT INTO TBL_LOAN_APPLICATION (LOAN_ID, LOAN_CODE, LOAN_TITLE, LOAN_TYPE, LOAN_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, LOAN_AMOUNT, LOAN_DATE, LOAN_REASON, EXPECT_RETURN_DATE, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, DISBURSE_STATUS, DISBURSE_TIME, DISBURSE_VOUCHER_NO, RETURN_STATUS, RETURNED_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('LOAN20260601001', 'JK20260601001', '差旅借款', 'TRAVEL', 'DISBURSED', 'USER001', '张三', 'DEPT001', '销售部', 5000.00, TO_DATE('2026-06-01','YYYY-MM-DD'), '上海出差预借款', TO_DATE('2026-06-15','YYYY-MM-DD'), 'APV001', '王经理', TO_DATE('2026-06-01 16:00:00','YYYY-MM-DD HH24:MI:SS'), '同意借款', 'DISBURSED', TO_DATE('2026-06-02 09:00:00','YYYY-MM-DD HH24:MI:SS'), 'DIS20260601001', 'UNRETURNED', 0.00, SYSDATE, 'USER001', SYSDATE, 'USER001', '待归还');

INSERT INTO TBL_LOAN_APPLICATION (LOAN_ID, LOAN_CODE, LOAN_TITLE, LOAN_TYPE, LOAN_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, LOAN_AMOUNT, LOAN_DATE, LOAN_REASON, EXPECT_RETURN_DATE, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, DISBURSE_STATUS, DISBURSE_TIME, DISBURSE_VOUCHER_NO, RETURN_STATUS, RETURNED_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('LOAN20260601002', 'JK20260601002', '业务借款', 'BUSINESS', 'DISBURSED', 'USER002', '李四', 'DEPT002', '技术部', 8000.00, TO_DATE('2026-06-02','YYYY-MM-DD'), '设备采购预借款', TO_DATE('2026-07-02','YYYY-MM-DD'), 'APV001', '王经理', TO_DATE('2026-06-02 11:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', 'DISBURSED', TO_DATE('2026-06-03 10:00:00','YYYY-MM-DD HH24:MI:SS'), 'DIS20260601002', 'PARTIAL', 3000.00, SYSDATE, 'USER002', SYSDATE, 'USER002', '部分归还');

INSERT INTO TBL_LOAN_APPLICATION (LOAN_ID, LOAN_CODE, LOAN_TITLE, LOAN_TYPE, LOAN_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, LOAN_AMOUNT, LOAN_DATE, LOAN_REASON, EXPECT_RETURN_DATE, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, DISBURSE_STATUS, DISBURSE_TIME, DISBURSE_VOUCHER_NO, RETURN_STATUS, RETURNED_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('LOAN20260601003', 'JK20260601003', '紧急借款', 'EMERGENCY', 'APPROVED', 'USER003', '王五', 'DEPT003', '市场部', 3000.00, TO_DATE('2026-06-03','YYYY-MM-DD'), '临时市场活动经费', TO_DATE('2026-06-20','YYYY-MM-DD'), 'APV002', '刘总监', TO_DATE('2026-06-03 15:00:00','YYYY-MM-DD HH24:MI:SS'), '同意，尽快放款', 'UNDISBURSED', NULL, NULL, 'UNRETURNED', 0.00, SYSDATE, 'USER003', SYSDATE, 'USER003', '已审批未放款');

INSERT INTO TBL_LOAN_APPLICATION (LOAN_ID, LOAN_CODE, LOAN_TITLE, LOAN_TYPE, LOAN_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, LOAN_AMOUNT, LOAN_DATE, LOAN_REASON, EXPECT_RETURN_DATE, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, DISBURSE_STATUS, DISBURSE_TIME, DISBURSE_VOUCHER_NO, RETURN_STATUS, RETURNED_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('LOAN20260601004', 'JK20260601004', '差旅借款', 'TRAVEL', 'RETURNED', 'USER004', '赵六', 'DEPT002', '技术部', 4500.00, TO_DATE('2026-05-15','YYYY-MM-DD'), '深圳技术交流', TO_DATE('2026-05-30','YYYY-MM-DD'), 'APV001', '王经理', TO_DATE('2026-05-15 10:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', 'DISBURSED', TO_DATE('2026-05-16 09:00:00','YYYY-MM-DD HH24:MI:SS'), 'DIS20260601003', 'RETURNED', 4500.00, SYSDATE, 'USER004', SYSDATE, 'USER004', '已全额归还');

INSERT INTO TBL_LOAN_APPLICATION (LOAN_ID, LOAN_CODE, LOAN_TITLE, LOAN_TYPE, LOAN_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, LOAN_AMOUNT, LOAN_DATE, LOAN_REASON, EXPECT_RETURN_DATE, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, DISBURSE_STATUS, DISBURSE_TIME, DISBURSE_VOUCHER_NO, RETURN_STATUS, RETURNED_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('LOAN20260601005', 'JK20260601005', '业务借款', 'BUSINESS', 'DISBURSED', 'USER005', '孙七', 'DEPT004', '管理部', 12000.00, TO_DATE('2026-06-05','YYYY-MM-DD'), '办公设备批量采购', TO_DATE('2026-08-05','YYYY-MM-DD'), 'APV002', '刘总监', TO_DATE('2026-06-05 14:00:00','YYYY-MM-DD HH24:MI:SS'), '同意，大额借款需跟踪', 'DISBURSED', TO_DATE('2026-06-06 10:00:00','YYYY-MM-DD HH24:MI:SS'), 'DIS20260601004', 'UNRETURNED', 0.00, SYSDATE, 'USER005', SYSDATE, 'USER005', '待归还');

INSERT INTO TBL_LOAN_APPLICATION (LOAN_ID, LOAN_CODE, LOAN_TITLE, LOAN_TYPE, LOAN_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, LOAN_AMOUNT, LOAN_DATE, LOAN_REASON, EXPECT_RETURN_DATE, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, DISBURSE_STATUS, DISBURSE_TIME, DISBURSE_VOUCHER_NO, RETURN_STATUS, RETURNED_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('LOAN20260601006', 'JK20260601006', '其他借款', 'OTHER', 'PENDING', 'USER006', '周八', 'DEPT005', '财务部', 2000.00, TO_DATE('2026-06-06','YYYY-MM-DD'), '临时备用金', TO_DATE('2026-06-30','YYYY-MM-DD'), NULL, NULL, NULL, NULL, 'UNDISBURSED', NULL, NULL, 'UNRETURNED', 0.00, SYSDATE, 'USER006', SYSDATE, 'USER006', '审批中');

INSERT INTO TBL_LOAN_APPLICATION (LOAN_ID, LOAN_CODE, LOAN_TITLE, LOAN_TYPE, LOAN_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, LOAN_AMOUNT, LOAN_DATE, LOAN_REASON, EXPECT_RETURN_DATE, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, DISBURSE_STATUS, DISBURSE_TIME, DISBURSE_VOUCHER_NO, RETURN_STATUS, RETURNED_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('LOAN20260601007', 'JK20260601007', '差旅借款', 'TRAVEL', 'DISBURSED', 'USER001', '张三', 'DEPT001', '销售部', 6000.00, TO_DATE('2026-06-07','YYYY-MM-DD'), '广州客户拜访', TO_DATE('2026-06-25','YYYY-MM-DD'), 'APV001', '王经理', TO_DATE('2026-06-07 09:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', 'DISBURSED', TO_DATE('2026-06-08 10:00:00','YYYY-MM-DD HH24:MI:SS'), 'DIS20260601005', 'UNRETURNED', 0.00, SYSDATE, 'USER001', SYSDATE, 'USER001', '待归还');

INSERT INTO TBL_LOAN_APPLICATION (LOAN_ID, LOAN_CODE, LOAN_TITLE, LOAN_TYPE, LOAN_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, LOAN_AMOUNT, LOAN_DATE, LOAN_REASON, EXPECT_RETURN_DATE, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, DISBURSE_STATUS, DISBURSE_TIME, DISBURSE_VOUCHER_NO, RETURN_STATUS, RETURNED_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('LOAN20260601008', 'JK20260601008', '业务借款', 'BUSINESS', 'REJECTED', 'USER007', '吴九', 'DEPT004', '管理部', 15000.00, TO_DATE('2026-06-08','YYYY-MM-DD'), '装修预付款', TO_DATE('2026-09-08','YYYY-MM-DD'), 'APV002', '刘总监', TO_DATE('2026-06-09 16:00:00','YYYY-MM-DD HH24:MI:SS'), '金额过大，需重新申请', 'UNDISBURSED', NULL, NULL, 'UNRETURNED', 0.00, SYSDATE, 'USER007', SYSDATE, 'USER007', '已驳回');

INSERT INTO TBL_LOAN_APPLICATION (LOAN_ID, LOAN_CODE, LOAN_TITLE, LOAN_TYPE, LOAN_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, LOAN_AMOUNT, LOAN_DATE, LOAN_REASON, EXPECT_RETURN_DATE, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, DISBURSE_STATUS, DISBURSE_TIME, DISBURSE_VOUCHER_NO, RETURN_STATUS, RETURNED_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('LOAN20260601009', 'JK20260601009', '紧急借款', 'EMERGENCY', 'DISBURSED', 'USER003', '王五', 'DEPT003', '市场部', 2500.00, TO_DATE('2026-06-09','YYYY-MM-DD'), '展会现场急需', TO_DATE('2026-06-16','YYYY-MM-DD'), 'APV001', '王经理', TO_DATE('2026-06-09 12:00:00','YYYY-MM-DD HH24:MI:SS'), '同意，紧急放款', 'DISBURSED', TO_DATE('2026-06-09 14:00:00','YYYY-MM-DD HH24:MI:SS'), 'DIS20260601006', 'RETURNED', 2500.00, SYSDATE, 'USER003', SYSDATE, 'USER003', '已全额归还');

INSERT INTO TBL_LOAN_APPLICATION (LOAN_ID, LOAN_CODE, LOAN_TITLE, LOAN_TYPE, LOAN_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, LOAN_AMOUNT, LOAN_DATE, LOAN_REASON, EXPECT_RETURN_DATE, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, DISBURSE_STATUS, DISBURSE_TIME, DISBURSE_VOUCHER_NO, RETURN_STATUS, RETURNED_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('LOAN20260601010', 'JK20260601010', '差旅借款', 'TRAVEL', 'DRAFT', 'USER008', '郑十', 'DEPT002', '技术部', 3500.00, TO_DATE('2026-06-10','YYYY-MM-DD'), '杭州技术大会', TO_DATE('2026-06-20','YYYY-MM-DD'), NULL, NULL, NULL, NULL, 'UNDISBURSED', NULL, NULL, 'UNRETURNED', 0.00, SYSDATE, 'USER008', SYSDATE, 'USER008', '草稿');

-- =====================================================
-- 7. TBL_PREPAYMENT 测试数据 (10条)
-- =====================================================

INSERT INTO TBL_PREPAYMENT (PREPAYMENT_ID, PREPAYMENT_CODE, PREPAYMENT_TITLE, PREPAYMENT_TYPE, PREPAYMENT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_ID, CONTRACT_CODE, PREPAYMENT_AMOUNT, PREPAYMENT_DATE, PREPAYMENT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, WRITEOFF_STATUS, WRITEOFF_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('PREPAY20260601001', 'YF20260601001', '服务器采购预付款', 'PURCHASE', 'PAID', 'USER002', '李四', 'DEPT002', '技术部', 'SUP001', '华为技术有限公司', 'CON20260601001', 'HT20260601001', 50000.00, TO_DATE('2026-06-01','YYYY-MM-DD'), '服务器设备采购预付款', 'APV002', '刘总监', TO_DATE('2026-06-01 10:00:00','YYYY-MM-DD HH24:MI:SS'), '同意预付', 'PAID', TO_DATE('2026-06-02 09:00:00','YYYY-MM-DD HH24:MI:SS'), 'PAY20260601005', 'UNWRITEOFF', 0.00, SYSDATE, 'USER002', SYSDATE, 'USER002', '待核销');

INSERT INTO TBL_PREPAYMENT (PREPAYMENT_ID, PREPAYMENT_CODE, PREPAYMENT_TITLE, PREPAYMENT_TYPE, PREPAYMENT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_ID, CONTRACT_CODE, PREPAYMENT_AMOUNT, PREPAYMENT_DATE, PREPAYMENT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, WRITEOFF_STATUS, WRITEOFF_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('PREPAY20260601002', 'YF20260601002', '云服务预付款', 'SERVICE', 'PAID', 'USER002', '李四', 'DEPT002', '技术部', 'SUP002', '阿里云', 'CON20260601002', 'HT20260601002', 24000.00, TO_DATE('2026-06-02','YYYY-MM-DD'), '年度云服务预付款', 'APV002', '刘总监', TO_DATE('2026-06-02 11:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', 'PAID', TO_DATE('2026-06-03 10:00:00','YYYY-MM-DD HH24:MI:SS'), 'PAY20260601006', 'PARTIAL', 12000.00, SYSDATE, 'USER002', SYSDATE, 'USER002', '部分核销');

INSERT INTO TBL_PREPAYMENT (PREPAYMENT_ID, PREPAYMENT_CODE, PREPAYMENT_TITLE, PREPAYMENT_TYPE, PREPAYMENT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_ID, CONTRACT_CODE, PREPAYMENT_AMOUNT, PREPAYMENT_DATE, PREPAYMENT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, WRITEOFF_STATUS, WRITEOFF_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('PREPAY20260601003', 'YF20260601003', '办公室租金预付款', 'RENT', 'APPROVED', 'USER005', '孙七', 'DEPT004', '管理部', 'SUP003', '万科物业', 'CON20260601003', 'HT20260601003', 36000.00, TO_DATE('2026-06-03','YYYY-MM-DD'), 'Q3办公室租金', 'APV002', '刘总监', TO_DATE('2026-06-03 14:00:00','YYYY-MM-DD HH24:MI:SS'), '同意预付', 'UNPAID', NULL, NULL, 'UNWRITEOFF', 0.00, SYSDATE, 'USER005', SYSDATE, 'USER005', '已审批待支付');

INSERT INTO TBL_PREPAYMENT (PREPAYMENT_ID, PREPAYMENT_CODE, PREPAYMENT_TITLE, PREPAYMENT_TYPE, PREPAYMENT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_ID, CONTRACT_CODE, PREPAYMENT_AMOUNT, PREPAYMENT_DATE, PREPAYMENT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, WRITEOFF_STATUS, WRITEOFF_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('PREPAY20260601004', 'YF20260601004', '培训服务预付款', 'SERVICE', 'PAID', 'USER004', '赵六', 'DEPT002', '技术部', 'SUP004', '极客时间', 'CON20260601004', 'HT20260601004', 8000.00, TO_DATE('2026-06-04','YYYY-MM-DD'), '团队技术培训预付款', 'APV001', '王经理', TO_DATE('2026-06-04 10:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', 'PAID', TO_DATE('2026-06-05 09:00:00','YYYY-MM-DD HH24:MI:SS'), 'PAY20260601007', 'WRITEOFF', 8000.00, SYSDATE, 'USER004', SYSDATE, 'USER004', '已全额核销');

INSERT INTO TBL_PREPAYMENT (PREPAYMENT_ID, PREPAYMENT_CODE, PREPAYMENT_TITLE, PREPAYMENT_TYPE, PREPAYMENT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_ID, CONTRACT_CODE, PREPAYMENT_AMOUNT, PREPAYMENT_DATE, PREPAYMENT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, WRITEOFF_STATUS, WRITEOFF_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('PREPAY20260601005', 'YF20260601005', '软件采购预付款', 'PURCHASE', 'PAID', 'USER002', '李四', 'DEPT002', '技术部', 'SUP005', 'Oracle中国', 'CON20260601005', 'HT20260601005', 120000.00, TO_DATE('2026-06-05','YYYY-MM-DD'), '数据库许可预付款', 'APV003', '张总', TO_DATE('2026-06-05 16:00:00','YYYY-MM-DD HH24:MI:SS'), '同意，大额预付需谨慎', 'PAID', TO_DATE('2026-06-08 09:00:00','YYYY-MM-DD HH24:MI:SS'), 'PAY20260601008', 'UNWRITEOFF', 0.00, SYSDATE, 'USER002', SYSDATE, 'USER002', '待核销');

INSERT INTO TBL_PREPAYMENT (PREPAYMENT_ID, PREPAYMENT_CODE, PREPAYMENT_TITLE, PREPAYMENT_TYPE, PREPAYMENT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_ID, CONTRACT_CODE, PREPAYMENT_AMOUNT, PREPAYMENT_DATE, PREPAYMENT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, WRITEOFF_STATUS, WRITEOFF_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('PREPAY20260601006', 'YF20260601006', '广告费预付款', 'OTHER', 'PENDING', 'USER003', '王五', 'DEPT003', '市场部', 'SUP006', '分众传媒', 'CON20260601006', 'HT20260601006', 50000.00, TO_DATE('2026-06-06','YYYY-MM-DD'), '电梯广告投放预付款', NULL, NULL, NULL, NULL, 'UNPAID', NULL, NULL, 'UNWRITEOFF', 0.00, SYSDATE, 'USER003', SYSDATE, 'USER003', '审批中');

INSERT INTO TBL_PREPAYMENT (PREPAYMENT_ID, PREPAYMENT_CODE, PREPAYMENT_TITLE, PREPAYMENT_TYPE, PREPAYMENT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_ID, CONTRACT_CODE, PREPAYMENT_AMOUNT, PREPAYMENT_DATE, PREPAYMENT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, WRITEOFF_STATUS, WRITEOFF_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('PREPAY20260601007', 'YF20260601007', '咨询费预付款', 'SERVICE', 'PAID', 'USER005', '孙七', 'DEPT004', '管理部', 'SUP007', '麦肯锡咨询', 'CON20260601007', 'HT20260601007', 150000.00, TO_DATE('2026-06-07','YYYY-MM-DD'), '管理咨询项目预付款', 'APV003', '张总', TO_DATE('2026-06-07 10:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', 'PAID', TO_DATE('2026-06-09 09:00:00','YYYY-MM-DD HH24:MI:SS'), 'PAY20260601009', 'UNWRITEOFF', 0.00, SYSDATE, 'USER005', SYSDATE, 'USER005', '待核销');

INSERT INTO TBL_PREPAYMENT (PREPAYMENT_ID, PREPAYMENT_CODE, PREPAYMENT_TITLE, PREPAYMENT_TYPE, PREPAYMENT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_ID, CONTRACT_CODE, PREPAYMENT_AMOUNT, PREPAYMENT_DATE, PREPAYMENT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, WRITEOFF_STATUS, WRITEOFF_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('PREPAY20260601008', 'YF20260601008', '设备维护预付款', 'PURCHASE', 'REJECTED', 'USER004', '赵六', 'DEPT002', '技术部', 'SUP008', 'IBM服务', 'CON20260601008', 'HT20260601008', 30000.00, TO_DATE('2026-06-08','YYYY-MM-DD'), '服务器维保预付款', 'APV002', '刘总监', TO_DATE('2026-06-09 16:00:00','YYYY-MM-DD HH24:MI:SS'), '合同条款需重新确认', 'UNPAID', NULL, NULL, 'UNWRITEOFF', 0.00, SYSDATE, 'USER004', SYSDATE, 'USER004', '已驳回');

INSERT INTO TBL_PREPAYMENT (PREPAYMENT_ID, PREPAYMENT_CODE, PREPAYMENT_TITLE, PREPAYMENT_TYPE, PREPAYMENT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_ID, CONTRACT_CODE, PREPAYMENT_AMOUNT, PREPAYMENT_DATE, PREPAYMENT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, WRITEOFF_STATUS, WRITEOFF_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('PREPAY20260601009', 'YF20260601009', '租金预付款', 'RENT', 'PAID', 'USER005', '孙七', 'DEPT004', '管理部', 'SUP003', '万科物业', 'CON20260601009', 'HT20260601009', 24000.00, TO_DATE('2026-06-09','YYYY-MM-DD'), 'Q2租金尾款', 'APV001', '王经理', TO_DATE('2026-06-09 11:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', 'PAID', TO_DATE('2026-06-10 10:00:00','YYYY-MM-DD HH24:MI:SS'), 'PAY20260601010', 'WRITEOFF', 24000.00, SYSDATE, 'USER005', SYSDATE, 'USER005', '已全额核销');

INSERT INTO TBL_PREPAYMENT (PREPAYMENT_ID, PREPAYMENT_CODE, PREPAYMENT_TITLE, PREPAYMENT_TYPE, PREPAYMENT_STATUS, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_ID, CONTRACT_CODE, PREPAYMENT_AMOUNT, PREPAYMENT_DATE, PREPAYMENT_REASON, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, PAYMENT_STATUS, PAYMENT_TIME, PAYMENT_VOUCHER_NO, WRITEOFF_STATUS, WRITEOFF_AMOUNT, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('PREPAY20260601010', 'YF20260601010', '其他预付款', 'OTHER', 'DRAFT', 'USER006', '周八', 'DEPT005', '财务部', 'SUP009', '顺丰速运', NULL, NULL, 5000.00, TO_DATE('2026-06-10','YYYY-MM-DD'), '物流预付款', NULL, NULL, NULL, NULL, 'UNPAID', NULL, NULL, 'UNWRITEOFF', 0.00, SYSDATE, 'USER006', SYSDATE, 'USER006', '草稿');

-- =====================================================
-- 8. TBL_CONTRACT 测试数据 (10条)
-- =====================================================

INSERT INTO TBL_CONTRACT (CONTRACT_ID, CONTRACT_CODE, CONTRACT_NAME, CONTRACT_TYPE, CONTRACT_STATUS, PARTY_A, PARTY_B, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_AMOUNT, SIGNED_DATE, START_DATE, END_DATE, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, CONTRACT_CONTENT, ATTACHMENT_URL, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('CON20260601001', 'HT20260601001', '服务器采购合同', 'PURCHASE', 'EXECUTING', '本公司', '华为技术有限公司', 'SUP001', '华为技术有限公司', 250000.00, TO_DATE('2026-01-15','YYYY-MM-DD'), TO_DATE('2026-01-15','YYYY-MM-DD'), TO_DATE('2026-12-31','YYYY-MM-DD'), 'USER002', '李四', 'DEPT002', '技术部', 'APV003', '张总', TO_DATE('2026-01-10 10:00:00','YYYY-MM-DD HH24:MI:SS'), '同意签署', '服务器设备采购合同正文', '/api/files/contracts/HT20260601001.pdf', SYSDATE, 'USER002', SYSDATE, 'USER002', '执行中');

INSERT INTO TBL_CONTRACT (CONTRACT_ID, CONTRACT_CODE, CONTRACT_NAME, CONTRACT_TYPE, CONTRACT_STATUS, PARTY_A, PARTY_B, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_AMOUNT, SIGNED_DATE, START_DATE, END_DATE, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, CONTRACT_CONTENT, ATTACHMENT_URL, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('CON20260601002', 'HT20260601002', '云服务年度合同', 'SERVICE', 'EXECUTING', '本公司', '阿里云', 'SUP002', '阿里云', 120000.00, TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2026-12-31','YYYY-MM-DD'), 'USER002', '李四', 'DEPT002', '技术部', 'APV003', '张总', TO_DATE('2025-12-25 14:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', '云服务年度框架合同', '/api/files/contracts/HT20260601002.pdf', SYSDATE, 'USER002', SYSDATE, 'USER002', '执行中');

INSERT INTO TBL_CONTRACT (CONTRACT_ID, CONTRACT_CODE, CONTRACT_NAME, CONTRACT_TYPE, CONTRACT_STATUS, PARTY_A, PARTY_B, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_AMOUNT, SIGNED_DATE, START_DATE, END_DATE, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, CONTRACT_CONTENT, ATTACHMENT_URL, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('CON20260601003', 'HT20260601003', '办公室租赁合同', 'OTHER', 'EXECUTING', '本公司', '万科物业', 'SUP003', '万科物业', 144000.00, TO_DATE('2026-04-01','YYYY-MM-DD'), TO_DATE('2026-04-01','YYYY-MM-DD'), TO_DATE('2027-03-31','YYYY-MM-DD'), 'USER005', '孙七', 'DEPT004', '管理部', 'APV003', '张总', TO_DATE('2026-03-20 10:00:00','YYYY-MM-DD HH24:MI:SS'), '同意签署', '办公室租赁协议', '/api/files/contracts/HT20260601003.pdf', SYSDATE, 'USER005', SYSDATE, 'USER005', '执行中');

INSERT INTO TBL_CONTRACT (CONTRACT_ID, CONTRACT_CODE, CONTRACT_NAME, CONTRACT_TYPE, CONTRACT_STATUS, PARTY_A, PARTY_B, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_AMOUNT, SIGNED_DATE, START_DATE, END_DATE, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, CONTRACT_CONTENT, ATTACHMENT_URL, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('CON20260601004', 'HT20260601004', '培训服务合同', 'SERVICE', 'COMPLETED', '本公司', '极客时间', 'SUP004', '极客时间', 20000.00, TO_DATE('2026-01-10','YYYY-MM-DD'), TO_DATE('2026-01-10','YYYY-MM-DD'), TO_DATE('2026-06-10','YYYY-MM-DD'), 'USER004', '赵六', 'DEPT002', '技术部', 'APV001', '王经理', TO_DATE('2026-01-05 11:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', '技术培训服务合同', '/api/files/contracts/HT20260601004.pdf', SYSDATE, 'USER004', SYSDATE, 'USER004', '已完成');

INSERT INTO TBL_CONTRACT (CONTRACT_ID, CONTRACT_CODE, CONTRACT_NAME, CONTRACT_TYPE, CONTRACT_STATUS, PARTY_A, PARTY_B, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_AMOUNT, SIGNED_DATE, START_DATE, END_DATE, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, CONTRACT_CONTENT, ATTACHMENT_URL, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('CON20260601005', 'HT20260601005', '数据库许可合同', 'PURCHASE', 'EXECUTING', '本公司', 'Oracle中国', 'SUP005', 'Oracle中国', 600000.00, TO_DATE('2026-02-01','YYYY-MM-DD'), TO_DATE('2026-02-01','YYYY-MM-DD'), TO_DATE('2027-01-31','YYYY-MM-DD'), 'USER002', '李四', 'DEPT002', '技术部', 'APV003', '张总', TO_DATE('2026-01-25 16:00:00','YYYY-MM-DD HH24:MI:SS'), '同意，注意合规', 'Oracle数据库许可协议', '/api/files/contracts/HT20260601005.pdf', SYSDATE, 'USER002', SYSDATE, 'USER002', '执行中');

INSERT INTO TBL_CONTRACT (CONTRACT_ID, CONTRACT_CODE, CONTRACT_NAME, CONTRACT_TYPE, CONTRACT_STATUS, PARTY_A, PARTY_B, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_AMOUNT, SIGNED_DATE, START_DATE, END_DATE, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, CONTRACT_CONTENT, ATTACHMENT_URL, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('CON20260601006', 'HT20260601006', '广告投放合同', 'SALES', 'APPROVED', '本公司', '分众传媒', 'SUP006', '分众传媒', 200000.00, TO_DATE('2026-06-15','YYYY-MM-DD'), TO_DATE('2026-06-15','YYYY-MM-DD'), TO_DATE('2026-12-31','YYYY-MM-DD'), 'USER003', '王五', 'DEPT003', '市场部', 'APV003', '张总', TO_DATE('2026-06-10 10:00:00','YYYY-MM-DD HH24:MI:SS'), '同意签署', '电梯广告投放协议', '/api/files/contracts/HT20260601006.pdf', SYSDATE, 'USER003', SYSDATE, 'USER003', '已审批待执行');

INSERT INTO TBL_CONTRACT (CONTRACT_ID, CONTRACT_CODE, CONTRACT_NAME, CONTRACT_TYPE, CONTRACT_STATUS, PARTY_A, PARTY_B, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_AMOUNT, SIGNED_DATE, START_DATE, END_DATE, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, CONTRACT_CONTENT, ATTACHMENT_URL, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('CON20260601007', 'HT20260601007', '管理咨询合同', 'SERVICE', 'EXECUTING', '本公司', '麦肯锡咨询', 'SUP007', '麦肯锡咨询', 500000.00, TO_DATE('2026-03-01','YYYY-MM-DD'), TO_DATE('2026-03-01','YYYY-MM-DD'), TO_DATE('2026-09-30','YYYY-MM-DD'), 'USER005', '孙七', 'DEPT004', '管理部', 'APV003', '张总', TO_DATE('2026-02-20 14:00:00','YYYY-MM-DD HH24:MI:SS'), '同意，分阶段付款', '管理咨询项目合同', '/api/files/contracts/HT20260601007.pdf', SYSDATE, 'USER005', SYSDATE, 'USER005', '执行中');

INSERT INTO TBL_CONTRACT (CONTRACT_ID, CONTRACT_CODE, CONTRACT_NAME, CONTRACT_TYPE, CONTRACT_STATUS, PARTY_A, PARTY_B, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_AMOUNT, SIGNED_DATE, START_DATE, END_DATE, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, CONTRACT_CONTENT, ATTACHMENT_URL, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('CON20260601008', 'HT20260601008', '服务器维保合同', 'PURCHASE', 'REJECTED', '本公司', 'IBM服务', 'SUP008', 'IBM服务', 150000.00, NULL, NULL, NULL, 'USER004', '赵六', 'DEPT002', '技术部', 'APV002', '刘总监', TO_DATE('2026-06-09 16:00:00','YYYY-MM-DD HH24:MI:SS'), '合同条款需重新确认', NULL, NULL, SYSDATE, 'USER004', SYSDATE, 'USER004', '已驳回');

INSERT INTO TBL_CONTRACT (CONTRACT_ID, CONTRACT_CODE, CONTRACT_NAME, CONTRACT_TYPE, CONTRACT_STATUS, PARTY_A, PARTY_B, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_AMOUNT, SIGNED_DATE, START_DATE, END_DATE, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, CONTRACT_CONTENT, ATTACHMENT_URL, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('CON20260601009', 'HT20260601009', 'Q2租金合同', 'OTHER', 'COMPLETED', '本公司', '万科物业', 'SUP003', '万科物业', 72000.00, TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2026-01-01','YYYY-MM-DD'), TO_DATE('2026-03-31','YYYY-MM-DD'), 'USER005', '孙七', 'DEPT004', '管理部', 'APV001', '王经理', TO_DATE('2025-12-20 10:00:00','YYYY-MM-DD HH24:MI:SS'), '同意', 'Q2办公室租赁协议', '/api/files/contracts/HT20260601009.pdf', SYSDATE, 'USER005', SYSDATE, 'USER005', '已完成');

INSERT INTO TBL_CONTRACT (CONTRACT_ID, CONTRACT_CODE, CONTRACT_NAME, CONTRACT_TYPE, CONTRACT_STATUS, PARTY_A, PARTY_B, SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_AMOUNT, SIGNED_DATE, START_DATE, END_DATE, APPLICANT_ID, APPLICANT_NAME, APPLICANT_DEPT_ID, APPLICANT_DEPT_NAME, APPROVER_ID, APPROVER_NAME, APPROVE_TIME, APPROVE_OPINION, CONTRACT_CONTENT, ATTACHMENT_URL, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('CON20260601010', 'HT20260601010', '销售代理合同', 'SALES', 'EXECUTING', '本公司', '渠道代理商A', 'SUP010', '渠道代理商A', 300000.00, TO_DATE('2026-05-01','YYYY-MM-DD'), TO_DATE('2026-05-01','YYYY-MM-DD'), TO_DATE('2026-12-31','YYYY-MM-DD'), 'USER003', '王五', 'DEPT003', '市场部', 'APV003', '张总', TO_DATE('2026-04-25 11:00:00','YYYY-MM-DD HH24:MI:SS'), '同意签署', '销售代理合作协议', '/api/files/contracts/HT20260601010.pdf', SYSDATE, 'USER003', SYSDATE, 'USER003', '执行中');

-- =====================================================
-- 9. 验证数据插入
-- =====================================================
SELECT 'TBL_EXPENSE_REPORT' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM TBL_EXPENSE_REPORT
UNION ALL
SELECT 'TBL_LOAN_APPLICATION' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM TBL_LOAN_APPLICATION
UNION ALL
SELECT 'TBL_PREPAYMENT' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM TBL_PREPAYMENT
UNION ALL
SELECT 'TBL_CONTRACT' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM TBL_CONTRACT;

COMMIT;
