-- =====================================================
-- 财务共享系统 - 费用项目表建表及测试数据
-- 创建日期：2026-06-16
-- 数据库：达梦(DM)
-- =====================================================

CREATE TABLE IF NOT EXISTS TBL_EXPENSE_ITEM (
    ITEM_ID      VARCHAR2(50)   NOT NULL PRIMARY KEY,
    ITEM_CODE    VARCHAR2(50),
    ITEM_NAME    VARCHAR2(100),
    PARENT_ID    VARCHAR2(50),
    ITEM_LEVEL   NUMBER(2),
    SORT_ORDER   NUMBER(5),
    IS_ENABLED   NUMBER(1)      DEFAULT 1,
    CREATE_TIME  TIMESTAMP      DEFAULT SYSDATE,
    CREATE_USER  VARCHAR2(50),
    UPDATE_TIME  TIMESTAMP      DEFAULT SYSDATE,
    UPDATE_USER  VARCHAR2(50),
    REMARK       VARCHAR2(500)
);

COMMENT ON TABLE  TBL_EXPENSE_ITEM                  IS '费用项目表';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.ITEM_ID          IS '费用项目ID';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.ITEM_CODE        IS '费用项目编码';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.ITEM_NAME        IS '费用项目名称';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.PARENT_ID        IS '父级ID';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.ITEM_LEVEL       IS '层级';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.SORT_ORDER       IS '排序号';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.IS_ENABLED       IS '是否启用(0-禁用,1-启用)';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.CREATE_TIME      IS '创建时间';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.CREATE_USER      IS '创建人';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.UPDATE_TIME      IS '更新时间';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.UPDATE_USER      IS '更新人';
COMMENT ON COLUMN TBL_EXPENSE_ITEM.REMARK           IS '备注';

-- =====================================================
-- 测试数据 (10条)
-- =====================================================

INSERT INTO TBL_EXPENSE_ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, PARENT_ID, ITEM_LEVEL, SORT_ORDER, IS_ENABLED, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('ITEM001', '0101', '机票', NULL, 1, 1, 1, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM', '差旅交通费-机票');

INSERT INTO TBL_EXPENSE_ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, PARENT_ID, ITEM_LEVEL, SORT_ORDER, IS_ENABLED, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('ITEM002', '0102', '火车票', NULL, 1, 2, 1, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM', '差旅交通费-火车票');

INSERT INTO TBL_EXPENSE_ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, PARENT_ID, ITEM_LEVEL, SORT_ORDER, IS_ENABLED, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('ITEM003', '0103', '出租车/网约车', NULL, 1, 3, 1, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM', '市内交通费');

INSERT INTO TBL_EXPENSE_ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, PARENT_ID, ITEM_LEVEL, SORT_ORDER, IS_ENABLED, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('ITEM004', '0201', '住宿费', NULL, 1, 4, 1, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM', '差旅住宿费');

INSERT INTO TBL_EXPENSE_ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, PARENT_ID, ITEM_LEVEL, SORT_ORDER, IS_ENABLED, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('ITEM005', '0202', '餐费', NULL, 1, 5, 1, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM', '差旅及业务招待餐费');

INSERT INTO TBL_EXPENSE_ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, PARENT_ID, ITEM_LEVEL, SORT_ORDER, IS_ENABLED, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('ITEM006', '0301', '办公用品', NULL, 1, 6, 1, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM', '日常办公用品采购');

INSERT INTO TBL_EXPENSE_ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, PARENT_ID, ITEM_LEVEL, SORT_ORDER, IS_ENABLED, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('ITEM007', '0302', '打印耗材', NULL, 1, 7, 1, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM', '打印纸、墨盒、硒鼓等');

INSERT INTO TBL_EXPENSE_ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, PARENT_ID, ITEM_LEVEL, SORT_ORDER, IS_ENABLED, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('ITEM008', '0401', '培训费', NULL, 1, 8, 1, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM', '外部培训课程费用');

INSERT INTO TBL_EXPENSE_ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, PARENT_ID, ITEM_LEVEL, SORT_ORDER, IS_ENABLED, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('ITEM009', '0402', '会议费', NULL, 1, 9, 1, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM', '外部会议参会费用');

INSERT INTO TBL_EXPENSE_ITEM (ITEM_ID, ITEM_CODE, ITEM_NAME, PARENT_ID, ITEM_LEVEL, SORT_ORDER, IS_ENABLED, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES ('ITEM010', '0501', '其他', NULL, 1, 10, 1, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM', '其他未分类费用');

-- 验证
SELECT 'TBL_EXPENSE_ITEM' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM TBL_EXPENSE_ITEM;

COMMIT;
