-- =====================================================
-- 财务共享系统 - 报销单费用明细表建表及测试数据
-- 创建日期：2026-06-16
-- 数据库：达梦(DM)
-- =====================================================

-- =====================================================
-- 1. 报销单费用明细表 TBL_EXPENSE_REPORT_DETAIL
-- =====================================================
CREATE TABLE IF NOT EXISTS TBL_EXPENSE_REPORT_DETAIL (
    DETAIL_ID           VARCHAR2(50)   NOT NULL PRIMARY KEY,
    REPORT_ID           VARCHAR2(50)   NOT NULL,
    EXPENSE_ITEM_ID     VARCHAR2(50),
    EXPENSE_ITEM_NAME   VARCHAR2(100),
    EXPENSE_AMOUNT      DECIMAL(18,2),
    EXPENSE_DATE        VARCHAR2(20),
    RECEIPT_COUNT       NUMBER(10),
    DESCRIPTION         VARCHAR2(500),
    CREATE_TIME         TIMESTAMP      DEFAULT SYSDATE,
    UPDATE_TIME         TIMESTAMP      DEFAULT SYSDATE
);

COMMENT ON TABLE  TBL_EXPENSE_REPORT_DETAIL                    IS '报销单费用明细表';
COMMENT ON COLUMN TBL_EXPENSE_REPORT_DETAIL.DETAIL_ID           IS '明细ID';
COMMENT ON COLUMN TBL_EXPENSE_REPORT_DETAIL.REPORT_ID           IS '报销单ID';
COMMENT ON COLUMN TBL_EXPENSE_REPORT_DETAIL.EXPENSE_ITEM_ID     IS '费用项目ID';
COMMENT ON COLUMN TBL_EXPENSE_REPORT_DETAIL.EXPENSE_ITEM_NAME   IS '费用项目名称';
COMMENT ON COLUMN TBL_EXPENSE_REPORT_DETAIL.EXPENSE_AMOUNT      IS '费用金额';
COMMENT ON COLUMN TBL_EXPENSE_REPORT_DETAIL.EXPENSE_DATE        IS '费用日期';
COMMENT ON COLUMN TBL_EXPENSE_REPORT_DETAIL.RECEIPT_COUNT       IS '发票数量';
COMMENT ON COLUMN TBL_EXPENSE_REPORT_DETAIL.DESCRIPTION         IS '费用说明';
COMMENT ON COLUMN TBL_EXPENSE_REPORT_DETAIL.CREATE_TIME         IS '创建时间';
COMMENT ON COLUMN TBL_EXPENSE_REPORT_DETAIL.UPDATE_TIME         IS '更新时间';

-- =====================================================
-- 2. 为现有报销单生成测试费用明细数据
-- =====================================================

-- 报销单1 (BX20260601001) - 差旅费明细
INSERT INTO TBL_EXPENSE_REPORT_DETAIL (DETAIL_ID, REPORT_ID, EXPENSE_ITEM_ID, EXPENSE_ITEM_NAME, EXPENSE_AMOUNT, EXPENSE_DATE, RECEIPT_COUNT, DESCRIPTION, CREATE_TIME)
SELECT 'DET20260616001', REPORT_ID, 'ITEM001', '交通费', 850.00, '2026-06-10', 2, '北京-上海往返高铁票', SYSDATE FROM TBL_EXPENSE_REPORT WHERE REPORT_CODE = 'BX20260601001';

INSERT INTO TBL_EXPENSE_REPORT_DETAIL (DETAIL_ID, REPORT_ID, EXPENSE_ITEM_ID, EXPENSE_ITEM_NAME, EXPENSE_AMOUNT, EXPENSE_DATE, RECEIPT_COUNT, DESCRIPTION, CREATE_TIME)
SELECT 'DET20260616002', REPORT_ID, 'ITEM002', '住宿费', 1200.00, '2026-06-10', 1, '上海酒店住宿2晚', SYSDATE FROM TBL_EXPENSE_REPORT WHERE REPORT_CODE = 'BX20260601001';

INSERT INTO TBL_EXPENSE_REPORT_DETAIL (DETAIL_ID, REPORT_ID, EXPENSE_ITEM_ID, EXPENSE_ITEM_NAME, EXPENSE_AMOUNT, EXPENSE_DATE, RECEIPT_COUNT, DESCRIPTION, CREATE_TIME)
SELECT 'DET20260616003', REPORT_ID, 'ITEM003', '餐饮费', 350.00, '2026-06-11', 3, '出差期间工作餐', SYSDATE FROM TBL_EXPENSE_REPORT WHERE REPORT_CODE = 'BX20260601001';

-- 报销单2 (BX20260601002) - 办公费明细
INSERT INTO TBL_EXPENSE_REPORT_DETAIL (DETAIL_ID, REPORT_ID, EXPENSE_ITEM_ID, EXPENSE_ITEM_NAME, EXPENSE_AMOUNT, EXPENSE_DATE, RECEIPT_COUNT, DESCRIPTION, CREATE_TIME)
SELECT 'DET20260616004', REPORT_ID, 'ITEM004', '办公用品', 256.50, '2026-06-12', 1, '打印纸、墨盒等办公耗材', SYSDATE FROM TBL_EXPENSE_REPORT WHERE REPORT_CODE = 'BX20260601002';

INSERT INTO TBL_EXPENSE_REPORT_DETAIL (DETAIL_ID, REPORT_ID, EXPENSE_ITEM_ID, EXPENSE_ITEM_NAME, EXPENSE_AMOUNT, EXPENSE_DATE, RECEIPT_COUNT, DESCRIPTION, CREATE_TIME)
SELECT 'DET20260616005', REPORT_ID, 'ITEM005', '快递费', 68.00, '2026-06-12', 5, '文件快递费用', SYSDATE FROM TBL_EXPENSE_REPORT WHERE REPORT_CODE = 'BX20260601002';

-- 报销单3 (BX20260601003) - 业务招待费明细
INSERT INTO TBL_EXPENSE_REPORT_DETAIL (DETAIL_ID, REPORT_ID, EXPENSE_ITEM_ID, EXPENSE_ITEM_NAME, EXPENSE_AMOUNT, EXPENSE_DATE, RECEIPT_COUNT, DESCRIPTION, CREATE_TIME)
SELECT 'DET20260616006', REPORT_ID, 'ITEM006', '招待费', 1680.00, '2026-06-13', 1, '客户商务宴请', SYSDATE FROM TBL_EXPENSE_REPORT WHERE REPORT_CODE = 'BX20260601003';

-- 报销单4 (BX20260601004) - 培训费明细
INSERT INTO TBL_EXPENSE_REPORT_DETAIL (DETAIL_ID, REPORT_ID, EXPENSE_ITEM_ID, EXPENSE_ITEM_NAME, EXPENSE_AMOUNT, EXPENSE_DATE, RECEIPT_COUNT, DESCRIPTION, CREATE_TIME)
SELECT 'DET20260616007', REPORT_ID, 'ITEM007', '培训费', 3200.00, '2026-06-14', 1, '财务共享系统操作培训', SYSDATE FROM TBL_EXPENSE_REPORT WHERE REPORT_CODE = 'BX20260601004';

INSERT INTO TBL_EXPENSE_REPORT_DETAIL (DETAIL_ID, REPORT_ID, EXPENSE_ITEM_ID, EXPENSE_ITEM_NAME, EXPENSE_AMOUNT, EXPENSE_DATE, RECEIPT_COUNT, DESCRIPTION, CREATE_TIME)
SELECT 'DET20260616008', REPORT_ID, 'ITEM008', '教材费', 180.00, '2026-06-14', 1, '培训教材及资料', SYSDATE FROM TBL_EXPENSE_REPORT WHERE REPORT_CODE = 'BX20260601004';

-- 报销单5 (BX20260601005) - 其他费用明细
INSERT INTO TBL_EXPENSE_REPORT_DETAIL (DETAIL_ID, REPORT_ID, EXPENSE_ITEM_ID, EXPENSE_ITEM_NAME, EXPENSE_AMOUNT, EXPENSE_DATE, RECEIPT_COUNT, DESCRIPTION, CREATE_TIME)
SELECT 'DET20260616009', REPORT_ID, 'ITEM009', '通讯费', 120.00, '2026-06-15', 1, '月度通讯补贴', SYSDATE FROM TBL_EXPENSE_REPORT WHERE REPORT_CODE = 'BX20260601005';

INSERT INTO TBL_EXPENSE_REPORT_DETAIL (DETAIL_ID, REPORT_ID, EXPENSE_ITEM_ID, EXPENSE_ITEM_NAME, EXPENSE_AMOUNT, EXPENSE_DATE, RECEIPT_COUNT, DESCRIPTION, CREATE_TIME)
SELECT 'DET20260616010', REPORT_ID, 'ITEM010', '差旅费', 560.00, '2026-06-15', 2, '市内交通费', SYSDATE FROM TBL_EXPENSE_REPORT WHERE REPORT_CODE = 'BX20260601005';
