package com.huabo.system.mappersql;

public class ScheduledTaskMapperSqlConfig {
	
	public String selectContractPlanNodeTimeout() throws Exception{
		StringBuffer sb = new StringBuffer("SELECT T1.DISPATCHSTAFF AS DISPATCHSTAFF,T1.PROJECTID AS PROJECTID,T1.CONTRACTID AS CONTRACTID,T1.CONTRACTNO AS CONTRACTNO,T1.CONTRACTNAME AS CONTRACTNAME,T1.CONTRACTMONEY AS CONTRACTMONEY,")
		.append("T1.DCTYPE AS DCTYPE,TRUNC(SYSDATE-T1.PLANENDDATE) AS DIFFDAY FROM (SELECT TCP.DISPATCHSTAFF,TCP.PROJECTID,MAX(PLANENDDATE) AS PLANENDDATE,")
		.append("TCU.CONTRACTID,TCU.CONTRACTNO,TCU.CONTRACTNAME,TCU.CONTRACTMONEY,TCU.DCTYPE FROM TBL_CONTRACT_PLANNODE TCP LEFT JOIN TBL_CYHW_UNIT TCU ON TCP.PROJECTID = TCU.CONTRACTID WHERE ")
		.append(" (TCP.PLANNODESTATUS != 2 OR TCP.PLANNODESTATUS IS NULL) GROUP BY TCP.DISPATCHSTAFF,TCP.PROJECTID,TCU.CONTRACTID,TCU.CONTRACTNO,TCU.CONTRACTNAME,TCU.CONTRACTMONEY,TCU.DCTYPE ")
		.append(" ) T1 WHERE ( TO_CHAR(T1.PLANENDDATE+3,'yyyy-mm-dd') = TO_CHAR(SYSDATE, 'yyyy-mm-dd') OR TO_CHAR(T1.PLANENDDATE+7,'yyyy-mm-dd') = TO_CHAR(SYSDATE, 'yyyy-mm-dd')")
		.append(" OR TO_CHAR(T1.PLANENDDATE+15,'yyyy-mm-dd') <= TO_CHAR(SYSDATE, 'yyyy-mm-dd')) ORDER BY T1.DISPATCHSTAFF,T1.PLANENDDATE DESC ");
		return sb.toString();
		
		
	}
}
