package com.huabo.system.mappersql;

import java.math.BigDecimal;

import com.hbfk.util.database.DataBaseSqlConfig;

public class YMFormDataMapperSqlConfig {
	
	public String selectXMGLMapById(BigDecimal fromId) throws Exception{
		String sql = "SELECT TNP.PRJOECTNAME AS PROJECTNAME,	TNP.PROJECTTYPE AS PROJECTTYPE,	"+DataBaseSqlConfig.getNullColumn("AUDITORG.ORGNAME", "AUDITSTA.REALNAME")
				+ " AS AUDITOBJ,	TNP.PLANYEAR AS PLANYEAR,	TNP.AUDITTYPE AS AUDITTYPE,	TNP.PROJECTSOURCE AS PROJECTSOURCE,	TNP.STARTDATE AS STARTDATE,	TNP.ENDDATE AS ENDDATE,	PM.PKYMSTAFFID AS ITEMPM,	TNP.PRO_SJFS AS PROSJFS,	TNP.CNTTYPE AS CNTTYPE,	TNP.COSTS AS COSTS,	TNP.EXTERNALASSIG AS EXTERNALASSIG,	JBORG.PKYMORGID AS COSPOMSORDEPARTMENT,	TNP.IMPLEMENTAION AS IMPLEMENTAION,	TNP.AUDITREQUIREMENTS AS AUDITREQUIREMENTS,	TNP.IMPLEMENTAIONSTEPS AS IMPLEMENTAIONSTEPS,	TNP.PURPOSE AS PURPOSE,	TNP.SCOPES AS SCOPES,	TNP.PURSUANT AS PURSUANT FROM TBL_NBSJ_PROJECT TNP LEFT JOIN TBL_ORGANIZATION AUDITORG ON AUDITORG.ORGID = TNP.AUDITORG LEFT JOIN TBL_STAFF AUDITSTA ON AUDITSTA.STAFFID = TNP.AUDITSTAFFID	LEFT JOIN TBL_STAFF PM ON PM.STAFFID = TNP.PMID	LEFT JOIN TBL_ORGANIZATION JBORG ON JBORG.ORGID = TNP.COSPOMSORDEPARTMENT "
				+ " WHERE TNP.PROJECTID = "+fromId;
		return sql;
	}
	
	public String selectZDSHMapById(BigDecimal fromId, String roleIdStrs) throws Exception{
		String sql = "SELECT "
	            + "	TFIA.AUDITTYPE AS AUDITTYPE, "
	            + "	TFIA.AUDITNAME AS AUDITNAME, "
	            + "	TFIA.OPINIONNAME AS OPINIONNAME, "
	            + "	TFIA.DRAFTADMINISTRATOROPINION AS DRAFTADMINISTRATOROPINION, "
	            + "	TFIA.DRAFTDEPARTMENTOPINION AS DRAFTDEPARTMENTOPINION, "
	            + "	TFIA.DEPARTMENTBELONGGROUPOPINION AS DEPARTMENTBELONGGROUPOPINION, "
	            + "	TFIA.DRAFTDEPARTMENTOPINIONSUCK AS DRAFTDEPARTMENTOPINIONSUCK, "
	            + "	TFIA.INSTITUTIONAUDITEXTID AS INSTITUTIONAUDITEXTID, "
	            + "	TS.REALNAME AS REALNAME, "
	            + "	(SELECT PKYMSTAFFID FROM TBL_STAFF WHERE  "+ DataBaseSqlConfig.getWhereColumnInStr("ROLEIDSTRS", roleIdStrs, ",")
	            + "	AND ORGID = TFIA.WORKUNIT ) AS COMPLIANCENAME, "
	            + "	TOA.ORGNAME AS WORKUNIT "
	            + " FROM "
	            + "	TBL_FWGL_INSTITUTION_AUDIT TFIA "
	            + "	LEFT JOIN TBL_STAFF TS ON TFIA.CREATOR = TS.STAFFID "
	            + "	LEFT JOIN TBL_ORGANIZATION TOA ON TFIA.WORKUNIT = TOA.ORGID  "
	            + " WHERE "
	            + "	INSTITUTIONAUDITID = "+fromId;
		return sql;
	}
	
	public String selectJYSXSHMapById(BigDecimal fromId, String roleIdStrs) throws Exception{
		String sql = "SELECT "
	            + "	TFIA.AUDITTYPE AS AUDITTYPE, "
	            + "	TFIA.AUDITNAME AS AUDITNAME, "
	            + "	TFIA.OPINIONNAME AS OPINIONNAME, "
	            + "	TFIA.MATTERSINFORMEDPERSONNEL AS MATTERSINFORMEDPERSONNEL, "
	            + "	TFIA.MATTERSINSTRUCTIONS AS MATTERSINSTRUCTIONS, "
	            + "	TFIA.HOSTDEPARTMENTOPINION AS HOSTDEPARTMENTOPINION, "
	            + "	TFIA.RELATEDDEPARTMENTOPINION AS RELATEDDEPARTMENTOPINION, "
	            + "	TFIA.TEAMLEADEROPINION AS TEAMLEADEROPINION, "
	            + "	TFIA.FIRMLEADEROPINION AS FIRMLEADEROPINION, "
	            + "	TFIA.CREATEDTIME AS CREATEDTIME, "
	            + "	TS.REALNAME AS CREATOR, "
	            + "	(SELECT PKYMSTAFFID  FROM TBL_STAFF  "
	            + "	WHERE "+ DataBaseSqlConfig.getWhereColumnInStr("ROLEIDSTRS", roleIdStrs, ",")
	            + "	AND ORGID = TFIA.WORKUNIT  ) AS COMPLIANCENAME, "
	            + "	TOA.ORGNAME AS WORKUNITNAME  "
	            + " FROM "
	            + "	TBL_FWGL_INSTITUTION_AUDIT TFIA "
	            + "	LEFT JOIN TBL_STAFF TS ON TFIA.CREATOR = TS.STAFFID "
	            + "	LEFT JOIN TBL_ORGANIZATION TOA ON TFIA.WORKUNIT = TOA.ORGID  "
	            + " WHERE "
	            + "	INSTITUTIONAUDITID = "+fromId;
		return sql;
	}
}
