spring:
 main:
  allow-bean-definition-overriding: true
 application:
  name: hbyunFinancialData #应用名称
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  #Oracle数据库配置
  oracle:
   url: jdbc:dm://192.0.2.200:5236/HBGRCZH?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
   username: HBGRCZH
   password: HBGRCZH1101
   driverClassName: dm.jdbc.driver.DmDriver
 druid: 
  oracle:
   initialSize: 5
   minIdle: 5
   maxActive: 20
   maxWait: 60000
   timeBetweenEvictionRunsMillis: 60000
   minEvictableIdleTimeMillis: 300000
   validationQuery: SELECT 1 FROM DUAL
   testWhileIdle: true
   testOnBorrow: false
   testOnReturn: false
   poolPreparedStatement: true
   maxPoolPreparedStatementPerConnectionSize: 20
   filters: stat,wall,log4j
   connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #Mysql数据库配置
  mysql:
   url: jdbc:mysql://192.0.2.200:3306/hbgrctest?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
   username: ROOT
   password: HBGRC
   driverClassName: com.mysql.jdbc.Driver
  druid:
   mysql:
     initialSize: 5
     minIdle: 5
     maxActive: 20
     maxWait: 60000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1 FROM DUAL
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatement: true
     maxPoolPreparedStatementPerConnectionSize: 20
     filters: stat,wall,log4j
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#eureka服务注册中心配置
eureka:
 instance:
  ip-address: 127.0.0.1
  instance-id: hbyunSystemSetting-8763
  prefer-ip-address: true
  hostname: hbyun-systemSetting-service
 client:
  register-with-eureka: false
  fetch-registry: false
  serviceUrl:
   defaultZone: http://hbyunadmin:hbEureka12345@127.0.0.1:8761/eureka
security:
  basic:
    enabled: false

#redis配置
redisAddressIp: 127.0.0.1
redisAddressPort: 6379
redisPwd: zhRedis@135246
redisMaxTotal: 512
redisMaxIdle: 100
redisMaxWait: 10000
redisTimeOut: 1000
redisTextonBorrow: true

acurl : http://127.0.0.1:8003
formurl : http://127.0.0.1:8001
activitiModelerUrl : http://127.0.0.1:8137
getOrgChildrenUrl : http://127.0.0.1:8379
insertOrgOneUrl : http://127.0.0.1:8379
redisurl : http://127.0.0.1:8379


logging:
  level:
    com:
      huabo:
        financialdata:
          mapper: debug