spring:
 main:
  allow-bean-definition-overriding: true
 application:
  name: hbyunFinancialData #应用名称
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  #Oracle数据库配置
  oracle:
   #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
   #username: SYSDBA
   #password: SYSDBA
   #driverClassName: oracle.jdbc.driver.OracleDriver
   url: jdbc:dm://127.0.0.1:5236/SYSDBA?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
   username: SYSDBA
   password: REDACTED
   driverClassName: dm.jdbc.driver.DmDriver
 druid: 
  oracle:
   initialSize: 5
   minIdle: 5
   maxActive: 20
   maxWait: 60000
   timeBetweenEvictionRunsMillis: 60000
   minEvictableIdleTimeMillis: 300000
   validationQuery: SELECT 1 FROM DUAL
   testWhileIdle: true
   testOnBorrow: false
   testOnReturn: false
   poolPreparedStatement: true
   maxPoolPreparedStatementPerConnectionSize: 20
   filters: stat,wall,log4j
   connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #Mysql数据库配置
  mysql:
   url: jdbc:mysql://127.0.0.1:3306/SYSDBA?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
   username: SYSDBA
   password: REDACTED
   driverClassName: com.mysql.jdbc.Driver
  druid:
   mysql:
     initialSize: 5
     minIdle: 5
     maxActive: 20
     maxWait: 60000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1 FROM DUAL
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatement: true
     maxPoolPreparedStatementPerConnectionSize: 20
     filters: stat,wall,log4j
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
 redis: 
  host: 127.0.0.1
  port: 6379
  password:REDACTED

#eureka服务注册中心配置
eureka:
  instance:
    ip-address: 127.0.0.1
    instance-id: hbyunFinanciaData-9988
    prefer-ip-address: true
    hostname: hbyun-financiadata-service
  client:
    serviceUrl:
      defaultZone: http://hbyunadmin:REDACTED@127.0.0.1:8761/eureka
security:
  basic:
    enabled: false

acurl: http://127.0.0.1:8003
formurl: http://127.0.0.1:8001
activitiModelerUrl: http://127.0.0.1:8137
getOrgChildrenUrl: http://127.0.0.1:8379
insertOrgOneUrl: http://127.0.0.1:8379
redisurl: http://127.0.0.1:8379


logging:
  level:
    com:
      huabo:
        financialdata:
          mapper: debug