spring:
  application:
    name: hbyunRiskControl #应用名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #Oracle数据库配置
    oracle:
      url: jdbc:oracle:thin:@192.0.2.200:1521:orcl
      username: HBGRCTEST
      password: HBGRCTEST
      driverClassName: oracle.jdbc.driver.OracleDriver
  druid:
    oracle:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatement: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    #Mysql数据库配置
    mysql:
      url: jdbc:mysql://192.0.2.200:3306/hbgrcccc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: ROOT
      password: HBGRC
      driverClassName: com.mysql.jdbc.Driver
    druid:
      mysql:
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatement: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#eureka服务注册中心配置
eureka:
  instance:
    ip-address: 127.0.0.1
    instance-id: hbyunRiskControl-8082
    prefer-ip-address: true
    hostname: hbyun-contract-service
  client:
    serviceUrl:
      #defaultZone: http://hbyunadmin:hbEureka12345@192.0.2.200:8761/eureka
      defaultZone: http://hbyunadmin:hbEureka12345@127.0.0.1:8761/eureka

mybatis-plus:
  type-aliases-package: com.huabo.fxgl.entity
  type-enums-package: com.huabo.fxgl.entity.enums

file:
  path: C:\HBFK\PRO\www\apache-tomcat-7.0.65\webapps\ROOT\WEB-INF\
#mybatis-plus:
#  type-aliases-package: com.huabo.fxgl.entity
#  mapper-locations: classpath*:/mapper/**/*.xml
#  mapper-locations: classpath*:/com/huabo/fxgl/mapper/xml/*.xml
mybatis:
  type-aliases-package: com.huabo.fxgl.entity
  mapper-locations: classpath*:/com/huabo/fxgl/mapper/xml/*.xml
  
  #redis配置
redisAddressIp: 127.0.0.1
redisAddressPort: 6379
redisPwd: 123456
redisMaxTotal: 512
redisMaxIdle: 100
redisMaxWait: 10000
redisTimeOut: 1000
redisTextonBorrow: true=======

  