spring:
  application:
    name: hbyunRiskControl #应用名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    oracle: 
    #数据库配置
      url: jdbc:dm://192.0.2.200:5236/HBGRCZH?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      username: HBGRCZH
      password: HBGRCZH1101
      driverClassName: dm.jdbc.driver.DmDriver
     #Mysql数据库配置
#    mysql:
#      url: jdbc:mysql://192.0.2.200:3306/hbgrcccc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
#      username: ROOT
#      password: HBGRC
#      driverClassName: com.mysql.jdbc.Driver
  druid:
    oracle:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatement: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    mysql:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatement: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis: 
    host: 127.0.0.1
    port: 6379
    password: zhRedis@135246


activiti:
  check-process-definitions: false
  database-schema-update: false
#通用mapper配置
mapper:
 mappers: tk.mybatis.mapper.common.Mapper
 not-empty: false
 identity: oracle
 before: true

#eureka服务注册中心配置
eureka:
 instance:
  ip-address: 127.0.0.1
  instance-id: hbyunRisk-8082
  prefer-ip-address: true
  hostname: hbyun-risk-service
 client:
  serviceUrl:
   defaultZone: http://hbyunadmin:hbEureka12345@127.0.0.1:8761/eureka
security:
  basic:
    enabled: false

mybatis-plus:
  type-aliases-package: com.huabo.fxgl.entity
  type-enums-package: com.huabo.fxgl.entity.enums

file:
  path: C:\HBFK\PRO\www\apache-tomcat-7.0.65\webapps\ROOT\WEB-INF\
#mybatis-plus:
#  type-aliases-package: com.huabo.fxgl.entity
#  mapper-locations: classpath*:/mapper/**/*.xml
#  mapper-locations: classpath*:/com/huabo/fxgl/mapper/xml/*.xml
mybatis:
  type-aliases-package: com.huabo.fxgl.entity
  mapper-locations: classpath*:/com/huabo/fxgl/mapper/xml/*.xml
  
application:
  #文件上传
  file-upload:
    base-dir: D:\nginx-1.20.2\html\hbfk
    #base-url: http://192.0.2.200/hbfk
    base-url: http://192.0.2.200/hbfk
  administrators: 风险管理员
  auditlegaldepartment: 审计法务部人员



  