server:
  port: 8066

spring:
  profiles:
    active: dev
    include: druid
  application:
    name: hbyunlog #应用名称
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-circular-references: true
  springdoc:
    swagger-ui:
      enabled: true
    api-docs:
      enabled: true

management:
  health:
    redis:
      enabled: false
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health  # 暴露健康检查端点
  endpoint:
    health:
      show-details: always  # 显示详细健康信息

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


