-- =====================================================
-- 银行贷款表字段扩展
-- 生成时间: 2026-02-09
-- 说明: 添加贷款期限、还款方式、担保方式等字段
-- =====================================================

-- 添加贷款期限字段
ALTER TABLE TBL_BANK_LOAN ADD LOAN_PERIOD NUMBER(10);
COMMENT ON COLUMN TBL_BANK_LOAN.LOAN_PERIOD IS '贷款期限';

-- 添加期限单位字段
ALTER TABLE TBL_BANK_LOAN ADD PERIOD_UNIT VARCHAR2(20) DEFAULT 'MONTH';
COMMENT ON COLUMN TBL_BANK_LOAN.PERIOD_UNIT IS '期限单位 MONTH-月 YEAR-年';

-- 添加还款方式字段
ALTER TABLE TBL_BANK_LOAN ADD PAYMENT_METHOD VARCHAR2(50);
COMMENT ON COLUMN TBL_BANK_LOAN.PAYMENT_METHOD IS '还款方式 EQUAL_PRINCIPAL-等额本金 EQUAL_INSTALLMENT-等额本息 INTEREST_FIRST-先息后本 BULLET-到期一次还本付息';

-- 添加担保类型字段
ALTER TABLE TBL_BANK_LOAN ADD GUARANTEE_TYPE VARCHAR2(50);
COMMENT ON COLUMN TBL_BANK_LOAN.GUARANTEE_TYPE IS '担保类型 CREDIT-信用 MORTGAGE-抵押 PLEDGE-质押 GUARANTEE-保证';

-- 添加担保金额字段
ALTER TABLE TBL_BANK_LOAN ADD GUARANTEE_AMOUNT NUMBER(20,2);
COMMENT ON COLUMN TBL_BANK_LOAN.GUARANTEE_AMOUNT IS '担保金额';

-- 添加备注字段
ALTER TABLE TBL_BANK_LOAN ADD REMARK VARCHAR2(500);
COMMENT ON COLUMN TBL_BANK_LOAN.REMARK IS '备注';

-- 提交
COMMIT;

-- 验证字段是否添加成功
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'TBL_BANK_LOAN'
ORDER BY COLUMN_ID;

