-- =====================================================
-- 银行贷款管理模块 - 合同、还款计划、监控表
-- 数据库: 达梦数据库 (DM Database)
-- 创建日期: 2026-02-09
-- 说明: 贷款合同、还款计划、贷款监控三个子模块的数据库表
-- =====================================================

-- ============================================================
-- 1. 贷款合同表 (TBL_LOAN_CONTRACT)
-- ============================================================
CREATE TABLE TBL_LOAN_CONTRACT (
    CONTRACT_ID BIGINT PRIMARY KEY,
    CONTRACT_NO VARCHAR(50) UNIQUE NOT NULL,
    LOAN_ID BIGINT NOT NULL,
    CONTRACT_NAME VARCHAR(200),
    CONTRACT_TYPE VARCHAR(20),
    CONTRACT_AMOUNT DECIMAL(18,2) NOT NULL,
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    INTEREST_RATE DECIMAL(8,4),
    RATE_TYPE VARCHAR(20),
    CONTRACT_PERIOD INT,
    PERIOD_UNIT VARCHAR(10),
    START_DATE DATE,
    END_DATE DATE,
    SIGNING_DATE DATE,
    BANK_ID BIGINT,
    BANK_NAME VARCHAR(200),
    BANK_CONTACT VARCHAR(100),
    BANK_PHONE VARCHAR(50),
    GUARANTOR_NAME VARCHAR(200),
    GUARANTEE_TYPE VARCHAR(20),
    GUARANTEE_AMOUNT DECIMAL(18,2),
    CONTRACT_STATUS VARCHAR(20) DEFAULT 'DRAFT',
    ATTACHMENT_URL VARCHAR(500),
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_LOAN_CONTRACT IS '贷款合同表';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.CONTRACT_ID IS '合同ID';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.CONTRACT_NO IS '合同编号';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.LOAN_ID IS '关联贷款ID';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.CONTRACT_NAME IS '合同名称';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.CONTRACT_TYPE IS '合同类型';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.CONTRACT_AMOUNT IS '合同金额';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.INTEREST_RATE IS '利率';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.RATE_TYPE IS '利率类型';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.CONTRACT_PERIOD IS '合同期限';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.PERIOD_UNIT IS '期限单位';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.START_DATE IS '开始日期';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.END_DATE IS '结束日期';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.SIGNING_DATE IS '签署日期';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.BANK_ID IS '银行ID';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.BANK_NAME IS '银行名称';
COMMENT ON COLUMN TBL_LOAN_CONTRACT.CONTRACT_STATUS IS '合同状态(DRAFT-草稿,ACTIVE-生效,EXPIRED-已到期,TERMINATED-已终止)';

CREATE INDEX IDX_LC_CONTRACT_NO ON TBL_LOAN_CONTRACT(CONTRACT_NO);
CREATE INDEX IDX_LC_LOAN_ID ON TBL_LOAN_CONTRACT(LOAN_ID);
CREATE INDEX IDX_LC_STATUS ON TBL_LOAN_CONTRACT(CONTRACT_STATUS);
CREATE INDEX IDX_LC_BANK_ID ON TBL_LOAN_CONTRACT(BANK_ID);

-- ============================================================
-- 2. 还款计划表 (TBL_REPAYMENT_PLAN)
-- ============================================================
CREATE TABLE TBL_REPAYMENT_PLAN (
    PLAN_ID BIGINT PRIMARY KEY,
    LOAN_ID BIGINT NOT NULL,
    CONTRACT_ID BIGINT,
    PERIOD_NO INT NOT NULL,
    DUE_DATE DATE NOT NULL,
    PRINCIPAL_AMOUNT DECIMAL(18,2) DEFAULT 0,
    INTEREST_AMOUNT DECIMAL(18,2) DEFAULT 0,
    TOTAL_AMOUNT DECIMAL(18,2) DEFAULT 0,
    PAID_PRINCIPAL DECIMAL(18,2) DEFAULT 0,
    PAID_INTEREST DECIMAL(18,2) DEFAULT 0,
    PAID_TOTAL DECIMAL(18,2) DEFAULT 0,
    REMAINING_PRINCIPAL DECIMAL(18,2) DEFAULT 0,
    PAYMENT_DATE DATE,
    PAYMENT_STATUS VARCHAR(20) DEFAULT 'PENDING',
    OVERDUE_DAYS INT DEFAULT 0,
    OVERDUE_INTEREST DECIMAL(18,2) DEFAULT 0,
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_REPAYMENT_PLAN IS '还款计划表';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.PLAN_ID IS '计划ID';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.LOAN_ID IS '关联贷款ID';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.CONTRACT_ID IS '关联合同ID';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.PERIOD_NO IS '期数';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.DUE_DATE IS '应还日期';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.PRINCIPAL_AMOUNT IS '应还本金';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.INTEREST_AMOUNT IS '应还利息';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.TOTAL_AMOUNT IS '应还总额';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.PAID_PRINCIPAL IS '已还本金';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.PAID_INTEREST IS '已还利息';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.PAID_TOTAL IS '已还总额';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.REMAINING_PRINCIPAL IS '剩余本金';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.PAYMENT_DATE IS '实际还款日期';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.PAYMENT_STATUS IS '还款状态(PENDING-待还款,PARTIAL-部分还款,PAID-已还款,OVERDUE-已逾期)';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.OVERDUE_DAYS IS '逾期天数';
COMMENT ON COLUMN TBL_REPAYMENT_PLAN.OVERDUE_INTEREST IS '逾期利息';

CREATE INDEX IDX_RP_LOAN_ID ON TBL_REPAYMENT_PLAN(LOAN_ID);
CREATE INDEX IDX_RP_CONTRACT_ID ON TBL_REPAYMENT_PLAN(CONTRACT_ID);
CREATE INDEX IDX_RP_DUE_DATE ON TBL_REPAYMENT_PLAN(DUE_DATE);
CREATE INDEX IDX_RP_STATUS ON TBL_REPAYMENT_PLAN(PAYMENT_STATUS);

-- ============================================================
-- 3. 贷款监控表 (TBL_LOAN_MONITORING)
-- ============================================================
CREATE TABLE TBL_LOAN_MONITORING (
    MONITORING_ID BIGINT PRIMARY KEY,
    LOAN_ID BIGINT NOT NULL,
    ALERT_TYPE VARCHAR(50) NOT NULL,
    ALERT_LEVEL VARCHAR(20) NOT NULL,
    ALERT_TITLE VARCHAR(200),
    ALERT_MESSAGE VARCHAR(1000),
    ALERT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DUE_DATE DATE,
    OVERDUE_DAYS INT DEFAULT 0,
    OVERDUE_AMOUNT DECIMAL(18,2) DEFAULT 0,
    ALERT_STATUS VARCHAR(20) DEFAULT 'PENDING',
    HANDLER_ID BIGINT,
    HANDLER_NAME VARCHAR(100),
    HANDLE_DATE TIMESTAMP,
    HANDLE_OPINION VARCHAR(500),
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_LOAN_MONITORING IS '贷款监控表';
COMMENT ON COLUMN TBL_LOAN_MONITORING.MONITORING_ID IS '监控ID';
COMMENT ON COLUMN TBL_LOAN_MONITORING.LOAN_ID IS '关联贷款ID';
COMMENT ON COLUMN TBL_LOAN_MONITORING.ALERT_TYPE IS '预警类型(MATURITY-到期预警,OVERDUE-逾期预警,RATE_CHANGE-利率变动,AMOUNT_CHANGE-金额变动)';
COMMENT ON COLUMN TBL_LOAN_MONITORING.ALERT_LEVEL IS '预警级别(LOW-低,MEDIUM-中,HIGH-高,CRITICAL-紧急)';
COMMENT ON COLUMN TBL_LOAN_MONITORING.ALERT_TITLE IS '预警标题';
COMMENT ON COLUMN TBL_LOAN_MONITORING.ALERT_MESSAGE IS '预警内容';
COMMENT ON COLUMN TBL_LOAN_MONITORING.ALERT_DATE IS '预警日期';
COMMENT ON COLUMN TBL_LOAN_MONITORING.DUE_DATE IS '到期日期';
COMMENT ON COLUMN TBL_LOAN_MONITORING.OVERDUE_DAYS IS '逾期天数';
COMMENT ON COLUMN TBL_LOAN_MONITORING.OVERDUE_AMOUNT IS '逾期金额';
COMMENT ON COLUMN TBL_LOAN_MONITORING.ALERT_STATUS IS '预警状态(PENDING-待处理,PROCESSING-处理中,RESOLVED-已解决,IGNORED-已忽略)';
COMMENT ON COLUMN TBL_LOAN_MONITORING.HANDLER_ID IS '处理人ID';
COMMENT ON COLUMN TBL_LOAN_MONITORING.HANDLER_NAME IS '处理人姓名';
COMMENT ON COLUMN TBL_LOAN_MONITORING.HANDLE_DATE IS '处理日期';
COMMENT ON COLUMN TBL_LOAN_MONITORING.HANDLE_OPINION IS '处理意见';

CREATE INDEX IDX_LM_LOAN_ID ON TBL_LOAN_MONITORING(LOAN_ID);
CREATE INDEX IDX_LM_ALERT_TYPE ON TBL_LOAN_MONITORING(ALERT_TYPE);
CREATE INDEX IDX_LM_ALERT_LEVEL ON TBL_LOAN_MONITORING(ALERT_LEVEL);
CREATE INDEX IDX_LM_STATUS ON TBL_LOAN_MONITORING(ALERT_STATUS);
CREATE INDEX IDX_LM_ALERT_DATE ON TBL_LOAN_MONITORING(ALERT_DATE);

-- ============================================================
-- 提交事务
-- ============================================================
COMMIT;