-- =====================================================
-- 银行贷款测试数据 (TBL_BANK_LOAN)
-- 生成时间: 2026-02-09
-- 说明: 插入10条测试数据用于开发测试
-- 基于实际数据库表结构生成
-- =====================================================

-- 实际表结构:
-- LOAN_ID, LOAN_NO, LOAN_NAME, COMPANY_ID, COMPANY_NAME, BANK_ID, BANK_NAME,
-- LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE,
-- RATE_TYPE, START_DATE, END_DATE, LOAN_STATUS, DELETE_FLAG,
-- CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME

-- 清理已有测试数据（可选，谨慎使用）
-- DELETE FROM TBL_BANK_LOAN WHERE LOAN_NO LIKE 'BL-TEST-%';

-- 插入10条测试数据
INSERT INTO TBL_BANK_LOAN (LOAN_ID, LOAN_NO, LOAN_NAME, COMPANY_ID, COMPANY_NAME, BANK_ID, BANK_NAME, LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, RATE_TYPE, START_DATE, END_DATE, LOAN_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (1001, 'BL-TEST-001', '流动资金贷款', 100, '华博科技有限公司', 1, '中国工商银行', 'CREDIT_LINE', 5000000.00, 4500000.00, 'CNY', 4.35, 'FIXED', DATE '2026-01-15', DATE '2027-01-14', 'ACTIVE', 0, 'system', SYSDATE, NULL, NULL);

INSERT INTO TBL_BANK_LOAN (LOAN_ID, LOAN_NO, LOAN_NAME, COMPANY_ID, COMPANY_NAME, BANK_ID, BANK_NAME, LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, RATE_TYPE, START_DATE, END_DATE, LOAN_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (1002, 'BL-TEST-002', '设备采购贷款', 100, '华博科技有限公司', 2, '中国建设银行', 'TERM_LOAN', 10000000.00, 8000000.00, 'CNY', 4.65, 'FIXED', DATE '2025-06-01', DATE '2028-05-31', 'ACTIVE', 0, 'system', SYSDATE, NULL, NULL);

INSERT INTO TBL_BANK_LOAN (LOAN_ID, LOAN_NO, LOAN_NAME, COMPANY_ID, COMPANY_NAME, BANK_ID, BANK_NAME, LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, RATE_TYPE, START_DATE, END_DATE, LOAN_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (1003, 'BL-TEST-003', '循环贷款', 101, '华博物流有限公司', 3, '中国农业银行', 'REVOLVING_LOAN', 3000000.00, 2500000.00, 'CNY', 4.15, 'FLOATING', DATE '2025-09-10', DATE '2027-09-09', 'ACTIVE', 0, 'system', SYSDATE, NULL, NULL);

INSERT INTO TBL_BANK_LOAN (LOAN_ID, LOAN_NO, LOAN_NAME, COMPANY_ID, COMPANY_NAME, BANK_ID, BANK_NAME, LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, RATE_TYPE, START_DATE, END_DATE, LOAN_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (1004, 'BL-TEST-004', '厂房抵押贷款', 100, '华博科技有限公司', 4, '招商银行', 'MORTGAGE', 20000000.00, 18000000.00, 'CNY', 4.90, 'FIXED', DATE '2024-03-20', DATE '2029-03-19', 'ACTIVE', 0, 'system', SYSDATE, NULL, NULL);

INSERT INTO TBL_BANK_LOAN (LOAN_ID, LOAN_NO, LOAN_NAME, COMPANY_ID, COMPANY_NAME, BANK_ID, BANK_NAME, LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, RATE_TYPE, START_DATE, END_DATE, LOAN_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (1005, 'BL-TEST-005', '担保贷款申请', 102, '华博医疗科技', 5, '中信银行', 'GUARANTEE', 8000000.00, 8000000.00, 'CNY', 5.20, 'FIXED', NULL, NULL, 'PENDING', 0, 'system', SYSDATE, NULL, NULL);

INSERT INTO TBL_BANK_LOAN (LOAN_ID, LOAN_NO, LOAN_NAME, COMPANY_ID, COMPANY_NAME, BANK_ID, BANK_NAME, LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, RATE_TYPE, START_DATE, END_DATE, LOAN_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (1006, 'BL-TEST-006', '农业生产贷款', 103, '华博农业发展', 6, '浦发银行', 'CREDIT_LINE', 2000000.00, 1500000.00, 'CNY', 4.50, 'FLOATING', DATE '2025-11-01', DATE '2026-10-31', 'ACTIVE', 0, 'system', SYSDATE, NULL, NULL);

INSERT INTO TBL_BANK_LOAN (LOAN_ID, LOAN_NO, LOAN_NAME, COMPANY_ID, COMPANY_NAME, BANK_ID, BANK_NAME, LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, RATE_TYPE, START_DATE, END_DATE, LOAN_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (1007, 'BL-TEST-007', '新能源项目贷款', 104, '华博新能源', 7, '兴业银行', 'TERM_LOAN', 15000000.00, 12000000.00, 'CNY', 4.75, 'FIXED', DATE '2023-08-15', DATE '2027-08-14', 'ACTIVE', 0, 'system', SYSDATE, NULL, NULL);

INSERT INTO TBL_BANK_LOAN (LOAN_ID, LOAN_NO, LOAN_NAME, COMPANY_ID, COMPANY_NAME, BANK_ID, BANK_NAME, LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, RATE_TYPE, START_DATE, END_DATE, LOAN_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (1008, 'BL-TEST-008', '外币贷款', 100, '华博科技有限公司', 8, '汇丰银行', 'REVOLVING_LOAN', 1500000.00, 1200000.00, 'USD', 3.85, 'FLOATING', DATE '2026-01-01', DATE '2026-12-31', 'ACTIVE', 0, 'system', SYSDATE, NULL, NULL);

INSERT INTO TBL_BANK_LOAN (LOAN_ID, LOAN_NO, LOAN_NAME, COMPANY_ID, COMPANY_NAME, BANK_ID, BANK_NAME, LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, RATE_TYPE, START_DATE, END_DATE, LOAN_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (1009, 'BL-TEST-009', '已结清贷款', 101, '华博物流有限公司', 9, '民生银行', 'MORTGAGE', 6000000.00, 0, 'CNY', 4.80, 'FIXED', DATE '2024-12-01', DATE '2027-11-30', 'COMPLETED', 0, 'system', SYSDATE, NULL, NULL);

INSERT INTO TBL_BANK_LOAN (LOAN_ID, LOAN_NO, LOAN_NAME, COMPANY_ID, COMPANY_NAME, BANK_ID, BANK_NAME, LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, RATE_TYPE, START_DATE, END_DATE, LOAN_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (1010, 'BL-TEST-010', '已审批待放款', 102, '华博医疗科技', 10, '光大银行', 'GUARANTEE', 4500000.00, 4500000.00, 'CNY', 5.10, 'FIXED', NULL, NULL, 'APPROVED', 0, 'system', SYSDATE, NULL, NULL);

-- 提交事务
COMMIT;

-- 验证数据
SELECT COUNT(*) AS total_count FROM TBL_BANK_LOAN WHERE DELETE_FLAG = 0;
SELECT LOAN_TYPE, COUNT(*) AS count FROM TBL_BANK_LOAN WHERE DELETE_FLAG = 0 GROUP BY LOAN_TYPE;

