-- 检查并创建业务系统注册表
-- 如果表不存在则创建

DECLARE
    v_count NUMBER;
BEGIN
    -- 检查表是否存在
    SELECT COUNT(*) INTO v_count
    FROM user_tables
    WHERE table_name = 'TC_BUSINESS_SYSTEM';

    -- 如果表不存在,则创建
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE REDACTED.TC_BUSINESS_SYSTEM (
            ID VARCHAR2(32) NOT NULL,
            SYSTEM_CODE VARCHAR2(50) NOT NULL,
            SYSTEM_NAME VARCHAR2(100) NOT NULL,
            SYSTEM_TYPE VARCHAR2(50),
            SYSTEM_DESC VARCHAR2(500),
            INTERFACE_URL VARCHAR2(200),
            INTERFACE_PORT NUMBER(5),
            AUTH_TYPE VARCHAR2(20),
            AUTH_CONFIG VARCHAR2(1000),
            DATA_FORMAT VARCHAR2(20),
            CONNECTION_STATUS VARCHAR2(20),
            LAST_CONNECT_TIME DATE,
            CONNECT_TIMEOUT NUMBER(10) DEFAULT 30000,
            READ_TIMEOUT NUMBER(10) DEFAULT 60000,
            RETRY_COUNT NUMBER(2) DEFAULT 3,
            STATUS VARCHAR2(10) DEFAULT ''1'',
            REMARK VARCHAR2(500),
            CREATE_TIME DATE DEFAULT SYSDATE,
            UPDATE_TIME DATE DEFAULT SYSDATE,
            CREATE_USER VARCHAR2(32),
            UPDATE_USER VARCHAR2(32),
            VERSION_NO NUMBER(10) DEFAULT 0,
            CONSTRAINT PK_TC_BUSINESS_SYSTEM PRIMARY KEY (ID),
            CONSTRAINT UK_TC_BUSINESS_SYSTEM_CODE UNIQUE (SYSTEM_CODE)
        )';
        
        -- 创建索引
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_TC_BUSINESS_SYSTEM_TYPE ON REDACTED.TC_BUSINESS_SYSTEM(SYSTEM_TYPE)';
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_TC_BUSINESS_SYSTEM_STATUS ON REDACTED.TC_BUSINESS_SYSTEM(STATUS)';
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_TC_BUSINESS_SYSTEM_CONN ON REDACTED.TC_BUSINESS_SYSTEM(CONNECTION_STATUS)';

        -- 添加表注释
        EXECUTE IMMEDIATE 'COMMENT ON TABLE REDACTED.TC_BUSINESS_SYSTEM IS ''业务系统注册表''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.ID IS ''主键ID''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.SYSTEM_CODE IS ''系统编码''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.SYSTEM_NAME IS ''系统名称''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.SYSTEM_TYPE IS ''系统类型''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.SYSTEM_DESC IS ''系统描述''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.INTERFACE_URL IS ''接口地址''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.INTERFACE_PORT IS ''接口端口''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.AUTH_TYPE IS ''认证类型''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.AUTH_CONFIG IS ''认证配置''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.DATA_FORMAT IS ''数据格式''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.CONNECTION_STATUS IS ''连接状态''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.LAST_CONNECT_TIME IS ''最后连接时间''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.CONNECT_TIMEOUT IS ''连接超时时间（毫秒）''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.READ_TIMEOUT IS ''读取超时时间（毫秒）''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.RETRY_COUNT IS ''重试次数''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.STATUS IS ''状态：1-启用，0-停用''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.REMARK IS ''备注''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.CREATE_TIME IS ''创建时间''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.UPDATE_TIME IS ''更新时间''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.CREATE_USER IS ''创建人''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.UPDATE_USER IS ''更新人''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REDACTED.TC_BUSINESS_SYSTEM.VERSION_NO IS ''版本号''';
        
        DBMS_OUTPUT.PUT_LINE('表 TC_BUSINESS_SYSTEM 创建成功');
    ELSE
        DBMS_OUTPUT.PUT_LINE('表 TC_BUSINESS_SYSTEM 已存在');
    END IF;
END;
/

