-- 融管理模块初始化数据脚本
-- 兼容达梦数据库

-- 初始化融资基础参数数据
INSERT INTO TBL_FINANCING_BASIC_PARAMS (PARAM_CODE, PARAM_NAME, PARAM_TYPE, PARAM_VALUE, PARAM_DESC, STATUS, CREATE_USER, ORG_ID, REMARK) VALUES
('INTEREST_RATE_BASE', '基准利率', 'RATE', '4.35', '人民银行基准利率', 'ENABLE', 1, 1, '人民银行公布的基准利率'),
('MAX_LOAN_RATIO', '最大贷款比例', 'RULE', '0.7', '企业最大贷款比例', 'ENABLE', 1, 1, '企业资产最大可贷款比例'),
('MIN_CREDIT_SCORE', '最低授信评分', 'RULE', '600', '企业授信最低评分要求', 'ENABLE', 1, 1, '企业授信申请最低信用评分'),
('MAX_GUARANTEE_PERIOD', '最长担保期限', 'PERIOD', '120', '担保合同最长期限（月）', 'ENABLE', 1, 1, '担保合同最长有效期限'),
('DEFAULT_INTEREST_RATE', '默认利率', 'RATE', '5.5', '默认贷款利率', 'ENABLE', 1, 1, '企业贷款默认利率');

-- 初始化债券类别数据（假设表结构为FM_BOND_CATEGORY）
INSERT INTO FM_BOND_CATEGORY (CATEGORY_CODE, CATEGORY_NAME, CATEGORY_TYPE, TRADING_MARKET, ISSUER_TYPE, MATURITY_RANGE, INTEREST_TYPE, MIN_ISSUE_AMOUNT, MAX_ISSUE_AMOUNT, ISSUE_CURRENCY, REGULATORY_AUTHORITY, APPROVAL_REQUIRED, DISCLOSURE_REQUIRED, LISTING_REQUIRED, SORT_ORDER, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO) VALUES
('GOV_001', '国债-短期', 'GOVERNMENT', 'SH', 'GOVERNMENT', '1-3年', 'FIXED', 1000000.00, 100000000.00, 'CNY', 'PBOC', '1', '1', '0', 1, '1', '短期国债', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1', 1),
('GOV_002', '国债-中期', 'GOVERNMENT', 'SH', 'GOVERNMENT', '3-7年', 'FIXED', 5000000.00, 500000000.00, 'CNY', 'PBOC', '1', '1', '0', 2, '1', '中期国债', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1', 1),
('CORP_001', '企业债券-AAA级', 'CORPORATE', 'SH', 'CORPORATE', '3-5年', 'FIXED', 10000000.00, 500000000.00, 'CNY', 'CSRC', '1', '1', '1', 3, '1', 'AAA级企业债券', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1', 1),
('FIN_001', '金融债券-银行', 'FINANCIAL', 'SH', 'BANK', '1-10年', 'FLOAT', 20000000.00, 1000000000.00, 'CNY', 'PBOC', '1', '1', '1', 4, '1', '银行金融债券', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1', 1);

-- 初始化授信类别数据（假设表结构存在）
INSERT INTO CREDIT_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, CATEGORY_TYPE, CREDIT_LEVEL, RISK_WEIGHT, MAX_TERM, APPROVAL_AUTHORITY, SORT_ORDER, STATUS, ORG_ID, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) VALUES
('1', 'HIGH_RISK', '高风险授信', 'HIGH', 'A', '100', 12, 'DIVISION_MANAGER', 1, '1', 1, '高风险授信类别，需要严格审批', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1'),
('2', 'MEDIUM_RISK', '中等风险授信', 'MEDIUM', 'BBB', '50', 36, 'DEPARTMENT_MANAGER', 2, '1', 1, '中等风险授信类别', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1'),
('3', 'LOW_RISK', '低风险授信', 'LOW', 'AAA', '20', 60, 'BRANCH_MANAGER', 3, '1', 1, '低风险授信类别，快速审批', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1');

-- 初始化授信申请数据（假设表结构存在）
INSERT INTO CREDIT_APPLICATION (APPLICATION_NO, APPLY_ORG, CREDIT_TYPE, APPLICATION_AMOUNT, APPLICATION_STATUS, APPLY_TIME, CREDIT_PERIOD, GUARANTEE_TYPE, INTEREST_RATE, PURPOSE, ORG_ID, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) VALUES
('CA2024001', '测试企业A', 'WORKING_CAPITAL', 5000000.00, 'PENDING', CURRENT_TIMESTAMP, 12, 'COLLATERAL', 5.5, '生产经营流动资金', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1'),
('CA2024002', '测试企业B', 'PROJECT_FINANCE', 10000000.00, 'PENDING', CURRENT_TIMESTAMP, 24, 'GUARANTEE', 6.0, '项目建设资金', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1'),
('CA2024003', '测试企业C', 'TRADE_FINANCE', 3000000.00, 'APPROVED', CURRENT_TIMESTAMP, 6, 'INVENTORY', 4.8, '贸易融资', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1');

-- 初始化授信合同数据（假设表结构存在）
INSERT INTO CREDIT_CONTRACT (CONTRACT_NO, COMPANY_NAME, FINANCING_INSTITUTION, CREDIT_TYPE, CREDIT_AMOUNT, CONTRACT_PERIOD, GUARANTEE_METHOD, CONTRACT_STATUS, INTEREST_RATE, START_DATE, END_DATE, SIGN_DATE, ORG_ID, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) VALUES
('CC2024001', '测试企业A', '工商银行', 'WORKING_CAPITAL', 5000000.00, 12, 'MORTGAGE', 'EFFECTIVE', 5.5, DATEADD(MONTH, CURRENT_TIMESTAMP, 1), DATEADD(MONTH, CURRENT_TIMESTAMP, 13), CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1'),
('CC2024002', '测试企业C', '招商银行', 'TRADE_FINANCE', 3000000.00, 6, 'INVENTORY', 'EFFECTIVE', 4.8, DATEADD(MONTH, CURRENT_TIMESTAMP, 1), DATEADD(MONTH, CURRENT_TIMESTAMP, 7), CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1'),
('CC2024003', '测试企业B', '中国银行', 'PROJECT_FINANCE', 10000000.00, 24, 'GUARANTEE', 'EFFECTIVE', 6.0, DATEADD(MONTH, CURRENT_TIMESTAMP, 2), DATEADD(MONTH, CURRENT_TIMESTAMP, 26), CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1');

-- 初始化还款记录数据（假设表结构存在）
-- 创建还款记录表（如果不存在）
CREATE TABLE IF NOT EXISTS TBL_REPAYMENT_RECORD (
    REPAYMENT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    REPAYMENT_NO VARCHAR(50) NOT NULL COMMENT '还款编号',
    FINANCING_TYPE VARCHAR(50) NOT NULL COMMENT '融资类型',
    REPAYMENT_TYPE VARCHAR(50) NOT NULL COMMENT '还款类型',
    PRINCIPAL_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '本金金额',
    INTEREST_AMOUNT DECIMAL(18,2) DEFAULT 0.00 COMMENT '利息金额',
    PAID_AMOUNT DECIMAL(18,2) DEFAULT 0.00 COMMENT '已还金额',
    REMAINING_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '剩余金额',
    DUE_DATE TIMESTAMP NOT NULL COMMENT '到期日期',
    ACTUAL_REPAY_DATE TIMESTAMP COMMENT '实际还款日期',
    OVERDUE_DAYS INTEGER DEFAULT 0 COMMENT '逾期天数',
    REPAYMENT_STATUS VARCHAR(20) NOT NULL COMMENT '还款状态',
    ORG_ID BIGINT NOT NULL COMMENT '组织ID',
    REMARK VARCHAR(1000) COMMENT '备注',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    CREATE_USER BIGINT COMMENT '创建人',
    UPDATE_USER BIGINT COMMENT '更新人'
);

-- 插入还款记录数据
INSERT INTO TBL_REPAYMENT_RECORD (REPAYMENT_NO, FINANCING_TYPE, REPAYMENT_TYPE, PRINCIPAL_AMOUNT, INTEREST_AMOUNT, PAID_AMOUNT, REMAINING_AMOUNT, DUE_DATE, ACTUAL_REPAY_DATE, OVERDUE_DAYS, REPAYMENT_STATUS, ORG_ID, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) VALUES
('RP20240925001', '银行贷款', '本息', 4500000.00, 0.00, 0.00, 4500000.00, '2024-10-25 00:00:00', NULL, 0, 'PENDING', 1, '工商银行流动资金贷款', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
('RP20240920002', '融资租赁', '利息', 0.00, 50000.00, 550000.00, 0.00, '2024-09-20 00:00:00', '2024-09-20 00:00:00', 0, 'COMPLETED', 1, '华融租赁设备租金', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
('RP20240915003', '债券发行', '利息', 4800000.00, 0.00, 2400000.00, 2400000.00, '2024-09-15 00:00:00', NULL, 10, 'PARTIAL', 1, '企业债券付息', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

-- 为还款记录表创建索引
CREATE INDEX IF NOT EXISTS IDX_REPAYMENT_NO ON TBL_REPAYMENT_RECORD(REPAYMENT_NO);
CREATE INDEX IF NOT EXISTS IDX_REPAYMENT_TYPE ON TBL_REPAYMENT_RECORD(FINANCING_TYPE);
CREATE INDEX IF NOT EXISTS IDX_REPAYMENT_STATUS ON TBL_REPAYMENT_RECORD(REPAYMENT_STATUS);
CREATE INDEX IF NOT EXISTS IDX_REPAYMENT_DUE_DATE ON TBL_REPAYMENT_RECORD(DUE_DATE);
CREATE INDEX IF NOT EXISTS IDX_REPAYMENT_ORG ON TBL_REPAYMENT_RECORD(ORG_ID);