-- ============================================================
-- 融资管理模块数据库表创建脚本
-- 数据库: 达梦数据库 (DM Database)
-- 版本: v1.0
-- 创建日期: 2026-01-14
-- 说明: 本脚本包含融资管理模块所需的所有数据库表
-- ============================================================

-- ============================================================
-- 第一部分: 担保业务相关表
-- ============================================================

-- 1.1 担保申请表
CREATE TABLE TBL_GUARANTEE_APPLICATION (
    APPLICATION_ID BIGINT PRIMARY KEY,
    APPLICATION_NO VARCHAR(50) UNIQUE NOT NULL,
    GUARANTEE_TYPE VARCHAR(20) NOT NULL,
    GUARANTEE_AMOUNT DECIMAL(18,2) NOT NULL,
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    GUARANTEE_PERIOD INT,
    PERIOD_UNIT VARCHAR(10),
    GUARANTEE_PURPOSE VARCHAR(500),
    GUARANTOR_ID BIGINT,
    GUARANTOR_NAME VARCHAR(100),
    BENEFCIARY_ID BIGINT,
    BENEFCIARY_NAME VARCHAR(100),
    GUARANTEE_MODE VARCHAR(20),
    APPLICATION_STATUS VARCHAR(20) DEFAULT 'PENDING',
    APPLICATION_DATE DATE,
    APPROVAL_DATE DATE,
    APPROVAL_OPINION VARCHAR(500),
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_GUARANTEE_APPLICATION IS '担保申请表';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.APPLICATION_ID IS '申请ID';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.APPLICATION_NO IS '申请编号';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.GUARANTEE_TYPE IS '担保类型';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.GUARANTEE_AMOUNT IS '担保金额';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.GUARANTEE_PERIOD IS '担保期限';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.PERIOD_UNIT IS '期限单位';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.GUARANTEE_PURPOSE IS '担保用途';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.GUARANTOR_ID IS '担保人ID';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.GUARANTOR_NAME IS '担保人姓名';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.BENEFCIARY_ID IS '受益人ID';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.BENEFCIARY_NAME IS '受益人名称';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.GUARANTEE_MODE IS '担保方式';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.APPLICATION_STATUS IS '申请状态';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.APPLICATION_DATE IS '申请日期';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.APPROVAL_DATE IS '审批日期';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.APPROVAL_OPINION IS '审批意见';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.COMPANY_ID IS '公司ID';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.COMPANY_NAME IS '公司名称';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.DELETE_FLAG IS '删除标志';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.CREATED_BY IS '创建人';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.CREATED_BY_NAME IS '创建人姓名';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.UPDATED_BY IS '更新人';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.UPDATED_BY_NAME IS '更新人姓名';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.UPDATED_TIME IS '更新时间';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.REMARK IS '备注';

-- 创建索引
CREATE INDEX IDX_GA_APPLICATION_NO ON TBL_GUARANTEE_APPLICATION(APPLICATION_NO);
CREATE INDEX IDX_GA_COMPANY_ID ON TBL_GUARANTEE_APPLICATION(COMPANY_ID);
CREATE INDEX IDX_GA_STATUS ON TBL_GUARANTEE_APPLICATION(APPLICATION_STATUS);
CREATE INDEX IDX_GA_APPLICATION_DATE ON TBL_GUARANTEE_APPLICATION(APPLICATION_DATE);

-- 1.2 担保合同表
CREATE TABLE TBL_GUARANTEE_CONTRACT (
    CONTRACT_ID BIGINT PRIMARY KEY,
    CONTRACT_NO VARCHAR(50) UNIQUE NOT NULL,
    APPLICATION_ID BIGINT,
    GUARANTEE_TYPE VARCHAR(20) NOT NULL,
    GUARANTEE_AMOUNT DECIMAL(18,2) NOT NULL,
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    GUARANTEE_PERIOD INT,
    PERIOD_UNIT VARCHAR(10),
    GUARANTEE_START_DATE DATE,
    GUARANTEE_END_DATE DATE,
    GUARANTEE_RATE DECIMAL(8,4),
    GUARANTEE_FEE DECIMAL(18,2),
    PAYMENT_METHOD VARCHAR(20),
    GUARANTOR_ID BIGINT,
    GUARANTOR_NAME VARCHAR(100),
    BENEFCIARY_ID BIGINT,
    BENEFCIARY_NAME VARCHAR(100),
    GUARANTEE_MODE VARCHAR(20),
    CONTRACT_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    SIGNING_DATE DATE,
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    FOREIGN KEY (APPLICATION_ID) REFERENCES TBL_GUARANTEE_APPLICATION(APPLICATION_ID)
);

COMMENT ON TABLE TBL_GUARANTEE_CONTRACT IS '担保合同表';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.CONTRACT_ID IS '合同ID';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.CONTRACT_NO IS '合同编号';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.APPLICATION_ID IS '申请ID';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.GUARANTEE_TYPE IS '担保类型';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.GUARANTEE_AMOUNT IS '担保金额';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.GUARANTEE_PERIOD IS '担保期限';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.PERIOD_UNIT IS '期限单位';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.GUARANTEE_START_DATE IS '担保开始日期';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.GUARANTEE_END_DATE IS '担保结束日期';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.GUARANTEE_RATE IS '担保费率';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.GUARANTEE_FEE IS '担保费用';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.PAYMENT_METHOD IS '支付方式';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.GUARANTOR_ID IS '担保人ID';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.GUARANTOR_NAME IS '担保人姓名';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.BENEFCIARY_ID IS '受益人ID';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.BENEFCIARY_NAME IS '受益人名称';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.GUARANTEE_MODE IS '担保方式';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.CONTRACT_STATUS IS '合同状态';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.SIGNING_DATE IS '签署日期';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.COMPANY_ID IS '公司ID';
COMMENT ON COLUMN TBL_GUARANTEE_CONTRACT.COMPANY_NAME IS '公司名称';

CREATE INDEX IDX_GC_CONTRACT_NO ON TBL_GUARANTEE_CONTRACT(CONTRACT_NO);
CREATE INDEX IDX_GC_APPLICATION_ID ON TBL_GUARANTEE_CONTRACT(APPLICATION_ID);
CREATE INDEX IDX_GC_COMPANY_ID ON TBL_GUARANTEE_CONTRACT(COMPANY_ID);
CREATE INDEX IDX_GC_STATUS ON TBL_GUARANTEE_CONTRACT(CONTRACT_STATUS);

-- 1.3 担保物表
CREATE TABLE TBL_COLLATERAL (
    COLLATERAL_ID BIGINT PRIMARY KEY,
    COLLATERAL_NO VARCHAR(50) UNIQUE NOT NULL,
    COLLATERAL_TYPE VARCHAR(20) NOT NULL,
    COLLATERAL_NAME VARCHAR(200),
    COLLATERAL_VALUE DECIMAL(18,2) NOT NULL,
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    EVALUATION_VALUE DECIMAL(18,2),
    EVALUATION_DATE DATE,
    EVALUATION_AGENCY VARCHAR(200),
    COLLATERAL_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    OWNER_ID BIGINT,
    OWNER_NAME VARCHAR(100),
    LOCATION VARCHAR(500),
    CONTRACT_ID BIGINT,
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    FOREIGN KEY (CONTRACT_ID) REFERENCES TBL_GUARANTEE_CONTRACT(CONTRACT_ID)
);

COMMENT ON TABLE TBL_COLLATERAL IS '担保物表';
COMMENT ON COLUMN TBL_COLLATERAL.COLLATERAL_ID IS '担保物ID';
COMMENT ON COLUMN TBL_COLLATERAL.COLLATERAL_NO IS '担保物编号';
COMMENT ON COLUMN TBL_COLLATERAL.COLLATERAL_TYPE IS '担保物类型';
COMMENT ON COLUMN TBL_COLLATERAL.COLLATERAL_NAME IS '担保物名称';
COMMENT ON COLUMN TBL_COLLATERAL.COLLATERAL_VALUE IS '担保物价值';
COMMENT ON COLUMN TBL_COLLATERAL.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_COLLATERAL.EVALUATION_VALUE IS '评估价值';
COMMENT ON COLUMN TBL_COLLATERAL.EVALUATION_DATE IS '评估日期';
COMMENT ON COLUMN TBL_COLLATERAL.EVALUATION_AGENCY IS '评估机构';
COMMENT ON COLUMN TBL_COLLATERAL.COLLATERAL_STATUS IS '担保物状态';
COMMENT ON COLUMN TBL_COLLATERAL.OWNER_ID IS '所有者ID';
COMMENT ON COLUMN TBL_COLLATERAL.OWNER_NAME IS '所有者姓名';
COMMENT ON COLUMN TBL_COLLATERAL.LOCATION IS '存放地点';
COMMENT ON COLUMN TBL_COLLATERAL.CONTRACT_ID IS '关联合同ID';
COMMENT ON COLUMN TBL_COLLATERAL.COMPANY_ID IS '公司ID';
COMMENT ON COLUMN TBL_COLLATERAL.COMPANY_NAME IS '公司名称';

CREATE INDEX IDX_COLLATERAL_NO ON TBL_COLLATERAL(COLLATERAL_NO);
CREATE INDEX IDX_COLLATERAL_TYPE ON TBL_COLLATERAL(COLLATERAL_TYPE);
CREATE INDEX IDX_COLLATERAL_CONTRACT_ID ON TBL_COLLATERAL(CONTRACT_ID);
CREATE INDEX IDX_COLLATERAL_COMPANY_ID ON TBL_COLLATERAL(COMPANY_ID);

-- ============================================================
-- 第二部分: 授信业务相关表
-- ============================================================

-- 2.1 金融机构表(主数据表)
CREATE TABLE TBL_FINANCIAL_INSTITUTION (
    INSTITUTION_ID BIGINT PRIMARY KEY,
    INSTITUTION_CODE VARCHAR(20) UNIQUE NOT NULL,
    INSTITUTION_NAME VARCHAR(200) NOT NULL,
    INSTITUTION_TYPE VARCHAR(20),
    LEGAL_REPRESENTATIVE VARCHAR(100),
    REGISTERED_CAPITAL DECIMAL(18,2),
    REGISTERED_ADDRESS VARCHAR(500),
    BUSINESS_SCOPE VARCHAR(1000),
    CREDIT_RATING VARCHAR(10),
    CONTACT_PERSON VARCHAR(100),
    CONTACT_PHONE VARCHAR(20),
    CONTACT_EMAIL VARCHAR(100),
    WEBSITE VARCHAR(200),
    STATUS INT DEFAULT 1,
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_FINANCIAL_INSTITUTION IS '金融机构表';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.INSTITUTION_ID IS '机构ID';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.INSTITUTION_CODE IS '机构编码';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.INSTITUTION_NAME IS '机构名称';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.INSTITUTION_TYPE IS '机构类型';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.LEGAL_REPRESENTATIVE IS '法定代表人';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.REGISTERED_CAPITAL IS '注册资本';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.REGISTERED_ADDRESS IS '注册地址';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.BUSINESS_SCOPE IS '经营范围';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.CREDIT_RATING IS '信用评级';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.CONTACT_PERSON IS '联系人';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.CONTACT_PHONE IS '联系电话';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.CONTACT_EMAIL IS '联系邮箱';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.WEBSITE IS '网站';
COMMENT ON COLUMN TBL_FINANCIAL_INSTITUTION.STATUS IS '状态';

CREATE INDEX IDX_FI_CODE ON TBL_FINANCIAL_INSTITUTION(INSTITUTION_CODE);
CREATE INDEX IDX_FI_TYPE ON TBL_FINANCIAL_INSTITUTION(INSTITUTION_TYPE);
CREATE INDEX IDX_FI_NAME ON TBL_FINANCIAL_INSTITUTION(INSTITUTION_NAME);

-- 2.2 授信申请表
CREATE TABLE TBL_CREDIT_APPLICATION (
    APPLICATION_ID BIGINT PRIMARY KEY,
    APPLICATION_NO VARCHAR(50) UNIQUE NOT NULL,
    CREDIT_TYPE VARCHAR(20) NOT NULL,
    APPLIED_AMOUNT DECIMAL(18,2) NOT NULL,
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    CREDIT_PURPOSE VARCHAR(500),
    CREDIT_PERIOD INT,
    PERIOD_UNIT VARCHAR(10),
    INTEREST_RATE DECIMAL(8,4),
    FINANCIAL_INSTITUTION_ID BIGINT,
    FINANCIAL_INSTITUTION_NAME VARCHAR(200),
    APPLICATION_STATUS VARCHAR(20) DEFAULT 'PENDING',
    APPLICATION_DATE DATE,
    APPROVAL_DATE DATE,
    APPROVAL_AMOUNT DECIMAL(18,2),
    APPROVAL_OPINION VARCHAR(500),
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    FOREIGN KEY (FINANCIAL_INSTITUTION_ID) REFERENCES TBL_FINANCIAL_INSTITUTION(INSTITUTION_ID)
);

COMMENT ON TABLE TBL_CREDIT_APPLICATION IS '授信申请表';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.APPLICATION_ID IS '申请ID';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.APPLICATION_NO IS '申请编号';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.CREDIT_TYPE IS '授信类型';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.APPLIED_AMOUNT IS '申请金额';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.CREDIT_PURPOSE IS '授信用途';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.CREDIT_PERIOD IS '授信期限';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.PERIOD_UNIT IS '期限单位';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.INTEREST_RATE IS '利率';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.FINANCIAL_INSTITUTION_ID IS '金融机构ID';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.FINANCIAL_INSTITUTION_NAME IS '金融机构名称';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.APPLICATION_STATUS IS '申请状态';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.APPLICATION_DATE IS '申请日期';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.APPROVAL_DATE IS '审批日期';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.APPROVAL_AMOUNT IS '审批金额';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.APPROVAL_OPINION IS '审批意见';

CREATE INDEX IDX_CA_APPLICATION_NO ON TBL_CREDIT_APPLICATION(APPLICATION_NO);
CREATE INDEX IDX_CA_INSTITUTION_ID ON TBL_CREDIT_APPLICATION(FINANCIAL_INSTITUTION_ID);
CREATE INDEX IDX_CA_COMPANY_ID ON TBL_CREDIT_APPLICATION(COMPANY_ID);
CREATE INDEX IDX_CA_STATUS ON TBL_CREDIT_APPLICATION(APPLICATION_STATUS);
CREATE INDEX IDX_CA_APPLICATION_DATE ON TBL_CREDIT_APPLICATION(APPLICATION_DATE);

-- 2.3 授信合同表
CREATE TABLE TBL_CREDIT_CONTRACT (
    CONTRACT_ID BIGINT PRIMARY KEY,
    CONTRACT_NO VARCHAR(50) UNIQUE NOT NULL,
    APPLICATION_ID BIGINT,
    CREDIT_TYPE VARCHAR(20) NOT NULL,
    CREDIT_LIMIT DECIMAL(18,2) NOT NULL,
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    USED_AMOUNT DECIMAL(18,2) DEFAULT 0,
    AVAILABLE_AMOUNT DECIMAL(18,2),
    INTEREST_RATE DECIMAL(8,4),
    CREDIT_PERIOD INT,
    PERIOD_UNIT VARCHAR(10),
    START_DATE DATE,
    END_DATE DATE,
    FINANCIAL_INSTITUTION_ID BIGINT,
    FINANCIAL_INSTITUTION_NAME VARCHAR(200),
    CONTRACT_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    SIGNING_DATE DATE,
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    FOREIGN KEY (APPLICATION_ID) REFERENCES TBL_CREDIT_APPLICATION(APPLICATION_ID),
    FOREIGN KEY (FINANCIAL_INSTITUTION_ID) REFERENCES TBL_FINANCIAL_INSTITUTION(INSTITUTION_ID)
);

COMMENT ON TABLE TBL_CREDIT_CONTRACT IS '授信合同表';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.CONTRACT_ID IS '合同ID';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.CONTRACT_NO IS '合同编号';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.APPLICATION_ID IS '申请ID';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.CREDIT_TYPE IS '授信类型';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.CREDIT_LIMIT IS '授信额度';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.USED_AMOUNT IS '已用额度';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.AVAILABLE_AMOUNT IS '可用额度';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.INTEREST_RATE IS '利率';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.CREDIT_PERIOD IS '授信期限';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.PERIOD_UNIT IS '期限单位';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.START_DATE IS '开始日期';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.END_DATE IS '结束日期';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.FINANCIAL_INSTITUTION_ID IS '金融机构ID';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.FINANCIAL_INSTITUTION_NAME IS '金融机构名称';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.CONTRACT_STATUS IS '合同状态';
COMMENT ON COLUMN TBL_CREDIT_CONTRACT.SIGNING_DATE IS '签署日期';

CREATE INDEX IDX_CC_CONTRACT_NO ON TBL_CREDIT_CONTRACT(CONTRACT_NO);
CREATE INDEX IDX_CC_APPLICATION_ID ON TBL_CREDIT_CONTRACT(APPLICATION_ID);
CREATE INDEX IDX_CC_INSTITUTION_ID ON TBL_CREDIT_CONTRACT(FINANCIAL_INSTITUTION_ID);
CREATE INDEX IDX_CC_COMPANY_ID ON TBL_CREDIT_CONTRACT(COMPANY_ID);
CREATE INDEX IDX_CC_STATUS ON TBL_CREDIT_CONTRACT(CONTRACT_STATUS);

-- 2.4 授信额度表
CREATE TABLE TBL_CREDIT_LIMIT (
    LIMIT_ID BIGINT PRIMARY KEY,
    CONTRACT_ID BIGINT NOT NULL,
    LIMIT_TYPE VARCHAR(20),
    TOTAL_LIMIT DECIMAL(18,2) NOT NULL,
    USED_LIMIT DECIMAL(18,2) DEFAULT 0,
    AVAILABLE_LIMIT DECIMAL(18,2),
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    LIMIT_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    FOREIGN KEY (CONTRACT_ID) REFERENCES TBL_CREDIT_CONTRACT(CONTRACT_ID)
);

COMMENT ON TABLE TBL_CREDIT_LIMIT IS '授信额度表';
COMMENT ON COLUMN TBL_CREDIT_LIMIT.LIMIT_ID IS '额度ID';
COMMENT ON COLUMN TBL_CREDIT_LIMIT.CONTRACT_ID IS '合同ID';
COMMENT ON COLUMN TBL_CREDIT_LIMIT.LIMIT_TYPE IS '额度类型';
COMMENT ON COLUMN TBL_CREDIT_LIMIT.TOTAL_LIMIT IS '总额度';
COMMENT ON COLUMN TBL_CREDIT_LIMIT.USED_LIMIT IS '已用额度';
COMMENT ON COLUMN TBL_CREDIT_LIMIT.AVAILABLE_LIMIT IS '可用额度';
COMMENT ON COLUMN TBL_CREDIT_LIMIT.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_CREDIT_LIMIT.LIMIT_STATUS IS '额度状态';
COMMENT ON COLUMN TBL_CREDIT_LIMIT.EFFECTIVE_DATE IS '生效日期';
COMMENT ON COLUMN TBL_CREDIT_LIMIT.EXPIRY_DATE IS '到期日期';

CREATE INDEX IDX_CL_CONTRACT_ID ON TBL_CREDIT_LIMIT(CONTRACT_ID);
CREATE INDEX IDX_CL_COMPANY_ID ON TBL_CREDIT_LIMIT(COMPANY_ID);
CREATE INDEX IDX_CL_STATUS ON TBL_CREDIT_LIMIT(LIMIT_STATUS);

-- ============================================================
-- 第三部分: 银行贷款、票据、融资租赁表
-- ============================================================

-- 3.1 银行贷款表
CREATE TABLE TBL_BANK_LOAN (
    LOAN_ID BIGINT PRIMARY KEY,
    LOAN_NO VARCHAR(50) UNIQUE NOT NULL,
    CONTRACT_ID BIGINT,
    LOAN_TYPE VARCHAR(20),
    LOAN_AMOUNT DECIMAL(18,2) NOT NULL,
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    INTEREST_RATE DECIMAL(8,4),
    LOAN_PERIOD INT,
    PERIOD_UNIT VARCHAR(10),
    START_DATE DATE,
    END_DATE DATE,
    PAYMENT_METHOD VARCHAR(20),
    FINANCIAL_INSTITUTION_ID BIGINT,
    FINANCIAL_INSTITUTION_NAME VARCHAR(200),
    LOAN_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    DRAWDOWN_DATE DATE,
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    FOREIGN KEY (CONTRACT_ID) REFERENCES TBL_CREDIT_CONTRACT(CONTRACT_ID),
    FOREIGN KEY (FINANCIAL_INSTITUTION_ID) REFERENCES TBL_FINANCIAL_INSTITUTION(INSTITUTION_ID)
);

COMMENT ON TABLE TBL_BANK_LOAN IS '银行贷款表';
COMMENT ON COLUMN TBL_BANK_LOAN.LOAN_ID IS '贷款ID';
COMMENT ON COLUMN TBL_BANK_LOAN.LOAN_NO IS '贷款编号';
COMMENT ON COLUMN TBL_BANK_LOAN.CONTRACT_ID IS '合同ID';
COMMENT ON COLUMN TBL_BANK_LOAN.LOAN_TYPE IS '贷款类型';
COMMENT ON COLUMN TBL_BANK_LOAN.LOAN_AMOUNT IS '贷款金额';
COMMENT ON COLUMN TBL_BANK_LOAN.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_BANK_LOAN.INTEREST_RATE IS '利率';
COMMENT ON COLUMN TBL_BANK_LOAN.LOAN_PERIOD IS '贷款期限';
COMMENT ON COLUMN TBL_BANK_LOAN.PERIOD_UNIT IS '期限单位';
COMMENT ON COLUMN TBL_BANK_LOAN.START_DATE IS '开始日期';
COMMENT ON COLUMN TBL_BANK_LOAN.END_DATE IS '结束日期';
COMMENT ON COLUMN TBL_BANK_LOAN.PAYMENT_METHOD IS '还款方式';
COMMENT ON COLUMN TBL_BANK_LOAN.FINANCIAL_INSTITUTION_ID IS '金融机构ID';
COMMENT ON COLUMN TBL_BANK_LOAN.FINANCIAL_INSTITUTION_NAME IS '金融机构名称';
COMMENT ON COLUMN TBL_BANK_LOAN.LOAN_STATUS IS '贷款状态';
COMMENT ON COLUMN TBL_BANK_LOAN.DRAWDOWN_DATE IS '放款日期';

CREATE INDEX IDX_BL_LOAN_NO ON TBL_BANK_LOAN(LOAN_NO);
CREATE INDEX IDX_BL_CONTRACT_ID ON TBL_BANK_LOAN(CONTRACT_ID);
CREATE INDEX IDX_BL_INSTITUTION_ID ON TBL_BANK_LOAN(FINANCIAL_INSTITUTION_ID);
CREATE INDEX IDX_BL_COMPANY_ID ON TBL_BANK_LOAN(COMPANY_ID);
CREATE INDEX IDX_BL_STATUS ON TBL_BANK_LOAN(LOAN_STATUS);

-- 3.2 票据贴现表
CREATE TABLE TBL_BILL_DISCOUNT (
    DISCOUNT_ID BIGINT PRIMARY KEY,
    DISCOUNT_NO VARCHAR(50) UNIQUE NOT NULL,
    BILL_TYPE VARCHAR(20),
    BILL_NO VARCHAR(50),
    BILL_AMOUNT DECIMAL(18,2) NOT NULL,
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    DISCOUNT_RATE DECIMAL(8,4),
    DISCOUNT_AMOUNT DECIMAL(18,2),
    DISCOUNT_PERIOD INT,
    BILL_ISSUE_DATE DATE,
    BILL_MATURITY_DATE DATE,
    DISCOUNT_DATE DATE,
    ACCEPTOR_NAME VARCHAR(200),
    DRAWER_NAME VARCHAR(200),
    PAYEE_NAME VARCHAR(200),
    FINANCIAL_INSTITUTION_ID BIGINT,
    FINANCIAL_INSTITUTION_NAME VARCHAR(200),
    DISCOUNT_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    FOREIGN KEY (FINANCIAL_INSTITUTION_ID) REFERENCES TBL_FINANCIAL_INSTITUTION(INSTITUTION_ID)
);

COMMENT ON TABLE TBL_BILL_DISCOUNT IS '票据贴现表';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_ID IS '贴现ID';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_NO IS '贴现编号';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.BILL_TYPE IS '票据类型';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.BILL_NO IS '票据号码';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.BILL_AMOUNT IS '票据金额';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_RATE IS '贴现率';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_AMOUNT IS '贴现金额';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_PERIOD IS '贴现期限';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.BILL_ISSUE_DATE IS '票据出票日期';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.BILL_MATURITY_DATE IS '票据到期日期';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_DATE IS '贴现日期';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.ACCEPTOR_NAME IS '承兑人名称';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DRAWER_NAME IS '出票人名称';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.PAYEE_NAME IS '收款人名称';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.FINANCIAL_INSTITUTION_ID IS '金融机构ID';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.FINANCIAL_INSTITUTION_NAME IS '金融机构名称';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_STATUS IS '贴现状态';

CREATE INDEX IDX_BD_DISCOUNT_NO ON TBL_BILL_DISCOUNT(DISCOUNT_NO);
CREATE INDEX IDX_BD_BILL_NO ON TBL_BILL_DISCOUNT(BILL_NO);
CREATE INDEX IDX_BD_INSTITUTION_ID ON TBL_BILL_DISCOUNT(FINANCIAL_INSTITUTION_ID);
CREATE INDEX IDX_BD_COMPANY_ID ON TBL_BILL_DISCOUNT(COMPANY_ID);
CREATE INDEX IDX_BD_STATUS ON TBL_BILL_DISCOUNT(DISCOUNT_STATUS);
CREATE INDEX IDX_BD_DISCOUNT_DATE ON TBL_BILL_DISCOUNT(DISCOUNT_DATE);

-- 3.3 银行承兑表
CREATE TABLE TBL_BILL_ACCEPTANCE (
    ACCEPTANCE_ID BIGINT PRIMARY KEY,
    ACCEPTANCE_NO VARCHAR(50) UNIQUE NOT NULL,
    BILL_TYPE VARCHAR(20),
    BILL_NO VARCHAR(50),
    BILL_AMOUNT DECIMAL(18,2) NOT NULL,
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    ACCEPTANCE_PERIOD INT,
    PERIOD_UNIT VARCHAR(10),
    ISSUE_DATE DATE,
    MATURITY_DATE DATE,
    ACCEPTANCE_RATE DECIMAL(8,4),
    ACCEPTANCE_FEE DECIMAL(18,2),
    DRAWER_NAME VARCHAR(200),
    PAYEE_NAME VARCHAR(200),
    ACCEPTOR_NAME VARCHAR(200),
    FINANCIAL_INSTITUTION_ID BIGINT,
    FINANCIAL_INSTITUTION_NAME VARCHAR(200),
    ACCEPTANCE_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    FOREIGN KEY (FINANCIAL_INSTITUTION_ID) REFERENCES TBL_FINANCIAL_INSTITUTION(INSTITUTION_ID)
);

COMMENT ON TABLE TBL_BILL_ACCEPTANCE IS '银行承兑表';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.ACCEPTANCE_ID IS '承兑ID';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.ACCEPTANCE_NO IS '承兑编号';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.BILL_TYPE IS '票据类型';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.BILL_NO IS '票据号码';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.BILL_AMOUNT IS '票据金额';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.ACCEPTANCE_PERIOD IS '承兑期限';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.PERIOD_UNIT IS '期限单位';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.ISSUE_DATE IS '出票日期';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.MATURITY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.ACCEPTANCE_RATE IS '承兑费率';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.ACCEPTANCE_FEE IS '承兑费用';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.DRAWER_NAME IS '出票人名称';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.PAYEE_NAME IS '收款人名称';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.ACCEPTOR_NAME IS '承兑人名称';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.FINANCIAL_INSTITUTION_ID IS '金融机构ID';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.FINANCIAL_INSTITUTION_NAME IS '金融机构名称';
COMMENT ON COLUMN TBL_BILL_ACCEPTANCE.ACCEPTANCE_STATUS IS '承兑状态';

CREATE INDEX IDX_BA_ACCEPTANCE_NO ON TBL_BILL_ACCEPTANCE(ACCEPTANCE_NO);
CREATE INDEX IDX_BA_BILL_NO ON TBL_BILL_ACCEPTANCE(BILL_NO);
CREATE INDEX IDX_BA_INSTITUTION_ID ON TBL_BILL_ACCEPTANCE(FINANCIAL_INSTITUTION_ID);
CREATE INDEX IDX_BA_COMPANY_ID ON TBL_BILL_ACCEPTANCE(COMPANY_ID);
CREATE INDEX IDX_BA_STATUS ON TBL_BILL_ACCEPTANCE(ACCEPTANCE_STATUS);
CREATE INDEX IDX_BA_ISSUE_DATE ON TBL_BILL_ACCEPTANCE(ISSUE_DATE);

-- 3.4 融资租赁表
CREATE TABLE TBL_FINANCIAL_LEASE (
    LEASE_ID BIGINT PRIMARY KEY,
    LEASE_NO VARCHAR(50) UNIQUE NOT NULL,
    PLAN_ID BIGINT,
    LEASE_TYPE VARCHAR(20),
    ASSET_NAME VARCHAR(200),
    ASSET_VALUE DECIMAL(18,2) NOT NULL,
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    LEASE_AMOUNT DECIMAL(18,2),
    LEASE_PERIOD INT,
    PERIOD_UNIT VARCHAR(10),
    LEASE_RATE DECIMAL(8,4),
    START_DATE DATE,
    END_DATE DATE,
    PAYMENT_METHOD VARCHAR(20),
    LEASING_COMPANY_ID BIGINT,
    LEASING_COMPANY_NAME VARCHAR(200),
    LEASE_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    SIGNING_DATE DATE,
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    DELETE_FLAG INT DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    FOREIGN KEY (PLAN_ID) REFERENCES TBL_FINANCING_PLAN(PLAN_ID)
);

COMMENT ON TABLE TBL_FINANCIAL_LEASE IS '融资租赁表';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASE_ID IS '租赁ID';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASE_NO IS '租赁编号';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.PLAN_ID IS '融资计划ID';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASE_TYPE IS '租赁类型';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.ASSET_NAME IS '资产名称';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.ASSET_VALUE IS '资产价值';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASE_AMOUNT IS '租赁金额';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASE_PERIOD IS '租赁期限';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.PERIOD_UNIT IS '期限单位';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASE_RATE IS '租赁费率';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.START_DATE IS '开始日期';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.END_DATE IS '结束日期';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.PAYMENT_METHOD IS '支付方式';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASING_COMPANY_ID IS '租赁公司ID';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASING_COMPANY_NAME IS '租赁公司名称';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASE_STATUS IS '租赁状态';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.SIGNING_DATE IS '签署日期';

CREATE INDEX IDX_FL_LEASE_NO ON TBL_FINANCIAL_LEASE(LEASE_NO);
CREATE INDEX IDX_FL_PLAN_ID ON TBL_FINANCIAL_LEASE(PLAN_ID);
CREATE INDEX IDX_FL_COMPANY_ID ON TBL_FINANCIAL_LEASE(COMPANY_ID);
CREATE INDEX IDX_FL_STATUS ON TBL_FINANCIAL_LEASE(LEASE_STATUS);
CREATE INDEX IDX_FL_SIGNING_DATE ON TBL_FINANCIAL_LEASE(SIGNING_DATE);

-- ============================================================
-- 脚本结束
-- ============================================================
