-- 融资基础参数表
-- 兼容达梦数据库
CREATE TABLE TBL_FINANCING_BASIC_PARAMS (
    PARAM_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    PARAM_CODE VARCHAR(50) NOT NULL,
    PARAM_NAME VARCHAR(200) NOT NULL,
    PARAM_TYPE VARCHAR(50) NOT NULL,
    PARAM_VALUE VARCHAR(500),
    PARAM_DESC VARCHAR(1000),
    STATUS VARCHAR(20) DEFAULT 'ENABLE',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER BIGINT,
    UPDATE_USER BIGINT,
    ORG_ID BIGINT NOT NULL,
    REMARK VARCHAR(1000)
);