-- =====================================================
-- 财资公共模块 - 基础配置管理组 数据库表设计
-- 兼容达梦数据库和Oracle数据库
-- =====================================================

-- 1. Ukey厂商管理表
CREATE TABLE TC_UKEY_VENDOR (
    ID VARCHAR2(32) NOT NULL,
    VENDOR_CODE VARCHAR2(20) NOT NULL,
    VENDOR_NAME VARCHAR2(100) NOT NULL,
    VENDOR_SHORT_NAME VARCHAR2(50),
    VENDOR_EN_NAME VARCHAR2(100),
    ESTABLISH_DATE DATE,
    REGISTER_ADDRESS VARCHAR2(500),
    BUSINESS_SCOPE VARCHAR2(1000),
    CONTACT_PHONE VARCHAR2(50),
    TECH_SUPPORT_PHONE VARCHAR2(50),
    OFFICIAL_WEBSITE VARCHAR2(200),
    LICENSE_NO VARCHAR2(50),
    TECH_CERT_NO VARCHAR2(50),
    SECURITY_LEVEL VARCHAR2(20),
    ENCRYPTION_ALGORITHMS VARCHAR2(200),
    STORAGE_CAPACITY VARCHAR2(50),
    CERT_LIMIT NUMBER(10),
    PIN_LENGTH_REQ NUMBER(2),
    DRIVER_VERSION VARCHAR2(50),
    INTERFACE_PROTOCOL VARCHAR2(50),
    SERVICE_RATING VARCHAR2(10),
    STATUS VARCHAR2(10) DEFAULT '1',
    REMARK VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(32),
    UPDATE_USER VARCHAR2(32),
    VERSION_NO NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_TC_UKEY_VENDOR PRIMARY KEY (ID),
    CONSTRAINT UK_TC_UKEY_VENDOR_CODE UNIQUE (VENDOR_CODE)
);

-- 2. 安全配置表
CREATE TABLE TC_SECURITY_CONFIG (
    ID VARCHAR2(32) NOT NULL,
    CONFIG_TYPE VARCHAR2(50) NOT NULL,
    CONFIG_KEY VARCHAR2(100) NOT NULL,
    CONFIG_VALUE VARCHAR2(500),
    CONFIG_DESC VARCHAR2(200),
    DEFAULT_VALUE VARCHAR2(500),
    VALUE_TYPE VARCHAR2(20) DEFAULT 'STRING',
    IS_REQUIRED VARCHAR2(1) DEFAULT '0',
    SORT_ORDER NUMBER(5) DEFAULT 0,
    STATUS VARCHAR2(10) DEFAULT '1',
    REMARK VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(32),
    UPDATE_USER VARCHAR2(32),
    VERSION_NO NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_TC_SECURITY_CONFIG PRIMARY KEY (ID),
    CONSTRAINT UK_TC_SECURITY_CONFIG_KEY UNIQUE (CONFIG_TYPE, CONFIG_KEY)
);

-- 3. 业务系统注册表
CREATE TABLE TC_BUSINESS_SYSTEM (
    ID VARCHAR2(32) NOT NULL,
    SYSTEM_CODE VARCHAR2(50) NOT NULL,
    SYSTEM_NAME VARCHAR2(100) NOT NULL,
    SYSTEM_TYPE VARCHAR2(50),
    SYSTEM_DESC VARCHAR2(500),
    INTERFACE_URL VARCHAR2(200),
    INTERFACE_PORT NUMBER(5),
    AUTH_TYPE VARCHAR2(20),
    AUTH_CONFIG VARCHAR2(1000),
    DATA_FORMAT VARCHAR2(20),
    CONNECTION_STATUS VARCHAR2(20),
    LAST_CONNECT_TIME DATE,
    CONNECT_TIMEOUT NUMBER(10) DEFAULT 30000,
    READ_TIMEOUT NUMBER(10) DEFAULT 60000,
    RETRY_COUNT NUMBER(2) DEFAULT 3,
    STATUS VARCHAR2(10) DEFAULT '1',
    REMARK VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(32),
    UPDATE_USER VARCHAR2(32),
    VERSION_NO NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_TC_BUSINESS_SYSTEM PRIMARY KEY (ID),
    CONSTRAINT UK_TC_BUSINESS_SYSTEM_CODE UNIQUE (SYSTEM_CODE)
);

-- 4. 数据映射配置表
CREATE TABLE TC_DATA_MAPPING (
    ID VARCHAR2(32) NOT NULL,
    SYSTEM_ID VARCHAR2(32) NOT NULL,
    MAPPING_NAME VARCHAR2(100),
    SOURCE_FIELD VARCHAR2(100) NOT NULL,
    TARGET_FIELD VARCHAR2(100) NOT NULL,
    FIELD_TYPE VARCHAR2(20),
    CONVERSION_RULE VARCHAR2(500),
    DEFAULT_VALUE VARCHAR2(200),
    IS_REQUIRED VARCHAR2(1) DEFAULT '0',
    VALIDATION_RULE VARCHAR2(500),
    ERROR_STRATEGY VARCHAR2(20) DEFAULT 'IGNORE',
    SORT_ORDER NUMBER(5) DEFAULT 0,
    STATUS VARCHAR2(10) DEFAULT '1',
    REMARK VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(32),
    UPDATE_USER VARCHAR2(32),
    VERSION_NO NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_TC_DATA_MAPPING PRIMARY KEY (ID),
    CONSTRAINT FK_TC_DATA_MAPPING_SYSTEM FOREIGN KEY (SYSTEM_ID) REFERENCES TC_BUSINESS_SYSTEM(ID)
);

-- 5. 印鉴类型表
CREATE TABLE TC_SEAL_TYPE (
    ID VARCHAR2(32) NOT NULL,
    TYPE_CODE VARCHAR2(20) NOT NULL,
    TYPE_NAME VARCHAR2(50) NOT NULL,
    TYPE_DESC VARCHAR2(200),
    USAGE_SCOPE VARCHAR2(100),
    PERMISSION_LEVEL VARCHAR2(20),
    SORT_ORDER NUMBER(5) DEFAULT 0,
    STATUS VARCHAR2(10) DEFAULT '1',
    REMARK VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(32),
    UPDATE_USER VARCHAR2(32),
    VERSION_NO NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_TC_SEAL_TYPE PRIMARY KEY (ID),
    CONSTRAINT UK_TC_SEAL_TYPE_CODE UNIQUE (TYPE_CODE)
);

-- 6. 印鉴档案表
CREATE TABLE TC_SEAL_ARCHIVE (
    ID VARCHAR2(32) NOT NULL,
    SEAL_CODE VARCHAR2(50) NOT NULL,
    SEAL_NAME VARCHAR2(100) NOT NULL,
    SEAL_TYPE_ID VARCHAR2(32) NOT NULL,
    SEAL_SPEC VARCHAR2(50),
    SEAL_MATERIAL VARCHAR2(50),
    SEAL_IMAGE_PATH VARCHAR2(500),
    OWNER_NAME VARCHAR2(50),
    OWNER_POSITION VARCHAR2(50),
    USAGE_PERMISSION VARCHAR2(100),
    SEAL_STATUS VARCHAR2(20) DEFAULT 'NORMAL',
    EFFECTIVE_DATE DATE,
    EXPIRE_DATE DATE,
    LOSS_REPORT_DATE DATE,
    CANCEL_DATE DATE,
    STATUS VARCHAR2(10) DEFAULT '1',
    REMARK VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(32),
    UPDATE_USER VARCHAR2(32),
    VERSION_NO NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_TC_SEAL_ARCHIVE PRIMARY KEY (ID),
    CONSTRAINT UK_TC_SEAL_ARCHIVE_CODE UNIQUE (SEAL_CODE),
    CONSTRAINT FK_TC_SEAL_ARCHIVE_TYPE FOREIGN KEY (SEAL_TYPE_ID) REFERENCES TC_SEAL_TYPE(ID)
);

-- 7. 印鉴组合表
CREATE TABLE TC_SEAL_COMBINATION (
    ID VARCHAR2(32) NOT NULL,
    COMBINATION_CODE VARCHAR2(50) NOT NULL,
    COMBINATION_NAME VARCHAR2(100) NOT NULL,
    BUSINESS_SCENARIO VARCHAR2(100),
    COMBINATION_DESC VARCHAR2(500),
    APPROVAL_LEVEL VARCHAR2(20),
    USAGE_RULE VARCHAR2(500),
    TIME_LIMIT VARCHAR2(100),
    LOCATION_LIMIT VARCHAR2(100),
    STATUS VARCHAR2(10) DEFAULT '1',
    REMARK VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(32),
    UPDATE_USER VARCHAR2(32),
    VERSION_NO NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_TC_SEAL_COMBINATION PRIMARY KEY (ID),
    CONSTRAINT UK_TC_SEAL_COMBINATION_CODE UNIQUE (COMBINATION_CODE)
);

-- 8. 印鉴组合明细表
CREATE TABLE TC_SEAL_COMBINATION_DETAIL (
    ID VARCHAR2(32) NOT NULL,
    COMBINATION_ID VARCHAR2(32) NOT NULL,
    SEAL_ID VARCHAR2(32) NOT NULL,
    IS_REQUIRED VARCHAR2(1) DEFAULT '1',
    USAGE_ORDER NUMBER(3) DEFAULT 1,
    ALTERNATIVE_SEAL_ID VARCHAR2(32),
    USAGE_CONDITION VARCHAR2(200),
    STATUS VARCHAR2(10) DEFAULT '1',
    REMARK VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(32),
    UPDATE_USER VARCHAR2(32),
    VERSION_NO NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_TC_SEAL_COMBINATION_DETAIL PRIMARY KEY (ID),
    CONSTRAINT FK_TC_SEAL_COMB_DETAIL_COMB FOREIGN KEY (COMBINATION_ID) REFERENCES TC_SEAL_COMBINATION(ID),
    CONSTRAINT FK_TC_SEAL_COMB_DETAIL_SEAL FOREIGN KEY (SEAL_ID) REFERENCES TC_SEAL_ARCHIVE(ID),
    CONSTRAINT FK_TC_SEAL_COMB_DETAIL_ALT FOREIGN KEY (ALTERNATIVE_SEAL_ID) REFERENCES TC_SEAL_ARCHIVE(ID)
);

-- 9. 印鉴使用记录表
CREATE TABLE TC_SEAL_USAGE_LOG (
    ID VARCHAR2(32) NOT NULL,
    COMBINATION_ID VARCHAR2(32),
    SEAL_ID VARCHAR2(32),
    BUSINESS_DOC_NO VARCHAR2(50),
    BUSINESS_TYPE VARCHAR2(50),
    USAGE_PURPOSE VARCHAR2(200),
    USAGE_USER VARCHAR2(32),
    USAGE_TIME DATE,
    USAGE_LOCATION VARCHAR2(100),
    APPROVAL_USER VARCHAR2(32),
    APPROVAL_TIME DATE,
    USAGE_RESULT VARCHAR2(20),
    EXCEPTION_REASON VARCHAR2(500),
    IP_ADDRESS VARCHAR2(50),
    MAC_ADDRESS VARCHAR2(50),
    STATUS VARCHAR2(10) DEFAULT '1',
    REMARK VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(32),
    UPDATE_USER VARCHAR2(32),
    VERSION_NO NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_TC_SEAL_USAGE_LOG PRIMARY KEY (ID),
    CONSTRAINT FK_TC_SEAL_USAGE_LOG_COMB FOREIGN KEY (COMBINATION_ID) REFERENCES TC_SEAL_COMBINATION(ID),
    CONSTRAINT FK_TC_SEAL_USAGE_LOG_SEAL FOREIGN KEY (SEAL_ID) REFERENCES TC_SEAL_ARCHIVE(ID)
);

-- 10. 虚拟账户表
CREATE TABLE TC_VIRTUAL_ACCOUNT (
    ID VARCHAR2(32) NOT NULL,
    ACCOUNT_CODE VARCHAR2(50) NOT NULL,
    ACCOUNT_NAME VARCHAR2(100) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(20) NOT NULL,
    PLATFORM_NAME VARCHAR2(50),
    ACCOUNT_NO VARCHAR2(100),
    ACCOUNT_HOLDER VARCHAR2(100),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    BALANCE NUMBER(18,2) DEFAULT 0,
    AVAILABLE_BALANCE NUMBER(18,2) DEFAULT 0,
    FROZEN_BALANCE NUMBER(18,2) DEFAULT 0,
    LAST_SYNC_TIME DATE,
    SYNC_STATUS VARCHAR2(20),
    SYNC_FREQUENCY VARCHAR2(20),
    RELATED_BANK_ACCOUNT VARCHAR2(50),
    API_CONFIG VARCHAR2(1000),
    STATUS VARCHAR2(10) DEFAULT '1',
    REMARK VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(32),
    UPDATE_USER VARCHAR2(32),
    VERSION_NO NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_TC_VIRTUAL_ACCOUNT PRIMARY KEY (ID),
    CONSTRAINT UK_TC_VIRTUAL_ACCOUNT_CODE UNIQUE (ACCOUNT_CODE)
);

-- 11. 电票账户设置表
CREATE TABLE TC_ETICKET_ACCOUNT (
    ID VARCHAR2(32) NOT NULL,
    BANK_ACCOUNT_ID VARCHAR2(32),
    BANK_CODE VARCHAR2(20),
    BANK_NAME VARCHAR2(100),
    ACCOUNT_NO VARCHAR2(50),
    CUSTOMER_NO VARCHAR2(50),
    ETICKET_STATUS VARCHAR2(20) DEFAULT 'INACTIVE',
    BUSINESS_SCOPE VARCHAR2(200),
    CURRENCY_CODES VARCHAR2(100) DEFAULT 'CNY',
    DAILY_LIMIT NUMBER(18,2),
    MONTHLY_LIMIT NUMBER(18,2),
    INTERFACE_URL VARCHAR2(200),
    INTERFACE_PORT NUMBER(5),
    CERT_PATH VARCHAR2(500),
    CERT_PASSWORD VARCHAR2(100),
    OPERATOR_INFO VARCHAR2(500),
    TIMEOUT_SETTING NUMBER(10) DEFAULT 30000,
    RETRY_COUNT NUMBER(2) DEFAULT 3,
    LAST_CONNECT_TIME DATE,
    CONNECTION_STATUS VARCHAR2(20),
    STATUS VARCHAR2(10) DEFAULT '1',
    REMARK VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(32),
    UPDATE_USER VARCHAR2(32),
    VERSION_NO NUMBER(10) DEFAULT 0,
    CONSTRAINT PK_TC_ETICKET_ACCOUNT PRIMARY KEY (ID)
);

-- =====================================================
-- 创建索引
-- =====================================================

-- Ukey厂商表索引
CREATE INDEX IDX_TC_UKEY_VENDOR_STATUS ON TC_UKEY_VENDOR(STATUS);
CREATE INDEX IDX_TC_UKEY_VENDOR_RATING ON TC_UKEY_VENDOR(SERVICE_RATING);

-- 安全配置表索引
CREATE INDEX IDX_TC_SECURITY_CONFIG_TYPE ON TC_SECURITY_CONFIG(CONFIG_TYPE);
CREATE INDEX IDX_TC_SECURITY_CONFIG_STATUS ON TC_SECURITY_CONFIG(STATUS);

-- 业务系统注册表索引
CREATE INDEX IDX_TC_BUSINESS_SYSTEM_TYPE ON TC_BUSINESS_SYSTEM(SYSTEM_TYPE);
CREATE INDEX IDX_TC_BUSINESS_SYSTEM_STATUS ON TC_BUSINESS_SYSTEM(STATUS);
CREATE INDEX IDX_TC_BUSINESS_SYSTEM_CONN ON TC_BUSINESS_SYSTEM(CONNECTION_STATUS);

-- 数据映射配置表索引
CREATE INDEX IDX_TC_DATA_MAPPING_SYSTEM ON TC_DATA_MAPPING(SYSTEM_ID);
CREATE INDEX IDX_TC_DATA_MAPPING_STATUS ON TC_DATA_MAPPING(STATUS);

-- 印鉴类型表索引
CREATE INDEX IDX_TC_SEAL_TYPE_STATUS ON TC_SEAL_TYPE(STATUS);

-- 印鉴档案表索引
CREATE INDEX IDX_TC_SEAL_ARCHIVE_TYPE ON TC_SEAL_ARCHIVE(SEAL_TYPE_ID);
CREATE INDEX IDX_TC_SEAL_ARCHIVE_STATUS ON TC_SEAL_ARCHIVE(STATUS);
CREATE INDEX IDX_TC_SEAL_ARCHIVE_SEAL_STATUS ON TC_SEAL_ARCHIVE(SEAL_STATUS);
CREATE INDEX IDX_TC_SEAL_ARCHIVE_OWNER ON TC_SEAL_ARCHIVE(OWNER_NAME);

-- 印鉴组合表索引
CREATE INDEX IDX_TC_SEAL_COMBINATION_SCENARIO ON TC_SEAL_COMBINATION(BUSINESS_SCENARIO);
CREATE INDEX IDX_TC_SEAL_COMBINATION_STATUS ON TC_SEAL_COMBINATION(STATUS);

-- 印鉴组合明细表索引
CREATE INDEX IDX_TC_SEAL_COMB_DETAIL_COMB ON TC_SEAL_COMBINATION_DETAIL(COMBINATION_ID);
CREATE INDEX IDX_TC_SEAL_COMB_DETAIL_SEAL ON TC_SEAL_COMBINATION_DETAIL(SEAL_ID);

-- 印鉴使用记录表索引
CREATE INDEX IDX_TC_SEAL_USAGE_LOG_COMB ON TC_SEAL_USAGE_LOG(COMBINATION_ID);
CREATE INDEX IDX_TC_SEAL_USAGE_LOG_SEAL ON TC_SEAL_USAGE_LOG(SEAL_ID);
CREATE INDEX IDX_TC_SEAL_USAGE_LOG_USER ON TC_SEAL_USAGE_LOG(USAGE_USER);
CREATE INDEX IDX_TC_SEAL_USAGE_LOG_TIME ON TC_SEAL_USAGE_LOG(USAGE_TIME);
CREATE INDEX IDX_TC_SEAL_USAGE_LOG_DOC ON TC_SEAL_USAGE_LOG(BUSINESS_DOC_NO);

-- 虚拟账户表索引
CREATE INDEX IDX_TC_VIRTUAL_ACCOUNT_TYPE ON TC_VIRTUAL_ACCOUNT(ACCOUNT_TYPE);
CREATE INDEX IDX_TC_VIRTUAL_ACCOUNT_STATUS ON TC_VIRTUAL_ACCOUNT(STATUS);
CREATE INDEX IDX_TC_VIRTUAL_ACCOUNT_SYNC ON TC_VIRTUAL_ACCOUNT(SYNC_STATUS);

-- 电票账户设置表索引
CREATE INDEX IDX_TC_ETICKET_ACCOUNT_BANK ON TC_ETICKET_ACCOUNT(BANK_CODE);
CREATE INDEX IDX_TC_ETICKET_ACCOUNT_STATUS ON TC_ETICKET_ACCOUNT(STATUS);
CREATE INDEX IDX_TC_ETICKET_ACCOUNT_ETICKET ON TC_ETICKET_ACCOUNT(ETICKET_STATUS);

-- =====================================================
-- 表注释
-- =====================================================

COMMENT ON TABLE TC_UKEY_VENDOR IS 'Ukey厂商管理表';
COMMENT ON TABLE TC_SECURITY_CONFIG IS '安全配置表';
COMMENT ON TABLE TC_BUSINESS_SYSTEM IS '业务系统注册表';
COMMENT ON TABLE TC_DATA_MAPPING IS '数据映射配置表';
COMMENT ON TABLE TC_SEAL_TYPE IS '印鉴类型表';
COMMENT ON TABLE TC_SEAL_ARCHIVE IS '印鉴档案表';
COMMENT ON TABLE TC_SEAL_COMBINATION IS '印鉴组合表';
COMMENT ON TABLE TC_SEAL_COMBINATION_DETAIL IS '印鉴组合明细表';
COMMENT ON TABLE TC_SEAL_USAGE_LOG IS '印鉴使用记录表';
COMMENT ON TABLE TC_VIRTUAL_ACCOUNT IS '虚拟账户表';
COMMENT ON TABLE TC_ETICKET_ACCOUNT IS '电票账户设置表';
