-- =====================================================
-- 财资公共模块 - 基础配置管理组 初始化数据
-- =====================================================

-- 1. Ukey厂商初始化数据
INSERT INTO TC_UKEY_VENDOR (ID, VENDOR_CODE, VENDOR_NAME, VENDOR_SHORT_NAME, VENDOR_EN_NAME, ENCRYPTION_ALGORITHMS, INTERFACE_PROTOCOL, SERVICE_RATING, STATUS, CREATE_USER, UPDATE_USER) VALUES
('UV001', 'FEITIAN', '飞天诚信科技股份有限公司', '飞天诚信', 'Feitian Technologies Co., Ltd.', 'RSA,ECC,SM2', 'PKCS#11', 'A', '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_UKEY_VENDOR (ID, VENDOR_CODE, VENDOR_NAME, VENDOR_SHORT_NAME, VENDOR_EN_NAME, ENCRYPTION_ALGORITHMS, INTERFACE_PROTOCOL, SERVICE_RATING, STATUS, CREATE_USER, UPDATE_USER) VALUES
('UV002', 'WATCHDATA', '握奇数据股份有限公司', '握奇数据', 'Watchdata Co., Ltd.', 'RSA,ECC,SM2', 'PKCS#11', 'A', '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_UKEY_VENDOR (ID, VENDOR_CODE, VENDOR_NAME, VENDOR_SHORT_NAME, VENDOR_EN_NAME, ENCRYPTION_ALGORITHMS, INTERFACE_PROTOCOL, SERVICE_RATING, STATUS, CREATE_USER, UPDATE_USER) VALUES
('UV003', 'CEC_HUADA', '华大电子有限公司', '华大电子', 'China Electronics Corporation Huada Electronic Co., Ltd.', 'RSA,ECC,SM2', 'PKCS#11', 'B', '1', 'SYSTEM', 'SYSTEM');

-- 2. 安全配置初始化数据
-- 密码策略配置
INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC001', 'PASSWORD_POLICY', 'MIN_LENGTH', '8', '密码最小长度', '8', 'NUMBER', '1', 1, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC002', 'PASSWORD_POLICY', 'REQUIRE_UPPERCASE', '1', '是否要求大写字母', '1', 'BOOLEAN', '1', 2, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC003', 'PASSWORD_POLICY', 'REQUIRE_LOWERCASE', '1', '是否要求小写字母', '1', 'BOOLEAN', '1', 3, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC004', 'PASSWORD_POLICY', 'REQUIRE_DIGIT', '1', '是否要求数字', '1', 'BOOLEAN', '1', 4, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC005', 'PASSWORD_POLICY', 'REQUIRE_SPECIAL', '1', '是否要求特殊字符', '1', 'BOOLEAN', '1', 5, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC006', 'PASSWORD_POLICY', 'EXPIRE_DAYS', '90', '密码有效期（天）', '90', 'NUMBER', '1', 6, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC007', 'PASSWORD_POLICY', 'HISTORY_COUNT', '5', '密码历史记录数量', '5', 'NUMBER', '1', 7, '1', 'SYSTEM', 'SYSTEM');

-- 登录控制配置
INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC008', 'LOGIN_CONTROL', 'MAX_FAIL_COUNT', '5', '最大登录失败次数', '5', 'NUMBER', '1', 1, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC009', 'LOGIN_CONTROL', 'LOCK_DURATION', '30', '账户锁定时间（分钟）', '30', 'NUMBER', '1', 2, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC010', 'LOGIN_CONTROL', 'AUTO_UNLOCK', '1', '是否自动解锁', '1', 'BOOLEAN', '1', 3, '1', 'SYSTEM', 'SYSTEM');

-- 会话管理配置
INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC011', 'SESSION_MANAGEMENT', 'TIMEOUT_MINUTES', '30', '会话超时时间（分钟）', '30', 'NUMBER', '1', 1, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC012', 'SESSION_MANAGEMENT', 'WARNING_MINUTES', '5', '超时前提醒时间（分钟）', '5', 'NUMBER', '1', 2, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC013', 'SESSION_MANAGEMENT', 'MAX_CONCURRENT', '3', '最大并发会话数', '3', 'NUMBER', '1', 3, '1', 'SYSTEM', 'SYSTEM');

-- 加密设置配置
INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC014', 'ENCRYPTION_SETTINGS', 'FORCE_HTTPS', '1', '强制HTTPS传输', '1', 'BOOLEAN', '1', 1, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC015', 'ENCRYPTION_SETTINGS', 'MIN_TLS_VERSION', '1.2', '最低TLS版本', '1.2', 'STRING', '1', 2, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SECURITY_CONFIG (ID, CONFIG_TYPE, CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, DEFAULT_VALUE, VALUE_TYPE, IS_REQUIRED, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('SC016', 'ENCRYPTION_SETTINGS', 'DATA_ENCRYPTION', 'AES-256', '数据加密算法', 'AES-256', 'STRING', '1', 3, '1', 'SYSTEM', 'SYSTEM');

-- 3. 印鉴类型初始化数据
INSERT INTO TC_SEAL_TYPE (ID, TYPE_CODE, TYPE_NAME, TYPE_DESC, USAGE_SCOPE, PERMISSION_LEVEL, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('ST001', 'CORPORATE', '企业公章', '企业法人公章', '对外合同签署、重要文件', 'HIGH', 1, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SEAL_TYPE (ID, TYPE_CODE, TYPE_NAME, TYPE_DESC, USAGE_SCOPE, PERMISSION_LEVEL, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('ST002', 'FINANCIAL', '财务专用章', '财务业务专用章', '财务凭证、银行业务', 'HIGH', 2, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SEAL_TYPE (ID, TYPE_CODE, TYPE_NAME, TYPE_DESC, USAGE_SCOPE, PERMISSION_LEVEL, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('ST003', 'LEGAL_PERSON', '法人章', '法定代表人印章', '重要合同、银行开户', 'HIGH', 3, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SEAL_TYPE (ID, TYPE_CODE, TYPE_NAME, TYPE_DESC, USAGE_SCOPE, PERMISSION_LEVEL, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('ST004', 'CONTRACT', '合同专用章', '合同签署专用章', '合同签署、协议签订', 'MEDIUM', 4, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SEAL_TYPE (ID, TYPE_CODE, TYPE_NAME, TYPE_DESC, USAGE_SCOPE, PERMISSION_LEVEL, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('ST005', 'INVOICE', '发票专用章', '发票开具专用章', '发票开具、税务业务', 'MEDIUM', 5, '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_SEAL_TYPE (ID, TYPE_CODE, TYPE_NAME, TYPE_DESC, USAGE_SCOPE, PERMISSION_LEVEL, SORT_ORDER, STATUS, CREATE_USER, UPDATE_USER) VALUES
('ST006', 'PERSONAL', '个人签名章', '个人签名印章', '个人签名、授权确认', 'LOW', 6, '1', 'SYSTEM', 'SYSTEM');

-- 4. 虚拟账户类型初始化数据（示例）
INSERT INTO TC_VIRTUAL_ACCOUNT (ID, ACCOUNT_CODE, ACCOUNT_NAME, ACCOUNT_TYPE, PLATFORM_NAME, CURRENCY_CODE, STATUS, CREATE_USER, UPDATE_USER) VALUES
('VA001', 'WECHAT_PAY_001', '微信支付账户', 'WECHAT', '微信支付', 'CNY', '1', 'SYSTEM', 'SYSTEM');

INSERT INTO TC_VIRTUAL_ACCOUNT (ID, ACCOUNT_CODE, ACCOUNT_NAME, ACCOUNT_TYPE, PLATFORM_NAME, CURRENCY_CODE, STATUS, CREATE_USER, UPDATE_USER) VALUES
('VA002', 'ALIPAY_001', '支付宝账户', 'ALIPAY', '支付宝', 'CNY', '1', 'SYSTEM', 'SYSTEM');

-- 提交事务
COMMIT;
