-- =====================================================
-- 更新银行贷款测试数据 - 填充新增字段
-- 生成时间: 2026-02-09
-- 说明: 为现有测试数据添加贷款期限、还款方式、担保方式等字段值
-- 前置条件: 先执行 alter_bank_loan_add_fields.sql 添加字段
-- =====================================================

-- 更新测试数据1: 流动资金贷款
UPDATE TBL_BANK_LOAN SET 
    LOAN_PERIOD = 12, 
    PERIOD_UNIT = 'MONTH', 
    PAYMENT_METHOD = 'INTEREST_FIRST', 
    GUARANTEE_TYPE = 'CREDIT',
    GUARANTEE_AMOUNT = NULL,
    REMARK = '流动资金周转'
WHERE LOAN_ID = 1001;

-- 更新测试数据2: 设备采购贷款
UPDATE TBL_BANK_LOAN SET 
    LOAN_PERIOD = 36, 
    PERIOD_UNIT = 'MONTH', 
    PAYMENT_METHOD = 'EQUAL_PRINCIPAL', 
    GUARANTEE_TYPE = 'PLEDGE',
    GUARANTEE_AMOUNT = 12000000.00,
    REMARK = '设备采购专项贷款'
WHERE LOAN_ID = 1002;

-- 更新测试数据3: 循环贷款
UPDATE TBL_BANK_LOAN SET 
    LOAN_PERIOD = 24, 
    PERIOD_UNIT = 'MONTH', 
    PAYMENT_METHOD = 'BULLET', 
    GUARANTEE_TYPE = 'CREDIT',
    GUARANTEE_AMOUNT = NULL,
    REMARK = '循环使用额度'
WHERE LOAN_ID = 1003;

-- 更新测试数据4: 厂房抵押贷款
UPDATE TBL_BANK_LOAN SET 
    LOAN_PERIOD = 5, 
    PERIOD_UNIT = 'YEAR', 
    PAYMENT_METHOD = 'EQUAL_INSTALLMENT', 
    GUARANTEE_TYPE = 'MORTGAGE',
    GUARANTEE_AMOUNT = 30000000.00,
    REMARK = '厂房抵押贷款'
WHERE LOAN_ID = 1004;

-- 更新测试数据5: 担保贷款申请
UPDATE TBL_BANK_LOAN SET 
    LOAN_PERIOD = 24, 
    PERIOD_UNIT = 'MONTH', 
    PAYMENT_METHOD = 'EQUAL_PRINCIPAL', 
    GUARANTEE_TYPE = 'GUARANTEE',
    GUARANTEE_AMOUNT = 10000000.00,
    REMARK = '第三方担保贷款'
WHERE LOAN_ID = 1005;

-- 更新测试数据6: 农业生产贷款
UPDATE TBL_BANK_LOAN SET 
    LOAN_PERIOD = 12, 
    PERIOD_UNIT = 'MONTH', 
    PAYMENT_METHOD = 'INTEREST_FIRST', 
    GUARANTEE_TYPE = 'CREDIT',
    GUARANTEE_AMOUNT = NULL,
    REMARK = '农业生产周转资金'
WHERE LOAN_ID = 1006;

-- 更新测试数据7: 新能源项目贷款
UPDATE TBL_BANK_LOAN SET 
    LOAN_PERIOD = 48, 
    PERIOD_UNIT = 'MONTH', 
    PAYMENT_METHOD = 'EQUAL_INSTALLMENT', 
    GUARANTEE_TYPE = 'PLEDGE',
    GUARANTEE_AMOUNT = 20000000.00,
    REMARK = '新能源项目专项贷款'
WHERE LOAN_ID = 1007;

-- 更新测试数据8: 外币贷款
UPDATE TBL_BANK_LOAN SET 
    LOAN_PERIOD = 12, 
    PERIOD_UNIT = 'MONTH', 
    PAYMENT_METHOD = 'BULLET', 
    GUARANTEE_TYPE = 'CREDIT',
    GUARANTEE_AMOUNT = NULL,
    REMARK = '外币流动资金贷款'
WHERE LOAN_ID = 1008;

-- 更新测试数据9: 已结清贷款
UPDATE TBL_BANK_LOAN SET 
    LOAN_PERIOD = 36, 
    PERIOD_UNIT = 'MONTH', 
    PAYMENT_METHOD = 'EQUAL_PRINCIPAL', 
    GUARANTEE_TYPE = 'MORTGAGE',
    GUARANTEE_AMOUNT = 8000000.00,
    REMARK = '已结清的抵押贷款'
WHERE LOAN_ID = 1009;

-- 更新测试数据10: 已审批待放款
UPDATE TBL_BANK_LOAN SET 
    LOAN_PERIOD = 24, 
    PERIOD_UNIT = 'MONTH', 
    PAYMENT_METHOD = 'EQUAL_INSTALLMENT', 
    GUARANTEE_TYPE = 'GUARANTEE',
    GUARANTEE_AMOUNT = 6000000.00,
    REMARK = '待放款担保贷款'
WHERE LOAN_ID = 1010;

-- 提交
COMMIT;

-- 验证更新结果
SELECT LOAN_ID, LOAN_NO, LOAN_PERIOD, PERIOD_UNIT, PAYMENT_METHOD, GUARANTEE_TYPE, GUARANTEE_AMOUNT, REMARK
FROM TBL_BANK_LOAN
WHERE DELETE_FLAG = 0
ORDER BY LOAN_ID;

