server:
  port: 8064
  max-http-header-size: 500MB
  jetty: 
    max-http-form-post-size: 500MB
 
spring:
  profiles:
    active: dev
  servlet: 
    multipart: 
      max-request-size: 500MB
      max-file-size: 500MB
  main:
    allow-circular-references: true
  springdoc:
    swagger-ui:
      enabled: true
    api-docs:
      enabled: true
      

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json