
#搜索接口
searchurl=https://api.yonyoucloud.com/apis/dst/Search/search

#工商信息
gsxxurl=https://api.yonyoucloud.com/apis/dst/baseinfo/baseinfoV3

#====背景信息
#变更信息
changeurl=https://api.yonyoucloud.com/apis/dst/background/changeinfo
#企业年报
qynburl=https://api.yonyoucloud.com/apis/dst/background/annualreport
#分支机构
fzjgurl=https://api.yonyoucloud.com/apis/dst/background/branch
#主要人员
zyrrurl=https://api.yonyoucloud.com/apis/dst/background/staff
#股东信息
gdxxurl=https://api.yonyoucloud.com/apis/dst/background/holder
#对外投资
dwtzurl=https://api.yonyoucloud.com/apis/dst/background/inverst





#===经营状况
#招投标
mangeurl=https://api.yonyoucloud.com/apis/dst/businesscircumstance/bids
#税务评级
swpjurl=https://api.yonyoucloud.com/apis/dst/businesscircumstance/taxCredit
#抽查检查
ccjcurl=https://api.yonyoucloud.com/apis/dst/businesscircumstance/checkInfo
#债券信息
zqxxurl=https://api.yonyoucloud.com/apis/dst/businesscircumstance/bond
#招聘
zpurl=https://api.yonyoucloud.com/apis/dst/businesscircumstance/employments





#===经营风险
#行政处罚
businriskurl=https://api.yonyoucloud.com/open/dst/Businessrisk/punishmentInfo
#行政处罚（信用中国）
xzcfurl=https://api.yonyoucloud.com/open/dst/Businessrisk/creditChina
#股权出质
gqczurl=https://api.yonyoucloud.com/open/dst/Businessrisk/equityInfo
#严重违法
yzwfurl=https://api.yonyoucloud.com/open/dst/Businessrisk/illegalinfo
#动产抵押
dcdyurl=https://api.yonyoucloud.com/open/dst/Businessrisk/mortgageInfo
#司法拍卖
sfpmurl=https://api.yonyoucloud.com/open/dst/Businessrisk/judicialSale
#欠税公告
qsggurl=https://api.yonyoucloud.com/open/dst/Businessrisk/ownTax
#经营异常
jyycurl=https://api.yonyoucloud.com/open/dst/Businessrisk/abnormal



#===司法风险
#法院公告
judicialurl=https://api.yonyoucloud.com/apis/dst/judicalrisk/courtAnnouncement
#失信人
sxrurl=https://api.yonyoucloud.com/apis/dst/judicalrisk/dishonest
#法律诉讼
flssurl=https://api.yonyoucloud.com/apis/dst/judicalrisk/lawSuit
#被执行人
bzxryrl=https://api.yonyoucloud.com/apis/dst/judicalrisk/zhixinginfo
#开庭公告
ktggurl=https://api.yonyoucloud.com/apis/dst/judicalrisk/ktannouncement






#===发展信息
#投资事件
developmenturl=https://api.yonyoucloud.com/apis/dst/develop/findTzanli
#融资历史
rzllurl=https://api.yonyoucloud.com/apis/dst/develop/findHistoryRongzi
#核心团队
hxtdurl=https://api.yonyoucloud.com/apis/dst/develop/findTeamMember
#竞品信息
jpxxurl=https://api.yonyoucloud.com/apis/dst/develop/findJingpin
#企业业务
qyywurl=https://api.yonyoucloud.com/apis/dst/develop/getProductInfo






#舆情信息
opeinurl=https://api.yonyoucloud.com/apis/dst/publicsentiment/news

#===关系发现
#关系图谱
relaurl=https://api.yonyoucloud.com/apis/dst/relationshipdiscovery/oneKey
#股权结构图
gqjgturl=https://api.yonyoucloud.com/apis/dst/relationshipdiscovery/equityRatio
#投资族谱对外接口
tzzudwjkurl=https://api.yonyoucloud.com/apis/dst/relationshipdiscovery/investtree

#知识产权
#行政许可
xzxkurl=https://api.yonyoucloud.com/apis/dst/patents/getLicense
#网站备案
wzbaurl=https://api.yonyoucloud.com/apis/dst/patents/icp
#专利信息
zlxxurl=https://api.yonyoucloud.com/apis/dst/patents/patents
#著作权
zzqurl=https://api.yonyoucloud.com/apis/dst/patents/copyReg
#产品信息
cpxxurl=https://api.yonyoucloud.com/apis/dst/patents/appbkInfo
#证书
zsurl=https://api.yonyoucloud.com/apis/dst/patents/certificate
#高管
ggurl=https://api.yonyoucloud.com/apis/dst/gsmarket/seniorExecutive
#企业简介
qyjjurl=https://api.yonyoucloud.com/apis/dst/gsmarket/companyInfo


#用户购买接口后的权限APICODE
#//搜索接口   个人                                                           
#APICODE_SEARCH = 
#//公司 
APICODE_SEARCH =                                                             


#//企业工商信息查询【加强版】  个人                                                         
#APICODE_GSXX =
#//公司     
APICODE_GSXX = 

#//企业工商信息查询【上市信息】                                                          
#APICODE_SSXX = 
#//公司     
APICODE_SSXX = 

#//背景信息  个人                                                          
#APICODE_CHANGE = 
#//公司
APICODE_CHANGE =                                                                                     


#//经营状况   个人                                                           
#APICODE_MANAGE = 
#//公司
APICODE_MANAGE =                                   


#//经营风险  个人                                                             
#APICODE_RISK = 
#//公司     
APICODE_RISK =                                           


#// 司法风险   个人                                                             
#APICODE_JUDICAL = 
#//公司
APICODE_JUDICAL =                                                             


#//发展信息  个人                                                             
#APICODE_DEVE = 
#//公司 
APICODE_DEVE =                                                        


#//舆情信息  个人                                                              
#APICODE_OPIN =
#//公司          
APICODE_OPIN =                                                             


#//关系发现  个人              未使用                                                    
#APICODE_RELA = 
#//公司         
APICODE_RELA = 



#//知识产权  个人                                                       
#INTELLECTUAL_PROPERTY= 
#//公司         
INTELLECTUAL_PROPERTY = 
