-- =============================================
-- 电票账户配置表 - 添加缺失的ETICKET_ACCOUNT_ID列
-- 表名: TC_ETICKET_ACCOUNT
-- 描述: 为现有表添加ETICKET_ACCOUNT_ID主键列
-- 作者: 华博云开发团队
-- 创建时间: 2024-12-24
-- 兼容性: 达梦数据库 (DM Database)
-- =============================================

-- 检查表是否存在
-- SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'TC_ETICKET_ACCOUNT';

-- 方案1: 如果表已有数据但没有主键列,先添加ID列并填充数据
ALTER TABLE TC_ETICKET_ACCOUNT ADD ETICKET_ACCOUNT_ID DECIMAL(20,0);

-- 为现有数据生成ID(如果表中有数据)
-- UPDATE TC_ETICKET_ACCOUNT SET ETICKET_ACCOUNT_ID = ROWID WHERE ETICKET_ACCOUNT_ID IS NULL;

-- 或者使用序列生成ID
-- CREATE SEQUENCE SEQ_ETICKET_ACCOUNT_ID START WITH 1 INCREMENT BY 1;
-- UPDATE TC_ETICKET_ACCOUNT SET ETICKET_ACCOUNT_ID = SEQ_ETICKET_ACCOUNT_ID.NEXTVAL WHERE ETICKET_ACCOUNT_ID IS NULL;

-- 设置列为NOT NULL
ALTER TABLE TC_ETICKET_ACCOUNT MODIFY ETICKET_ACCOUNT_ID NOT NULL;

-- 添加主键约束
ALTER TABLE TC_ETICKET_ACCOUNT ADD CONSTRAINT PK_ETICKET_ACCOUNT PRIMARY KEY (ETICKET_ACCOUNT_ID);

-- 添加列注释
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ETICKET_ACCOUNT_ID IS '电票账户ID(主键)';

-- 提交事务
COMMIT;

-- 验证结果
-- SELECT * FROM TC_ETICKET_ACCOUNT WHERE ROWNUM <= 5;
