-- =============================================================
-- TBL_BILL_POOL 表结构完整修复脚本 - 达梦数据库
-- 说明: 添加代码中使用但数据库表中缺失的所有列
-- 执行时间: 2026-02-03
-- 注意: 如果某列已存在会报错，可以忽略该错误继续执行
-- =============================================================

-- ==================== 基础字段 ====================

-- 添加 POOL_NAME 列（票据池名称）
-- ALTER TABLE TBL_BILL_POOL ADD COLUMN POOL_NAME VARCHAR(200);
-- COMMENT ON COLUMN TBL_BILL_POOL.POOL_NAME IS '票据池名称';

-- 添加 POOL_CODE 列（票据池编码）
ALTER TABLE TBL_BILL_POOL ADD COLUMN POOL_CODE VARCHAR(50);
COMMENT ON COLUMN TBL_BILL_POOL.POOL_CODE IS '票据池编码';

-- 添加 POOL_TYPE 列（票据池类型）
ALTER TABLE TBL_BILL_POOL ADD COLUMN POOL_TYPE VARCHAR(20);
COMMENT ON COLUMN TBL_BILL_POOL.POOL_TYPE IS '票据池类型';

-- 添加 POOL_STATUS 列（票据池状态）
ALTER TABLE TBL_BILL_POOL ADD COLUMN POOL_STATUS VARCHAR(20);
COMMENT ON COLUMN TBL_BILL_POOL.POOL_STATUS IS '票据池状态';

-- ==================== 所有者信息 ====================

-- 添加 OWNER_ID 列（所有者ID）
ALTER TABLE TBL_BILL_POOL ADD COLUMN OWNER_ID DECIMAL(20,0);
COMMENT ON COLUMN TBL_BILL_POOL.OWNER_ID IS '所有者ID';

-- 添加 OWNER_NAME 列（所有者名称）
ALTER TABLE TBL_BILL_POOL ADD COLUMN OWNER_NAME VARCHAR(200);
COMMENT ON COLUMN TBL_BILL_POOL.OWNER_NAME IS '所有者名称';

-- ==================== 金额统计字段 ====================

-- 添加 TOTAL_AMOUNT 列（总金额）
ALTER TABLE TBL_BILL_POOL ADD COLUMN TOTAL_AMOUNT DECIMAL(18,2) DEFAULT 0;
COMMENT ON COLUMN TBL_BILL_POOL.TOTAL_AMOUNT IS '总金额';

-- 添加 BILL_COUNT 列（票据数量）
ALTER TABLE TBL_BILL_POOL ADD COLUMN BILL_COUNT INTEGER DEFAULT 0;
COMMENT ON COLUMN TBL_BILL_POOL.BILL_COUNT IS '票据数量';

-- ==================== 业务扩展字段 ====================

-- 添加 POOL_PURPOSE 列（票据池用途）
ALTER TABLE TBL_BILL_POOL ADD COLUMN POOL_PURPOSE VARCHAR(200);
COMMENT ON COLUMN TBL_BILL_POOL.POOL_PURPOSE IS '票据池用途';

-- 添加 MAX_POOL_VALUE 列（最大池值）
ALTER TABLE TBL_BILL_POOL ADD COLUMN MAX_POOL_VALUE DECIMAL(18,2);
COMMENT ON COLUMN TBL_BILL_POOL.MAX_POOL_VALUE IS '最大池值';

-- 添加 MIN_BILL_VALUE 列（最小票据金额）
ALTER TABLE TBL_BILL_POOL ADD COLUMN MIN_BILL_VALUE DECIMAL(18,2);
COMMENT ON COLUMN TBL_BILL_POOL.MIN_BILL_VALUE IS '最小票据金额';

-- 添加 PLEDGE_RATE 列（质押率）
ALTER TABLE TBL_BILL_POOL ADD COLUMN PLEDGE_RATE DECIMAL(10,4);
COMMENT ON COLUMN TBL_BILL_POOL.PLEDGE_RATE IS '质押率';

-- 添加 FINANCING_AMOUNT 列（融资金额）
ALTER TABLE TBL_BILL_POOL ADD COLUMN FINANCING_AMOUNT DECIMAL(18,2);
COMMENT ON COLUMN TBL_BILL_POOL.FINANCING_AMOUNT IS '融资金额';

-- 添加 ALLOWED_BILL_TYPES 列（允许的票据类型）
ALTER TABLE TBL_BILL_POOL ADD COLUMN ALLOWED_BILL_TYPES VARCHAR(500);
COMMENT ON COLUMN TBL_BILL_POOL.ALLOWED_BILL_TYPES IS '允许的票据类型';

-- 添加 POOL_RULES 列（票据池规则）
ALTER TABLE TBL_BILL_POOL ADD COLUMN POOL_RULES VARCHAR(1000);
COMMENT ON COLUMN TBL_BILL_POOL.POOL_RULES IS '票据池规则';

-- ==================== 时间和审计字段 ====================

-- 添加 CREATE_TIME 列（创建时间）
ALTER TABLE TBL_BILL_POOL ADD COLUMN CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
COMMENT ON COLUMN TBL_BILL_POOL.CREATE_TIME IS '创建时间';

-- 添加 UPDATE_TIME 列（更新时间）
ALTER TABLE TBL_BILL_POOL ADD COLUMN UPDATE_TIME TIMESTAMP;
COMMENT ON COLUMN TBL_BILL_POOL.UPDATE_TIME IS '更新时间';

-- 添加 CREATE_USER 列（创建人）
ALTER TABLE TBL_BILL_POOL ADD COLUMN CREATE_USER VARCHAR(50);
COMMENT ON COLUMN TBL_BILL_POOL.CREATE_USER IS '创建人';

-- 添加 UPDATE_USER 列（更新人）
ALTER TABLE TBL_BILL_POOL ADD COLUMN UPDATE_USER VARCHAR(50);
COMMENT ON COLUMN TBL_BILL_POOL.UPDATE_USER IS '更新人';

-- 添加 DELETE_FLAG 列（删除标记）
ALTER TABLE TBL_BILL_POOL ADD COLUMN DELETE_FLAG INTEGER DEFAULT 0;
COMMENT ON COLUMN TBL_BILL_POOL.DELETE_FLAG IS '删除标记(0:未删除 1:已删除)';

-- ==================== 创建索引 ====================
-- 如果索引已存在会报错，可忽略
CREATE INDEX IDX_BILL_POOL_CODE ON TBL_BILL_POOL(POOL_CODE);
CREATE INDEX IDX_BILL_POOL_OWNER ON TBL_BILL_POOL(OWNER_ID);
CREATE INDEX IDX_BILL_POOL_STATUS ON TBL_BILL_POOL(POOL_STATUS);

COMMIT;

-- =============================================================
-- 验证脚本（执行后检查表结构）
-- =============================================================
-- SELECT COLUMN_NAME, DATA_TYPE FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_BILL_POOL';
-- SELECT * FROM TBL_BILL_POOL;

