-- 融资租赁表添加缺失字段
-- 执行时间: 2026-02-09
-- 说明: 添加资产名称、资产价值、支付方式、备注、租赁期限等字段

-- 添加资产名称字段
ALTER TABLE TBL_FINANCIAL_LEASE ADD ASSET_NAME VARCHAR2(200);
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.ASSET_NAME IS '资产名称';

-- 添加资产价值字段
ALTER TABLE TBL_FINANCIAL_LEASE ADD ASSET_VALUE NUMBER(20,2);
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.ASSET_VALUE IS '资产价值';

-- 添加支付方式字段
ALTER TABLE TBL_FINANCIAL_LEASE ADD PAYMENT_METHOD VARCHAR2(50);
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.PAYMENT_METHOD IS '支付方式(EQUAL_PRINCIPAL_INTEREST/EQUAL_PRINCIPAL/INTEREST_FIRST/LUMP_SUM)';

-- 添加备注字段
ALTER TABLE TBL_FINANCIAL_LEASE ADD REMARK VARCHAR2(500);
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.REMARK IS '备注';

-- 添加租赁期限字段
ALTER TABLE TBL_FINANCIAL_LEASE ADD LEASE_PERIOD NUMBER(10);
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASE_PERIOD IS '租赁期限';

-- 添加期限单位字段
ALTER TABLE TBL_FINANCIAL_LEASE ADD PERIOD_UNIT VARCHAR2(20) DEFAULT 'MONTH';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.PERIOD_UNIT IS '期限单位(MONTH/YEAR)';

