-- ===================================================================
-- 数据源配置表结构升级SQL
-- 达梦数据库(DM8)兼容Oracle语法
-- 创建时间: 2026-01-30
-- 说明: 为现有表添加缺失的字段
-- ===================================================================

-- 添加缺失的字段
ALTER TABLE TC_DATA_SOURCE_CONFIG ADD CONNECTION_URL VARCHAR(500);
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CONNECTION_URL IS '连接地址';

ALTER TABLE TC_DATA_SOURCE_CONFIG ADD USERNAME VARCHAR(100);
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.USERNAME IS '用户名';

ALTER TABLE TC_DATA_SOURCE_CONFIG ADD PASSWORD VARCHAR(500);
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.PASSWORD IS '密码(加密存储)';

ALTER TABLE TC_DATA_SOURCE_CONFIG ADD ENVIRONMENT VARCHAR(32);
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.ENVIRONMENT IS '环境类型: DEV/TEST/UAT/PROD';

ALTER TABLE TC_DATA_SOURCE_CONFIG ADD CONNECTION_STATUS VARCHAR(32) DEFAULT 'UNTESTED';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CONNECTION_STATUS IS '连接状态: UNTESTED/NORMAL/ERROR/DISABLED';

ALTER TABLE TC_DATA_SOURCE_CONFIG ADD LAST_TEST_TIME DATE;
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.LAST_TEST_TIME IS '最后测试时间';

ALTER TABLE TC_DATA_SOURCE_CONFIG ADD IS_ENABLED VARCHAR(1) DEFAULT '1';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.IS_ENABLED IS '是否启用: 1-是 0-否';

ALTER TABLE TC_DATA_SOURCE_CONFIG ADD API_CONFIG VARCHAR(2000);
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.API_CONFIG IS 'API配置(JSON格式)';

ALTER TABLE TC_DATA_SOURCE_CONFIG ADD DESCRIPTION VARCHAR(1000);
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.DESCRIPTION IS '数据源描述';

-- 注意：ERROR_COUNT, MAX_ERROR_COUNT, TIMEOUT_SECONDS, RETRY_COUNT 这些字段在原表中可能已存在
-- 如果不存在则添加，如果已存在则忽略
BEGIN
    -- 检查并添加ERROR_COUNT字段
    SELECT COUNT(*) INTO COLUMN_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TC_DATA_SOURCE_CONFIG' AND COLUMN_NAME = 'ERROR_COUNT';
    IF COLUMN_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TC_DATA_SOURCE_CONFIG ADD ERROR_COUNT INT DEFAULT 0';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.ERROR_COUNT IS ''错误次数''';
    END IF;
END;
/

-- 简化版：直接添加已知的缺失字段（如果字段已存在会报错，可以忽略）
-- 如果字段已存在，达梦数据库会报错，但不会影响后续操作

ALTER TABLE TC_DATA_SOURCE_CONFIG ADD MAX_ERROR_COUNT INT DEFAULT 3;
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.MAX_ERROR_COUNT IS '最大错误次数';

ALTER TABLE TC_DATA_SOURCE_CONFIG ADD TIMEOUT_SECONDS INT DEFAULT 30;
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.TIMEOUT_SECONDS IS '超时时间(秒)';

ALTER TABLE TC_DATA_SOURCE_CONFIG ADD RETRY_COUNT INT DEFAULT 3;
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.RETRY_COUNT IS '重试次数';

-- 添加额外的索引
CREATE INDEX IF NOT EXISTS IDX_TC_DATA_SOURCE_ENV ON TC_DATA_SOURCE_CONFIG(ENVIRONMENT);
CREATE INDEX IF NOT EXISTS IDX_TC_DATA_SOURCE_STATUS ON TC_DATA_SOURCE_CONFIG(CONNECTION_STATUS);
CREATE INDEX IF NOT EXISTS IDX_TC_DATA_SOURCE_ENABLED ON TC_DATA_SOURCE_CONFIG(IS_ENABLED);
CREATE INDEX IF NOT EXISTS IDX_TC_DATA_SOURCE_SYNC ON TC_DATA_SOURCE_CONFIG(SYNC_STATUS);

COMMIT;

-- 验证字段是否添加成功
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'TC_DATA_SOURCE_CONFIG'
ORDER BY COLUMN_ID;

-- 显示表结构
SELECT '表结构升级完成' AS MESSAGE FROM DUAL;
