-- ============================================
-- 债券发行表字段扩展脚本 - 评级/上市/兑付管理
-- 适用于达梦数据库(DM8)/Oracle
-- 创建时间: 2026-02-10
-- 说明: 为 TBL_BOND_ISSUANCE 表添加评级、上市、兑付管理相关字段
-- ============================================

-- 1. 添加评级日期字段
ALTER TABLE TBL_BOND_ISSUANCE ADD RATING_DATE DATE;
COMMENT ON COLUMN TBL_BOND_ISSUANCE.RATING_DATE IS '评级日期';

-- 2. 添加评级展望字段
ALTER TABLE TBL_BOND_ISSUANCE ADD RATING_OUTLOOK VARCHAR2(50);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.RATING_OUTLOOK IS '评级展望：STABLE-稳定/POSITIVE-正面/NEGATIVE-负面/WATCH-观察';

-- 3. 添加评级说明字段
ALTER TABLE TBL_BOND_ISSUANCE ADD RATING_NOTES VARCHAR2(500);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.RATING_NOTES IS '评级说明';

-- 4. 添加上市日期字段
ALTER TABLE TBL_BOND_ISSUANCE ADD LISTING_DATE DATE;
COMMENT ON COLUMN TBL_BOND_ISSUANCE.LISTING_DATE IS '上市日期';

-- 5. 添加证券代码字段
ALTER TABLE TBL_BOND_ISSUANCE ADD STOCK_CODE VARCHAR2(50);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.STOCK_CODE IS '证券代码';

-- 6. 添加上市说明字段
ALTER TABLE TBL_BOND_ISSUANCE ADD LISTING_NOTES VARCHAR2(500);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.LISTING_NOTES IS '上市说明';

-- 7. 添加兑付类型字段
ALTER TABLE TBL_BOND_ISSUANCE ADD REDEEM_TYPE VARCHAR2(50);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.REDEEM_TYPE IS '兑付类型：MATURITY-到期兑付/EARLY-提前兑付/PARTIAL-部分兑付/PUT-回售兑付';

-- 8. 添加兑付金额字段
ALTER TABLE TBL_BOND_ISSUANCE ADD REDEEM_AMOUNT NUMBER(20,2);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.REDEEM_AMOUNT IS '兑付金额';

-- 9. 添加兑付日期字段
ALTER TABLE TBL_BOND_ISSUANCE ADD REDEEM_DATE DATE;
COMMENT ON COLUMN TBL_BOND_ISSUANCE.REDEEM_DATE IS '兑付日期';

-- 10. 添加兑付说明字段
ALTER TABLE TBL_BOND_ISSUANCE ADD REDEEM_NOTES VARCHAR2(500);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.REDEEM_NOTES IS '兑付说明';

-- 创建索引
CREATE INDEX IDX_BOND_RATING_DATE ON TBL_BOND_ISSUANCE(RATING_DATE);
CREATE INDEX IDX_BOND_LISTING_DATE ON TBL_BOND_ISSUANCE(LISTING_DATE);
CREATE INDEX IDX_BOND_REDEEM_DATE ON TBL_BOND_ISSUANCE(REDEEM_DATE);
CREATE INDEX IDX_BOND_STOCK_CODE ON TBL_BOND_ISSUANCE(STOCK_CODE);

-- 提交事务
COMMIT;

-- 验证字段添加结果
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'TBL_BOND_ISSUANCE'
  AND COLUMN_NAME IN ('RATING_DATE', 'RATING_OUTLOOK', 'RATING_NOTES', 
                      'LISTING_DATE', 'STOCK_CODE', 'LISTING_NOTES',
                      'REDEEM_TYPE', 'REDEEM_AMOUNT', 'REDEEM_DATE', 'REDEEM_NOTES')
ORDER BY COLUMN_ID;

