-- ============================================
-- 债券发行表字段扩展脚本
-- 适用于达梦数据库(DM8)/Oracle
-- 创建时间: 2026-02-10
-- 说明: 为 TBL_BOND_ISSUANCE 表添加缺失的业务字段
-- ============================================

-- 1. 添加债券代码字段
ALTER TABLE TBL_BOND_ISSUANCE ADD BOND_CODE VARCHAR2(50);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.BOND_CODE IS '债券代码';

-- 2. 添加面值字段
ALTER TABLE TBL_BOND_ISSUANCE ADD FACE_VALUE NUMBER(20,2) DEFAULT 100;
COMMENT ON COLUMN TBL_BOND_ISSUANCE.FACE_VALUE IS '面值（元）';

-- 3. 添加债券期限字段
ALTER TABLE TBL_BOND_ISSUANCE ADD BOND_TERM NUMBER(10);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.BOND_TERM IS '债券期限';

-- 4. 添加期限单位字段
ALTER TABLE TBL_BOND_ISSUANCE ADD TERM_UNIT VARCHAR2(10) DEFAULT 'YEAR';
COMMENT ON COLUMN TBL_BOND_ISSUANCE.TERM_UNIT IS '期限单位：MONTH-月/YEAR-年';

-- 5. 添加付息频率字段
ALTER TABLE TBL_BOND_ISSUANCE ADD PAYMENT_FREQUENCY VARCHAR2(20) DEFAULT 'ANNUAL';
COMMENT ON COLUMN TBL_BOND_ISSUANCE.PAYMENT_FREQUENCY IS '付息频率：MONTHLY-月付/QUARTERLY-季付/SEMI_ANNUAL-半年付/ANNUAL-年付';

-- 6. 添加信用评级字段
ALTER TABLE TBL_BOND_ISSUANCE ADD CREDIT_RATING VARCHAR2(20);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.CREDIT_RATING IS '信用评级：AAA/AA+/AA/AA-/A+/A/A-/BBB+/BBB等';

-- 7. 添加承销商字段
ALTER TABLE TBL_BOND_ISSUANCE ADD UNDERWRITER VARCHAR2(200);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.UNDERWRITER IS '承销商名称';

-- 8. 添加受托管理人字段
ALTER TABLE TBL_BOND_ISSUANCE ADD TRUSTEE VARCHAR2(200);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.TRUSTEE IS '受托管理人名称';

-- 9. 添加评级机构字段
ALTER TABLE TBL_BOND_ISSUANCE ADD RATING_AGENCY VARCHAR2(200);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.RATING_AGENCY IS '评级机构名称';

-- 10. 添加上市交易所字段
ALTER TABLE TBL_BOND_ISSUANCE ADD LISTING_EXCHANGE VARCHAR2(100);
COMMENT ON COLUMN TBL_BOND_ISSUANCE.LISTING_EXCHANGE IS '上市交易所';

-- 创建索引
CREATE INDEX IDX_BOND_CODE ON TBL_BOND_ISSUANCE(BOND_CODE);
CREATE INDEX IDX_BOND_RATING ON TBL_BOND_ISSUANCE(CREDIT_RATING);

-- 提交事务
COMMIT;

-- ============================================
-- 更新现有测试数据（可选）
-- ============================================
UPDATE TBL_BOND_ISSUANCE SET 
    BOND_CODE = 'HBY' || LPAD(BOND_ID, 6, '0'),
    FACE_VALUE = 100,
    BOND_TERM = 3,
    TERM_UNIT = 'YEAR',
    PAYMENT_FREQUENCY = 'ANNUAL',
    CREDIT_RATING = 'AA+',
    UNDERWRITER = '中信证券',
    TRUSTEE = '中国银行',
    RATING_AGENCY = '中诚信国际',
    LISTING_EXCHANGE = '上海证券交易所'
WHERE BOND_CODE IS NULL;

COMMIT;

-- 验证字段添加结果
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'TBL_BOND_ISSUANCE'
ORDER BY COLUMN_ID;

