-- 银行理财投资测试数据 (MySQL版本)
-- 用于在MySQL数据库中插入测试数据

-- 清空现有测试数据（可选）
-- DELETE FROM TBL_BANK_WEALTH_INVESTMENT WHERE INVESTMENT_NO LIKE 'TEST%';

-- 插入测试数据
INSERT INTO TBL_BANK_WEALTH_INVESTMENT (
    BANK_WEALTH_INVESTMENT_ID,
    PLAN_ID,
    PRODUCT_ID,
    ACCOUNT_ID,
    INVESTMENT_NO,
    PRODUCT_CODE,
    BANK_CODE,
    INVESTMENT_AMOUNT,
    EXPECTED_RETURN_RATE,
    ACTUAL_RETURN_RATE,
    CURRENT_VALUE,
    EXPECTED_RETURN,
    ACTUAL_RETURN,
    INVESTMENT_DATE,
    MATURITY_DATE,
    REDEEM_DATE,
    REDEEM_AMOUNT,
    INVESTMENT_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    CREATE_USER,
    UPDATE_USER
) VALUES (
    1, 1, 1, 1, 'TEST2024001', 'LRZG001', 'ICBC',
    1000000.00, 0.045, 0.046, 1046000.00, 45000.00, 46000.00,
    '2024-01-15', '2025-01-15', NULL, NULL, 'ACTIVE',
    NOW(), NOW(), 1, 1
);

INSERT INTO TBL_BANK_WEALTH_INVESTMENT (
    BANK_WEALTH_INVESTMENT_ID,
    PLAN_ID,
    PRODUCT_ID,
    ACCOUNT_ID,
    INVESTMENT_NO,
    PRODUCT_CODE,
    BANK_CODE,
    INVESTMENT_AMOUNT,
    EXPECTED_RETURN_RATE,
    ACTUAL_RETURN_RATE,
    CURRENT_VALUE,
    EXPECTED_RETURN,
    ACTUAL_RETURN,
    INVESTMENT_DATE,
    MATURITY_DATE,
    REDEEM_DATE,
    REDEEM_AMOUNT,
    INVESTMENT_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    CREATE_USER,
    UPDATE_USER
) VALUES (
    2, 1, 2, 1, 'TEST2024002', 'LRZG002', 'CCB',
    500000.00, 0.038, NULL, 500000.00, 19000.00, NULL,
    '2024-03-20', '2024-09-20', NULL, NULL, 'MATURED',
    NOW(), NOW(), 1, 1
);

INSERT INTO TBL_BANK_WEALTH_INVESTMENT (
    BANK_WEALTH_INVESTMENT_ID,
    PLAN_ID,
    PRODUCT_ID,
    ACCOUNT_ID,
    INVESTMENT_NO,
    PRODUCT_CODE,
    BANK_CODE,
    INVESTMENT_AMOUNT,
    EXPECTED_RETURN_RATE,
    ACTUAL_RETURN_RATE,
    CURRENT_VALUE,
    EXPECTED_RETURN,
    ACTUAL_RETURN,
    INVESTMENT_DATE,
    MATURITY_DATE,
    REDEEM_DATE,
    REDEEM_AMOUNT,
    INVESTMENT_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    CREATE_USER,
    UPDATE_USER
) VALUES (
    3, 2, 3, 2, 'TEST2024003', 'LRZG003', 'ABC',
    2000000.00, 0.050, 0.052, 2104000.00, 100000.00, 104000.00,
    '2023-06-10', '2024-06-10', '2024-06-10', 2104000.00, 'REDEEMED',
    NOW(), NOW(), 1, 1
);

INSERT INTO TBL_BANK_WEALTH_INVESTMENT (
    BANK_WEALTH_INVESTMENT_ID,
    PLAN_ID,
    PRODUCT_ID,
    ACCOUNT_ID,
    INVESTMENT_NO,
    PRODUCT_CODE,
    BANK_CODE,
    INVESTMENT_AMOUNT,
    EXPECTED_RETURN_RATE,
    ACTUAL_RETURN_RATE,
    CURRENT_VALUE,
    EXPECTED_RETURN,
    ACTUAL_RETURN,
    INVESTMENT_DATE,
    MATURITY_DATE,
    REDEEM_DATE,
    REDEEM_AMOUNT,
    INVESTMENT_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    CREATE_USER,
    UPDATE_USER
) VALUES (
    4, 2, 4, 2, 'TEST2024004', 'LRZG004', 'BOC',
    800000.00, 0.042, 0.041, 832800.00, 33600.00, 32800.00,
    '2024-05-01', '2025-05-01', NULL, NULL, 'ACTIVE',
    NOW(), NOW(), 1, 1
);

INSERT INTO TBL_BANK_WEALTH_INVESTMENT (
    BANK_WEALTH_INVESTMENT_ID,
    PLAN_ID,
    PRODUCT_ID,
    ACCOUNT_ID,
    INVESTMENT_NO,
    PRODUCT_CODE,
    BANK_CODE,
    INVESTMENT_AMOUNT,
    EXPECTED_RETURN_RATE,
    ACTUAL_RETURN_RATE,
    CURRENT_VALUE,
    EXPECTED_RETURN,
    ACTUAL_RETURN,
    INVESTMENT_DATE,
    MATURITY_DATE,
    REDEEM_DATE,
    REDEEM_AMOUNT,
    INVESTMENT_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    CREATE_USER,
    UPDATE_USER
) VALUES (
    5, 3, 5, 3, 'TEST2024005', 'LRZG005', 'BCM',
    1500000.00, 0.048, 0.049, 1573500.00, 72000.00, 73500.00,
    '2024-02-15', '2025-02-15', NULL, NULL, 'ACTIVE',
    NOW(), NOW(), 1, 1
);

INSERT INTO TBL_BANK_WEALTH_INVESTMENT (
    BANK_WEALTH_INVESTMENT_ID,
    PLAN_ID,
    PRODUCT_ID,
    ACCOUNT_ID,
    INVESTMENT_NO,
    PRODUCT_CODE,
    BANK_CODE,
    INVESTMENT_AMOUNT,
    EXPECTED_RETURN_RATE,
    ACTUAL_RETURN_RATE,
    CURRENT_VALUE,
    EXPECTED_RETURN,
    ACTUAL_RETURN,
    INVESTMENT_DATE,
    MATURITY_DATE,
    REDEEM_DATE,
    REDEEM_AMOUNT,
    INVESTMENT_STATUS,
    CREATE_TIME,
    UPDATE_TIME,
    CREATE_USER,
    UPDATE_USER
) VALUES (
    6, 3, 6, 3, 'TEST2024006', 'LRZG006', 'CMB',
    600000.00, 0.040, NULL, 600000.00, 24000.00, NULL,
    '2024-08-01', '2025-02-01', NULL, NULL, 'ACTIVE',
    NOW(), NOW(), 1, 1
);

-- 查询验证
SELECT
    INVESTMENT_NO AS '投资编号',
    PRODUCT_CODE AS '产品代码',
    BANK_CODE AS '银行代码',
    INVESTMENT_AMOUNT AS '投资金额',
    EXPECTED_RETURN_RATE AS '预期收益率',
    ACTUAL_RETURN_RATE AS '实际收益率',
    CURRENT_VALUE AS '当前价值',
    INVESTMENT_STATUS AS '投资状态',
    INVESTMENT_DATE AS '投资日期',
    MATURITY_DATE AS '到期日期'
FROM TBL_BANK_WEALTH_INVESTMENT
ORDER BY CREATE_TIME DESC;
