-- =====================================================
-- 票据登记表测试数据 - 通用SQL版本
-- 适用于 MySQL / Oracle / 达梦数据库
-- =====================================================

-- 如果表不存在，先创建表
-- 注意：达梦数据库使用 DECIMAL，MySQL 使用 BIGINT
CREATE TABLE IF NOT EXISTS TBL_BILL_REGISTRATION (
    BILL_ID BIGINT PRIMARY KEY,
    BILL_NUMBER VARCHAR(50) NOT NULL,
    BILL_TYPE VARCHAR(30),
    BILL_AMOUNT DECIMAL(18,2),
    CURRENCY VARCHAR(10) DEFAULT 'CNY',
    ISSUE_DATE DATETIME,
    MATURITY_DATE DATETIME,
    DRAWER_NAME VARCHAR(200),
    DRAWER_ACCOUNT VARCHAR(100),
    PAYEE_NAME VARCHAR(200),
    PAYEE_ACCOUNT VARCHAR(100),
    ACCEPTOR_NAME VARCHAR(200),
    ACCEPTING_BANK VARCHAR(200),
    BILL_STATUS VARCHAR(20),
    BILL_PURPOSE VARCHAR(100),
    BILL_SOURCE VARCHAR(50),
    STORAGE_LOCATION VARCHAR(200),
    REGISTRAR_ID BIGINT,
    REGISTRAR_NAME VARCHAR(100),
    REMARK VARCHAR(500),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(50),
    UPDATE_BY VARCHAR(50),
    COMPANY_ID BIGINT,
    DEPT_ID BIGINT,
    DELETE_FLAG INT DEFAULT 0
);

-- 清空现有测试数据（可选，取消注释执行）
-- DELETE FROM TBL_BILL_REGISTRATION WHERE BILL_ID >= 1000000;

-- ==================== 银行承兑汇票 ====================
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000001, 'BA202501001', 'BANK_ACCEPTANCE', 1500000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_ADD(NOW(), INTERVAL 150 DAY), '华博科技有限公司', '供应商A公司', '工商银行北京分行', 'HOLDING', '采购付款', DATE_SUB(NOW(), INTERVAL 30 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000002, 'BA202501002', 'BANK_ACCEPTANCE', 2800000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 25 DAY), DATE_ADD(NOW(), INTERVAL 155 DAY), '华博科技有限公司', '供应商B公司', '建设银行上海分行', 'HOLDING', '设备采购', DATE_SUB(NOW(), INTERVAL 25 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000003, 'BA202501003', 'BANK_ACCEPTANCE', 850000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_ADD(NOW(), INTERVAL 160 DAY), '华博科技有限公司', '供应商C公司', '农业银行广州分行', 'ENDORSED', '原材料采购', DATE_SUB(NOW(), INTERVAL 20 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000004, 'BA202501004', 'BANK_ACCEPTANCE', 3200000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_ADD(NOW(), INTERVAL 165 DAY), '华博科技有限公司', '供应商D公司', '中国银行深圳分行', 'HOLDING', '工程款', DATE_SUB(NOW(), INTERVAL 15 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000005, 'BA202501005', 'BANK_ACCEPTANCE', 1200000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_ADD(NOW(), INTERVAL 170 DAY), '华博科技有限公司', '供应商E公司', '交通银行杭州分行', 'DISCOUNTED', '服务费', DATE_SUB(NOW(), INTERVAL 10 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000006, 'BA202501006', 'BANK_ACCEPTANCE', 2100000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_ADD(NOW(), INTERVAL 174 DAY), '华博科技有限公司', '供应商F公司', '兴业银行', 'HOLDING', '材料款', DATE_SUB(NOW(), INTERVAL 6 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000007, 'BA202501007', 'BANK_ACCEPTANCE', 1750000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_ADD(NOW(), INTERVAL 176 DAY), '华博科技有限公司', '供应商G公司', '光大银行', 'HOLDING', '加工费', DATE_SUB(NOW(), INTERVAL 4 DAY), 0);

-- ==================== 商业承兑汇票 ====================
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000008, 'CA202501001', 'COMMERCIAL_ACCEPTANCE', 500000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 28 DAY), DATE_ADD(NOW(), INTERVAL 152 DAY), '合作伙伴A公司', '华博科技有限公司', NULL, 'HOLDING', '货款', DATE_SUB(NOW(), INTERVAL 28 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000009, 'CA202501002', 'COMMERCIAL_ACCEPTANCE', 780000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 22 DAY), DATE_ADD(NOW(), INTERVAL 158 DAY), '合作伙伴B公司', '华博科技有限公司', NULL, 'HOLDING', '服务费', DATE_SUB(NOW(), INTERVAL 22 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000010, 'CA202501003', 'COMMERCIAL_ACCEPTANCE', 320000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 18 DAY), DATE_ADD(NOW(), INTERVAL 162 DAY), '合作伙伴C公司', '华博科技有限公司', NULL, 'ENDORSED', '咨询费', DATE_SUB(NOW(), INTERVAL 18 DAY), 0);

-- ==================== 电子票据 ====================
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000011, 'EB202501001', 'ELECTRONIC_BILL', 2500000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_ADD(NOW(), INTERVAL 168 DAY), '华博科技有限公司', '电子商务公司A', '招商银行南京分行', 'HOLDING', '电商结算', DATE_SUB(NOW(), INTERVAL 12 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000012, 'EB202501002', 'ELECTRONIC_BILL', 1800000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_ADD(NOW(), INTERVAL 172 DAY), '华博科技有限公司', '电子商务公司B', '浦发银行成都分行', 'HOLDING', '平台服务费', DATE_SUB(NOW(), INTERVAL 8 DAY), 0);

-- ==================== 支票 ====================
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000013, 'CK202501001', 'CHECK', 50000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_ADD(NOW(), INTERVAL 5 DAY), '华博科技有限公司', '办公用品供应商', '工商银行北京分行', 'HOLDING', '办公用品', DATE_SUB(NOW(), INTERVAL 5 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000014, 'CK202501002', 'CHECK', 80000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_ADD(NOW(), INTERVAL 7 DAY), '华博科技有限公司', '差旅服务公司', '建设银行北京分行', 'MATURED', '差旅费', DATE_SUB(NOW(), INTERVAL 3 DAY), 0);

-- ==================== 本票 ====================
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000015, 'PN202501001', 'PROMISSORY_NOTE', 200000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_ADD(NOW(), INTERVAL 83 DAY), '华博科技有限公司', '技术服务商', '中国银行北京分行', 'HOLDING', '技术服务', DATE_SUB(NOW(), INTERVAL 7 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000016, 'PN202501002', 'PROMISSORY_NOTE', 150000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_ADD(NOW(), INTERVAL 88 DAY), '华博科技有限公司', '咨询公司', '农业银行北京分行', 'HOLDING', '咨询服务', DATE_SUB(NOW(), INTERVAL 2 DAY), 0);

-- ==================== 历史数据（用于趋势分析） ====================
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, CREATE_TIME, DELETE_FLAG)
VALUES (1000017, 'BA202412001', 'BANK_ACCEPTANCE', 1100000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 45 DAY), DATE_ADD(NOW(), INTERVAL 135 DAY), '华博科技有限公司', '供应商H公司', '工商银行', 'HOLDING', DATE_SUB(NOW(), INTERVAL 45 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, CREATE_TIME, DELETE_FLAG)
VALUES (1000018, 'BA202412002', 'BANK_ACCEPTANCE', 950000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 40 DAY), DATE_ADD(NOW(), INTERVAL 140 DAY), '华博科技有限公司', '供应商I公司', '建设银行', 'ENDORSED', DATE_SUB(NOW(), INTERVAL 40 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, CREATE_TIME, DELETE_FLAG)
VALUES (1000019, 'CA202412001', 'COMMERCIAL_ACCEPTANCE', 420000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 35 DAY), DATE_ADD(NOW(), INTERVAL 145 DAY), '合作伙伴D公司', '华博科技有限公司', NULL, 'HOLDING', DATE_SUB(NOW(), INTERVAL 35 DAY), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, CREATE_TIME, DELETE_FLAG)
VALUES (1000020, 'EB202412001', 'ELECTRONIC_BILL', 1650000.00, 'CNY', DATE_SUB(NOW(), INTERVAL 32 DAY), DATE_ADD(NOW(), INTERVAL 148 DAY), '华博科技有限公司', '电子商务公司C', '民生银行', 'DISCOUNTED', DATE_SUB(NOW(), INTERVAL 32 DAY), 0);

-- ==================== 验证数据 ====================
SELECT '票据总数' AS item, COUNT(*) AS value FROM TBL_BILL_REGISTRATION WHERE DELETE_FLAG = 0;
SELECT '票据总金额(万元)' AS item, ROUND(SUM(BILL_AMOUNT)/10000, 2) AS value FROM TBL_BILL_REGISTRATION WHERE DELETE_FLAG = 0;
SELECT BILL_TYPE, COUNT(*) AS count, ROUND(SUM(BILL_AMOUNT)/10000, 2) AS amount_wan FROM TBL_BILL_REGISTRATION WHERE DELETE_FLAG = 0 GROUP BY BILL_TYPE;

