-- =====================================================
-- 票据登记表测试数据 - 用于票据查询统计页面
-- 适用于达梦数据库
-- =====================================================

-- 首先确保表结构正确（如果表不存在或结构不对，先执行此DDL）
-- DROP TABLE IF EXISTS TBL_BILL_REGISTRATION;

CREATE TABLE IF NOT EXISTS TBL_BILL_REGISTRATION (
    BILL_ID DECIMAL(20,0) PRIMARY KEY,
    BILL_NUMBER VARCHAR(50) NOT NULL,
    BILL_TYPE VARCHAR(30),
    BILL_AMOUNT DECIMAL(18,2),
    CURRENCY VARCHAR(10) DEFAULT 'CNY',
    ISSUE_DATE TIMESTAMP,
    MATURITY_DATE TIMESTAMP,
    DRAWER_NAME VARCHAR(200),
    DRAWER_ACCOUNT VARCHAR(100),
    PAYEE_NAME VARCHAR(200),
    PAYEE_ACCOUNT VARCHAR(100),
    ACCEPTOR_NAME VARCHAR(200),
    ACCEPTING_BANK VARCHAR(200),
    BILL_STATUS VARCHAR(20),
    BILL_PURPOSE VARCHAR(100),
    BILL_SOURCE VARCHAR(50),
    STORAGE_LOCATION VARCHAR(200),
    REGISTRAR_ID DECIMAL(20,0),
    REGISTRAR_NAME VARCHAR(100),
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_BY VARCHAR(50),
    UPDATE_BY VARCHAR(50),
    COMPANY_ID DECIMAL(20,0),
    DEPT_ID DECIMAL(20,0),
    DELETE_FLAG DECIMAL(1) DEFAULT 0
);

-- 清空现有测试数据（可选）
-- DELETE FROM TBL_BILL_REGISTRATION WHERE BILL_ID >= 1000000;

-- 插入银行承兑汇票测试数据
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000001, 'BA202501001', 'BANK_ACCEPTANCE', 1500000.00, 'CNY', DATEADD(DAY, -30, SYSDATE), DATEADD(DAY, 150, SYSDATE), '华博科技有限公司', '6222021234567890', '供应商A公司', '6222029876543210', '中国工商银行', '工商银行北京分行', 'HOLDING', '采购付款', DATEADD(DAY, -30, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000002, 'BA202501002', 'BANK_ACCEPTANCE', 2800000.00, 'CNY', DATEADD(DAY, -25, SYSDATE), DATEADD(DAY, 155, SYSDATE), '华博科技有限公司', '6222021234567890', '供应商B公司', '6222029876543211', '中国建设银行', '建设银行上海分行', 'HOLDING', '设备采购', DATEADD(DAY, -25, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000003, 'BA202501003', 'BANK_ACCEPTANCE', 850000.00, 'CNY', DATEADD(DAY, -20, SYSDATE), DATEADD(DAY, 160, SYSDATE), '华博科技有限公司', '6222021234567890', '供应商C公司', '6222029876543212', '中国农业银行', '农业银行广州分行', 'ENDORSED', '原材料采购', DATEADD(DAY, -20, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000004, 'BA202501004', 'BANK_ACCEPTANCE', 3200000.00, 'CNY', DATEADD(DAY, -15, SYSDATE), DATEADD(DAY, 165, SYSDATE), '华博科技有限公司', '6222021234567890', '供应商D公司', '6222029876543213', '中国银行', '中国银行深圳分行', 'HOLDING', '工程款', DATEADD(DAY, -15, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000005, 'BA202501005', 'BANK_ACCEPTANCE', 1200000.00, 'CNY', DATEADD(DAY, -10, SYSDATE), DATEADD(DAY, 170, SYSDATE), '华博科技有限公司', '6222021234567890', '供应商E公司', '6222029876543214', '交通银行', '交通银行杭州分行', 'DISCOUNTED', '服务费', DATEADD(DAY, -10, SYSDATE), 0);

-- 插入商业承兑汇票测试数据
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000006, 'CA202501001', 'COMMERCIAL_ACCEPTANCE', 500000.00, 'CNY', DATEADD(DAY, -28, SYSDATE), DATEADD(DAY, 152, SYSDATE), '合作伙伴A公司', '6222031234567890', '华博科技有限公司', '6222021234567890', '合作伙伴A公司', NULL, 'HOLDING', '货款', DATEADD(DAY, -28, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000007, 'CA202501002', 'COMMERCIAL_ACCEPTANCE', 780000.00, 'CNY', DATEADD(DAY, -22, SYSDATE), DATEADD(DAY, 158, SYSDATE), '合作伙伴B公司', '6222031234567891', '华博科技有限公司', '6222021234567890', '合作伙伴B公司', NULL, 'HOLDING', '服务费', DATEADD(DAY, -22, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000008, 'CA202501003', 'COMMERCIAL_ACCEPTANCE', 320000.00, 'CNY', DATEADD(DAY, -18, SYSDATE), DATEADD(DAY, 162, SYSDATE), '合作伙伴C公司', '6222031234567892', '华博科技有限公司', '6222021234567890', '合作伙伴C公司', NULL, 'ENDORSED', '咨询费', DATEADD(DAY, -18, SYSDATE), 0);

-- 插入电子票据测试数据
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000009, 'EB202501001', 'ELECTRONIC_BILL', 2500000.00, 'CNY', DATEADD(DAY, -12, SYSDATE), DATEADD(DAY, 168, SYSDATE), '华博科技有限公司', '6222021234567890', '电子商务公司A', '6222041234567890', '招商银行', '招商银行南京分行', 'HOLDING', '电商结算', DATEADD(DAY, -12, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000010, 'EB202501002', 'ELECTRONIC_BILL', 1800000.00, 'CNY', DATEADD(DAY, -8, SYSDATE), DATEADD(DAY, 172, SYSDATE), '华博科技有限公司', '6222021234567890', '电子商务公司B', '6222041234567891', '浦发银行', '浦发银行成都分行', 'HOLDING', '平台服务费', DATEADD(DAY, -8, SYSDATE), 0);

-- 插入支票测试数据
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000011, 'CK202501001', 'CHECK', 50000.00, 'CNY', DATEADD(DAY, -5, SYSDATE), DATEADD(DAY, 5, SYSDATE), '华博科技有限公司', '6222021234567890', '办公用品供应商', '6222051234567890', NULL, '工商银行北京分行', 'HOLDING', '办公用品', DATEADD(DAY, -5, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000012, 'CK202501002', 'CHECK', 80000.00, 'CNY', DATEADD(DAY, -3, SYSDATE), DATEADD(DAY, 7, SYSDATE), '华博科技有限公司', '6222021234567890', '差旅服务公司', '6222051234567891', NULL, '建设银行北京分行', 'MATURED', '差旅费', DATEADD(DAY, -3, SYSDATE), 0);

-- 插入本票测试数据
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000013, 'PN202501001', 'PROMISSORY_NOTE', 200000.00, 'CNY', DATEADD(DAY, -7, SYSDATE), DATEADD(DAY, 83, SYSDATE), '华博科技有限公司', '6222021234567890', '技术服务商', '6222061234567890', NULL, '中国银行北京分行', 'HOLDING', '技术服务', DATEADD(DAY, -7, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, DRAWER_ACCOUNT, PAYEE_NAME, PAYEE_ACCOUNT, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, CREATE_TIME, DELETE_FLAG)
VALUES (1000014, 'PN202501002', 'PROMISSORY_NOTE', 150000.00, 'CNY', DATEADD(DAY, -2, SYSDATE), DATEADD(DAY, 88, SYSDATE), '华博科技有限公司', '6222021234567890', '咨询公司', '6222061234567891', NULL, '农业银行北京分行', 'HOLDING', '咨询服务', DATEADD(DAY, -2, SYSDATE), 0);

-- 插入更多历史数据用于趋势分析
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, CREATE_TIME, DELETE_FLAG)
VALUES (1000015, 'BA202412001', 'BANK_ACCEPTANCE', 1100000.00, 'CNY', DATEADD(DAY, -45, SYSDATE), DATEADD(DAY, 135, SYSDATE), '华博科技有限公司', '供应商F公司', '工商银行', 'HOLDING', DATEADD(DAY, -45, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, CREATE_TIME, DELETE_FLAG)
VALUES (1000016, 'BA202412002', 'BANK_ACCEPTANCE', 950000.00, 'CNY', DATEADD(DAY, -40, SYSDATE), DATEADD(DAY, 140, SYSDATE), '华博科技有限公司', '供应商G公司', '建设银行', 'ENDORSED', DATEADD(DAY, -40, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, CREATE_TIME, DELETE_FLAG)
VALUES (1000017, 'CA202412001', 'COMMERCIAL_ACCEPTANCE', 420000.00, 'CNY', DATEADD(DAY, -35, SYSDATE), DATEADD(DAY, 145, SYSDATE), '合作伙伴D公司', '华博科技有限公司', NULL, 'HOLDING', DATEADD(DAY, -35, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, CREATE_TIME, DELETE_FLAG)
VALUES (1000018, 'EB202412001', 'ELECTRONIC_BILL', 1650000.00, 'CNY', DATEADD(DAY, -32, SYSDATE), DATEADD(DAY, 148, SYSDATE), '华博科技有限公司', '电子商务公司C', '民生银行', 'DISCOUNTED', DATEADD(DAY, -32, SYSDATE), 0);

-- 更多近期数据
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, CREATE_TIME, DELETE_FLAG)
VALUES (1000019, 'BA202501006', 'BANK_ACCEPTANCE', 2100000.00, 'CNY', DATEADD(DAY, -6, SYSDATE), DATEADD(DAY, 174, SYSDATE), '华博科技有限公司', '供应商H公司', '兴业银行', 'HOLDING', DATEADD(DAY, -6, SYSDATE), 0);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE, DRAWER_NAME, PAYEE_NAME, ACCEPTING_BANK, BILL_STATUS, CREATE_TIME, DELETE_FLAG)
VALUES (1000020, 'BA202501007', 'BANK_ACCEPTANCE', 1750000.00, 'CNY', DATEADD(DAY, -4, SYSDATE), DATEADD(DAY, 176, SYSDATE), '华博科技有限公司', '供应商I公司', '光大银行', 'HOLDING', DATEADD(DAY, -4, SYSDATE), 0);

-- 验证数据
SELECT '票据总数' AS 统计项, COUNT(*) AS 数值 FROM TBL_BILL_REGISTRATION WHERE DELETE_FLAG = 0
UNION ALL
SELECT '票据总金额(万元)', ROUND(SUM(BILL_AMOUNT)/10000, 2) FROM TBL_BILL_REGISTRATION WHERE DELETE_FLAG = 0
UNION ALL
SELECT '银行承兑汇票数量', COUNT(*) FROM TBL_BILL_REGISTRATION WHERE DELETE_FLAG = 0 AND BILL_TYPE = 'BANK_ACCEPTANCE'
UNION ALL
SELECT '商业承兑汇票数量', COUNT(*) FROM TBL_BILL_REGISTRATION WHERE DELETE_FLAG = 0 AND BILL_TYPE = 'COMMERCIAL_ACCEPTANCE'
UNION ALL
SELECT '电子票据数量', COUNT(*) FROM TBL_BILL_REGISTRATION WHERE DELETE_FLAG = 0 AND BILL_TYPE = 'ELECTRONIC_BILL'
UNION ALL
SELECT '支票数量', COUNT(*) FROM TBL_BILL_REGISTRATION WHERE DELETE_FLAG = 0 AND BILL_TYPE = 'CHECK'
UNION ALL
SELECT '本票数量', COUNT(*) FROM TBL_BILL_REGISTRATION WHERE DELETE_FLAG = 0 AND BILL_TYPE = 'PROMISSORY_NOTE';

