-- =============================================================
-- 票据管理模块数据库表 - 达梦数据库建表脚本
-- 数据库: DM8
-- 编码: UTF-8
-- 创建时间: 2025-12-30
-- 说明: 包含票据管理所需的8张核心表
-- =============================================================

-- 表1: 票据信息表
DROP TABLE IF EXISTS TBL_BILL_INSTRUMENT;

CREATE TABLE TBL_BILL_INSTRUMENT (
    INSTRUMENT_ID DECIMAL(20,0) PRIMARY KEY,
    INSTRUMENT_NO VARCHAR(50) NOT NULL,
    BILL_NO VARCHAR(50),
    BILL_TYPE VARCHAR(20),
    BILL_AMOUNT DECIMAL(18,2),
    CURRENCY_CODE VARCHAR(10) DEFAULT 'CNY',
    DRAWER VARCHAR(200),
    DRAWER_ACCOUNT VARCHAR(100),
    PAYEE VARCHAR(200),
    PAYEE_ACCOUNT VARCHAR(100),
    ACCEPTOR VARCHAR(200),
    ACCEPTOR_ACCOUNT VARCHAR(100),
    ISSUE_DATE TIMESTAMP,
    MATURITY_DATE TIMESTAMP,
    BILL_STATUS VARCHAR(20),
    DELETE_FLAG DECIMAL(1) DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50),
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_BILL_INSTRUMENT IS '票据信息表';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.INSTRUMENT_ID IS '票据ID';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.INSTRUMENT_NO IS '票据编号';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.BILL_NO IS '票据号码';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.BILL_TYPE IS '票据类型(银行承兑汇票/商业承兑汇票/电子汇票)';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.BILL_AMOUNT IS '票面金额';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.DRAWER IS '出票人';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.PAYEE IS '收款人';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.ACCEPTOR IS '承兑人';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.ISSUE_DATE IS '出票日期';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.MATURITY_DATE IS '到期日';
COMMENT ON COLUMN TBL_BILL_INSTRUMENT.BILL_STATUS IS '票据状态(已开立/已承兑/已背书/已贴现/已到期)';

CREATE INDEX IDX_INSTRUMENT_NO ON TBL_BILL_INSTRUMENT(INSTRUMENT_NO);
CREATE INDEX IDX_BILL_NO ON TBL_BILL_INSTRUMENT(BILL_NO);
CREATE INDEX IDX_BILL_TYPE ON TBL_BILL_INSTRUMENT(BILL_TYPE);
CREATE INDEX IDX_BILL_STATUS ON TBL_BILL_INSTRUMENT(BILL_STATUS);

-- 表2: 票据贴现表
DROP TABLE IF EXISTS TBL_BILL_DISCOUNT;

CREATE TABLE TBL_BILL_DISCOUNT (
    DISCOUNT_ID DECIMAL(20,0) PRIMARY KEY,
    DISCOUNT_NUMBER VARCHAR(50) NOT NULL,
    BILL_ID DECIMAL(20,0),
    DISCOUNT_TYPE VARCHAR(20),
    DISCOUNT_STATUS VARCHAR(20),
    DISCOUNT_BANK VARCHAR(200),
    DISCOUNT_RATE DECIMAL(10,6),
    DISCOUNT_AMOUNT DECIMAL(18,2),
    INTEREST_AMOUNT DECIMAL(18,2),
    HANDLING_FEE DECIMAL(18,2),
    ACTUAL_AMOUNT DECIMAL(18,2),
    APPLICATION_DATE TIMESTAMP,
    APPROVAL_DATE TIMESTAMP,
    MATURITY_DATE TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50),
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_BILL_DISCOUNT IS '票据贴现表';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_ID IS '贴现ID';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_NUMBER IS '贴现编号';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.BILL_ID IS '票据ID';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_TYPE IS '贴现类型(买断式/回购式)';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_STATUS IS '贴现状态(申请中/已审批/已放款/已还款)';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_RATE IS '贴现利率';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_AMOUNT IS '贴现金额';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.INTEREST_AMOUNT IS '贴现利息';

CREATE INDEX IDX_DISCOUNT_NUMBER ON TBL_BILL_DISCOUNT(DISCOUNT_NUMBER);
CREATE INDEX IDX_DISCOUNT_STATUS ON TBL_BILL_DISCOUNT(DISCOUNT_STATUS);

-- 表3: 票据背书表
DROP TABLE IF EXISTS TBL_BILL_ENDORSEMENT;

CREATE TABLE TBL_BILL_ENDORSEMENT (
    ENDORSEMENT_ID DECIMAL(20,0) PRIMARY KEY,
    ENDORSEMENT_NUMBER VARCHAR(50) NOT NULL,
    BILL_ID DECIMAL(20,0),
    ENDORSEMENT_TYPE VARCHAR(20),
    ENDORSEMENT_STATUS VARCHAR(20),
    ENDORSER VARCHAR(200),
    ENDORSER_ACCOUNT VARCHAR(100),
    ENDORSEE VARCHAR(200),
    ENDORSEE_ACCOUNT VARCHAR(100),
    ENDORSEMENT_DATE TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50),
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_BILL_ENDORSEMENT IS '票据背书表';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.ENDORSEMENT_ID IS '背书ID';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.ENDORSEMENT_NUMBER IS '背书编号';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.BILL_ID IS '票据ID';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.ENDORSEMENT_TYPE IS '背书类型(转让/质押)';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.ENDORSEMENT_STATUS IS '背书状态(申请中/已完成/已撤销)';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.ENDORSER IS '背书人';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.ENDORSEE IS '被背书人';

CREATE INDEX IDX_ENDORSEMENT_NUMBER ON TBL_BILL_ENDORSEMENT(ENDORSEMENT_NUMBER);
CREATE INDEX IDX_ENDORSEMENT_STATUS ON TBL_BILL_ENDORSEMENT(ENDORSEMENT_STATUS);

-- 表4: 票据到期管理表
DROP TABLE IF EXISTS TBL_BILL_MATURITY;

CREATE TABLE TBL_BILL_MATURITY (
    MATURITY_ID DECIMAL(20,0) PRIMARY KEY,
    BILL_ID DECIMAL(20,0),
    MATURITY_DATE TIMESTAMP,
    MATURITY_STATUS VARCHAR(20),
    PROCESS_TYPE VARCHAR(20),
    PROCESS_DATE TIMESTAMP,
    EXTEND_DAYS INTEGER,
    COLLECT_BANK VARCHAR(200),
    COLLECT_ACCOUNT VARCHAR(100),
    PROCESS_RESULT VARCHAR(20),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50),
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_BILL_MATURITY IS '票据到期管理表';
COMMENT ON COLUMN TBL_BILL_MATURITY.MATURITY_ID IS '到期ID';
COMMENT ON COLUMN TBL_BILL_MATURITY.BILL_ID IS '票据ID';
COMMENT ON COLUMN TBL_BILL_MATURITY.MATURITY_DATE IS '到期日';
COMMENT ON COLUMN TBL_BILL_MATURITY.MATURITY_STATUS IS '到期状态(未到期/即将到期/已到期/已处理/已逾期)';
COMMENT ON COLUMN TBL_BILL_MATURITY.PROCESS_TYPE IS '处理类型(正常收款/托收/延期)';
COMMENT ON COLUMN TBL_BILL_MATURITY.EXTEND_DAYS IS '延期天数';

CREATE INDEX IDX_MATURITY_DATE ON TBL_BILL_MATURITY(MATURITY_DATE);
CREATE INDEX IDX_MATURITY_STATUS ON TBL_BILL_MATURITY(MATURITY_STATUS);

-- 表5: 票据池表
DROP TABLE IF EXISTS TBL_BILL_POOL;

CREATE TABLE TBL_BILL_POOL (
    POOL_ID DECIMAL(20,0) PRIMARY KEY,
    POOL_NAME VARCHAR(200) NOT NULL,
    POOL_NO VARCHAR(50) NOT NULL,
    POOL_TYPE VARCHAR(20),
    POOL_STATUS VARCHAR(20),
    TOTAL_AMOUNT DECIMAL(18,2) DEFAULT 0,
    BILL_COUNT INTEGER DEFAULT 0,
    AVAILABLE_AMOUNT DECIMAL(18,2) DEFAULT 0,
    PLEDGED_AMOUNT DECIMAL(18,2) DEFAULT 0,
    CREATOR_ID DECIMAL(20,0),
    CREATOR_NAME VARCHAR(100),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50),
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_BILL_POOL IS '票据池表';
COMMENT ON COLUMN TBL_BILL_POOL.POOL_ID IS '票据池ID';
COMMENT ON COLUMN TBL_BILL_POOL.POOL_NAME IS '票据池名称';
COMMENT ON COLUMN TBL_BILL_POOL.POOL_NO IS '票据池编号';
COMMENT ON COLUMN TBL_BILL_POOL.POOL_TYPE IS '票据池类型(自营/代持/质押)';
COMMENT ON COLUMN TBL_BILL_POOL.POOL_STATUS IS '票据池状态(正常/冻结/关闭)';
COMMENT ON COLUMN TBL_BILL_POOL.TOTAL_AMOUNT IS '总金额';
COMMENT ON COLUMN TBL_BILL_POOL.BILL_COUNT IS '票据数量';
COMMENT ON COLUMN TBL_BILL_POOL.AVAILABLE_AMOUNT IS '可用金额';
COMMENT ON COLUMN TBL_BILL_POOL.PLEDGED_AMOUNT IS '已质押金额';

CREATE INDEX IDX_POOL_NO ON TBL_BILL_POOL(POOL_NO);
CREATE INDEX IDX_POOL_STATUS ON TBL_BILL_POOL(POOL_STATUS);

-- 票据池关联表
DROP TABLE IF EXISTS TBL_BILL_POOL_ITEM;

CREATE TABLE TBL_BILL_POOL_ITEM (
    ITEM_ID DECIMAL(20,0) PRIMARY KEY,
    POOL_ID DECIMAL(20,0),
    BILL_ID DECIMAL(20,0),
    ADD_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMOVE_TIME TIMESTAMP,
    STATUS VARCHAR(20),
    CREATE_USER VARCHAR(50)
);

COMMENT ON TABLE TBL_BILL_POOL_ITEM IS '票据池明细表';
CREATE INDEX IDX_POOL_ID ON TBL_BILL_POOL_ITEM(POOL_ID);
CREATE INDEX IDX_BILL_ID ON TBL_BILL_POOL_ITEM(BILL_ID);

-- 表6: 票据登记表
DROP TABLE IF EXISTS TBL_BILL_REGISTRATION;

CREATE TABLE TBL_BILL_REGISTRATION (
    REGISTRATION_ID DECIMAL(20,0) PRIMARY KEY,
    BILL_ID DECIMAL(20,0),
    REGISTRATION_NO VARCHAR(50),
    REGISTRATION_DATE TIMESTAMP,
    REGISTRATION_STATUS VARCHAR(20),
    REGISTER VARCHAR(200),
    REGISTER_ACCOUNT VARCHAR(100),
    BANK_NAME VARCHAR(200),
    BRANCH_NAME VARCHAR(200),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50),
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_BILL_REGISTRATION IS '票据登记表';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.REGISTRATION_ID IS '登记ID';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.BILL_ID IS '票据ID';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.REGISTRATION_NO IS '登记编号';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.REGISTRATION_STATUS IS '登记状态(已登记/处理中/已完成)';

CREATE INDEX IDX_REGISTRATION_NO ON TBL_BILL_REGISTRATION(REGISTRATION_NO);

-- 表7: 电子票据表
DROP TABLE IF EXISTS TBL_ELECTRONIC_BILL;

CREATE TABLE TBL_ELECTRONIC_BILL (
    E_BILL_ID DECIMAL(20,0) PRIMARY KEY,
    E_BILL_NO VARCHAR(50) NOT NULL,
    BILL_ID DECIMAL(20,0),
    ELECTRONIC_STATUS VARCHAR(20),
    SIGNATURE_STATUS VARCHAR(20),
    VERIFICATION_STATUS VARCHAR(20),
    SIGNER_NAME VARCHAR(200),
    SIGNER_CERTIFICATE VARCHAR(500),
    SIGN_TIME TIMESTAMP,
    VERIFICATION_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50),
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_ELECTRONIC_BILL IS '电子票据表';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.E_BILL_ID IS '电子票据ID';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.E_BILL_NO IS '电子票据号码';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.BILL_ID IS '票据ID';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.ELECTRONIC_STATUS IS '电子状态(待签收/已签收/已拒绝)';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.SIGNATURE_STATUS IS '签名状态(未签名/已签名)';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.VERIFICATION_STATUS IS '验证状态(未验证/已验证/验证失败)';

CREATE INDEX IDX_E_BILL_NO ON TBL_ELECTRONIC_BILL(E_BILL_NO);

-- 表8: 票据风险评估表
DROP TABLE IF EXISTS TBL_BILL_RISK_ASSESSMENT;

CREATE TABLE TBL_BILL_RISK_ASSESSMENT (
    RISK_ID DECIMAL(20,0) PRIMARY KEY,
    BILL_ID DECIMAL(20,0),
    ASSESSMENT_NO VARCHAR(50) NOT NULL,
    RISK_LEVEL VARCHAR(20),
    RISK_TYPE VARCHAR(20),
    RISK_SCORE INTEGER,
    ASSESSMENT_STATUS VARCHAR(20),
    ASSESSMENT_DATE TIMESTAMP,
    ASSESSOR VARCHAR(100),
    RISK_DESC VARCHAR(1000),
    SUGGESTION VARCHAR(1000),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50),
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_BILL_RISK_ASSESSMENT IS '票据风险评估表';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_ID IS '风险评估ID';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.BILL_ID IS '票据ID';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.ASSESSMENT_NO IS '评估编号';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_LEVEL IS '风险等级(低/中/高)';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_TYPE IS '风险类型(信用风险/市场风险/操作风险)';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_SCORE IS '风险评分';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.ASSESSMENT_STATUS IS '评估状态(草稿/已完成)';

CREATE INDEX IDX_ASSESSMENT_NO ON TBL_BILL_RISK_ASSESSMENT(ASSESSMENT_NO);
CREATE INDEX IDX_RISK_LEVEL ON TBL_BILL_RISK_ASSESSMENT(RISK_LEVEL);

COMMIT;

-- =============================================================
-- 插入测试数据
-- =============================================================

-- 测试数据: 票据信息
INSERT INTO TBL_BILL_INSTRUMENT (INSTRUMENT_ID, INSTRUMENT_NO, BILL_NO, BILL_TYPE, BILL_AMOUNT, CURRENCY_CODE, DRAWER, PAYEE, ISSUE_DATE, MATURITY_DATE, BILL_STATUS, CREATE_USER) VALUES
(1, 'INST20240001', 'BILL20240001', '银行承兑汇票', 1000000.00, 'CNY', '北京XX科技有限公司', '上海XX贸易有限公司', TIMESTAMP '2024-12-01 00:00:00', TIMESTAMP '2025-06-01 00:00:00', '已承兑', 'system');

INSERT INTO TBL_BILL_INSTRUMENT (INSTRUMENT_ID, INSTRUMENT_NO, BILL_NO, BILL_TYPE, BILL_AMOUNT, CURRENCY_CODE, DRAWER, PAYEE, ACCEPTOR, ISSUE_DATE, MATURITY_DATE, BILL_STATUS, CREATE_USER) VALUES
(2, 'INST20240002', 'BILL20240002', '商业承兑汇票', 500000.00, 'CNY', '广州XX商贸有限公司', '深圳XX供应链公司', '招商银行广州分行', TIMESTAMP '2024-12-05 00:00:00', TIMESTAMP '2025-06-05 00:00:00', '已承兑', 'system');

INSERT INTO TBL_BILL_INSTRUMENT (INSTRUMENT_ID, INSTRUMENT_NO, BILL_NO, BILL_TYPE, BILL_AMOUNT, CURRENCY_CODE, DRAWER, PAYEE, ISSUE_DATE, MATURITY_DATE, BILL_STATUS, CREATE_USER) VALUES
(3, 'INST20240003', 'BILL20240003', '电子汇票', 2000000.00, 'CNY', '上海XX实业公司', '北京XX物资公司', '工商银行上海分行', TIMESTAMP '2024-12-10 00:00:00', TIMESTAMP '2025-06-10 00:00:00', '已承兑', 'system');

-- 测试数据: 票据贴现
INSERT INTO TBL_BILL_DISCOUNT (DISCOUNT_ID, DISCOUNT_NUMBER, BILL_ID, DISCOUNT_TYPE, DISCOUNT_STATUS, DISCOUNT_BANK, DISCOUNT_RATE, DISCOUNT_AMOUNT, INTEREST_AMOUNT, ACTUAL_AMOUNT, APPLICATION_DATE, CREATE_USER) VALUES
(1, 'DISCOUNT20240001', 1, '买断式', '已完成', '工商银行北京分行', 0.035, 980000.00, 20000.00, 980000.00, TIMESTAMP '2024-12-15 00:00:00', 'system');

-- 测试数据: 票据池
INSERT INTO TBL_BILL_POOL (POOL_ID, POOL_NAME, POOL_NO, POOL_TYPE, POOL_STATUS, TOTAL_AMOUNT, BILL_COUNT, AVAILABLE_AMOUNT, PLEDGED_AMOUNT, CREATOR_NAME, CREATE_USER) VALUES
(1, '主要票据池', 'POOL2024001', '自营', '正常', 3500000.00, 3, 2500000.00, 1000000.00, '管理员', 'system');

INSERT INTO TBL_BILL_POOL_ITEM (ITEM_ID, POOL_ID, BILL_ID, STATUS, CREATE_USER) VALUES
(1, 1, 1, '正常', 'system');
INSERT INTO TBL_BILL_POOL_ITEM (ITEM_ID, POOL_ID, BILL_ID, STATUS, CREATE_USER) VALUES
(2, 1, 2, '正常', 'system');
INSERT INTO TBL_BILL_POOL_ITEM (ITEM_ID, POOL_ID, BILL_ID, STATUS, CREATE_USER) VALUES
(3, 1, 3, '已质押', 'system');

COMMIT;

-- =============================================================
-- 验证数据
-- =============================================================
-- SELECT COUNT(*) AS TOTAL_RECORDS FROM TBL_BILL_INSTRUMENT;
-- SELECT COUNT(*) AS TOTAL_RECORDS FROM TBL_BILL_DISCOUNT;
-- SELECT COUNT(*) AS TOTAL_RECORDS FROM TBL_BILL_POOL;
