-- =====================================================
-- 票据管理模块数据库表 - 达梦数据库兼容版本
-- 生成时间: 2025-12-29
-- 数据库: 达梦数据库 DM8
-- 模块: 票据管理 (Bill Management)
-- =====================================================

-- =====================================================
-- 1. 票据登记表 (TBL_BILL_REGISTRATION)
-- =====================================================
CREATE TABLE TBL_BILL_REGISTRATION (
    BILL_ID BIGINT NOT NULL PRIMARY KEY,
    BILL_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    BILL_TYPE VARCHAR(50) NOT NULL,
    BILL_AMOUNT DECIMAL(18,2) NOT NULL,
    CURRENCY VARCHAR(10) DEFAULT 'CNY',
    ISSUE_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    DRAWER_NAME VARCHAR(200) NOT NULL,
    DRAWER_ACCOUNT VARCHAR(50),
    PAYEE_NAME VARCHAR(200) NOT NULL,
    PAYEE_ACCOUNT VARCHAR(50),
    ACCEPTOR_NAME VARCHAR(200),
    ACCEPTING_BANK VARCHAR(200),
    BILL_STATUS VARCHAR(50) DEFAULT 'HOLDING',
    BILL_PURPOSE VARCHAR(50),
    BILL_SOURCE VARCHAR(50),
    STORAGE_LOCATION VARCHAR(200),
    REGISTRAR_ID BIGINT,
    REGISTRAR_NAME VARCHAR(100),
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    COMPANY_ID BIGINT,
    DEPT_ID BIGINT,
    DELETE_FLAG INT DEFAULT 0
);

COMMENT ON TABLE TBL_BILL_REGISTRATION IS '票据登记表';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.BILL_ID IS '票据ID';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.BILL_NUMBER IS '票据号码';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.BILL_TYPE IS '票据类型:BANK_ACCEPTANCE/COMMERCIAL_ACCEPTANCE/CHECK/PROMISSORY_NOTE/ELECTRONIC_BILL';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.BILL_AMOUNT IS '票据金额';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.CURRENCY IS '币种';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.ISSUE_DATE IS '出票日期';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.MATURITY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.DRAWER_NAME IS '出票人名称';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.DRAWER_ACCOUNT IS '出票人账号';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.PAYEE_NAME IS '收款人名称';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.PAYEE_ACCOUNT IS '收款人账号';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.ACCEPTOR_NAME IS '承兑人名称';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.ACCEPTING_BANK IS '承兑银行';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.BILL_STATUS IS '票据状态:HOLDING/ENDORSED/DISCOUNTED/MATURED/CANCELLED';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.BILL_PURPOSE IS '票据用途:PAYMENT/SERVICE_FEE/INVESTMENT/OTHER';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.BILL_SOURCE IS '票据来源:RECEIVED/ISSUED/ENDORSED';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.STORAGE_LOCATION IS '保管地点';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.REGISTRAR_ID IS '登记人ID';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.REGISTRAR_NAME IS '登记人姓名';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.REMARK IS '备注';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.COMPANY_ID IS '公司ID';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.DEPT_ID IS '部门ID';
COMMENT ON COLUMN TBL_BILL_REGISTRATION.DELETE_FLAG IS '删除标记:0-未删除,1-已删除';

-- 创建索引
CREATE INDEX IDX_BILL_NUMBER ON TBL_BILL_REGISTRATION(BILL_NUMBER);
CREATE INDEX IDX_BILL_TYPE ON TBL_BILL_REGISTRATION(BILL_TYPE);
CREATE INDEX IDX_BILL_STATUS ON TBL_BILL_REGISTRATION(BILL_STATUS);
CREATE INDEX IDX_MATURITY_DATE ON TBL_BILL_REGISTRATION(MATURITY_DATE);
CREATE INDEX IDX_COMPANY_ID ON TBL_BILL_REGISTRATION(COMPANY_ID);

-- 创建序列
CREATE SEQUENCE SEQ_BILL_REGISTRATION START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 2. 票据背书表 (TBL_BILL_ENDORSEMENT)
-- =====================================================
CREATE TABLE TBL_BILL_ENDORSEMENT (
    ENDORSEMENT_ID BIGINT NOT NULL PRIMARY KEY,
    ENDORSEMENT_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    BILL_NUMBER VARCHAR(50) NOT NULL,
    ENDORSEMENT_TYPE VARCHAR(50) NOT NULL,
    BILL_AMOUNT DECIMAL(18,2) NOT NULL,
    ENDORSER_NAME VARCHAR(200) NOT NULL,
    ENDORSER_ACCOUNT VARCHAR(50),
    ENDORSEE_NAME VARCHAR(200) NOT NULL,
    ENDORSEE_ACCOUNT VARCHAR(50),
    ENDORSEE_BANK VARCHAR(200),
    CONTACT_PHONE VARCHAR(20),
    APPLICATION_DATE DATE NOT NULL,
    EXPECTED_EXECUTION_DATE DATE,
    ACTUAL_EXECUTION_DATE DATE,
    ENDORSEMENT_STATUS VARCHAR(50) DEFAULT 'PENDING',
    APPLICANT_ID BIGINT,
    APPLICANT_NAME VARCHAR(100),
    APPROVER_ID BIGINT,
    APPROVER_NAME VARCHAR(100),
    APPROVAL_DATE DATE,
    APPROVAL_COMMENT VARCHAR(500),
    ENDORSEMENT_PURPOSE VARCHAR(50),
    IS_CONTINUOUS INT DEFAULT 1,
    RISK_LEVEL VARCHAR(50) DEFAULT 'LOW',
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    COMPANY_ID BIGINT,
    DEPT_ID BIGINT,
    DELETE_FLAG INT DEFAULT 0
);

COMMENT ON TABLE TBL_BILL_ENDORSEMENT IS '票据背书表';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.ENDORSEMENT_ID IS '背书ID';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.ENDORSEMENT_NUMBER IS '背书编号';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.BILL_NUMBER IS '票据号码';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.ENDORSEMENT_TYPE IS '背书类型:TRANSFER/PLEDGE/COLLECTION';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.ENDORSEMENT_STATUS IS '背书状态:PENDING/APPROVED/EXECUTED/REJECTED/CANCELLED';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.IS_CONTINUOUS IS '是否连续背书:1-是,0-否';
COMMENT ON COLUMN TBL_BILL_ENDORSEMENT.RISK_LEVEL IS '风险等级:LOW/MEDIUM/HIGH';

-- 创建索引
CREATE INDEX IDX_ENDORSEMENT_NUMBER ON TBL_BILL_ENDORSEMENT(ENDORSEMENT_NUMBER);
CREATE INDEX IDX_ENDORSEMENT_BILL_NUMBER ON TBL_BILL_ENDORSEMENT(BILL_NUMBER);
CREATE INDEX IDX_ENDORSEMENT_STATUS ON TBL_BILL_ENDORSEMENT(ENDORSEMENT_STATUS);
CREATE INDEX IDX_ENDORSEMENT_COMPANY_ID ON TBL_BILL_ENDORSEMENT(COMPANY_ID);

-- 创建序列
CREATE SEQUENCE SEQ_BILL_ENDORSEMENT START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 3. 票据贴现表 (TBL_BILL_DISCOUNT)
-- =====================================================
CREATE TABLE TBL_BILL_DISCOUNT (
    DISCOUNT_ID BIGINT NOT NULL PRIMARY KEY,
    DISCOUNT_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    BILL_NUMBER VARCHAR(50) NOT NULL,
    BILL_AMOUNT DECIMAL(18,2) NOT NULL,
    DISCOUNT_RATE DECIMAL(5,2) NOT NULL,
    DISCOUNT_PERIOD INT NOT NULL,
    DISCOUNT_INTEREST DECIMAL(18,2),
    DISCOUNT_AMOUNT DECIMAL(18,2),
    DISCOUNT_BANK VARCHAR(200) NOT NULL,
    APPLICATION_DATE DATE NOT NULL,
    EXPECTED_DISCOUNT_DATE DATE,
    ACTUAL_DISCOUNT_DATE DATE,
    DISCOUNT_STATUS VARCHAR(50) DEFAULT 'PENDING',
    APPLICANT_ID BIGINT,
    APPLICANT_NAME VARCHAR(100),
    APPROVER_ID BIGINT,
    APPROVER_NAME VARCHAR(100),
    APPROVAL_DATE DATE,
    APPROVAL_COMMENT VARCHAR(500),
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    COMPANY_ID BIGINT,
    DEPT_ID BIGINT,
    DELETE_FLAG INT DEFAULT 0
);

COMMENT ON TABLE TBL_BILL_DISCOUNT IS '票据贴现表';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_ID IS '贴现ID';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_NUMBER IS '贴现编号';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.BILL_NUMBER IS '票据号码';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_RATE IS '贴现率(%)';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_PERIOD IS '贴现期限(天)';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_INTEREST IS '贴现利息';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_AMOUNT IS '贴现金额';
COMMENT ON COLUMN TBL_BILL_DISCOUNT.DISCOUNT_STATUS IS '贴现状态:PENDING/APPROVED/EXECUTED/REJECTED';

-- 创建索引
CREATE INDEX IDX_DISCOUNT_NUMBER ON TBL_BILL_DISCOUNT(DISCOUNT_NUMBER);
CREATE INDEX IDX_DISCOUNT_BILL_NUMBER ON TBL_BILL_DISCOUNT(BILL_NUMBER);
CREATE INDEX IDX_DISCOUNT_STATUS ON TBL_BILL_DISCOUNT(DISCOUNT_STATUS);
CREATE INDEX IDX_DISCOUNT_COMPANY_ID ON TBL_BILL_DISCOUNT(COMPANY_ID);

-- 创建序列
CREATE SEQUENCE SEQ_BILL_DISCOUNT START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 4. 票据到期表 (TBL_BILL_MATURITY)
-- =====================================================
CREATE TABLE TBL_BILL_MATURITY (
    MATURITY_ID BIGINT NOT NULL PRIMARY KEY,
    BILL_ID BIGINT NOT NULL,
    BILL_NUMBER VARCHAR(50) NOT NULL,
    BILL_TYPE VARCHAR(50),
    BILL_AMOUNT DECIMAL(18,2) NOT NULL,
    DRAWER_NAME VARCHAR(200),
    ACCEPTOR_NAME VARCHAR(200),
    ISSUE_DATE DATE,
    MATURITY_DATE DATE NOT NULL,
    REMAINING_DAYS INT,
    MATURITY_STATUS VARCHAR(50) NOT NULL,
    REMINDER_STATUS VARCHAR(50) DEFAULT 'NOT_SENT',
    PROCESS_TYPE VARCHAR(50),
    PROCESS_DATE DATE,
    PROCESS_DESCRIPTION VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    COMPANY_ID BIGINT,
    DEPT_ID BIGINT,
    DELETE_FLAG INT DEFAULT 0
);

COMMENT ON TABLE TBL_BILL_MATURITY IS '票据到期表';
COMMENT ON COLUMN TBL_BILL_MATURITY.MATURITY_ID IS '到期记录ID';
COMMENT ON COLUMN TBL_BILL_MATURITY.BILL_ID IS '票据ID';
COMMENT ON COLUMN TBL_BILL_MATURITY.MATURITY_STATUS IS '到期状态:NOT_MATURED/EXPIRING/MATURED/PROCESSED/OVERDUE';
COMMENT ON COLUMN TBL_BILL_MATURITY.REMINDER_STATUS IS '提醒状态:NOT_SENT/SENT/CONFIRMED';
COMMENT ON COLUMN TBL_BILL_MATURITY.PROCESS_TYPE IS '处理方式:COLLECT/EXTEND/RETURN/DISCOUNT';

-- 创建索引
CREATE INDEX IDX_MATURITY_BILL_ID ON TBL_BILL_MATURITY(BILL_ID);
CREATE INDEX IDX_MATURITY_BILL_NUMBER ON TBL_BILL_MATURITY(BILL_NUMBER);
CREATE INDEX IDX_MATURITY_STATUS ON TBL_BILL_MATURITY(MATURITY_STATUS);
CREATE INDEX IDX_MATURITY_DATE_STATUS ON TBL_BILL_MATURITY(MATURITY_DATE, MATURITY_STATUS);

-- 创建序列
CREATE SEQUENCE SEQ_BILL_MATURITY START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 5. 票据风险评估表 (TBL_BILL_RISK_ASSESSMENT)
-- =====================================================
CREATE TABLE TBL_BILL_RISK_ASSESSMENT (
    ASSESSMENT_ID BIGINT NOT NULL PRIMARY KEY,
    BILL_NUMBER VARCHAR(50) NOT NULL,
    BILL_AMOUNT DECIMAL(18,2) NOT NULL,
    RISK_LEVEL VARCHAR(50) NOT NULL,
    RISK_SCORE INT NOT NULL,
    RISK_FACTORS CLOB,
    RISK_SUGGESTIONS CLOB,
    ASSESSOR_ID BIGINT,
    ASSESSOR_NAME VARCHAR(100),
    ASSESSMENT_DATE DATE NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    COMPANY_ID BIGINT,
    DEPT_ID BIGINT,
    DELETE_FLAG INT DEFAULT 0
);

COMMENT ON TABLE TBL_BILL_RISK_ASSESSMENT IS '票据风险评估表';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.ASSESSMENT_ID IS '评估ID';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_LEVEL IS '风险等级:LOW/MEDIUM/HIGH';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_SCORE IS '风险评分(0-100)';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_FACTORS IS '风险因素(JSON数组)';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_SUGGESTIONS IS '风险建议(JSON数组)';

-- 创建索引
CREATE INDEX IDX_RISK_BILL_NUMBER ON TBL_BILL_RISK_ASSESSMENT(BILL_NUMBER);
CREATE INDEX IDX_RISK_LEVEL ON TBL_BILL_RISK_ASSESSMENT(RISK_LEVEL);
CREATE INDEX IDX_RISK_COMPANY_ID ON TBL_BILL_RISK_ASSESSMENT(COMPANY_ID);

-- 创建序列
CREATE SEQUENCE SEQ_BILL_RISK_ASSESSMENT START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 6. 票据风险预警表 (TBL_BILL_RISK_ALERT)
-- =====================================================
CREATE TABLE TBL_BILL_RISK_ALERT (
    ALERT_ID BIGINT NOT NULL PRIMARY KEY,
    BILL_NUMBER VARCHAR(50) NOT NULL,
    ALERT_TYPE VARCHAR(50) NOT NULL,
    ALERT_LEVEL VARCHAR(50) NOT NULL,
    ALERT_MESSAGE VARCHAR(500),
    ALERT_STATUS VARCHAR(50) DEFAULT 'PENDING',
    DISPOSE_ACTION VARCHAR(50),
    DISPOSE_REMARK VARCHAR(500),
    DISPOSE_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    COMPANY_ID BIGINT,
    DEPT_ID BIGINT,
    DELETE_FLAG INT DEFAULT 0
);

COMMENT ON TABLE TBL_BILL_RISK_ALERT IS '票据风险预警表';
COMMENT ON COLUMN TBL_BILL_RISK_ALERT.ALERT_ID IS '预警ID';
COMMENT ON COLUMN TBL_BILL_RISK_ALERT.ALERT_TYPE IS '预警类型:MATURITY_APPROACHING/HIGH_RISK/OVERDUE';
COMMENT ON COLUMN TBL_BILL_RISK_ALERT.ALERT_LEVEL IS '预警级别:LOW/MEDIUM/HIGH';
COMMENT ON COLUMN TBL_BILL_RISK_ALERT.ALERT_STATUS IS '预警状态:PENDING/HANDLED/IGNORED';
COMMENT ON COLUMN TBL_BILL_RISK_ALERT.DISPOSE_ACTION IS '处置方式:HANDLE/IGNORE';

-- 创建索引
CREATE INDEX IDX_ALERT_BILL_NUMBER ON TBL_BILL_RISK_ALERT(BILL_NUMBER);
CREATE INDEX IDX_ALERT_STATUS ON TBL_BILL_RISK_ALERT(ALERT_STATUS);
CREATE INDEX IDX_ALERT_LEVEL ON TBL_BILL_RISK_ALERT(ALERT_LEVEL);

-- 创建序列
CREATE SEQUENCE SEQ_BILL_RISK_ALERT START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 7. 电子票据表 (TBL_ELECTRONIC_BILL)
-- =====================================================
CREATE TABLE TBL_ELECTRONIC_BILL (
    ELECTRONIC_BILL_ID BIGINT NOT NULL PRIMARY KEY,
    BILL_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    BILL_TYPE VARCHAR(50) NOT NULL,
    BILL_AMOUNT DECIMAL(18,2) NOT NULL,
    DIGITAL_SIGNATURE VARCHAR(1000),
    SIGNATURE_STATUS VARCHAR(50),
    VERIFICATION_STATUS VARCHAR(50),
    ELECTRONIC_STATUS VARCHAR(50) DEFAULT 'VALID',
    ISSUE_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    CERTIFICATE_ID VARCHAR(100),
    SIGNER_NAME VARCHAR(100),
    SIGNER_ORG VARCHAR(200),
    VERIFICATION_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    COMPANY_ID BIGINT,
    DEPT_ID BIGINT,
    DELETE_FLAG INT DEFAULT 0
);

COMMENT ON TABLE TBL_ELECTRONIC_BILL IS '电子票据表';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.ELECTRONIC_BILL_ID IS '电子票据ID';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.DIGITAL_SIGNATURE IS '数字签名';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.SIGNATURE_STATUS IS '签名状态:UNSIGNED/SIGNED/VERIFIED';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.VERIFICATION_STATUS IS '验证状态:NOT_VERIFIED/VERIFIED/FAILED';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.ELECTRONIC_STATUS IS '电子票据状态:VALID/INVALID/EXPIRED';

-- 创建索引
CREATE INDEX IDX_EBILL_NUMBER ON TBL_ELECTRONIC_BILL(BILL_NUMBER);
CREATE INDEX IDX_EBILL_STATUS ON TBL_ELECTRONIC_BILL(ELECTRONIC_STATUS);
CREATE INDEX IDX_EBILL_COMPANY_ID ON TBL_ELECTRONIC_BILL(COMPANY_ID);

-- 创建序列
CREATE SEQUENCE SEQ_ELECTRONIC_BILL START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 8. 电子票据流转记录表 (TBL_ELECTRONIC_BILL_TRANSFER)
-- =====================================================
CREATE TABLE TBL_ELECTRONIC_BILL_TRANSFER (
    TRANSFER_ID BIGINT NOT NULL PRIMARY KEY,
    BILL_ID BIGINT NOT NULL,
    BILL_NUMBER VARCHAR(50) NOT NULL,
    FROM_PARTY VARCHAR(200) NOT NULL,
    TO_PARTY VARCHAR(200) NOT NULL,
    TRANSFER_TYPE VARCHAR(50) NOT NULL,
    TRANSFER_TIME TIMESTAMP NOT NULL,
    TRANSFER_AMOUNT DECIMAL(18,2),
    TRANSFER_STATUS VARCHAR(50),
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    COMPANY_ID BIGINT,
    DELETE_FLAG INT DEFAULT 0
);

COMMENT ON TABLE TBL_ELECTRONIC_BILL_TRANSFER IS '电子票据流转记录表';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL_TRANSFER.TRANSFER_ID IS '流转ID';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL_TRANSFER.TRANSFER_TYPE IS '流转类型:ENDORSEMENT/DISCOUNT/PLEDGE';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL_TRANSFER.TRANSFER_STATUS IS '流转状态:SUCCESS/FAILED/PENDING';

-- 创建索引
CREATE INDEX IDX_TRANSFER_BILL_ID ON TBL_ELECTRONIC_BILL_TRANSFER(BILL_ID);
CREATE INDEX IDX_TRANSFER_BILL_NUMBER ON TBL_ELECTRONIC_BILL_TRANSFER(BILL_NUMBER);

-- 创建序列
CREATE SEQUENCE SEQ_ELECTRONIC_BILL_TRANSFER START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 9. 票据摊销表 (TBL_BILL_AMORTIZATION)
-- =====================================================
CREATE TABLE TBL_BILL_AMORTIZATION (
    AMORTIZATION_ID BIGINT NOT NULL PRIMARY KEY,
    BILL_NUMBER VARCHAR(50) NOT NULL,
    TOTAL_AMOUNT DECIMAL(18,2) NOT NULL,
    AMORTIZED_AMOUNT DECIMAL(18,2) DEFAULT 0,
    REMAINING_AMOUNT DECIMAL(18,2),
    AMORTIZATION_METHOD VARCHAR(50) NOT NULL,
    AMORTIZATION_PERIOD INT NOT NULL,
    MONTHLY_AMOUNT DECIMAL(18,2),
    AMORTIZATION_STATUS VARCHAR(50) DEFAULT 'ACTIVE',
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    COMPANY_ID BIGINT,
    DEPT_ID BIGINT,
    DELETE_FLAG INT DEFAULT 0
);

COMMENT ON TABLE TBL_BILL_AMORTIZATION IS '票据摊销表';
COMMENT ON COLUMN TBL_BILL_AMORTIZATION.AMORTIZATION_ID IS '摊销ID';
COMMENT ON COLUMN TBL_BILL_AMORTIZATION.AMORTIZATION_METHOD IS '摊销方法:STRAIGHT_LINE/DECLINING_BALANCE';
COMMENT ON COLUMN TBL_BILL_AMORTIZATION.AMORTIZATION_PERIOD IS '摊销期数(月)';
COMMENT ON COLUMN TBL_BILL_AMORTIZATION.AMORTIZATION_STATUS IS '摊销状态:ACTIVE/COMPLETED/CANCELLED';

-- 创建索引
CREATE INDEX IDX_AMORTIZATION_BILL_NUMBER ON TBL_BILL_AMORTIZATION(BILL_NUMBER);
CREATE INDEX IDX_AMORTIZATION_STATUS ON TBL_BILL_AMORTIZATION(AMORTIZATION_STATUS);

-- 创建序列
CREATE SEQUENCE SEQ_BILL_AMORTIZATION START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 10. 票据册表 (TBL_BILL_BOOK)
-- =====================================================
CREATE TABLE TBL_BILL_BOOK (
    BOOK_ID BIGINT NOT NULL PRIMARY KEY,
    BOOK_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    BOOK_NAME VARCHAR(200) NOT NULL,
    BILL_COUNT INT DEFAULT 0,
    TOTAL_AMOUNT DECIMAL(18,2) DEFAULT 0,
    BOOK_STATUS VARCHAR(50) DEFAULT 'ACTIVE',
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CLOSE_DATE DATE,
    CLOSE_OPERATOR VARCHAR(100),
    CREATOR_NAME VARCHAR(100),
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    COMPANY_ID BIGINT,
    DEPT_ID BIGINT,
    DELETE_FLAG INT DEFAULT 0
);

COMMENT ON TABLE TBL_BILL_BOOK IS '票据册表';
COMMENT ON COLUMN TBL_BILL_BOOK.BOOK_ID IS '票据册ID';
COMMENT ON COLUMN TBL_BILL_BOOK.BOOK_NUMBER IS '票据册编号';
COMMENT ON COLUMN TBL_BILL_BOOK.BOOK_NAME IS '票据册名称';
COMMENT ON COLUMN TBL_BILL_BOOK.BILL_COUNT IS '票据数量';
COMMENT ON COLUMN TBL_BILL_BOOK.TOTAL_AMOUNT IS '总金额';
COMMENT ON COLUMN TBL_BILL_BOOK.BOOK_STATUS IS '票据册状态:ACTIVE/CLOSED/ARCHIVED';

-- 创建索引
CREATE INDEX IDX_BOOK_NUMBER ON TBL_BILL_BOOK(BOOK_NUMBER);
CREATE INDEX IDX_BOOK_STATUS ON TBL_BILL_BOOK(BOOK_STATUS);
CREATE INDEX IDX_BOOK_COMPANY_ID ON TBL_BILL_BOOK(COMPANY_ID);

-- 创建序列
CREATE SEQUENCE SEQ_BILL_BOOK START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 11. 票据册明细表 (TBL_BILL_BOOK_DETAIL)
-- =====================================================
CREATE TABLE TBL_BILL_BOOK_DETAIL (
    DETAIL_ID BIGINT NOT NULL PRIMARY KEY,
    BOOK_ID BIGINT NOT NULL,
    BILL_ID BIGINT NOT NULL,
    BILL_NUMBER VARCHAR(50) NOT NULL,
    ADD_TIME TIMESTAMP NOT NULL,
    REMOVE_TIME TIMESTAMP,
    STATUS VARCHAR(50) DEFAULT 'ACTIVE',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    DELETE_FLAG INT DEFAULT 0
);

COMMENT ON TABLE TBL_BILL_BOOK_DETAIL IS '票据册明细表';
COMMENT ON COLUMN TBL_BILL_BOOK_DETAIL.DETAIL_ID IS '明细ID';
COMMENT ON COLUMN TBL_BILL_BOOK_DETAIL.BOOK_ID IS '票据册ID';
COMMENT ON COLUMN TBL_BILL_BOOK_DETAIL.BILL_ID IS '票据ID';
COMMENT ON COLUMN TBL_BILL_BOOK_DETAIL.STATUS IS '状态:ACTIVE/REMOVED';

-- 创建索引
CREATE INDEX IDX_BOOK_DETAIL_BOOK_ID ON TBL_BILL_BOOK_DETAIL(BOOK_ID);
CREATE INDEX IDX_BOOK_DETAIL_BILL_ID ON TBL_BILL_BOOK_DETAIL(BILL_ID);

-- 创建序列
CREATE SEQUENCE SEQ_BILL_BOOK_DETAIL START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 测试数据插入
-- =====================================================

-- 插入票据登记测试数据
INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE,
    DRAWER_NAME, PAYEE_NAME, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, BILL_SOURCE,
    STORAGE_LOCATION, REGISTRAR_NAME, REMARK, CREATE_BY, COMPANY_ID, DEPT_ID)
VALUES (SEQ_BILL_REGISTRATION.NEXTVAL, 'BA20240925001', 'BANK_ACCEPTANCE', 1000000.00, 'CNY',
    TO_DATE('2024-09-25', 'YYYY-MM-DD'), TO_DATE('2024-12-25', 'YYYY-MM-DD'),
    '华博云科技有限公司', '供应商A', '中国工商银行', '中国工商银行北京分行',
    'HOLDING', 'PAYMENT', 'ISSUED', '财务部保险柜', '张三', '货款支付票据', 'admin', 1, 1);

INSERT INTO TBL_BILL_REGISTRATION (BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT, CURRENCY, ISSUE_DATE, MATURITY_DATE,
    DRAWER_NAME, PAYEE_NAME, ACCEPTOR_NAME, ACCEPTING_BANK, BILL_STATUS, BILL_PURPOSE, BILL_SOURCE,
    STORAGE_LOCATION, REGISTRAR_NAME, REMARK, CREATE_BY, COMPANY_ID, DEPT_ID)
VALUES (SEQ_BILL_REGISTRATION.NEXTVAL, 'CA20240926001', 'COMMERCIAL_ACCEPTANCE', 500000.00, 'CNY',
    TO_DATE('2024-09-26', 'YYYY-MM-DD'), TO_DATE('2025-03-26', 'YYYY-MM-DD'),
    '华博云科技有限公司', '供应商B', '华博云科技有限公司', NULL,
    'HOLDING', 'SERVICE_FEE', 'ISSUED', '财务部保险柜', '李四', '服务费支付票据', 'admin', 1, 1);

-- 插入票据背书测试数据
INSERT INTO TBL_BILL_ENDORSEMENT (ENDORSEMENT_ID, ENDORSEMENT_NUMBER, BILL_NUMBER, ENDORSEMENT_TYPE, BILL_AMOUNT,
    ENDORSER_NAME, ENDORSEE_NAME, ENDORSEE_BANK, APPLICATION_DATE, ENDORSEMENT_STATUS,
    APPLICANT_NAME, ENDORSEMENT_PURPOSE, IS_CONTINUOUS, RISK_LEVEL, CREATE_BY, COMPANY_ID, DEPT_ID)
VALUES (SEQ_BILL_ENDORSEMENT.NEXTVAL, 'EN20240927001', 'BA20240925001', 'TRANSFER', 1000000.00,
    '华博云科技有限公司', '供应商C', '中国建设银行', TO_DATE('2024-09-27', 'YYYY-MM-DD'), 'PENDING',
    '张三', 'PAYMENT', 1, 'LOW', 'admin', 1, 1);

-- 插入票据贴现测试数据
INSERT INTO TBL_BILL_DISCOUNT (DISCOUNT_ID, DISCOUNT_NUMBER, BILL_NUMBER, BILL_AMOUNT, DISCOUNT_RATE, DISCOUNT_PERIOD,
    DISCOUNT_INTEREST, DISCOUNT_AMOUNT, DISCOUNT_BANK, APPLICATION_DATE, DISCOUNT_STATUS,
    APPLICANT_NAME, REMARK, CREATE_BY, COMPANY_ID, DEPT_ID)
VALUES (SEQ_BILL_DISCOUNT.NEXTVAL, 'DN20240928001', 'CA20240926001', 500000.00, 3.5, 90,
    4375.00, 495625.00, '中国工商银行', TO_DATE('2024-09-28', 'YYYY-MM-DD'), 'PENDING',
    '李四', '急需资金周转', 'admin', 1, 1);

-- 插入票据册测试数据
INSERT INTO TBL_BILL_BOOK (BOOK_ID, BOOK_NUMBER, BOOK_NAME, BILL_COUNT, TOTAL_AMOUNT, BOOK_STATUS,
    START_DATE, END_DATE, CREATOR_NAME, REMARK, CREATE_BY, COMPANY_ID, DEPT_ID)
VALUES (SEQ_BILL_BOOK.NEXTVAL, 'BK2024001', '2024年第一册', 2, 1500000.00, 'ACTIVE',
    TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'),
    '张三', '上半年票据册', 'admin', 1, 1);

COMMIT;

-- =====================================================
-- 脚本执行完成
-- =====================================================

