-- ===================================================================
-- 检查TC_DATA_SOURCE_CONFIG表的实际结构
-- 达梦数据库(DM8)
-- ===================================================================

-- 查询表中所有字段
SELECT
    COLUMN_NAME AS "字段名",
    DATA_TYPE AS "数据类型",
    DATA_LENGTH AS "长度",
    NULLABLE AS "可为空",
    DATA_DEFAULT AS "默认值"
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'TC_DATA_SOURCE_CONFIG'
ORDER BY COLUMN_ID;

-- 查询表的索引
SELECT
    INDEX_NAME AS "索引名",
    COLUMN_NAME AS "列名",
    INDEX_POSITION AS "位置"
FROM USER_IND_COLUMNS
WHERE TABLE_NAME = 'TC_DATA_SOURCE_CONFIG'
ORDER BY INDEX_NAME, INDEX_POSITION;

-- 查询表的主键
SELECT
    CONSTRAINTS.CONSTRAINT_NAME AS "约束名",
    CONSTRAINTS.CONSTRAINT_TYPE AS "约束类型",
    COLUMNS.COLUMN_NAME AS "列名"
FROM USER_CONSTRAINTS CONSTRAINTS
JOIN USER_CONS_COLUMNS COLUMNS ON CONSTRAINTS.CONSTRAINT_NAME = COLUMNS.CONSTRAINT_NAME
WHERE CONSTRAINTS.TABLE_NAME = 'TC_DATA_SOURCE_CONFIG'
AND CONSTRAINTS.CONSTRAINT_TYPE = 'P';

-- 查询表的行数
SELECT COUNT(*) AS "总行数" FROM TC_DATA_SOURCE_CONFIG;
