-- 租金计划表
-- 执行时间: 2026-02-09
-- 说明: 创建租金计划表，用于管理融资租赁的租金支付计划

CREATE TABLE TBL_LEASE_PAYMENT (
    PAYMENT_ID NUMBER(19) PRIMARY KEY,
    LEASE_ID NUMBER(19) NOT NULL,
    PERIOD NUMBER(10) NOT NULL,
    DUE_DATE DATE,
    PRINCIPAL NUMBER(20,2),
    INTEREST NUMBER(20,2),
    AMOUNT NUMBER(20,2),
    PAID_AMOUNT NUMBER(20,2),
    PAID_DATE DATE,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    REMARK VARCHAR2(500),
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE,
    CONSTRAINT FK_LEASE_PAYMENT_LEASE FOREIGN KEY (LEASE_ID) REFERENCES TBL_FINANCIAL_LEASE(LEASE_ID)
);

COMMENT ON TABLE TBL_LEASE_PAYMENT IS '租金计划表';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.PAYMENT_ID IS '付款ID';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.LEASE_ID IS '租赁ID';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.PERIOD IS '期数';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.DUE_DATE IS '应付日期';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.PRINCIPAL IS '本金';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.INTEREST IS '利息';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.AMOUNT IS '应付金额';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.PAID_AMOUNT IS '实付金额';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.PAID_DATE IS '付款日期';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.STATUS IS '状态(PENDING-待付/PAID-已付/OVERDUE-逾期)';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.REMARK IS '备注';

-- 创建索引
CREATE INDEX IDX_LEASE_PAYMENT_LEASE_ID ON TBL_LEASE_PAYMENT(LEASE_ID);
CREATE INDEX IDX_LEASE_PAYMENT_STATUS ON TBL_LEASE_PAYMENT(STATUS);
CREATE INDEX IDX_LEASE_PAYMENT_DUE_DATE ON TBL_LEASE_PAYMENT(DUE_DATE);

