-- 第三方账户表创建SQL
-- 兼容达梦数据库
-- 创建第三方账户表
CREATE TABLE TBL_THIRD_PARTY_ACCOUNT (
    ID VARCHAR(32) PRIMARY KEY,
    ACCOUNT_CODE VARCHAR(100) NOT NULL,
    ACCOUNT_NAME VARCHAR(200) NOT NULL,
    THIRD_PARTY_SYSTEM VARCHAR(50) NOT NULL,
    ACCOUNT_TYPE VARCHAR(50),
    CONNECTION_STATUS VARCHAR(50),
    ACCOUNT_NUMBER VARCHAR(100),
    BANK_NAME VARCHAR(200),
    BRANCH_NAME VARCHAR(200),
    CONTACT_PERSON VARCHAR(100),
    CONTACT_PHONE VARCHAR(20),
    CONTACT_EMAIL VARCHAR(200),
    API_URL VARCHAR(500),
    API_KEY VARCHAR(200),
    API_SECRET VARCHAR(200),
    STATUS VARCHAR(20),
    REMARK TEXT,
    IS_ENABLED VARCHAR(1) DEFAULT '1',
    CREATE_BY VARCHAR(50),
    CREATE_TIME DATETIME,
    UPDATE_BY VARCHAR(50),
    UPDATE_TIME DATETIME
);

-- 创建索引
CREATE INDEX IDX_THIRD_PARTY_ACCOUNT_CODE ON TBL_THIRD_PARTY_ACCOUNT(ACCOUNT_CODE);
CREATE INDEX IDX_THIRD_PARTY_ACCOUNT_NAME ON TBL_THIRD_PARTY_ACCOUNT(ACCOUNT_NAME);
CREATE INDEX IDX_THIRD_PARTY_SYSTEM ON TBL_THIRD_PARTY_ACCOUNT(THIRD_PARTY_SYSTEM);
CREATE INDEX IDX_THIRD_PARTY_TYPE ON TBL_THIRD_PARTY_ACCOUNT(ACCOUNT_TYPE);
CREATE INDEX IDX_CONNECTION_STATUS ON TBL_THIRD_PARTY_ACCOUNT(CONNECTION_STATUS);
CREATE INDEX IDX_CREATE_TIME ON TBL_THIRD_PARTY_ACCOUNT(CREATE_TIME);

-- 插入一些示例数据
INSERT INTO TBL_THIRD_PARTY_ACCOUNT (
    ID, ACCOUNT_CODE, ACCOUNT_NAME, THIRD_PARTY_SYSTEM, ACCOUNT_TYPE, CONNECTION_STATUS,
    ACCOUNT_NUMBER, BANK_NAME, BRANCH_NAME, CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    API_URL, API_KEY, STATUS, REMARK, IS_ENABLED, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
) VALUES (
    '1', 'ICBC_001', '工商银行企业账户', 'ICBC', 'CHECKING', 'CONNECTED',
    '6222020200012345678', '工商银行', '北京分行营业部', '张三', '13800138000', 'zhangsan@example.com',
    'https://api.icbc.com', 'icbc_key_001', 'ACTIVE', '主要对公账户', '1', 'admin', NOW(), 'admin', NOW()
);

INSERT INTO TBL_THIRD_PARTY_ACCOUNT (
    ID, ACCOUNT_CODE, ACCOUNT_NAME, THIRD_PARTY_SYSTEM, ACCOUNT_TYPE, CONNECTION_STATUS,
    ACCOUNT_NUMBER, BANK_NAME, BRANCH_NAME, CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    API_URL, API_KEY, STATUS, REMARK, IS_ENABLED, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
) VALUES (
    '2', 'CCB_001', '建设银行企业账户', 'CCB', 'SAVINGS', 'CONNECTED',
    '6222080100123456789', '建设银行', '上海分行营业部', '李四', '13800138000', 'lisi@example.com',
    'https://api.ccb.com', 'ccb_key_001', 'ACTIVE', '储蓄账户', '1', 'admin', NOW(), 'admin', NOW()
);

INSERT INTO TBL_THIRD_PARTY_ACCOUNT (
    ID, ACCOUNT_CODE, ACCOUNT_NAME, THIRD_PARTY_SYSTEM, ACCOUNT_TYPE, CONNECTION_STATUS,
    ACCOUNT_NUMBER, BANK_NAME, BRANCH_NAME, CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    API_URL, API_KEY, STATUS, REMARK, IS_ENABLED, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
) VALUES (
    '3', 'BOC_001', '中国银行企业账户', 'BOC', 'CREDIT', 'DISCONNECTED',
    '6222085800012345678', '中国银行', '广州分行营业部', '王五', '13800138000', 'wangwu@example.com',
    'https://api.boc.com', 'boc_key_001', 'INACTIVE', '信用账户，待连接', '1', 'admin', NOW(), 'admin', NOW()
);