-- 租赁资产表
-- 执行时间: 2026-02-09
-- 说明: 创建租赁资产表，用于管理融资租赁的资产信息

CREATE TABLE TBL_LEASE_ASSET (
    ASSET_ID NUMBER(19) PRIMARY KEY,
    LEASE_ID NUMBER(19) NOT NULL,
    ASSET_CODE VARCHAR2(50),
    ASSET_NAME VARCHAR2(200) NOT NULL,
    ASSET_TYPE VARCHAR2(50),
    ASSET_VALUE NUMBER(20,2),
    PURCHASE_DATE DATE,
    LOCATION VARCHAR2(200),
    DESCRIPTION VARCHAR2(500),
    STATUS VARCHAR2(20) DEFAULT 'NORMAL',
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE,
    CONSTRAINT FK_LEASE_ASSET_LEASE FOREIGN KEY (LEASE_ID) REFERENCES TBL_FINANCIAL_LEASE(LEASE_ID)
);

COMMENT ON TABLE TBL_LEASE_ASSET IS '租赁资产表';
COMMENT ON COLUMN TBL_LEASE_ASSET.ASSET_ID IS '资产ID';
COMMENT ON COLUMN TBL_LEASE_ASSET.LEASE_ID IS '租赁ID';
COMMENT ON COLUMN TBL_LEASE_ASSET.ASSET_CODE IS '资产编号';
COMMENT ON COLUMN TBL_LEASE_ASSET.ASSET_NAME IS '资产名称';
COMMENT ON COLUMN TBL_LEASE_ASSET.ASSET_TYPE IS '资产类型(EQUIPMENT-设备/VEHICLE-车辆/PROPERTY-房产/OTHER-其他)';
COMMENT ON COLUMN TBL_LEASE_ASSET.ASSET_VALUE IS '资产价值';
COMMENT ON COLUMN TBL_LEASE_ASSET.PURCHASE_DATE IS '购置日期';
COMMENT ON COLUMN TBL_LEASE_ASSET.LOCATION IS '存放位置';
COMMENT ON COLUMN TBL_LEASE_ASSET.DESCRIPTION IS '资产描述';
COMMENT ON COLUMN TBL_LEASE_ASSET.STATUS IS '状态(NORMAL-正常/ABNORMAL-异常)';

-- 创建索引
CREATE INDEX IDX_LEASE_ASSET_LEASE_ID ON TBL_LEASE_ASSET(LEASE_ID);
CREATE INDEX IDX_LEASE_ASSET_STATUS ON TBL_LEASE_ASSET(STATUS);

