-- 退租记录表
-- 执行时间: 2026-02-09
-- 说明: 创建退租记录表，用于管理融资租赁的退租信息

CREATE TABLE TBL_LEASE_RETURN (
    RETURN_ID NUMBER(19) PRIMARY KEY,
    LEASE_ID NUMBER(19) NOT NULL,
    RETURN_DATE DATE,
    RETURN_TYPE VARCHAR2(50),
    RETURN_REASON VARCHAR2(500),
    SETTLEMENT_AMOUNT NUMBER(20,2),
    PENALTY_AMOUNT NUMBER(20,2),
    REFUND_AMOUNT NUMBER(20,2),
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    REMARK VARCHAR2(500),
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE,
    CONSTRAINT FK_LEASE_RETURN_LEASE FOREIGN KEY (LEASE_ID) REFERENCES TBL_FINANCIAL_LEASE(LEASE_ID)
);

COMMENT ON TABLE TBL_LEASE_RETURN IS '退租记录表';
COMMENT ON COLUMN TBL_LEASE_RETURN.RETURN_ID IS '退租ID';
COMMENT ON COLUMN TBL_LEASE_RETURN.LEASE_ID IS '租赁ID';
COMMENT ON COLUMN TBL_LEASE_RETURN.RETURN_DATE IS '退租日期';
COMMENT ON COLUMN TBL_LEASE_RETURN.RETURN_TYPE IS '退租类型(NORMAL-正常退租/EARLY-提前退租/BREACH-违约退租)';
COMMENT ON COLUMN TBL_LEASE_RETURN.RETURN_REASON IS '退租原因';
COMMENT ON COLUMN TBL_LEASE_RETURN.SETTLEMENT_AMOUNT IS '结算金额';
COMMENT ON COLUMN TBL_LEASE_RETURN.PENALTY_AMOUNT IS '违约金';
COMMENT ON COLUMN TBL_LEASE_RETURN.REFUND_AMOUNT IS '退款金额';
COMMENT ON COLUMN TBL_LEASE_RETURN.STATUS IS '状态(PENDING-待处理/PROCESSING-处理中/COMPLETED-已完成)';

-- 创建索引
CREATE INDEX IDX_LEASE_RETURN_LEASE_ID ON TBL_LEASE_RETURN(LEASE_ID);
CREATE INDEX IDX_LEASE_RETURN_STATUS ON TBL_LEASE_RETURN(STATUS);

