-- =============================================
-- 融资管理扩展表建表脚本
-- 数据库：达梦数据库 (DM8)
-- 版本：v1.0
-- 创建日期：2026-01-13
-- 说明：创建5个扩展表，保留原表结构，通过外键关联
-- =============================================

-- =============================================
-- 表1: TBL_FINANCING_APPLICATION_EXT
-- 用途：融资申请扩展表（扩展TBL_FINANCING_PLAN）
-- =============================================
CREATE TABLE TBL_FINANCING_APPLICATION_EXT (
    EXT_ID NUMBER(20) NOT NULL,
    PLAN_ID NUMBER(20) NOT NULL,
    APPLICATION_NO VARCHAR2(50) NOT NULL,
    APPLICANT_NAME VARCHAR2(100),
    APPLICANT_DEPT VARCHAR2(200),
    GUARANTEE_TYPE VARCHAR2(50),
    GUARANTEE_AMOUNT DECIMAL(20,2),
    PLEDGE_ASSETS VARCHAR2(500),
    CREDIT_RATING VARCHAR2(20),
    RISK_LEVEL VARCHAR2(20),
    APPROVAL_WORKFLOW_ID NUMBER(20),
    ATTACHMENT_URL VARCHAR2(500),
    REMARK VARCHAR2(1000),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER NUMBER(20),
    UPDATE_USER NUMBER(20),
    ORG_ID NUMBER(20) NOT NULL,
    DELETE_FLAG INTEGER DEFAULT 0,
    CONSTRAINT PK_FINANCING_APP_EXT PRIMARY KEY (EXT_ID)
);

-- 添加表注释
COMMENT ON TABLE TBL_FINANCING_APPLICATION_EXT IS '融资申请扩展表';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.EXT_ID IS '扩展ID';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.PLAN_ID IS '关联融资计划ID';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.APPLICATION_NO IS '申请编号';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.APPLICANT_NAME IS '申请人姓名';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.APPLICANT_DEPT IS '申请部门';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.GUARANTEE_TYPE IS '担保方式：CREDIT-信用/MORTGAGE-抵押/PLEDGE-质押/GUARANTEE-保证';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.GUARANTEE_AMOUNT IS '担保金额';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.PLEDGE_ASSETS IS '质押资产描述';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.CREDIT_RATING IS '信用评级：AAA/AA/A/BBB/BB/B/CCC';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.RISK_LEVEL IS '风险等级：HIGH-高/MEDIUM-中/LOW-低';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.APPROVAL_WORKFLOW_ID IS '审批工作流ID';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.ATTACHMENT_URL IS '附件URL';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.REMARK IS '备注';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.CREATE_USER IS '创建人ID';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.UPDATE_USER IS '更新人ID';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.ORG_ID IS '组织机构ID';
COMMENT ON COLUMN TBL_FINANCING_APPLICATION_EXT.DELETE_FLAG IS '删除标志：0-正常/1-已删除';

-- 创建索引
CREATE INDEX IDX_APP_EXT_PLAN_ID ON TBL_FINANCING_APPLICATION_EXT(PLAN_ID);
CREATE INDEX IDX_APP_EXT_NO ON TBL_FINANCING_APPLICATION_EXT(APPLICATION_NO);
CREATE INDEX IDX_APP_EXT_ORG_ID ON TBL_FINANCING_APPLICATION_EXT(ORG_ID);
CREATE INDEX IDX_APP_EXT_STATUS ON TBL_FINANCING_APPLICATION_EXT(DELETE_FLAG);

-- 创建唯一索引（同一计划只能有一条扩展记录）
CREATE UNIQUE INDEX UK_APP_EXT_PLAN_ID ON TBL_FINANCING_APPLICATION_EXT(PLAN_ID) WHERE DELETE_FLAG = 0;

-- =============================================
-- 表2: TBL_BANK_LOAN_EXT
-- 用途：银行贷款扩展表
-- =============================================
CREATE TABLE TBL_BANK_LOAN_EXT (
    EXT_ID NUMBER(20) NOT NULL,
    LOAN_ID NUMBER(20),
    APPLICATION_ID NUMBER(20) NOT NULL,
    BANK_CODE VARCHAR2(20) NOT NULL,
    BANK_NAME VARCHAR2(200) NOT NULL,
    BANK_BRANCH VARCHAR2(200),
    ACCOUNT_NUMBER VARCHAR2(50),
    GUARANTEE_TYPE VARCHAR2(50),
    GUARANTOR VARCHAR2(200),
    LOAN_CONTRACT_NO VARCHAR2(100),
    DRAWDOWN_DATE DATE,
    INTEREST_PAYMENT_METHOD VARCHAR2(50),
    PREPAYMENT_PENALTY_RATE DECIMAL(10,4),
    LOAN_OFFICER VARCHAR2(100),
    LOAN_OFFICER_PHONE VARCHAR2(20),
    ATTACHMENT_URL VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER NUMBER(20),
    UPDATE_USER NUMBER(20),
    ORG_ID NUMBER(20) NOT NULL,
    DELETE_FLAG INTEGER DEFAULT 0,
    CONSTRAINT PK_BANK_LOAN_EXT PRIMARY KEY (EXT_ID)
);

-- 添加表注释
COMMENT ON TABLE TBL_BANK_LOAN_EXT IS '银行贷款扩展表';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.EXT_ID IS '扩展ID';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.LOAN_ID IS '关联TBL_BANK_LOAN表的LOAN_ID';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.APPLICATION_ID IS '融资申请ID';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.BANK_CODE IS '银行编码';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.BANK_NAME IS '银行名称';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.BANK_BRANCH IS '银行分行';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.ACCOUNT_NUMBER IS '贷款账号';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.GUARANTEE_TYPE IS '担保方式：CREDIT-信用/MORTGAGE-抵押/PLEDGE-质押/GUARANTEE-保证';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.GUARANTOR IS '担保人';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.LOAN_CONTRACT_NO IS '贷款合同号';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.DRAWDOWN_DATE IS '放款日期';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.INTEREST_PAYMENT_METHOD IS '利息支付方式';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.PREPAYMENT_PENALTY_RATE IS '提前还款罚息率';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.LOAN_OFFICER IS '信贷经理';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.LOAN_OFFICER_PHONE IS '信贷经理电话';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.ATTACHMENT_URL IS '附件URL';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.CREATE_USER IS '创建人ID';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.UPDATE_USER IS '更新人ID';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.ORG_ID IS '组织机构ID';
COMMENT ON COLUMN TBL_BANK_LOAN_EXT.DELETE_FLAG IS '删除标志：0-正常/1-已删除';

-- 创建索引
CREATE INDEX IDX_BANK_LOAN_APP ON TBL_BANK_LOAN_EXT(APPLICATION_ID);
CREATE INDEX IDX_BANK_LOAN_BANK ON TBL_BANK_LOAN_EXT(BANK_CODE);
CREATE INDEX IDX_BANK_LOAN_ORG ON TBL_BANK_LOAN_EXT(ORG_ID);
CREATE INDEX IDX_BANK_LOAN_CONTRACT ON TBL_BANK_LOAN_EXT(LOAN_CONTRACT_NO);

-- =============================================
-- 表3: TBL_FINANCIAL_LEASE_EXT
-- 用途：融资租赁扩展表
-- =============================================
CREATE TABLE TBL_FINANCIAL_LEASE_EXT (
    EXT_ID NUMBER(20) NOT NULL,
    LEASE_ID NUMBER(20),
    APPLICATION_ID NUMBER(20) NOT NULL,
    LEASING_COMPANY VARCHAR2(200) NOT NULL,
    LEASING_TYPE VARCHAR2(50),
    ASSET_TYPE VARCHAR2(100),
    ASSET_DESCRIPTION VARCHAR2(500),
    ASSET_VALUE DECIMAL(20,2),
    LEASE_AMOUNT DECIMAL(20,2),
    RESIDUAL_VALUE_RATE DECIMAL(10,4),
    RESIDUAL_VALUE DECIMAL(20,2),
    SECURITY_DEPOSIT DECIMAL(20,2),
    LEASE_CONTRACT_NO VARCHAR2(100),
    DELIVERY_DATE DATE,
    LEASE_START_DATE DATE,
    LEASE_END_DATE DATE,
    MAINTENANCE_RESPONSIBILITY VARCHAR2(100),
    ATTACHMENT_URL VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER NUMBER(20),
    UPDATE_USER NUMBER(20),
    ORG_ID NUMBER(20) NOT NULL,
    DELETE_FLAG INTEGER DEFAULT 0,
    CONSTRAINT PK_FINANCIAL_LEASE_EXT PRIMARY KEY (EXT_ID)
);

-- 添加表注释
COMMENT ON TABLE TBL_FINANCIAL_LEASE_EXT IS '融资租赁扩展表';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.EXT_ID IS '扩展ID';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.LEASE_ID IS '关联TBL_FINANCIAL_LEASE表的LEASE_ID';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.APPLICATION_ID IS '融资申请ID';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.LEASING_COMPANY IS '租赁公司';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.LEASING_TYPE IS '租赁类型：FINANCE_LEASE-直租/SALE_LEASEBACK-回租/OPERATING_LEASE-经营租赁';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.ASSET_TYPE IS '资产类型';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.ASSET_DESCRIPTION IS '资产描述';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.ASSET_VALUE IS '资产价值';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.LEASE_AMOUNT IS '租赁金额';
COMMENT ON COLUMN TBL_FINANCING_LEASE_EXT.RESIDUAL_VALUE_RATE IS '残值率（百分比）';
COMMENT ON COLUMN TBL_FINANCING_LEASE_EXT.RESIDUAL_VALUE IS '残值';
COMMENT ON COLUMN TBL_FINANCING_LEASE_EXT.SECURITY_DEPOSIT IS '保证金';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.LEASE_CONTRACT_NO IS '租赁合同号';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.DELIVERY_DATE IS '资产交付日期';
COMMENT ON COLUMN TBL_FINANCING_LEASE_EXT.LEASE_START_DATE IS '租赁开始日期';
COMMENT ON COLUMN TBL_FINANCING_LEASE_EXT.LEASE_END_DATE IS '租赁结束日期';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.MAINTENANCE_RESPONSIBILITY IS '维护责任方';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.ATTACHMENT_URL IS '附件URL';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.CREATE_USER IS '创建人ID';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.UPDATE_USER IS '更新人ID';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.ORG_ID IS '组织机构ID';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE_EXT.DELETE_FLAG IS '删除标志：0-正常/1-已删除';

-- 创建索引
CREATE INDEX IDX_LEASE_APP ON TBL_FINANCIAL_LEASE_EXT(APPLICATION_ID);
CREATE INDEX IDX_LEASE_COMPANY ON TBL_FINANCIAL_LEASE_EXT(LEASING_COMPANY);
CREATE INDEX IDX_LEASE_CONTRACT ON TBL_FINANCIAL_LEASE_EXT(LEASE_CONTRACT_NO);
CREATE INDEX IDX_LEASE_ORG ON TBL_FINANCIAL_LEASE_EXT(ORG_ID);

-- =============================================
-- 表4: TBL_BOND_ISSUANCE_EXT
-- 用途：债券发行扩展表
-- =============================================
CREATE TABLE TBL_BOND_ISSUANCE_EXT (
    EXT_ID NUMBER(20) NOT NULL,
    ISSUANCE_ID NUMBER(20),
    APPLICATION_ID NUMBER(20) NOT NULL,
    BOND_CODE VARCHAR2(20),
    BOND_NAME VARCHAR2(200) NOT NULL,
    BOND_TYPE VARCHAR2(50),
    ISSUANCE_AMOUNT DECIMAL(20,2),
    FACE_VALUE DECIMAL(20,2),
    COUPON_RATE DECIMAL(10,4),
    BOND_TERM INTEGER,
    PAYMENT_FREQUENCY VARCHAR2(20),
    CREDIT_RATING VARCHAR2(20),
    UNDERWRITER VARCHAR2(200),
    ISSUE_DATE DATE,
    MATURITY_DATE DATE,
    INTEREST_PAYMENT_METHOD VARCHAR2(50),
    ATTACHMENT_URL VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER NUMBER(20),
    UPDATE_USER NUMBER(20),
    ORG_ID NUMBER(20) NOT NULL,
    DELETE_FLAG INTEGER DEFAULT 0,
    CONSTRAINT PK_BOND_ISSUANCE_EXT PRIMARY KEY (EXT_ID)
);

-- 添加表注释
COMMENT ON TABLE TBL_BOND_ISSUANCE_EXT IS '债券发行扩展表';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.EXT_ID IS '扩展ID';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.ISSUANCE_ID IS '关联TBL_BOND_ISSUANCE表的ISSUANCE_ID';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.APPLICATION_ID IS '融资申请ID';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.BOND_CODE IS '债券代码';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.BOND_NAME IS '债券名称';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.BOND_TYPE IS '债券类型：CORPORATE_BOND-企业债/COMPANY_BOND-公司债/MEDIUM_TERM_NOTE-中期票据';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.ISSUANCE_AMOUNT IS '发行金额';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.FACE_VALUE IS '面值';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.COUPON_RATE IS '票面利率（百分比）';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.BOND_TERM IS '债券期限（月）';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.PAYMENT_FREQUENCY IS '付息频率：ANNUAL-年付/SEMI_ANNUAL-半年付/QUARTERLY-季度付';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.CREDIT_RATING IS '信用评级';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.UNDERWRITER IS '承销商';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.ISSUE_DATE IS '发行日期';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.MATURITY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.INTEREST_PAYMENT_METHOD IS '利息支付方式';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.ATTACHMENT_URL IS '附件URL';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.CREATE_USER IS '创建人ID';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.UPDATE_USER IS '更新人ID';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.ORG_ID IS '组织机构ID';
COMMENT ON COLUMN TBL_BOND_ISSUANCE_EXT.DELETE_FLAG IS '删除标志：0-正常/1-已删除';

-- 创建索引
CREATE INDEX IDX_BOND_APP ON TBL_BOND_ISSUANCE_EXT(APPLICATION_ID);
CREATE INDEX IDX_BOND_CODE ON TBL_BOND_ISSUANCE_EXT(BOND_CODE);
CREATE INDEX IDX_BOND_TYPE ON TBL_BOND_ISSUANCE_EXT(BOND_TYPE);
CREATE INDEX IDX_BOND_ORG ON TBL_BOND_ISSUANCE_EXT(ORG_ID);

-- =============================================
-- 表5: TBL_FINANCING_REPAYMENT_SCHEDULE
-- 用途：融资还款计划表
-- =============================================
CREATE TABLE TBL_FINANCING_REPAYMENT_SCHEDULE (
    SCHEDULE_ID NUMBER(20) NOT NULL,
    REPAYMENT_NO VARCHAR2(50) NOT NULL,
    FINANCING_ID NUMBER(20) NOT NULL,
    FINANCING_TYPE VARCHAR2(20),
    PERIOD_NUMBER INTEGER NOT NULL,
    PRINCIPAL_AMOUNT DECIMAL(20,2),
    INTEREST_AMOUNT DECIMAL(20,2),
    TOTAL_AMOUNT DECIMAL(20,2),
    DUE_DATE DATE NOT NULL,
    ACTUAL_REPAYMENT_DATE DATE,
    REPAID_PRINCIPAL DECIMAL(20,2) DEFAULT 0,
    REPAID_INTEREST DECIMAL(20,2) DEFAULT 0,
    PENALTY_AMOUNT DECIMAL(20,2) DEFAULT 0,
    REPAYMENT_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    OVERDUE_DAYS INTEGER DEFAULT 0,
    PAYMENT_ACCOUNT VARCHAR2(100),
    REMARK VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER NUMBER(20),
    UPDATE_USER NUMBER(20),
    ORG_ID NUMBER(20) NOT NULL,
    DELETE_FLAG INTEGER DEFAULT 0,
    CONSTRAINT PK_REPAYMENT_SCHEDULE PRIMARY KEY (SCHEDULE_ID)
);

-- 添加表注释
COMMENT ON TABLE TBL_FINANCING_REPAYMENT_SCHEDULE IS '融资还款计划表';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.SCHEDULE_ID IS '还款计划ID';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REPAYMENT_NO IS '还款编号';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.FINANCING_ID IS '融资ID（关联到LOAN_ID/LEASE_ID/ISSUANCE_ID）';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.FINANCING_TYPE IS '融资类型：LOAN-贷款/BOND-债券/LEASE-租赁';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.PERIOD_NUMBER IS '期数（第几期）';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.PRINCIPAL_AMOUNT IS '应还本金';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.INTEREST_AMOUNT IS '应还利息';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.TOTAL_AMOUNT IS '应还总额';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.DUE_DATE IS '应还日期';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.ACTUAL_REPAYMENT_DATE IS '实际还款日期';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REPAID_PRINCIPAL IS '已还本金';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REPAID_INTEREST IS '已还利息';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.PENALTY_AMOUNT IS '罚息金额';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REPAYMENT_STATUS IS '还款状态：PENDING-待还/PAID-已还/PARTIAL-部分还款/OVERDUE-逾期';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.OVERDUE_DAYS IS '逾期天数';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.PAYMENT_ACCOUNT IS '还款账户';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REMARK IS '备注';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.CREATE_USER IS '创建人ID';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.UPDATE_USER IS '更新人ID';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.ORG_ID IS '组织机构ID';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.DELETE_FLAG IS '删除标志：0-正常/1-已删除';

-- 创建索引
CREATE INDEX IDX_REPAY_SCHED_FIN ON TBL_FINANCING_REPAYMENT_SCHEDULE(FINANCING_ID);
CREATE INDEX IDX_REPAY_SCHED_DUE ON TBL_FINANCING_REPAYMENT_SCHEDULE(DUE_DATE);
CREATE INDEX IDX_REPAY_SCHED_STATUS ON TBL_FINANCING_REPAYMENT_SCHEDULE(REPAYMENT_STATUS);
CREATE INDEX IDX_REPAY_SCHED_TYPE ON TBL_FINANCING_REPAYMENT_SCHEDULE(FINANCING_TYPE);
CREATE INDEX IDX_REPAY_SCHED_ORG ON TBL_FINANCING_REPAYMENT_SCHEDULE(ORG_ID);

-- 创建唯一索引（同一融资的同一期只能有一条记录）
CREATE UNIQUE INDEX UK_REPAY_SCHED_PERIOD ON TBL_FINANCING_REPAYMENT_SCHEDULE(FINANCING_ID, PERIOD_NUMBER) WHERE DELETE_FLAG = 0;

-- =============================================
-- 创建序列（用于生成主键ID）
-- =============================================

-- 序列1: TBL_FINANCING_APPLICATION_EXT
CREATE SEQUENCE SEQ_FINANCING_APP_EXT
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

-- 序列2: TBL_BANK_LOAN_EXT
CREATE SEQUENCE SEQ_BANK_LOAN_EXT
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

-- 序列3: TBL_FINANCIAL_LEASE_EXT
CREATE SEQUENCE SEQ_FINANCIAL_LEASE_EXT
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

-- 序列4: TBL_BOND_ISSUANCE_EXT
CREATE SEQUENCE SEQ_BOND_ISSUANCE_EXT
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

-- 序列5: TBL_FINANCING_REPAYMENT_SCHEDULE
CREATE SEQUENCE SEQ_FINANCING_REPAYMENT
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

-- =============================================
-- 脚本执行完成
-- =============================================
-- 说明：
-- 1. 本脚本创建了5个扩展表，保留了原表结构
-- 2. 通过外键关联主表，确保数据一致性
-- 3. 使用达梦数据库兼容的语法
-- 4. 包含完整的索引和注释
-- 5. 支持软删除（DELETE_FLAG字段）
-- =============================================
