-- =====================================================
-- 票据到期管理测试数据初始化脚本 (达梦数据库版本)
-- 表名: REDACTED.TBL_BILL_MATURITY
-- 创建时间: 2026-02-03
-- 说明: 用于初始化票据到期管理页面的测试数据
-- =====================================================

-- 清空现有数据（可选，生产环境请谨慎使用）
-- DELETE FROM REDACTED.TBL_BILL_MATURITY WHERE DELETE_FLAG = 0;

-- 插入测试数据 - 即将到期的票据（30天内）
INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, COMPANY_ID, DEPT_ID,
    CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (1, 1001, 'BA2026020301001', 'BANK_ACCEPTANCE', 500000.00,
    '华博科技有限公司', '中国工商银行深圳分行', SYSDATE - 150, SYSDATE + 10, 10,
    'EXPIRING', 'NOT_SENT', NULL, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP, 0);

INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, COMPANY_ID, DEPT_ID,
    CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (2, 1002, 'BA2026020301002', 'BANK_ACCEPTANCE', 800000.00,
    '广州贸易集团', '中国建设银行广州分行', SYSDATE - 160, SYSDATE + 20, 20,
    'EXPIRING', 'SENT', NULL, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP, 0);

INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, COMPANY_ID, DEPT_ID,
    CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (3, 1003, 'CA2026020301003', 'COMMERCIAL_ACCEPTANCE', 350000.00,
    '上海投资控股', '浙江民营企业集团', SYSDATE - 170, SYSDATE + 5, 5,
    'EXPIRING', 'NOT_SENT', NULL, 1, 2, SYSTIMESTAMP, SYSTIMESTAMP, 0);

-- 已到期未处理的票据
INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, COMPANY_ID, DEPT_ID,
    CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (4, 1004, 'BA2026020301004', 'BANK_ACCEPTANCE', 1200000.00,
    '北京科技发展', '中国银行北京分行', SYSDATE - 185, SYSDATE - 5, -5,
    'MATURED', 'SENT', NULL, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP, 0);

INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, COMPANY_ID, DEPT_ID,
    CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (5, 1005, 'CA2026020301005', 'COMMERCIAL_ACCEPTANCE', 450000.00,
    '成都商贸有限公司', '四川民营企业', SYSDATE - 190, SYSDATE - 10, -10,
    'MATURED', 'NOT_SENT', NULL, 1, 2, SYSTIMESTAMP, SYSTIMESTAMP, 0);

-- 未到期的票据（30天以上）
INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, COMPANY_ID, DEPT_ID,
    CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (6, 1006, 'BA2026020301006', 'BANK_ACCEPTANCE', 2000000.00,
    '武汉钢铁集团', '中国农业银行武汉分行', SYSDATE - 120, SYSDATE + 60, 60,
    'NOT_MATURED', 'NOT_SENT', NULL, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP, 0);

INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, COMPANY_ID, DEPT_ID,
    CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (7, 1007, 'BA2026020301007', 'BANK_ACCEPTANCE', 1500000.00,
    '南京电子科技', '交通银行南京分行', SYSDATE - 100, SYSDATE + 80, 80,
    'NOT_MATURED', 'NOT_SENT', NULL, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP, 0);

INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, COMPANY_ID, DEPT_ID,
    CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (8, 1008, 'CK2026020301008', 'CHECK', 100000.00,
    '西安贸易公司', '招商银行西安分行', SYSDATE - 10, SYSDATE + 25, 25,
    'EXPIRING', 'NOT_SENT', NULL, 1, 3, SYSTIMESTAMP, SYSTIMESTAMP, 0);

-- 已处理的票据
INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, PROCESS_DATE, PROCESS_DESCRIPTION,
    COMPANY_ID, DEPT_ID, CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (9, 1009, 'BA2026020301009', 'BANK_ACCEPTANCE', 600000.00,
    '厦门进出口', '中国工商银行厦门分行', SYSDATE - 200, SYSDATE - 20, -20,
    'PROCESSED', 'SENT', 'COLLECT', SYSDATE - 18, '已完成托收处理',
    1, 1, SYSTIMESTAMP, SYSTIMESTAMP, 0);

INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, PROCESS_DATE, PROCESS_DESCRIPTION,
    COMPANY_ID, DEPT_ID, CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (10, 1010, 'CA2026020301010', 'COMMERCIAL_ACCEPTANCE', 280000.00,
    '济南化工集团', '山东民营企业', SYSDATE - 195, SYSDATE - 15, -15,
    'PROCESSED', 'SENT', 'EXTEND', SYSDATE - 14, '已延期30天处理',
    1, 2, SYSTIMESTAMP, SYSTIMESTAMP, 0);

-- 本票类型
INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, COMPANY_ID, DEPT_ID,
    CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (11, 1011, 'PN2026020301011', 'PROMISSORY_NOTE', 200000.00,
    '郑州商贸有限公司', NULL, SYSDATE - 80, SYSDATE + 100, 100,
    'NOT_MATURED', 'NOT_SENT', NULL, 1, 3, SYSTIMESTAMP, SYSTIMESTAMP, 0);

INSERT INTO REDACTED.TBL_BILL_MATURITY (
    MATURITY_ID, BILL_ID, BILL_NUMBER, BILL_TYPE, BILL_AMOUNT,
    DRAWER_NAME, ACCEPTOR_NAME, ISSUE_DATE, MATURITY_DATE, REMAINING_DAYS,
    MATURITY_STATUS, REMINDER_STATUS, PROCESS_TYPE, COMPANY_ID, DEPT_ID,
    CREATE_TIME, UPDATE_TIME, DELETE_FLAG
) VALUES (12, 1012, 'PN2026020301012', 'PROMISSORY_NOTE', 150000.00,
    '合肥科技园区', NULL, SYSDATE - 140, SYSDATE + 40, 40,
    'NOT_MATURED', 'NOT_SENT', NULL, 1, 3, SYSTIMESTAMP, SYSTIMESTAMP, 0);

COMMIT;

-- 验证插入结果
SELECT COUNT(*) AS TOTAL_RECORDS FROM REDACTED.TBL_BILL_MATURITY WHERE DELETE_FLAG = 0;

-- 查看统计数据
SELECT
    COUNT(*) AS "totalBills",
    SUM(CASE WHEN REMAINING_DAYS BETWEEN 0 AND 30 THEN 1 ELSE 0 END) AS "expiringBills",
    SUM(CASE WHEN REMAINING_DAYS < 0 AND MATURITY_STATUS != 'PROCESSED' THEN 1 ELSE 0 END) AS "maturedBills",
    COALESCE(SUM(CASE WHEN REMAINING_DAYS <= 30 THEN BILL_AMOUNT ELSE 0 END) / 10000, 0) AS "totalAmount"
FROM REDACTED.TBL_BILL_MATURITY
WHERE DELETE_FLAG = 0;

