-- ===================================================================
-- 数据源配置表测试数据（安全版本 - 只使用确定存在的字段）
-- 达梦数据库(DM8)
-- 创建时间: 2026-01-30
-- 说明: 只使用CREATE TABLE语句中明确列出的字段
-- ===================================================================

-- 先清空旧数据
DELETE FROM TC_DATA_SOURCE_CONFIG;
COMMIT;

-- 插入测试数据1: 生产环境MySQL主数据库
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_CONFIG, SYNC_FREQUENCY, SYNC_STATUS,
    ERROR_COUNT, MAX_ERROR_COUNT, TIMEOUT_SECONDS, RETRY_COUNT,
    IS_ACTIVE, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130001', 'MYSQL_MAIN_PROD', '生产环境MySQL主数据库', 'MYSQL', 'DATABASE',
    '{"host":"192.0.2.200","port":3306,"database":"hbyun_treasury"}', 'DAILY', 'SUCCESS',
    0, 3, 30, 3, '1', '1', '主数据库，每日全量备份', SYSDATE, SYSDATE, 'system', 'system', 1
);

-- 插入测试数据2: 备份环境达梦数据库
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_CONFIG, SYNC_FREQUENCY, SYNC_STATUS,
    ERROR_COUNT, MAX_ERROR_COUNT, TIMEOUT_SECONDS, RETRY_COUNT,
    IS_ACTIVE, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130002', 'DM_BACKUP_PROD', '生产环境达梦备份数据库', 'DAMENG', 'DATABASE',
    '{"host":"192.0.2.200","port":5236,"database":"HBYUN_BACKUP"}', 'WEEKLY', 'SUCCESS',
    0, 5, 60, 5, '1', '1', '用于数据备份和恢复', SYSDATE, SYSDATE, 'system', 'system', 1
);

-- 插入测试数据3: 银行接口API
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    API_CONFIG, SYNC_FREQUENCY, SYNC_STATUS,
    ERROR_COUNT, MAX_ERROR_COUNT, TIMEOUT_SECONDS, RETRY_COUNT,
    IS_ACTIVE, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130003', 'BANK_API_ICBC', '工商银行接口API', 'API', 'API',
    '{"apiKey":"xxx","secret":"REDACTED","version":"1.0"}', 'REALTIME', 'FAILED',
    5, 3, 10, 1, '0', '1', '暂时不可用，等待银行修复', SYSDATE, SYSDATE, 'system', 'system', 1
);

-- 插入测试数据4: Redis缓存服务
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_CONFIG, SYNC_FREQUENCY, SYNC_STATUS,
    ERROR_COUNT, MAX_ERROR_COUNT, TIMEOUT_SECONDS, RETRY_COUNT,
    IS_ACTIVE, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130004', 'REDIS_CACHE_MAIN', 'Redis缓存主服务', 'REDIS', 'CACHE',
    '{"host":"192.0.2.200","port":6379,"database":0}', 'HOURLY', 'SUCCESS',
    0, 3, 5, 2, '1', '1', 'Redis缓存服务，用于缓存热点数据', SYSDATE, SYSDATE, 'system', 'system', 1
);

-- 插入测试数据5: 测试环境PostgreSQL
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_CONFIG, SYNC_FREQUENCY, SYNC_STATUS,
    ERROR_COUNT, MAX_ERROR_COUNT, TIMEOUT_SECONDS, RETRY_COUNT,
    IS_ACTIVE, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130005', 'POSTGRESQL_TEST', '测试环境PostgreSQL数据库', 'POSTGRESQL', 'DATABASE',
    '{"host":"192.0.2.200","port":5432,"database":"hbyun_test"}', 'DAILY', 'SUCCESS',
    0, 3, 30, 3, '1', '1', '用于开发和测试', SYSDATE, SYSDATE, 'system', 'system', 1
);

-- 插入测试数据6: ERP系统Oracle数据库
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_CONFIG, SYNC_FREQUENCY, SYNC_STATUS,
    ERROR_COUNT, MAX_ERROR_COUNT, TIMEOUT_SECONDS, RETRY_COUNT,
    IS_ACTIVE, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130006', 'ORACLE_ERP_PROD', 'ERP系统Oracle数据库', 'ORACLE', 'DATABASE',
    '{"host":"192.0.2.200","port":1521,"sid":"ERPPROD"}', 'WEEKLY', 'PENDING',
    0, 3, 60, 3, '1', '1', 'ERP系统数据同步源', SYSDATE, SYSDATE, 'system', 'system', 1
);

-- 插入测试数据7: 文件数据源接口
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_CONFIG, SYNC_FREQUENCY, SYNC_STATUS,
    ERROR_COUNT, MAX_ERROR_COUNT, TIMEOUT_SECONDS, RETRY_COUNT,
    IS_ACTIVE, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130007', 'FILE_INTERFACE_BANK', '银行对账文件接口', 'FILE', 'FILE',
    '{"path":"/data/interface/bank/statement/","pattern":"*.txt"}', 'DAILY', 'SUCCESS',
    0, 3, 120, 3, '1', '1', '每日凌晨2点自动处理', SYSDATE, SYSDATE, 'system', 'system', 1
);

-- 插入测试数据8: 开发环境MySQL
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_CONFIG, SYNC_FREQUENCY, SYNC_STATUS,
    ERROR_COUNT, MAX_ERROR_COUNT, TIMEOUT_SECONDS, RETRY_COUNT,
    IS_ACTIVE, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130008', 'MYSQL_DEV_LOCAL', '开发环境本地MySQL', 'MYSQL', 'DATABASE',
    '{"host":"localhost","port":3306,"database":"hbyun_dev"}', 'REALTIME', 'SUCCESS',
    0, 3, 10, 1, '1', '1', '开发人员本地测试环境', SYSDATE, SYSDATE, 'system', 'system', 1
);

-- 插入测试数据9: 数据仓库大数据平台
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_CONFIG, SYNC_FREQUENCY, SYNC_STATUS,
    ERROR_COUNT, MAX_ERROR_COUNT, TIMEOUT_SECONDS, RETRY_COUNT,
    IS_ACTIVE, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130009', 'HIVE_DATA_WAREHOUSE', '数据仓库Hive集群', 'HIVE', 'DATABASE',
    '{"host":"192.0.2.200","port":10000,"database":"hbyun_warehouse"}', 'MONTHLY', 'SUCCESS',
    0, 5, 300, 5, '1', '1', '用于大数据分析和报表', SYSDATE, SYSDATE, 'system', 'system', 1
);

-- 插入测试数据10: 第三方支付接口
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    API_CONFIG, SYNC_FREQUENCY, SYNC_STATUS,
    ERROR_COUNT, MAX_ERROR_COUNT, TIMEOUT_SECONDS, RETRY_COUNT,
    IS_ACTIVE, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130010', 'ALIPAY_API', '支付宝支付接口', 'API', 'API',
    '{"appId":"xxx","privateKey":"xxx","publicKey":"xxx","format":"JSON"}', 'DAILY', 'SUCCESS',
    0, 3, 15, 3, '1', '1', '每日自动对账', SYSDATE, SYSDATE, 'system', 'system', 1
);

COMMIT;

-- 验证插入结果
SELECT
    ID AS "主键ID",
    SOURCE_CODE AS "数据源编码",
    SOURCE_NAME AS "数据源名称",
    SOURCE_TYPE AS "数据源类型",
    DATA_TYPE AS "数据类型",
    SYNC_STATUS AS "同步状态",
    IS_ACTIVE AS "是否激活",
    STATUS AS "状态",
    REMARK AS "备注",
    CREATE_TIME AS "创建时间"
FROM TC_DATA_SOURCE_CONFIG
ORDER BY CREATE_TIME DESC;

-- 统计插入的数据量
SELECT '数据源配置表测试数据插入完成，共插入 ' || COUNT(*) || ' 条记录' AS MESSAGE
FROM TC_DATA_SOURCE_CONFIG;
