-- =====================================================
-- 投资管理模块数据库表 - 达梦数据库兼容版本
-- 创建日期: 2025-01-04
-- 模块: 投资计划、银行理财投资、债券投资、投资监控
-- =====================================================

-- 1. 投资计划表 (TBL_INVESTMENT_PLAN)
CREATE TABLE IF NOT EXISTS TBL_INVESTMENT_PLAN (
    PLAN_ID BIGINT PRIMARY KEY,
    PLAN_NO VARCHAR(50) NOT NULL,
    PLAN_NAME VARCHAR(200) NOT NULL,
    PLAN_TYPE VARCHAR(50),
    INVESTMENT_TYPE VARCHAR(50),
    PLAN_AMOUNT DECIMAL(20,2),
    INVESTED_AMOUNT DECIMAL(20,2) DEFAULT 0,
    REMAINING_AMOUNT DECIMAL(20,2),
    EXPECTED_RETURN_RATE DECIMAL(10,6),
    ACTUAL_RETURN_RATE DECIMAL(10,6),
    RISK_LEVEL VARCHAR(20),
    PLAN_STATUS VARCHAR(20) DEFAULT 'DRAFT',
    PLAN_START_DATE DATE,
    PLAN_END_DATE DATE,
    PLAN_DESCRIPTION CLOB,
    APPROVAL_COMMENTS VARCHAR(500),
    REJECTION_REASON VARCHAR(500),
    COMPLETION_NOTES VARCHAR(500),
    CANCEL_REASON VARCHAR(500),
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP,
    DELETE_FLAG INT DEFAULT 0,
    REMARK VARCHAR(500)
);

-- 投资计划表索引
CREATE INDEX IF NOT EXISTS IDX_INVESTMENT_PLAN_NO ON TBL_INVESTMENT_PLAN(PLAN_NO);
CREATE INDEX IF NOT EXISTS IDX_INVESTMENT_PLAN_STATUS ON TBL_INVESTMENT_PLAN(PLAN_STATUS);
CREATE INDEX IF NOT EXISTS IDX_INVESTMENT_PLAN_TYPE ON TBL_INVESTMENT_PLAN(INVESTMENT_TYPE);
CREATE INDEX IF NOT EXISTS IDX_INVESTMENT_PLAN_COMPANY ON TBL_INVESTMENT_PLAN(COMPANY_ID);

-- 投资计划表注释
COMMENT ON TABLE TBL_INVESTMENT_PLAN IS '投资计划表';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_ID IS '计划ID';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_NO IS '计划编号';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_NAME IS '计划名称';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_TYPE IS '计划类型';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.INVESTMENT_TYPE IS '投资类型(BANK_WEALTH-银行理财,BOND-债券,EQUITY-股权,FUND-基金,DERIVATIVE-衍生品)';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_AMOUNT IS '计划金额';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.INVESTED_AMOUNT IS '已投资金额';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.REMAINING_AMOUNT IS '剩余金额';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.EXPECTED_RETURN_RATE IS '预期收益率';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.ACTUAL_RETURN_RATE IS '实际收益率';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.RISK_LEVEL IS '风险等级(LOW-低,MEDIUM-中,HIGH-高)';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_STATUS IS '计划状态(DRAFT-草稿,SUBMITTED-已提交,APPROVED-已审批,EXECUTING-执行中,COMPLETED-已完成,CANCELLED-已取消)';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_START_DATE IS '开始日期';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_END_DATE IS '结束日期';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_DESCRIPTION IS '计划描述';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.DELETE_FLAG IS '删除标志(0-正常,1-删除)';

-- 2. 银行理财投资表 (TBL_BANK_WEALTH_INVESTMENT)
CREATE TABLE IF NOT EXISTS TBL_BANK_WEALTH_INVESTMENT (
    INVESTMENT_ID BIGINT PRIMARY KEY,
    PLAN_ID BIGINT,
    PRODUCT_ID BIGINT,
    ACCOUNT_ID BIGINT,
    INVESTMENT_NO VARCHAR(50) NOT NULL,
    PRODUCT_CODE VARCHAR(50),
    PRODUCT_NAME VARCHAR(200),
    BANK_CODE VARCHAR(50),
    BANK_NAME VARCHAR(200),
    INVESTMENT_AMOUNT DECIMAL(20,2),
    CURRENT_VALUE DECIMAL(20,2),
    EXPECTED_RETURN DECIMAL(20,2),
    ACTUAL_RETURN DECIMAL(20,2),
    EXPECTED_RETURN_RATE DECIMAL(10,6),
    ACTUAL_RETURN_RATE DECIMAL(10,6),
    INVESTMENT_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    INVESTMENT_DATE DATE,
    MATURITY_DATE DATE,
    REDEEM_DATE DATE,
    REDEEM_AMOUNT DECIMAL(20,2),
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP,
    DELETE_FLAG INT DEFAULT 0,
    REMARK VARCHAR(500)
);

-- 银行理财投资表索引
CREATE INDEX IF NOT EXISTS IDX_BANK_WEALTH_INV_NO ON TBL_BANK_WEALTH_INVESTMENT(INVESTMENT_NO);
CREATE INDEX IF NOT EXISTS IDX_BANK_WEALTH_INV_STATUS ON TBL_BANK_WEALTH_INVESTMENT(INVESTMENT_STATUS);
CREATE INDEX IF NOT EXISTS IDX_BANK_WEALTH_INV_PLAN ON TBL_BANK_WEALTH_INVESTMENT(PLAN_ID);
CREATE INDEX IF NOT EXISTS IDX_BANK_WEALTH_INV_BANK ON TBL_BANK_WEALTH_INVESTMENT(BANK_CODE);

-- 银行理财投资表注释
COMMENT ON TABLE TBL_BANK_WEALTH_INVESTMENT IS '银行理财投资表';
COMMENT ON COLUMN TBL_BANK_WEALTH_INVESTMENT.INVESTMENT_ID IS '投资ID';
COMMENT ON COLUMN TBL_BANK_WEALTH_INVESTMENT.PLAN_ID IS '关联计划ID';
COMMENT ON COLUMN TBL_BANK_WEALTH_INVESTMENT.INVESTMENT_NO IS '投资编号';
COMMENT ON COLUMN TBL_BANK_WEALTH_INVESTMENT.PRODUCT_CODE IS '产品代码';
COMMENT ON COLUMN TBL_BANK_WEALTH_INVESTMENT.BANK_CODE IS '银行代码';
COMMENT ON COLUMN TBL_BANK_WEALTH_INVESTMENT.INVESTMENT_AMOUNT IS '投资金额';
COMMENT ON COLUMN TBL_BANK_WEALTH_INVESTMENT.CURRENT_VALUE IS '当前价值';
COMMENT ON COLUMN TBL_BANK_WEALTH_INVESTMENT.INVESTMENT_STATUS IS '投资状态(ACTIVE-活跃,MATURED-已到期,REDEEMED-已赎回,CANCELLED-已取消)';

-- 3. 债券投资表 (TBL_BOND_INVESTMENT)
CREATE TABLE IF NOT EXISTS TBL_BOND_INVESTMENT (
    INVESTMENT_ID BIGINT PRIMARY KEY,
    PLAN_ID BIGINT,
    INVESTMENT_NO VARCHAR(50) NOT NULL,
    BOND_CODE VARCHAR(50),
    BOND_NAME VARCHAR(200),
    BOND_TYPE VARCHAR(50),
    ISSUER VARCHAR(200),
    FACE_VALUE DECIMAL(20,2),
    PURCHASE_PRICE DECIMAL(20,6),
    PURCHASE_QUANTITY BIGINT,
    PURCHASE_AMOUNT DECIMAL(20,2),
    CURRENT_PRICE DECIMAL(20,6),
    CURRENT_VALUE DECIMAL(20,2),
    COUPON_RATE DECIMAL(10,6),
    YIELD_TO_MATURITY DECIMAL(10,6),
    ACCRUED_INTEREST DECIMAL(20,2),
    TOTAL_INTEREST_RECEIVED DECIMAL(20,2),
    INVESTMENT_STATUS VARCHAR(20) DEFAULT 'HOLDING',
    PURCHASE_DATE DATE,
    MATURITY_DATE DATE,
    SELL_DATE DATE,
    SELL_PRICE DECIMAL(20,6),
    SELL_AMOUNT DECIMAL(20,2),
    CREDIT_RATING VARCHAR(20),
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP,
    DELETE_FLAG INT DEFAULT 0,
    REMARK VARCHAR(500)
);

-- 债券投资表索引
CREATE INDEX IF NOT EXISTS IDX_BOND_INV_NO ON TBL_BOND_INVESTMENT(INVESTMENT_NO);
CREATE INDEX IF NOT EXISTS IDX_BOND_INV_CODE ON TBL_BOND_INVESTMENT(BOND_CODE);
CREATE INDEX IF NOT EXISTS IDX_BOND_INV_STATUS ON TBL_BOND_INVESTMENT(INVESTMENT_STATUS);
CREATE INDEX IF NOT EXISTS IDX_BOND_INV_PLAN ON TBL_BOND_INVESTMENT(PLAN_ID);
CREATE INDEX IF NOT EXISTS IDX_BOND_INV_TYPE ON TBL_BOND_INVESTMENT(BOND_TYPE);

-- 债券投资表注释
COMMENT ON TABLE TBL_BOND_INVESTMENT IS '债券投资表';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.INVESTMENT_ID IS '投资ID';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.PLAN_ID IS '关联计划ID';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.INVESTMENT_NO IS '投资编号';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.BOND_CODE IS '债券代码';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.BOND_NAME IS '债券名称';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.BOND_TYPE IS '债券类型(GOVERNMENT-国债,CORPORATE-企业债,FINANCIAL-金融债,LOCAL_GOV-地方政府债)';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.ISSUER IS '发行人';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.FACE_VALUE IS '面值';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.PURCHASE_PRICE IS '购买价格';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.PURCHASE_QUANTITY IS '购买数量';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.PURCHASE_AMOUNT IS '购买金额';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.CURRENT_PRICE IS '当前价格';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.CURRENT_VALUE IS '当前价值';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.COUPON_RATE IS '票面利率';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.YIELD_TO_MATURITY IS '到期收益率';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.ACCRUED_INTEREST IS '应计利息';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.INVESTMENT_STATUS IS '投资状态(HOLDING-持有中,SOLD-已卖出,MATURED-已到期)';

-- 4. 投资监控表 (TBL_INVESTMENT_MONITORING)
CREATE TABLE IF NOT EXISTS TBL_INVESTMENT_MONITORING (
    MONITORING_ID BIGINT PRIMARY KEY,
    INVESTMENT_ID BIGINT,
    INVESTMENT_TYPE VARCHAR(50),
    MONITORING_DATE DATE,
    MONITORING_TYPE VARCHAR(50),
    CURRENT_VALUE DECIMAL(20,2),
    PREVIOUS_VALUE DECIMAL(20,2),
    VALUE_CHANGE DECIMAL(20,2),
    VALUE_CHANGE_RATE DECIMAL(10,6),
    RISK_SCORE DECIMAL(10,2),
    RISK_LEVEL VARCHAR(20),
    ALERT_STATUS VARCHAR(20) DEFAULT 'NORMAL',
    ALERT_TYPE VARCHAR(50),
    ALERT_MESSAGE VARCHAR(500),
    ALERT_TIME TIMESTAMP,
    HANDLE_STATUS VARCHAR(20) DEFAULT 'PENDING',
    HANDLE_RESULT VARCHAR(500),
    HANDLE_TIME TIMESTAMP,
    HANDLER_ID BIGINT,
    HANDLER_NAME VARCHAR(100),
    COMPANY_ID BIGINT,
    COMPANY_NAME VARCHAR(200),
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_TIME TIMESTAMP,
    DELETE_FLAG INT DEFAULT 0,
    REMARK VARCHAR(500)
);

-- 投资监控表索引
CREATE INDEX IF NOT EXISTS IDX_INV_MONITOR_INV ON TBL_INVESTMENT_MONITORING(INVESTMENT_ID);
CREATE INDEX IF NOT EXISTS IDX_INV_MONITOR_TYPE ON TBL_INVESTMENT_MONITORING(INVESTMENT_TYPE);
CREATE INDEX IF NOT EXISTS IDX_INV_MONITOR_DATE ON TBL_INVESTMENT_MONITORING(MONITORING_DATE);
CREATE INDEX IF NOT EXISTS IDX_INV_MONITOR_ALERT ON TBL_INVESTMENT_MONITORING(ALERT_STATUS);

-- 投资监控表注释
COMMENT ON TABLE TBL_INVESTMENT_MONITORING IS '投资监控表';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.MONITORING_ID IS '监控ID';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.INVESTMENT_ID IS '投资ID';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.INVESTMENT_TYPE IS '投资类型(BANK_WEALTH-银行理财,BOND-债券)';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.MONITORING_DATE IS '监控日期';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.MONITORING_TYPE IS '监控类型(VALUE-价值监控,RISK-风险监控,RETURN-收益监控)';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.CURRENT_VALUE IS '当前价值';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.VALUE_CHANGE IS '价值变动';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.VALUE_CHANGE_RATE IS '价值变动率';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.RISK_SCORE IS '风险评分';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.RISK_LEVEL IS '风险等级(LOW-低,MEDIUM-中,HIGH-高,CRITICAL-严重)';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.ALERT_STATUS IS '预警状态(NORMAL-正常,WARNING-预警,ALERT-告警)';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.ALERT_TYPE IS '预警类型';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.HANDLE_STATUS IS '处理状态(PENDING-待处理,PROCESSING-处理中,COMPLETED-已完成,IGNORED-已忽略)';

-- =====================================================
-- 测试数据
-- =====================================================

-- 投资计划测试数据
INSERT INTO TBL_INVESTMENT_PLAN (PLAN_ID, PLAN_NO, PLAN_NAME, PLAN_TYPE, INVESTMENT_TYPE, PLAN_AMOUNT, INVESTED_AMOUNT, REMAINING_AMOUNT, EXPECTED_RETURN_RATE, RISK_LEVEL, PLAN_STATUS, PLAN_START_DATE, PLAN_END_DATE, PLAN_DESCRIPTION, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (1, 'IP202501001', '2025年度银行理财投资计划', '年度计划', 'BANK_WEALTH', 50000000.00, 30000000.00, 20000000.00, 0.045, 'LOW', 'EXECUTING', '2025-01-01', '2025-12-31', '2025年度银行理财产品投资计划，以稳健型产品为主', 1, '华博云科技有限公司', 1, '管理员', CURRENT_TIMESTAMP, 0);

INSERT INTO TBL_INVESTMENT_PLAN (PLAN_ID, PLAN_NO, PLAN_NAME, PLAN_TYPE, INVESTMENT_TYPE, PLAN_AMOUNT, INVESTED_AMOUNT, REMAINING_AMOUNT, EXPECTED_RETURN_RATE, RISK_LEVEL, PLAN_STATUS, PLAN_START_DATE, PLAN_END_DATE, PLAN_DESCRIPTION, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (2, 'IP202501002', '2025年度债券投资计划', '年度计划', 'BOND', 100000000.00, 60000000.00, 40000000.00, 0.038, 'LOW', 'EXECUTING', '2025-01-01', '2025-12-31', '2025年度债券投资计划，以国债和高等级企业债为主', 1, '华博云科技有限公司', 1, '管理员', CURRENT_TIMESTAMP, 0);

INSERT INTO TBL_INVESTMENT_PLAN (PLAN_ID, PLAN_NO, PLAN_NAME, PLAN_TYPE, INVESTMENT_TYPE, PLAN_AMOUNT, INVESTED_AMOUNT, REMAINING_AMOUNT, EXPECTED_RETURN_RATE, RISK_LEVEL, PLAN_STATUS, PLAN_START_DATE, PLAN_END_DATE, PLAN_DESCRIPTION, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (3, 'IP202501003', 'Q1短期理财计划', '季度计划', 'BANK_WEALTH', 20000000.00, 0, 20000000.00, 0.035, 'LOW', 'DRAFT', '2025-01-01', '2025-03-31', '第一季度短期理财计划', 1, '华博云科技有限公司', 1, '管理员', CURRENT_TIMESTAMP, 0);

-- 银行理财投资测试数据
INSERT INTO TBL_BANK_WEALTH_INVESTMENT (INVESTMENT_ID, PLAN_ID, INVESTMENT_NO, PRODUCT_CODE, PRODUCT_NAME, BANK_CODE, BANK_NAME, INVESTMENT_AMOUNT, CURRENT_VALUE, EXPECTED_RETURN, EXPECTED_RETURN_RATE, INVESTMENT_STATUS, INVESTMENT_DATE, MATURITY_DATE, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (1, 1, 'BWI202501001', 'ICBC-WM-001', '工银稳健理财A', 'ICBC', '中国工商银行', 10000000.00, 10150000.00, 450000.00, 0.045, 'ACTIVE', '2025-01-05', '2025-07-05', 1, '华博云科技有限公司', 1, '管理员', CURRENT_TIMESTAMP, 0);

INSERT INTO TBL_BANK_WEALTH_INVESTMENT (INVESTMENT_ID, PLAN_ID, INVESTMENT_NO, PRODUCT_CODE, PRODUCT_NAME, BANK_CODE, BANK_NAME, INVESTMENT_AMOUNT, CURRENT_VALUE, EXPECTED_RETURN, EXPECTED_RETURN_RATE, INVESTMENT_STATUS, INVESTMENT_DATE, MATURITY_DATE, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (2, 1, 'BWI202501002', 'CCB-WM-002', '建行增利宝', 'CCB', '中国建设银行', 15000000.00, 15200000.00, 600000.00, 0.04, 'ACTIVE', '2025-01-10', '2025-06-10', 1, '华博云科技有限公司', 1, '管理员', CURRENT_TIMESTAMP, 0);

INSERT INTO TBL_BANK_WEALTH_INVESTMENT (INVESTMENT_ID, PLAN_ID, INVESTMENT_NO, PRODUCT_CODE, PRODUCT_NAME, BANK_CODE, BANK_NAME, INVESTMENT_AMOUNT, CURRENT_VALUE, EXPECTED_RETURN, ACTUAL_RETURN, EXPECTED_RETURN_RATE, ACTUAL_RETURN_RATE, INVESTMENT_STATUS, INVESTMENT_DATE, MATURITY_DATE, REDEEM_DATE, REDEEM_AMOUNT, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (3, 1, 'BWI202412001', 'BOC-WM-001', '中银稳富', 'BOC', '中国银行', 5000000.00, 5180000.00, 175000.00, 180000.00, 0.035, 0.036, 'MATURED', '2024-07-01', '2024-12-31', '2024-12-31', 5180000.00, 1, '华博云科技有限公司', 1, '管理员', CURRENT_TIMESTAMP, 0);

-- 债券投资测试数据
INSERT INTO TBL_BOND_INVESTMENT (INVESTMENT_ID, PLAN_ID, INVESTMENT_NO, BOND_CODE, BOND_NAME, BOND_TYPE, ISSUER, FACE_VALUE, PURCHASE_PRICE, PURCHASE_QUANTITY, PURCHASE_AMOUNT, CURRENT_PRICE, CURRENT_VALUE, COUPON_RATE, YIELD_TO_MATURITY, ACCRUED_INTEREST, INVESTMENT_STATUS, PURCHASE_DATE, MATURITY_DATE, CREDIT_RATING, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (1, 2, 'BI202501001', '019666', '24国债01', 'GOVERNMENT', '财政部', 100.00, 99.50, 300000, 29850000.00, 100.20, 30060000.00, 0.028, 0.0275, 150000.00, 'HOLDING', '2025-01-08', '2027-01-08', 'AAA', 1, '华博云科技有限公司', 1, '管理员', CURRENT_TIMESTAMP, 0);

INSERT INTO TBL_BOND_INVESTMENT (INVESTMENT_ID, PLAN_ID, INVESTMENT_NO, BOND_CODE, BOND_NAME, BOND_TYPE, ISSUER, FACE_VALUE, PURCHASE_PRICE, PURCHASE_QUANTITY, PURCHASE_AMOUNT, CURRENT_PRICE, CURRENT_VALUE, COUPON_RATE, YIELD_TO_MATURITY, ACCRUED_INTEREST, INVESTMENT_STATUS, PURCHASE_DATE, MATURITY_DATE, CREDIT_RATING, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (2, 2, 'BI202501002', '2380001', '23华能集MTN001', 'CORPORATE', '华能集团', 100.00, 98.80, 200000, 19760000.00, 99.50, 19900000.00, 0.042, 0.0435, 80000.00, 'HOLDING', '2025-01-12', '2026-06-12', 'AAA', 1, '华博云科技有限公司', 1, '管理员', CURRENT_TIMESTAMP, 0);

INSERT INTO TBL_BOND_INVESTMENT (INVESTMENT_ID, PLAN_ID, INVESTMENT_NO, BOND_CODE, BOND_NAME, BOND_TYPE, ISSUER, FACE_VALUE, PURCHASE_PRICE, PURCHASE_QUANTITY, PURCHASE_AMOUNT, CURRENT_PRICE, CURRENT_VALUE, COUPON_RATE, YIELD_TO_MATURITY, ACCRUED_INTEREST, TOTAL_INTEREST_RECEIVED, INVESTMENT_STATUS, PURCHASE_DATE, MATURITY_DATE, SELL_DATE, SELL_PRICE, SELL_AMOUNT, CREDIT_RATING, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (3, 2, 'BI202406001', '019650', '23国债15', 'GOVERNMENT', '财政部', 100.00, 99.00, 100000, 9900000.00, 100.50, 10050000.00, 0.025, 0.024, 0, 250000.00, 'SOLD', '2024-06-01', '2026-06-01', '2024-12-15', 100.50, 10050000.00, 'AAA', 1, '华博云科技有限公司', 1, '管理员', CURRENT_TIMESTAMP, 0);

-- 投资监控测试数据
INSERT INTO TBL_INVESTMENT_MONITORING (MONITORING_ID, INVESTMENT_ID, INVESTMENT_TYPE, MONITORING_DATE, MONITORING_TYPE, CURRENT_VALUE, PREVIOUS_VALUE, VALUE_CHANGE, VALUE_CHANGE_RATE, RISK_SCORE, RISK_LEVEL, ALERT_STATUS, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (1, 1, 'BANK_WEALTH', '2025-01-04', 'VALUE', 10150000.00, 10100000.00, 50000.00, 0.00495, 25.00, 'LOW', 'NORMAL', 1, '华博云科技有限公司', 1, '系统', CURRENT_TIMESTAMP, 0);

INSERT INTO TBL_INVESTMENT_MONITORING (MONITORING_ID, INVESTMENT_ID, INVESTMENT_TYPE, MONITORING_DATE, MONITORING_TYPE, CURRENT_VALUE, PREVIOUS_VALUE, VALUE_CHANGE, VALUE_CHANGE_RATE, RISK_SCORE, RISK_LEVEL, ALERT_STATUS, ALERT_TYPE, ALERT_MESSAGE, ALERT_TIME, HANDLE_STATUS, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (2, 2, 'BOND', '2025-01-04', 'RISK', 19900000.00, 19850000.00, 50000.00, 0.00252, 45.00, 'MEDIUM', 'WARNING', 'CREDIT_DOWNGRADE', '发行人信用评级下调预警', CURRENT_TIMESTAMP, 'PENDING', 1, '华博云科技有限公司', 1, '系统', CURRENT_TIMESTAMP, 0);

INSERT INTO TBL_INVESTMENT_MONITORING (MONITORING_ID, INVESTMENT_ID, INVESTMENT_TYPE, MONITORING_DATE, MONITORING_TYPE, CURRENT_VALUE, PREVIOUS_VALUE, VALUE_CHANGE, VALUE_CHANGE_RATE, RISK_SCORE, RISK_LEVEL, ALERT_STATUS, COMPANY_ID, COMPANY_NAME, CREATED_BY, CREATED_BY_NAME, CREATED_TIME, DELETE_FLAG)
VALUES (3, 1, 'BOND', '2025-01-04', 'RETURN', 30060000.00, 29900000.00, 160000.00, 0.00535, 20.00, 'LOW', 'NORMAL', 1, '华博云科技有限公司', 1, '系统', CURRENT_TIMESTAMP, 0);

COMMIT;

