-- =====================================================
-- 投资管理模块数据库表结构
-- 兼容达梦数据库/MySQL/Oracle
-- 创建时间: 2025-12-30
-- =====================================================

-- 1. 投资产品表
CREATE TABLE TBL_INVESTMENT_PRODUCT (
    PRODUCT_ID              BIGINT          NOT NULL,
    PRODUCT_CODE            VARCHAR(50)     NOT NULL,
    PRODUCT_NAME            VARCHAR(200)    NOT NULL,
    PRODUCT_TYPE            VARCHAR(50)     NOT NULL,
    ISSUER                  VARCHAR(200),
    RISK_LEVEL              VARCHAR(20)     NOT NULL,
    EXPECTED_RETURN_RATE    DECIMAL(10,4),
    MIN_INVESTMENT_AMOUNT   DECIMAL(18,2),
    MAX_INVESTMENT_AMOUNT   DECIMAL(18,2),
    INVESTMENT_TERM         INT,
    NET_VALUE               DECIMAL(10,4)   DEFAULT 1.0000,
    LAUNCH_DATE             DATE,
    MATURITY_DATE           DATE,
    SUBSCRIPTION_START_DATE DATE,
    SUBSCRIPTION_END_DATE   DATE,
    REDEMPTION_ALLOWED      INT             DEFAULT 1,
    PRODUCT_STATUS          VARCHAR(20)     DEFAULT 'ACTIVE',
    PRODUCT_DESCRIPTION     VARCHAR(2000),
    SUSPEND_REASON          VARCHAR(500),
    CURRENCY_CODE           VARCHAR(10)     DEFAULT 'CNY',
    COMPANY_ID              BIGINT,
    COMPANY_NAME            VARCHAR(200),
    DELETE_FLAG             INT             DEFAULT 0,
    CREATED_BY              BIGINT,
    CREATED_BY_NAME         VARCHAR(100),
    CREATED_TIME            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY              BIGINT,
    UPDATED_BY_NAME         VARCHAR(100),
    UPDATED_TIME            TIMESTAMP,
    REMARK                  VARCHAR(500),
    PRIMARY KEY (PRODUCT_ID)
);

CREATE UNIQUE INDEX IDX_PRODUCT_CODE ON TBL_INVESTMENT_PRODUCT(PRODUCT_CODE);
CREATE INDEX IDX_PRODUCT_TYPE ON TBL_INVESTMENT_PRODUCT(PRODUCT_TYPE);
CREATE INDEX IDX_PRODUCT_STATUS ON TBL_INVESTMENT_PRODUCT(PRODUCT_STATUS);
CREATE INDEX IDX_PRODUCT_COMPANY ON TBL_INVESTMENT_PRODUCT(COMPANY_ID);

COMMENT ON TABLE TBL_INVESTMENT_PRODUCT IS '投资产品表';
COMMENT ON COLUMN TBL_INVESTMENT_PRODUCT.PRODUCT_ID IS '产品ID';
COMMENT ON COLUMN TBL_INVESTMENT_PRODUCT.PRODUCT_CODE IS '产品代码';
COMMENT ON COLUMN TBL_INVESTMENT_PRODUCT.PRODUCT_NAME IS '产品名称';
COMMENT ON COLUMN TBL_INVESTMENT_PRODUCT.PRODUCT_TYPE IS '产品类型';
COMMENT ON COLUMN TBL_INVESTMENT_PRODUCT.RISK_LEVEL IS '风险等级(LOW/MEDIUM/HIGH)';
COMMENT ON COLUMN TBL_INVESTMENT_PRODUCT.PRODUCT_STATUS IS '产品状态(ACTIVE/SUSPENDED)';

-- 2. 投资计划表
CREATE TABLE TBL_INVESTMENT_PLAN (
    PLAN_ID                 BIGINT          NOT NULL,
    PLAN_NO                 VARCHAR(50)     NOT NULL,
    PLAN_NAME               VARCHAR(200)    NOT NULL,
    INVESTMENT_TYPE         VARCHAR(50)     NOT NULL,
    RISK_LEVEL              VARCHAR(20)     NOT NULL,
    PLAN_AMOUNT             DECIMAL(18,2)   NOT NULL,
    INVESTED_AMOUNT         DECIMAL(18,2)   DEFAULT 0,
    EXPECTED_RETURN_RATE    DECIMAL(10,4),
    ACTUAL_RETURN_RATE      DECIMAL(10,4),
    PLAN_START_DATE         DATE            NOT NULL,
    PLAN_END_DATE           DATE            NOT NULL,
    PLAN_STATUS             VARCHAR(20)     DEFAULT 'DRAFT',
    PLAN_DESCRIPTION        VARCHAR(2000),
    APPROVAL_COMMENTS       VARCHAR(500),
    APPROVED_BY             BIGINT,
    APPROVED_BY_NAME        VARCHAR(100),
    APPROVAL_TIME           TIMESTAMP,
    REJECTION_REASON        VARCHAR(500),
    COMPLETION_NOTES        VARCHAR(500),
    CANCEL_REASON           VARCHAR(500),
    CURRENCY_CODE           VARCHAR(10)     DEFAULT 'CNY',
    COMPANY_ID              BIGINT,
    COMPANY_NAME            VARCHAR(200),
    DELETE_FLAG             INT             DEFAULT 0,
    CREATED_BY              BIGINT,
    CREATED_BY_NAME         VARCHAR(100),
    CREATED_TIME            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY              BIGINT,
    UPDATED_BY_NAME         VARCHAR(100),
    UPDATED_TIME            TIMESTAMP,
    REMARK                  VARCHAR(500),
    PRIMARY KEY (PLAN_ID)
);

CREATE UNIQUE INDEX IDX_PLAN_NO ON TBL_INVESTMENT_PLAN(PLAN_NO);
CREATE INDEX IDX_PLAN_STATUS ON TBL_INVESTMENT_PLAN(PLAN_STATUS);
CREATE INDEX IDX_PLAN_TYPE ON TBL_INVESTMENT_PLAN(INVESTMENT_TYPE);
CREATE INDEX IDX_PLAN_COMPANY ON TBL_INVESTMENT_PLAN(COMPANY_ID);

COMMENT ON TABLE TBL_INVESTMENT_PLAN IS '投资计划表';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_ID IS '计划ID';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_NO IS '计划编号';
COMMENT ON COLUMN TBL_INVESTMENT_PLAN.PLAN_STATUS IS '计划状态(DRAFT/SUBMITTED/APPROVED/EXECUTING/COMPLETED/CANCELLED)';

-- 3. 投资监控表
CREATE TABLE TBL_INVESTMENT_MONITORING (
    MONITORING_ID           BIGINT          NOT NULL,
    INVESTMENT_ID           BIGINT          NOT NULL,
    INVESTMENT_TYPE         VARCHAR(50),
    MONITORING_DATE         DATE            NOT NULL,
    MONITORING_TYPE         VARCHAR(20)     NOT NULL,
    PREVIOUS_VALUE          DECIMAL(18,2),
    CURRENT_VALUE           DECIMAL(18,2),
    VALUE_CHANGE            DECIMAL(18,2),
    VALUE_CHANGE_RATE       DECIMAL(10,4),
    PERFORMANCE_SCORE       INT,
    RISK_SCORE              INT,
    ALERT_LEVEL             VARCHAR(20),
    ALERT_MESSAGE           VARCHAR(500),
    ALERT_TYPE              VARCHAR(50),
    ALERT_STATUS            VARCHAR(20)     DEFAULT 'PENDING',
    MONITORING_STATUS       VARCHAR(20)     DEFAULT 'ACTIVE',
    MONITORING_NOTES        VARCHAR(1000),
    COMPANY_ID              BIGINT,
    COMPANY_NAME            VARCHAR(200),
    DELETE_FLAG             INT             DEFAULT 0,
    CREATED_BY              BIGINT,
    CREATED_BY_NAME         VARCHAR(100),
    CREATED_TIME            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY              BIGINT,
    UPDATED_BY_NAME         VARCHAR(100),
    UPDATED_TIME            TIMESTAMP,
    REMARK                  VARCHAR(500),
    PRIMARY KEY (MONITORING_ID)
);

CREATE INDEX IDX_MONITORING_INVESTMENT ON TBL_INVESTMENT_MONITORING(INVESTMENT_ID);
CREATE INDEX IDX_MONITORING_DATE ON TBL_INVESTMENT_MONITORING(MONITORING_DATE);
CREATE INDEX IDX_MONITORING_ALERT ON TBL_INVESTMENT_MONITORING(ALERT_LEVEL, ALERT_STATUS);

COMMENT ON TABLE TBL_INVESTMENT_MONITORING IS '投资监控表';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.MONITORING_ID IS '监控ID';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.ALERT_LEVEL IS '预警级别(LOW/MEDIUM/HIGH)';
COMMENT ON COLUMN TBL_INVESTMENT_MONITORING.ALERT_STATUS IS '预警状态(PENDING/PROCESSED)';

-- 4. 银行理财投资表
CREATE TABLE TBL_BANK_WEALTH_INVESTMENT (
    INVESTMENT_ID           BIGINT          NOT NULL,
    INVESTMENT_NO           VARCHAR(50)     NOT NULL,
    PRODUCT_ID              BIGINT,
    PRODUCT_CODE            VARCHAR(50),
    PRODUCT_NAME            VARCHAR(200)    NOT NULL,
    BANK_NAME               VARCHAR(200)    NOT NULL,
    INVESTMENT_AMOUNT       DECIMAL(18,2)   NOT NULL,
    EXPECTED_RETURN_RATE    DECIMAL(10,4),
    ACTUAL_RETURN_RATE      DECIMAL(10,4),
    EXPECTED_RETURN         DECIMAL(18,2),
    ACTUAL_RETURN           DECIMAL(18,2),
    INVESTMENT_TERM         INT             NOT NULL,
    VALUE_DATE              DATE            NOT NULL,
    MATURITY_DATE           DATE            NOT NULL,
    REDEMPTION_DATE         DATE,
    RISK_LEVEL              VARCHAR(20)     NOT NULL,
    INVESTMENT_STATUS       VARCHAR(20)     DEFAULT 'PENDING',
    CURRENCY_CODE           VARCHAR(10)     DEFAULT 'CNY',
    PLAN_ID                 BIGINT,
    PLAN_NO                 VARCHAR(50),
    COMPANY_ID              BIGINT,
    COMPANY_NAME            VARCHAR(200),
    DELETE_FLAG             INT             DEFAULT 0,
    CREATED_BY              BIGINT,
    CREATED_BY_NAME         VARCHAR(100),
    CREATED_TIME            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY              BIGINT,
    UPDATED_BY_NAME         VARCHAR(100),
    UPDATED_TIME            TIMESTAMP,
    REMARK                  VARCHAR(500),
    PRIMARY KEY (INVESTMENT_ID)
);

CREATE UNIQUE INDEX IDX_BANK_INVESTMENT_NO ON TBL_BANK_WEALTH_INVESTMENT(INVESTMENT_NO);
CREATE INDEX IDX_BANK_INVESTMENT_STATUS ON TBL_BANK_WEALTH_INVESTMENT(INVESTMENT_STATUS);
CREATE INDEX IDX_BANK_INVESTMENT_MATURITY ON TBL_BANK_WEALTH_INVESTMENT(MATURITY_DATE);
CREATE INDEX IDX_BANK_INVESTMENT_COMPANY ON TBL_BANK_WEALTH_INVESTMENT(COMPANY_ID);

COMMENT ON TABLE TBL_BANK_WEALTH_INVESTMENT IS '银行理财投资表';
COMMENT ON COLUMN TBL_BANK_WEALTH_INVESTMENT.INVESTMENT_ID IS '投资ID';
COMMENT ON COLUMN TBL_BANK_WEALTH_INVESTMENT.INVESTMENT_STATUS IS '投资状态(PENDING/ACTIVE/MATURED/REDEEMED)';

-- 5. 债券投资表
CREATE TABLE TBL_BOND_INVESTMENT (
    INVESTMENT_ID           BIGINT          NOT NULL,
    INVESTMENT_NO           VARCHAR(50)     NOT NULL,
    BOND_CODE               VARCHAR(50)     NOT NULL,
    BOND_NAME               VARCHAR(200)    NOT NULL,
    BOND_TYPE               VARCHAR(50)     NOT NULL,
    ISSUER                  VARCHAR(200)    NOT NULL,
    CREDIT_RATING           VARCHAR(20),
    FACE_VALUE              DECIMAL(18,2)   NOT NULL,
    PURCHASE_PRICE          DECIMAL(18,4)   NOT NULL,
    PURCHASE_QUANTITY       INT             NOT NULL,
    INVESTMENT_AMOUNT       DECIMAL(18,2)   NOT NULL,
    COUPON_RATE             DECIMAL(10,4)   NOT NULL,
    YIELD_TO_MATURITY       DECIMAL(10,4),
    COUPON_FREQUENCY        VARCHAR(20),
    PURCHASE_DATE           DATE            NOT NULL,
    MATURITY_DATE           DATE            NOT NULL,
    NEXT_COUPON_DATE        DATE,
    ACCUMULATED_INTEREST    DECIMAL(18,2)   DEFAULT 0,
    CURRENT_MARKET_VALUE    DECIMAL(18,2),
    UNREALIZED_PNL          DECIMAL(18,2)   DEFAULT 0,
    RISK_LEVEL              VARCHAR(20)     NOT NULL,
    INVESTMENT_STATUS       VARCHAR(20)     DEFAULT 'HOLDING',
    CURRENCY_CODE           VARCHAR(10)     DEFAULT 'CNY',
    PLAN_ID                 BIGINT,
    PLAN_NO                 VARCHAR(50),
    COMPANY_ID              BIGINT,
    COMPANY_NAME            VARCHAR(200),
    DELETE_FLAG             INT             DEFAULT 0,
    CREATED_BY              BIGINT,
    CREATED_BY_NAME         VARCHAR(100),
    CREATED_TIME            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY              BIGINT,
    UPDATED_BY_NAME         VARCHAR(100),
    UPDATED_TIME            TIMESTAMP,
    REMARK                  VARCHAR(500),
    PRIMARY KEY (INVESTMENT_ID)
);

CREATE UNIQUE INDEX IDX_BOND_INVESTMENT_NO ON TBL_BOND_INVESTMENT(INVESTMENT_NO);
CREATE INDEX IDX_BOND_CODE ON TBL_BOND_INVESTMENT(BOND_CODE);
CREATE INDEX IDX_BOND_TYPE ON TBL_BOND_INVESTMENT(BOND_TYPE);
CREATE INDEX IDX_BOND_INVESTMENT_STATUS ON TBL_BOND_INVESTMENT(INVESTMENT_STATUS);
CREATE INDEX IDX_BOND_MATURITY ON TBL_BOND_INVESTMENT(MATURITY_DATE);
CREATE INDEX IDX_BOND_COMPANY ON TBL_BOND_INVESTMENT(COMPANY_ID);

COMMENT ON TABLE TBL_BOND_INVESTMENT IS '债券投资表';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.INVESTMENT_ID IS '投资ID';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.BOND_TYPE IS '债券类型(GOVERNMENT/CORPORATE/FINANCIAL/LOCAL)';
COMMENT ON COLUMN TBL_BOND_INVESTMENT.INVESTMENT_STATUS IS '投资状态(HOLDING/SOLD/MATURED)';

