-- ============================================================
-- 融资租赁管理模块 - 数据库初始化脚本
-- 适用数据库: 达梦数据库 / Oracle / MySQL
-- 创建时间: 2026-02-09
-- ============================================================

-- 1. 租赁资产表
CREATE TABLE TBL_LEASE_ASSET (
    ASSET_ID            NUMBER(19)          PRIMARY KEY,
    LEASE_ID            NUMBER(19)          NOT NULL,
    ASSET_CODE          VARCHAR2(50)        NOT NULL,
    ASSET_NAME          VARCHAR2(200)       NOT NULL,
    ASSET_TYPE          VARCHAR2(20)        DEFAULT 'EQUIPMENT',
    ASSET_VALUE         NUMBER(18,2)        DEFAULT 0,
    PURCHASE_DATE       DATE,
    LOCATION            VARCHAR2(200),
    DESCRIPTION         VARCHAR2(500),
    STATUS              VARCHAR2(20)        DEFAULT 'NORMAL',
    CREATED_BY          NUMBER(19),
    CREATED_TIME        DATE                DEFAULT SYSDATE,
    UPDATED_BY          NUMBER(19),
    UPDATED_TIME        DATE
);

COMMENT ON TABLE TBL_LEASE_ASSET IS '租赁资产表';
COMMENT ON COLUMN TBL_LEASE_ASSET.ASSET_ID IS '资产ID';
COMMENT ON COLUMN TBL_LEASE_ASSET.LEASE_ID IS '租赁ID';
COMMENT ON COLUMN TBL_LEASE_ASSET.ASSET_CODE IS '资产编号';
COMMENT ON COLUMN TBL_LEASE_ASSET.ASSET_NAME IS '资产名称';
COMMENT ON COLUMN TBL_LEASE_ASSET.ASSET_TYPE IS '资产类型(EQUIPMENT-设备,VEHICLE-车辆,PROPERTY-房产,OTHER-其他)';
COMMENT ON COLUMN TBL_LEASE_ASSET.ASSET_VALUE IS '资产价值';
COMMENT ON COLUMN TBL_LEASE_ASSET.PURCHASE_DATE IS '购置日期';
COMMENT ON COLUMN TBL_LEASE_ASSET.LOCATION IS '存放位置';
COMMENT ON COLUMN TBL_LEASE_ASSET.DESCRIPTION IS '资产描述';
COMMENT ON COLUMN TBL_LEASE_ASSET.STATUS IS '资产状态(NORMAL-正常,ABNORMAL-异常,DISPOSED-已处置)';

CREATE INDEX IDX_LEASE_ASSET_LEASE_ID ON TBL_LEASE_ASSET(LEASE_ID);

-- 2. 租金计划表
CREATE TABLE TBL_LEASE_PAYMENT (
    PAYMENT_ID          NUMBER(19)          PRIMARY KEY,
    LEASE_ID            NUMBER(19)          NOT NULL,
    PERIOD              NUMBER(10)          NOT NULL,
    DUE_DATE            DATE                NOT NULL,
    PRINCIPAL           NUMBER(18,2)        DEFAULT 0,
    INTEREST            NUMBER(18,2)        DEFAULT 0,
    AMOUNT              NUMBER(18,2)        DEFAULT 0,
    PAID_AMOUNT         NUMBER(18,2)        DEFAULT 0,
    PAID_DATE           DATE,
    STATUS              VARCHAR2(20)        DEFAULT 'PENDING',
    REMARK              VARCHAR2(500),
    CREATED_BY          NUMBER(19),
    CREATED_TIME        DATE                DEFAULT SYSDATE,
    UPDATED_BY          NUMBER(19),
    UPDATED_TIME        DATE
);

COMMENT ON TABLE TBL_LEASE_PAYMENT IS '租金计划表';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.PAYMENT_ID IS '付款ID';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.LEASE_ID IS '租赁ID';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.PERIOD IS '期数';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.DUE_DATE IS '应付日期';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.PRINCIPAL IS '本金';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.INTEREST IS '利息';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.AMOUNT IS '应付金额';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.PAID_AMOUNT IS '实付金额';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.PAID_DATE IS '付款日期';
COMMENT ON COLUMN TBL_LEASE_PAYMENT.STATUS IS '付款状态(PENDING-待付,PAID-已付,OVERDUE-逾期)';

CREATE INDEX IDX_LEASE_PAYMENT_LEASE_ID ON TBL_LEASE_PAYMENT(LEASE_ID);
CREATE INDEX IDX_LEASE_PAYMENT_STATUS ON TBL_LEASE_PAYMENT(STATUS);

-- 3. 退租申请表
CREATE TABLE TBL_LEASE_RETURN (
    RETURN_ID           NUMBER(19)          PRIMARY KEY,
    LEASE_ID            NUMBER(19)          NOT NULL,
    RETURN_TYPE         VARCHAR2(20)        NOT NULL,
    RETURN_DATE         DATE,
    ASSET_DISPOSAL      VARCHAR2(20),
    RESIDUAL_VALUE      NUMBER(18,2)        DEFAULT 0,
    PENALTY_AMOUNT      NUMBER(18,2)        DEFAULT 0,
    SETTLEMENT_AMOUNT   NUMBER(18,2)        DEFAULT 0,
    RETURN_REASON       VARCHAR2(1000),
    STATUS              VARCHAR2(20)        DEFAULT 'DRAFT',
    ATTACHMENTS         VARCHAR2(2000),
    APPROVAL_COMMENTS   VARCHAR2(500),
    APPROVED_BY         NUMBER(19),
    APPROVED_TIME       DATE,
    CREATED_BY          NUMBER(19),
    CREATED_TIME        DATE                DEFAULT SYSDATE,
    UPDATED_BY          NUMBER(19),
    UPDATED_TIME        DATE
);

COMMENT ON TABLE TBL_LEASE_RETURN IS '退租申请表';
COMMENT ON COLUMN TBL_LEASE_RETURN.RETURN_ID IS '退租ID';
COMMENT ON COLUMN TBL_LEASE_RETURN.LEASE_ID IS '租赁ID';
COMMENT ON COLUMN TBL_LEASE_RETURN.RETURN_TYPE IS '退租类型(NORMAL-正常到期,EARLY-提前退租,BREACH-违约退租)';
COMMENT ON COLUMN TBL_LEASE_RETURN.RETURN_DATE IS '退租日期';
COMMENT ON COLUMN TBL_LEASE_RETURN.ASSET_DISPOSAL IS '资产处置方式(RETURN-归还,PURCHASE-购买,TRANSFER-转让)';
COMMENT ON COLUMN TBL_LEASE_RETURN.RESIDUAL_VALUE IS '资产残值';
COMMENT ON COLUMN TBL_LEASE_RETURN.PENALTY_AMOUNT IS '违约金';
COMMENT ON COLUMN TBL_LEASE_RETURN.SETTLEMENT_AMOUNT IS '结算金额';
COMMENT ON COLUMN TBL_LEASE_RETURN.RETURN_REASON IS '退租原因';
COMMENT ON COLUMN TBL_LEASE_RETURN.STATUS IS '申请状态(DRAFT-草稿,SUBMITTED-已提交,APPROVED-已审批,REJECTED-已拒绝,COMPLETED-已完成)';

CREATE INDEX IDX_LEASE_RETURN_LEASE_ID ON TBL_LEASE_RETURN(LEASE_ID);
CREATE INDEX IDX_LEASE_RETURN_STATUS ON TBL_LEASE_RETURN(STATUS);

-- ============================================================
-- 测试数据插入
-- 注意: 请先确保 TBL_FINANCIAL_LEASE 表中存在对应的租赁记录
-- 以下测试数据关联到已存在的租赁ID
-- ============================================================

-- 首先查询现有的租赁ID（请根据实际情况调整）
-- SELECT LEASE_ID, LEASE_NO FROM TBL_FINANCIAL_LEASE WHERE DELETE_FLAG = 0;

-- ============================================================
-- 如果需要先插入主表测试数据，请使用以下语句
-- 注意：请根据实际表结构调整列名
-- ============================================================
-- 方案A: 如果表结构是 create_tables.sql 中的版本
INSERT INTO TBL_FINANCIAL_LEASE (LEASE_ID, LEASE_NO, LEASE_NAME, COMPANY_ID, COMPANY_NAME, LESSOR_ID, LESSOR_NAME, LEASE_TYPE, LEASE_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, START_DATE, END_DATE, LEASE_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME)
VALUES (1001, 'FL-2026-0001', '数控机床设备融资租赁', 100, '华博科技有限公司', 1, '中信金融租赁', 'DIRECT', 4500000.00, 4000000.00, 'CNY', 0.055, TO_DATE('2026-02-01', 'YYYY-MM-DD'), TO_DATE('2029-01-31', 'YYYY-MM-DD'), 'ACTIVE', 0, '1', SYSDATE);

INSERT INTO TBL_FINANCIAL_LEASE (LEASE_ID, LEASE_NO, LEASE_NAME, COMPANY_ID, COMPANY_NAME, LESSOR_ID, LESSOR_NAME, LEASE_TYPE, LEASE_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, START_DATE, END_DATE, LEASE_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME)
VALUES (1002, 'FL-2026-0002', '物流运输车队售后回租', 100, '华博科技有限公司', 2, '招银金融租赁', 'LEASEBACK', 2700000.00, 2400000.00, 'CNY', 0.048, TO_DATE('2026-02-15', 'YYYY-MM-DD'), TO_DATE('2028-02-14', 'YYYY-MM-DD'), 'ACTIVE', 0, '1', SYSDATE);

INSERT INTO TBL_FINANCIAL_LEASE (LEASE_ID, LEASE_NO, LEASE_NAME, COMPANY_ID, COMPANY_NAME, LESSOR_ID, LESSOR_NAME, LEASE_TYPE, LEASE_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, START_DATE, END_DATE, LEASE_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME)
VALUES (1003, 'FL-2026-0003', '办公楼宇融资租赁', 101, '华博物流有限公司', 3, '工银金融租赁', 'DIRECT', 18000000.00, 18000000.00, 'CNY', 0.052, NULL, NULL, 'PENDING', 0, '1', SYSDATE);

INSERT INTO TBL_FINANCIAL_LEASE (LEASE_ID, LEASE_NO, LEASE_NAME, COMPANY_ID, COMPANY_NAME, LESSOR_ID, LESSOR_NAME, LEASE_TYPE, LEASE_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, START_DATE, END_DATE, LEASE_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME)
VALUES (1004, 'FL-2026-0004', '医疗设备杠杆租赁', 102, '华博医疗科技', 4, '交银金融租赁', 'LEVERAGED', 7200000.00, 7200000.00, 'CNY', 0.050, NULL, NULL, 'PENDING', 0, '1', SYSDATE);

INSERT INTO TBL_FINANCIAL_LEASE (LEASE_ID, LEASE_NO, LEASE_NAME, COMPANY_ID, COMPANY_NAME, LESSOR_ID, LESSOR_NAME, LEASE_TYPE, LEASE_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, START_DATE, END_DATE, LEASE_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME)
VALUES (1005, 'FL-2026-0005', '商务车辆经营租赁', 100, '华博科技有限公司', 5, '建信金融租赁', 'OPERATING', 1350000.00, 1000000.00, 'CNY', 0.045, TO_DATE('2025-12-15', 'YYYY-MM-DD'), TO_DATE('2026-12-14', 'YYYY-MM-DD'), 'ACTIVE', 0, '1', SYSDATE);

INSERT INTO TBL_FINANCIAL_LEASE (LEASE_ID, LEASE_NO, LEASE_NAME, COMPANY_ID, COMPANY_NAME, LESSOR_ID, LESSOR_NAME, LEASE_TYPE, LEASE_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, START_DATE, END_DATE, LEASE_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME)
VALUES (1006, 'FL-2026-0006', '农业机械设备租赁', 103, '华博农业发展', 6, '农银金融租赁', 'DIRECT', 2250000.00, 2250000.00, 'CNY', 0.042, NULL, NULL, 'PENDING', 0, '1', SYSDATE);

INSERT INTO TBL_FINANCIAL_LEASE (LEASE_ID, LEASE_NO, LEASE_NAME, COMPANY_ID, COMPANY_NAME, LESSOR_ID, LESSOR_NAME, LEASE_TYPE, LEASE_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, START_DATE, END_DATE, LEASE_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME)
VALUES (1007, 'FL-2026-0007', '印刷设备售后回租', 100, '华博科技有限公司', 7, '兴业金融租赁', 'LEASEBACK', 3600000.00, 0, 'CNY', 0.053, TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2026-01-31', 'YYYY-MM-DD'), 'COMPLETED', 0, '1', SYSDATE);

INSERT INTO TBL_FINANCIAL_LEASE (LEASE_ID, LEASE_NO, LEASE_NAME, COMPANY_ID, COMPANY_NAME, LESSOR_ID, LESSOR_NAME, LEASE_TYPE, LEASE_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, START_DATE, END_DATE, LEASE_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME)
VALUES (1008, 'FL-2026-0008', 'IT服务器设备租赁', 100, '华博科技有限公司', 8, '浦银金融租赁', 'DIRECT', 1080000.00, 800000.00, 'CNY', 0.058, TO_DATE('2025-07-01', 'YYYY-MM-DD'), TO_DATE('2028-06-30', 'YYYY-MM-DD'), 'ACTIVE', 0, '1', SYSDATE);

INSERT INTO TBL_FINANCIAL_LEASE (LEASE_ID, LEASE_NO, LEASE_NAME, COMPANY_ID, COMPANY_NAME, LESSOR_ID, LESSOR_NAME, LEASE_TYPE, LEASE_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, START_DATE, END_DATE, LEASE_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME)
VALUES (1009, 'FL-2026-0009', '新能源发电设备租赁', 104, '华博新能源', 9, '民生金融租赁', 'LEVERAGED', 13500000.00, 13500000.00, 'CNY', 0.049, TO_DATE('2026-03-01', 'YYYY-MM-DD'), TO_DATE('2031-02-28', 'YYYY-MM-DD'), 'ACTIVE', 0, '1', SYSDATE);

INSERT INTO TBL_FINANCIAL_LEASE (LEASE_ID, LEASE_NO, LEASE_NAME, COMPANY_ID, COMPANY_NAME, LESSOR_ID, LESSOR_NAME, LEASE_TYPE, LEASE_AMOUNT, OUTSTANDING_AMOUNT, CURRENCY_CODE, INTEREST_RATE, START_DATE, END_DATE, LEASE_STATUS, DELETE_FLAG, CREATED_BY, CREATED_TIME)
VALUES (1010, 'FL-2026-0010', '仓储物流中心租赁', 101, '华博物流有限公司', 10, '光大金融租赁', 'OPERATING', 27000000.00, 27000000.00, 'CNY', 0.051, NULL, NULL, 'PENDING', 0, '1', SYSDATE);

-- ============================================================
-- 租赁资产测试数据 (关联租赁ID 1001, 1002, 1005, 1008)
-- ============================================================
INSERT INTO TBL_LEASE_ASSET (ASSET_ID, LEASE_ID, ASSET_CODE, ASSET_NAME, ASSET_TYPE, ASSET_VALUE, PURCHASE_DATE, LOCATION, DESCRIPTION, STATUS, CREATED_BY, CREATED_TIME)
VALUES (2001, 1001, 'AST-2026-0001', '五轴数控加工中心', 'EQUIPMENT', 2500000.00, TO_DATE('2026-01-20', 'YYYY-MM-DD'), '生产车间A区', '德国进口五轴联动数控加工中心', 'NORMAL', 1, SYSDATE);

INSERT INTO TBL_LEASE_ASSET (ASSET_ID, LEASE_ID, ASSET_CODE, ASSET_NAME, ASSET_TYPE, ASSET_VALUE, PURCHASE_DATE, LOCATION, DESCRIPTION, STATUS, CREATED_BY, CREATED_TIME)
VALUES (2002, 1001, 'AST-2026-0002', '数控车床', 'EQUIPMENT', 1500000.00, TO_DATE('2026-01-20', 'YYYY-MM-DD'), '生产车间A区', '高精度数控车床', 'NORMAL', 1, SYSDATE);

INSERT INTO TBL_LEASE_ASSET (ASSET_ID, LEASE_ID, ASSET_CODE, ASSET_NAME, ASSET_TYPE, ASSET_VALUE, PURCHASE_DATE, LOCATION, DESCRIPTION, STATUS, CREATED_BY, CREATED_TIME)
VALUES (2003, 1001, 'AST-2026-0003', '激光切割机', 'EQUIPMENT', 1000000.00, TO_DATE('2026-01-22', 'YYYY-MM-DD'), '生产车间B区', '光纤激光切割设备', 'NORMAL', 1, SYSDATE);

INSERT INTO TBL_LEASE_ASSET (ASSET_ID, LEASE_ID, ASSET_CODE, ASSET_NAME, ASSET_TYPE, ASSET_VALUE, PURCHASE_DATE, LOCATION, DESCRIPTION, STATUS, CREATED_BY, CREATED_TIME)
VALUES (2004, 1002, 'AST-2026-0004', '重型货运卡车A', 'VEHICLE', 800000.00, TO_DATE('2026-02-10', 'YYYY-MM-DD'), '物流停车场', '东风重型货运卡车', 'NORMAL', 1, SYSDATE);

INSERT INTO TBL_LEASE_ASSET (ASSET_ID, LEASE_ID, ASSET_CODE, ASSET_NAME, ASSET_TYPE, ASSET_VALUE, PURCHASE_DATE, LOCATION, DESCRIPTION, STATUS, CREATED_BY, CREATED_TIME)
VALUES (2005, 1002, 'AST-2026-0005', '重型货运卡车B', 'VEHICLE', 800000.00, TO_DATE('2026-02-10', 'YYYY-MM-DD'), '物流停车场', '东风重型货运卡车', 'NORMAL', 1, SYSDATE);

INSERT INTO TBL_LEASE_ASSET (ASSET_ID, LEASE_ID, ASSET_CODE, ASSET_NAME, ASSET_TYPE, ASSET_VALUE, PURCHASE_DATE, LOCATION, DESCRIPTION, STATUS, CREATED_BY, CREATED_TIME)
VALUES (2006, 1002, 'AST-2026-0006', '冷链运输车', 'VEHICLE', 1200000.00, TO_DATE('2026-02-12', 'YYYY-MM-DD'), '物流停车场', '冷链物流专用车', 'NORMAL', 1, SYSDATE);

INSERT INTO TBL_LEASE_ASSET (ASSET_ID, LEASE_ID, ASSET_CODE, ASSET_NAME, ASSET_TYPE, ASSET_VALUE, PURCHASE_DATE, LOCATION, DESCRIPTION, STATUS, CREATED_BY, CREATED_TIME)
VALUES (2007, 1005, 'AST-2025-0007', '商务轿车A', 'VEHICLE', 500000.00, TO_DATE('2025-12-10', 'YYYY-MM-DD'), '公司停车场', '奥迪A6L商务轿车', 'NORMAL', 1, SYSDATE);

INSERT INTO TBL_LEASE_ASSET (ASSET_ID, LEASE_ID, ASSET_CODE, ASSET_NAME, ASSET_TYPE, ASSET_VALUE, PURCHASE_DATE, LOCATION, DESCRIPTION, STATUS, CREATED_BY, CREATED_TIME)
VALUES (2008, 1005, 'AST-2025-0008', '商务轿车B', 'VEHICLE', 500000.00, TO_DATE('2025-12-10', 'YYYY-MM-DD'), '公司停车场', '宝马5系商务轿车', 'NORMAL', 1, SYSDATE);

INSERT INTO TBL_LEASE_ASSET (ASSET_ID, LEASE_ID, ASSET_CODE, ASSET_NAME, ASSET_TYPE, ASSET_VALUE, PURCHASE_DATE, LOCATION, DESCRIPTION, STATUS, CREATED_BY, CREATED_TIME)
VALUES (2009, 1008, 'AST-2025-0009', '服务器集群', 'OTHER', 800000.00, TO_DATE('2025-06-25', 'YYYY-MM-DD'), '数据中心机房', 'Dell PowerEdge服务器集群', 'NORMAL', 1, SYSDATE);

INSERT INTO TBL_LEASE_ASSET (ASSET_ID, LEASE_ID, ASSET_CODE, ASSET_NAME, ASSET_TYPE, ASSET_VALUE, PURCHASE_DATE, LOCATION, DESCRIPTION, STATUS, CREATED_BY, CREATED_TIME)
VALUES (2010, 1008, 'AST-2025-0010', '存储阵列', 'OTHER', 400000.00, TO_DATE('2025-06-25', 'YYYY-MM-DD'), '数据中心机房', 'EMC存储阵列设备', 'NORMAL', 1, SYSDATE);

-- ============================================================
-- 租金计划测试数据 (为租赁ID 1001 创建12期租金计划)
-- ============================================================
INSERT INTO TBL_LEASE_PAYMENT (PAYMENT_ID, LEASE_ID, PERIOD, DUE_DATE, PRINCIPAL, INTEREST, AMOUNT, PAID_AMOUNT, PAID_DATE, STATUS, REMARK, CREATED_BY, CREATED_TIME)
VALUES (3001, 1001, 1, TO_DATE('2026-03-01', 'YYYY-MM-DD'), 125000.00, 20625.00, 145625.00, 145625.00, TO_DATE('2026-02-28', 'YYYY-MM-DD'), 'PAID', '第1期租金已付', 1, SYSDATE);

INSERT INTO TBL_LEASE_PAYMENT (PAYMENT_ID, LEASE_ID, PERIOD, DUE_DATE, PRINCIPAL, INTEREST, AMOUNT, PAID_AMOUNT, PAID_DATE, STATUS, REMARK, CREATED_BY, CREATED_TIME)
VALUES (3002, 1001, 2, TO_DATE('2026-04-01', 'YYYY-MM-DD'), 125000.00, 20052.08, 145052.08, 0, NULL, 'PENDING', '第2期租金待付', 1, SYSDATE);

INSERT INTO TBL_LEASE_PAYMENT (PAYMENT_ID, LEASE_ID, PERIOD, DUE_DATE, PRINCIPAL, INTEREST, AMOUNT, PAID_AMOUNT, PAID_DATE, STATUS, REMARK, CREATED_BY, CREATED_TIME)
VALUES (3003, 1001, 3, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 125000.00, 19479.17, 144479.17, 0, NULL, 'PENDING', '第3期租金待付', 1, SYSDATE);

INSERT INTO TBL_LEASE_PAYMENT (PAYMENT_ID, LEASE_ID, PERIOD, DUE_DATE, PRINCIPAL, INTEREST, AMOUNT, PAID_AMOUNT, PAID_DATE, STATUS, REMARK, CREATED_BY, CREATED_TIME)
VALUES (3004, 1001, 4, TO_DATE('2026-06-01', 'YYYY-MM-DD'), 125000.00, 18906.25, 143906.25, 0, NULL, 'PENDING', '第4期租金待付', 1, SYSDATE);

INSERT INTO TBL_LEASE_PAYMENT (PAYMENT_ID, LEASE_ID, PERIOD, DUE_DATE, PRINCIPAL, INTEREST, AMOUNT, PAID_AMOUNT, PAID_DATE, STATUS, REMARK, CREATED_BY, CREATED_TIME)
VALUES (3005, 1001, 5, TO_DATE('2026-07-01', 'YYYY-MM-DD'), 125000.00, 18333.33, 143333.33, 0, NULL, 'PENDING', '第5期租金待付', 1, SYSDATE);

INSERT INTO TBL_LEASE_PAYMENT (PAYMENT_ID, LEASE_ID, PERIOD, DUE_DATE, PRINCIPAL, INTEREST, AMOUNT, PAID_AMOUNT, PAID_DATE, STATUS, REMARK, CREATED_BY, CREATED_TIME)
VALUES (3006, 1001, 6, TO_DATE('2026-08-01', 'YYYY-MM-DD'), 125000.00, 17760.42, 142760.42, 0, NULL, 'PENDING', '第6期租金待付', 1, SYSDATE);

-- 为租赁ID 1005 创建租金计划（部分已付，部分逾期）
INSERT INTO TBL_LEASE_PAYMENT (PAYMENT_ID, LEASE_ID, PERIOD, DUE_DATE, PRINCIPAL, INTEREST, AMOUNT, PAID_AMOUNT, PAID_DATE, STATUS, REMARK, CREATED_BY, CREATED_TIME)
VALUES (3007, 1005, 1, TO_DATE('2026-01-15', 'YYYY-MM-DD'), 112500.00, 5062.50, 117562.50, 117562.50, TO_DATE('2026-01-14', 'YYYY-MM-DD'), 'PAID', '第1期租金已付', 1, SYSDATE);

INSERT INTO TBL_LEASE_PAYMENT (PAYMENT_ID, LEASE_ID, PERIOD, DUE_DATE, PRINCIPAL, INTEREST, AMOUNT, PAID_AMOUNT, PAID_DATE, STATUS, REMARK, CREATED_BY, CREATED_TIME)
VALUES (3008, 1005, 2, TO_DATE('2026-02-15', 'YYYY-MM-DD'), 112500.00, 4640.63, 117140.63, 0, NULL, 'OVERDUE', '第2期租金逾期', 1, SYSDATE);

INSERT INTO TBL_LEASE_PAYMENT (PAYMENT_ID, LEASE_ID, PERIOD, DUE_DATE, PRINCIPAL, INTEREST, AMOUNT, PAID_AMOUNT, PAID_DATE, STATUS, REMARK, CREATED_BY, CREATED_TIME)
VALUES (3009, 1005, 3, TO_DATE('2026-03-15', 'YYYY-MM-DD'), 112500.00, 4218.75, 116718.75, 0, NULL, 'PENDING', '第3期租金待付', 1, SYSDATE);

INSERT INTO TBL_LEASE_PAYMENT (PAYMENT_ID, LEASE_ID, PERIOD, DUE_DATE, PRINCIPAL, INTEREST, AMOUNT, PAID_AMOUNT, PAID_DATE, STATUS, REMARK, CREATED_BY, CREATED_TIME)
VALUES (3010, 1005, 4, TO_DATE('2026-04-15', 'YYYY-MM-DD'), 112500.00, 3796.88, 116296.88, 0, NULL, 'PENDING', '第4期租金待付', 1, SYSDATE);

-- ============================================================
-- 退租申请测试数据
-- ============================================================
INSERT INTO TBL_LEASE_RETURN (RETURN_ID, LEASE_ID, RETURN_TYPE, RETURN_DATE, ASSET_DISPOSAL, RESIDUAL_VALUE, PENALTY_AMOUNT, SETTLEMENT_AMOUNT, RETURN_REASON, STATUS, ATTACHMENTS, APPROVAL_COMMENTS, APPROVED_BY, APPROVED_TIME, CREATED_BY, CREATED_TIME)
VALUES (4001, 1007, 'NORMAL', TO_DATE('2026-01-31', 'YYYY-MM-DD'), 'RETURN', 200000.00, 0, 200000.00, '租赁期满正常退租', 'COMPLETED', '退租协议.pdf,资产交接单.pdf', '同意退租，资产已验收', 2, TO_DATE('2026-01-25', 'YYYY-MM-DD'), 1, SYSDATE);

INSERT INTO TBL_LEASE_RETURN (RETURN_ID, LEASE_ID, RETURN_TYPE, RETURN_DATE, ASSET_DISPOSAL, RESIDUAL_VALUE, PENALTY_AMOUNT, SETTLEMENT_AMOUNT, RETURN_REASON, STATUS, ATTACHMENTS, APPROVAL_COMMENTS, APPROVED_BY, APPROVED_TIME, CREATED_BY, CREATED_TIME)
VALUES (4002, 1005, 'EARLY', TO_DATE('2026-06-15', 'YYYY-MM-DD'), 'PURCHASE', 75000.00, 67500.00, 350000.00, '业务调整，提前终止租赁', 'SUBMITTED', '提前退租申请.pdf', NULL, NULL, NULL, 1, SYSDATE);

COMMIT;

