-- ============================================================
-- 补丁：为 ORG_ID=1000 补充结算平台测试数据
-- 原始数据 ORG_ID=1，当前登录用户 ORG_ID=1000 查不到数据
-- 执行前请确认 TBL_PENDING_DATA / TBL_SETTLEMENT_EXCEPTION 表已存在
-- ============================================================

-- ============================================================
-- 1. TBL_PENDING_DATA 待结算数据（ORG_ID=1000）
-- ============================================================

-- 高优先级 URGENT
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001001,'BUS20260316001','PAYMENT',158000.00,'CNY','6222021234567890001','北京科技有限公司','中国工商银行北京分行','URGENT',SYSDATE+1,NULL,'PENDING','PENDING',NULL,0,'供应商货款结算','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',NULL,NULL,NULL,NULL);
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001002,'BUS20260316002','TRANSFER',850000.00,'CNY','6222021234567890002','上海贸易股份公司','中国建设银行上海分行','URGENT',SYSDATE+1,NULL,'APPROVED','APPROVED',NULL,0,'集团内部资金划转','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',1,'管理员',SYSDATE,'同意划转');

-- 高优先级 HIGH
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001003,'BUS20260315003','TRANSFER',2200000.00,'USD','6222021234567890003','香港贸易有限公司','汇丰银行香港分行','HIGH',SYSDATE+2,NULL,'PENDING','PENDING',NULL,0,'跨境贸易结算','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',NULL,NULL,NULL,NULL);
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001004,'BUS20260315004','COLLECTION',430000.00,'CNY','6222021234567890004','深圳电子科技公司','招商银行深圳分行','HIGH',SYSDATE+3,NULL,'PENDING','PENDING',NULL,0,'货款回收','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',NULL,NULL,NULL,NULL);
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001005,'BUS20260314005','PAYMENT',980000.00,'EUR','6222021234567890005','德国汽车零部件公司','德意志银行法兰克福','HIGH',SYSDATE,NULL,'APPROVED','APPROVED',NULL,0,'进口零部件货款','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',1,'管理员',SYSDATE,'同意进口付款');

-- 中低优先级（用于 summary 统计）
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001006,'BUS20260316006','PAYMENT',52000.00,'CNY','6222021234567890006','广州物流有限公司','中国农业银行广州分行','MEDIUM',SYSDATE+2,NULL,'PENDING','DRAFT',NULL,0,'物流服务费结算','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',NULL,NULL,NULL,NULL);
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001007,'BUS20260316007','PAYMENT',76000.00,'CNY','6222021234567890007','武汉制造有限公司','交通银行武汉分行','MEDIUM',SYSDATE+2,NULL,'PENDING','PENDING',NULL,0,'原材料采购款','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',NULL,NULL,NULL,NULL);
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001008,'BUS20260316008','PAYMENT',230000.00,'CNY','6222021234567890008','西安能源股份公司','中国工商银行西安分行','MEDIUM',SYSDATE+3,NULL,'PROCESSING','APPROVED',NULL,0,'能源采购结算','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',1,'管理员',SYSDATE,'同意采购');
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001009,'BUS20260315009','PAYMENT',125000.00,'CNY','6222021234567890009','杭州互联网公司','浙商银行杭州分行','LOW',SYSDATE-1,SYSDATE-1,'SETTLED','APPROVED',NULL,0,'技术服务费','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',1,'管理员',SYSDATE,'同意支付');
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001010,'BUS20260315010','TRANSFER',560000.00,'CNY','6222021234567890010','南京金融控股公司','中国建设银行南京分行','HIGH',SYSDATE-2,SYSDATE-2,'SETTLED','APPROVED',NULL,0,'子公司资金归集','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',1,'管理员',SYSDATE,'同意归集');
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001011,'BUS20260316011','PAYMENT',38000.00,'CNY','6222021234567890011','天津物资贸易公司','中国农业银行天津分行','LOW',SYSDATE+5,NULL,'PENDING','DRAFT',NULL,0,'办公用品采购','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',NULL,NULL,NULL,NULL);
INSERT INTO TBL_PENDING_DATA(PENDING_ID,BUSINESS_NO,BUSINESS_TYPE,SETTLEMENT_AMOUNT,CURRENCY_CODE,COUNTERPARTY_ACCOUNT,COUNTERPARTY_NAME,COUNTERPARTY_BANK,PRIORITY,EXPECTED_SETTLEMENT_DATE,ACTUAL_SETTLEMENT_DATE,SETTLEMENT_STATUS,APPROVAL_STATUS,FAILURE_REASON,RETRY_COUNT,BUSINESS_DESCRIPTION,ATTACHMENT_PATH,REMARK,DELETE_FLAG,CREATE_BY,CREATE_BY_NAME,CREATE_TIME,UPDATE_BY,UPDATE_BY_NAME,UPDATE_TIME,ORG_ID,ORG_NAME,APPROVAL_BY,APPROVAL_BY_NAME,APPROVAL_TIME,APPROVAL_OPINION)
VALUES(1001000000001012,'BUS20260316012','PAYMENT',980000.00,'CNY','6222021234567890012','成都建设集团公司','中国银行成都分行','HIGH',SYSDATE,NULL,'FAILED','APPROVED','银行接口超时，请重试',2,'工程款结算','',NULL,0,1,'管理员',SYSDATE,1,'管理员',SYSDATE,1000,'国务院国有资产监督管理委员会',1,'管理员',SYSDATE,'同意付款');

COMMIT;

-- ============================================================
-- 2. TBL_SETTLEMENT_EXCEPTION 结算异常（ORG_ID=1000）
-- 列：EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_LEVEL, EXCEPTION_TYPE,
--     ERROR_MESSAGE, EXCEPTION_STATUS, ASSIGNEE, ASSIGNEE_NAME,
--     RESOLVE_NOTES, RESOLVE_TIME, ESCALATION_LEVEL, RELATED_BUSINESS_NO,
--     RELATED_BATCH_ID, REMARK, CREATE_TIME, UPDATE_TIME,
--     CREATE_USER, UPDATE_USER, ORG_ID, DELETE_FLAG
-- ============================================================

-- CRITICAL 级别（会被 /exception/critical 接口查到，状态需为 OPEN 或 ASSIGNED）
INSERT INTO TBL_SETTLEMENT_EXCEPTION(EXCEPTION_ID,EXCEPTION_NO,EXCEPTION_LEVEL,EXCEPTION_TYPE,ERROR_MESSAGE,EXCEPTION_STATUS,ASSIGNEE,ASSIGNEE_NAME,RESOLVE_NOTES,RESOLVE_TIME,ESCALATION_LEVEL,RELATED_BUSINESS_NO,RELATED_BATCH_ID,REMARK,CREATE_TIME,UPDATE_TIME,CREATE_USER,UPDATE_USER,ORG_ID,DELETE_FLAG)
VALUES(4001000000001001,'EXCP-1000-001','CRITICAL','BANK_CONNECTION_FAILED','银行接口连接超时，工商银行支付通道不可用','PENDING',NULL,NULL,NULL,NULL,0,'BUS20260316001',NULL,'需紧急处理',SYSDATE,SYSDATE,'admin','admin',1000,0);
INSERT INTO TBL_SETTLEMENT_EXCEPTION(EXCEPTION_ID,EXCEPTION_NO,EXCEPTION_LEVEL,EXCEPTION_TYPE,ERROR_MESSAGE,EXCEPTION_STATUS,ASSIGNEE,ASSIGNEE_NAME,RESOLVE_NOTES,RESOLVE_TIME,ESCALATION_LEVEL,RELATED_BUSINESS_NO,RELATED_BATCH_ID,REMARK,CREATE_TIME,UPDATE_TIME,CREATE_USER,UPDATE_USER,ORG_ID,DELETE_FLAG)
VALUES(4001000000001002,'EXCP-1000-002','CRITICAL','AMOUNT_LIMIT_EXCEEDED','结算金额超出单笔限额，交易被拒绝','ASSIGNED','zhangsan','张三',NULL,NULL,1,'BUS20260316002',NULL,'已分配处理人',SYSDATE,SYSDATE,'admin','admin',1000,0);
INSERT INTO TBL_SETTLEMENT_EXCEPTION(EXCEPTION_ID,EXCEPTION_NO,EXCEPTION_LEVEL,EXCEPTION_TYPE,ERROR_MESSAGE,EXCEPTION_STATUS,ASSIGNEE,ASSIGNEE_NAME,RESOLVE_NOTES,RESOLVE_TIME,ESCALATION_LEVEL,RELATED_BUSINESS_NO,RELATED_BATCH_ID,REMARK,CREATE_TIME,UPDATE_TIME,CREATE_USER,UPDATE_USER,ORG_ID,DELETE_FLAG)
VALUES(4001000000001003,'EXCP-1000-003','CRITICAL','SYSTEM_UNAVAILABLE','核心系统响应异常，结算服务不可用','PENDING',NULL,NULL,NULL,NULL,2,'BUS20260315003',NULL,'系统级故障，需立即处理',SYSDATE,SYSDATE,'admin','admin',1000,0);
INSERT INTO TBL_SETTLEMENT_EXCEPTION(EXCEPTION_ID,EXCEPTION_NO,EXCEPTION_LEVEL,EXCEPTION_TYPE,ERROR_MESSAGE,EXCEPTION_STATUS,ASSIGNEE,ASSIGNEE_NAME,RESOLVE_NOTES,RESOLVE_TIME,ESCALATION_LEVEL,RELATED_BUSINESS_NO,RELATED_BATCH_ID,REMARK,CREATE_TIME,UPDATE_TIME,CREATE_USER,UPDATE_USER,ORG_ID,DELETE_FLAG)
VALUES(4001000000001004,'EXCP-1000-004','CRITICAL','CERTIFICATE_EXPIRING','数字证书即将过期，银企联通道存在中断风险','PENDING',NULL,NULL,NULL,NULL,1,'BUS20260315004',NULL,'证书有效期剩余3天',SYSDATE,SYSDATE,'admin','admin',1000,0);

-- HIGH 级别
INSERT INTO TBL_SETTLEMENT_EXCEPTION(EXCEPTION_ID,EXCEPTION_NO,EXCEPTION_LEVEL,EXCEPTION_TYPE,ERROR_MESSAGE,EXCEPTION_STATUS,ASSIGNEE,ASSIGNEE_NAME,RESOLVE_NOTES,RESOLVE_TIME,ESCALATION_LEVEL,RELATED_BUSINESS_NO,RELATED_BATCH_ID,REMARK,CREATE_TIME,UPDATE_TIME,CREATE_USER,UPDATE_USER,ORG_ID,DELETE_FLAG)
VALUES(4001000000001005,'EXCP-1000-005','HIGH','ACCOUNT_INVALID','收款账号验证失败，账号格式不正确','PENDING',NULL,NULL,NULL,NULL,0,'BUS20260314005',NULL,NULL,SYSDATE,SYSDATE,'admin','admin',1000,0);
INSERT INTO TBL_SETTLEMENT_EXCEPTION(EXCEPTION_ID,EXCEPTION_NO,EXCEPTION_LEVEL,EXCEPTION_TYPE,ERROR_MESSAGE,EXCEPTION_STATUS,ASSIGNEE,ASSIGNEE_NAME,RESOLVE_NOTES,RESOLVE_TIME,ESCALATION_LEVEL,RELATED_BUSINESS_NO,RELATED_BATCH_ID,REMARK,CREATE_TIME,UPDATE_TIME,CREATE_USER,UPDATE_USER,ORG_ID,DELETE_FLAG)
VALUES(4001000000001006,'EXCP-1000-006','HIGH','INSUFFICIENT_BALANCE','资金账户余额不足，结算失败','ASSIGNED','lisi','李四',NULL,NULL,0,'BUS20260316006',NULL,'需补充资金',SYSDATE,SYSDATE,'admin','admin',1000,0);
INSERT INTO TBL_SETTLEMENT_EXCEPTION(EXCEPTION_ID,EXCEPTION_NO,EXCEPTION_LEVEL,EXCEPTION_TYPE,ERROR_MESSAGE,EXCEPTION_STATUS,ASSIGNEE,ASSIGNEE_NAME,RESOLVE_NOTES,RESOLVE_TIME,ESCALATION_LEVEL,RELATED_BUSINESS_NO,RELATED_BATCH_ID,REMARK,CREATE_TIME,UPDATE_TIME,CREATE_USER,UPDATE_USER,ORG_ID,DELETE_FLAG)
VALUES(4001000000001007,'EXCP-1000-007','HIGH','DUPLICATE_TRANSACTION','重复提交检测，该笔业务已存在处理记录','PENDING',NULL,NULL,NULL,NULL,0,'BUS20260316007',NULL,'疑似重复提交',SYSDATE,SYSDATE,'admin','admin',1000,0);

-- MEDIUM 级别
INSERT INTO TBL_SETTLEMENT_EXCEPTION(EXCEPTION_ID,EXCEPTION_NO,EXCEPTION_LEVEL,EXCEPTION_TYPE,ERROR_MESSAGE,EXCEPTION_STATUS,ASSIGNEE,ASSIGNEE_NAME,RESOLVE_NOTES,RESOLVE_TIME,ESCALATION_LEVEL,RELATED_BUSINESS_NO,RELATED_BATCH_ID,REMARK,CREATE_TIME,UPDATE_TIME,CREATE_USER,UPDATE_USER,ORG_ID,DELETE_FLAG)
VALUES(4001000000001008,'EXCP-1000-008','MEDIUM','EXCHANGE_RATE_FAILED','汇率获取失败，使用默认汇率处理','PENDING',NULL,NULL,NULL,NULL,0,'BUS20260316008',NULL,NULL,SYSDATE,SYSDATE,'admin','admin',1000,0);
INSERT INTO TBL_SETTLEMENT_EXCEPTION(EXCEPTION_ID,EXCEPTION_NO,EXCEPTION_LEVEL,EXCEPTION_TYPE,ERROR_MESSAGE,EXCEPTION_STATUS,ASSIGNEE,ASSIGNEE_NAME,RESOLVE_NOTES,RESOLVE_TIME,ESCALATION_LEVEL,RELATED_BUSINESS_NO,RELATED_BATCH_ID,REMARK,CREATE_TIME,UPDATE_TIME,CREATE_USER,UPDATE_USER,ORG_ID,DELETE_FLAG)
VALUES(4001000000001009,'EXCP-1000-009','MEDIUM','APPROVAL_TIMEOUT','审批流程超时，等待审批人响应超过24小时','ASSIGNED','wangwu','王五',NULL,NULL,0,'BUS20260315009',NULL,'催促审批人处理',SYSDATE,SYSDATE,'admin','admin',1000,0);

-- LOW 级别（已解决）
INSERT INTO TBL_SETTLEMENT_EXCEPTION(EXCEPTION_ID,EXCEPTION_NO,EXCEPTION_LEVEL,EXCEPTION_TYPE,ERROR_MESSAGE,EXCEPTION_STATUS,ASSIGNEE,ASSIGNEE_NAME,RESOLVE_NOTES,RESOLVE_TIME,ESCALATION_LEVEL,RELATED_BUSINESS_NO,RELATED_BATCH_ID,REMARK,CREATE_TIME,UPDATE_TIME,CREATE_USER,UPDATE_USER,ORG_ID,DELETE_FLAG)
VALUES(4001000000001010,'EXCP-1000-010','LOW','NON_WORKING_DAY','结算日期为非工作日，自动顺延至下一工作日','RESOLVED',NULL,NULL,'已自动顺延至下一工作日',SYSDATE,0,'BUS20260315010',NULL,NULL,SYSDATE,SYSDATE,'admin','admin',1000,0);

COMMIT;

