-- =============================================
-- 快速修复：数据源配置测试数据
-- 表名: TC_DATA_SOURCE_CONFIG
-- 用途: 快速插入测试数据解决"数据源配置不存在"问题
-- 执行时间: < 1分钟
-- =============================================

-- 步骤1: 检查表是否存在
SELECT COUNT(*) AS TABLE_EXISTS FROM USER_TABLES WHERE TABLE_NAME = 'TC_DATA_SOURCE_CONFIG';

-- 步骤2: 清理可能存在的测试数据
DELETE FROM TC_DATA_SOURCE_CONFIG WHERE SOURCE_CODE LIKE 'QUICK_TEST_%';

-- 步骤3: 插入3条简单的测试数据

-- 数据源1: MySQL测试数据源
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    LAST_TEST_TIME, IS_ENABLED, IS_ACTIVE, STATUS, REMARK,
    CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130001', 'QUICK_TEST_MYSQL', 'MySQL测试数据源', 'MYSQL', 'DATABASE',
    'jdbc:mysql://localhost:3306/test', 'root', '******', 'DEV', 'NORMAL',
    CURRENT_TIMESTAMP, '1', '1', '1', '快速测试数据-MySQL',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin', 1
);

-- 数据源2: Oracle测试数据源
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    LAST_TEST_TIME, IS_ENABLED, IS_ACTIVE, STATUS, REMARK,
    CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130002', 'QUICK_TEST_ORACLE', 'Oracle测试数据源', 'ORACLE', 'DATABASE',
    'jdbc:oracle:thin:@localhost:1521:ORCL', 'system', '******', 'TEST', 'NORMAL',
    CURRENT_TIMESTAMP, '1', '1', '1', '快速测试数据-Oracle',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin', 1
);

-- 数据源3: 达梦测试数据源
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    LAST_TEST_TIME, IS_ENABLED, IS_ACTIVE, STATUS, REMARK,
    CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130003', 'QUICK_TEST_DAMENG', '达梦测试数据源', 'DAMENG', 'DATABASE',
    'jdbc:dm://localhost:5236', 'SYSDBA', '******', 'PROD', 'NORMAL',
    CURRENT_TIMESTAMP, '1', '1', '1', '快速测试数据-达梦',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin', 1
);

-- 数据源4: API接口数据源
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    LAST_TEST_TIME, IS_ENABLED, IS_ACTIVE, STATUS, REMARK,
    CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130004', 'QUICK_TEST_API', '第三方API接口', 'API', 'API',
    'https://api.example.com/v1', 'api_user', 'api_key_******', 'PROD', 'NORMAL',
    CURRENT_TIMESTAMP, '1', '1', '1', '快速测试数据-API',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin', 1
);

-- 数据源5: Redis缓存数据源
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    LAST_TEST_TIME, IS_ENABLED, IS_ACTIVE, STATUS, REMARK,
    CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO
) VALUES (
    'DS20250130005', 'QUICK_TEST_REDIS', 'Redis缓存服务', 'REDIS', 'CACHE',
    'redis://localhost:6379', 'default', '******', 'DEV', 'NORMAL',
    CURRENT_TIMESTAMP, '1', '1', '1', '快速测试数据-Redis',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin', 1
);

-- 步骤4: 验证插入结果
SELECT 
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, ENVIRONMENT, 
    CONNECTION_STATUS, IS_ENABLED, STATUS, CREATE_TIME
FROM TC_DATA_SOURCE_CONFIG 
WHERE STATUS = '1'
ORDER BY CREATE_TIME DESC;

-- 步骤5: 统计数据
SELECT 
    '总数据源数' AS METRIC, COUNT(*) AS VALUE FROM TC_DATA_SOURCE_CONFIG WHERE STATUS = '1'
UNION ALL
SELECT 
    '启用数据源数', COUNT(*) FROM TC_DATA_SOURCE_CONFIG WHERE IS_ENABLED = '1' AND STATUS = '1'
UNION ALL
SELECT 
    '正常连接数', COUNT(*) FROM TC_DATA_SOURCE_CONFIG WHERE CONNECTION_STATUS = 'NORMAL' AND STATUS = '1';

-- =============================================
-- 执行完成后的验证步骤：
-- 1. 重启后端服务
-- 2. 访问前端页面测试
-- 3. 检查是否能正常显示数据列表
-- =============================================

