-- =====================================================
-- 印鉴管理模块数据库表 - 达梦数据库DM8兼容版本
-- 生成日期: 2025-12-25
-- 作者: 华博云开发团队
-- 数据库: 达梦数据库 DM8
-- =====================================================

-- =====================================================
-- 表1: 印鉴组合配置表
-- 功能: 管理印鉴组合使用规则,包括组合类型、使用场景、权限控制和审批流程
-- =====================================================

-- 创建表
CREATE TABLE TBL_SEAL_COMBINATION (
    COMBINATION_ID VARCHAR(32) NOT NULL PRIMARY KEY,
    COMBINATION_CODE VARCHAR(50) NOT NULL UNIQUE,
    COMBINATION_NAME VARCHAR(100) NOT NULL,
    COMBINATION_TYPE VARCHAR(20) NOT NULL,
    BUSINESS_TYPE VARCHAR(50),
    AUTHORITY_LEVEL VARCHAR(20),
    MAX_AMOUNT_LIMIT DECIMAL(18,2),
    USAGE_COUNT INTEGER DEFAULT 0,
    IS_ENABLED INTEGER DEFAULT 1,
    DESCRIPTION VARCHAR(500),
    ORG_ID VARCHAR(32),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
    UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50)
);

-- 表注释
COMMENT ON TABLE TBL_SEAL_COMBINATION IS '印鉴组合配置表';

-- 字段注释
COMMENT ON COLUMN TBL_SEAL_COMBINATION.COMBINATION_ID IS '组合ID(主键)';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.COMBINATION_CODE IS '组合编码(唯一)';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.COMBINATION_NAME IS '组合名称';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.COMBINATION_TYPE IS '组合类型(SINGLE_SEAL-单印章,DUAL_SEAL-双印章,MULTI_SEAL-多印章)';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.BUSINESS_TYPE IS '业务类型(FUND_TRANSFER-资金划转,INVESTMENT_TRANSACTION-投资交易,CONTRACT_SIGNING-合同签署)';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.AUTHORITY_LEVEL IS '权限级别(LEVEL_1-一级,LEVEL_2-二级,LEVEL_3-三级)';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.MAX_AMOUNT_LIMIT IS '最大金额限制';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.USAGE_COUNT IS '使用次数';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.IS_ENABLED IS '是否启用(1-启用,0-禁用)';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.DESCRIPTION IS '描述';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.ORG_ID IS '组织ID';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.CREATE_USER IS '创建用户';
COMMENT ON COLUMN TBL_SEAL_COMBINATION.UPDATE_USER IS '更新用户';

-- 创建索引
CREATE INDEX IDX_SEAL_COMB_CODE ON TBL_SEAL_COMBINATION(COMBINATION_CODE);
CREATE INDEX IDX_SEAL_COMB_TYPE ON TBL_SEAL_COMBINATION(COMBINATION_TYPE);
CREATE INDEX IDX_SEAL_COMB_BTYPE ON TBL_SEAL_COMBINATION(BUSINESS_TYPE);
CREATE INDEX IDX_SEAL_COMB_ORG ON TBL_SEAL_COMBINATION(ORG_ID);

-- =====================================================
-- 表2: 印鉴类型表
-- 功能: 管理企业印鉴类型配置,包括公章、财务章、法人章等
-- =====================================================

-- 创建表
CREATE TABLE TBL_SEAL_TYPE (
    TYPE_ID VARCHAR(32) NOT NULL PRIMARY KEY,
    TYPE_CODE VARCHAR(50) NOT NULL UNIQUE,
    TYPE_NAME VARCHAR(100) NOT NULL,
    SEAL_LEVEL INTEGER NOT NULL,
    SCOPE VARCHAR(100),
    DESCRIPTION VARCHAR(500),
    STATUS INTEGER DEFAULT 1,
    SORT_ORDER INTEGER DEFAULT 0,
    ORG_ID VARCHAR(32),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
    UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50)
);

-- 表注释
COMMENT ON TABLE TBL_SEAL_TYPE IS '印鉴类型表';

-- 字段注释
COMMENT ON COLUMN TBL_SEAL_TYPE.TYPE_ID IS '类型ID(主键)';
COMMENT ON COLUMN TBL_SEAL_TYPE.TYPE_CODE IS '类型编码(唯一)';
COMMENT ON COLUMN TBL_SEAL_TYPE.TYPE_NAME IS '类型名称';
COMMENT ON COLUMN TBL_SEAL_TYPE.SEAL_LEVEL IS '印鉴级别(1-一级印鉴,2-二级印鉴,3-三级印鉴)';
COMMENT ON COLUMN TBL_SEAL_TYPE.SCOPE IS '适用范围';
COMMENT ON COLUMN TBL_SEAL_TYPE.DESCRIPTION IS '描述';
COMMENT ON COLUMN TBL_SEAL_TYPE.STATUS IS '状态(1-启用,0-禁用)';
COMMENT ON COLUMN TBL_SEAL_TYPE.SORT_ORDER IS '排序号';
COMMENT ON COLUMN TBL_SEAL_TYPE.ORG_ID IS '组织ID';
COMMENT ON COLUMN TBL_SEAL_TYPE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_SEAL_TYPE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_SEAL_TYPE.CREATE_USER IS '创建用户';
COMMENT ON COLUMN TBL_SEAL_TYPE.UPDATE_USER IS '更新用户';

-- 创建索引
CREATE INDEX IDX_SEAL_TYPE_CODE ON TBL_SEAL_TYPE(TYPE_CODE);
CREATE INDEX IDX_SEAL_TYPE_LEVEL ON TBL_SEAL_TYPE(SEAL_LEVEL);
CREATE INDEX IDX_SEAL_TYPE_STATUS ON TBL_SEAL_TYPE(STATUS);
CREATE INDEX IDX_SEAL_TYPE_ORG ON TBL_SEAL_TYPE(ORG_ID);

-- =====================================================
-- 表3: 印鉴使用记录表
-- 功能: 记录印鉴使用情况,包括使用时间、使用人员、业务场景和审批状态
-- =====================================================

-- 创建表
CREATE TABLE TBL_SEAL_USAGE_RECORD (
    RECORD_ID VARCHAR(32) NOT NULL PRIMARY KEY,
    RECORD_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    SEAL_ID VARCHAR(32) NOT NULL,
    SEAL_CODE VARCHAR(50),
    SEAL_NAME VARCHAR(100),
    OPERATOR_ID VARCHAR(32) NOT NULL,
    OPERATOR_NAME VARCHAR(50) NOT NULL,
    BUSINESS_TYPE VARCHAR(50),
    BUSINESS_NUMBER VARCHAR(100),
    USAGE_AMOUNT DECIMAL(18,2),
    USAGE_TIME TIMESTAMP NOT NULL,
    USAGE_STATUS VARCHAR(20) NOT NULL,
    REMARK VARCHAR(500),
    ORG_ID VARCHAR(32),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
    UPDATE_TIME TIMESTAMP DEFAULT SYSDATE
);

-- 表注释
COMMENT ON TABLE TBL_SEAL_USAGE_RECORD IS '印鉴使用记录表';

-- 字段注释
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.RECORD_ID IS '记录ID(主键)';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.RECORD_NUMBER IS '记录编号(唯一)';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_ID IS '印鉴ID';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_CODE IS '印鉴编码';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_NAME IS '印鉴名称';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.OPERATOR_ID IS '操作人ID';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.OPERATOR_NAME IS '操作人姓名';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.BUSINESS_TYPE IS '业务类型(FUND_TRANSFER-资金划转,INVESTMENT_TRANSACTION-投资交易)';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.BUSINESS_NUMBER IS '业务编号';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_AMOUNT IS '使用金额';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_TIME IS '使用时间';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_STATUS IS '使用状态(SUCCESS-成功,FAILED-失败,PENDING-待处理,CANCELLED-已取消)';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.REMARK IS '备注';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.ORG_ID IS '组织ID';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.UPDATE_TIME IS '更新时间';

-- 创建索引
CREATE INDEX IDX_SEAL_USAGE_NUMBER ON TBL_SEAL_USAGE_RECORD(RECORD_NUMBER);
CREATE INDEX IDX_SEAL_USAGE_SEAL ON TBL_SEAL_USAGE_RECORD(SEAL_ID);
CREATE INDEX IDX_SEAL_USAGE_OPERATOR ON TBL_SEAL_USAGE_RECORD(OPERATOR_ID);
CREATE INDEX IDX_SEAL_USAGE_TIME ON TBL_SEAL_USAGE_RECORD(USAGE_TIME);
CREATE INDEX IDX_SEAL_USAGE_STATUS ON TBL_SEAL_USAGE_RECORD(USAGE_STATUS);
CREATE INDEX IDX_SEAL_USAGE_ORG ON TBL_SEAL_USAGE_RECORD(ORG_ID);

-- =====================================================
-- 测试数据
-- =====================================================

-- 印鉴类型测试数据
INSERT INTO TBL_SEAL_TYPE (TYPE_ID, TYPE_CODE, TYPE_NAME, SEAL_LEVEL, SCOPE, DESCRIPTION, STATUS, SORT_ORDER, ORG_ID, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
VALUES
('ST001', 'OFFICIAL_SEAL', '公章', 1, '通用', '公司正式公章,用于对外重要文件', 1, 1, 'ORG001', SYSDATE, SYSDATE, 'admin', 'admin'),
('ST002', 'FINANCE_SEAL', '财务章', 1, '财务业务', '财务专用章,用于财务相关业务', 1, 2, 'ORG001', SYSDATE, SYSDATE, 'admin', 'admin'),
('ST003', 'LEGAL_SEAL', '法人章', 1, '法律文件', '法定代表人专用章,用于法律文件', 1, 3, 'ORG001', SYSDATE, SYSDATE, 'admin', 'admin'),
('ST004', 'CONTRACT_SEAL', '合同章', 2, '合同签署', '合同专用章,用于合同签署', 1, 4, 'ORG001', SYSDATE, SYSDATE, 'admin', 'admin'),
('ST005', 'DEPARTMENT_SEAL', '部门章', 3, '部门内部', '部门内部使用印章', 1, 5, 'ORG001', SYSDATE, SYSDATE, 'admin', 'admin');

-- 印鉴组合配置测试数据
INSERT INTO TBL_SEAL_COMBINATION (COMBINATION_ID, COMBINATION_CODE, COMBINATION_NAME, COMBINATION_TYPE, BUSINESS_TYPE, AUTHORITY_LEVEL, MAX_AMOUNT_LIMIT, USAGE_COUNT, IS_ENABLED, DESCRIPTION, ORG_ID, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
VALUES
('SC001', 'COMB001', '公章+法人章组合', 'DUAL_SEAL', 'CONTRACT_SIGNING', 'LEVEL_2', 1000000, 15, 1, '用于合同签署,需要公章和法人章同时使用', 'ORG001', SYSDATE, SYSDATE, 'admin', 'admin'),
('SC002', 'COMB002', '财务章+法人章组合', 'DUAL_SEAL', 'FUND_TRANSFER', 'LEVEL_2', 500000, 28, 1, '用于资金划转,需要财务章和法人章同时使用', 'ORG001', SYSDATE, SYSDATE, 'admin', 'admin'),
('SC003', 'COMB003', '单公章使用', 'SINGLE_SEAL', 'INVESTMENT_TRANSACTION', 'LEVEL_3', 100000, 45, 1, '单公章使用,用于小额投资交易', 'ORG001', SYSDATE, SYSDATE, 'admin', 'admin');

-- 印鉴使用记录测试数据
INSERT INTO TBL_SEAL_USAGE_RECORD (RECORD_ID, RECORD_NUMBER, SEAL_ID, SEAL_CODE, SEAL_NAME, OPERATOR_ID, OPERATOR_NAME, BUSINESS_TYPE, BUSINESS_NUMBER, USAGE_AMOUNT, USAGE_TIME, USAGE_STATUS, REMARK, ORG_ID, CREATE_TIME, UPDATE_TIME)
VALUES
('REC001', 'REC20240101001', 'SEAL001', 'YZGZ2024001', '华博云科技有限公司公章', 'U001', '张伟', 'FUND_TRANSFER', 'BIZ20240101001', 50000, TO_DATE('2024-01-01 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'SUCCESS', '资金划转使用', 'ORG001', SYSDATE, SYSDATE),
('REC002', 'REC20240101002', 'SEAL002', 'YZCW2024001', '华博云科技有限公司财务章', 'U002', '李娜', 'FUND_TRANSFER', 'BIZ20240101002', 80000, TO_DATE('2024-01-01 14:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'SUCCESS', '资金划转使用', 'ORG001', SYSDATE, SYSDATE),
('REC003', 'REC20240101003', 'SEAL001', 'YZGZ2024001', '华博云科技有限公司公章', 'U003', '王强', 'CONTRACT_SIGNING', 'BIZ20240101003', NULL, TO_DATE('2024-01-01 16:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'SUCCESS', '合同签署使用', 'ORG001', SYSDATE, SYSDATE),
('REC004', 'REC20240102001', 'SEAL003', 'YZFR2024001', '华博云科技有限公司法人章', 'U001', '张伟', 'INVESTMENT_TRANSACTION', 'BIZ20240102001', 120000, TO_DATE('2024-01-02 09:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'PENDING', '投资交易使用', 'ORG001', SYSDATE, SYSDATE);

COMMIT;
