-- 现金流类型管理表
CREATE TABLE TBL_CASHFLOW_TYPE (
    CASHFLOW_TYPE_ID VARCHAR2(64) PRIMARY KEY,
    CASHFLOW_TYPE_CODE VARCHAR2(50) NOT NULL UNIQUE,
    CASHFLOW_TYPE_NAME VARCHAR2(100) NOT NULL,
    CASHFLOW_DIRECTION VARCHAR2(20) NOT NULL CHECK (CASHFLOW_DIRECTION IN ('INFLOW', 'OUTFLOW', 'BOTH')),
    BUSINESS_CATEGORY VARCHAR2(50),
    IMPACT_TYPE VARCHAR2(20) CHECK (IMPACT_TYPE IN ('DIRECT', 'INDIRECT')),
    ACCOUNTING_SUBJECT VARCHAR2(50),
    FORECAST_WEIGHT NUMBER(5,2) DEFAULT 0.00,
    DESCRIPTION VARCHAR2(500),
    PARENT_ID VARCHAR2(64),
    IS_ENABLED NUMBER(1) DEFAULT 1 CHECK (IS_ENABLED IN (0, 1)),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR2(50),
    UPDATE_USER VARCHAR2(50)
);

-- 添加索引
CREATE INDEX IDX_CASHFLOW_CODE ON TBL_CASHFLOW_TYPE(CASHFLOW_TYPE_CODE);
CREATE INDEX IDX_CASHFLOW_DIRECTION ON TBL_CASHFLOW_TYPE(CASHFLOW_DIRECTION);
CREATE INDEX IDX_CASHFLOW_PARENT ON TBL_CASHFLOW_TYPE(PARENT_ID);
CREATE INDEX IDX_CASHFLOW_ENABLED ON TBL_CASHFLOW_TYPE(IS_ENABLED);

-- 添加外键约束（自关联）
ALTER TABLE TBL_CASHFLOW_TYPE ADD CONSTRAINT FK_CASHFLOW_PARENT
FOREIGN KEY (PARENT_ID) REFERENCES TBL_CASHFLOW_TYPE(CASHFLOW_TYPE_ID);

-- 插入初始数据
INSERT INTO TBL_CASHFLOW_TYPE (
    CASHFLOW_TYPE_ID,
    CASHFLOW_TYPE_CODE,
    CASHFLOW_TYPE_NAME,
    CASHFLOW_DIRECTION,
    BUSINESS_CATEGORY,
    IMPACT_TYPE,
    ACCOUNTING_SUBJECT,
    FORECAST_WEIGHT,
    DESCRIPTION,
    IS_ENABLED,
    CREATE_USER
) VALUES (
    SYS_GUID(),
    'CF_INVEST_PURCHASE',
    '投资申购现金流',
    'OUTFLOW',
    'INVESTING',
    'DIRECT',
    '1503',
    85.5,
    '投资产品申购产生的现金流出',
    1,
    'SYSTEM'
);

INSERT INTO TBL_CASHFLOW_TYPE (
    CASHFLOW_TYPE_ID,
    CASHFLOW_TYPE_CODE,
    CASHFLOW_TYPE_NAME,
    CASHFLOW_DIRECTION,
    BUSINESS_CATEGORY,
    IMPACT_TYPE,
    ACCOUNTING_SUBJECT,
    FORECAST_WEIGHT,
    DESCRIPTION,
    IS_ENABLED,
    CREATE_USER
) VALUES (
    SYS_GUID(),
    'CF_INVEST_REDEMPTION',
    '投资赎回现金流',
    'INFLOW',
    'INVESTING',
    'DIRECT',
    '1101',
    90.2,
    '投资产品赎回产生的现金流入',
    1,
    'SYSTEM'
);

INSERT INTO TBL_CASHFLOW_TYPE (
    CASHFLOW_TYPE_ID,
    CASHFLOW_TYPE_CODE,
    CASHFLOW_TYPE_NAME,
    CASHFLOW_DIRECTION,
    BUSINESS_CATEGORY,
    IMPACT_TYPE,
    ACCOUNTING_SUBJECT,
    FORECAST_WEIGHT,
    DESCRIPTION,
    IS_ENABLED,
    CREATE_USER
) VALUES (
    SYS_GUID(),
    'CF_INTEREST_INCOME',
    '利息收入现金流',
    'INFLOW',
    'INVESTING',
    'DIRECT',
    '6051',
    95.8,
    '投资产品利息收入产生的现金流入',
    1,
    'SYSTEM'
);