-- ============================================
-- 用户表格配置表 - 达梦数据库建表脚本
-- 兼容达梦数据库 DM8
-- 创建日期: 2025-12-25
-- ============================================

-- 用户表格配置表
CREATE TABLE TBL_USER_TABLE_CONFIG (
    CONFIG_ID VARCHAR2(50) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    TABLE_NAME VARCHAR2(100) NOT NULL,
    COLUMN_CONFIG VARCHAR2(2000),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TBL_USER_TABLE_CONFIG PRIMARY KEY (CONFIG_ID)
);

-- 表注释
COMMENT ON TABLE TBL_USER_TABLE_CONFIG IS '用户表格列显示配置表';
COMMENT ON COLUMN TBL_USER_TABLE_CONFIG.CONFIG_ID IS '配置ID,主键';
COMMENT ON COLUMN TBL_USER_TABLE_CONFIG.USER_ID IS '用户ID';
COMMENT ON COLUMN TBL_USER_TABLE_CONFIG.TABLE_NAME IS '表名/页面标识';
COMMENT ON COLUMN TBL_USER_TABLE_CONFIG.COLUMN_CONFIG IS '列配置(JSON格式)';
COMMENT ON COLUMN TBL_USER_TABLE_CONFIG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_USER_TABLE_CONFIG.UPDATE_TIME IS '更新时间';

-- 创建索引
CREATE INDEX IDX_USER_TABLE_USER_ID ON TBL_USER_TABLE_CONFIG(USER_ID);
CREATE INDEX IDX_USER_TABLE_NAME ON TBL_USER_TABLE_CONFIG(TABLE_NAME);

-- 插入测试数据
INSERT INTO TBL_USER_TABLE_CONFIG (
    CONFIG_ID, USER_ID, TABLE_NAME, COLUMN_CONFIG
)
SELECT
    'CFG001', 'admin', 'SealArchiveManage',
    '["sealCode","sealName","ownerName","effectiveDate","expireDate","status"]'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TBL_USER_TABLE_CONFIG WHERE CONFIG_ID = 'CFG001');

COMMIT;
