-- =============================================
-- 监管分析表创建脚本
-- 表名: TBL_REGULATORY_ANALYSIS
-- 描述: 存储跨境资金、大额交易、高频交易、合规检查等监管分析数据
-- 数据库: 达梦数据库 (DM Database)
-- 创建日期: 2026-01-20
-- =============================================

-- 删除已存在的表（如果需要）
-- DROP TABLE IF EXISTS TBL_REGULATORY_ANALYSIS;

-- 创建监管分析表
CREATE TABLE TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    ANALYSIS_NO VARCHAR(50) NOT NULL,
    ANALYSIS_NAME VARCHAR(200),
    ANALYSIS_TYPE VARCHAR(50),
    POOL_ID VARCHAR(64),
    COMPANY_ID VARCHAR(64),
    COMPANY_NAME VARCHAR(200),
    ANALYSIS_DATE TIMESTAMP,
    COMPLIANCE_STATUS VARCHAR(50),
    RISK_LEVEL VARCHAR(20),
    TOTAL_AMOUNT DECIMAL(20,2),
    CROSS_BORDER_AMOUNT DECIMAL(20,2),
    DOMESTIC_AMOUNT DECIMAL(20,2),
    VIOLATION_COUNT INTEGER DEFAULT 0,
    WARNING_COUNT INTEGER DEFAULT 0,
    ANALYSIS_RESULT CLOB,
    RECOMMENDATIONS CLOB,
    REPORT_FILE_PATH VARCHAR(500),
    ANALYSIS_STATUS VARCHAR(20),
    GENERATE_TIME TIMESTAMP,
    GENERATE_BY VARCHAR(100),
    REVIEW_TIME TIMESTAMP,
    REVIEW_BY VARCHAR(100),
    REVIEW_REMARK VARCHAR(1000),
    REMARK VARCHAR(1000),
    CREATE_BY VARCHAR(100),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(100),
    UPDATE_TIME TIMESTAMP,
    DEL_FLAG VARCHAR(10) DEFAULT '0'
);

-- 创建索引
CREATE INDEX IDX_ANALYSIS_NO ON TBL_REGULATORY_ANALYSIS(ANALYSIS_NO);
CREATE INDEX IDX_ANALYSIS_TYPE ON TBL_REGULATORY_ANALYSIS(ANALYSIS_TYPE);
CREATE INDEX IDX_ANALYSIS_DATE ON TBL_REGULATORY_ANALYSIS(ANALYSIS_DATE);
CREATE INDEX IDX_COMPLIANCE_STATUS ON TBL_REGULATORY_ANALYSIS(COMPLIANCE_STATUS);
CREATE INDEX IDX_RISK_LEVEL ON TBL_REGULATORY_ANALYSIS(RISK_LEVEL);
CREATE INDEX IDX_COMPANY_ID ON TBL_REGULATORY_ANALYSIS(COMPANY_ID);
CREATE INDEX IDX_ANALYSIS_STATUS ON TBL_REGULATORY_ANALYSIS(ANALYSIS_STATUS);
CREATE INDEX IDX_CREATE_TIME ON TBL_REGULATORY_ANALYSIS(CREATE_TIME);

-- 添加表注释
COMMENT ON TABLE TBL_REGULATORY_ANALYSIS IS '监管分析表';

-- =============================================
-- 插入测试数据
-- =============================================

-- 测试数据1: 跨境资金分析 - 合规 - 低风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA001', 'RA202601001', '2026年1月跨境资金分析', 'CROSS_BORDER',
    'POOL001', 'COMP001', '华博集团有限公司', TO_DATE('2026-01-20', 'YYYY-MM-DD'),
    'COMPLIANT', 'LOW', 50000000.00,
    15000000.00, 35000000.00,
    0, 2,
    '跨境资金流动符合外汇管理规定，未发现违规操作。所有跨境交易均已按规定申报。',
    '继续保持合规操作，定期关注外汇政策变化',
    '/reports/regulatory/RA202601001.pdf', 'COMPLETED',
    TO_DATE('2026-01-20 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    TO_DATE('2026-01-20 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '审核通过',
    '月度例行分析', 'system', TO_DATE('2026-01-20 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据2: 大额交易分析 - 合规 - 中风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA002', 'RA202601002', '2026年1月大额交易分析', 'LARGE_AMOUNT',
    'POOL001', 'COMP002', '子公司A', TO_DATE('2026-01-20', 'YYYY-MM-DD'),
    'COMPLIANT', 'MEDIUM', 80000000.00,
    20000000.00, 60000000.00,
    0, 5,
    '大额交易均已按规定报备，发现5笔单笔超过500万的大额转账，均已正常履行报备程序。',
    '建议对大额交易加强内部审批流程，确保每笔交易都有完整的审批记录',
    '/reports/regulatory/RA202601002.pdf', 'COMPLETED',
    TO_DATE('2026-01-20 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    TO_DATE('2026-01-20 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '审核通过',
    '发现大额交易需要关注', 'system', TO_DATE('2026-01-20 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据3: 高频交易分析 - 待审核 - 高风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA003', 'RA202601003', '2026年1月高频交易分析', 'FREQUENCY',
    'POOL001', 'COMP003', '子公司B', TO_DATE('2026-01-20', 'YYYY-MM-DD'),
    'PENDING_REVIEW', 'HIGH', 120000000.00,
    30000000.00, 90000000.00,
    3, 15,
    '检测到3个账户存在频繁交易行为，单日内交易次数超过50次，累计交易金额1.2亿元。其中3笔交易可能涉及规避监管，需要进一步核查。',
    '立即开展专项调查，核实高频交易的真实用途和背景，如发现违规行为应及时上报监管部门',
    '/reports/regulatory/RA202601003.pdf', 'COMPLETED',
    TO_DATE('2026-01-20 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    NULL, NULL, NULL,
    '需要重点核查', 'system', TO_DATE('2026-01-20 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据4: 合规检查 - 合规 - 低风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA004', 'RA202601004', '2026年1月合规检查', 'COMPLIANCE',
    'POOL001', 'COMP001', '华博集团有限公司', TO_DATE('2026-01-19', 'YYYY-MM-DD'),
    'COMPLIANT', 'LOW', 65000000.00,
    18000000.00, 47000000.00,
    0, 1,
    '本月合规检查总体情况良好，各项监管指标均符合要求。发现1笔交易的报备时间略有延迟，但不影响整体合规性。',
    '加强内部培训，提高员工合规意识，确保所有交易及时准确报备',
    '/reports/regulatory/RA202601004.pdf', 'REVIEWED',
    TO_DATE('2026-01-19 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    TO_DATE('2026-01-20 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '审核通过，建议加强培训',
    '月度合规检查', 'system', TO_DATE('2026-01-19 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据5: 跨境资金分析 - 合规 - 中风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA005', 'RA202512001', '2025年12月跨境资金分析', 'CROSS_BORDER',
    'POOL001', 'COMP002', '子公司A', TO_DATE('2025-12-31', 'YYYY-MM-DD'),
    'COMPLIANT', 'MEDIUM', 45000000.00,
    12000000.00, 33000000.00,
    0, 4,
    '跨境资金流入流出基本平衡，符合业务实际情况。年末出现资金集中汇回情况，属于正常业务操作。',
    '建议合理规划跨境资金流动时间，避免年末集中操作',
    '/reports/regulatory/RA202512001.pdf', 'REVIEWED',
    TO_DATE('2025-12-31 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    TO_DATE('2026-01-03 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '审核通过',
    '年末专项分析', 'system', TO_DATE('2025-12-31 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据6: 大额交易分析 - 不合规 - 严重风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA006', 'RA202601005', '2026年1月大额交易异常分析', 'LARGE_AMOUNT',
    'POOL001', 'COMP003', '子公司B', TO_DATE('2026-01-18', 'YYYY-MM-DD'),
    'NON_COMPLIANT', 'CRITICAL', 200000000.00,
    50000000.00, 150000000.00,
    5, 20,
    '发现5笔大额交易未按规定报备，单笔金额均超过1000万，涉嫌规避监管。累计违规金额达2亿元，需要立即采取整改措施。',
    '立即停止相关账户的交易权限，开展全面内部调查，追究相关责任人责任，并向监管部门主动报告',
    '/reports/regulatory/RA202601005.pdf', 'COMPLETED',
    TO_DATE('2026-01-18 20:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    TO_DATE('2026-01-19 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '严重违规，需立即整改',
    '紧急处理', 'system', TO_DATE('2026-01-18 20:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据7: 高频交易分析 - 合规 - 中风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA007', 'RA202601006', '2026年1月高频交易监控', 'FREQUENCY',
    'POOL001', 'COMP001', '华博集团有限公司', TO_DATE('2026-01-17', 'YYYY-MM-DD'),
    'COMPLIANT', 'MEDIUM', 95000000.00,
    25000000.00, 70000000.00,
    0, 8,
    '监控到8个账户存在较高频率的交易行为，经核查均为正常业务往来，未发现违规操作。交易频率在合理范围内。',
    '持续关注高频交易账户，确保交易背景真实合法',
    '/reports/regulatory/RA202601006.pdf', 'REVIEWED',
    TO_DATE('2026-01-17 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    TO_DATE('2026-01-18 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '审核通过',
    '例行监控', 'system', TO_DATE('2026-01-17 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据8: 合规检查 - 待审核 - 高风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA008', 'RA202601007', '2026年1月合规专项检查', 'COMPLIANCE',
    'POOL001', 'COMP002', '子公司A', TO_DATE('2026-01-16', 'YYYY-MM-DD'),
    'PENDING_REVIEW', 'HIGH', 78000000.00,
    22000000.00, 56000000.00,
    2, 12,
    '专项检查发现2笔交易存在合规性问题，未完整保留交易凭证，不符合反洗钱要求。另有12笔交易的审批流程不够完善。',
    '立即完善交易凭证管理，加强内控制度执行，对相关人员进行再培训',
    '/reports/regulatory/RA202601007.pdf', 'COMPLETED',
    TO_DATE('2026-01-16 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    NULL, NULL, NULL,
    '专项检查发现问题', 'system', TO_DATE('2026-01-16 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据9: 跨境资金分析 - 合规 - 低风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA009', 'RA202511001', '2025年11月跨境资金分析', 'CROSS_BORDER',
    'POOL001', 'COMP003', '子公司B', TO_DATE('2025-11-30', 'YYYY-MM-DD'),
    'COMPLIANT', 'LOW', 38000000.00,
    10000000.00, 28000000.00,
    0, 1,
    '11月份跨境资金流动平稳，所有交易均符合外汇管理规定。资金用途清晰，报备完整。',
    '继续保持良好的合规操作，定期更新外汇政策知识',
    '/reports/regulatory/RA202511001.pdf', 'REVIEWED',
    TO_DATE('2025-11-30 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    TO_DATE('2025-12-02 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '审核通过',
    '月度分析', 'system', TO_DATE('2025-11-30 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据10: 大额交易分析 - 合规 - 低风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA010', 'RA202601008', '2026年1月大额交易监控报告', 'LARGE_AMOUNT',
    'POOL001', 'COMP001', '华博集团有限公司', TO_DATE('2026-01-15', 'YYYY-MM-DD'),
    'COMPLIANT', 'LOW', 55000000.00,
    15000000.00, 40000000.00,
    0, 3,
    '大额交易监控正常，本月监控到3笔单笔超过500万的交易，均已完成审批和报备程序，无违规情况。',
    '继续保持良好的大额交易管理机制',
    '/reports/regulatory/RA202601008.pdf', 'REVIEWED',
    TO_DATE('2026-01-15 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    TO_DATE('2026-01-16 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '审核通过',
    '例行监控', 'system', TO_DATE('2026-01-15 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据11: 综合监管分析 - 合规 - 中风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA011', 'RA202601009', '2025年度监管分析总结', 'COMPLIANCE',
    'POOL001', 'COMP001', '华博集团有限公司', TO_DATE('2025-12-31', 'YYYY-MM-DD'),
    'COMPLIANT', 'MEDIUM', 680000000.00,
    180000000.00, 500000000.00,
    5, 45,
    '2025年度整体合规情况良好，全年完成12次例行检查，发现5处轻微违规已全部整改。累计预警45次，均已妥善处理。',
    '2026年继续加强合规管理，重点关注跨境资金和大额交易，完善内控制度',
    '/reports/regulatory/RA202601009.pdf', 'REVIEWED',
    TO_DATE('2025-12-31 23:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    TO_DATE('2026-01-05 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '年度总结审核通过',
    '年度报告', 'system', TO_DATE('2025-12-31 23:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据12: 高频交易分析 - 不合规 - 严重风险
INSERT INTO TBL_REGULATORY_ANALYSIS (
    ANALYSIS_ID, ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE,
    POOL_ID, COMPANY_ID, COMPANY_NAME, ANALYSIS_DATE,
    COMPLIANCE_STATUS, RISK_LEVEL, TOTAL_AMOUNT,
    CROSS_BORDER_AMOUNT, DOMESTIC_AMOUNT,
    VIOLATION_COUNT, WARNING_COUNT,
    ANALYSIS_RESULT, RECOMMENDATIONS,
    REPORT_FILE_PATH, ANALYSIS_STATUS,
    GENERATE_TIME, GENERATE_BY,
    REVIEW_TIME, REVIEW_BY, REVIEW_REMARK,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'RA012', 'RA202601010', '异常高频交易调查', 'FREQUENCY',
    'POOL001', 'COMP003', '子公司B', TO_DATE('2026-01-14', 'YYYY-MM-DD'),
    'NON_COMPLIANT', 'CRITICAL', 150000000.00,
    40000000.00, 110000000.00,
    8, 30,
    '发现某账户在短时间内进行大量小额高频交易，涉嫌洗钱行为，单日内交易超过200笔，累计金额1.5亿元。',
    '立即冻结可疑账户，保存所有交易记录，向反洗钱中心报告，配合司法机关调查',
    '/reports/regulatory/RA202601010.pdf', 'COMPLETED',
    TO_DATE('2026-01-14 21:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    TO_DATE('2026-01-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '严重可疑，需立即上报',
    '紧急调查', 'system', TO_DATE('2026-01-14 21:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- =============================================
-- 验证数据
-- =============================================
-- 查询插入的数据
-- SELECT ANALYSIS_NO, ANALYSIS_NAME, ANALYSIS_TYPE, RISK_LEVEL,
--        COMPLIANCE_STATUS, COMPANY_NAME, ANALYSIS_DATE
-- FROM TBL_REGULATORY_ANALYSIS
-- ORDER BY ANALYSIS_DATE DESC;

-- 查看统计信息
-- SELECT ANALYSIS_TYPE, RISK_LEVEL, COMPLIANCE_STATUS, COUNT(*) as CNT
-- FROM TBL_REGULATORY_ANALYSIS
-- GROUP BY ANALYSIS_TYPE, RISK_LEVEL, COMPLIANCE_STATUS;

-- 查看高风险项目
-- SELECT ANALYSIS_NO, ANALYSIS_NAME, RISK_LEVEL, COMPLIANCE_STATUS
-- FROM TBL_REGULATORY_ANALYSIS
-- WHERE RISK_LEVEL IN ('HIGH', 'CRITICAL')
-- ORDER BY ANALYSIS_DATE DESC;

COMMIT;

-- =============================================
-- 说明
-- =============================================
-- 分析类型 (ANALYSIS_TYPE):
--   CROSS_BORDER - 跨境资金
--   LARGE_AMOUNT - 大额交易
--   FREQUENCY - 高频交易
--   COMPLIANCE - 合规检查
--
-- 合规状态 (COMPLIANCE_STATUS):
--   COMPLIANT - 合规
--   NON_COMPLIANT - 不合规
--   PENDING_REVIEW - 待审核
--
-- 风险等级 (RISK_LEVEL):
--   LOW - 低
--   MEDIUM - 中
--   HIGH - 高
--   CRITICAL - 严重
--
-- 分析状态 (ANALYSIS_STATUS):
--   DRAFT - 草稿
--   ANALYZING - 分析中
--   COMPLETED - 已完成
--   REVIEWED - 已审核
--
-- 删除标志 (DEL_FLAG):
--   '0' - 正常
--   '1' - 已删除
-- =============================================
