-- 融资还款计划表
-- 兼容达梦数据库、MySQL、Oracle

-- 达梦数据库建表语句
CREATE TABLE TBL_FINANCING_REPAYMENT_SCHEDULE (
    REPAYMENT_ID DECIMAL(20,0) NOT NULL,
    FINANCING_ID DECIMAL(20,0),
    FINANCING_NO VARCHAR(50),
    FINANCING_TYPE INT,
    FINANCIAL_INSTITUTION VARCHAR(200),
    REPAYMENT_PERIOD INT,
    REPAYMENT_METHOD INT,
    PLANNED_REPAYMENT_DATE VARCHAR(20),
    ACTUAL_REPAYMENT_DATE VARCHAR(20),
    PRINCIPAL_AMOUNT DECIMAL(18,2),
    INTEREST_AMOUNT DECIMAL(18,2),
    FEE_AMOUNT DECIMAL(18,2),
    TOTAL_AMOUNT DECIMAL(18,2),
    ACTUAL_PRINCIPAL_AMOUNT DECIMAL(18,2),
    ACTUAL_INTEREST_AMOUNT DECIMAL(18,2),
    ACTUAL_FEE_AMOUNT DECIMAL(18,2),
    ACTUAL_TOTAL_AMOUNT DECIMAL(18,2),
    REPAYMENT_STATUS INT,
    OVERDUE_DAYS INT,
    OVERDUE_INTEREST DECIMAL(18,2),
    CURRENCY VARCHAR(10),
    EXCHANGE_RATE DECIMAL(10,6),
    BASE_CURRENCY_AMOUNT DECIMAL(18,2),
    REPAYMENT_ACCOUNT VARCHAR(100),
    COLLECTION_ACCOUNT VARCHAR(100),
    OPERATOR VARCHAR(50),
    REVIEWER VARCHAR(50),
    REVIEW_TIME TIMESTAMP,
    ATTACHMENT VARCHAR(500),
    REMARK VARCHAR(500),
    CREATETIME TIMESTAMP,
    CREATEUSER DECIMAL(20,0),
    UPDATETIME TIMESTAMP,
    UPDATEUSER DECIMAL(20,0),
    ORGID DECIMAL(20,0),
    PRIMARY KEY (REPAYMENT_ID)
);

-- 添加注释
COMMENT ON TABLE TBL_FINANCING_REPAYMENT_SCHEDULE IS '融资还款计划表';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REPAYMENT_ID IS '还款计划ID';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.FINANCING_ID IS '融资ID';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.FINANCING_NO IS '融资编号';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.FINANCING_TYPE IS '融资类型(1-银行贷款 2-债券发行 3-融资租赁 4-信托融资 5-其他融资)';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.FINANCIAL_INSTITUTION IS '金融机构';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REPAYMENT_PERIOD IS '还款期次';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REPAYMENT_METHOD IS '还款方式(1-等额本息 2-等额本金 3-按期付息到期还本 4-一次性还本付息 5-自定义)';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.PLANNED_REPAYMENT_DATE IS '计划还款日期';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.ACTUAL_REPAYMENT_DATE IS '实际还款日期';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.PRINCIPAL_AMOUNT IS '应还本金';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.INTEREST_AMOUNT IS '应还利息';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.FEE_AMOUNT IS '应还费用';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.TOTAL_AMOUNT IS '应还总额';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.ACTUAL_PRINCIPAL_AMOUNT IS '实还本金';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.ACTUAL_INTEREST_AMOUNT IS '实还利息';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.ACTUAL_FEE_AMOUNT IS '实还费用';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.ACTUAL_TOTAL_AMOUNT IS '实还总额';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REPAYMENT_STATUS IS '还款状态(0-未还款 1-部分还款 2-已还款 3-逾期未还 4-逾期已还)';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.OVERDUE_DAYS IS '逾期天数';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.OVERDUE_INTEREST IS '逾期利息';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.CURRENCY IS '币种';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.EXCHANGE_RATE IS '汇率';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.BASE_CURRENCY_AMOUNT IS '本币金额';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REPAYMENT_ACCOUNT IS '还款账户';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.COLLECTION_ACCOUNT IS '收款账户';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.OPERATOR IS '经办人';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REVIEWER IS '审核人';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REVIEW_TIME IS '审核时间';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.ATTACHMENT IS '附件';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.REMARK IS '备注';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.CREATETIME IS '创建时间';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.CREATEUSER IS '创建用户';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.UPDATETIME IS '更新时间';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.UPDATEUSER IS '更新用户';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT_SCHEDULE.ORGID IS '组织ID';

-- 创建索引
CREATE INDEX IDX_REPAYMENT_FINANCING_ID ON TBL_FINANCING_REPAYMENT_SCHEDULE(FINANCING_ID);
CREATE INDEX IDX_REPAYMENT_FINANCING_NO ON TBL_FINANCING_REPAYMENT_SCHEDULE(FINANCING_NO);
CREATE INDEX IDX_REPAYMENT_STATUS ON TBL_FINANCING_REPAYMENT_SCHEDULE(REPAYMENT_STATUS);
CREATE INDEX IDX_REPAYMENT_PLANNED_DATE ON TBL_FINANCING_REPAYMENT_SCHEDULE(PLANNED_REPAYMENT_DATE);
CREATE INDEX IDX_REPAYMENT_ORGID ON TBL_FINANCING_REPAYMENT_SCHEDULE(ORGID);

-- 初始化序列(达梦数据库)
CREATE SEQUENCE SEQ_FINANCING_REPAYMENT
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

-- MySQL版本建表语句（注释状态，如需使用请取消注释）
/*
CREATE TABLE TBL_FINANCING_REPAYMENT_SCHEDULE (
    REPAYMENT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '还款计划ID',
    FINANCING_ID BIGINT COMMENT '融资ID',
    FINANCING_NO VARCHAR(50) COMMENT '融资编号',
    FINANCING_TYPE INT COMMENT '融资类型',
    FINANCIAL_INSTITUTION VARCHAR(200) COMMENT '金融机构',
    REPAYMENT_PERIOD INT COMMENT '还款期次',
    REPAYMENT_METHOD INT COMMENT '还款方式',
    PLANNED_REPAYMENT_DATE VARCHAR(20) COMMENT '计划还款日期',
    ACTUAL_REPAYMENT_DATE VARCHAR(20) COMMENT '实际还款日期',
    PRINCIPAL_AMOUNT DECIMAL(18,2) COMMENT '应还本金',
    INTEREST_AMOUNT DECIMAL(18,2) COMMENT '应还利息',
    FEE_AMOUNT DECIMAL(18,2) COMMENT '应还费用',
    TOTAL_AMOUNT DECIMAL(18,2) COMMENT '应还总额',
    ACTUAL_PRINCIPAL_AMOUNT DECIMAL(18,2) COMMENT '实还本金',
    ACTUAL_INTEREST_AMOUNT DECIMAL(18,2) COMMENT '实还利息',
    ACTUAL_FEE_AMOUNT DECIMAL(18,2) COMMENT '实还费用',
    ACTUAL_TOTAL_AMOUNT DECIMAL(18,2) COMMENT '实还总额',
    REPAYMENT_STATUS INT COMMENT '还款状态',
    OVERDUE_DAYS INT COMMENT '逾期天数',
    OVERDUE_INTEREST DECIMAL(18,2) COMMENT '逾期利息',
    CURRENCY VARCHAR(10) COMMENT '币种',
    EXCHANGE_RATE DECIMAL(10,6) COMMENT '汇率',
    BASE_CURRENCY_AMOUNT DECIMAL(18,2) COMMENT '本币金额',
    REPAYMENT_ACCOUNT VARCHAR(100) COMMENT '还款账户',
    COLLECTION_ACCOUNT VARCHAR(100) COMMENT '收款账户',
    OPERATOR VARCHAR(50) COMMENT '经办人',
    REVIEWER VARCHAR(50) COMMENT '审核人',
    REVIEW_TIME DATETIME COMMENT '审核时间',
    ATTACHMENT VARCHAR(500) COMMENT '附件',
    REMARK VARCHAR(500) COMMENT '备注',
    CREATETIME DATETIME COMMENT '创建时间',
    CREATEUSER BIGINT COMMENT '创建用户',
    UPDATETIME DATETIME COMMENT '更新时间',
    UPDATEUSER BIGINT COMMENT '更新用户',
    ORGID BIGINT COMMENT '组织ID',
    PRIMARY KEY (REPAYMENT_ID),
    INDEX IDX_FINANCING_ID (FINANCING_ID),
    INDEX IDX_FINANCING_NO (FINANCING_NO),
    INDEX IDX_REPAYMENT_STATUS (REPAYMENT_STATUS),
    INDEX IDX_PLANNED_DATE (PLANNED_REPAYMENT_DATE),
    INDEX IDX_ORGID (ORGID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='融资还款计划表';
*/
