-- 产品风险控制管理表
CREATE TABLE TBL_PRODUCT_RISK_CONTROL (
    RISK_CONTROL_ID INTEGER PRIMARY KEY,
    RISK_CONTROL_CODE VARCHAR(50) NOT NULL UNIQUE,
    RISK_CONTROL_NAME VARCHAR(200) NOT NULL,
    RISK_LEVEL VARCHAR(50) NOT NULL,
    CONTROL_TYPE VARCHAR(50) NOT NULL,
    LIMIT_THRESHOLD DECIMAL(20,2),
    WARNING_THRESHOLD DECIMAL(20,2),
    CURRENT_UTILIZATION_RATE DECIMAL(5,2),
    MONITORING_STATUS VARCHAR(50) DEFAULT 'NORMAL',
    CONTROL_MEASURES CLOB,
    DESCRIPTION CLOB,
    IS_ENABLED NUMBER(1) DEFAULT 1,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_BY VARCHAR(50),
    UPDATE_BY VARCHAR(50),
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TBL_PRODUCT_RISK_CONTROL IS '产品风险控制管理表';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.RISK_CONTROL_ID IS '风控策略ID';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.RISK_CONTROL_CODE IS '风控策略编码';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.RISK_CONTROL_NAME IS '风控策略名称';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.RISK_LEVEL IS '风险等级(LOW/MEDIUM_LOW/MEDIUM/MEDIUM_HIGH/HIGH)';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.CONTROL_TYPE IS '控制类型(INVESTMENT_LIMIT/CONCENTRATION_LIMIT/MATURITY_LIMIT/LIQUIDITY_LIMIT/CREDIT_RISK_LIMIT)';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.LIMIT_THRESHOLD IS '限额阈值';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.WARNING_THRESHOLD IS '预警阈值';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.CURRENT_UTILIZATION_RATE IS '当前使用率(%)';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.MONITORING_STATUS IS '监控状态(NORMAL/WARNING/EXCEEDED/SUSPENDED)';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.CONTROL_MEASURES IS '控制措施';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.DESCRIPTION IS '描述';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.IS_ENABLED IS '是否启用(1-启用,0-禁用)';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_PRODUCT_RISK_CONTROL.REMARK IS '备注';

-- 创建序列
CREATE SEQUENCE SEQ_PRODUCT_RISK_CONTROL START WITH 1 INCREMENT BY 1;

-- 创建索引
CREATE INDEX IDX_RISK_CONTROL_CODE ON TBL_PRODUCT_RISK_CONTROL(RISK_CONTROL_CODE);
CREATE INDEX IDX_RISK_LEVEL ON TBL_PRODUCT_RISK_CONTROL(RISK_LEVEL);
CREATE INDEX IDX_CONTROL_TYPE ON TBL_PRODUCT_RISK_CONTROL(CONTROL_TYPE);
CREATE INDEX IDX_MONITORING_STATUS ON TBL_PRODUCT_RISK_CONTROL(MONITORING_STATUS);

-- 插入初始数据
INSERT INTO TBL_PRODUCT_RISK_CONTROL (RISK_CONTROL_ID, RISK_CONTROL_CODE, RISK_CONTROL_NAME, RISK_LEVEL, CONTROL_TYPE, LIMIT_THRESHOLD, WARNING_THRESHOLD, CURRENT_UTILIZATION_RATE, MONITORING_STATUS, DESCRIPTION, IS_ENABLED, CREATE_TIME)
VALUES (1, 'RISK_LIMIT_001', '银行理财投资限额控制', 'MEDIUM', 'INVESTMENT_LIMIT', 50000000.00, 40000000.00, 75.50, 'NORMAL', '银行理财产品投资限额风险控制', 1, CURRENT_TIMESTAMP);

INSERT INTO TBL_PRODUCT_RISK_CONTROL (RISK_CONTROL_ID, RISK_CONTROL_CODE, RISK_CONTROL_NAME, RISK_LEVEL, CONTROL_TYPE, LIMIT_THRESHOLD, WARNING_THRESHOLD, CURRENT_UTILIZATION_RATE, MONITORING_STATUS, DESCRIPTION, IS_ENABLED, CREATE_TIME)
VALUES (2, 'RISK_LIMIT_002', '债券集中度控制', 'HIGH', 'CONCENTRATION_LIMIT', 30000000.00, 25000000.00, 85.20, 'WARNING', '债券投资集中度风险控制', 1, CURRENT_TIMESTAMP);

INSERT INTO TBL_PRODUCT_RISK_CONTROL (RISK_CONTROL_ID, RISK_CONTROL_CODE, RISK_CONTROL_NAME, RISK_LEVEL, CONTROL_TYPE, LIMIT_THRESHOLD, WARNING_THRESHOLD, CURRENT_UTILIZATION_RATE, MONITORING_STATUS, DESCRIPTION, IS_ENABLED, CREATE_TIME)
VALUES (3, 'RISK_LIMIT_003', '流动性风险控制', 'MEDIUM_LOW', 'LIQUIDITY_LIMIT', 20000000.00, 15000000.00, 45.30, 'NORMAL', '产品流动性风险控制', 1, CURRENT_TIMESTAMP);
