-- ============================================
-- 印鉴档案管理模块 - 达梦数据库建表脚本
-- 兼容达梦数据库 DM8
-- 创建日期: 2025-12-25
-- 说明: 包含建表语句、COMMENT注释、索引、测试数据
-- ============================================

-- ============================================
-- 1. 印鉴类型表 (TC_SEAL_TYPE)
-- ============================================
CREATE TABLE TC_SEAL_TYPE (
    SEAL_ID VARCHAR2(50) NOT NULL,
    TYPE_CODE VARCHAR2(50) NOT NULL,
    TYPE_NAME VARCHAR2(100) NOT NULL,
    SORT_ORDER INTEGER DEFAULT 0,
    IS_ENABLED INTEGER DEFAULT 1,
    DESCRIPTION VARCHAR2(500),
    CREATE_BY VARCHAR2(50),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR2(50),
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR2(500),
    CONSTRAINT PK_TC_SEAL_TYPE PRIMARY KEY (SEAL_ID)
);

-- 表注释
COMMENT ON TABLE TC_SEAL_TYPE IS '印鉴类型表';
COMMENT ON COLUMN TC_SEAL_TYPE.SEAL_ID IS '类型ID,主键';
COMMENT ON COLUMN TC_SEAL_TYPE.TYPE_CODE IS '类型编码,如:OFFICIAL_SEAL';
COMMENT ON COLUMN TC_SEAL_TYPE.TYPE_NAME IS '类型名称,如:公章';
COMMENT ON COLUMN TC_SEAL_TYPE.SORT_ORDER IS '排序号,数字越小越靠前';
COMMENT ON COLUMN TC_SEAL_TYPE.IS_ENABLED IS '是否启用:1-启用,0-禁用';
COMMENT ON COLUMN TC_SEAL_TYPE.DESCRIPTION IS '类型描述说明';
COMMENT ON COLUMN TC_SEAL_TYPE.CREATE_BY IS '创建人';
COMMENT ON COLUMN TC_SEAL_TYPE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TC_SEAL_TYPE.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TC_SEAL_TYPE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TC_SEAL_TYPE.REMARK IS '备注信息';

-- 创建索引
CREATE INDEX IDX_SEAL_TYPE_CODE ON TC_SEAL_TYPE(TYPE_CODE);
CREATE INDEX IDX_SEAL_TYPE_ENABLED ON TC_SEAL_TYPE(IS_ENABLED);
CREATE INDEX IDX_SEAL_TYPE_SORT ON TC_SEAL_TYPE(SORT_ORDER);

-- ============================================
-- 2. 印鉴档案表 (TC_SEAL_ARCHIVE_V2)
-- ============================================
CREATE TABLE TC_SEAL_ARCHIVE_V2 (
    ID VARCHAR2(50) NOT NULL,
    SEAL_CODE VARCHAR2(50) NOT NULL,
    SEAL_NAME VARCHAR2(200) NOT NULL,
    SEAL_TYPE_ID DECIMAL(20,0),
    SEAL_TYPE_NAME VARCHAR2(100),
    OWNER_NAME VARCHAR2(100) NOT NULL,
    OWNER_POSITION VARCHAR2(100),
    OWNER_ID_CARD VARCHAR2(18),
    EFFECTIVE_DATE TIMESTAMP,
    EXPIRE_DATE TIMESTAMP,
    SEAL_IMAGE_URL VARCHAR2(500),
    IS_ACTIVE INTEGER DEFAULT 1,
    VERSION_NO INTEGER DEFAULT 1,
    DESCRIPTION VARCHAR2(1000),
    CREATE_BY VARCHAR2(50),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR2(50),
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR2(500),
    CONSTRAINT PK_TC_SEAL_ARCHIVE_V2 PRIMARY KEY (ID)
);

-- 表注释
COMMENT ON TABLE TC_SEAL_ARCHIVE_V2 IS '印鉴档案表';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.ID IS '印鉴ID,主键';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.SEAL_CODE IS '印鉴编码,唯一编号';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.SEAL_NAME IS '印鉴名称';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.SEAL_TYPE_ID IS '印鉴类型ID,关联TC_SEAL_TYPE表';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.SEAL_TYPE_NAME IS '印鉴类型名称,冗余字段方便查询';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.OWNER_NAME IS '持有人姓名';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.OWNER_POSITION IS '持有人职位';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.OWNER_ID_CARD IS '持有人身份证号';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.EFFECTIVE_DATE IS '生效日期';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.EXPIRE_DATE IS '失效日期';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.SEAL_IMAGE_URL IS '印鉴图片URL地址';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.IS_ACTIVE IS '是否启用:1-启用,0-停用';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.VERSION_NO IS '版本号,用于乐观锁控制';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.DESCRIPTION IS '印鉴描述';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.CREATE_BY IS '创建人';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.REMARK IS '备注信息';

-- 创建索引
CREATE INDEX IDX_ARCHIVE_CODE ON TC_SEAL_ARCHIVE_V2(SEAL_CODE);
CREATE INDEX IDX_ARCHIVE_NAME ON TC_SEAL_ARCHIVE_V2(SEAL_NAME);
CREATE INDEX IDX_ARCHIVE_TYPE ON TC_SEAL_ARCHIVE_V2(SEAL_TYPE_ID);
CREATE INDEX IDX_ARCHIVE_OWNER ON TC_SEAL_ARCHIVE_V2(OWNER_NAME);
CREATE INDEX IDX_ARCHIVE_ACTIVE ON TC_SEAL_ARCHIVE_V2(IS_ACTIVE);
CREATE INDEX IDX_ARCHIVE_CREATE_TIME ON TC_SEAL_ARCHIVE_V2(CREATE_TIME);

-- ============================================
-- 3. 印鉴使用记录表 (TBL_SEAL_USAGE_RECORD)
-- ============================================
CREATE TABLE TBL_SEAL_USAGE_RECORD (
    RECORD_ID VARCHAR2(50) NOT NULL,
    SEAL_ID VARCHAR2(50) NOT NULL,
    SEAL_NAME VARCHAR2(200),
    SEAL_CODE VARCHAR2(50),
    USAGE_TYPE VARCHAR2(50),
    BUSINESS_TYPE VARCHAR2(50),
    USAGE_STATUS VARCHAR2(20),
    OPERATOR_ID VARCHAR2(50),
    OPERATOR_NAME VARCHAR2(100),
    USAGE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    APPROVER_ID VARCHAR2(50),
    APPROVER_NAME VARCHAR2(100),
    APPROVE_TIME TIMESTAMP,
    DESCRIPTION VARCHAR2(1000),
    REMARK VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TBL_SEAL_USAGE_RECORD PRIMARY KEY (RECORD_ID)
);

-- 表注释
COMMENT ON TABLE TBL_SEAL_USAGE_RECORD IS '印鉴使用记录表';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.RECORD_ID IS '记录ID,主键';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_ID IS '印鉴ID,关联TC_SEAL_ARCHIVE_V2表';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_NAME IS '印鉴名称,冗余字段';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_CODE IS '印鉴编码,冗余字段';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_TYPE IS '使用类型:单次盖章、多次盖章等';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.BUSINESS_TYPE IS '业务类型:合同、财务、行政等';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_STATUS IS '使用状态:SUCCESS-成功,FAILED-失败,PENDING-待审批';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.OPERATOR_ID IS '操作人ID';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.OPERATOR_NAME IS '操作人姓名';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_TIME IS '使用时间';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.APPROVER_ID IS '审批人ID';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.APPROVER_NAME IS '审批人姓名';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.APPROVE_TIME IS '审批时间';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.DESCRIPTION IS '使用说明';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.REMARK IS '备注';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.CREATE_TIME IS '创建时间';

-- 创建索引
CREATE INDEX IDX_USAGE_SEAL_ID ON TBL_SEAL_USAGE_RECORD(SEAL_ID);
CREATE INDEX IDX_USAGE_TIME ON TBL_SEAL_USAGE_RECORD(USAGE_TIME);
CREATE INDEX IDX_USAGE_OPERATOR ON TBL_SEAL_USAGE_RECORD(OPERATOR_NAME);
CREATE INDEX IDX_USAGE_STATUS ON TBL_SEAL_USAGE_RECORD(USAGE_STATUS);

-- ============================================
-- 插入测试数据 - 印鉴类型
-- ============================================
INSERT INTO TC_SEAL_TYPE (SEAL_ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, IS_ENABLED, DESCRIPTION, CREATE_BY, CREATE_TIME)
SELECT '1', 'OFFICIAL_SEAL', '公章', 1, 1, '企业公章,用于重要文件签署', 'admin', CURRENT_TIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TC_SEAL_TYPE WHERE SEAL_ID = '1');

INSERT INTO TC_SEAL_TYPE (SEAL_ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, IS_ENABLED, DESCRIPTION, CREATE_BY, CREATE_TIME)
SELECT '2', 'FINANCE_SEAL', '财务章', 2, 1, '财务专用章,用于财务相关文件', 'admin', CURRENT_TIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TC_SEAL_TYPE WHERE SEAL_ID = '2');

INSERT INTO TC_SEAL_TYPE (SEAL_ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, IS_ENABLED, DESCRIPTION, CREATE_BY, CREATE_TIME)
SELECT '3', 'LEGAL_SEAL', '法人章', 3, 1, '法定代表人章,代表法人意愿', 'admin', CURRENT_TIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TC_SEAL_TYPE WHERE SEAL_ID = '3');

INSERT INTO TC_SEAL_TYPE (SEAL_ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, IS_ENABLED, DESCRIPTION, CREATE_BY, CREATE_TIME)
SELECT '4', 'CONTRACT_SEAL', '合同章', 4, 1, '合同专用章,用于合同签署', 'admin', CURRENT_TIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TC_SEAL_TYPE WHERE SEAL_ID = '4');

INSERT INTO TC_SEAL_TYPE (SEAL_ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, IS_ENABLED, DESCRIPTION, CREATE_BY, CREATE_TIME)
SELECT '5', 'INVOICE_SEAL', '发票章', 5, 1, '发票专用章,用于发票开具', 'admin', CURRENT_TIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TC_SEAL_TYPE WHERE SEAL_ID = '5');

-- ============================================
-- 插入测试数据 - 印鉴档案
-- ============================================
INSERT INTO TC_SEAL_ARCHIVE_V2 (
    ID, SEAL_CODE, SEAL_NAME, SEAL_TYPE_ID, SEAL_TYPE_NAME,
    OWNER_NAME, OWNER_POSITION, OWNER_ID_CARD,
    EFFECTIVE_DATE, EXPIRE_DATE, IS_ACTIVE, VERSION_NO,
    DESCRIPTION, CREATE_BY, CREATE_TIME
)
SELECT
    '1001', 'SEAL001', '华博云科技有限公司公章', 1, '公章',
    '张三', '总经理', '110101199001011234',
    TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2029-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
    1, 1,
    '企业公章,用于公司重要文件签署', 'admin', CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TC_SEAL_ARCHIVE_V2 WHERE ID = '1001');

INSERT INTO TC_SEAL_ARCHIVE_V2 (
    ID, SEAL_CODE, SEAL_NAME, SEAL_TYPE_ID, SEAL_TYPE_NAME,
    OWNER_NAME, OWNER_POSITION, OWNER_ID_CARD,
    EFFECTIVE_DATE, EXPIRE_DATE, IS_ACTIVE, VERSION_NO,
    DESCRIPTION, CREATE_BY, CREATE_TIME
)
SELECT
    '1002', 'SEAL002', '华博云财务专用章', 2, '财务章',
    '李四', '财务总监', '110101199002021234',
    TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2029-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
    1, 1,
    '财务专用章,用于财务相关业务', 'admin', CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TC_SEAL_ARCHIVE_V2 WHERE ID = '1002');

INSERT INTO TC_SEAL_ARCHIVE_V2 (
    ID, SEAL_CODE, SEAL_NAME, SEAL_TYPE_ID, SEAL_TYPE_NAME,
    OWNER_NAME, OWNER_POSITION, OWNER_ID_CARD,
    EFFECTIVE_DATE, EXPIRE_DATE, IS_ACTIVE, VERSION_NO,
    DESCRIPTION, CREATE_BY, CREATE_TIME
)
SELECT
    '1003', 'SEAL003', '华博云法人章', 3, '法人章',
    '王五', '法定代表人', '110101198003031234',
    TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2029-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
    1, 1,
    '法定代表人章,代表法人意愿', 'admin', CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TC_SEAL_ARCHIVE_V2 WHERE ID = '1003');

INSERT INTO TC_SEAL_ARCHIVE_V2 (
    ID, SEAL_CODE, SEAL_NAME, SEAL_TYPE_ID, SEAL_TYPE_NAME,
    OWNER_NAME, OWNER_POSITION, OWNER_ID_CARD,
    EFFECTIVE_DATE, EXPIRE_DATE, IS_ACTIVE, VERSION_NO,
    DESCRIPTION, CREATE_BY, CREATE_TIME
)
SELECT
    '1004', 'SEAL004', '华博云合同专用章', 4, '合同章',
    '赵六', '销售总监', '110101199004041234',
    TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2029-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
    1, 1,
    '合同专用章,用于合同业务签署', 'admin', CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TC_SEAL_ARCHIVE_V2 WHERE ID = '1004');

INSERT INTO TC_SEAL_ARCHIVE_V2 (
    ID, SEAL_CODE, SEAL_NAME, SEAL_TYPE_ID, SEAL_TYPE_NAME,
    OWNER_NAME, OWNER_POSITION, OWNER_ID_CARD,
    EFFECTIVE_DATE, EXPIRE_DATE, IS_ACTIVE, VERSION_NO,
    DESCRIPTION, CREATE_BY, CREATE_TIME
)
SELECT
    '1005', 'SEAL005', '华博云发票专用章', 5, '发票章',
    '孙七', '财务主管', '110101199005051234',
    TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2029-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
    0, 1,
    '发票专用章,已停用', 'admin', CURRENT_TIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TC_SEAL_ARCHIVE_V2 WHERE ID = '1005');

-- ============================================
-- 插入测试数据 - 印鉴使用记录
-- ============================================
INSERT INTO TBL_SEAL_USAGE_RECORD (
    RECORD_ID, SEAL_ID, SEAL_NAME, SEAL_CODE,
    USAGE_TYPE, BUSINESS_TYPE, USAGE_STATUS,
    OPERATOR_ID, OPERATOR_NAME, USAGE_TIME, DESCRIPTION
)
SELECT
    'UR001', '1001', '华博云科技有限公司公章', 'SEAL001',
    '单次盖章', '合同签署', 'SUCCESS',
    'U001', '张三', TO_TIMESTAMP('2025-12-25 10:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    '签订销售合同'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TBL_SEAL_USAGE_RECORD WHERE RECORD_ID = 'UR001');

INSERT INTO TBL_SEAL_USAGE_RECORD (
    RECORD_ID, SEAL_ID, SEAL_NAME, SEAL_CODE,
    USAGE_TYPE, BUSINESS_TYPE, USAGE_STATUS,
    OPERATOR_ID, OPERATOR_NAME, USAGE_TIME, DESCRIPTION
)
SELECT
    'UR002', '1002', '华博云财务专用章', 'SEAL002',
    '单次盖章', '财务报销', 'SUCCESS',
    'U002', '李四', TO_TIMESTAMP('2025-12-25 11:15:00', 'YYYY-MM-DD HH24:MI:SS'),
    '费用报销单盖章'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TBL_SEAL_USAGE_RECORD WHERE RECORD_ID = 'UR002');

INSERT INTO TBL_SEAL_USAGE_RECORD (
    RECORD_ID, SEAL_ID, SEAL_NAME, SEAL_CODE,
    USAGE_TYPE, BUSINESS_TYPE, USAGE_STATUS,
    OPERATOR_ID, OPERATOR_NAME, USAGE_TIME, DESCRIPTION
)
SELECT
    'UR003', '1001', '华博云科技有限公司公章', 'SEAL001',
    '单次盖章', '行政管理', 'SUCCESS',
    'U003', '王五', TO_TIMESTAMP('2025-12-25 14:20:00', 'YYYY-MM-DD HH24:MI:SS'),
    '人事任命文件盖章'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TBL_SEAL_USAGE_RECORD WHERE RECORD_ID = 'UR003');

COMMIT;

-- 查询验证
SELECT '印鉴类型数据统计:' AS 统计类型, COUNT(*) AS 记录数 FROM TC_SEAL_TYPE
UNION ALL
SELECT '印鉴档案数据统计:', COUNT(*) FROM TC_SEAL_ARCHIVE_V2
UNION ALL
SELECT '使用记录数据统计:', COUNT(*) FROM TBL_SEAL_USAGE_RECORD;
