-- ===================================================================
-- 财资公共模块 - 数据源配置管理表
-- 数据库: 达梦数据库 (DM8)
-- 创建时间: 2026-01-30
-- 创建人: HuaBo Cloud AI Assistant
-- 说明: 修复表名和列名大小写问题，全部使用大写
-- ===================================================================

-- 删除旧表（如果存在）
DROP TABLE IF EXISTS TC_DATA_SOURCE_CONFIG;

-- 创建数据源配置表（达梦数据库，所有列名大写）
CREATE TABLE TC_DATA_SOURCE_CONFIG (
    ID VARCHAR(32) PRIMARY KEY,
    SOURCE_CODE VARCHAR(64) NOT NULL UNIQUE,
    SOURCE_NAME VARCHAR(200) NOT NULL,
    SOURCE_TYPE VARCHAR(32) NOT NULL,
    DATA_TYPE VARCHAR(32) NOT NULL,
    CONNECTION_CONFIG VARCHAR(2000),
    API_CONFIG VARCHAR(2000),
    CONNECTION_URL VARCHAR(500),
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(500),
    ENVIRONMENT VARCHAR(32),
    CONNECTION_STATUS VARCHAR(32) DEFAULT 'UNTESTED',
    SYNC_FREQUENCY VARCHAR(64),
    LAST_SYNC_TIME TIMESTAMP,
    LAST_TEST_TIME TIMESTAMP,
    SYNC_STATUS VARCHAR(32) DEFAULT 'PENDING',
    ERROR_COUNT INT DEFAULT 0,
    MAX_ERROR_COUNT INT DEFAULT 3,
    TIMEOUT_SECONDS INT DEFAULT 30,
    RETRY_COUNT INT DEFAULT 3,
    IS_ENABLED VARCHAR(1) DEFAULT '1',
    IS_ACTIVE VARCHAR(1) DEFAULT '1',
    STATUS VARCHAR(1) DEFAULT '1',
    REMARK VARCHAR(1000),
    DESCRIPTION VARCHAR(1000),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR(64),
    UPDATE_USER VARCHAR(64),
    VERSION_NO INT DEFAULT 1
);

-- 创建索引
CREATE INDEX IDX_TC_DATA_SOURCE_CODE ON TC_DATA_SOURCE_CONFIG(SOURCE_CODE);
CREATE INDEX IDX_TC_DATA_SOURCE_TYPE ON TC_DATA_SOURCE_CONFIG(SOURCE_TYPE);
CREATE INDEX IDX_TC_DATA_SOURCE_ENV ON TC_DATA_SOURCE_CONFIG(ENVIRONMENT);
CREATE INDEX IDX_TC_DATA_SOURCE_STATUS ON TC_DATA_SOURCE_CONFIG(CONNECTION_STATUS);
CREATE INDEX IDX_TC_DATA_SOURCE_ENABLED ON TC_DATA_SOURCE_CONFIG(IS_ENABLED);
CREATE INDEX IDX_TC_DATA_SOURCE_SYNC ON TC_DATA_SOURCE_CONFIG(SYNC_STATUS);
CREATE INDEX IDX_TC_DATA_SOURCE_CREATE_TIME ON TC_DATA_SOURCE_CONFIG(CREATE_TIME);

-- 表和列注释
COMMENT ON TABLE TC_DATA_SOURCE_CONFIG IS '财资公共模块 - 数据源配置管理表';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.ID IS '主键ID';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.SOURCE_CODE IS '数据源编码';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.SOURCE_NAME IS '数据源名称';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.SOURCE_TYPE IS '数据源类型: MYSQL/ORACLE/POSTGRESQL/DAMENG/REDIS/API';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.DATA_TYPE IS '数据类型: DATABASE/CACHE/API/FILE';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CONNECTION_CONFIG IS '连接配置(JSON格式)';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.API_CONFIG IS 'API配置(JSON格式)';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CONNECTION_URL IS '连接地址';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.USERNAME IS '用户名';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.PASSWORD IS '密码(加密存储)';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.ENVIRONMENT IS '环境类型: DEV/TEST/UAT/PROD';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CONNECTION_STATUS IS '连接状态: UNTESTED/NORMAL/ERROR/DISABLED';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.SYNC_FREQUENCY IS '同步频率: REALTIME/HOURLY/DAILY/WEEKLY/MONTHLY';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.LAST_SYNC_TIME IS '最后同步时间';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.LAST_TEST_TIME IS '最后测试时间';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.SYNC_STATUS IS '同步状态: PENDING/SYNCING/SUCCESS/FAILED';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.ERROR_COUNT IS '错误次数';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.MAX_ERROR_COUNT IS '最大错误次数';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.TIMEOUT_SECONDS IS '超时时间(秒)';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.RETRY_COUNT IS '重试次数';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.IS_ENABLED IS '是否启用: 1-是 0-否';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.IS_ACTIVE IS '是否激活: 1-是 0-否';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.STATUS IS '状态: 1-启用 0-停用';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.REMARK IS '备注信息';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.DESCRIPTION IS '数据源描述';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CREATE_USER IS '创建人';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.UPDATE_USER IS '更新人';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.VERSION_NO IS '版本号';

-- ===================================================================
-- 插入10条测试数据
-- ===================================================================

-- 测试数据1: 生产环境MySQL主数据库
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, IS_ACTIVE, STATUS, DESCRIPTION, REMARK,
    SYNC_FREQUENCY, TIMEOUT_SECONDS, RETRY_COUNT,
    CREATE_USER, CREATE_TIME
) VALUES (
    'DS20250130001', 'MYSQL_MAIN_PROD', '生产环境MySQL主数据库', 'MYSQL', 'DATABASE',
    'jdbc:mysql://192.0.2.200:3306/hbyun_treasury?useUnicode=true&characterEncoding=utf8', 'treasury_admin', 'encrypted_password', 'PROD', 'NORMAL',
    '1', '1', '1', '财资系统生产环境MySQL主数据库', '主数据库，每日全量备份',
    'DAILY', 30, 3, 'system', CURRENT_TIMESTAMP
);

-- 测试数据2: 备份环境达梦数据库
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, IS_ACTIVE, STATUS, DESCRIPTION, REMARK,
    SYNC_FREQUENCY, TIMEOUT_SECONDS, RETRY_COUNT,
    CREATE_USER, CREATE_TIME
) VALUES (
    'DS20250130002', 'DM_BACKUP_PROD', '生产环境达梦备份数据库', 'DAMENG', 'DATABASE',
    'jdbc:dm://192.0.2.200:5236/HBYUN_BACKUP', 'backup_user', 'encrypted_password', 'PROD', 'NORMAL',
    '1', '1', '1', '财资系统达梦备份数据库', '用于数据备份和恢复',
    'WEEKLY', 60, 5, 'system', CURRENT_TIMESTAMP
);

-- 测试数据3: 银行接口API
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, ENVIRONMENT, CONNECTION_STATUS,
    API_CONFIG, IS_ENABLED, IS_ACTIVE, STATUS, DESCRIPTION, REMARK,
    SYNC_FREQUENCY, TIMEOUT_SECONDS, RETRY_COUNT,
    CREATE_USER, CREATE_TIME
) VALUES (
    'DS20250130003', 'BANK_API_ICBC', '工商银行接口API', 'API', 'API',
    'https://api.icbc.com.cn/treasury/v1', 'PROD', 'ERROR',
    '{"apiKey":"xxx","secret":"REDACTED","version":"1.0"}', '0', '0', '1', '工商银行银企直联接口', '暂时不可用，等待银行修复',
    'REALTIME', 10, 1, 'system', CURRENT_TIMESTAMP
);

-- 测试数据4: Redis缓存服务
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, IS_ACTIVE, STATUS, DESCRIPTION, REMARK,
    SYNC_FREQUENCY, TIMEOUT_SECONDS, RETRY_COUNT,
    CREATE_USER, CREATE_TIME
) VALUES (
    'DS20250130004', 'REDIS_CACHE_MAIN', 'Redis缓存主服务', 'REDIS', 'CACHE',
    'redis://192.0.2.200:6379/0', 'cache_user', 'encrypted_password', 'PROD', 'NORMAL',
    '1', '1', '1', 'Redis缓存服务，用于缓存热点数据', '主缓存节点',
    'HOURLY', 5, 2, 'system', CURRENT_TIMESTAMP
);

-- 测试数据5: 测试环境PostgreSQL
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, IS_ACTIVE, STATUS, DESCRIPTION, REMARK,
    SYNC_FREQUENCY, TIMEOUT_SECONDS, RETRY_COUNT,
    CREATE_USER, CREATE_TIME
) VALUES (
    'DS20250130005', 'POSTGRESQL_TEST', '测试环境PostgreSQL数据库', 'POSTGRESQL', 'DATABASE',
    'jdbc:postgresql://192.0.2.200:5432/hbyun_test', 'test_user', 'encrypted_password', 'TEST', 'NORMAL',
    '1', '1', '1', '测试环境PostgreSQL数据库', '用于开发和测试',
    'DAILY', 30, 3, 'system', CURRENT_TIMESTAMP
);

-- 测试数据6: ERP系统Oracle数据库
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, IS_ACTIVE, STATUS, DESCRIPTION, REMARK,
    SYNC_FREQUENCY, TIMEOUT_SECONDS, RETRY_COUNT,
    CREATE_USER, CREATE_TIME
) VALUES (
    'DS20250130006', 'ORACLE_ERP_PROD', 'ERP系统Oracle数据库', 'ORACLE', 'DATABASE',
    'jdbc:oracle:thin:@192.0.2.200:1521:ERPPROD', 'erp_user', 'encrypted_password', 'PROD', 'UNTESTED',
    '1', '1', '1', 'ERP系统Oracle数据库连接', 'ERP系统数据同步源',
    'WEEKLY', 60, 3, 'system', CURRENT_TIMESTAMP
);

-- 测试数据7: 文件数据源接口
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, IS_ACTIVE, STATUS, DESCRIPTION, REMARK,
    SYNC_FREQUENCY, TIMEOUT_SECONDS, RETRY_COUNT,
    CREATE_USER, CREATE_TIME
) VALUES (
    'DS20250130007', 'FILE_INTERFACE_BANK', '银行对账文件接口', 'FILE', 'FILE',
    '/data/interface/bank/statement/', 'file_user', 'PROD', 'NORMAL',
    '1', '1', '1', '银行对账文件接口，用于处理银行对账单文件', '每日凌晨2点自动处理',
    'DAILY', 120, 3, 'system', CURRENT_TIMESTAMP
);

-- 测试数据8: 开发环境MySQL
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, IS_ACTIVE, STATUS, DESCRIPTION, REMARK,
    SYNC_FREQUENCY, TIMEOUT_SECONDS, RETRY_COUNT,
    CREATE_USER, CREATE_TIME
) VALUES (
    'DS20250130008', 'MYSQL_DEV_LOCAL', '开发环境本地MySQL', 'MYSQL', 'DATABASE',
    'jdbc:mysql://localhost:3306/hbyun_dev?useUnicode=true&characterEncoding=utf8', 'root', 'encrypted_password', 'DEV', 'NORMAL',
    '1', '1', '1', '开发环境本地MySQL数据库', '开发人员本地测试环境',
    'REALTIME', 10, 1, 'system', CURRENT_TIMESTAMP
);

-- 测试数据9: 数据仓库大数据平台
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, PASSWORD, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, IS_ACTIVE, STATUS, DESCRIPTION, REMARK,
    SYNC_FREQUENCY, TIMEOUT_SECONDS, RETRY_COUNT,
    CREATE_USER, CREATE_TIME
) VALUES (
    'DS20250130009', 'HIVE_DATA_WAREHOUSE', '数据仓库Hive集群', 'HIVE', 'DATABASE',
    'jdbc:hive2://192.0.2.200:10000/hbyun_warehouse', 'hive_user', 'encrypted_password', 'PROD', 'NORMAL',
    '1', '1', '1', '数据仓库Hive集群连接', '用于大数据分析和报表',
    'MONTHLY', 300, 5, 'system', CURRENT_TIMESTAMP
);

-- 测试数据10: 第三方支付接口
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, ENVIRONMENT, CONNECTION_STATUS,
    API_CONFIG, IS_ENABLED, IS_ACTIVE, STATUS, DESCRIPTION, REMARK,
    SYNC_FREQUENCY, TIMEOUT_SECONDS, RETRY_COUNT,
    CREATE_USER, CREATE_TIME
) VALUES (
    'DS20250130010', 'ALIPAY_API', '支付宝支付接口', 'API', 'API',
    'https://openapi.alipay.com/gateway.do', 'PROD', 'NORMAL',
    '{"appId":"xxx","privateKey":"xxx","publicKey":"xxx","format":"JSON"}', '1', '1', '1', '支付宝支付接口，用于线上支付对账', '每日自动对账',
    'DAILY', 15, 3, 'system', CURRENT_TIMESTAMP
);

-- 提交事务
COMMIT;

-- 查询验证
SELECT '数据源配置表初始化完成，共插入 ' || COUNT(*) || ' 条测试数据' AS MESSAGE
FROM TC_DATA_SOURCE_CONFIG;

-- 显示所有数据源
SELECT
    SOURCE_CODE AS "数据源编码",
    SOURCE_NAME AS "数据源名称",
    SOURCE_TYPE AS "数据源类型",
    DATA_TYPE AS "数据类型",
    ENVIRONMENT AS "环境",
    CONNECTION_STATUS AS "连接状态",
    IS_ENABLED AS "是否启用"
FROM TC_DATA_SOURCE_CONFIG
ORDER BY CREATE_TIME DESC;
