-- ============================================================
-- 数据映射配置表
-- 数据库: 达梦数据库 (DM8)
-- 说明: 用于管理系统间数据字段映射关系
-- 作者: 华博云开发团队
-- 日期: 2025-01-04
-- ============================================================

-- 创建数据映射配置表
CREATE TABLE TC_DATA_MAPPING (
    ID NUMBER(20) NOT NULL,
    SYSTEM_ID NUMBER(20),
    MAPPING_NAME VARCHAR2(200),
    SOURCE_FIELD VARCHAR2(200),
    TARGET_FIELD VARCHAR2(200),
    FIELD_TYPE VARCHAR2(50),
    CONVERSION_RULE VARCHAR2(1000),
    DEFAULT_VALUE VARCHAR2(500),
    IS_REQUIRED VARCHAR2(1) DEFAULT '0',
    VALIDATION_RULE VARCHAR2(1000),
    ERROR_STRATEGY VARCHAR2(200),
    SORT_ORDER NUMBER(10),
    STATUS VARCHAR2(1) DEFAULT '1',
    REMARK VARCHAR2(1000),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR2(100),
    UPDATE_USER VARCHAR2(100),
    VERSION_NO NUMBER(10) DEFAULT 1,
    CONSTRAINT PK_DATA_MAPPING PRIMARY KEY (ID)
);

-- 添加表注释
COMMENT ON TABLE TC_DATA_MAPPING IS '数据映射配置表，用于存储系统间数据字段映射关系和转换规则';

-- 添加列注释
COMMENT ON COLUMN TC_DATA_MAPPING.ID IS '主键ID';
COMMENT ON COLUMN TC_DATA_MAPPING.SYSTEM_ID IS '系统ID';
COMMENT ON COLUMN TC_DATA_MAPPING.MAPPING_NAME IS '映射名称';
COMMENT ON COLUMN TC_DATA_MAPPING.SOURCE_FIELD IS '源字段';
COMMENT ON COLUMN TC_DATA_MAPPING.TARGET_FIELD IS '目标字段';
COMMENT ON COLUMN TC_DATA_MAPPING.FIELD_TYPE IS '字段类型';
COMMENT ON COLUMN TC_DATA_MAPPING.CONVERSION_RULE IS '转换规则';
COMMENT ON COLUMN TC_DATA_MAPPING.DEFAULT_VALUE IS '默认值';
COMMENT ON COLUMN TC_DATA_MAPPING.IS_REQUIRED IS '是否必填：1-是，0-否';
COMMENT ON COLUMN TC_DATA_MAPPING.VALIDATION_RULE IS '校验规则';
COMMENT ON COLUMN TC_DATA_MAPPING.ERROR_STRATEGY IS '错误处理策略';
COMMENT ON COLUMN TC_DATA_MAPPING.SORT_ORDER IS '排序顺序';
COMMENT ON COLUMN TC_DATA_MAPPING.STATUS IS '状态：1-启用，0-停用';
COMMENT ON COLUMN TC_DATA_MAPPING.REMARK IS '备注';
COMMENT ON COLUMN TC_DATA_MAPPING.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TC_DATA_MAPPING.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TC_DATA_MAPPING.CREATE_USER IS '创建人';
COMMENT ON COLUMN TC_DATA_MAPPING.UPDATE_USER IS '更新人';
COMMENT ON COLUMN TC_DATA_MAPPING.VERSION_NO IS '版本号';

-- 创建索引
CREATE INDEX IDX_SYSTEM_ID ON TC_DATA_MAPPING(SYSTEM_ID);
COMMENT ON INDEX IDX_SYSTEM_ID IS '系统ID索引';

CREATE INDEX IDX_MAPPING_NAME ON TC_DATA_MAPPING(MAPPING_NAME);
COMMENT ON INDEX IDX_MAPPING_NAME IS '映射名称索引';

CREATE INDEX IDX_STATUS ON TC_DATA_MAPPING(STATUS);
COMMENT ON INDEX IDX_STATUS IS '状态索引';

CREATE INDEX IDX_CREATE_TIME ON TC_DATA_MAPPING(CREATE_TIME);
COMMENT ON INDEX IDX_CREATE_TIME IS '创建时间索引';

-- 创建序列
CREATE SEQUENCE SEQ_DATA_MAPPING
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    NOCACHE;
COMMENT ON SEQUENCE SEQ_DATA_MAPPING IS '数据映射配置表主键序列';

-- ============================================================
-- 测试数据
-- ============================================================

-- 插入测试数据
INSERT INTO TC_DATA_MAPPING (ID, SYSTEM_ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, FIELD_TYPE, CONVERSION_RULE, DEFAULT_VALUE, IS_REQUIRED, VALIDATION_RULE, ERROR_STRATEGY, SORT_ORDER, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO)
VALUES (1, 1, '财务系统-银行系统映射', 'accountNo', 'accountNumber', 'String', 'DIRECT', null, '1', 'NOT_EMPTY', 'SKIP', 1, '1', '账户号映射', TIMESTAMP '2024-12-01 10:00:00', TIMESTAMP '2024-12-01 10:00:00', 'admin', 'admin', 1);

INSERT INTO TC_DATA_MAPPING (ID, SYSTEM_ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, FIELD_TYPE, CONVERSION_RULE, DEFAULT_VALUE, IS_REQUIRED, VALIDATION_RULE, ERROR_STRATEGY, SORT_ORDER, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO)
VALUES (2, 1, '财务系统-银行系统映射', 'accountName', 'accountName', 'String', 'DIRECT', null, '1', 'NOT_EMPTY', 'SKIP', 2, '1', '账户名称映射', TIMESTAMP '2024-12-01 10:00:00', TIMESTAMP '2024-12-01 10:00:00', 'admin', 'admin', 1);

INSERT INTO TC_DATA_MAPPING (ID, SYSTEM_ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, FIELD_TYPE, CONVERSION_RULE, DEFAULT_VALUE, IS_REQUIRED, VALIDATION_RULE, ERROR_STRATEGY, SORT_ORDER, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO)
VALUES (3, 2, 'OA系统-ERP系统映射', 'employeeCode', 'empNo', 'String', 'DIRECT', null, '1', 'NOT_EMPTY', 'SKIP', 1, '1', '员工编号映射', TIMESTAMP '2024-12-02 14:30:00', TIMESTAMP '2024-12-02 14:30:00', 'admin', 'admin', 1);

INSERT INTO TC_DATA_MAPPING (ID, SYSTEM_ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, FIELD_TYPE, CONVERSION_RULE, DEFAULT_VALUE, IS_REQUIRED, VALIDATION_RULE, ERROR_STRATEGY, SORT_ORDER, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO)
VALUES (4, 2, 'OA系统-ERP系统映射', 'departmentName', 'deptName', 'String', 'DIRECT', null, '0', '', 'LOG_ERROR', 2, '1', '部门名称映射', TIMESTAMP '2024-12-02 14:30:00', TIMESTAMP '2024-12-02 14:30:00', 'admin', 'admin', 1);

INSERT INTO TC_DATA_MAPPING (ID, SYSTEM_ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, FIELD_TYPE, CONVERSION_RULE, DEFAULT_VALUE, IS_REQUIRED, VALIDATION_RULE, ERROR_STRATEGY, SORT_ORDER, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO)
VALUES (5, 3, 'ERP-财务系统映射', 'productCode', 'productCode', 'String', 'TRIM_PREFIX', 'PRD-', null, '1', 'NOT_EMPTY', 'SKIP', 1, '1', '产品编码映射(去除前缀)', TIMESTAMP '2024-12-03 09:15:00', TIMESTAMP '2024-12-03 09:15:00', 'admin', 'admin', 1);

INSERT INTO TC_DATA_MAPPING (ID, SYSTEM_ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, FIELD_TYPE, CONVERSION_RULE, DEFAULT_VALUE, IS_REQUIRED, VALIDATION_RULE, ERROR_STRATEGY, SORT_ORDER, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO)
VALUES (6, 3, 'ERP-财务系统映射', 'amount', 'transAmount', 'Decimal', 'MULTIPLY', '1.14', '0.00', 'NUMERIC', 'LOG_ERROR', 2, '1', '金额映射(含税转换)', TIMESTAMP '2024-12-03 09:15:00', TIMESTAMP '2024-12-03 09:15:00', 'admin', 'admin', 1);

INSERT INTO TC_DATA_MAPPING (ID, SYSTEM_ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, FIELD_TYPE, CONVERSION_RULE, DEFAULT_VALUE, IS_REQUIRED, VALIDATION_RULE, ERROR_STRATEGY, SORT_ORDER, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO)
VALUES (7, 4, 'HR-财务系统映射', 'salaryAmount', 'salary', 'Decimal', 'DIRECT', null, '1', 'POSITIVE_NUMBER', 'SKIP', 1, '1', '薪资金额映射', TIMESTAMP '2024-12-04 16:20:00', TIMESTAMP '2024-12-04 16:20:00', 'admin', 'admin', 1);

INSERT INTO TC_DATA_MAPPING (ID, SYSTEM_ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, FIELD_TYPE, CONVERSION_RULE, DEFAULT_VALUE, IS_REQUIRED, VALIDATION_RULE, ERROR_STRATEGY, SORT_ORDER, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO)
VALUES (8, 5, 'CRM-财务系统映射', 'customerNo', 'customerId', 'String', 'PAD_LEFT', '10', '0', '1', 'NOT_EMPTY', 'SKIP', 1, '1', '客户编号映射(左填充)', TIMESTAMP '2024-12-05 11:45:00', TIMESTAMP '2024-12-05 11:45:00', 'admin', 'admin', 1);

INSERT INTO TC_DATA_MAPPING (ID, SYSTEM_ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, FIELD_TYPE, CONVERSION_RULE, DEFAULT_VALUE, IS_REQUIRED, VALIDATION_RULE, ERROR_STRATEGY, SORT_ORDER, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO)
VALUES (9, 6, 'SCM-财务系统映射', 'orderNo', 'purchaseOrderNo', 'String', 'ADD_PREFIX', 'PO-', null, '1', 'NOT_EMPTY', 'SKIP', 1, '1', '订单编号映射(添加前缀)', TIMESTAMP '2024-12-06 13:30:00', TIMESTAMP '2024-12-06 13:30:00', 'admin', 'admin', 1);

INSERT INTO TC_DATA_MAPPING (ID, SYSTEM_ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, FIELD_TYPE, CONVERSION_RULE, DEFAULT_VALUE, IS_REQUIRED, VALIDATION_RULE, ERROR_STRATEGY, SORT_ORDER, STATUS, REMARK, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO)
VALUES (10, 6, 'SCM-财务系统映射', 'supplierName', 'vendorName', 'String', 'DIRECT', null, '1', 'NOT_EMPTY', 'SKIP', 2, '1', '供应商名称映射', TIMESTAMP '2024-12-06 13:30:00', TIMESTAMP '2024-12-06 13:30:00', 'admin', 'admin', 1);

-- 提交事务
COMMIT;

-- ============================================================
-- 验证数据
-- ============================================================

-- 查询测试数据
-- SELECT ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, CREATE_TIME
-- FROM TC_DATA_MAPPING
-- ORDER BY CREATE_TIME DESC;

-- 查询记录数
-- SELECT COUNT(*) AS TOTAL_RECORDS FROM TC_DATA_MAPPING;
