-- =============================================
-- 电票账户配置表 - 达梦数据库建表脚本
-- 表名: TC_ETICKET_ACCOUNT
-- 描述: 存储电子票据账户的配置信息,包括账户基本信息、银行信息、额度信息等
-- 作者: 华博云开发团队
-- 创建时间: 2024-12-24
-- 兼容性: 达梦数据库 (DM Database)
-- =============================================

-- 删除已存在的表(如果需要)
-- DROP TABLE IF EXISTS TC_ETICKET_ACCOUNT;

-- 创建电票账户配置表
CREATE TABLE TC_ETICKET_ACCOUNT (
    -- 主键
    ETICKET_ACCOUNT_ID DECIMAL(20,0) NOT NULL,

    -- 账户基本信息
    ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
    ACCOUNT_NAME VARCHAR(200) NOT NULL,
    ETICKET_SYSTEM VARCHAR(50) NOT NULL,
    ACCOUNT_TYPE VARCHAR(50) NOT NULL,

    -- 银行信息
    BANK_NAME VARCHAR(200),
    BRANCH_NAME VARCHAR(200),
    BANK_CODE VARCHAR(50) NOT NULL,
    BANK_ACCOUNT_NUMBER VARCHAR(100) NOT NULL,

    -- 金额信息
    ACCOUNT_BALANCE DECIMAL(18,2) DEFAULT 0.00,
    CREDIT_LIMIT DECIMAL(18,2) DEFAULT 0.00,

    -- 账户状态
    OPEN_DATE DATE,
    ACCOUNT_STATUS VARCHAR(20) DEFAULT 'NORMAL',
    IS_ACTIVE INTEGER DEFAULT 1,

    -- 联系信息
    CONTACT_PERSON VARCHAR(100),
    CONTACT_PHONE VARCHAR(50),
    CONTACT_EMAIL VARCHAR(100),

    -- 备注和描述
    REMARK VARCHAR(500),
    DESCRIPTION VARCHAR(1000),

    -- 同步信息
    LAST_SYNC_TIME TIMESTAMP,
    SYNC_STATUS VARCHAR(20) DEFAULT 'PENDING',

    -- 组织信息
    ORG_ID DECIMAL(20,0),

    -- 审计字段
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50),

    -- 主键约束
    CONSTRAINT PK_ETICKET_ACCOUNT PRIMARY KEY (ETICKET_ACCOUNT_ID)
);

-- 添加表注释
COMMENT ON TABLE TC_ETICKET_ACCOUNT IS '电票账户配置表';

-- 添加列注释
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ETICKET_ACCOUNT_ID IS '电票账户ID(主键)';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ACCOUNT_NUMBER IS '账户编号';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ACCOUNT_NAME IS '账户名称';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ETICKET_SYSTEM IS '电票系统(ECDS/BECP/BANK_ETICKET)';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ACCOUNT_TYPE IS '账户类型(ACCEPTANCE/DISCOUNT/REDISCOUNT/PLEDGE/CUSTODY/MARGIN)';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BANK_NAME IS '开户银行名称';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BRANCH_NAME IS '分支机构名称';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BANK_CODE IS '银行编码(ICBC/CCB/ABC/BOC/BOCOM/CMB等)';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BANK_ACCOUNT_NUMBER IS '银行账号';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ACCOUNT_BALANCE IS '账户余额';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CREDIT_LIMIT IS '授信额度(万元)';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.OPEN_DATE IS '开户日期';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ACCOUNT_STATUS IS '账户状态(NORMAL正常/FROZEN冻结/CLOSED关闭)';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.IS_ACTIVE IS '是否启用(1启用/0禁用)';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CONTACT_PERSON IS '联系人姓名';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CONTACT_PHONE IS '联系电话';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CONTACT_EMAIL IS '联系邮箱';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.REMARK IS '备注信息';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.DESCRIPTION IS '描述信息';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.LAST_SYNC_TIME IS '最后同步时间';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.SYNC_STATUS IS '同步状态(SUCCESS成功/FAILED失败/PENDING待同步)';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ORG_ID IS '组织ID';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CREATE_USER IS '创建人';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.UPDATE_USER IS '更新人';

-- 创建索引
CREATE UNIQUE INDEX IDX_ETICKET_ACCOUNT_NUMBER ON TC_ETICKET_ACCOUNT(ACCOUNT_NUMBER);
CREATE INDEX IDX_ETICKET_ACCOUNT_NAME ON TC_ETICKET_ACCOUNT(ACCOUNT_NAME);
CREATE INDEX IDX_ETICKET_SYSTEM ON TC_ETICKET_ACCOUNT(ETICKET_SYSTEM);
CREATE INDEX IDX_ETICKET_TYPE ON TC_ETICKET_ACCOUNT(ACCOUNT_TYPE);
CREATE INDEX IDX_ETICKET_BANK_CODE ON TC_ETICKET_ACCOUNT(BANK_CODE);
CREATE INDEX IDX_ETICKET_STATUS ON TC_ETICKET_ACCOUNT(ACCOUNT_STATUS);
CREATE INDEX IDX_ETICKET_ORG_ID ON TC_ETICKET_ACCOUNT(ORG_ID);
CREATE INDEX IDX_ETICKET_CREATE_TIME ON TC_ETICKET_ACCOUNT(CREATE_TIME);

-- 添加索引注释
COMMENT ON INDEX IDX_ETICKET_ACCOUNT_NUMBER IS '账户编号唯一索引';
COMMENT ON INDEX IDX_ETICKET_ACCOUNT_NAME IS '账户名称索引';
COMMENT ON INDEX IDX_ETICKET_SYSTEM IS '电票系统索引';
COMMENT ON INDEX IDX_ETICKET_TYPE IS '账户类型索引';
COMMENT ON INDEX IDX_ETICKET_BANK_CODE IS '银行编码索引';
COMMENT ON INDEX IDX_ETICKET_STATUS IS '账户状态索引';
COMMENT ON INDEX IDX_ETICKET_ORG_ID IS '组织ID索引';
COMMENT ON INDEX IDX_ETICKET_CREATE_TIME IS '创建时间索引';

-- =============================================
-- 测试数据插入
-- =============================================

-- 插入测试数据
INSERT INTO TC_ETICKET_ACCOUNT (
    ETICKET_ACCOUNT_ID, ACCOUNT_NUMBER, ACCOUNT_NAME, ETICKET_SYSTEM, ACCOUNT_TYPE,
    BANK_NAME, BRANCH_NAME, BANK_CODE, BANK_ACCOUNT_NUMBER,
    ACCOUNT_BALANCE, CREDIT_LIMIT, OPEN_DATE, ACCOUNT_STATUS, IS_ACTIVE,
    CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    REMARK, DESCRIPTION, SYNC_STATUS, ORG_ID,
    CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER
) VALUES (
    1, 'ETK20240001', '工商银行电票账户-测试01', 'ECDS', 'ACCEPTANCE',
    '中国工商银行', '北京分行营业部', 'ICBC', '6222020200001234567',
    500000.00, 1000.00, TO_DATE('2024-01-15', 'YYYY-MM-DD'), 'NORMAL', 1,
    '张三', '13800138000', 'zhangsan@example.com',
    '测试账户', '用于测试的电票账户配置', 'SUCCESS', 1,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin'
);

INSERT INTO TC_ETICKET_ACCOUNT (
    ETICKET_ACCOUNT_ID, ACCOUNT_NUMBER, ACCOUNT_NAME, ETICKET_SYSTEM, ACCOUNT_TYPE,
    BANK_NAME, BRANCH_NAME, BANK_CODE, BANK_ACCOUNT_NUMBER,
    ACCOUNT_BALANCE, CREDIT_LIMIT, OPEN_DATE, ACCOUNT_STATUS, IS_ACTIVE,
    CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    REMARK, DESCRIPTION, SYNC_STATUS, ORG_ID,
    CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER
) VALUES (
    2, 'ETK20240002', '建设银行贴现账户-主账户', 'BECP', 'DISCOUNT',
    '中国建设银行', '上海浦东分行', 'CCB', '6217000012345678901',
    1200000.00, 2000.00, TO_DATE('2024-02-20', 'YYYY-MM-DD'), 'NORMAL', 1,
    '李四', '13800138000', 'lisi@example.com',
    '主要贴现账户', '用于票据贴现业务的主要账户', 'SUCCESS', 1,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin'
);

INSERT INTO TC_ETICKET_ACCOUNT (
    ETICKET_ACCOUNT_ID, ACCOUNT_NUMBER, ACCOUNT_NAME, ETICKET_SYSTEM, ACCOUNT_TYPE,
    BANK_NAME, BRANCH_NAME, BANK_CODE, BANK_ACCOUNT_NUMBER,
    ACCOUNT_BALANCE, CREDIT_LIMIT, OPEN_DATE, ACCOUNT_STATUS, IS_ACTIVE,
    CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    REMARK, DESCRIPTION, SYNC_STATUS, ORG_ID,
    CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER
) VALUES (
    3, 'ETK20240003', '农业银行质押账户-备用', 'BANK_ETICKET', 'PLEDGE',
    '中国农业银行', '广州天河支行', 'ABC', '6228480123456789012',
    800000.00, 1500.00, TO_DATE('2024-03-10', 'YYYY-MM-DD'), 'FROZEN', 0,
    '王五', '13800138000', 'wangwu@example.com',
    '质押账户', '用于票据质押的账户,暂时冻结', 'PENDING', 1,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin'
);

INSERT INTO TC_ETICKET_ACCOUNT (
    ETICKET_ACCOUNT_ID, ACCOUNT_NUMBER, ACCOUNT_NAME, ETICKET_SYSTEM, ACCOUNT_TYPE,
    BANK_NAME, BRANCH_NAME, BANK_CODE, BANK_ACCOUNT_NUMBER,
    ACCOUNT_BALANCE, CREDIT_LIMIT, OPEN_DATE, ACCOUNT_STATUS, IS_ACTIVE,
    CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    REMARK, DESCRIPTION, SYNC_STATUS, ORG_ID,
    CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER
) VALUES (
    4, 'ETK20240004', '中国银行转贴现账户', 'ECDS', 'REDISCOUNT',
    '中国银行', '深圳福田分行', 'BOC', '621661000012345678',
    2000000.00, 3000.00, TO_DATE('2024-04-05', 'YYYY-MM-DD'), 'NORMAL', 1,
    '赵六', '13800138000', 'zhaoliu@example.com',
    '转贴现专用', '用于转贴现业务的专用账户', 'SUCCESS', 1,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin'
);

INSERT INTO TC_ETICKET_ACCOUNT (
    ETICKET_ACCOUNT_ID, ACCOUNT_NUMBER, ACCOUNT_NAME, ETICKET_SYSTEM, ACCOUNT_TYPE,
    BANK_NAME, BRANCH_NAME, BANK_CODE, BANK_ACCOUNT_NUMBER,
    ACCOUNT_BALANCE, CREDIT_LIMIT, OPEN_DATE, ACCOUNT_STATUS, IS_ACTIVE,
    CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    REMARK, DESCRIPTION, SYNC_STATUS, ORG_ID,
    CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER
) VALUES (
    5, 'ETK20240005', '交通银行托管账户', 'BECP', 'CUSTODY',
    '交通银行', '杭州西湖支行', 'BOCOM', '622252000012345678',
    3500000.00, 5000.00, TO_DATE('2024-05-12', 'YYYY-MM-DD'), 'NORMAL', 1,
    '孙七', '13800138000', 'sunqi@example.com',
    '资金托管账户', '用于资金托管的专用账户', 'FAILED', 1,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin'
);

-- 提交事务
COMMIT;

-- 查询验证数据
-- SELECT * FROM TC_ETICKET_ACCOUNT ORDER BY CREATE_TIME DESC;
