-- ============================================================
-- 华博云全球司库系统 - 基础配置管理模块数据库表
-- 数据库: 达梦数据库 DM8
-- 创建时间: 2026-01-14
-- 说明: 包含业务系统注册、数据映射配置、电票账户配置三张表
-- ============================================================

-- 1. 业务系统注册表
CREATE TABLE TBL_BUSINESS_SYSTEM_REGISTRY (
    ID BIGINT PRIMARY KEY,
    SYSTEM_NAME VARCHAR(200) NOT NULL,
    SYSTEM_CODE VARCHAR(100) NOT NULL UNIQUE,
    SYSTEM_TYPE VARCHAR(50),
    INTERFACE_URL VARCHAR(500),
    AUTH_TYPE VARCHAR(50),
    AUTH_CONFIG CLOB,
    DESCRIPTION VARCHAR(1000),
    SYSTEM_DESC VARCHAR(1000),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(100),
    UPDATE_USER VARCHAR(100)
);

COMMENT ON TABLE TBL_BUSINESS_SYSTEM_REGISTRY IS '业务系统注册表';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.ID IS '主键ID';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_NAME IS '系统名称';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_CODE IS '系统编码';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_TYPE IS '系统类型';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.INTERFACE_URL IS '接口地址';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.AUTH_TYPE IS '认证方式';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.AUTH_CONFIG IS '认证配置JSON';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.DESCRIPTION IS '系统描述';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_DESC IS '系统描述(别名)';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.CREATE_USER IS '创建人';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.UPDATE_USER IS '更新人';

CREATE INDEX IDX_BS_SYSTEM_CODE ON TBL_BUSINESS_SYSTEM_REGISTRY(SYSTEM_CODE);
CREATE INDEX IDX_BS_SYSTEM_TYPE ON TBL_BUSINESS_SYSTEM_REGISTRY(SYSTEM_TYPE);
CREATE INDEX IDX_BS_CREATE_TIME ON TBL_BUSINESS_SYSTEM_REGISTRY(CREATE_TIME);

-- 2. 数据映射配置表
CREATE TABLE TC_DATA_MAPPING (
    ID VARCHAR(50) PRIMARY KEY,
    SYSTEM_ID VARCHAR(50) NOT NULL,
    MAPPING_NAME VARCHAR(200) NOT NULL,
    SOURCE_FIELD VARCHAR(200) NOT NULL,
    TARGET_FIELD VARCHAR(200) NOT NULL,
    FIELD_TYPE VARCHAR(50),
    CONVERSION_RULE VARCHAR(500),
    DEFAULT_VALUE VARCHAR(200),
    IS_REQUIRED CHAR(1) DEFAULT '0',
    VALIDATION_RULE VARCHAR(500),
    ERROR_STRATEGY VARCHAR(200),
    SORT_ORDER INT DEFAULT 0,
    STATUS CHAR(1) DEFAULT '1',
    REMARK VARCHAR(1000),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(100),
    UPDATE_USER VARCHAR(100),
    VERSION_NO INT DEFAULT 1
);

COMMENT ON TABLE TC_DATA_MAPPING IS '数据映射配置表';
COMMENT ON COLUMN TC_DATA_MAPPING.ID IS '主键ID';
COMMENT ON COLUMN TC_DATA_MAPPING.SYSTEM_ID IS '系统ID';
COMMENT ON COLUMN TC_DATA_MAPPING.MAPPING_NAME IS '映射名称';
COMMENT ON COLUMN TC_DATA_MAPPING.SOURCE_FIELD IS '源字段';
COMMENT ON COLUMN TC_DATA_MAPPING.TARGET_FIELD IS '目标字段';
COMMENT ON COLUMN TC_DATA_MAPPING.FIELD_TYPE IS '字段类型';
COMMENT ON COLUMN TC_DATA_MAPPING.CONVERSION_RULE IS '转换规则';
COMMENT ON COLUMN TC_DATA_MAPPING.DEFAULT_VALUE IS '默认值';
COMMENT ON COLUMN TC_DATA_MAPPING.IS_REQUIRED IS '是否必填：1-是，0-否';
COMMENT ON COLUMN TC_DATA_MAPPING.VALIDATION_RULE IS '校验规则';
COMMENT ON COLUMN TC_DATA_MAPPING.ERROR_STRATEGY IS '错误处理策略';
COMMENT ON COLUMN TC_DATA_MAPPING.SORT_ORDER IS '排序顺序';
COMMENT ON COLUMN TC_DATA_MAPPING.STATUS IS '状态：1-启用，0-停用';
COMMENT ON COLUMN TC_DATA_MAPPING.REMARK IS '备注';
COMMENT ON COLUMN TC_DATA_MAPPING.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TC_DATA_MAPPING.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TC_DATA_MAPPING.CREATE_USER IS '创建人';
COMMENT ON COLUMN TC_DATA_MAPPING.UPDATE_USER IS '更新人';
COMMENT ON COLUMN TC_DATA_MAPPING.VERSION_NO IS '版本号';

CREATE INDEX IDX_DM_SYSTEM_ID ON TC_DATA_MAPPING(SYSTEM_ID);
CREATE INDEX IDX_DM_MAPPING_NAME ON TC_DATA_MAPPING(MAPPING_NAME);
CREATE INDEX IDX_DM_STATUS ON TC_DATA_MAPPING(STATUS);

-- 3. 电票账户设置表
CREATE TABLE TC_ETICKET_ACCOUNT (
    ID VARCHAR(50) PRIMARY KEY,
    BANK_ACCOUNT_ID VARCHAR(50),
    BANK_CODE VARCHAR(50),
    BANK_NAME VARCHAR(200),
    ACCOUNT_NO VARCHAR(100),
    CUSTOMER_NO VARCHAR(100),
    ETICKET_STATUS VARCHAR(50),
    BUSINESS_SCOPE VARCHAR(500),
    CURRENCY_CODES VARCHAR(200),
    DAILY_LIMIT DECIMAL(18,2),
    MONTHLY_LIMIT DECIMAL(18,2),
    INTERFACE_URL VARCHAR(500),
    INTERFACE_PORT INT,
    CERT_PATH VARCHAR(500),
    CERT_PASSWORD VARCHAR(200),
    OPERATOR_INFO VARCHAR(500),
    TIMEOUT_SETTING INT DEFAULT 30,
    RETRY_COUNT INT DEFAULT 3,
    LAST_CONNECT_TIME TIMESTAMP,
    CONNECTION_STATUS VARCHAR(50),
    STATUS CHAR(1) DEFAULT '1',
    REMARK VARCHAR(1000),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(100),
    UPDATE_USER VARCHAR(100),
    VERSION_NO INT DEFAULT 1
);

COMMENT ON TABLE TC_ETICKET_ACCOUNT IS '电票账户设置表';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ID IS '主键ID';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BANK_ACCOUNT_ID IS '银行账户ID';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BANK_CODE IS '银行代码';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BANK_NAME IS '银行名称';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ACCOUNT_NO IS '账户号码';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CUSTOMER_NO IS '客户号';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ETICKET_STATUS IS '电票状态';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BUSINESS_SCOPE IS '业务范围';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CURRENCY_CODES IS '币种代码';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.DAILY_LIMIT IS '日限额';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.MONTHLY_LIMIT IS '月限额';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.INTERFACE_URL IS '接口地址';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.INTERFACE_PORT IS '接口端口';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CERT_PATH IS '证书路径';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CERT_PASSWORD IS '证书密码';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.OPERATOR_INFO IS '操作员信息';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.TIMEOUT_SETTING IS '超时设置';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.RETRY_COUNT IS '重试次数';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.LAST_CONNECT_TIME IS '最后连接时间';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CONNECTION_STATUS IS '连接状态';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.STATUS IS '状态：1-启用，0-停用';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.REMARK IS '备注';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CREATE_USER IS '创建人';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.UPDATE_USER IS '更新人';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.VERSION_NO IS '版本号';

CREATE INDEX IDX_EA_BANK_CODE ON TC_ETICKET_ACCOUNT(BANK_CODE);
CREATE INDEX IDX_EA_ACCOUNT_NO ON TC_ETICKET_ACCOUNT(ACCOUNT_NO);
CREATE INDEX IDX_EA_STATUS ON TC_ETICKET_ACCOUNT(STATUS);

-- ============================================================
-- 插入测试数据
-- ============================================================

-- 插入业务系统测试数据
INSERT INTO TBL_BUSINESS_SYSTEM_REGISTRY (ID, SYSTEM_NAME, SYSTEM_CODE, SYSTEM_TYPE, INTERFACE_URL, AUTH_TYPE, AUTH_CONFIG, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
VALUES
(1705000000001, '财务共享系统', 'FINANCE_001', 'FINANCE', 'http://finance.internal/api', 'API_KEY', '{"apiKey":"test-key-001","timeout":30000}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin'),
(1705000000002, '工商银行系统', 'ICBC_001', 'BANK', 'https://icbc.com.cn/api', 'OAUTH2', '{"clientId":"icbc-client","clientSecret":"REDACTED"}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin'),
(1705000000003, 'ERP系统', 'ERP_001', 'ERP', 'http://erp.internal/api', 'JWT', '{"secret":"REDACTED"}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

-- 插入数据映射测试数据
INSERT INTO TC_DATA_MAPPING (ID, SYSTEM_ID, MAPPING_NAME, SOURCE_FIELD, TARGET_FIELD, FIELD_TYPE, CONVERSION_RULE, DEFAULT_VALUE, IS_REQUIRED, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
VALUES
('DM001', '1705000000001', '客户信息映射', 'CUSTOMER_ID', 'CUST_NO', 'STRING', 'DIRECT', NULL, '1', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin'),
('DM002', '1705000000001', '金额映射', 'AMOUNT', 'TXN_AMOUNT', 'DECIMAL', 'MULTIPLY:100', '0', '1', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin'),
('DM003', '1705000000002', '账号映射', 'ACCOUNT_NO', 'BANK_ACCT_NO', 'STRING', 'TRIM:LR', NULL, '1', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

-- 插入电票账户测试数据
INSERT INTO TC_ETICKET_ACCOUNT (ID, BANK_CODE, BANK_NAME, ACCOUNT_NO, CUSTOMER_NO, ETICKET_STATUS, BUSINESS_SCOPE, CURRENCY_CODES, DAILY_LIMIT, MONTHLY_LIMIT, INTERFACE_URL, INTERFACE_PORT, CERT_PATH, CERT_PASSWORD, TIMEOUT_SETTING, RETRY_COUNT, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
VALUES
('EA001', 'ICBC', '中国工商银行', '6222021234567890123', 'CUST001', 'ACTIVE', 'BANK_ACCEPTANCE,COMMERCIAL_ACCEPTANCE', 'CNY', 5000000.00, 150000000.00, 'https://icbc.com.cn/eticket/api', 443, '/certs/icbc/client.p12', '***', 30, 3, '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin'),
('EA002', 'CCB', '中国建设银行', '6227001234567890123', 'CUST002', 'ACTIVE', 'BANK_ACCEPTANCE', 'CNY', 3000000.00, 90000000.00, 'https://ccb.com.cn/eticket/api', 443, '/certs/ccb/client.p12', '***', 30, 3, '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

COMMIT;

-- 查询验证
SELECT '业务系统注册表' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM TBL_BUSINESS_SYSTEM_REGISTRY
UNION ALL
SELECT '数据映射配置表', COUNT(*) FROM TC_DATA_MAPPING
UNION ALL
SELECT '电票账户设置表', COUNT(*) FROM TC_ETICKET_ACCOUNT;
