-- =============================================
-- 印鉴使用记录表
-- 兼容达梦数据库、MySQL、Oracle
-- =============================================

-- 创建印鉴使用记录表
CREATE TABLE TBL_SEAL_USAGE_RECORD (
    ID BIGINT PRIMARY KEY,
    RECORD_NUMBER VARCHAR(50),
    SEAL_ID BIGINT,
    SEAL_CODE VARCHAR(50),
    SEAL_NAME VARCHAR(100),
    OPERATOR_ID VARCHAR(50),
    OPERATOR_NAME VARCHAR(100),
    BUSINESS_TYPE VARCHAR(50),
    BUSINESS_NUMBER VARCHAR(100),
    USAGE_STATUS VARCHAR(20),
    USAGE_TIME TIMESTAMP,
    USAGE_DESCRIPTION VARCHAR(500),
    APPROVER VARCHAR(100),
    APPROVAL_TIME TIMESTAMP,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 添加索引
CREATE INDEX IDX_SEAL_ID ON TBL_SEAL_USAGE_RECORD(SEAL_ID);
CREATE INDEX IDX_OPERATOR_NAME ON TBL_SEAL_USAGE_RECORD(OPERATOR_NAME);
CREATE INDEX IDX_BUSINESS_TYPE ON TBL_SEAL_USAGE_RECORD(BUSINESS_TYPE);
CREATE INDEX IDX_USAGE_STATUS ON TBL_SEAL_USAGE_RECORD(USAGE_STATUS);
CREATE INDEX IDX_USAGE_TIME ON TBL_SEAL_USAGE_RECORD(USAGE_TIME);

-- 添加表注释
COMMENT ON TABLE TBL_SEAL_USAGE_RECORD IS '印鉴使用记录表';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.ID IS '主键ID';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.RECORD_NUMBER IS '记录编号';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_ID IS '印鉴ID';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_CODE IS '印鉴编码';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_NAME IS '印鉴名称';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.OPERATOR_ID IS '使用人员ID';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.OPERATOR_NAME IS '使用人员姓名';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.BUSINESS_TYPE IS '业务类型';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.BUSINESS_NUMBER IS '业务单号';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_STATUS IS '使用状态';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_TIME IS '使用时间';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_DESCRIPTION IS '使用说明';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.APPROVER IS '审批人';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.APPROVAL_TIME IS '审批时间';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.REMARK IS '备注';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.UPDATE_TIME IS '更新时间';

-- 插入测试数据
INSERT INTO TBL_SEAL_USAGE_RECORD (ID, RECORD_NUMBER, SEAL_ID, SEAL_CODE, SEAL_NAME, OPERATOR_ID, OPERATOR_NAME, BUSINESS_TYPE, BUSINESS_NUMBER, USAGE_STATUS, USAGE_TIME, USAGE_DESCRIPTION, APPROVER, APPROVAL_TIME, CREATE_TIME, UPDATE_TIME)
VALUES (1, 'REC20241223001', 1001, 'SEAL001', '公司公章', 'U001', '张三', 'CONTRACT_SIGN', 'CTR20241223001', 'COMPLETED', SYSDATE, '合同签署使用', '李四', SYSDATE, SYSDATE, SYSDATE);

INSERT INTO TBL_SEAL_USAGE_RECORD (ID, RECORD_NUMBER, SEAL_ID, SEAL_CODE, SEAL_NAME, OPERATOR_ID, OPERATOR_NAME, BUSINESS_TYPE, BUSINESS_NUMBER, USAGE_STATUS, USAGE_TIME, USAGE_DESCRIPTION, CREATE_TIME, UPDATE_TIME)
VALUES (2, 'REC20241223002', 1002, 'SEAL002', '财务专用章', 'U002', '王五', 'FINANCIAL_REIMBURSEMENT', 'EXP20241223001', 'PENDING', SYSDATE, '财务报销使用', SYSDATE, SYSDATE);

INSERT INTO TBL_SEAL_USAGE_RECORD (ID, RECORD_NUMBER, SEAL_ID, SEAL_CODE, SEAL_NAME, OPERATOR_ID, OPERATOR_NAME, BUSINESS_TYPE, BUSINESS_NUMBER, USAGE_STATUS, USAGE_TIME, APPROVAL_TIME, CREATE_TIME, UPDATE_TIME)
VALUES (3, 'REC20241223003', 1001, 'SEAL001', '公司公章', 'U003', '赵六', 'AUTHORIZATION', 'AUTH20241223001', 'APPROVED', SYSDATE, SYSDATE, SYSDATE, SYSDATE);

COMMIT;
