-- =============================================
-- 安全参数配置表
-- 兼容达梦数据库、MySQL、Oracle
-- =============================================

-- 创建安全参数配置表
CREATE TABLE TBL_SECURITY_PARAMETER (
    ID BIGINT PRIMARY KEY,
    PARAM_CODE VARCHAR(50) UNIQUE NOT NULL,
    PARAM_NAME VARCHAR(100) NOT NULL,
    PARAM_TYPE VARCHAR(50) NOT NULL,
    PARAM_VALUE VARCHAR(500) NOT NULL,
    IS_ENABLED INT DEFAULT 1,
    DESCRIPTION VARCHAR(500),
    CREATE_BY VARCHAR(50),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(50),
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500)
);

-- 添加索引
CREATE INDEX IDX_PARAM_CODE ON TBL_SECURITY_PARAMETER(PARAM_CODE);
CREATE INDEX IDX_PARAM_TYPE ON TBL_SECURITY_PARAMETER(PARAM_TYPE);
CREATE INDEX IDX_IS_ENABLED ON TBL_SECURITY_PARAMETER(IS_ENABLED);

-- 添加表注释
COMMENT ON TABLE TBL_SECURITY_PARAMETER IS '安全参数配置表';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.ID IS '主键ID';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.PARAM_CODE IS '参数编码';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.PARAM_NAME IS '参数名称';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.PARAM_TYPE IS '参数类型';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.PARAM_VALUE IS '参数值';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.IS_ENABLED IS '是否启用(1-启用 0-禁用)';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.DESCRIPTION IS '参数描述';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_SECURITY_PARAMETER.REMARK IS '备注';

-- 插入初始配置数据
INSERT INTO TBL_SECURITY_PARAMETER (ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, PARAM_VALUE, IS_ENABLED, DESCRIPTION, CREATE_TIME, UPDATE_TIME)
VALUES (1, 'PASSWORD_MIN_LENGTH', '密码最小长度', 'PASSWORD_POLICY', '8', 1, '用户密码最小长度限制', SYSDATE, SYSDATE);

INSERT INTO TBL_SECURITY_PARAMETER (ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, PARAM_VALUE, IS_ENABLED, DESCRIPTION, CREATE_TIME, UPDATE_TIME)
VALUES (2, 'PASSWORD_MAX_LENGTH', '密码最大长度', 'PASSWORD_POLICY', '20', 1, '用户密码最大长度限制', SYSDATE, SYSDATE);

INSERT INTO TBL_SECURITY_PARAMETER (ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, PARAM_VALUE, IS_ENABLED, DESCRIPTION, CREATE_TIME, UPDATE_TIME)
VALUES (3, 'SESSION_TIMEOUT', '会话超时时间', 'SESSION_TIMEOUT', '30', 1, '用户会话超时时间(分钟)', SYSDATE, SYSDATE);

INSERT INTO TBL_SECURITY_PARAMETER (ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, PARAM_VALUE, IS_ENABLED, DESCRIPTION, CREATE_TIME, UPDATE_TIME)
VALUES (4, 'MAX_LOGIN_ATTEMPTS', '最大登录尝试次数', 'LOGIN_LIMIT', '5', 1, '用户最大登录失败次数', SYSDATE, SYSDATE);

INSERT INTO TBL_SECURITY_PARAMETER (ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, PARAM_VALUE, IS_ENABLED, DESCRIPTION, CREATE_TIME, UPDATE_TIME)
VALUES (5, 'IP_WHITELIST', 'IP白名单', 'ACCESS_CONTROL', '192.0.2.200/24', 1, '允许访问的IP地址白名单', SYSDATE, SYSDATE);

INSERT INTO TBL_SECURITY_PARAMETER (ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, PARAM_VALUE, IS_ENABLED, DESCRIPTION, CREATE_TIME, UPDATE_TIME)
VALUES (6, 'DATA_ENCRYPTION_KEY', '数据加密密钥', 'DATA_ENCRYPTION', 'AES256', 1, '数据加密算法和密钥配置', SYSDATE, SYSDATE);

INSERT INTO TBL_SECURITY_PARAMETER (ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, PARAM_VALUE, IS_ENABLED, DESCRIPTION, CREATE_TIME, UPDATE_TIME)
VALUES (7, 'AUDIT_LOG_RETENTION', '审计日志保留天数', 'AUDIT_LOG', '90', 1, '审计日志保留天数', SYSDATE, SYSDATE);

COMMIT;
