-- =============================================
-- 第三方账户管理表
-- 兼容达梦数据库、MySQL、Oracle
-- =============================================

-- 创建第三方账户管理表
CREATE TABLE TBL_THIRD_PARTY_ACCOUNT (
    ID BIGINT PRIMARY KEY,
    ACCOUNT_CODE VARCHAR(50) UNIQUE NOT NULL,
    ACCOUNT_NAME VARCHAR(100) NOT NULL,
    THIRD_PARTY_SYSTEM VARCHAR(50) NOT NULL,
    ACCOUNT_TYPE VARCHAR(50) NOT NULL,
    ACCOUNT_IDENTIFIER VARCHAR(200),
    AUTH_CONFIG CLOB,
    CONNECTION_STATUS VARCHAR(20) DEFAULT 'OFFLINE',
    LAST_SYNC_TIME TIMESTAMP,
    DESCRIPTION VARCHAR(500),
    IS_ENABLED INT DEFAULT 1,
    CREATE_BY VARCHAR(50),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(50),
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500)
);

-- 添加索引
CREATE INDEX IDX_ACCOUNT_CODE ON TBL_THIRD_PARTY_ACCOUNT(ACCOUNT_CODE);
CREATE INDEX IDX_THIRD_PARTY_SYSTEM ON TBL_THIRD_PARTY_ACCOUNT(THIRD_PARTY_SYSTEM);
CREATE INDEX IDX_ACCOUNT_TYPE ON TBL_THIRD_PARTY_ACCOUNT(ACCOUNT_TYPE);
CREATE INDEX IDX_CONNECTION_STATUS ON TBL_THIRD_PARTY_ACCOUNT(CONNECTION_STATUS);
CREATE INDEX IDX_IS_ENABLED ON TBL_THIRD_PARTY_ACCOUNT(IS_ENABLED);

-- 添加表注释
COMMENT ON TABLE TBL_THIRD_PARTY_ACCOUNT IS '第三方账户管理表';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.ID IS '主键ID';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.ACCOUNT_CODE IS '账户编码';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.ACCOUNT_NAME IS '账户名称';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.THIRD_PARTY_SYSTEM IS '第三方系统';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.ACCOUNT_TYPE IS '账户类型';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.ACCOUNT_IDENTIFIER IS '账户标识';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.AUTH_CONFIG IS '认证配置(JSON格式)';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.CONNECTION_STATUS IS '连接状态';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.LAST_SYNC_TIME IS '最后同步时间';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.DESCRIPTION IS '账户描述';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.IS_ENABLED IS '是否启用(1-启用 0-禁用)';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_THIRD_PARTY_ACCOUNT.REMARK IS '备注';

-- 插入测试数据
INSERT INTO TBL_THIRD_PARTY_ACCOUNT (ID, ACCOUNT_CODE, ACCOUNT_NAME, THIRD_PARTY_SYSTEM, ACCOUNT_TYPE, ACCOUNT_IDENTIFIER, AUTH_CONFIG, CONNECTION_STATUS, DESCRIPTION, IS_ENABLED, CREATE_TIME, UPDATE_TIME)
VALUES (1, 'ALIPAY001', '支付宝企业账户', 'ALIPAY', 'PAYMENT', 'dev@example.com', '{"appId": "2021001234567890", "privateKey": "***"}', 'ONLINE', '公司支付宝收款账户', 1, SYSDATE, SYSDATE);

INSERT INTO TBL_THIRD_PARTY_ACCOUNT (ID, ACCOUNT_CODE, ACCOUNT_NAME, THIRD_PARTY_SYSTEM, ACCOUNT_TYPE, ACCOUNT_IDENTIFIER, AUTH_CONFIG, CONNECTION_STATUS, DESCRIPTION, IS_ENABLED, CREATE_TIME, UPDATE_TIME)
VALUES (2, 'WECHAT001', '微信支付商户号', 'WECHAT_PAY', 'PAYMENT', 'mch_id_123456', '{"mchId": "1234567890", "apiKey": "***"}', 'ONLINE', '公司微信支付收款账户', 1, SYSDATE, SYSDATE);

INSERT INTO TBL_THIRD_PARTY_ACCOUNT (ID, ACCOUNT_CODE, ACCOUNT_NAME, THIRD_PARTY_SYSTEM, ACCOUNT_TYPE, ACCOUNT_IDENTIFIER, AUTH_CONFIG, CONNECTION_STATUS, DESCRIPTION, IS_ENABLED, CREATE_TIME, UPDATE_TIME)
VALUES (3, 'UNIONPAY001', '银联支付账户', 'UNIONPAY', 'SETTLEMENT', 'dev@example.com', '{"merId": "898123456789012", "cert": "***"}', 'OFFLINE', '银联支付结算账户', 1, SYSDATE, SYSDATE);

INSERT INTO TBL_THIRD_PARTY_ACCOUNT (ID, ACCOUNT_CODE, ACCOUNT_NAME, THIRD_PARTY_SYSTEM, ACCOUNT_TYPE, ACCOUNT_IDENTIFIER, CONNECTION_STATUS, DESCRIPTION, IS_ENABLED, CREATE_TIME, UPDATE_TIME)
VALUES (4, 'PAYPAL001', 'PayPal企业账户', 'PAYPAL', 'RECEIPT', 'dev@example.com', 'OFFLINE', 'PayPal收款账户(测试中)', 0, SYSDATE, SYSDATE);

COMMIT;
