-- ============================================================
-- 业务系统注册表 - 添加缺失列的SQL脚本
-- 数据库: 达梦数据库 (DM8)
-- 说明: 如果表已存在但缺少某些列,则自动添加缺失的列
-- 作者: 华博云开发团队
-- 日期: 2024-12-23
-- ============================================================

-- ============================================================
-- 方法1: 使用 CREATE TABLE IF NOT EXISTS (推荐)
-- ============================================================

-- 创建新表(如果不存在)
CREATE TABLE IF NOT EXISTS TBL_BUSINESS_SYSTEM_REGISTRY (
    ID NUMBER(20) NOT NULL,
    SYSTEM_NAME VARCHAR2(200) NOT NULL,
    SYSTEM_CODE VARCHAR2(100) NOT NULL,
    SYSTEM_TYPE VARCHAR2(50),
    API_URL VARCHAR2(500),
    AUTH_TYPE VARCHAR2(50),
    AUTH_CONFIG CLOB,
    DESCRIPTION VARCHAR2(1000),
    SYSTEM_DESC VARCHAR2(1000),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR2(100),
    UPDATE_USER VARCHAR2(100),
    CONSTRAINT PK_BUSINESS_SYSTEM_REGISTRY PRIMARY KEY (ID)
);

-- 添加表注释
COMMENT ON TABLE TBL_BUSINESS_SYSTEM_REGISTRY IS '业务系统注册表,用于存储各业务系统的连接和配置信息';

-- 添加列注释(如果列存在会报错但不会中断执行)
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.ID IS '主键ID';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_NAME IS '系统名称';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_CODE IS '系统编码,唯一标识';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_TYPE IS '系统类型(如:财务系统、OA系统、ERP系统等)';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.API_URL IS '接口地址';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.AUTH_TYPE IS '认证方式(如:TOKEN、OAUTH2、BASIC_AUTH等)';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.AUTH_CONFIG IS '认证配置JSON字符串';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.DESCRIPTION IS '系统描述';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_DESC IS '系统描述(备用字段)';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.CREATE_USER IS '创建人';
COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.UPDATE_USER IS '更新人';

-- 创建索引(如果不存在)
CREATE UNIQUE INDEX IF NOT EXISTS IDX_SYSTEM_CODE ON TBL_BUSINESS_SYSTEM_REGISTRY(SYSTEM_CODE);
COMMENT ON INDEX IDX_SYSTEM_CODE IS '系统编码唯一索引';

CREATE INDEX IF NOT EXISTS IDX_SYSTEM_NAME ON TBL_BUSINESS_SYSTEM_REGISTRY(SYSTEM_NAME);
COMMENT ON INDEX IDX_SYSTEM_NAME IS '系统名称索引';

CREATE INDEX IF NOT EXISTS IDX_SYSTEM_TYPE ON TBL_BUSINESS_SYSTEM_REGISTRY(SYSTEM_TYPE);
COMMENT ON INDEX IDX_SYSTEM_TYPE IS '系统类型索引';

CREATE INDEX IF NOT EXISTS IDX_CREATE_TIME ON TBL_BUSINESS_SYSTEM_REGISTRY(CREATE_TIME);
COMMENT ON INDEX IDX_CREATE_TIME IS '创建时间索引';

-- 创建序列(如果不存在)
CREATE SEQUENCE IF NOT EXISTS SEQ_BUSINESS_SYSTEM_REGISTRY
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    NOCACHE;
COMMENT ON SEQUENCE SEQ_BUSINESS_SYSTEM_REGISTRY IS '业务系统注册表主键序列';

-- ============================================================
-- 方法2: 使用 PL/SQL 动态添加缺失的列(兼容性更好)
-- ============================================================

-- 声明变量
DECLARE
    v_column_exists NUMBER;
BEGIN
    -- 检查并添加 SYSTEM_NAME 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'SYSTEM_NAME';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD SYSTEM_NAME VARCHAR2(200) NOT NULL';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_NAME IS ''系统名称''';
    END IF;

    -- 检查并添加 SYSTEM_CODE 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'SYSTEM_CODE';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD SYSTEM_CODE VARCHAR2(100) NOT NULL';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_CODE IS ''系统编码,唯一标识''';
    END IF;

    -- 检查并添加 SYSTEM_TYPE 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'SYSTEM_TYPE';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD SYSTEM_TYPE VARCHAR2(50)';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_TYPE IS ''系统类型(如:财务系统、OA系统、ERP系统等)''';
    END IF;

    -- 检查并添加 API_URL 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'API_URL';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD API_URL VARCHAR2(500)';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.API_URL IS ''接口地址''';
    END IF;

    -- 检查并添加 AUTH_TYPE 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'AUTH_TYPE';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD AUTH_TYPE VARCHAR2(50)';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.AUTH_TYPE IS ''认证方式(如:TOKEN、OAUTH2、BASIC_AUTH等)''';
    END IF;

    -- 检查并添加 AUTH_CONFIG 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'AUTH_CONFIG';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD AUTH_CONFIG CLOB';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.AUTH_CONFIG IS ''认证配置JSON字符串''';
    END IF;

    -- 检查并添加 DESCRIPTION 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'DESCRIPTION';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD DESCRIPTION VARCHAR2(1000)';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.DESCRIPTION IS ''系统描述''';
    END IF;

    -- 检查并添加 SYSTEM_DESC 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'SYSTEM_DESC';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD SYSTEM_DESC VARCHAR2(1000)';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.SYSTEM_DESC IS ''系统描述(备用字段)''';
    END IF;

    -- 检查并添加 CREATE_TIME 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'CREATE_TIME';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.CREATE_TIME IS ''创建时间''';
    END IF;

    -- 检查并添加 UPDATE_TIME 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'UPDATE_TIME';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.UPDATE_TIME IS ''更新时间''';
    END IF;

    -- 检查并添加 CREATE_USER 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'CREATE_USER';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD CREATE_USER VARCHAR2(100)';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.CREATE_USER IS ''创建人''';
    END IF;

    -- 检查并添加 UPDATE_USER 列
    SELECT COUNT(*) INTO v_column_exists
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
    AND COLUMN_NAME = 'UPDATE_USER';

    IF v_column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_BUSINESS_SYSTEM_REGISTRY ADD UPDATE_USER VARCHAR2(100)';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_BUSINESS_SYSTEM_REGISTRY.UPDATE_USER IS ''更新人''';
    END IF;

END;
/

-- ============================================================
-- 插入测试数据(仅当表为空时)
-- ============================================================

-- 声明变量
DECLARE
    v_row_count NUMBER;
BEGIN
    -- 检查表是否有数据
    SELECT COUNT(*) INTO v_row_count FROM TBL_BUSINESS_SYSTEM_REGISTRY;

    -- 只有当表为空时才插入测试数据
    IF v_row_count = 0 THEN
        -- 使用序列插入测试数据
        INSERT INTO TBL_BUSINESS_SYSTEM_REGISTRY (ID, SYSTEM_NAME, SYSTEM_CODE, SYSTEM_TYPE, API_URL, AUTH_TYPE, AUTH_CONFIG, DESCRIPTION, SYSTEM_DESC, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
        VALUES (SEQ_BUSINESS_SYSTEM_REGISTRY.NEXTVAL, '财务共享系统', 'FINANCIAL_SHARING', 'FINANCIAL', 'http://localhost:8001/api', 'TOKEN', '{"token": "REDACTED"}', '财务共享服务中心系统', '财务共享服务中心系统', TIMESTAMP '2024-12-01 10:00:00', TIMESTAMP '2024-12-01 10:00:00', 'admin', 'admin');

        INSERT INTO TBL_BUSINESS_SYSTEM_REGISTRY (ID, SYSTEM_NAME, SYSTEM_CODE, SYSTEM_TYPE, API_URL, AUTH_TYPE, AUTH_CONFIG, DESCRIPTION, SYSTEM_DESC, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
        VALUES (SEQ_BUSINESS_SYSTEM_REGISTRY.NEXTVAL, 'OA办公系统', 'OA_SYSTEM', 'OA', 'http://oa.example.com/api', 'OAUTH2', '{"clientId": "client123", "clientSecret": "REDACTED"}', '企业办公自动化系统', '企业办公自动化系统', TIMESTAMP '2024-12-02 14:30:00', TIMESTAMP '2024-12-02 14:30:00', 'admin', 'admin');

        INSERT INTO TBL_BUSINESS_SYSTEM_REGISTRY (ID, SYSTEM_NAME, SYSTEM_CODE, SYSTEM_TYPE, API_URL, AUTH_TYPE, AUTH_CONFIG, DESCRIPTION, SYSTEM_DESC, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
        VALUES (SEQ_BUSINESS_SYSTEM_REGISTRY.NEXTVAL, 'ERP企业资源规划', 'ERP_SYSTEM', 'ERP', 'http://erp.example.com/api', 'BASIC_AUTH', '{"username": "erp_user", "password": "REDACTED"}', '企业资源规划系统', '企业资源规划系统', TIMESTAMP '2024-12-03 09:15:00', TIMESTAMP '2024-12-03 09:15:00', 'admin', 'admin');

        INSERT INTO TBL_BUSINESS_SYSTEM_REGISTRY (ID, SYSTEM_NAME, SYSTEM_CODE, SYSTEM_TYPE, API_URL, AUTH_TYPE, AUTH_CONFIG, DESCRIPTION, SYSTEM_DESC, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
        VALUES (SEQ_BUSINESS_SYSTEM_REGISTRY.NEXTVAL, '人力资源系统', 'HR_SYSTEM', 'HR', 'http://hr.example.com/api', 'TOKEN', '{"token": "REDACTED"}', '人力资源管理系统', '人力资源管理系统', TIMESTAMP '2024-12-04 16:20:00', TIMESTAMP '2024-12-04 16:20:00', 'admin', 'admin');

        INSERT INTO TBL_BUSINESS_SYSTEM_REGISTRY (ID, SYSTEM_NAME, SYSTEM_CODE, SYSTEM_TYPE, API_URL, AUTH_TYPE, AUTH_CONFIG, DESCRIPTION, SYSTEM_DESC, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
        VALUES (SEQ_BUSINESS_SYSTEM_REGISTRY.NEXTVAL, '客户关系管理', 'CRM_SYSTEM', 'CRM', 'http://crm.example.com/api', 'API_KEY', '{"apiKey": "crm-key-789", "apiSecret": "REDACTED"}', '客户关系管理系统', '客户关系管理系统', TIMESTAMP '2024-12-05 11:45:00', TIMESTAMP '2024-12-05 11:45:00', 'admin', 'admin');

        INSERT INTO TBL_BUSINESS_SYSTEM_REGISTRY (ID, SYSTEM_NAME, SYSTEM_CODE, SYSTEM_TYPE, API_URL, AUTH_TYPE, AUTH_CONFIG, DESCRIPTION, SYSTEM_DESC, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
        VALUES (SEQ_BUSINESS_SYSTEM_REGISTRY.NEXTVAL, '供应链管理', 'SCM_SYSTEM', 'SCM', 'http://scm.example.com/api', 'TOKEN', '{"token": "REDACTED"}', '供应链管理系统', '供应链管理系统', TIMESTAMP '2024-12-06 13:30:00', TIMESTAMP '2024-12-06 13:30:00', 'admin', 'admin');

        DBMS_OUTPUT.PUT_LINE('成功插入6条测试数据');
    ELSE
        DBMS_OUTPUT.PUT_LINE('表已有数据,跳过测试数据插入');
    END IF;
END;
/

-- 提交事务
COMMIT;

-- ============================================================
-- 验证脚本执行结果
-- ============================================================

-- 查询表结构
-- SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, COMMENTS
-- FROM USER_COL_COMMENTS
-- WHERE TABLE_NAME = 'TBL_BUSINESS_SYSTEM_REGISTRY'
-- ORDER BY COLUMN_ID;

-- 查询数据量
-- SELECT COUNT(*) AS TOTAL_RECORDS FROM TBL_BUSINESS_SYSTEM_REGISTRY;

-- 查询测试数据
-- SELECT ID, SYSTEM_NAME, SYSTEM_CODE, SYSTEM_TYPE, CREATE_TIME
-- FROM TBL_BUSINESS_SYSTEM_REGISTRY
-- ORDER BY CREATE_TIME DESC;
