-- =============================================
-- 电票账户配置表 - 添加缺失的列
-- 表名: TC_ETICKET_ACCOUNT
-- 描述: 为现有表添加缺失的列
-- 作者: 华博云开发团队
-- 创建时间: 2024-12-24
-- 兼容性: 达梦数据库 (DM Database)
-- =============================================

-- 查询现有表结构
-- SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TC_ETICKET_ACCOUNT' ORDER BY COLUMN_ID;

-- 添加缺失的列(如果不存在)
-- 注意:执行前请先检查列是否已存在,避免重复添加

-- 1. 添加ETICKET_SYSTEM列(电票系统)
ALTER TABLE TC_ETICKET_ACCOUNT ADD ETICKET_SYSTEM VARCHAR(50);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ETICKET_SYSTEM IS '电票系统(ECDS/BECP/BANK_ETICKET)';

-- 2. 添加ACCOUNT_TYPE列(账户类型)
ALTER TABLE TC_ETICKET_ACCOUNT ADD ACCOUNT_TYPE VARCHAR(50);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ACCOUNT_TYPE IS '账户类型(ACCEPTANCE/DISCOUNT/REDISCOUNT/PLEDGE/CUSTODY/MARGIN)';

-- 3. 添加BANK_NAME列(开户银行名称)
ALTER TABLE TC_ETICKET_ACCOUNT ADD BANK_NAME VARCHAR(200);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BANK_NAME IS '开户银行名称';

-- 4. 添加BRANCH_NAME列(分支机构名称)
ALTER TABLE TC_ETICKET_ACCOUNT ADD BRANCH_NAME VARCHAR(200);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BRANCH_NAME IS '分支机构名称';

-- 5. 添加BANK_CODE列(银行编码)
ALTER TABLE TC_ETICKET_ACCOUNT ADD BANK_CODE VARCHAR(50);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BANK_CODE IS '银行编码(ICBC/CCB/ABC/BOC/BOCOM/CMB等)';

-- 6. 添加BANK_ACCOUNT_NUMBER列(银行账号)
ALTER TABLE TC_ETICKET_ACCOUNT ADD BANK_ACCOUNT_NUMBER VARCHAR(100);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.BANK_ACCOUNT_NUMBER IS '银行账号';

-- 7. 添加ACCOUNT_BALANCE列(账户余额)
ALTER TABLE TC_ETICKET_ACCOUNT ADD ACCOUNT_BALANCE DECIMAL(18,2) DEFAULT 0.00;
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ACCOUNT_BALANCE IS '账户余额';

-- 8. 添加CREDIT_LIMIT列(授信额度)
ALTER TABLE TC_ETICKET_ACCOUNT ADD CREDIT_LIMIT DECIMAL(18,2) DEFAULT 0.00;
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CREDIT_LIMIT IS '授信额度(万元)';

-- 9. 添加OPEN_DATE列(开户日期)
ALTER TABLE TC_ETICKET_ACCOUNT ADD OPEN_DATE DATE;
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.OPEN_DATE IS '开户日期';

-- 10. 添加ACCOUNT_STATUS列(账户状态)
ALTER TABLE TC_ETICKET_ACCOUNT ADD ACCOUNT_STATUS VARCHAR(20) DEFAULT 'NORMAL';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ACCOUNT_STATUS IS '账户状态(NORMAL正常/FROZEN冻结/CLOSED关闭)';

-- 11. 添加IS_ACTIVE列(是否启用)
ALTER TABLE TC_ETICKET_ACCOUNT ADD IS_ACTIVE INTEGER DEFAULT 1;
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.IS_ACTIVE IS '是否启用(1启用/0禁用)';

-- 12. 添加CONTACT_PERSON列(联系人)
ALTER TABLE TC_ETICKET_ACCOUNT ADD CONTACT_PERSON VARCHAR(100);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CONTACT_PERSON IS '联系人姓名';

-- 13. 添加CONTACT_PHONE列(联系电话)
ALTER TABLE TC_ETICKET_ACCOUNT ADD CONTACT_PHONE VARCHAR(50);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CONTACT_PHONE IS '联系电话';

-- 14. 添加CONTACT_EMAIL列(联系邮箱)
ALTER TABLE TC_ETICKET_ACCOUNT ADD CONTACT_EMAIL VARCHAR(100);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.CONTACT_EMAIL IS '联系邮箱';

-- 15. 添加REMARK列(备注)
ALTER TABLE TC_ETICKET_ACCOUNT ADD REMARK VARCHAR(500);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.REMARK IS '备注信息';

-- 16. 添加DESCRIPTION列(描述)
ALTER TABLE TC_ETICKET_ACCOUNT ADD DESCRIPTION VARCHAR(1000);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.DESCRIPTION IS '描述信息';

-- 17. 添加LAST_SYNC_TIME列(最后同步时间)
ALTER TABLE TC_ETICKET_ACCOUNT ADD LAST_SYNC_TIME TIMESTAMP;
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.LAST_SYNC_TIME IS '最后同步时间';

-- 18. 添加SYNC_STATUS列(同步状态)
ALTER TABLE TC_ETICKET_ACCOUNT ADD SYNC_STATUS VARCHAR(20) DEFAULT 'PENDING';
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.SYNC_STATUS IS '同步状态(SUCCESS成功/FAILED失败/PENDING待同步)';

-- 19. 添加ORG_ID列(组织ID)
ALTER TABLE TC_ETICKET_ACCOUNT ADD ORG_ID DECIMAL(20,0);
COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ORG_ID IS '组织ID';

-- 20. 添加ETICKET_ACCOUNT_ID主键列(如果不存在)
-- ALTER TABLE TC_ETICKET_ACCOUNT ADD ETICKET_ACCOUNT_ID DECIMAL(20,0);
-- COMMENT ON COLUMN TC_ETICKET_ACCOUNT.ETICKET_ACCOUNT_ID IS '电票账户ID(主键)';
-- ALTER TABLE TC_ETICKET_ACCOUNT ADD CONSTRAINT PK_ETICKET_ACCOUNT PRIMARY KEY (ETICKET_ACCOUNT_ID);

-- 提交事务
COMMIT;

-- 验证结果
-- SELECT * FROM TC_ETICKET_ACCOUNT WHERE ROWNUM <= 5;
