-- 查询现有数据,确定当前最大TRANSACTION_ID
SELECT MAX("TRANSACTION_ID") AS MAX_ID FROM "REDACTED"."TBL_SWAP_TRANSACTION";

-- 查看现有数据
SELECT "TRANSACTION_ID", "CONTRACT_CODE", "SWAP_TYPE", "CURRENCY", "STATUS"
FROM "REDACTED"."TBL_SWAP_TRANSACTION"
ORDER BY "TRANSACTION_ID";
