-- 检查ORG_ID分布问题
-- 如果用户ORG_ID不是1,会导致查询为空

SELECT '========== 检查ORG_ID分布 ==========' AS INFO;

-- 检查各表的ORG_ID分布
SELECT 'TBL_FORWARD_TRANSACTION ORG_ID分布:' AS INFO;
SELECT ORG_ID, COUNT(*) AS 记录数,
       SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS 活跃,
       SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END) AS 待生效
FROM TBL_FORWARD_TRANSACTION
WHERE DEL_FLAG = '0'
GROUP BY ORG_ID
ORDER BY ORG_ID;

SELECT 'TBL_OPTION_TRANSACTION ORG_ID分布:' AS INFO;
SELECT ORG_ID, COUNT(*) AS 记录数,
       SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS 活跃,
       SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END) AS 待生效
FROM TBL_OPTION_TRANSACTION
WHERE DEL_FLAG = '0'
GROUP BY ORG_ID
ORDER BY ORG_ID;

SELECT 'TBL_FUTURES_TRANSACTION ORG_ID分布:' AS INFO;
SELECT ORG_ID, COUNT(*) AS 记录数,
       SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS 活跃,
       SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END) AS 待生效
FROM TBL_FUTURES_TRANSACTION
WHERE DEL_FLAG = '0'
GROUP BY ORG_ID
ORDER BY ORG_ID;

SELECT 'TBL_SWAP_TRANSACTION ORG_ID分布:' AS INFO;
SELECT ORG_ID, COUNT(*) AS 记录数,
       SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS 活跃,
       SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END) AS 待生效
FROM TBL_SWAP_TRANSACTION
WHERE DEL_FLAG = '0'
GROUP BY ORG_ID
ORDER BY ORG_ID;

SELECT '========== 检查ORG_ID=1的数据详情 ==========' AS INFO;

-- 检查ORG_ID=1的详细数据
SELECT CONCAT(CONCAT('TBL_FORWARD_TRANSACTION (ORG_ID=1): ', COUNT(*)), ' 条') AS INFO
FROM TBL_FORWARD_TRANSACTION
WHERE ORG_ID = 1 AND DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING')

UNION ALL

SELECT CONCAT(CONCAT('TBL_OPTION_TRANSACTION (ORG_ID=1): ', COUNT(*)), ' 条') AS INFO
FROM TBL_OPTION_TRANSACTION
WHERE ORG_ID = 1 AND DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING')

UNION ALL

SELECT CONCAT(CONCAT('TBL_FUTURES_TRANSACTION (ORG_ID=1): ', COUNT(*)), ' 条') AS INFO
FROM TBL_FUTURES_TRANSACTION
WHERE ORG_ID = 1 AND DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING')

UNION ALL

SELECT CONCAT(CONCAT('TBL_SWAP_TRANSACTION (ORG_ID=1): ', COUNT(*)), ' 条') AS INFO
FROM TBL_SWAP_TRANSACTION
WHERE ORG_ID = 1 AND DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING');

-- 如果ORG_ID=1的数据很少或没有,需要更新数据
SELECT '========== 解决方案 ==========' AS INFO;
SELECT '如果ORG_ID=1的数据为0或很少,执行以下SQL:' AS INFO;
SELECT 'UPDATE TBL_FORWARD_TRANSACTION SET ORG_ID = 1 WHERE DEL_FLAG = ''0'';' AS INFO;
SELECT 'UPDATE TBL_OPTION_TRANSACTION SET ORG_ID = 1 WHERE DEL_FLAG = ''0'';' AS INFO;
SELECT 'UPDATE TBL_FUTURES_TRANSACTION SET ORG_ID = 1 WHERE DEL_FLAG = ''0'';' AS INFO;
SELECT 'UPDATE TBL_SWAP_TRANSACTION SET ORG_ID = 1 WHERE DEL_FLAG = ''0'';' AS INFO;
SELECT 'COMMIT;' AS INFO;
