-- 第四批合作伙伴直连功能 - 银行与合同管理相关表结构
-- 兼容达梦数据库语法

-- 1. 银行接口配置表 (实体类 TreasuryBankInterfaceConfig 已存在，这里提供表结构参考)
CREATE TABLE IF NOT EXISTS TBL_TREASURY_BANK_INTERFACE_CONFIG (
    INTERFACE_CONFIG_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    INTERFACE_CODE VARCHAR(100) NOT NULL COMMENT '接口编码',
    INTERFACE_NAME VARCHAR(200) NOT NULL COMMENT '接口名称',
    BANK_CODE VARCHAR(50) NOT NULL COMMENT '银行代码',
    BANK_NAME VARCHAR(200) NOT NULL COMMENT '银行名称',
    INTERFACE_TYPE VARCHAR(50) NOT NULL COMMENT '接口类型',
    PROTOCOL VARCHAR(20) NOT NULL COMMENT '接口协议',
    INTERFACE_VERSION VARCHAR(20) COMMENT '接口版本',
    REQUEST_METHOD VARCHAR(10) COMMENT '请求方法',
    SERVICE_URL VARCHAR(500) NOT NULL COMMENT '服务地址',
    SERVICE_PORT INTEGER COMMENT '服务端口',
    INTERFACE_PATH VARCHAR(500) COMMENT '接口路径',
    FULL_URL VARCHAR(1000) COMMENT '完整接口地址',
    REQUEST_HEADERS CLOB COMMENT '请求头（JSON格式）',
    REQUEST_TEMPLATE CLOB COMMENT '请求参数模板',
    RESPONSE_PARSE_RULE CLOB COMMENT '响应解析规则',
    AUTH_TYPE VARCHAR(50) NOT NULL COMMENT '认证方式',
    USERNAME VARCHAR(100) COMMENT '用户名',
    PASSWORD VARCHAR(500) COMMENT '密码',
    API_KEY VARCHAR(500) COMMENT 'API密钥',
    ACCESS_TOKEN VARCHAR(1000) COMMENT '访问令牌',
    TOKEN_TYPE VARCHAR(20) COMMENT '令牌类型',
    SIGN_ALGORITHM VARCHAR(20) COMMENT '签名算法',
    SIGN_SECRET VARCHAR(500) COMMENT '签名密钥',
    TIMESTAMP_FIELD VARCHAR(50) COMMENT '时间戳字段名',
    NONCE_FIELD VARCHAR(50) COMMENT '随机数字段名',
    CERT_PATH VARCHAR(500) COMMENT '证书路径',
    CERT_PASSWORD VARCHAR(200) COMMENT '证书密码',
    PUBLIC_KEY CLOB COMMENT '公钥',
    PRIVATE_KEY CLOB COMMENT '私钥',
    ENCRYPT_ALGORITHM VARCHAR(20) COMMENT '加密算法',
    ENCRYPT_KEY VARCHAR(500) COMMENT '加密密钥',
    ENCODING VARCHAR(20) DEFAULT 'UTF-8' COMMENT '编码格式',
    CONTENT_TYPE VARCHAR(100) DEFAULT 'application/json' COMMENT '内容类型',
    TIMEOUT_SECONDS INTEGER DEFAULT 30 COMMENT '超时时间（秒）',
    CONNECT_TIMEOUT INTEGER COMMENT '连接超时（秒）',
    READ_TIMEOUT INTEGER COMMENT '读取超时（秒）',
    RETRY_TIMES INTEGER DEFAULT 3 COMMENT '重试次数',
    RETRY_INTERVAL INTEGER DEFAULT 1000 COMMENT '重试间隔（毫秒）',
    CONNECTION_POOL_SIZE INTEGER COMMENT '连接池大小',
    MAX_CONNECTIONS INTEGER COMMENT '最大连接数',
    ENABLE_CONNECTION_POOL INTEGER DEFAULT 0 COMMENT '是否启用连接池',
    ENABLE_COMPRESSION INTEGER DEFAULT 0 COMMENT '是否启用压缩',
    VERIFY_SSL INTEGER DEFAULT 1 COMMENT '是否验证SSL证书',
    ENABLE_PROXY INTEGER DEFAULT 0 COMMENT '是否启用代理',
    PROXY_HOST VARCHAR(200) COMMENT '代理服务器地址',
    PROXY_PORT INTEGER COMMENT '代理服务器端口',
    PROXY_USERNAME VARCHAR(100) COMMENT '代理用户名',
    PROXY_PASSWORD VARCHAR(200) COMMENT '代理密码',
    SUPPORTED_BUSINESS_TYPES VARCHAR(500) COMMENT '支持的业务类型',
    INTERFACE_STATUS VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '接口状态',
    MONITOR_LEVEL VARCHAR(20) COMMENT '监控等级',
    DESCRIPTION CLOB COMMENT '接口描述',
    TEST_STATUS VARCHAR(20) COMMENT '测试状态',
    LAST_TEST_TIME TIMESTAMP COMMENT '最后测试时间',
    LAST_TEST_RESULT VARCHAR(1000) COMMENT '最后测试结果',
    DOCUMENT_URL VARCHAR(500) COMMENT '接口文档URL',
    CATEGORY VARCHAR(100) COMMENT '接口分类',
    TAGS VARCHAR(500) COMMENT '标签',
    ORG_ID BIGINT NOT NULL COMMENT '组织ID',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    CREATE_USER BIGINT COMMENT '创建用户',
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    UPDATE_USER BIGINT COMMENT '更新用户',
    IS_ENABLED INTEGER DEFAULT 1 COMMENT '是否启用'
);

-- 创建索引
CREATE INDEX IDX_BANK_INTERFACE_CODE ON TBL_TREASURY_BANK_INTERFACE_CONFIG(INTERFACE_CODE);
CREATE INDEX IDX_BANK_INTERFACE_BANK_CODE ON TBL_TREASURY_BANK_INTERFACE_CONFIG(BANK_CODE);
CREATE INDEX IDX_BANK_INTERFACE_TYPE ON TBL_TREASURY_BANK_INTERFACE_CONFIG(INTERFACE_TYPE);
CREATE INDEX IDX_BANK_INTERFACE_STATUS ON TBL_TREASURY_BANK_INTERFACE_CONFIG(INTERFACE_STATUS);
CREATE INDEX IDX_BANK_INTERFACE_ORG_ID ON TBL_TREASURY_BANK_INTERFACE_CONFIG(ORG_ID);
CREATE UNIQUE INDEX UNQ_BANK_INTERFACE_CODE_ORG ON TBL_TREASURY_BANK_INTERFACE_CONFIG(INTERFACE_CODE, ORG_ID) WHERE IS_DELETED = 0;

-- 2. 云连接合同表 (实体类 TreasuryCloudConnectionContract 已存在，这里提供表结构参考)
CREATE TABLE IF NOT EXISTS TBL_TREASURY_CLOUD_CONNECTION_CONTRACT (
    CONTRACT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CONTRACT_NO VARCHAR(100) NOT NULL COMMENT '合同编号',
    CONTRACT_NAME VARCHAR(500) NOT NULL COMMENT '合同名称',
    BANK_CODE VARCHAR(50) NOT NULL COMMENT '银行代码',
    BANK_NAME VARCHAR(200) NOT NULL COMMENT '银行名称',
    ACCOUNT_ID BIGINT COMMENT '账户ID',
    ACCOUNT_NUMBER VARCHAR(100) COMMENT '账户号码',
    ACCOUNT_NAME VARCHAR(200) COMMENT '账户名称',
    CONTRACT_TYPE VARCHAR(50) NOT NULL COMMENT '合同类型',
    CONTRACT_STATUS VARCHAR(50) NOT NULL COMMENT '合同状态',
    APPLICATION_DATE DATE COMMENT '申请日期',
    APPLICANT_ID BIGINT COMMENT '申请人ID',
    APPLICANT_NAME VARCHAR(100) COMMENT '申请人姓名',
    APPLICANT_DEPARTMENT VARCHAR(200) COMMENT '申请部门',
    QUALIFICATION_VERIFICATION_STATUS VARCHAR(50) COMMENT '资质验证状态',
    QUALIFICATION_VERIFICATION_TIME TIMESTAMP COMMENT '资质验证时间',
    QUALIFICATION_VERIFIER_ID BIGINT COMMENT '资质验证人ID',
    QUALIFICATION_VERIFIER_NAME VARCHAR(100) COMMENT '资质验证人姓名',
    VERIFICATION_RESULT VARCHAR(1000) COMMENT '资质验证结果',
    AGREEMENT_SIGNING_STATUS VARCHAR(50) COMMENT '协议签署状态',
    AGREEMENT_SIGNING_TIME TIMESTAMP COMMENT '协议签署时间',
    AGREEMENT_SIGNER_ID BIGINT COMMENT '协议签署人ID',
    AGREEMENT_SIGNER_NAME VARCHAR(100) COMMENT '协议签署人姓名',
    ELECTRONIC_CONTRACT_PATH VARCHAR(1000) COMMENT '电子合同文件路径',
    PAPER_CONTRACT_PATH VARCHAR(1000) COMMENT '纸质合同文件路径',
    SERVICE_ACTIVATION_STATUS VARCHAR(50) COMMENT '服务激活状态',
    SERVICE_ACTIVATION_TIME TIMESTAMP COMMENT '服务激活时间',
    SERVICE_ACTIVATOR_ID BIGINT COMMENT '服务激活人ID',
    SERVICE_ACTIVATOR_NAME VARCHAR(100) COMMENT '服务激活人姓名',
    CONTRACT_EFFECTIVE_DATE DATE COMMENT '合同生效日期',
    CONTRACT_EXPIRE_DATE DATE COMMENT '合同到期日期',
    CONTRACT_TERM_MONTHS INTEGER COMMENT '合同期限（月）',
    AUTO_RENEWAL INTEGER DEFAULT 0 COMMENT '是否自动续签',
    RENEWAL_REMINDER_DAYS INTEGER DEFAULT 30 COMMENT '续约提醒天数',
    NEXT_RENEWAL_DATE DATE COMMENT '下次续签日期',
    RENEWAL_COUNT INTEGER DEFAULT 0 COMMENT '续签次数',
    MAX_RENEWAL_COUNT INTEGER DEFAULT 0 COMMENT '最大续签次数',
    TERMINATION_REASON VARCHAR(1000) COMMENT '终止原因',
    TERMINATION_DATE DATE COMMENT '终止日期',
    TERMINATOR_ID BIGINT COMMENT '终止人ID',
    TERMINATOR_NAME VARCHAR(100) COMMENT '终止人姓名',
    SERVICE_FEE DECIMAL(20,2) COMMENT '服务费用',
    FEE_PERIOD VARCHAR(50) COMMENT '费用周期',
    PAYMENT_METHOD VARCHAR(50) COMMENT '费用支付方式',
    SERVICE_LEVEL VARCHAR(50) COMMENT '服务等级',
    SLA_DOCUMENT_PATH VARCHAR(1000) COMMENT '服务水平协议文件路径',
    CONTACT_NAME VARCHAR(100) COMMENT '联系人姓名',
    CONTACT_PHONE VARCHAR(50) COMMENT '联系人电话',
    CONTACT_EMAIL VARCHAR(200) COMMENT '联系人邮箱',
    TECHNICAL_SUPPORT_CONTACT VARCHAR(500) COMMENT '技术支持联系方式',
    BUSINESS_SUPPORT_CONTACT VARCHAR(500) COMMENT '业务支持联系方式',
    AVAILABILITY_GUARANTEE DECIMAL(5,2) COMMENT '服务可用性保证（百分比）',
    RECOVERY_TIME_REQUIREMENT INTEGER COMMENT '故障恢复时间要求（小时）',
    SPECIAL_TERMS CLOB COMMENT '特殊条款',
    CONTRACT_NOTES CLOB COMMENT '合同备注',
    APPROVAL_STATUS VARCHAR(50) COMMENT '审批状态',
    APPROVER_ID BIGINT COMMENT '审批人ID',
    APPROVER_NAME VARCHAR(100) COMMENT '审批人姓名',
    APPROVAL_TIME TIMESTAMP COMMENT '审批时间',
    APPROVAL_COMMENTS CLOB COMMENT '审批意见',
    CONTRACT_DOCUMENT_PATH VARCHAR(1000) COMMENT '合同文件存储路径',
    ATTACHMENT_PATHS CLOB COMMENT '相关附件路径',
    ORG_ID BIGINT NOT NULL COMMENT '组织ID',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    CREATE_USER BIGINT COMMENT '创建用户',
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    UPDATE_USER BIGINT COMMENT '更新用户',
    IS_ENABLED INTEGER DEFAULT 1 COMMENT '是否启用'
);

-- 创建索引
CREATE INDEX IDX_CLOUD_CONTRACT_NO ON TBL_TREASURY_CLOUD_CONNECTION_CONTRACT(CONTRACT_NO);
CREATE INDEX IDX_CLOUD_CONTRACT_BANK_CODE ON TBL_TREASURY_CLOUD_CONNECTION_CONTRACT(BANK_CODE);
CREATE INDEX IDX_CLOUD_CONTRACT_TYPE ON TBL_TREASURY_CLOUD_CONNECTION_CONTRACT(CONTRACT_TYPE);
CREATE INDEX IDX_CLOUD_CONTRACT_STATUS ON TBL_TREASURY_CLOUD_CONNECTION_CONTRACT(CONTRACT_STATUS);
CREATE INDEX IDX_CLOUD_CONTRACT_EXPIRE_DATE ON TBL_TREASURY_CLOUD_CONNECTION_CONTRACT(CONTRACT_EXPIRE_DATE);
CREATE INDEX IDX_CLOUD_CONTRACT_ORG_ID ON TBL_TREASURY_CLOUD_CONNECTION_CONTRACT(ORG_ID);
CREATE UNIQUE INDEX UNQ_CLOUD_CONTRACT_NO_ORG ON TBL_TREASURY_CLOUD_CONNECTION_CONTRACT(CONTRACT_NO, ORG_ID);

-- 3. 合作伙伴表 (实体类 TreasuryPartner 已存在，这里提供表结构参考)
-- 需要检查是否已存在，这里提供必要的字段补充

-- 4. 合作伙伴类型表 (实体类 TreasuryPartnerType 已存在，这里提供表结构参考)
-- 需要检查是否已存在，这里提供必要的字段补充

-- 5. 银行接口测试记录表
CREATE TABLE IF NOT EXISTS TBL_BANK_INTERFACE_TEST_LOG (
    TEST_LOG_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    INTERFACE_CONFIG_ID BIGINT NOT NULL COMMENT '接口配置ID',
    TEST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '测试时间',
    TEST_RESULT VARCHAR(20) NOT NULL COMMENT '测试结果：SUCCESS-成功，FAILED-失败',
    RESPONSE_TIME INTEGER COMMENT '响应时间（毫秒）',
    ERROR_CODE VARCHAR(100) COMMENT '错误代码',
    ERROR_MESSAGE VARCHAR(2000) COMMENT '错误信息',
    TEST_DATA CLOB COMMENT '测试数据',
    RESPONSE_DATA CLOB COMMENT '响应数据',
    TEST_USER_ID BIGINT COMMENT '测试用户ID',
    TEST_USER_NAME VARCHAR(100) COMMENT '测试用户姓名',
    REMARK VARCHAR(1000) COMMENT '备注',
    ORG_ID BIGINT NOT NULL COMMENT '组织ID'
);

-- 创建索引
CREATE INDEX IDX_BANK_TEST_INTERFACE_ID ON TBL_BANK_INTERFACE_TEST_LOG(INTERFACE_CONFIG_ID);
CREATE INDEX IDX_BANK_TEST_TIME ON TBL_BANK_INTERFACE_TEST_LOG(TEST_TIME);
CREATE INDEX IDX_BANK_TEST_RESULT ON TBL_BANK_INTERFACE_TEST_LOG(TEST_RESULT);
CREATE INDEX IDX_BANK_TEST_ORG_ID ON TBL_BANK_INTERFACE_TEST_LOG(ORG_ID);

-- 6. 合同履约记录表
CREATE TABLE IF NOT EXISTS TBL_CONTRACT_PERFORMANCE_RECORD (
    PERFORMANCE_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CONTRACT_ID BIGINT NOT NULL COMMENT '合同ID',
    RECORD_DATE DATE NOT NULL COMMENT '记录日期',
    PERFORMANCE_TYPE VARCHAR(50) NOT NULL COMMENT '履约类型',
    PERFORMANCE_STATUS VARCHAR(20) NOT NULL COMMENT '履约状态',
    SERVICE_AVAILABILITY DECIMAL(5,2) COMMENT '服务可用性（百分比）',
    RESPONSE_TIME AVG COMMENT '平均响应时间（毫秒）',
    SERVICE_QUALITY_SCORE DECIMAL(5,2) COMMENT '服务质量评分',
    ISSUE_COUNT INTEGER DEFAULT 0 COMMENT '问题数量',
    RESOLVED_ISSUE_COUNT INTEGER DEFAULT 0 COMMENT '已解决问题数量',
    PENDING_ISSUE_COUNT INTEGER DEFAULT 0 COMMENT '待解决问题数量',
    DETAILED_REPORT CLOB COMMENT '详细报告',
    ATTACHMENT_PATHS VARCHAR(2000) COMMENT '附件路径',
    RECORD_USER_ID BIGINT COMMENT '记录用户ID',
    RECORD_USER_NAME VARCHAR(100) COMMENT '记录用户姓名',
    REMARK VARCHAR(1000) COMMENT '备注',
    ORG_ID BIGINT NOT NULL COMMENT '组织ID',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
);

-- 创建索引
CREATE INDEX IDX_CONTRACT_PERFORMANCE_CONTRACT_ID ON TBL_CONTRACT_PERFORMANCE_RECORD(CONTRACT_ID);
CREATE INDEX IDX_CONTRACT_PERFORMANCE_DATE ON TBL_CONTRACT_PERFORMANCE_RECORD(RECORD_DATE);
CREATE INDEX IDX_CONTRACT_PERFORMANCE_TYPE ON TBL_CONTRACT_PERFORMANCE_RECORD(PERFORMANCE_TYPE);
CREATE INDEX IDX_CONTRACT_PERFORMANCE_ORG_ID ON TBL_CONTRACT_PERFORMANCE_RECORD(ORG_ID);

-- 7. 初始化数据
-- 银行列表数据
INSERT INTO TBL_DICTIONARY (DICT_CODE, DICT_NAME, DICT_TYPE, DICT_VALUE, DICT_SORT, REMARK, ORG_ID, CREATE_TIME, CREATE_USER, IS_ENABLED)
SELECT 'ICBC', '工商银行', 'BANK', 'ICBC', 1, '中国工商银行股份有限公司', 0, CURRENT_TIMESTAMP, 1, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TBL_DICTIONARY WHERE DICT_CODE = 'ICBC' AND DICT_TYPE = 'BANK');

INSERT INTO TBL_DICTIONARY (DICT_CODE, DICT_NAME, DICT_TYPE, DICT_VALUE, DICT_SORT, REMARK, ORG_ID, CREATE_TIME, CREATE_USER, IS_ENABLED)
SELECT 'CCB', '建设银行', 'BANK', 'CCB', 2, '中国建设银行股份有限公司', 0, CURRENT_TIMESTAMP, 1, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TBL_DICTIONARY WHERE DICT_CODE = 'CCB' AND DICT_TYPE = 'BANK');

INSERT INTO TBL_DICTIONARY (DICT_CODE, DICT_NAME, DICT_TYPE, DICT_VALUE, DICT_SORT, REMARK, ORG_ID, CREATE_TIME, CREATE_USER, IS_ENABLED)
SELECT 'ABC', '农业银行', 'BANK', 'ABC', 3, '中国农业银行股份有限公司', 0, CURRENT_TIMESTAMP, 1, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TBL_DICTIONARY WHERE DICT_CODE = 'ABC' AND DICT_TYPE = 'BANK');

INSERT INTO TBL_DICTIONARY (DICT_CODE, DICT_NAME, DICT_TYPE, DICT_VALUE, DICT_SORT, REMARK, ORG_ID, CREATE_TIME, CREATE_USER, IS_ENABLED)
SELECT 'BOC', '中国银行', 'BANK', 'BOC', 4, '中国银行股份有限公司', 0, CURRENT_TIMESTAMP, 1, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TBL_DICTIONARY WHERE DICT_CODE = 'BOC' AND DICT_TYPE = 'BANK');

-- 接口类型数据
INSERT INTO TBL_DICTIONARY (DICT_CODE, DICT_NAME, DICT_TYPE, DICT_VALUE, DICT_SORT, REMARK, ORG_ID, CREATE_TIME, CREATE_USER, IS_ENABLED)
SELECT 'ACCOUNT_QUERY', '账户查询', 'INTERFACE_TYPE', 'ACCOUNT_QUERY', 1, '银行账户查询接口', 0, CURRENT_TIMESTAMP, 1, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TBL_DICTIONARY WHERE DICT_CODE = 'ACCOUNT_QUERY' AND DICT_TYPE = 'INTERFACE_TYPE');

INSERT INTO TBL_DICTIONARY (DICT_CODE, DICT_NAME, DICT_TYPE, DICT_VALUE, DICT_SORT, REMARK, ORG_ID, CREATE_TIME, CREATE_USER, IS_ENABLED)
SELECT 'BALANCE_QUERY', '余额查询', 'INTERFACE_TYPE', 'BALANCE_QUERY', 2, '账户余额查询接口', 0, CURRENT_TIMESTAMP, 1, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TBL_DICTIONARY WHERE DICT_CODE = 'BALANCE_QUERY' AND DICT_TYPE = 'INTERFACE_TYPE');

INSERT INTO TBL_DICTIONARY (DICT_CODE, DICT_NAME, DICT_TYPE, DICT_VALUE, DICT_SORT, REMARK, ORG_ID, CREATE_TIME, CREATE_USER, IS_ENABLED)
SELECT 'TRANSACTION_QUERY', '交易查询', 'INTERFACE_TYPE', 'TRANSACTION_QUERY', 3, '交易记录查询接口', 0, CURRENT_TIMESTAMP, 1, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TBL_DICTIONARY WHERE DICT_CODE = 'TRANSACTION_QUERY' AND DICT_TYPE = 'INTERFACE_TYPE');

INSERT INTO TBL_DICTIONARY (DICT_CODE, DICT_NAME, DICT_TYPE, DICT_VALUE, DICT_SORT, REMARK, ORG_ID, CREATE_TIME, CREATE_USER, IS_ENABLED)
SELECT 'TRANSFER', '转账交易', 'INTERFACE_TYPE', 'TRANSFER', 4, '资金转账交易接口', 0, CURRENT_TIMESTAMP, 1, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TBL_DICTIONARY WHERE DICT_CODE = 'TRANSFER' AND DICT_TYPE = 'INTERFACE_TYPE');

-- 服务提供商数据
INSERT INTO TBL_DICTIONARY (DICT_CODE, DICT_NAME, DICT_TYPE, DICT_VALUE, DICT_SORT, REMARK, ORG_ID, CREATE_TIME, CREATE_USER, IS_ENABLED)
SELECT 'ALIYUN', '阿里云', 'SERVICE_PROVIDER', 'ALIYUN', 1, '阿里云计算有限公司', 0, CURRENT_TIMESTAMP, 1, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TBL_DICTIONARY WHERE DICT_CODE = 'ALIYUN' AND DICT_TYPE = 'SERVICE_PROVIDER');

INSERT INTO TBL_DICTIONARY (DICT_CODE, DICT_NAME, DICT_TYPE, DICT_VALUE, DICT_SORT, REMARK, ORG_ID, CREATE_TIME, CREATE_USER, IS_ENABLED)
SELECT 'TENCENT_CLOUD', '腾讯云', 'SERVICE_PROVIDER', 'TENCENT_CLOUD', 2, '腾讯云计算（北京）有限责任公司', 0, CURRENT_TIMESTAMP, 1, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TBL_DICTIONARY WHERE DICT_CODE = 'TENCENT_CLOUD' AND DICT_TYPE = 'SERVICE_PROVIDER');

INSERT INTO TBL_DICTIONARY (DICT_CODE, DICT_NAME, DICT_TYPE, DICT_VALUE, DICT_SORT, REMARK, ORG_ID, CREATE_TIME, CREATE_USER, IS_ENABLED)
SELECT 'HUAWEI_CLOUD', '华为云', 'SERVICE_PROVIDER', 'HUAWEI_CLOUD', 3, '华为软件技术有限公司', 0, CURRENT_TIMESTAMP, 1, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TBL_DICTIONARY WHERE DICT_CODE = 'HUAWEI_CLOUD' AND DICT_TYPE = 'SERVICE_PROVIDER');

COMMENT ON TABLE TBL_TREASURY_BANK_INTERFACE_CONFIG IS '银行接口配置表';
COMMENT ON TABLE TBL_TREASURY_CLOUD_CONNECTION_CONTRACT IS '云连接合同管理表';
COMMENT ON TABLE TBL_BANK_INTERFACE_TEST_LOG IS '银行接口测试记录表';
COMMENT ON TABLE TBL_CONTRACT_PERFORMANCE_RECORD IS '合同履约记录表';