-- Ukey厂商表创建SQL
-- 兼容达梦数据库
-- 创建Ukey厂商表
CREATE TABLE TBL_UKEY_VENDOR (
    ID VARCHAR(32) PRIMARY KEY,
    VENDOR_CODE VARCHAR(100) NOT NULL,
    VENDOR_NAME VARCHAR(200) NOT NULL,
    VENDOR_TYPE VARCHAR(50),
    VENDOR_LEVEL VARCHAR(50),
    CONTACT_PERSON VARCHAR(100),
    CONTACT_PHONE VARCHAR(20),
    CONTACT_EMAIL VARCHAR(200),
    COOPERATION_STATUS VARCHAR(50),
    EVALUATION_LEVEL VARCHAR(50),
    CERTIFICATE_INFO TEXT,
    AUTH_METHODS VARCHAR(500),
    REMARK TEXT,
    IS_ENABLED VARCHAR(1) DEFAULT '1',
    CREATE_BY VARCHAR(50),
    CREATE_TIME DATETIME,
    UPDATE_BY VARCHAR(50),
    UPDATE_TIME DATETIME
);

-- 创建索引
CREATE INDEX IDX_UKEY_VENDOR_CODE ON TBL_UKEY_VENDOR(VENDOR_CODE);
CREATE INDEX IDX_UKEY_VENDOR_NAME ON TBL_UKEY_VENDOR(VENDOR_NAME);
CREATE INDEX IDX_UKEY_VENDOR_TYPE ON TBL_UKEY_VENDOR(VENDOR_TYPE);
CREATE INDEX IDX_VENDOR_LEVEL ON TBL_UKEY_VENDOR(VENDOR_LEVEL);
CREATE INDEX IDX_COOPERATION_STATUS ON TBL_UKEY_VENDOR(COOPERATION_STATUS);
CREATE INDEX IDX_EVALUATION_LEVEL ON TBL_UKEY_VENDOR(EVALUATION_LEVEL);
CREATE INDEX IDX_CREATE_TIME ON TBL_UKEY_VENDOR(CREATE_TIME);

-- 插入一些示例数据
INSERT INTO TBL_UKEY_VENDOR (
    ID, VENDOR_CODE, VENDOR_NAME, VENDOR_TYPE, VENDOR_LEVEL, CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    COOPERATION_STATUS, EVALUATION_LEVEL, CERTIFICATE_INFO, AUTH_METHODS, REMARK, IS_ENABLED,
    CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
) VALUES (
    '1', 'VENDOR_001', '北京华博科技有限公司', 'SOFTWARE', 'LEVEL1', '张经理', '010-12345678', 'dev@example.com',
    'COOPERATION', 'EXCELLENT', '营业执照：91110108MA01234567X', 'RSA256,ECDSA', '核心Ukey供应商', '1',
    'admin', NOW(), 'admin', NOW()
);

INSERT INTO TBL_UKEY_VENDOR (
    ID, VENDOR_CODE, VENDOR_NAME, VENDOR_TYPE, VENDOR_LEVEL, CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    COOPERATION_STATUS, EVALUATION_LEVEL, CERTIFICATE_INFO, AUTH_METHODS, REMARK, IS_ENABLED,
    CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
) VALUES (
    '2', 'VENDOR_002', '上海天信安全设备公司', 'HARDWARE', 'LEVEL2', '李经理', '021-87654321', 'dev@example.com',
    'COOPERATION', 'GOOD', '资质证书：XXX-2024-001', 'RSA2048,SM2', '硬件Ukey制造商', '1',
    'admin', NOW(), 'admin', NOW()
);

INSERT INTO TBL_UKEY_VENDOR (
    ID, VENDOR_CODE, VENDOR_NAME, VENDOR_TYPE, VENDOR_LEVEL, CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    COOPERATION_STATUS, EVALUATION_LEVEL, CERTIFICATE_INFO, AUTH_METHODS, REMARK, IS_ENABLED,
    CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
) VALUES (
    '3', 'VENDOR_003', '深圳数字技术服务有限公司', 'SERVICE', 'LEVEL3', '王经理', '0755-11223344', 'dev@example.com',
    'PENDING', 'GENERAL', '服务资质：SZZJ-2024-002', 'RSA1024', '技术服务提供商', '1',
    'admin', NOW(), 'admin', NOW()
);

INSERT INTO TBL_UKEY_VENDOR (
    ID, VENDOR_CODE, VENDOR_NAME, VENDOR_TYPE, VENDOR_LEVEL, CONTACT_PERSON, CONTACT_PHONE, CONTACT_EMAIL,
    COOPERATION_STATUS, EVALUATION_LEVEL, CERTIFICATE_INFO, AUTH_METHODS, REMARK, IS_ENABLED,
    CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
) VALUES (
    '4', 'VENDOR_004', '广州盾安信息技术公司', 'HARDWARE', 'LEVEL2', '赵经理', '020-55667788', 'dev@example.com',
    'TERMINATED', 'POOR', '证书已过期', 'RSA2048', '已终止合作', '0',
    'admin', NOW(), 'admin', NOW()
);