-- ========================================
-- 票据管理模块缺失表创建脚本
-- 数据库: 达梦数据库 (DM DB)
-- 生成时间: 2025-12-29
-- ========================================

-- 1. 商业汇票表
CREATE TABLE TBL_COMMERCIAL_BILL (
    BILL_ID BIGINT PRIMARY KEY,
    BILL_NO VARCHAR(50) NOT NULL UNIQUE,
    BILL_TYPE VARCHAR(20) NOT NULL,
    BILL_STATUS VARCHAR(20) DEFAULT 'NORMAL',
    BILL_AMOUNT DECIMAL(18,2) NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    DRAWER_NAME VARCHAR(100),
    DRAWER_ACCOUNT VARCHAR(50),
    DRAWER_BANK VARCHAR(100),
    PAYEE_NAME VARCHAR(100),
    PAYEE_ACCOUNT VARCHAR(50),
    PAYEE_BANK VARCHAR(100),
    ACCEPTOR_NAME VARCHAR(100),
    ACCEPTOR_ACCOUNT VARCHAR(50),
    ACCEPTOR_BANK VARCHAR(100),
    ISSUE_LOCATION VARCHAR(100),
    GUARANTOR VARCHAR(100),
    REMARK VARCHAR(500),
    DELETE_FLAG INTEGER DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR VARCHAR(50),
    UPDATER VARCHAR(50)
);

COMMENT ON TABLE TBL_COMMERCIAL_BILL IS '商业汇票表';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.BILL_ID IS '汇票ID';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.BILL_NO IS '汇票号码';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.BILL_TYPE IS '汇票类型(银承/商承)';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.BILL_STATUS IS '汇票状态(NORMAL-正常/DISCOUNTED-已贴现/MATURED-已到期)';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.BILL_AMOUNT IS '汇票金额';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.ISSUE_DATE IS '出票日期';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.MATURITY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.DRAWER_NAME IS '出票人名称';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.DRAWER_ACCOUNT IS '出票人账号';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.DRAWER_BANK IS '出票人开户行';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.PAYEE_NAME IS '收款人名称';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.PAYEE_ACCOUNT IS '收款人账号';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.PAYEE_BANK IS '收款人开户行';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.ACCEPTOR_NAME IS '承兑人名称';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.ACCEPTOR_ACCOUNT IS '承兑人账号';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.ACCEPTOR_BANK IS '承兑人开户行';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.ISSUE_LOCATION IS '出票地点';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.GUARANTOR IS '保证人';
COMMENT ON COLUMN TBL_COMMERCIAL_BILL.DELETE_FLAG IS '删除标识(0-正常/1-删除)';

CREATE INDEX IDX_COMM_BILL_NO ON TBL_COMMERCIAL_BILL(BILL_NO);
CREATE INDEX IDX_COMM_BILL_TYPE ON TBL_COMMERCIAL_BILL(BILL_TYPE);
CREATE INDEX IDX_COMM_BILL_STATUS ON TBL_COMMERCIAL_BILL(BILL_STATUS);
CREATE INDEX IDX_COMM_ISSUE_DATE ON TBL_COMMERCIAL_BILL(ISSUE_DATE);
CREATE INDEX IDX_COMM_MATURITY_DATE ON TBL_COMMERCIAL_BILL(MATURITY_DATE);

-- 2. 票据风险评估表
CREATE TABLE TBL_BILL_RISK_ASSESSMENT (
    ASSESSMENT_ID BIGINT PRIMARY KEY,
    BILL_ID BIGINT NOT NULL,
    BILL_NUMBER VARCHAR(50),
    RISK_LEVEL VARCHAR(20) NOT NULL,
    RISK_SCORE INTEGER,
    RISK_DESCRIPTION VARCHAR(500),
    RISK_FACTORS CLOB,
    RECOMMENDATIONS VARCHAR(1000),
    ASSESSMENT_DATE DATE NOT NULL,
    ASSESSOR VARCHAR(50),
    DISPOSE_RESULT VARCHAR(500),
    DISPOSE_TIME TIMESTAMP,
    DISPOSER VARCHAR(50),
    DELETE_FLAG INTEGER DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR VARCHAR(50),
    UPDATER VARCHAR(50)
);

COMMENT ON TABLE TBL_BILL_RISK_ASSESSMENT IS '票据风险评估表';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.ASSESSMENT_ID IS '评估ID';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.BILL_ID IS '票据ID';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.BILL_NUMBER IS '票据号码';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_LEVEL IS '风险等级(HIGH-高/MEDIUM-中/LOW-低)';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_SCORE IS '风险评分(0-100)';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_DESCRIPTION IS '风险描述';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RISK_FACTORS IS '风险因素(JSON格式)';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.RECOMMENDATIONS IS '建议措施';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.ASSESSMENT_DATE IS '评估日期';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.ASSESSOR IS '评估人';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.DISPOSE_RESULT IS '处置结果';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.DISPOSE_TIME IS '处置时间';
COMMENT ON COLUMN TBL_BILL_RISK_ASSESSMENT.DISPOSER IS '处置人';

CREATE INDEX IDX_RISK_BILL_ID ON TBL_BILL_RISK_ASSESSMENT(BILL_ID);
CREATE INDEX IDX_RISK_LEVEL ON TBL_BILL_RISK_ASSESSMENT(RISK_LEVEL);
CREATE INDEX IDX_RISK_ASSESSMENT_DATE ON TBL_BILL_RISK_ASSESSMENT(ASSESSMENT_DATE);
CREATE INDEX IDX_RISK_SCORE ON TBL_BILL_RISK_ASSESSMENT(RISK_SCORE);

-- 3. 电子票据表
CREATE TABLE TBL_ELECTRONIC_BILL (
    BILL_ID BIGINT PRIMARY KEY,
    BILL_NO VARCHAR(50) NOT NULL UNIQUE,
    BILL_TYPE VARCHAR(20) NOT NULL,
    BILL_STATUS VARCHAR(20) DEFAULT 'NORMAL',
    BILL_AMOUNT DECIMAL(18,2) NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    DRAWER_NAME VARCHAR(100),
    DRAWER_ACCOUNT VARCHAR(50),
    DRAWER_BANK VARCHAR(100),
    PAYEE_NAME VARCHAR(100),
    PAYEE_ACCOUNT VARCHAR(50),
    PAYEE_BANK VARCHAR(100),
    ACCEPTOR_NAME VARCHAR(100),
    ACCEPTOR_ACCOUNT VARCHAR(50),
    ACCEPTOR_BANK VARCHAR(100),
    ELECTRONIC_SIGNATURE CLOB,
    SIGNATURE_STATUS VARCHAR(20) DEFAULT 'UNSIGNED',
    SIGNATURE_TIME TIMESTAMP,
    SIGNATORY VARCHAR(50),
    VERIFICATION_STATUS VARCHAR(20) DEFAULT 'UNVERIFIED',
    VERIFICATION_TIME TIMESTAMP,
    VERIFIER VARCHAR(50),
    TRACKING_INFO CLOB,
    REMARK VARCHAR(500),
    DELETE_FLAG INTEGER DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR VARCHAR(50),
    UPDATER VARCHAR(50)
);

COMMENT ON TABLE TBL_ELECTRONIC_BILL IS '电子票据表';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.BILL_ID IS '票据ID';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.BILL_NO IS '票据号码';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.BILL_TYPE IS '票据类型(银承/商承)';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.BILL_STATUS IS '票据状态(NORMAL-正常/DISCOUNTED-已贴现/MATURED-已到期)';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.BILL_AMOUNT IS '票据金额';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.ISSUE_DATE IS '出票日期';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.MATURITY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.DRAWER_NAME IS '出票人名称';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.DRAWER_ACCOUNT IS '出票人账号';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.DRAWER_BANK IS '出票人开户行';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.PAYEE_NAME IS '收款人名称';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.PAYEE_ACCOUNT IS '收款人账号';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.PAYEE_BANK IS '收款人开户行';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.ACCEPTOR_NAME IS '承兑人名称';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.ACCEPTOR_ACCOUNT IS '承兑人账号';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.ACCEPTOR_BANK IS '承兑人开户行';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.ELECTRONIC_SIGNATURE IS '电子签名(Base64编码)';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.SIGNATURE_STATUS IS '签名状态(UNSIGNED-未签名/SIGNED-已签名)';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.SIGNATURE_TIME IS '签名时间';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.SIGNATORY IS '签名方';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.VERIFICATION_STATUS IS '验证状态(UNVERIFIED-未验证/VERIFIED-已验证/FAILED-验证失败)';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.VERIFICATION_TIME IS '验证时间';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.VERIFIER IS '验证方';
COMMENT ON COLUMN TBL_ELECTRONIC_BILL.TRACKING_INFO IS '流转追踪信息(JSON格式)';

CREATE INDEX IDX_ELEC_BILL_NO ON TBL_ELECTRONIC_BILL(BILL_NO);
CREATE INDEX IDX_ELEC_BILL_TYPE ON TBL_ELECTRONIC_BILL(BILL_TYPE);
CREATE INDEX IDX_ELEC_BILL_STATUS ON TBL_ELECTRONIC_BILL(BILL_STATUS);
CREATE INDEX IDX_ELEC_SIGNATURE_STATUS ON TBL_ELECTRONIC_BILL(SIGNATURE_STATUS);
CREATE INDEX IDX_ELEC_VERIFICATION_STATUS ON TBL_ELECTRONIC_BILL(VERIFICATION_STATUS);

-- ========================================
-- 说明:
-- 1. 执行前请确认数据库连接正常
-- 2. 按顺序执行三个表的创建脚本
-- 3. 如表已存在，请先删除再创建: DROP TABLE TBL_XXX;
-- ========================================
