-- ================================================================================
-- 印鉴类型表 (TBL_SEAL_TYPE) - 智能创建/更新脚本
-- 达梦数据库 DM8 兼容
-- 功能: 检查表是否存在,不存在则创建,存在则检查并添加缺失的列
-- 创建日期: 2024-12-25
-- ================================================================================

DECLARE
    v_table_count INTEGER;
    v_column_count INTEGER;
BEGIN
    -- 检查表是否存在
    SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'TBL_SEAL_TYPE';

    -- 如果表不存在,则创建表
    IF v_table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE TBL_SEAL_TYPE (
                ID VARCHAR(32) NOT NULL,
                CODE VARCHAR(50) NOT NULL,
                NAME VARCHAR(100) NOT NULL,
                SEAL_LEVEL INT,
                SCOPE VARCHAR(500),
                DESCRIPTION VARCHAR(500),
                STATUS INT DEFAULT 1,
                CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CREATE_USER VARCHAR(50),
                UPDATE_USER VARCHAR(50),
                CONSTRAINT PK_TBL_SEAL_TYPE PRIMARY KEY (ID)
            )
        ';

        -- 添加表注释
        EXECUTE IMMEDIATE 'COMMENT ON TABLE TBL_SEAL_TYPE IS ''印鉴类型表''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.ID IS ''主键ID''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.CODE IS ''类型编码''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.NAME IS ''类型名称''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.SEAL_LEVEL IS ''印鉴级别(1-一级,2-二级,3-三级)''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.SCOPE IS ''适用范围''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.DESCRIPTION IS ''描述''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.STATUS IS ''状态(1-启用,0-禁用)''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.CREATE_TIME IS ''创建时间''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.UPDATE_TIME IS ''更新时间''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.CREATE_USER IS ''创建人''';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.UPDATE_USER IS ''更新人''';

        -- 创建索引
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEAL_TYPE_CODE ON TBL_SEAL_TYPE(CODE)';
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEAL_TYPE_STATUS ON TBL_SEAL_TYPE(STATUS)';
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEAL_TYPE_CREATE_TIME ON TBL_SEAL_TYPE(CREATE_TIME)';

        DBMS_OUTPUT.PUT_LINE('表 TBL_SEAL_TYPE 创建成功');
    ELSE
        -- 表已存在,检查并添加缺失的列
        -- 检查ID列
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_SEAL_TYPE' AND COLUMN_NAME = 'ID';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE TBL_SEAL_TYPE ADD ID VARCHAR(32) NOT NULL';
            EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.ID IS ''主键ID''';
        END IF;

        -- 检查CODE列
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_SEAL_TYPE' AND COLUMN_NAME = 'CODE';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE TBL_SEAL_TYPE ADD CODE VARCHAR(50) NOT NULL';
            EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.CODE IS ''类型编码''';
        END IF;

        -- 检查NAME列
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_SEAL_TYPE' AND COLUMN_NAME = 'NAME';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE TBL_SEAL_TYPE ADD NAME VARCHAR(100) NOT NULL';
            EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.NAME IS ''类型名称''';
        END IF;

        -- 检查SEAL_LEVEL列
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_SEAL_TYPE' AND COLUMN_NAME = 'SEAL_LEVEL';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE TBL_SEAL_TYPE ADD SEAL_LEVEL INT';
            EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.SEAL_LEVEL IS ''印鉴级别(1-一级,2-二级,3-三级)''';
        END IF;

        -- 检查SCOPE列
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_SEAL_TYPE' AND COLUMN_NAME = 'SCOPE';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE TBL_SEAL_TYPE ADD SCOPE VARCHAR(500)';
            EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.SCOPE IS ''适用范围''';
        END IF;

        -- 检查DESCRIPTION列
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_SEAL_TYPE' AND COLUMN_NAME = 'DESCRIPTION';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE TBL_SEAL_TYPE ADD DESCRIPTION VARCHAR(500)';
            EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.DESCRIPTION IS ''描述''';
        END IF;

        -- 检查STATUS列
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_SEAL_TYPE' AND COLUMN_NAME = 'STATUS';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE TBL_SEAL_TYPE ADD STATUS INT DEFAULT 1';
            EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.STATUS IS ''状态(1-启用,0-禁用)''';
        END IF;

        -- 检查CREATE_TIME列
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_SEAL_TYPE' AND COLUMN_NAME = 'CREATE_TIME';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE TBL_SEAL_TYPE ADD CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP';
            EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.CREATE_TIME IS ''创建时间''';
        END IF;

        -- 检查UPDATE_TIME列
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_SEAL_TYPE' AND COLUMN_NAME = 'UPDATE_TIME';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE TBL_SEAL_TYPE ADD UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP';
            EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.UPDATE_TIME IS ''更新时间''';
        END IF;

        -- 检查CREATE_USER列
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_SEAL_TYPE' AND COLUMN_NAME = 'CREATE_USER';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE TBL_SEAL_TYPE ADD CREATE_USER VARCHAR(50)';
            EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.CREATE_USER IS ''创建人''';
        END IF;

        -- 检查UPDATE_USER列
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_SEAL_TYPE' AND COLUMN_NAME = 'UPDATE_USER';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE TBL_SEAL_TYPE ADD UPDATE_USER VARCHAR(50)';
            EXECUTE IMMEDIATE 'COMMENT ON COLUMN TBL_SEAL_TYPE.UPDATE_USER IS ''更新人''';
        END IF;

        DBMS_OUTPUT.PUT_LINE('表 TBL_SEAL_TYPE 已存在,列检查完成');
    END IF;
END;
/

-- 检查并创建索引(不论表是新创建的还是已存在的)
BEGIN
    -- 检查并创建CODE索引
    IF NOT EXISTS (SELECT 1 FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SEAL_TYPE_CODE') THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEAL_TYPE_CODE ON TBL_SEAL_TYPE(CODE)';
    END IF;

    -- 检查并创建STATUS索引
    IF NOT EXISTS (SELECT 1 FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SEAL_TYPE_STATUS') THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEAL_TYPE_STATUS ON TBL_SEAL_TYPE(STATUS)';
    END IF;

    -- 检查并创建CREATE_TIME索引
    IF NOT EXISTS (SELECT 1 FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SEAL_TYPE_CREATE_TIME') THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEAL_TYPE_CREATE_TIME ON TBL_SEAL_TYPE(CREATE_TIME)';
    END IF;
END;
/

-- 插入测试数据(如果表为空)
BEGIN
    INSERT INTO TBL_SEAL_TYPE (ID, CODE, NAME, SEAL_LEVEL, SCOPE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
    SELECT '1', 'OFFICIAL_SEAL', '公章', 1, '全公司通用', '公司正式公章', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM TBL_SEAL_TYPE WHERE ID = '1');

    INSERT INTO TBL_SEAL_TYPE (ID, CODE, NAME, SEAL_LEVEL, SCOPE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
    SELECT '2', 'FINANCE_SEAL', '财务章', 2, '财务部门专用', '财务专用章', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM TBL_SEAL_TYPE WHERE ID = '2');

    INSERT INTO TBL_SEAL_TYPE (ID, CODE, NAME, SEAL_LEVEL, SCOPE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
    SELECT '3', 'CONTRACT_SEAL', '合同章', 1, '合同签署专用', '合同专用章', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM TBL_SEAL_TYPE WHERE ID = '3');

    INSERT INTO TBL_SEAL_TYPE (ID, CODE, NAME, SEAL_LEVEL, SCOPE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
    SELECT '4', 'LEGAL_SEAL', '法人章', 1, '法定代表人专用', '法定代表人名章', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM TBL_SEAL_TYPE WHERE ID = '4');

    INSERT INTO TBL_SEAL_TYPE (ID, CODE, NAME, SEAL_LEVEL, SCOPE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER)
    SELECT '5', 'DEPARTMENT_SEAL', '部门章', 3, '各部门内部使用', '部门内部章', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM TBL_SEAL_TYPE WHERE ID = '5');

    DBMS_OUTPUT.PUT_LINE('测试数据插入完成');
END;
/

COMMIT;

-- 验证结果
SELECT '表TBL_SEAL_TYPE的行数: ' || COUNT(*) as result FROM TBL_SEAL_TYPE;

-- 说明:
-- 1. 本脚本兼容达梦数据库(DM8),使用PL/SQL语法
-- 2. 智能判断表是否存在,不存在则创建,存在则检查列
-- 3. 自动创建索引和注释
-- 4. 只插入不存在的测试数据,避免重复
-- 5. 保留原有表数据,只添加缺失的列
