-- ============================================
-- 融资管理模块数据库建表脚本
-- 适用于: 达梦数据库 / Oracle / MySQL
-- 创建时间: 2025-12-30
-- ============================================

-- 1. 公司信息表
CREATE TABLE TBL_COMPANY_INFO (
    COMPANY_ID NUMBER(19) PRIMARY KEY,
    COMPANY_CODE VARCHAR2(50) NOT NULL,
    COMPANY_NAME VARCHAR2(200) NOT NULL,
    COMPANY_SHORT_NAME VARCHAR2(100),
    COMPANY_TYPE VARCHAR2(50),
    PARENT_ID NUMBER(19),
    CREDIT_CODE VARCHAR2(50),
    LEGAL_PERSON VARCHAR2(100),
    REGISTERED_CAPITAL NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    CONTACT_PERSON VARCHAR2(100),
    CONTACT_PHONE VARCHAR2(50),
    ADDRESS VARCHAR2(500),
    COMPANY_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_COMPANY_INFO IS '公司信息表';
COMMENT ON COLUMN TBL_COMPANY_INFO.COMPANY_ID IS '公司ID';
COMMENT ON COLUMN TBL_COMPANY_INFO.COMPANY_CODE IS '公司编码';
COMMENT ON COLUMN TBL_COMPANY_INFO.COMPANY_NAME IS '公司名称';
COMMENT ON COLUMN TBL_COMPANY_INFO.COMPANY_TYPE IS '公司类型';
COMMENT ON COLUMN TBL_COMPANY_INFO.PARENT_ID IS '上级公司ID';

-- 2. 银行信息表
CREATE TABLE TBL_BANK_INFO (
    BANK_ID NUMBER(19) PRIMARY KEY,
    BANK_CODE VARCHAR2(50) NOT NULL,
    BANK_NAME VARCHAR2(200) NOT NULL,
    BANK_SHORT_NAME VARCHAR2(100),
    BANK_TYPE VARCHAR2(50),
    SWIFT_CODE VARCHAR2(20),
    COUNTRY_CODE VARCHAR2(10),
    CONTACT_PERSON VARCHAR2(100),
    CONTACT_PHONE VARCHAR2(50),
    CONTACT_EMAIL VARCHAR2(100),
    ADDRESS VARCHAR2(500),
    BANK_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_BANK_INFO IS '银行信息表';
COMMENT ON COLUMN TBL_BANK_INFO.BANK_ID IS '银行ID';
COMMENT ON COLUMN TBL_BANK_INFO.BANK_CODE IS '银行编码';
COMMENT ON COLUMN TBL_BANK_INFO.BANK_NAME IS '银行名称';
COMMENT ON COLUMN TBL_BANK_INFO.SWIFT_CODE IS 'SWIFT代码';

-- 3. 融资计划表
CREATE TABLE TBL_FINANCING_PLAN (
    PLAN_ID NUMBER(19) PRIMARY KEY,
    PLAN_NO VARCHAR2(50) NOT NULL,
    PLAN_NAME VARCHAR2(200) NOT NULL,
    COMPANY_ID NUMBER(19),
    COMPANY_NAME VARCHAR2(200),
    PLAN_TYPE VARCHAR2(50),
    PLAN_YEAR NUMBER(4),
    PLAN_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    PLAN_STATUS VARCHAR2(20) DEFAULT 'DRAFT',
    START_DATE DATE,
    END_DATE DATE,
    DESCRIPTION VARCHAR2(1000),
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_FINANCING_PLAN IS '融资计划表';
COMMENT ON COLUMN TBL_FINANCING_PLAN.PLAN_ID IS '计划ID';
COMMENT ON COLUMN TBL_FINANCING_PLAN.PLAN_NO IS '计划编号';
COMMENT ON COLUMN TBL_FINANCING_PLAN.PLAN_NAME IS '计划名称';
COMMENT ON COLUMN TBL_FINANCING_PLAN.PLAN_TYPE IS '计划类型';
COMMENT ON COLUMN TBL_FINANCING_PLAN.PLAN_STATUS IS '计划状态';

-- 4. 融资合同表
CREATE TABLE TBL_FINANCING_CONTRACT (
    CONTRACT_ID NUMBER(19) PRIMARY KEY,
    CONTRACT_NO VARCHAR2(50) NOT NULL,
    CONTRACT_NAME VARCHAR2(200) NOT NULL,
    COMPANY_ID NUMBER(19),
    COMPANY_NAME VARCHAR2(200),
    BANK_ID NUMBER(19),
    BANK_NAME VARCHAR2(200),
    CONTRACT_TYPE VARCHAR2(50),
    CONTRACT_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    INTEREST_RATE NUMBER(10,6),
    RATE_TYPE VARCHAR2(20),
    START_DATE DATE,
    END_DATE DATE,
    CONTRACT_STATUS VARCHAR2(20) DEFAULT 'DRAFT',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_FINANCING_CONTRACT IS '融资合同表';
COMMENT ON COLUMN TBL_FINANCING_CONTRACT.CONTRACT_ID IS '合同ID';
COMMENT ON COLUMN TBL_FINANCING_CONTRACT.CONTRACT_NO IS '合同编号';
COMMENT ON COLUMN TBL_FINANCING_CONTRACT.CONTRACT_TYPE IS '合同类型';
COMMENT ON COLUMN TBL_FINANCING_CONTRACT.INTEREST_RATE IS '利率';

-- 5. 融资提款表
CREATE TABLE TBL_FINANCING_DRAWDOWN (
    DRAWDOWN_ID NUMBER(19) PRIMARY KEY,
    DRAWDOWN_NO VARCHAR2(50) NOT NULL,
    CONTRACT_ID NUMBER(19),
    CONTRACT_NO VARCHAR2(50),
    COMPANY_ID NUMBER(19),
    COMPANY_NAME VARCHAR2(200),
    DRAWDOWN_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    DRAWDOWN_DATE DATE,
    MATURITY_DATE DATE,
    INTEREST_RATE NUMBER(10,6),
    DRAWDOWN_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_FINANCING_DRAWDOWN IS '融资提款表';
COMMENT ON COLUMN TBL_FINANCING_DRAWDOWN.DRAWDOWN_ID IS '提款ID';
COMMENT ON COLUMN TBL_FINANCING_DRAWDOWN.DRAWDOWN_NO IS '提款编号';
COMMENT ON COLUMN TBL_FINANCING_DRAWDOWN.DRAWDOWN_AMOUNT IS '提款金额';

-- 6. 融资还款表
CREATE TABLE TBL_FINANCING_REPAYMENT (
    REPAYMENT_ID NUMBER(19) PRIMARY KEY,
    REPAYMENT_NO VARCHAR2(50) NOT NULL,
    DRAWDOWN_ID NUMBER(19),
    DRAWDOWN_NO VARCHAR2(50),
    COMPANY_ID NUMBER(19),
    COMPANY_NAME VARCHAR2(200),
    PRINCIPAL_AMOUNT NUMBER(20,2),
    INTEREST_AMOUNT NUMBER(20,2),
    TOTAL_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    PLAN_DATE DATE,
    ACTUAL_DATE DATE,
    REPAYMENT_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_FINANCING_REPAYMENT IS '融资还款表';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT.REPAYMENT_ID IS '还款ID';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT.PRINCIPAL_AMOUNT IS '本金金额';
COMMENT ON COLUMN TBL_FINANCING_REPAYMENT.INTEREST_AMOUNT IS '利息金额';

-- 7. 授信额度表
CREATE TABLE TBL_CREDIT_LINE (
    CREDIT_ID NUMBER(19) PRIMARY KEY,
    CREDIT_NO VARCHAR2(50) NOT NULL,
    COMPANY_ID NUMBER(19),
    COMPANY_NAME VARCHAR2(200),
    BANK_ID NUMBER(19),
    BANK_NAME VARCHAR2(200),
    CREDIT_TYPE VARCHAR2(50),
    CREDIT_AMOUNT NUMBER(20,2),
    USED_AMOUNT NUMBER(20,2) DEFAULT 0,
    AVAILABLE_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    START_DATE DATE,
    END_DATE DATE,
    CREDIT_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_CREDIT_LINE IS '授信额度表';
COMMENT ON COLUMN TBL_CREDIT_LINE.CREDIT_ID IS '授信ID';
COMMENT ON COLUMN TBL_CREDIT_LINE.CREDIT_AMOUNT IS '授信金额';
COMMENT ON COLUMN TBL_CREDIT_LINE.USED_AMOUNT IS '已用金额';
COMMENT ON COLUMN TBL_CREDIT_LINE.AVAILABLE_AMOUNT IS '可用金额';

-- 8. 授信申请表
CREATE TABLE TBL_CREDIT_APPLICATION (
    APPLICATION_ID NUMBER(19) PRIMARY KEY,
    APPLICATION_NO VARCHAR2(50) NOT NULL,
    COMPANY_ID NUMBER(19),
    COMPANY_NAME VARCHAR2(200),
    BANK_ID NUMBER(19),
    BANK_NAME VARCHAR2(200),
    CREDIT_TYPE VARCHAR2(50),
    APPLY_AMOUNT NUMBER(20,2),
    APPROVED_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    APPLY_DATE DATE,
    EXPECTED_START_DATE DATE,
    EXPECTED_END_DATE DATE,
    APPLICATION_STATUS VARCHAR2(20) DEFAULT 'DRAFT',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_CREDIT_APPLICATION IS '授信申请表';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.APPLICATION_ID IS '申请ID';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.APPLY_AMOUNT IS '申请金额';
COMMENT ON COLUMN TBL_CREDIT_APPLICATION.APPROVED_AMOUNT IS '批准金额';

-- 9. 担保表
CREATE TABLE TBL_GUARANTEE (
    GUARANTEE_ID NUMBER(19) PRIMARY KEY,
    GUARANTEE_NO VARCHAR2(50) NOT NULL,
    GUARANTEE_TYPE VARCHAR2(50),
    GUARANTOR_ID NUMBER(19),
    GUARANTOR_NAME VARCHAR2(200),
    BENEFICIARY_ID NUMBER(19),
    BENEFICIARY_NAME VARCHAR2(200),
    GUARANTEE_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    START_DATE DATE,
    END_DATE DATE,
    GUARANTEE_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_GUARANTEE IS '担保表';
COMMENT ON COLUMN TBL_GUARANTEE.GUARANTEE_ID IS '担保ID';
COMMENT ON COLUMN TBL_GUARANTEE.GUARANTEE_TYPE IS '担保类型';
COMMENT ON COLUMN TBL_GUARANTEE.GUARANTEE_AMOUNT IS '担保金额';

-- 10. 担保申请表
CREATE TABLE TBL_GUARANTEE_APPLICATION (
    APPLICATION_ID NUMBER(19) PRIMARY KEY,
    APPLICATION_NO VARCHAR2(50) NOT NULL,
    GUARANTEE_TYPE VARCHAR2(50),
    APPLICANT_ID NUMBER(19),
    APPLICANT_NAME VARCHAR2(200),
    GUARANTOR_ID NUMBER(19),
    GUARANTOR_NAME VARCHAR2(200),
    APPLY_AMOUNT NUMBER(20,2),
    APPROVED_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    APPLY_DATE DATE,
    EXPECTED_START_DATE DATE,
    EXPECTED_END_DATE DATE,
    APPLICATION_STATUS VARCHAR2(20) DEFAULT 'DRAFT',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_GUARANTEE_APPLICATION IS '担保申请表';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.APPLICATION_ID IS '申请ID';
COMMENT ON COLUMN TBL_GUARANTEE_APPLICATION.APPLY_AMOUNT IS '申请金额';

-- 11. 担保函表
CREATE TABLE TBL_GUARANTEE_LETTER (
    LETTER_ID NUMBER(19) PRIMARY KEY,
    LETTER_NO VARCHAR2(50) NOT NULL,
    GUARANTEE_ID NUMBER(19),
    LETTER_TYPE VARCHAR2(50),
    ISSUER_ID NUMBER(19),
    ISSUER_NAME VARCHAR2(200),
    BENEFICIARY_ID NUMBER(19),
    BENEFICIARY_NAME VARCHAR2(200),
    LETTER_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    ISSUE_DATE DATE,
    EXPIRY_DATE DATE,
    LETTER_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_GUARANTEE_LETTER IS '担保函表';
COMMENT ON COLUMN TBL_GUARANTEE_LETTER.LETTER_ID IS '担保函ID';
COMMENT ON COLUMN TBL_GUARANTEE_LETTER.LETTER_AMOUNT IS '担保函金额';

-- 12. 担保解除表
CREATE TABLE TBL_GUARANTEE_RELEASE (
    RELEASE_ID NUMBER(19) PRIMARY KEY,
    RELEASE_NO VARCHAR2(50) NOT NULL,
    GUARANTEE_ID NUMBER(19),
    GUARANTEE_NO VARCHAR2(50),
    RELEASE_TYPE VARCHAR2(50),
    RELEASE_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    RELEASE_DATE DATE,
    RELEASE_REASON VARCHAR2(500),
    RELEASE_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_GUARANTEE_RELEASE IS '担保解除表';
COMMENT ON COLUMN TBL_GUARANTEE_RELEASE.RELEASE_ID IS '解除ID';
COMMENT ON COLUMN TBL_GUARANTEE_RELEASE.RELEASE_AMOUNT IS '解除金额';

-- 13. 担保物表
CREATE TABLE TBL_COLLATERAL (
    COLLATERAL_ID NUMBER(19) PRIMARY KEY,
    COLLATERAL_NO VARCHAR2(50) NOT NULL,
    COLLATERAL_NAME VARCHAR2(200) NOT NULL,
    COLLATERAL_TYPE VARCHAR2(50),
    OWNER_ID NUMBER(19),
    OWNER_NAME VARCHAR2(200),
    ASSESSED_VALUE NUMBER(20,2),
    PLEDGED_VALUE NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    ASSESSMENT_DATE DATE,
    COLLATERAL_STATUS VARCHAR2(20) DEFAULT 'AVAILABLE',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_COLLATERAL IS '担保物表';
COMMENT ON COLUMN TBL_COLLATERAL.COLLATERAL_ID IS '担保物ID';
COMMENT ON COLUMN TBL_COLLATERAL.ASSESSED_VALUE IS '评估价值';
COMMENT ON COLUMN TBL_COLLATERAL.PLEDGED_VALUE IS '质押价值';

-- 14. 银行贷款表
CREATE TABLE TBL_BANK_LOAN (
    LOAN_ID NUMBER(19) PRIMARY KEY,
    LOAN_NO VARCHAR2(50) NOT NULL,
    LOAN_NAME VARCHAR2(200),
    COMPANY_ID NUMBER(19),
    COMPANY_NAME VARCHAR2(200),
    BANK_ID NUMBER(19),
    BANK_NAME VARCHAR2(200),
    LOAN_TYPE VARCHAR2(50),
    LOAN_AMOUNT NUMBER(20,2),
    OUTSTANDING_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    INTEREST_RATE NUMBER(10,6),
    RATE_TYPE VARCHAR2(20),
    START_DATE DATE,
    END_DATE DATE,
    LOAN_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_BANK_LOAN IS '银行贷款表';
COMMENT ON COLUMN TBL_BANK_LOAN.LOAN_ID IS '贷款ID';
COMMENT ON COLUMN TBL_BANK_LOAN.LOAN_AMOUNT IS '贷款金额';
COMMENT ON COLUMN TBL_BANK_LOAN.OUTSTANDING_AMOUNT IS '未还金额';

-- 15. 债券发行表
CREATE TABLE TBL_BOND_ISSUANCE (
    BOND_ID NUMBER(19) PRIMARY KEY,
    BOND_NO VARCHAR2(50) NOT NULL,
    BOND_NAME VARCHAR2(200) NOT NULL,
    COMPANY_ID NUMBER(19),
    COMPANY_NAME VARCHAR2(200),
    BOND_TYPE VARCHAR2(50),
    ISSUE_AMOUNT NUMBER(20,2),
    OUTSTANDING_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    COUPON_RATE NUMBER(10,6),
    ISSUE_DATE DATE,
    MATURITY_DATE DATE,
    BOND_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_BOND_ISSUANCE IS '债券发行表';
COMMENT ON COLUMN TBL_BOND_ISSUANCE.BOND_ID IS '债券ID';
COMMENT ON COLUMN TBL_BOND_ISSUANCE.ISSUE_AMOUNT IS '发行金额';
COMMENT ON COLUMN TBL_BOND_ISSUANCE.COUPON_RATE IS '票面利率';

-- 16. 融资租赁表
CREATE TABLE TBL_FINANCIAL_LEASE (
    LEASE_ID NUMBER(19) PRIMARY KEY,
    LEASE_NO VARCHAR2(50) NOT NULL,
    LEASE_NAME VARCHAR2(200),
    COMPANY_ID NUMBER(19),
    COMPANY_NAME VARCHAR2(200),
    LESSOR_ID NUMBER(19),
    LESSOR_NAME VARCHAR2(200),
    LEASE_TYPE VARCHAR2(50),
    LEASE_AMOUNT NUMBER(20,2),
    OUTSTANDING_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    INTEREST_RATE NUMBER(10,6),
    START_DATE DATE,
    END_DATE DATE,
    LEASE_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_FINANCIAL_LEASE IS '融资租赁表';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASE_ID IS '租赁ID';
COMMENT ON COLUMN TBL_FINANCIAL_LEASE.LEASE_AMOUNT IS '租赁金额';

-- 17. 利息计算表
CREATE TABLE TBL_INTEREST_CALCULATION (
    CALCULATION_ID NUMBER(19) PRIMARY KEY,
    DRAWDOWN_ID NUMBER(19),
    DRAWDOWN_NO VARCHAR2(50),
    CALCULATION_DATE DATE,
    START_DATE DATE,
    END_DATE DATE,
    PRINCIPAL_AMOUNT NUMBER(20,2),
    INTEREST_RATE NUMBER(10,6),
    INTEREST_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    CALCULATION_STATUS VARCHAR2(20) DEFAULT 'CALCULATED',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_INTEREST_CALCULATION IS '利息计算表';
COMMENT ON COLUMN TBL_INTEREST_CALCULATION.CALCULATION_ID IS '计算ID';
COMMENT ON COLUMN TBL_INTEREST_CALCULATION.INTEREST_AMOUNT IS '利息金额';

-- 18. 费用记录表
CREATE TABLE TBL_FEE_RECORD (
    FEE_ID NUMBER(19) PRIMARY KEY,
    FEE_NO VARCHAR2(50) NOT NULL,
    RELATED_ID NUMBER(19),
    RELATED_TYPE VARCHAR2(50),
    FEE_TYPE VARCHAR2(50),
    FEE_NAME VARCHAR2(200),
    FEE_AMOUNT NUMBER(20,2),
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'CNY',
    FEE_DATE DATE,
    PAYMENT_DATE DATE,
    FEE_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_FEE_RECORD IS '费用记录表';
COMMENT ON COLUMN TBL_FEE_RECORD.FEE_ID IS '费用ID';
COMMENT ON COLUMN TBL_FEE_RECORD.FEE_AMOUNT IS '费用金额';

-- 19. 汇率表
CREATE TABLE TBL_CURRENCY_RATE (
    RATE_ID NUMBER(19) PRIMARY KEY,
    BASE_CURRENCY VARCHAR2(10) NOT NULL,
    TARGET_CURRENCY VARCHAR2(10) NOT NULL,
    EXCHANGE_RATE NUMBER(20,8),
    RATE_DATE DATE,
    RATE_TYPE VARCHAR2(20),
    DATA_SOURCE VARCHAR2(100),
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_CURRENCY_RATE IS '汇率表';
COMMENT ON COLUMN TBL_CURRENCY_RATE.RATE_ID IS '汇率ID';
COMMENT ON COLUMN TBL_CURRENCY_RATE.EXCHANGE_RATE IS '汇率';

-- 20. 预警记录表
CREATE TABLE TBL_ALERT_RECORD (
    ALERT_ID NUMBER(19) PRIMARY KEY,
    ALERT_NO VARCHAR2(50) NOT NULL,
    ALERT_TYPE VARCHAR2(50),
    ALERT_LEVEL VARCHAR2(20),
    ALERT_TITLE VARCHAR2(200),
    ALERT_CONTENT VARCHAR2(2000),
    RELATED_ID NUMBER(19),
    RELATED_TYPE VARCHAR2(50),
    COMPANY_ID NUMBER(19),
    COMPANY_NAME VARCHAR2(200),
    ALERT_TIME DATE,
    HANDLE_TIME DATE,
    HANDLER VARCHAR2(100),
    HANDLE_RESULT VARCHAR2(500),
    ALERT_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    DELETE_FLAG NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TBL_ALERT_RECORD IS '预警记录表';
COMMENT ON COLUMN TBL_ALERT_RECORD.ALERT_ID IS '预警ID';
COMMENT ON COLUMN TBL_ALERT_RECORD.ALERT_LEVEL IS '预警级别';
COMMENT ON COLUMN TBL_ALERT_RECORD.ALERT_STATUS IS '预警状态';

-- ============================================
-- 创建索引
-- ============================================

-- 公司信息表索引
CREATE INDEX IDX_COMPANY_CODE ON TBL_COMPANY_INFO(COMPANY_CODE);
CREATE INDEX IDX_COMPANY_PARENT ON TBL_COMPANY_INFO(PARENT_ID);

-- 银行信息表索引
CREATE INDEX IDX_BANK_CODE ON TBL_BANK_INFO(BANK_CODE);

-- 融资计划表索引
CREATE INDEX IDX_PLAN_NO ON TBL_FINANCING_PLAN(PLAN_NO);
CREATE INDEX IDX_PLAN_COMPANY ON TBL_FINANCING_PLAN(COMPANY_ID);
CREATE INDEX IDX_PLAN_STATUS ON TBL_FINANCING_PLAN(PLAN_STATUS);

-- 融资合同表索引
CREATE INDEX IDX_CONTRACT_NO ON TBL_FINANCING_CONTRACT(CONTRACT_NO);
CREATE INDEX IDX_CONTRACT_COMPANY ON TBL_FINANCING_CONTRACT(COMPANY_ID);
CREATE INDEX IDX_CONTRACT_BANK ON TBL_FINANCING_CONTRACT(BANK_ID);

-- 融资提款表索引
CREATE INDEX IDX_DRAWDOWN_NO ON TBL_FINANCING_DRAWDOWN(DRAWDOWN_NO);
CREATE INDEX IDX_DRAWDOWN_CONTRACT ON TBL_FINANCING_DRAWDOWN(CONTRACT_ID);

-- 融资还款表索引
CREATE INDEX IDX_REPAYMENT_NO ON TBL_FINANCING_REPAYMENT(REPAYMENT_NO);
CREATE INDEX IDX_REPAYMENT_DRAWDOWN ON TBL_FINANCING_REPAYMENT(DRAWDOWN_ID);

-- 授信额度表索引
CREATE INDEX IDX_CREDIT_NO ON TBL_CREDIT_LINE(CREDIT_NO);
CREATE INDEX IDX_CREDIT_COMPANY ON TBL_CREDIT_LINE(COMPANY_ID);
CREATE INDEX IDX_CREDIT_BANK ON TBL_CREDIT_LINE(BANK_ID);

-- 担保表索引
CREATE INDEX IDX_GUARANTEE_NO ON TBL_GUARANTEE(GUARANTEE_NO);
CREATE INDEX IDX_GUARANTEE_GUARANTOR ON TBL_GUARANTEE(GUARANTOR_ID);

-- 银行贷款表索引
CREATE INDEX IDX_LOAN_NO ON TBL_BANK_LOAN(LOAN_NO);
CREATE INDEX IDX_LOAN_COMPANY ON TBL_BANK_LOAN(COMPANY_ID);
CREATE INDEX IDX_LOAN_BANK ON TBL_BANK_LOAN(BANK_ID);

-- 债券发行表索引
CREATE INDEX IDX_BOND_NO ON TBL_BOND_ISSUANCE(BOND_NO);
CREATE INDEX IDX_BOND_COMPANY ON TBL_BOND_ISSUANCE(COMPANY_ID);

-- 融资租赁表索引
CREATE INDEX IDX_LEASE_NO ON TBL_FINANCIAL_LEASE(LEASE_NO);
CREATE INDEX IDX_LEASE_COMPANY ON TBL_FINANCIAL_LEASE(COMPANY_ID);

-- 预警记录表索引
CREATE INDEX IDX_ALERT_NO ON TBL_ALERT_RECORD(ALERT_NO);
CREATE INDEX IDX_ALERT_COMPANY ON TBL_ALERT_RECORD(COMPANY_ID);
CREATE INDEX IDX_ALERT_STATUS ON TBL_ALERT_RECORD(ALERT_STATUS);

-- ============================================
-- 创建序列 (用于主键生成)
-- ============================================

CREATE SEQUENCE SEQ_COMPANY_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BANK_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PLAN_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONTRACT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DRAWDOWN_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REPAYMENT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CREDIT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CREDIT_APP_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GUARANTEE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GUARANTEE_APP_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LETTER_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RELEASE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COLLATERAL_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOAN_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BOND_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LEASE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CALCULATION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FEE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RATE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERT_ID START WITH 1 INCREMENT BY 1;

-- ============================================
-- 脚本执行完成
-- ============================================

COMMIT;

