-- 创建衍生品相关表 - 达梦数据库
-- 生成日期: 2026-01-21
-- 说明: 包含所有需要的衍生品交易表

-- ==================== 1. 远期交易表 ====================
-- 表名: TBL_FORWARD_TRANSACTION
-- 说明: 存储远期外汇、远期利率等远期合约数据

DROP TABLE IF EXISTS TBL_FORWARD_TRANSACTION;

CREATE TABLE TBL_FORWARD_TRANSACTION (
    TRANSACTION_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CONTRACT_CODE VARCHAR(50) NOT NULL,
    TRANSACTION_TYPE VARCHAR(50) NOT NULL,
    UNDERLYING_ASSET VARCHAR(100) NOT NULL,
    NOTIONAL_AMOUNT DECIMAL(20, 4) NOT NULL,
    CURRENCY VARCHAR(10) NOT NULL,
    FORWARD_PRICE DECIMAL(20, 6),
    TRADE_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    CURRENT_VALUE DECIMAL(20, 4),
    PNL DECIMAL(20, 4),
    COUNTERPARTY VARCHAR(200),
    COUNTERPARTY_RATING VARCHAR(20),
    TRADER VARCHAR(50),
    SALESPERSON VARCHAR(50),
    RISK_LIMIT DECIMAL(20, 4),
    MARGIN_REQUIREMENT DECIMAL(20, 4),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_TIME TIMESTAMP,
    UPDATE_BY VARCHAR(100),
    DEL_FLAG VARCHAR(1) DEFAULT '0',
    ORG_ID BIGINT NOT NULL
);

-- 添加注释
COMMENT ON TABLE TBL_FORWARD_TRANSACTION IS '远期交易表';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.TRANSACTION_TYPE IS '交易类型(FX_FORWARD-远期外汇, RATE_FORWARD-远期利率, COMMODITY_FORWARD-远期商品)';

-- 创建索引
CREATE INDEX IDX_FORWARD_CONTRACT ON TBL_FORWARD_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_FORWARD_TYPE ON TBL_FORWARD_TRANSACTION(TRANSACTION_TYPE);
CREATE INDEX IDX_FORWARD_STATUS ON TBL_FORWARD_TRANSACTION(STATUS);
CREATE INDEX IDX_FORWARD_CURRENCY ON TBL_FORWARD_TRANSACTION(CURRENCY);
CREATE INDEX IDX_FORWARD_MATURITY ON TBL_FORWARD_TRANSACTION(MATURITY_DATE);

-- ==================== 2. 期权交易表 ====================
-- 表名: TBL_OPTION_TRANSACTION
-- 说明: 存储看涨/看跌期权合约数据

DROP TABLE IF EXISTS TBL_OPTION_TRANSACTION;

CREATE TABLE TBL_OPTION_TRANSACTION (
    TRANSACTION_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CONTRACT_CODE VARCHAR(50) NOT NULL,
    OPTION_TYPE VARCHAR(10) NOT NULL,
    OPTION_STYLE VARCHAR(20) NOT NULL,
    UNDERLYING_ASSET VARCHAR(100) NOT NULL,
    CONTRACT_SIZE DECIMAL(20, 4) NOT NULL,
    STRIKE_PRICE DECIMAL(20, 6) NOT NULL,
    PREMIUM DECIMAL(20, 6) NOT NULL,
    THEORETICAL_VALUE DECIMAL(20, 6),
    CURRENCY VARCHAR(10) NOT NULL,
    TRADE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UNDERLYING_PRICE DECIMAL(20, 6),
    RISK_FREE_RATE DECIMAL(10, 6),
    VOLATILITY DECIMAL(10, 6),
    DIVIDEND_YIELD DECIMAL(10, 6),
    PRICING_MODEL VARCHAR(50),
    EXERCISE_TYPE VARCHAR(50),
    DELTA DECIMAL(10, 6),
    GAMMA DECIMAL(10, 6),
    THETA DECIMAL(10, 6),
    VEGA DECIMAL(10, 6),
    RHO DECIMAL(10, 6),
    COUNTERPARTY VARCHAR(200),
    COUNTERPARTY_RATING VARCHAR(20),
    TRADER VARCHAR(50),
    SALESPERSON VARCHAR(50),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_TIME TIMESTAMP,
    UPDATE_BY VARCHAR(100),
    DEL_FLAG VARCHAR(1) DEFAULT '0',
    ORG_ID BIGINT NOT NULL
);

-- 添加注释
COMMENT ON TABLE TBL_OPTION_TRANSACTION IS '期权交易表';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.OPTION_TYPE IS '期权类型(CALL-看涨, PUT-看跌)';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.OPTION_STYLE IS '期权风格(EUROPEAN-欧式, AMERICAN-美式, ASIAN-亚式)';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.PRICING_MODEL IS '定价模型(BLACK_SCHOLES, BINOMIAL_TREE, MONTE_CARLO)';

-- 创建索引
CREATE INDEX IDX_OPTION_CONTRACT ON TBL_OPTION_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_OPTION_TYPE ON TBL_OPTION_TRANSACTION(OPTION_TYPE);
CREATE INDEX IDX_OPTION_STYLE ON TBL_OPTION_TRANSACTION(OPTION_STYLE);
CREATE INDEX IDX_OPTION_STATUS ON TBL_OPTION_TRANSACTION(STATUS);
CREATE INDEX IDX_OPTION_EXPIRY ON TBL_OPTION_TRANSACTION(EXPIRY_DATE);

-- ==================== 3. 期货交易表 ====================
-- 表名: TBL_FUTURES_TRANSACTION
-- 说明: 存储商品期货、金融期货、股指期货等合约数据

DROP TABLE IF EXISTS TBL_FUTURES_TRANSACTION;

CREATE TABLE TBL_FUTURES_TRANSACTION (
    TRANSACTION_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CONTRACT_CODE VARCHAR(50) NOT NULL,
    FUTURES_TYPE VARCHAR(50) NOT NULL,
    UNDERLYING_ASSET VARCHAR(100) NOT NULL,
    DIRECTION VARCHAR(10) NOT NULL,
    CONTRACT_SIZE DECIMAL(20, 4) NOT NULL,
    OPEN_PRICE DECIMAL(20, 6) NOT NULL,
    CURRENT_PRICE DECIMAL(20, 6),
    CURRENCY VARCHAR(10) NOT NULL,
    TRADE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    INITIAL_MARGIN DECIMAL(20, 4),
    MAINTENANCE_MARGIN DECIMAL(20, 4),
    MARGIN_RATIO DECIMAL(10, 6),
    MARGIN DECIMAL(20, 4),
    UNREALIZED_PNL DECIMAL(20, 4),
    REALIZED_PNL DECIMAL(20, 4),
    "EXCHANGE" VARCHAR(50),
    BROKER VARCHAR(200),
    TRADER VARCHAR(50),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_TIME TIMESTAMP,
    UPDATE_BY VARCHAR(100),
    DEL_FLAG VARCHAR(1) DEFAULT '0',
    ORG_ID BIGINT NOT NULL
);

-- 添加注释
COMMENT ON TABLE TBL_FUTURES_TRANSACTION IS '期货交易表';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.FUTURES_TYPE IS '期货类型(COMMODITY-商品期货, FINANCIAL-金融期货, INDEX-股指期货, FX-外汇期货)';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.DIRECTION IS '交易方向(LONG-多头, SHORT-空头)';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION."EXCHANGE" IS '交易所(SHFE-上期所, DCE-大商所, CZCE-郑商所, CFFEX-中金所, INE-能源中心)';

-- 创建索引
CREATE INDEX IDX_FUTURES_CONTRACT ON TBL_FUTURES_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_FUTURES_TYPE ON TBL_FUTURES_TRANSACTION(FUTURES_TYPE);
CREATE INDEX IDX_FUTURES_STATUS ON TBL_FUTURES_TRANSACTION(STATUS);
CREATE INDEX IDX_FUTURES_CURRENCY ON TBL_FUTURES_TRANSACTION(CURRENCY);
CREATE INDEX IDX_FUTURES_EXCHANGE ON TBL_FUTURES_TRANSACTION("EXCHANGE");
CREATE INDEX IDX_FUTURES_EXPIRY ON TBL_FUTURES_TRANSACTION(EXPIRY_DATE);

-- ==================== 4. 掉期交易表 ====================
-- 表名: TBL_SWAP_TRANSACTION
-- 说明: 存储利率掉期、货币掉期等合约数据
-- 注意: 这个表可能已存在,如果存在会先删除再重建

DROP TABLE IF EXISTS TBL_SWAP_TRANSACTION;

CREATE TABLE TBL_SWAP_TRANSACTION (
    TRANSACTION_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CONTRACT_CODE VARCHAR(100) NOT NULL,
    SWAP_TYPE VARCHAR(50) NOT NULL,
    NOTIONAL_AMOUNT DECIMAL(20, 4) NOT NULL,
    CURRENCY VARCHAR(10) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    FIXED_RATE DECIMAL(10, 4),
    FLOATING_RATE_BASIS VARCHAR(50),
    SPREAD DECIMAL(10, 4),
    PAYMENT_FREQUENCY VARCHAR(50),
    DAY_COUNT_BASIS VARCHAR(20),
    PAY_DIRECTION VARCHAR(50),
    PAY_CURRENCY VARCHAR(10),
    RECEIVE_CURRENCY VARCHAR(10),
    PAY_NOTIONAL DECIMAL(20, 4),
    RECEIVE_NOTIONAL DECIMAL(20, 4),
    INITIAL_EXCHANGE_RATE DECIMAL(20, 4),
    EXCHANGE_PRINCIPAL VARCHAR(1),
    CURRENT_VALUE DECIMAL(20, 4),
    NEXT_PAYMENT_DATE DATE,
    STATUS VARCHAR(20) NOT NULL,
    COUNTERPARTY VARCHAR(200),
    COUNTERPARTY_RATING VARCHAR(20),
    REMARK VARCHAR(1000),
    ORG_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP(6),
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    DEL_FLAG VARCHAR(1) DEFAULT '0' NOT NULL
);

-- 添加注释
COMMENT ON TABLE TBL_SWAP_TRANSACTION IS '掉期交易表';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.SWAP_TYPE IS '掉期类型(INTEREST_RATE-利率掉期, CURRENCY-货币掉期, COMMODITY-商品掉期, CDS-信用违约掉期)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.FLOATING_RATE_BASIS IS '浮动利率基准(SHIBOR, LIBOR, LPR, EURIBOR等)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.PAYMENT_FREQUENCY IS '支付频率(DAILY, WEEKLY, MONTHLY, QUARTERLY, SEMI_ANNUAL, ANNUAL)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.DAY_COUNT_BASIS IS '日期计算基准(ACT_360, ACT_365, 30_360等)';

-- 创建索引
CREATE INDEX IDX_SWAP_CONTRACT ON TBL_SWAP_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_SWAP_TYPE ON TBL_SWAP_TRANSACTION(SWAP_TYPE);
CREATE INDEX IDX_SWAP_STATUS ON TBL_SWAP_TRANSACTION(STATUS);
CREATE INDEX IDX_SWAP_CURRENCY ON TBL_SWAP_TRANSACTION(CURRENCY);
CREATE INDEX IDX_SWAP_MATURITY ON TBL_SWAP_TRANSACTION(MATURITY_DATE);

-- ==================== 5. 衍生品预警表 ====================
-- 表名: TBL_DERIVATIVES_ALERT
-- 说明: 存储衍生品交易的预警信息

DROP TABLE IF EXISTS TBL_DERIVATIVES_ALERT;

CREATE TABLE TBL_DERIVATIVES_ALERT (
    ALERT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ALERT_NAME VARCHAR(200) NOT NULL,
    ALERT_TYPE VARCHAR(50) NOT NULL,
    MONITORING_METRIC VARCHAR(100) NOT NULL,
    THRESHOLD DECIMAL(20, 6) NOT NULL,
    CURRENT_VALUE DECIMAL(20, 6),
    ALERT_LEVEL VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    TRIGGER_TIME TIMESTAMP,
    NOTIFICATION_METHOD VARCHAR(200),
    DESCRIPTION VARCHAR(1000),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    UPDATE_TIME TIMESTAMP,
    UPDATE_BY VARCHAR(100),
    DEL_FLAG VARCHAR(1) DEFAULT '0',
    ORG_ID BIGINT NOT NULL
);

-- 添加注释
COMMENT ON TABLE TBL_DERIVATIVES_ALERT IS '衍生品预警表';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_TYPE IS '预警类型(PRICE_ALERT-价格预警, RISK_ALERT-风险预警, POSITION_ALERT-持仓预警, EXPIRY_ALERT-到期预警)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_LEVEL IS '预警级别(LOW-低, MEDIUM-中, HIGH-高, CRITICAL-紧急)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.STATUS IS '状态(ACTIVE-活跃, TRIGGERED-已触发, PROCESSED-已处理, IGNORED-已忽略)';

-- 创建索引
CREATE INDEX IDX_ALERT_TYPE ON TBL_DERIVATIVES_ALERT(ALERT_TYPE);
CREATE INDEX IDX_ALERT_LEVEL ON TBL_DERIVATIVES_ALERT(ALERT_LEVEL);
CREATE INDEX IDX_ALERT_STATUS ON TBL_DERIVATIVES_ALERT(STATUS);
CREATE INDEX IDX_ALERT_ORG ON TBL_DERIVATIVES_ALERT(ORG_ID);

-- ==================== 6. 衍生品市场数据表 ====================
-- 表名: TBL_DERIVATIVES_MARKET_DATA
-- 说明: 存储衍生品相关的市场数据

DROP TABLE IF EXISTS TBL_DERIVATIVES_MARKET_DATA;

CREATE TABLE TBL_DERIVATIVES_MARKET_DATA (
    MARKET_DATA_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ASSET_TYPE VARCHAR(50) NOT NULL,
    ASSET_CODE VARCHAR(50) NOT NULL,
    ASSET_NAME VARCHAR(100),
    CURRENT_PRICE DECIMAL(20, 6),
    PRICE_CHANGE DECIMAL(10, 6),
    VOLATILITY DECIMAL(10, 6),
    VOLUME DECIMAL(20, 4),
    OPEN_INTEREST DECIMAL(20, 4),
    DATA_SOURCE VARCHAR(50),
    DATA_TIME TIMESTAMP(6),
    CREATE_TIME TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    ORG_ID BIGINT
);

-- 添加注释
COMMENT ON TABLE TBL_DERIVATIVES_MARKET_DATA IS '衍生品市场数据表';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.ASSET_TYPE IS '资产类型(INDEX-指数, ETF-ETF, COMMODITY-商品, ENERGY-能源, CURRENCY-货币)';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.PRICE_CHANGE IS '价格变动(%)';

-- 创建索引
CREATE INDEX IDX_MARKET_DATA_TYPE ON TBL_DERIVATIVES_MARKET_DATA(ASSET_TYPE);
CREATE INDEX IDX_MARKET_DATA_CODE ON TBL_DERIVATIVES_MARKET_DATA(ASSET_CODE);
CREATE INDEX IDX_MARKET_DATA_TIME ON TBL_DERIVATIVES_MARKET_DATA(DATA_TIME);

COMMIT;

-- ==================== 验证表创建 ====================
SELECT '以下表已创建成功:' AS INFO;
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN (
    'TBL_FORWARD_TRANSACTION',
    'TBL_OPTION_TRANSACTION',
    'TBL_FUTURES_TRANSACTION',
    'TBL_SWAP_TRANSACTION',
    'TBL_DERIVATIVES_ALERT',
    'TBL_DERIVATIVES_MARKET_DATA'
) ORDER BY TABLE_NAME;
