-- ===================================================================
-- 决策支持模块数据库表创建脚本
-- 数据库类型: 达梦数据库/MySQL兼容
-- 创建日期: 2025-01-12
-- 说明: 包含5张核心表的创建语句,兼容达梦数据库和MySQL
-- ===================================================================

-- 表1: 决策模型表
CREATE TABLE TBL_DECISION_MODEL (
    MODEL_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    MODEL_CODE VARCHAR(50) NOT NULL,
    MODEL_NAME VARCHAR(200) NOT NULL,
    MODEL_TYPE VARCHAR(50) NOT NULL,
    ALGORITHM_TYPE VARCHAR(50) NOT NULL,
    MODEL_STATUS VARCHAR(20) NOT NULL,
    ACCURACY DECIMAL(5,4),
    LAST_TRAIN_TIME TIMESTAMP,
    MODEL_DESCRIPTION CLOB,
    INPUT_PARAMETERS CLOB,
    REMARK VARCHAR(500),
    ORG_ID BIGINT NOT NULL,
    CREATE_BY BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY BIGINT,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG CHAR(1) DEFAULT '0'
);

COMMENT ON TABLE TBL_DECISION_MODEL IS '决策模型表';
COMMENT ON COLUMN TBL_DECISION_MODEL.MODEL_ID IS '模型ID';
COMMENT ON COLUMN TBL_DECISION_MODEL.MODEL_CODE IS '模型编号';
COMMENT ON COLUMN TBL_DECISION_MODEL.MODEL_NAME IS '模型名称';
COMMENT ON COLUMN TBL_DECISION_MODEL.MODEL_TYPE IS '模型类型(RISK_ASSESSMENT/INVESTMENT_DECISION/FINANCING_DECISION/CASHFLOW_FORECAST)';
COMMENT ON COLUMN TBL_DECISION_MODEL.ALGORITHM_TYPE IS '算法类型(LINEAR_REGRESSION/LOGISTIC_REGRESSION/DECISION_TREE/RANDOM_FOREST/NEURAL_NETWORK)';
COMMENT ON COLUMN TBL_DECISION_MODEL.MODEL_STATUS IS '模型状态(ACTIVE/INACTIVE/TESTING)';
COMMENT ON COLUMN TBL_DECISION_MODEL.ACCURACY IS '准确率';
COMMENT ON COLUMN TBL_DECISION_MODEL.LAST_TRAIN_TIME IS '最后训练时间';
COMMENT ON COLUMN TBL_DECISION_MODEL.MODEL_DESCRIPTION IS '模型描述';
COMMENT ON COLUMN TBL_DECISION_MODEL.INPUT_PARAMETERS IS '输入参数(JSON格式)';
COMMENT ON COLUMN TBL_DECISION_MODEL.ORG_ID IS '组织ID';
COMMENT ON COLUMN TBL_DECISION_MODEL.DEL_FLAG IS '删除标志(0正常1删除)';

CREATE INDEX IDX_DM_MODEL_TYPE ON TBL_DECISION_MODEL(MODEL_TYPE);
CREATE INDEX IDX_DM_MODEL_STATUS ON TBL_DECISION_MODEL(MODEL_STATUS);
CREATE INDEX IDX_DM_ORG_ID ON TBL_DECISION_MODEL(ORG_ID);

-- 表2: 数据分析任务表
CREATE TABLE TBL_DATA_ANALYSIS_TASK (
    TASK_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    TASK_NO VARCHAR(50) NOT NULL,
    TASK_NAME VARCHAR(200) NOT NULL,
    TASK_TYPE VARCHAR(50) NOT NULL,
    ANALYSIS_TYPE VARCHAR(100) NOT NULL,
    DATA_SOURCE VARCHAR(200) NOT NULL,
    DATA_RANGE VARCHAR(500),
    ANALYSIS_PARAMETERS CLOB,
    MODEL_ID BIGINT,
    SCHEDULE_TYPE VARCHAR(20) NOT NULL,
    SCHEDULE_CRON VARCHAR(100),
    RESULT_FORMAT VARCHAR(20) NOT NULL,
    TASK_STATUS VARCHAR(20) NOT NULL,
    EXECUTION_TIME INT,
    EXECUTE_USER BIGINT,
    EXECUTION_RESULT CLOB,
    ERROR_MESSAGE CLOB,
    REMARK VARCHAR(500),
    ORG_ID BIGINT NOT NULL,
    CREATE_BY BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY BIGINT,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG CHAR(1) DEFAULT '0'
);

COMMENT ON TABLE TBL_DATA_ANALYSIS_TASK IS '数据分析任务表';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.TASK_ID IS '任务ID';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.TASK_NO IS '任务编号';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.TASK_NAME IS '任务名称';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.TASK_TYPE IS '任务类型(DESCRIPTIVE/DIAGNOSTIC/PREDICTIVE/PRESCRIPTIVE)';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.ANALYSIS_TYPE IS '分析类型';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.DATA_SOURCE IS '数据源';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.ANALYSIS_PARAMETERS IS '分析参数(JSON格式)';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.MODEL_ID IS '关联模型ID';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.SCHEDULE_TYPE IS '调度类型(MANUAL/SCHEDULED/TRIGGERED)';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.SCHEDULE_CRON IS '调度表达式(cron表达式)';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.RESULT_FORMAT IS '结果格式(JSON/XML/CSV/EXCEL)';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.TASK_STATUS IS '任务状态(PENDING/RUNNING/COMPLETED/FAILED/CANCELLED)';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.EXECUTION_TIME IS '执行时长(秒)';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.ORG_ID IS '组织ID';
COMMENT ON COLUMN TBL_DATA_ANALYSIS_TASK.DEL_FLAG IS '删除标志(0正常1删除)';

CREATE UNIQUE INDEX IDX_DAT_TASK_NO ON TBL_DATA_ANALYSIS_TASK(TASK_NO);
CREATE INDEX IDX_DAT_TASK_TYPE ON TBL_DATA_ANALYSIS_TASK(TASK_TYPE);
CREATE INDEX IDX_DAT_TASK_STATUS ON TBL_DATA_ANALYSIS_TASK(TASK_STATUS);
CREATE INDEX IDX_DAT_ORG_ID ON TBL_DATA_ANALYSIS_TASK(ORG_ID);
CREATE INDEX IDX_DAT_MODEL_ID ON TBL_DATA_ANALYSIS_TASK(MODEL_ID);

-- 表3: KPI指标表
CREATE TABLE TBL_KPI_INDICATOR (
    KPI_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    KPI_CODE VARCHAR(50) NOT NULL,
    KPI_NAME VARCHAR(200) NOT NULL,
    KPI_CATEGORY VARCHAR(50) NOT NULL,
    KPI_TYPE VARCHAR(50) NOT NULL,
    CALCULATION_FORMULA CLOB NOT NULL,
    DATA_SOURCE VARCHAR(200) NOT NULL,
    UNIT VARCHAR(20),
    TARGET_VALUE DECIMAL(18,2),
    WARNING_THRESHOLD DECIMAL(18,2),
    CRITICAL_THRESHOLD DECIMAL(18,2),
    CURRENT_VALUE DECIMAL(18,2),
    CALCULATION_FREQUENCY VARCHAR(20) NOT NULL,
    TREND VARCHAR(10),
    KPI_STATUS VARCHAR(20) NOT NULL,
    CALCULATION_DATE DATE,
    REMARK VARCHAR(500),
    ORG_ID BIGINT NOT NULL,
    CREATE_BY BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY BIGINT,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG CHAR(1) DEFAULT '0'
);

COMMENT ON TABLE TBL_KPI_INDICATOR IS 'KPI指标表';
COMMENT ON COLUMN TBL_KPI_INDICATOR.KPI_ID IS 'KPI ID';
COMMENT ON COLUMN TBL_KPI_INDICATOR.KPI_CODE IS 'KPI编码';
COMMENT ON COLUMN TBL_KPI_INDICATOR.KPI_NAME IS 'KPI名称';
COMMENT ON COLUMN TBL_KPI_INDICATOR.KPI_CATEGORY IS 'KPI分类(FINANCIAL/OPERATIONAL/RISK/PERFORMANCE/CUSTOMER/PROCESS)';
COMMENT ON COLUMN TBL_KPI_INDICATOR.KPI_TYPE IS 'KPI类型(FINANCIAL/OPERATIONAL/RISK/PERFORMANCE)';
COMMENT ON COLUMN TBL_KPI_INDICATOR.CALCULATION_FORMULA IS '计算公式';
COMMENT ON COLUMN TBL_KPI_INDICATOR.DATA_SOURCE IS '数据源';
COMMENT ON COLUMN TBL_KPI_INDICATOR.UNIT IS '单位';
COMMENT ON COLUMN TBL_KPI_INDICATOR.TARGET_VALUE IS '目标值';
COMMENT ON COLUMN TBL_KPI_INDICATOR.WARNING_THRESHOLD IS '预警阈值';
COMMENT ON COLUMN TBL_KPI_INDICATOR.CRITICAL_THRESHOLD IS '临界阈值';
COMMENT ON COLUMN TBL_KPI_INDICATOR.CURRENT_VALUE IS '当前值';
COMMENT ON COLUMN TBL_KPI_INDICATOR.CALCULATION_FREQUENCY IS '计算频率(REAL_TIME/HOURLY/DAILY/WEEKLY/MONTHLY)';
COMMENT ON COLUMN TBL_KPI_INDICATOR.TREND IS '趋势(UP/DOWN/STABLE)';
COMMENT ON COLUMN TBL_KPI_INDICATOR.KPI_STATUS IS 'KPI状态(NORMAL/WARNING/CRITICAL/INACTIVE)';
COMMENT ON COLUMN TBL_KPI_INDICATOR.CALCULATION_DATE IS '计算日期';
COMMENT ON COLUMN TBL_KPI_INDICATOR.ORG_ID IS '组织ID';
COMMENT ON COLUMN TBL_KPI_INDICATOR.DEL_FLAG IS '删除标志(0正常1删除)';

CREATE UNIQUE INDEX IDX_KPI_CODE ON TBL_KPI_INDICATOR(KPI_CODE, ORG_ID);
CREATE INDEX IDX_KPI_CATEGORY ON TBL_KPI_INDICATOR(KPI_CATEGORY);
CREATE INDEX IDX_KPI_TYPE ON TBL_KPI_INDICATOR(KPI_TYPE);
CREATE INDEX IDX_KPI_STATUS ON TBL_KPI_INDICATOR(KPI_STATUS);
CREATE INDEX IDX_KPI_ORG_ID ON TBL_KPI_INDICATOR(ORG_ID);

-- 表4: 预测分析表
CREATE TABLE TBL_PREDICTIVE_ANALYSIS (
    ANALYSIS_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ANALYSIS_NO VARCHAR(50) NOT NULL,
    ANALYSIS_NAME VARCHAR(200) NOT NULL,
    PREDICTION_TYPE VARCHAR(50) NOT NULL,
    MODEL_ID BIGINT NOT NULL,
    INPUT_DATA CLOB NOT NULL,
    PREDICTION_RESULT CLOB,
    ACTUAL_RESULT CLOB,
    CONFIDENCE_INTERVAL CLOB,
    PREDICTION_PERIOD VARCHAR(20) NOT NULL,
    PREDICTION_HORIZON INT NOT NULL,
    CONFIDENCE_LEVEL DECIMAL(5,2) NOT NULL,
    ACCURACY DECIMAL(5,2),
    DEVIATION_ANALYSIS CLOB,
    ANALYSIS_STATUS VARCHAR(20) NOT NULL,
    ANALYSIS_DATE DATE,
    REMARK VARCHAR(500),
    ORG_ID BIGINT NOT NULL,
    CREATE_BY BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY BIGINT,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG CHAR(1) DEFAULT '0'
);

COMMENT ON TABLE TBL_PREDICTIVE_ANALYSIS IS '预测分析表';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.ANALYSIS_ID IS '分析ID';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.ANALYSIS_NO IS '分析编号';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.ANALYSIS_NAME IS '分析名称';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.PREDICTION_TYPE IS '预测类型(CASH_FLOW/EXCHANGE_RATE/INTEREST_RATE/RISK_METRIC/MARKET_TREND)';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.MODEL_ID IS '关联模型ID';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.INPUT_DATA IS '输入数据(JSON格式)';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.PREDICTION_RESULT IS '预测结果(JSON格式)';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.ACTUAL_RESULT IS '实际结果(JSON格式)';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.CONFIDENCE_INTERVAL IS '置信区间(JSON格式)';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.PREDICTION_PERIOD IS '预测周期(DAILY/WEEKLY/MONTHLY/QUARTERLY/YEARLY)';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.PREDICTION_HORIZON IS '预测期限(天)';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.CONFIDENCE_LEVEL IS '置信水平(0-100)';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.ACCURACY IS '准确率(百分比)';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.DEVIATION_ANALYSIS IS '偏差分析结果';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.ANALYSIS_STATUS IS '分析状态(PENDING/RUNNING/COMPLETED/FAILED)';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.ANALYSIS_DATE IS '分析日期';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.ORG_ID IS '组织ID';
COMMENT ON COLUMN TBL_PREDICTIVE_ANALYSIS.DEL_FLAG IS '删除标志(0正常1删除)';

CREATE UNIQUE INDEX IDX_PA_ANALYSIS_NO ON TBL_PREDICTIVE_ANALYSIS(ANALYSIS_NO);
CREATE INDEX IDX_PA_PREDICTION_TYPE ON TBL_PREDICTIVE_ANALYSIS(PREDICTION_TYPE);
CREATE INDEX IDX_PA_ANALYSIS_STATUS ON TBL_PREDICTIVE_ANALYSIS(ANALYSIS_STATUS);
CREATE INDEX IDX_PA_MODEL_ID ON TBL_PREDICTIVE_ANALYSIS(MODEL_ID);
CREATE INDEX IDX_PA_ORG_ID ON TBL_PREDICTIVE_ANALYSIS(ORG_ID);

-- 表5: 决策建议表
CREATE TABLE TBL_DECISION_RECOMMENDATION (
    RECOMMENDATION_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    RECOMMENDATION_NO VARCHAR(50) NOT NULL,
    RECOMMENDATION_NAME VARCHAR(200) NOT NULL,
    RECOMMENDATION_TYPE VARCHAR(50) NOT NULL,
    MODEL_ID BIGINT,
    ANALYSIS_ID BIGINT,
    RECOMMENDATION_CONTENT CLOB NOT NULL,
    EXPECTED_BENEFIT CLOB,
    RISK_ASSESSMENT CLOB,
    IMPLEMENTATION_PLAN CLOB,
    PRIORITY VARCHAR(20) NOT NULL,
    CONFIDENCE_LEVEL DECIMAL(5,2) NOT NULL,
    RECOMMENDATION_STATUS VARCHAR(20) NOT NULL,
    REVIEW_USER BIGINT,
    REVIEW_DATE TIMESTAMP,
    REVIEW_OPINION CLOB,
    APPROVAL_USER BIGINT,
    APPROVAL_DATE TIMESTAMP,
    APPROVAL_OPINION CLOB,
    IMPLEMENTATION_USER BIGINT,
    IMPLEMENTATION_DATE TIMESTAMP,
    IMPLEMENTATION_RESULT CLOB,
    REMARK VARCHAR(500),
    ORG_ID BIGINT NOT NULL,
    CREATE_BY BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY BIGINT,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG CHAR(1) DEFAULT '0'
);

COMMENT ON TABLE TBL_DECISION_RECOMMENDATION IS '决策建议表';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.RECOMMENDATION_ID IS '建议ID';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.RECOMMENDATION_NO IS '建议编号';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.RECOMMENDATION_NAME IS '建议名称';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.RECOMMENDATION_TYPE IS '建议类型(INVESTMENT/FINANCING/RISK_CONTROL/CASH_MANAGEMENT/OPTIMIZATION)';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.MODEL_ID IS '关联模型ID';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.ANALYSIS_ID IS '关联分析ID';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.RECOMMENDATION_CONTENT IS '建议内容';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.EXPECTED_BENEFIT IS '预期收益';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.RISK_ASSESSMENT IS '风险评估';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.IMPLEMENTATION_PLAN IS '实施计划';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.PRIORITY IS '优先级(HIGH/MEDIUM/LOW)';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.CONFIDENCE_LEVEL IS '置信水平(0-100)';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.RECOMMENDATION_STATUS IS '建议状态(PENDING/REVIEWED/APPROVED/REJECTED/IMPLEMENTED)';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.REVIEW_USER IS '审核人ID';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.REVIEW_DATE IS '审核时间';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.APPROVAL_USER IS '批准人ID';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.APPROVAL_DATE IS '批准时间';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.IMPLEMENTATION_USER IS '实施人ID';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.IMPLEMENTATION_DATE IS '实施时间';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.ORG_ID IS '组织ID';
COMMENT ON COLUMN TBL_DECISION_RECOMMENDATION.DEL_FLAG IS '删除标志(0正常1删除)';

CREATE UNIQUE INDEX IDX_DR_RECOMMENDATION_NO ON TBL_DECISION_RECOMMENDATION(RECOMMENDATION_NO);
CREATE INDEX IDX_DR_RECOMMENDATION_TYPE ON TBL_DECISION_RECOMMENDATION(RECOMMENDATION_TYPE);
CREATE INDEX IDX_DR_RECOMMENDATION_STATUS ON TBL_DECISION_RECOMMENDATION(RECOMMENDATION_STATUS);
CREATE INDEX IDX_DR_PRIORITY ON TBL_DECISION_RECOMMENDATION(PRIORITY);
CREATE INDEX IDX_DR_MODEL_ID ON TBL_DECISION_RECOMMENDATION(MODEL_ID);
CREATE INDEX IDX_DR_ANALYSIS_ID ON TBL_DECISION_RECOMMENDATION(ANALYSIS_ID);
CREATE INDEX IDX_DR_ORG_ID ON TBL_DECISION_RECOMMENDATION(ORG_ID);

-- ===================================================================
-- 测试数据插入(仅用于开发测试)
-- ===================================================================

-- 决策模型测试数据
INSERT INTO TBL_DECISION_MODEL (MODEL_CODE, MODEL_NAME, MODEL_TYPE, ALGORITHM_TYPE, MODEL_STATUS, ACCURACY, ORG_ID, CREATE_BY)
VALUES ('MODEL001', '风险评估模型V1.0', 'RISK_ASSESSMENT', 'RANDOM_FOREST', 'ACTIVE', 0.8560, 1, 1);

INSERT INTO TBL_DECISION_MODEL (MODEL_CODE, MODEL_NAME, MODEL_TYPE, ALGORITHM_TYPE, MODEL_STATUS, ORG_ID, CREATE_BY)
VALUES ('MODEL002', '投资决策模型V1.0', 'INVESTMENT_DECISION', 'NEURAL_NETWORK', 'TESTING', 1, 1);

-- KPI指标测试数据
INSERT INTO TBL_KPI_INDICATOR (KPI_CODE, KPI_NAME, KPI_CATEGORY, KPI_TYPE, CALCULATION_FORMULA, DATA_SOURCE, UNIT, TARGET_VALUE, WARNING_THRESHOLD, CRITICAL_THRESHOLD, CALCULATION_FREQUENCY, KPI_STATUS, ORG_ID, CREATE_BY)
VALUES ('KPI001', '流动比率', 'FINANCIAL', 'FINANCIAL', '流动资产 / 流动负债', '财务系统', '%', 200.00, 150.00, 100.00, 'MONTHLY', 'NORMAL', 1, 1);

INSERT INTO TBL_KPI_INDICATOR (KPI_CODE, KPI_NAME, KPI_CATEGORY, KPI_TYPE, CALCULATION_FORMULA, DATA_SOURCE, UNIT, TARGET_VALUE, CALCULATION_FREQUENCY, KPI_STATUS, ORG_ID, CREATE_BY)
VALUES ('KPI002', '资产负债率', 'FINANCIAL', 'FINANCIAL', '总负债 / 总资产 * 100', '财务系统', '%', 60.00, 'QUARTERLY', 'NORMAL', 1, 1);

-- ===================================================================
-- 脚本结束
-- ===================================================================
