-- ============================================================
-- 衍生品管理模块 - 达梦数据库建表脚本
-- 兼容版本：DM8
-- 创建日期：2026-01-21
-- 说明：包含掉期、远期、期货、期权交易表及监控相关表
-- ============================================================

-- ============================================================
-- 1. 掉期交易表（已存在，仅供参考）
-- ============================================================
-- 表名：TBL_SWAP_TRANSACTION
-- 说明：存储掉期交易合约信息，包括利率掉期、货币掉期、商品掉期、信用违约掉期
-- ============================================================

-- ============================================================
-- 2. 远期交易表
-- ============================================================
-- 表名：TBL_FORWARD_TRANSACTION
-- 说明：存储远期交易合约信息，包括远期外汇、远期利率、远期商品
CREATE TABLE TBL_FORWARD_TRANSACTION (
    TRANSACTION_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CONTRACT_CODE VARCHAR(50) NOT NULL,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    UNDERLYING_ASSET VARCHAR(100),
    NOTIONAL_AMOUNT DECIMAL(20,4),
    CURRENCY VARCHAR(10),
    FORWARD_PRICE DECIMAL(20,6),
    TRADE_DATE DATE,
    MATURITY_DATE DATE,
    CURRENT_VALUE DECIMAL(20,4),
    PNL DECIMAL(20,4),
    COUNTERPARTY VARCHAR(100),
    COUNTERPARTY_RATING VARCHAR(10),
    TRADER VARCHAR(50),
    SALESPERSON VARCHAR(50),
    RISK_LIMIT DECIMAL(20,4),
    MARGIN_REQUIREMENT DECIMAL(20,4),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY BIGINT,
    UPDATE_TIME TIMESTAMP,
    UPDATE_BY BIGINT,
    DEL_FLAG INTEGER DEFAULT 0,
    ORG_ID BIGINT
);

COMMENT ON TABLE TBL_FORWARD_TRANSACTION IS '远期交易表';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.TRANSACTION_ID IS '主键ID';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.CONTRACT_CODE IS '合约编号';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.TRANSACTION_TYPE IS '交易类型(FX_FORWARD-远期外汇, RATE_FORWARD-远期利率, COMMODITY_FORWARD-远期商品)';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.UNDERLYING_ASSET IS '标的资产';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.NOTIONAL_AMOUNT IS '名义本金';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.CURRENCY IS '币种';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.FORWARD_PRICE IS '远期价格';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.TRADE_DATE IS '交易日期';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.MATURITY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.CURRENT_VALUE IS '当前估值';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.PNL IS '损益';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.COUNTERPARTY IS '交易对手';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.COUNTERPARTY_RATING IS '对手评级';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.TRADER IS '交易员';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.SALESPERSON IS '销售员';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.RISK_LIMIT IS '风险限额';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.MARGIN_REQUIREMENT IS '保证金要求';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.STATUS IS '状态(PENDING-待生效, ACTIVE-生效中, EXECUTED-已执行, SETTLED-已交割, CANCELLED-已取消)';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.REMARK IS '备注';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.DEL_FLAG IS '删除标志(0-正常, 1-删除)';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.ORG_ID IS '机构ID';

-- 创建索引
CREATE INDEX IDX_FWD_CONTRACT_CODE ON TBL_FORWARD_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_FWD_TRANSACTION_TYPE ON TBL_FORWARD_TRANSACTION(TRANSACTION_TYPE);
CREATE INDEX IDX_FWD_STATUS ON TBL_FORWARD_TRANSACTION(STATUS);
CREATE INDEX IDX_FWD_CURRENCY ON TBL_FORWARD_TRANSACTION(CURRENCY);
CREATE INDEX IDX_FWD_MATURITY_DATE ON TBL_FORWARD_TRANSACTION(MATURITY_DATE);
CREATE INDEX IDX_FWD_ORG_ID ON TBL_FORWARD_TRANSACTION(ORG_ID);

-- ============================================================
-- 3. 期货交易表
-- ============================================================
-- 表名：TBL_FUTURES_TRANSACTION
-- 说明：存储期货交易合约信息，包括商品期货、金融期货、股指期货、外汇期货
CREATE TABLE TBL_FUTURES_TRANSACTION (
    TRANSACTION_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CONTRACT_CODE VARCHAR(50) NOT NULL,
    FUTURES_TYPE VARCHAR(20) NOT NULL,
    UNDERLYING_ASSET VARCHAR(100),
    DIRECTION VARCHAR(10),
    CONTRACT_SIZE DECIMAL(20,4),
    OPEN_PRICE DECIMAL(20,6),
    CURRENT_PRICE DECIMAL(20,6),
    CURRENCY VARCHAR(10),
    TRADE_DATE DATE,
    EXPIRY_DATE DATE,
    INITIAL_MARGIN DECIMAL(20,4),
    MAINTENANCE_MARGIN DECIMAL(20,4),
    MARGIN_RATIO DECIMAL(10,4),
    MARGIN DECIMAL(20,4),
    UNREALIZED_PNL DECIMAL(20,4),
    REALIZED_PNL DECIMAL(20,4),
    EXCHANGE VARCHAR(50),
    BROKER VARCHAR(100),
    TRADER VARCHAR(50),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY BIGINT,
    UPDATE_TIME TIMESTAMP,
    UPDATE_BY BIGINT,
    DEL_FLAG INTEGER DEFAULT 0,
    ORG_ID BIGINT
);

COMMENT ON TABLE TBL_FUTURES_TRANSACTION IS '期货交易表';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.TRANSACTION_ID IS '主键ID';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CONTRACT_CODE IS '合约编号';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.FUTURES_TYPE IS '期货类型(COMMODITY-商品期货, FINANCIAL-金融期货, INDEX-股指期货, FX-外汇期货)';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.UNDERLYING_ASSET IS '标的资产';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.DIRECTION IS '交易方向(LONG-多头, SHORT-空头)';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CONTRACT_SIZE IS '合约数量';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.OPEN_PRICE IS '开仓价格';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CURRENT_PRICE IS '当前价格';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CURRENCY IS '币种';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.TRADE_DATE IS '交易日期';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.EXPIRY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.INITIAL_MARGIN IS '初始保证金';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.MAINTENANCE_MARGIN IS '维持保证金';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.MARGIN_RATIO IS '保证金比例(%)';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.MARGIN IS '保证金余额';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.UNREALIZED_PNL IS '浮动盈亏';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.REALIZED_PNL IS '已实现盈亏';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.EXCHANGE IS '交易所(SHFE-上期所, DCE-大商所, CZCE-郑商所, CFFEX-中金所, INE-能源中心)';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.BROKER IS '期货公司';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.TRADER IS '交易员';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.STATUS IS '状态(PENDING-待生效, OPEN-持仓中, CLOSED-已平仓, SETTLED-已交割, CANCELLED-已取消)';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.REMARK IS '备注';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.DEL_FLAG IS '删除标志(0-正常, 1-删除)';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.ORG_ID IS '机构ID';

-- 创建索引
CREATE INDEX IDX_FUT_CONTRACT_CODE ON TBL_FUTURES_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_FUT_FUTURES_TYPE ON TBL_FUTURES_TRANSACTION(FUTURES_TYPE);
CREATE INDEX IDX_FUT_DIRECTION ON TBL_FUTURES_TRANSACTION(DIRECTION);
CREATE INDEX IDX_FUT_STATUS ON TBL_FUTURES_TRANSACTION(STATUS);
CREATE INDEX IDX_FUT_CURRENCY ON TBL_FUTURES_TRANSACTION(CURRENCY);
CREATE INDEX IDX_FUT_EXPIRY_DATE ON TBL_FUTURES_TRANSACTION(EXPIRY_DATE);
CREATE INDEX IDX_FUT_ORG_ID ON TBL_FUTURES_TRANSACTION(ORG_ID);

-- ============================================================
-- 4. 期货保证金变动记录表
-- ============================================================
-- 表名：TBL_FUTURES_MARGIN_RECORD
-- 说明：记录期货保证金变动历史
CREATE TABLE TBL_FUTURES_MARGIN_RECORD (
    RECORD_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    TRANSACTION_ID BIGINT NOT NULL,
    OPERATION_TYPE VARCHAR(20) NOT NULL,
    AMOUNT DECIMAL(20,4) NOT NULL,
    BEFORE_BALANCE DECIMAL(20,4),
    AFTER_BALANCE DECIMAL(20,4),
    REASON VARCHAR(200),
    OPERATOR VARCHAR(50),
    OPERATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    ORG_ID BIGINT
);

COMMENT ON TABLE TBL_FUTURES_MARGIN_RECORD IS '期货保证金变动记录表';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.RECORD_ID IS '记录ID';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.TRANSACTION_ID IS '交易ID';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.OPERATION_TYPE IS '操作类型(ADD-追加, WITHDRAW-提取, CALL-追加通知, RETURN-返还)';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.AMOUNT IS '变动金额';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.BEFORE_BALANCE IS '变动前余额';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.AFTER_BALANCE IS '变动后余额';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.REASON IS '变动原因';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.OPERATOR IS '操作人';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.OPERATE_TIME IS '操作时间';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.REMARK IS '备注';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.ORG_ID IS '机构ID';

-- 创建索引
CREATE INDEX IDX_FMR_TRANSACTION_ID ON TBL_FUTURES_MARGIN_RECORD(TRANSACTION_ID);
CREATE INDEX IDX_FMR_OPERATION_TYPE ON TBL_FUTURES_MARGIN_RECORD(OPERATION_TYPE);
CREATE INDEX IDX_FMR_OPERATE_TIME ON TBL_FUTURES_MARGIN_RECORD(OPERATE_TIME);
CREATE INDEX IDX_FMR_ORG_ID ON TBL_FUTURES_MARGIN_RECORD(ORG_ID);

-- ============================================================
-- 5. 期权交易表
-- ============================================================
-- 表名：TBL_OPTION_TRANSACTION
-- 说明：存储期权交易合约信息，包括看涨/看跌期权、欧式/美式期权
CREATE TABLE TBL_OPTION_TRANSACTION (
    TRANSACTION_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CONTRACT_CODE VARCHAR(50) NOT NULL,
    OPTION_TYPE VARCHAR(10) NOT NULL,
    OPTION_STYLE VARCHAR(20) NOT NULL,
    UNDERLYING_ASSET VARCHAR(100) NOT NULL,
    CONTRACT_SIZE DECIMAL(20,4),
    STRIKE_PRICE DECIMAL(20,6) NOT NULL,
    PREMIUM DECIMAL(20,4),
    THEORETICAL_VALUE DECIMAL(20,4),
    CURRENCY VARCHAR(10),
    TRADE_DATE DATE,
    EXPIRY_DATE DATE,
    UNDERLYING_PRICE DECIMAL(20,6),
    RISK_FREE_RATE DECIMAL(10,6),
    VOLATILITY DECIMAL(10,6),
    DIVIDEND_YIELD DECIMAL(10,6),
    PRICING_MODEL VARCHAR(50),
    EXERCISE_TYPE VARCHAR(50),
    DELTA DECIMAL(10,6),
    GAMMA DECIMAL(10,6),
    THETA DECIMAL(10,6),
    VEGA DECIMAL(10,6),
    RHO DECIMAL(10,6),
    COUNTERPARTY VARCHAR(100),
    COUNTERPARTY_RATING VARCHAR(10),
    TRADER VARCHAR(50),
    SALESPERSON VARCHAR(50),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY BIGINT,
    UPDATE_TIME TIMESTAMP,
    UPDATE_BY BIGINT,
    DEL_FLAG INTEGER DEFAULT 0,
    ORG_ID BIGINT
);

COMMENT ON TABLE TBL_OPTION_TRANSACTION IS '期权交易表';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.TRANSACTION_ID IS '主键ID';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.CONTRACT_CODE IS '合约编号';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.OPTION_TYPE IS '期权类型(CALL-看涨期权, PUT-看跌期权)';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.OPTION_STYLE IS '期权风格(EUROPEAN-欧式, AMERICAN-美式, ASIAN-亚式)';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.UNDERLYING_ASSET IS '标的资产';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.CONTRACT_SIZE IS '合约数量';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.STRIKE_PRICE IS '行权价格';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.PREMIUM IS '期权费';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.THEORETICAL_VALUE IS '理论价值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.CURRENCY IS '币种';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.TRADE_DATE IS '交易日期';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.EXPIRY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.UNDERLYING_PRICE IS '标的价格';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.RISK_FREE_RATE IS '无风险利率(%)';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.VOLATILITY IS '波动率(%)';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.DIVIDEND_YIELD IS '股息率(%)';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.PRICING_MODEL IS '定价模型(BLACK_SCHOLES, BINOMIAL_TREE, MONTE_CARLO)';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.EXERCISE_TYPE IS '行权方式(CASH_SETTLEMENT-现金交割, PHYSICAL_SETTLEMENT-实物交割)';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.DELTA IS 'Delta值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.GAMMA IS 'Gamma值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.THETA IS 'Theta值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.VEGA IS 'Vega值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.RHO IS 'Rho值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.COUNTERPARTY IS '交易对手';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.COUNTERPARTY_RATING IS '对手评级';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.TRADER IS '交易员';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.SALESPERSON IS '销售员';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.STATUS IS '状态(PENDING-待生效, ACTIVE-生效中, EXERCISED-已行权, EXPIRED-已到期, CANCELLED-已取消)';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.REMARK IS '备注';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.DEL_FLAG IS '删除标志(0-正常, 1-删除)';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.ORG_ID IS '机构ID';

-- 创建索引
CREATE INDEX IDX_OPT_CONTRACT_CODE ON TBL_OPTION_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_OPT_OPTION_TYPE ON TBL_OPTION_TRANSACTION(OPTION_TYPE);
CREATE INDEX IDX_OPT_OPTION_STYLE ON TBL_OPTION_TRANSACTION(OPTION_STYLE);
CREATE INDEX IDX_OPT_STATUS ON TBL_OPTION_TRANSACTION(STATUS);
CREATE INDEX IDX_OPT_CURRENCY ON TBL_OPTION_TRANSACTION(CURRENCY);
CREATE INDEX IDX_OPT_EXPIRY_DATE ON TBL_OPTION_TRANSACTION(EXPIRY_DATE);
CREATE INDEX IDX_OPT_ORG_ID ON TBL_OPTION_TRANSACTION(ORG_ID);

-- ============================================================
-- 6. 衍生品监控预警表
-- ============================================================
-- 表名：TBL_DERIVATIVES_ALERT
-- 说明：存储衍生品监控预警规则和预警记录
CREATE TABLE TBL_DERIVATIVES_ALERT (
    ALERT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ALERT_NAME VARCHAR(100) NOT NULL,
    ALERT_TYPE VARCHAR(50) NOT NULL,
    MONITORING_METRIC VARCHAR(100) NOT NULL,
    THRESHOLD DECIMAL(20,6) NOT NULL,
    CURRENT_VALUE DECIMAL(20,6),
    ALERT_LEVEL VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    NOTIFICATION_METHOD VARCHAR(200),
    TRIGGER_TIME TIMESTAMP,
    DESCRIPTION VARCHAR(500),
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY BIGINT,
    UPDATE_TIME TIMESTAMP,
    UPDATE_BY BIGINT,
    DEL_FLAG INTEGER DEFAULT 0,
    ORG_ID BIGINT
);

COMMENT ON TABLE TBL_DERIVATIVES_ALERT IS '衍生品监控预警表';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_ID IS '预警ID';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_NAME IS '预警名称';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_TYPE IS '预警类型(PRICE_ALERT-价格预警, RISK_ALERT-风险预警, POSITION_ALERT-持仓预警, EXPIRY_ALERT-到期预警)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.MONITORING_METRIC IS '监控指标';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.THRESHOLD IS '阈值';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.CURRENT_VALUE IS '当前值';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_LEVEL IS '预警级别(LOW-低, MEDIUM-中, HIGH-高, CRITICAL-紧急)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.STATUS IS '状态(ACTIVE-活跃, TRIGGERED-已触发, PROCESSED-已处理, IGNORED-已忽略)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.NOTIFICATION_METHOD IS '通知方式(EMAIL-邮件, SMS-短信, SYSTEM-系统通知)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.TRIGGER_TIME IS '触发时间';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.DESCRIPTION IS '描述';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.REMARK IS '备注';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.DEL_FLAG IS '删除标志(0-正常, 1-删除)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ORG_ID IS '机构ID';

-- 创建索引
CREATE INDEX IDX_DA_ALERT_TYPE ON TBL_DERIVATIVES_ALERT(ALERT_TYPE);
CREATE INDEX IDX_DA_ALERT_LEVEL ON TBL_DERIVATIVES_ALERT(ALERT_LEVEL);
CREATE INDEX IDX_DA_STATUS ON TBL_DERIVATIVES_ALERT(STATUS);
CREATE INDEX IDX_DA_TRIGGER_TIME ON TBL_DERIVATIVES_ALERT(TRIGGER_TIME);
CREATE INDEX IDX_DA_ORG_ID ON TBL_DERIVATIVES_ALERT(ORG_ID);

-- ============================================================
-- 7. 衍生品市场数据表
-- ============================================================
-- 表名：TBL_DERIVATIVES_MARKET_DATA
-- 说明：存储衍生品相关市场数据
CREATE TABLE TBL_DERIVATIVES_MARKET_DATA (
    MARKET_DATA_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ASSET_TYPE VARCHAR(50) NOT NULL,
    ASSET_CODE VARCHAR(50) NOT NULL,
    ASSET_NAME VARCHAR(100),
    CURRENT_PRICE DECIMAL(20,6),
    PRICE_CHANGE DECIMAL(10,6),
    VOLATILITY DECIMAL(10,6),
    VOLUME DECIMAL(20,4),
    OPEN_INTEREST DECIMAL(20,4),
    DATA_SOURCE VARCHAR(50),
    DATA_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ORG_ID BIGINT
);

COMMENT ON TABLE TBL_DERIVATIVES_MARKET_DATA IS '衍生品市场数据表';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.MARKET_DATA_ID IS '市场数据ID';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.ASSET_TYPE IS '资产类型(FORWARD-远期, FUTURES-期货, OPTION-期权, SPOT-现货)';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.ASSET_CODE IS '资产代码';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.ASSET_NAME IS '资产名称';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.CURRENT_PRICE IS '当前价格';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.PRICE_CHANGE IS '价格变化(%)';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.VOLATILITY IS '波动率(%)';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.VOLUME IS '成交量';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.OPEN_INTEREST IS '持仓量';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.DATA_SOURCE IS '数据源';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.DATA_TIME IS '数据时间';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.ORG_ID IS '机构ID';

-- 创建索引
CREATE INDEX IDX_DMD_ASSET_CODE ON TBL_DERIVATIVES_MARKET_DATA(ASSET_CODE);
CREATE INDEX IDX_DMD_ASSET_TYPE ON TBL_DERIVATIVES_MARKET_DATA(ASSET_TYPE);
CREATE INDEX IDX_DMD_DATA_TIME ON TBL_DERIVATIVES_MARKET_DATA(DATA_TIME);
CREATE INDEX IDX_DMD_ORG_ID ON TBL_DERIVATIVES_MARKET_DATA(ORG_ID);

-- ============================================================
-- 测试数据
-- ============================================================

-- 插入远期交易测试数据
INSERT INTO TBL_FORWARD_TRANSACTION (CONTRACT_CODE, TRANSACTION_TYPE, UNDERLYING_ASSET, NOTIONAL_AMOUNT, CURRENCY, FORWARD_PRICE, TRADE_DATE, MATURITY_DATE, STATUS, ORG_ID)
VALUES ('FX2026001', 'FX_FORWARD', 'USD/CNY', 1000000, 'USD', 7.2500, '2026-01-15', '2026-04-15', 'ACTIVE', 1);

INSERT INTO TBL_FORWARD_TRANSACTION (CONTRACT_CODE, TRANSACTION_TYPE, UNDERLYING_ASSET, NOTIONAL_AMOUNT, CURRENCY, FORWARD_PRICE, TRADE_DATE, MATURITY_DATE, STATUS, ORG_ID)
VALUES ('FX2026002', 'FX_FORWARD', 'EUR/CNY', 500000, 'EUR', 7.8500, '2026-01-16', '2026-07-16', 'ACTIVE', 1);

-- 插入期货交易测试数据
INSERT INTO TBL_FUTURES_TRANSACTION (CONTRACT_CODE, FUTURES_TYPE, UNDERLYING_ASSET, DIRECTION, CONTRACT_SIZE, OPEN_PRICE, CURRENT_PRICE, CURRENCY, TRADE_DATE, EXPIRY_DATE, INITIAL_MARGIN, MAINTENANCE_MARGIN, MARGIN, STATUS, ORG_ID)
VALUES ('CU2606', 'COMMODITY', '铜', 'LONG', 10, 68500, 69000, 'CNY', '2026-01-15', '2026-06-15', 50000, 40000, 45000, 'OPEN', 1);

INSERT INTO TBL_FUTURES_TRANSACTION (CONTRACT_CODE, FUTURES_TYPE, UNDERLYING_ASSET, DIRECTION, CONTRACT_SIZE, OPEN_PRICE, CURRENT_PRICE, CURRENCY, TRADE_DATE, EXPIRY_DATE, INITIAL_MARGIN, MAINTENANCE_MARGIN, MARGIN, STATUS, ORG_ID)
VALUES ('IF2606', 'INDEX', '沪深300', 'LONG', 1, 3500, 3550, 'CNY', '2026-01-16', '2026-06-16', 100000, 80000, 90000, 'OPEN', 1);

-- 插入期权交易测试数据
INSERT INTO TBL_OPTION_TRANSACTION (CONTRACT_CODE, OPTION_TYPE, OPTION_STYLE, UNDERLYING_ASSET, CONTRACT_SIZE, STRIKE_PRICE, PREMIUM, THEORETICAL_VALUE, CURRENCY, TRADE_DATE, EXPIRY_DATE, UNDERLYING_PRICE, RISK_FREE_RATE, VOLATILITY, PRICING_MODEL, DELTA, GAMMA, THETA, VEGA, STATUS, ORG_ID)
VALUES ('OPT-USD-2406-P', 'PUT', 'AMERICAN', 'USD/CNY', 100000, 7.25, 0.05, 0.052, 'USD', '2026-01-15', '2026-06-15', 7.20, 3.5, 15.0, 'BLACK_SCHOLES', -0.45, 0.08, -0.03, 0.25, 'ACTIVE', 1);

INSERT INTO TBL_OPTION_TRANSACTION (CONTRACT_CODE, OPTION_TYPE, OPTION_STYLE, UNDERLYING_ASSET, CONTRACT_SIZE, STRIKE_PRICE, PREMIUM, THEORETICAL_VALUE, CURRENCY, TRADE_DATE, EXPIRY_DATE, UNDERLYING_PRICE, RISK_FREE_RATE, VOLATILITY, PRICING_MODEL, DELTA, GAMMA, THETA, VEGA, STATUS, ORG_ID)
VALUES ('OPT-EUR-2406-C', 'CALL', 'EUROPEAN', 'EUR/CNY', 100000, 7.80, 0.08, 0.078, 'EUR', '2026-01-16', '2026-06-16', 7.85, 3.5, 12.0, 'BLACK_SCHOLES', 0.55, 0.06, -0.02, 0.22, 'ACTIVE', 1);

-- 插入预警规则测试数据
INSERT INTO TBL_DERIVATIVES_ALERT (ALERT_NAME, ALERT_TYPE, MONITORING_METRIC, THRESHOLD, ALERT_LEVEL, STATUS, NOTIFICATION_METHOD, DESCRIPTION, ORG_ID)
VALUES ('汇率预警', 'PRICE_ALERT', 'USD/CNY', 7.5, 'MEDIUM', 'ACTIVE', 'EMAIL,SYSTEM', '当美元兑人民币汇率超过7.5时触发预警', 1);

INSERT INTO TBL_DERIVATIVES_ALERT (ALERT_NAME, ALERT_TYPE, MONITORING_METRIC, THRESHOLD, ALERT_LEVEL, STATUS, NOTIFICATION_METHOD, DESCRIPTION, ORG_ID)
VALUES ('持仓限额预警', 'POSITION_ALERT', 'TOTAL_POSITION', 10000000, 'HIGH', 'ACTIVE', 'EMAIL,SMS,SYSTEM', '当总持仓超过1000万时触发预警', 1);

-- 插入市场数据测试数据
INSERT INTO TBL_DERIVATIVES_MARKET_DATA (ASSET_TYPE, ASSET_CODE, ASSET_NAME, CURRENT_PRICE, PRICE_CHANGE, VOLATILITY, VOLUME, DATA_SOURCE, DATA_TIME, ORG_ID)
VALUES ('SPOT', 'USD/CNY', '美元兑人民币', 7.2456, 0.0025, 8.5, 1000000, 'Bloomberg', CURRENT_TIMESTAMP, 1);

INSERT INTO TBL_DERIVATIVES_MARKET_DATA (ASSET_TYPE, ASSET_CODE, ASSET_NAME, CURRENT_PRICE, PRICE_CHANGE, VOLATILITY, VOLUME, DATA_SOURCE, DATA_TIME, ORG_ID)
VALUES ('FUTURES', 'CU2606', '铜期货2606', 69000, 0.0073, 18.5, 50000, 'SHFE', CURRENT_TIMESTAMP, 1);

-- ============================================================
-- 提交事务
-- ============================================================
COMMIT;

-- ============================================================
-- 脚本执行完成
-- ============================================================
