-- ================================================================
-- 华博云衍生品交易管理 - 数据库建表脚本
-- 数据库类型: 达梦数据库 (DM8)
-- 字符集: UTF-8
-- 创建时间: 2026-01-21
-- ================================================================

-- ================================================================
-- 1. 期货交易表 (TBL_FUTURES_TRANSACTION)
-- ================================================================
CREATE TABLE TBL_FUTURES_TRANSACTION (
    TRANSACTION_ID BIGINT NOT NULL,  -- 交易ID (主键)
    CONTRACT_CODE VARCHAR(100) NOT NULL,  -- 合约编号
    FUTURES_TYPE VARCHAR(50) NOT NULL,  -- 期货类型 (COMMODITY-商品期货, FINANCIAL-金融期货, INDEX-股指期货, FX-外汇期货)
    UNDERLYING_ASSET VARCHAR(200) NOT NULL,  -- 标的资产
    DIRECTION VARCHAR(20) NOT NULL,  -- 交易方向 (LONG-多头, SHORT-空头)
    CONTRACT_SIZE DECIMAL(20,4) NOT NULL,  -- 合约数量
    OPEN_PRICE DECIMAL(20,4) NOT NULL,  -- 开仓价格
    CURRENT_PRICE DECIMAL(20,4),  -- 当前价格
    CURRENCY VARCHAR(10) NOT NULL,  -- 币种 (CNY, USD, EUR, JPY)
    EXPIRY_DATE DATE,  -- 到期日期
    TRADE_DATE DATE NOT NULL,  -- 交易日期
    INITIAL_MARGIN DECIMAL(20,4),  -- 初始保证金
    MAINTENANCE_MARGIN DECIMAL(20,4),  -- 维持保证金
    MARGIN_RATIO DECIMAL(10,4),  -- 保证金比例
    MARGIN DECIMAL(20,4),  -- 当前保证金
    UNREALIZED_PNL DECIMAL(20,4),  -- 浮动盈亏
    REALIZED_PNL DECIMAL(20,4),  -- 已实现盈亏
    STATUS VARCHAR(20) NOT NULL,  -- 状态 (PENDING-待生效, OPEN-持仓中, CLOSED-已平仓, SETTLED-已交割, CANCELLED-已取消)
    EXCHANGE VARCHAR(100),  -- 交易所 (SHFE-上期所, DCE-大商所, CZCE-郑商所, CFFEX-中金所, INE-能源中心)
    BROKER VARCHAR(200),  -- 期货公司
    TRADER VARCHAR(100),  -- 交易员
    COUNTERPARTY VARCHAR(200),  -- 交易对手
    COUNTERPARTY_RATING VARCHAR(20),  -- 对手评级 (AAA, AA, A, BBB, BB)
    RISK_LIMIT DECIMAL(20,4),  -- 风险限额
    REMARK VARCHAR(1000),  -- 备注
    ORG_ID BIGINT NOT NULL,  -- 机构ID
    CREATE_TIME DATETIME NOT NULL,  -- 创建时间
    UPDATE_TIME DATETIME NOT NULL,  -- 更新时间
    CREATE_BY VARCHAR(100),  -- 创建人
    UPDATE_BY VARCHAR(100),  -- 更新人
    DEL_FLAG VARCHAR(1) DEFAULT '0' NOT NULL,  -- 删除标志 (0-正常, 1-删除)
    CONSTRAINT PK_FUTURES_TRANSACTION PRIMARY KEY (TRANSACTION_ID)
);

-- 表注释
COMMENT ON TABLE TBL_FUTURES_TRANSACTION IS '期货交易表';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.TRANSACTION_ID IS '交易ID';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CONTRACT_CODE IS '合约编号';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.FUTURES_TYPE IS '期货类型';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.UNDERLYING_ASSET IS '标的资产';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.DIRECTION IS '交易方向';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CONTRACT_SIZE IS '合约数量';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.OPEN_PRICE IS '开仓价格';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CURRENT_PRICE IS '当前价格';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CURRENCY IS '币种';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.EXPIRY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.TRADE_DATE IS '交易日期';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.INITIAL_MARGIN IS '初始保证金';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.MAINTENANCE_MARGIN IS '维持保证金';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.MARGIN_RATIO IS '保证金比例';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.MARGIN IS '当前保证金';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.UNREALIZED_PNL IS '浮动盈亏';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.REALIZED_PNL IS '已实现盈亏';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.STATUS IS '状态';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.EXCHANGE IS '交易所';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.BROKER IS '期货公司';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.TRADER IS '交易员';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.COUNTERPARTY IS '交易对手';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.COUNTERPARTY_RATING IS '对手评级';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.RISK_LIMIT IS '风险限额';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.REMARK IS '备注';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.ORG_ID IS '机构ID';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_FUTURES_TRANSACTION.DEL_FLAG IS '删除标志';

-- 创建索引
CREATE INDEX IDX_FT_CONTRACT_CODE ON TBL_FUTURES_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_FT_ORG_ID ON TBL_FUTURES_TRANSACTION(ORG_ID);
CREATE INDEX IDX_FT_STATUS ON TBL_FUTURES_TRANSACTION(STATUS);
CREATE INDEX IDX_FT_TRADE_DATE ON TBL_FUTURES_TRANSACTION(TRADE_DATE);
CREATE INDEX IDX_FT_EXPIRY_DATE ON TBL_FUTURES_TRANSACTION(EXPIRY_DATE);
CREATE INDEX IDX_FT_DEL_FLAG ON TBL_FUTURES_TRANSACTION(DEL_FLAG);

-- ================================================================
-- 2. 期货保证金记录表 (TBL_FUTURES_MARGIN_RECORD)
-- ================================================================
CREATE TABLE TBL_FUTURES_MARGIN_RECORD (
    RECORD_ID BIGINT NOT NULL,  -- 记录ID (主键)
    TRANSACTION_ID BIGINT NOT NULL,  -- 交易ID (外键)
    OPERATION_TYPE VARCHAR(20) NOT NULL,  -- 操作类型 (ADD-追加, WITHDRAW-提取, ADJUST-调整)
    AMOUNT DECIMAL(20,4) NOT NULL,  -- 操作金额
    BEFORE_BALANCE DECIMAL(20,4) NOT NULL,  -- 操作前余额
    AFTER_BALANCE DECIMAL(20,4) NOT NULL,  -- 操作后余额
    REASON VARCHAR(500),  -- 原因
    OPERATOR VARCHAR(100),  -- 操作人
    OPERATION_TIME DATETIME NOT NULL,  -- 操作时间
    REMARK VARCHAR(1000),  -- 备注
    ORG_ID BIGINT NOT NULL,  -- 机构ID
    CONSTRAINT PK_FUTURES_MARGIN_RECORD PRIMARY KEY (RECORD_ID)
);

-- 表注释
COMMENT ON TABLE TBL_FUTURES_MARGIN_RECORD IS '期货保证金记录表';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.RECORD_ID IS '记录ID';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.TRANSACTION_ID IS '交易ID';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.OPERATION_TYPE IS '操作类型';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.AMOUNT IS '操作金额';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.BEFORE_BALANCE IS '操作前余额';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.AFTER_BALANCE IS '操作后余额';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.REASON IS '原因';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.OPERATOR IS '操作人';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.OPERATION_TIME IS '操作时间';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.REMARK IS '备注';
COMMENT ON COLUMN TBL_FUTURES_MARGIN_RECORD.ORG_ID IS '机构ID';

-- 创建索引
CREATE INDEX IDX_FMR_TRANSACTION_ID ON TBL_FUTURES_MARGIN_RECORD(TRANSACTION_ID);
CREATE INDEX IDX_FMR_ORG_ID ON TBL_FUTURES_MARGIN_RECORD(ORG_ID);
CREATE INDEX IDX_FMR_OPERATION_TIME ON TBL_FUTURES_MARGIN_RECORD(OPERATION_TIME);

-- ================================================================
-- 3. 远期交易表 (TBL_FORWARD_TRANSACTION)
-- ================================================================
CREATE TABLE TBL_FORWARD_TRANSACTION (
    TRANSACTION_ID BIGINT NOT NULL,  -- 交易ID (主键)
    CONTRACT_CODE VARCHAR(100) NOT NULL,  -- 合约编号
    TRANSACTION_TYPE VARCHAR(50) NOT NULL,  -- 交易类型 (FX_FORWARD-远期外汇, RATE_FORWARD-远期利率, COMMODITY_FORWARD-远期商品)
    UNDERLYING_ASSET VARCHAR(200) NOT NULL,  -- 标的资产
    NOTIONAL_AMOUNT DECIMAL(20,4) NOT NULL,  -- 名义本金
    FORWARD_PRICE DECIMAL(20,4) NOT NULL,  -- 远期价格
    CURRENT_VALUE DECIMAL(20,4),  -- 当前估值
    PNL DECIMAL(20,4),  -- 损益
    CURRENCY VARCHAR(10) NOT NULL,  -- 币种
    TRADE_DATE DATE NOT NULL,  -- 交易日期
    MATURITY_DATE DATE NOT NULL,  -- 到期日期
    STATUS VARCHAR(20) NOT NULL,  -- 状态 (PENDING-待生效, ACTIVE-生效中, EXECUTED-已执行, SETTLED-已交割, CANCELLED-已取消)
    COUNTERPARTY VARCHAR(200),  -- 交易对手
    COUNTERPARTY_RATING VARCHAR(20),  -- 对手评级
    TRADER VARCHAR(100),  -- 交易员
    SALESPERSON VARCHAR(100),  -- 销售员
    RISK_LIMIT DECIMAL(20,4),  -- 风险限额
    MARGIN_REQUIREMENT DECIMAL(20,4),  -- 保证金要求
    REMARK VARCHAR(1000),  -- 备注
    ORG_ID BIGINT NOT NULL,  -- 机构ID
    CREATE_TIME DATETIME NOT NULL,  -- 创建时间
    UPDATE_TIME DATETIME NOT NULL,  -- 更新时间
    CREATE_BY VARCHAR(100),  -- 创建人
    UPDATE_BY VARCHAR(100),  -- 更新人
    DEL_FLAG VARCHAR(1) DEFAULT '0' NOT NULL,  -- 删除标志
    CONSTRAINT PK_FORWARD_TRANSACTION PRIMARY KEY (TRANSACTION_ID)
);

-- 表注释
COMMENT ON TABLE TBL_FORWARD_TRANSACTION IS '远期交易表';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.TRANSACTION_ID IS '交易ID';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.CONTRACT_CODE IS '合约编号';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.TRANSACTION_TYPE IS '交易类型';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.UNDERLYING_ASSET IS '标的资产';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.NOTIONAL_AMOUNT IS '名义本金';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.FORWARD_PRICE IS '远期价格';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.CURRENT_VALUE IS '当前估值';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.PNL IS '损益';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.CURRENCY IS '币种';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.TRADE_DATE IS '交易日期';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.MATURITY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.STATUS IS '状态';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.COUNTERPARTY IS '交易对手';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.COUNTERPARTY_RATING IS '对手评级';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.TRADER IS '交易员';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.SALESPERSON IS '销售员';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.RISK_LIMIT IS '风险限额';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.MARGIN_REQUIREMENT IS '保证金要求';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.REMARK IS '备注';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.ORG_ID IS '机构ID';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_FORWARD_TRANSACTION.DEL_FLAG IS '删除标志';

-- 创建索引
CREATE INDEX IDX_FWD_CONTRACT_CODE ON TBL_FORWARD_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_FWD_ORG_ID ON TBL_FORWARD_TRANSACTION(ORG_ID);
CREATE INDEX IDX_FWD_STATUS ON TBL_FORWARD_TRANSACTION(STATUS);
CREATE INDEX IDX_FWD_TRADE_DATE ON TBL_FORWARD_TRANSACTION(TRADE_DATE);
CREATE INDEX IDX_FWD_MATURITY_DATE ON TBL_FORWARD_TRANSACTION(MATURITY_DATE);
CREATE INDEX IDX_FWD_DEL_FLAG ON TBL_FORWARD_TRANSACTION(DEL_FLAG);

-- ================================================================
-- 4. 期权交易表 (TBL_OPTION_TRANSACTION)
-- ================================================================
CREATE TABLE TBL_OPTION_TRANSACTION (
    TRANSACTION_ID BIGINT NOT NULL,  -- 交易ID (主键)
    CONTRACT_CODE VARCHAR(100) NOT NULL,  -- 合约编号
    OPTION_TYPE VARCHAR(20) NOT NULL,  -- 期权类型 (CALL-看涨期权, PUT-看跌期权)
    OPTION_STYLE VARCHAR(20) NOT NULL,  -- 期权风格 (EUROPEAN-欧式, AMERICAN-美式, ASIAN-亚式)
    UNDERLYING_ASSET VARCHAR(200) NOT NULL,  -- 标的资产
    CONTRACT_SIZE DECIMAL(20,4) NOT NULL,  -- 合约数量
    STRIKE_PRICE DECIMAL(20,4) NOT NULL,  -- 行权价格
    PREMIUM DECIMAL(20,4) NOT NULL,  -- 期权费
    THEORETICAL_VALUE DECIMAL(20,4),  -- 理论价值
    UNDERLYING_PRICE DECIMAL(20,4),  -- 标的价格
    RISK_FREE_RATE DECIMAL(10,4),  -- 无风险利率
    VOLATILITY DECIMAL(10,4),  -- 波动率
    DIVIDEND_YIELD DECIMAL(10,4),  -- 股息率
    PRICING_MODEL VARCHAR(50),  -- 定价模型 (BLACK_SCHOLES-BS模型, BINOMIAL_TREE-二叉树, MONTE_CARLO-蒙特卡洛)
    CURRENCY VARCHAR(10) NOT NULL,  -- 币种
    TRADE_DATE DATE NOT NULL,  -- 交易日期
    EXPIRY_DATE DATE NOT NULL,  -- 到期日期
    EXERCISE_TYPE VARCHAR(50),  -- 行权方式 (CASH_SETTLEMENT-现金交割, PHYSICAL_SETTLEMENT-实物交割)
    STATUS VARCHAR(20) NOT NULL,  -- 状态 (PENDING-待生效, ACTIVE-生效中, EXERCISED-已行权, EXPIRED-已到期, CANCELLED-已取消)
    DELTA DECIMAL(10,4),  -- Delta值
    GAMMA DECIMAL(10,4),  -- Gamma值
    THETA DECIMAL(10,4),  -- Theta值
    VEGA DECIMAL(10,4),  -- Vega值
    RHO DECIMAL(10,4),  -- Rho值
    COUNTERPARTY VARCHAR(200),  -- 交易对手
    COUNTERPARTY_RATING VARCHAR(20),  -- 对手评级
    TRADER VARCHAR(100),  -- 交易员
    SALESPERSON VARCHAR(100),  -- 销售员
    REMARK VARCHAR(1000),  -- 备注
    ORG_ID BIGINT NOT NULL,  -- 机构ID
    CREATE_TIME DATETIME NOT NULL,  -- 创建时间
    UPDATE_TIME DATETIME NOT NULL,  -- 更新时间
    CREATE_BY VARCHAR(100),  -- 创建人
    UPDATE_BY VARCHAR(100),  -- 更新人
    DEL_FLAG VARCHAR(1) DEFAULT '0' NOT NULL,  -- 删除标志
    CONSTRAINT PK_OPTION_TRANSACTION PRIMARY KEY (TRANSACTION_ID)
);

-- 表注释
COMMENT ON TABLE TBL_OPTION_TRANSACTION IS '期权交易表';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.TRANSACTION_ID IS '交易ID';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.CONTRACT_CODE IS '合约编号';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.OPTION_TYPE IS '期权类型';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.OPTION_STYLE IS '期权风格';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.UNDERLYING_ASSET IS '标的资产';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.CONTRACT_SIZE IS '合约数量';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.STRIKE_PRICE IS '行权价格';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.PREMIUM IS '期权费';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.THEORETICAL_VALUE IS '理论价值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.UNDERLYING_PRICE IS '标的价格';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.RISK_FREE_RATE IS '无风险利率';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.VOLATILITY IS '波动率';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.DIVIDEND_YIELD IS '股息率';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.PRICING_MODEL IS '定价模型';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.CURRENCY IS '币种';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.TRADE_DATE IS '交易日期';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.EXPIRY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.EXERCISE_TYPE IS '行权方式';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.STATUS IS '状态';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.DELTA IS 'Delta值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.GAMMA IS 'Gamma值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.THETA IS 'Theta值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.VEGA IS 'Vega值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.RHO IS 'Rho值';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.COUNTERPARTY IS '交易对手';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.COUNTERPARTY_RATING IS '对手评级';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.TRADER IS '交易员';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.SALESPERSON IS '销售员';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.REMARK IS '备注';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.ORG_ID IS '机构ID';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_OPTION_TRANSACTION.DEL_FLAG IS '删除标志';

-- 创建索引
CREATE INDEX IDX_OPT_CONTRACT_CODE ON TBL_OPTION_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_OPT_ORG_ID ON TBL_OPTION_TRANSACTION(ORG_ID);
CREATE INDEX IDX_OPT_STATUS ON TBL_OPTION_TRANSACTION(STATUS);
CREATE INDEX IDX_OPT_TRADE_DATE ON TBL_OPTION_TRANSACTION(TRADE_DATE);
CREATE INDEX IDX_OPT_EXPIRY_DATE ON TBL_OPTION_TRANSACTION(EXPIRY_DATE);
CREATE INDEX IDX_OPT_DEL_FLAG ON TBL_OPTION_TRANSACTION(DEL_FLAG);

-- ================================================================
-- 5. 期权希腊字母历史表 (TBL_OPTION_GREEKS_HISTORY)
-- ================================================================
CREATE TABLE TBL_OPTION_GREEKS_HISTORY (
    GREEKS_ID BIGINT NOT NULL,  -- 希腊字母ID (主键)
    TRANSACTION_ID BIGINT NOT NULL,  -- 交易ID (外键)
    DELTA DECIMAL(10,4) NOT NULL,  -- Delta值
    GAMMA DECIMAL(10,4) NOT NULL,  -- Gamma值
    THETA DECIMAL(10,4) NOT NULL,  -- Theta值
    VEGA DECIMAL(10,4) NOT NULL,  -- Vega值
    RHO DECIMAL(10,4) NOT NULL,  -- Rho值
    UNDERLYING_PRICE DECIMAL(20,4) NOT NULL,  -- 计算时标的价格
    IMPLIED_VOLATILITY DECIMAL(10,4),  -- 隐含波动率
    TIME_TO_EXPIRY DECIMAL(10,4),  -- 到期时间(年)
    CALCULATION_TIME DATETIME NOT NULL,  -- 计算时间
    ORG_ID BIGINT NOT NULL,  -- 机构ID
    CONSTRAINT PK_OPTION_GREEKS_HISTORY PRIMARY KEY (GREEKS_ID)
);

-- 表注释
COMMENT ON TABLE TBL_OPTION_GREEKS_HISTORY IS '期权希腊字母历史表';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.GREEKS_ID IS '希腊字母ID';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.TRANSACTION_ID IS '交易ID';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.DELTA IS 'Delta值';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.GAMMA IS 'Gamma值';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.THETA IS 'Theta值';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.VEGA IS 'Vega值';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.RHO IS 'Rho值';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.UNDERLYING_PRICE IS '计算时标的价格';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.IMPLIED_VOLATILITY IS '隐含波动率';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.TIME_TO_EXPIRY IS '到期时间(年)';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.CALCULATION_TIME IS '计算时间';
COMMENT ON COLUMN TBL_OPTION_GREEKS_HISTORY.ORG_ID IS '机构ID';

-- 创建索引
CREATE INDEX IDX_OGH_TRANSACTION_ID ON TBL_OPTION_GREEKS_HISTORY(TRANSACTION_ID);
CREATE INDEX IDX_OGH_ORG_ID ON TBL_OPTION_GREEKS_HISTORY(ORG_ID);
CREATE INDEX IDX_OGH_CALCULATION_TIME ON TBL_OPTION_GREEKS_HISTORY(CALCULATION_TIME);

-- ================================================================
-- 6. 掉期交易表 (TBL_SWAP_TRANSACTION)
-- ================================================================
CREATE TABLE TBL_SWAP_TRANSACTION (
    TRANSACTION_ID BIGINT NOT NULL,  -- 交易ID (主键)
    CONTRACT_CODE VARCHAR(100) NOT NULL,  -- 合约编号
    SWAP_TYPE VARCHAR(50) NOT NULL,  -- 掉期类型 (INTEREST_RATE-利率掉期, CURRENCY-货币掉期, COMMODITY-商品掉期, CDS-信用违约掉期)
    NOTIONAL_AMOUNT DECIMAL(20,4) NOT NULL,  -- 名义本金
    CURRENCY VARCHAR(10) NOT NULL,  -- 币种
    EFFECTIVE_DATE DATE NOT NULL,  -- 生效日期
    MATURITY_DATE DATE NOT NULL,  -- 到期日期
    FIXED_RATE DECIMAL(10,4),  -- 固定利率
    FLOATING_RATE_BASIS VARCHAR(50),  -- 浮动利率基准 (SHIBOR, LPR, LIBOR, SOFR)
    SPREAD DECIMAL(10,4),  -- 利差(bp)
    PAYMENT_FREQUENCY VARCHAR(50),  -- 支付频率 (MONTHLY-月度, QUARTERLY-季度, SEMI_ANNUAL-半年, ANNUAL-年度)
    DAY_COUNT_BASIS VARCHAR(20),  -- 计息基准 (ACT_360, ACT_365, 30_360)
    PAY_DIRECTION VARCHAR(50),  -- 支付方向 (PAY_FIXED-支付固定/收取浮动, RECEIVE_FIXED-收取固定/支付浮动)
    PAY_CURRENCY VARCHAR(10),  -- 支付币种 (货币掉期专用)
    RECEIVE_CURRENCY VARCHAR(10),  -- 收取币种 (货币掉期专用)
    PAY_NOTIONAL DECIMAL(20,4),  -- 支付本金 (货币掉期专用)
    RECEIVE_NOTIONAL DECIMAL(20,4),  -- 收取本金 (货币掉期专用)
    INITIAL_EXCHANGE_RATE DECIMAL(20,4),  -- 初始汇率 (货币掉期专用)
    EXCHANGE_PRINCIPAL VARCHAR(1),  -- 是否交换本金 (货币掉期专用)
    CURRENT_VALUE DECIMAL(20,4),  -- 当前估值
    NEXT_PAYMENT_DATE DATE,  -- 下次支付日期
    STATUS VARCHAR(20) NOT NULL,  -- 状态 (PENDING-待生效, ACTIVE-生效中, TERMINATED-已终止, MATURED-已到期, CANCELLED-已取消)
    COUNTERPARTY VARCHAR(200),  -- 交易对手
    COUNTERPARTY_RATING VARCHAR(20),  -- 对手评级
    REMARK VARCHAR(1000),  -- 备注
    ORG_ID BIGINT NOT NULL,  -- 机构ID
    CREATE_TIME DATETIME NOT NULL,  -- 创建时间
    UPDATE_TIME DATETIME NOT NULL,  -- 更新时间
    CREATE_BY VARCHAR(100),  -- 创建人
    UPDATE_BY VARCHAR(100),  -- 更新人
    DEL_FLAG VARCHAR(1) DEFAULT '0' NOT NULL,  -- 删除标志
    CONSTRAINT PK_SWAP_TRANSACTION PRIMARY KEY (TRANSACTION_ID)
);

-- 表注释
COMMENT ON TABLE TBL_SWAP_TRANSACTION IS '掉期交易表';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.TRANSACTION_ID IS '交易ID';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.CONTRACT_CODE IS '合约编号';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.SWAP_TYPE IS '掉期类型';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.NOTIONAL_AMOUNT IS '名义本金';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.CURRENCY IS '币种';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.EFFECTIVE_DATE IS '生效日期';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.MATURITY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.FIXED_RATE IS '固定利率';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.FLOATING_RATE_BASIS IS '浮动利率基准';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.SPREAD IS '利差';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.PAYMENT_FREQUENCY IS '支付频率';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.DAY_COUNT_BASIS IS '计息基准';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.PAY_DIRECTION IS '支付方向';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.PAY_CURRENCY IS '支付币种';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.RECEIVE_CURRENCY IS '收取币种';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.PAY_NOTIONAL IS '支付本金';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.RECEIVE_NOTIONAL IS '收取本金';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.INITIAL_EXCHANGE_RATE IS '初始汇率';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.EXCHANGE_PRINCIPAL IS '是否交换本金';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.CURRENT_VALUE IS '当前估值';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.NEXT_PAYMENT_DATE IS '下次支付日期';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.STATUS IS '状态';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.COUNTERPARTY IS '交易对手';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.COUNTERPARTY_RATING IS '对手评级';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.REMARK IS '备注';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.ORG_ID IS '机构ID';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.DEL_FLAG IS '删除标志';

-- 创建索引
CREATE INDEX IDX_SWAP_CONTRACT_CODE ON TBL_SWAP_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_SWAP_ORG_ID ON TBL_SWAP_TRANSACTION(ORG_ID);
CREATE INDEX IDX_SWAP_STATUS ON TBL_SWAP_TRANSACTION(STATUS);
CREATE INDEX IDX_SWAP_EFFECTIVE_DATE ON TBL_SWAP_TRANSACTION(EFFECTIVE_DATE);
CREATE INDEX IDX_SWAP_MATURITY_DATE ON TBL_SWAP_TRANSACTION(MATURITY_DATE);
CREATE INDEX IDX_SWAP_DEL_FLAG ON TBL_SWAP_TRANSACTION(DEL_FLAG);

-- ================================================================
-- 7. 掉期现金流表 (TBL_SWAP_CASHFLOW)
-- ================================================================
CREATE TABLE TBL_SWAP_CASHFLOW (
    CASHFLOW_ID BIGINT NOT NULL,  -- 现金流ID (主键)
    TRANSACTION_ID BIGINT NOT NULL,  -- 交易ID (外键)
    PAYMENT_DATE DATE NOT NULL,  -- 支付日期
    PAYMENT_TYPE VARCHAR(50) NOT NULL,  -- 支付类型 (FIXED-固定, FLOATING-浮动)
    PAY_AMOUNT DECIMAL(20,4),  -- 支付金额
    RECEIVE_AMOUNT DECIMAL(20,4),  -- 收取金额
    NET_CASHFLOW DECIMAL(20,4),  -- 净现金流
    STATUS VARCHAR(20) NOT NULL,  -- 状态 (PENDING-待支付, PAID-已支付)
    ACTUAL_PAY_DATE DATE,  -- 实际支付日期
    REMARK VARCHAR(1000),  -- 备注
    ORG_ID BIGINT NOT NULL,  -- 机构ID
    CREATE_TIME DATETIME NOT NULL,  -- 创建时间
    UPDATE_TIME DATETIME NOT NULL,  -- 更新时间
    CONSTRAINT PK_SWAP_CASHFLOW PRIMARY KEY (CASHFLOW_ID)
);

-- 表注释
COMMENT ON TABLE TBL_SWAP_CASHFLOW IS '掉期现金流表';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.CASHFLOW_ID IS '现金流ID';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.TRANSACTION_ID IS '交易ID';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.PAYMENT_DATE IS '支付日期';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.PAYMENT_TYPE IS '支付类型';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.PAY_AMOUNT IS '支付金额';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.RECEIVE_AMOUNT IS '收取金额';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.NET_CASHFLOW IS '净现金流';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.STATUS IS '状态';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.ACTUAL_PAY_DATE IS '实际支付日期';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.REMARK IS '备注';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.ORG_ID IS '机构ID';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_SWAP_CASHFLOW.UPDATE_TIME IS '更新时间';

-- 创建索引
CREATE INDEX IDX_SC_TRANSACTION_ID ON TBL_SWAP_CASHFLOW(TRANSACTION_ID);
CREATE INDEX IDX_SC_ORG_ID ON TBL_SWAP_CASHFLOW(ORG_ID);
CREATE INDEX IDX_SC_PAYMENT_DATE ON TBL_SWAP_CASHFLOW(PAYMENT_DATE);
CREATE INDEX IDX_SC_STATUS ON TBL_SWAP_CASHFLOW(STATUS);

-- ================================================================
-- 8. 衍生品监控预警表 (TBL_DERIVATIVES_ALERT)
-- ================================================================
CREATE TABLE TBL_DERIVATIVES_ALERT (
    ALERT_ID BIGINT NOT NULL,  -- 预警ID (主键)
    ALERT_NAME VARCHAR(200) NOT NULL,  -- 预警名称
    ALERT_TYPE VARCHAR(50) NOT NULL,  -- 预警类型 (PRICE_ALERT-价格预警, RISK_ALERT-风险预警, POSITION_ALERT-持仓预警, EXPIRY_ALERT-到期预警)
    MONITORING_METRIC VARCHAR(100) NOT NULL,  -- 监控指标
    THRESHOLD DECIMAL(20,4) NOT NULL,  -- 阈值
    CURRENT_VALUE DECIMAL(20,4),  -- 当前值
    ALERT_LEVEL VARCHAR(20) NOT NULL,  -- 预警级别 (LOW-低, MEDIUM-中, HIGH-高, CRITICAL-紧急)
    STATUS VARCHAR(20) NOT NULL,  -- 状态 (ACTIVE-活跃, TRIGGERED-已触发, PROCESSED-已处理, IGNORED-已忽略)
    TRIGGER_TIME DATETIME,  -- 触发时间
    NOTIFICATION_METHOD VARCHAR(200),  -- 通知方式 (EMAIL-邮件, SMS-短信, SYSTEM-系统通知, 多个用逗号分隔)
    DESCRIPTION VARCHAR(1000),  -- 描述
    TRANSACTION_ID BIGINT,  -- 关联交易ID
    ORG_ID BIGINT NOT NULL,  -- 机构ID
    CREATE_TIME DATETIME NOT NULL,  -- 创建时间
    UPDATE_TIME DATETIME NOT NULL,  -- 更新时间
    CREATE_BY VARCHAR(100),  -- 创建人
    UPDATE_BY VARCHAR(100),  -- 更新人
    DEL_FLAG VARCHAR(1) DEFAULT '0' NOT NULL,  -- 删除标志
    CONSTRAINT PK_DERIVATIVES_ALERT PRIMARY KEY (ALERT_ID)
);

-- 表注释
COMMENT ON TABLE TBL_DERIVATIVES_ALERT IS '衍生品监控预警表';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_ID IS '预警ID';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_NAME IS '预警名称';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_TYPE IS '预警类型';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.MONITORING_METRIC IS '监控指标';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.THRESHOLD IS '阈值';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.CURRENT_VALUE IS '当前值';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_LEVEL IS '预警级别';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.STATUS IS '状态';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.TRIGGER_TIME IS '触发时间';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.NOTIFICATION_METHOD IS '通知方式';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.DESCRIPTION IS '描述';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.TRANSACTION_ID IS '关联交易ID';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ORG_ID IS '机构ID';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.DEL_FLAG IS '删除标志';

-- 创建索引
CREATE INDEX IDX_DA_ORG_ID ON TBL_DERIVATIVES_ALERT(ORG_ID);
CREATE INDEX IDX_DA_ALERT_TYPE ON TBL_DERIVATIVES_ALERT(ALERT_TYPE);
CREATE INDEX IDX_DA_ALERT_LEVEL ON TBL_DERIVATIVES_ALERT(ALERT_LEVEL);
CREATE INDEX IDX_DA_STATUS ON TBL_DERIVATIVES_ALERT(STATUS);
CREATE INDEX IDX_DA_TRANSACTION_ID ON TBL_DERIVATIVES_ALERT(TRANSACTION_ID);
CREATE INDEX IDX_DA_DEL_FLAG ON TBL_DERIVATIVES_ALERT(DEL_FLAG);

-- ================================================================
-- 9. 衍生品市场数据表 (TBL_DERIVATIVES_MARKET_DATA)
-- ================================================================
CREATE TABLE TBL_DERIVATIVES_MARKET_DATA (
    MARKET_DATA_ID BIGINT NOT NULL,  -- 市场数据ID (主键)
    ASSET_TYPE VARCHAR(50) NOT NULL,  -- 资产类型
    ASSET_CODE VARCHAR(50) NOT NULL,  -- 资产代码
    ASSET_NAME VARCHAR(200) NOT NULL,  -- 资产名称
    CURRENT_PRICE DECIMAL(20,4) NOT NULL,  -- 当前价格
    PRICE_CHANGE DECIMAL(10,4),  -- 涨跌幅
    VOLATILITY DECIMAL(10,4),  -- 波动率
    VOLUME BIGINT,  -- 成交量
    OPEN_PRICE DECIMAL(20,4),  -- 开盘价
    HIGH_PRICE DECIMAL(20,4),  -- 最高价
    LOW_PRICE DECIMAL(20,4),  -- 最低价
    CLOSE_PRICE DECIMAL(20,4),  -- 收盘价
    DATA_SOURCE VARCHAR(100),  -- 数据源
    UPDATE_TIME DATETIME NOT NULL,  -- 更新时间
    ORG_ID BIGINT NOT NULL,  -- 机构ID
    CONSTRAINT PK_DERIVATIVES_MARKET_DATA PRIMARY KEY (MARKET_DATA_ID)
);

-- 表注释
COMMENT ON TABLE TBL_DERIVATIVES_MARKET_DATA IS '衍生品市场数据表';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.MARKET_DATA_ID IS '市场数据ID';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.ASSET_TYPE IS '资产类型';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.ASSET_CODE IS '资产代码';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.ASSET_NAME IS '资产名称';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.CURRENT_PRICE IS '当前价格';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.PRICE_CHANGE IS '涨跌幅';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.VOLATILITY IS '波动率';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.VOLUME IS '成交量';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.OPEN_PRICE IS '开盘价';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.HIGH_PRICE IS '最高价';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.LOW_PRICE IS '最低价';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.CLOSE_PRICE IS '收盘价';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.DATA_SOURCE IS '数据源';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_DERIVATIVES_MARKET_DATA.ORG_ID IS '机构ID';

-- 创建索引
CREATE INDEX IDX_DMD_ASSET_CODE ON TBL_DERIVATIVES_MARKET_DATA(ASSET_CODE);
CREATE INDEX IDX_DMD_ASSET_TYPE ON TBL_DERIVATIVES_MARKET_DATA(ASSET_TYPE);
CREATE INDEX IDX_DMD_ORG_ID ON TBL_DERIVATIVES_MARKET_DATA(ORG_ID);
CREATE INDEX IDX_DMD_UPDATE_TIME ON TBL_DERIVATIVES_MARKET_DATA(UPDATE_TIME);

-- ================================================================
-- 测试数据
-- ================================================================

-- 期货交易测试数据
INSERT INTO TBL_FUTURES_TRANSACTION (
    TRANSACTION_ID, CONTRACT_CODE, FUTURES_TYPE, UNDERLYING_ASSET, DIRECTION, CONTRACT_SIZE,
    OPEN_PRICE, CURRENT_PRICE, CURRENCY, EXPIRY_DATE, TRADE_DATE, INITIAL_MARGIN,
    MAINTENANCE_MARGIN, MARGIN, STATUS, EXCHANGE, TRADER, ORG_ID,
    CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    1, 'FU202601001', 'COMMODITY', '螺纹钢', 'LONG', 100,
    3800.0000, 3850.0000, 'CNY', DATE '2026-06-15', DATE '2026-01-21', 380000.0000,
    300000.0000, 380000.0000, 'OPEN', 'SHFE', '张三', 1,
    DATETIME '2026-01-21 10:00:00', DATETIME '2026-01-21 10:00:00', 'admin', 'admin', '0'
);

-- 远期交易测试数据
INSERT INTO TBL_FORWARD_TRANSACTION (
    TRANSACTION_ID, CONTRACT_CODE, TRANSACTION_TYPE, UNDERLYING_ASSET, NOTIONAL_AMOUNT,
    FORWARD_PRICE, CURRENT_VALUE, CURRENCY, TRADE_DATE, MATURITY_DATE, STATUS,
    TRADER, ORG_ID, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    1, 'FW202601001', 'FX_FORWARD', 'USD/CNY', 1000000.0000,
    7.2000, 50000.0000, 'CNY', DATE '2026-01-21', DATE '2026-07-21', 'ACTIVE',
    '李四', 1, DATETIME '2026-01-21 10:00:00', DATETIME '2026-01-21 10:00:00', 'admin', 'admin', '0'
);

-- 掉期交易测试数据
INSERT INTO TBL_SWAP_TRANSACTION (
    TRANSACTION_ID, CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY, EFFECTIVE_DATE,
    MATURITY_DATE, FIXED_RATE, FLOATING_RATE_BASIS, PAYMENT_FREQUENCY, STATUS,
    ORG_ID, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    1, 'SW202601001', 'INTEREST_RATE', 10000000.0000, 'CNY', DATE '2026-01-21',
    DATE '2028-01-21', 4.5000, 'LPR', 'QUARTERLY', 'ACTIVE',
    1, DATETIME '2026-01-21 10:00:00', DATETIME '2026-01-21 10:00:00', 'admin', 'admin', '0'
);

COMMIT;

-- ================================================================
-- 脚本结束
-- ================================================================
