-- =====================================================================
-- 衍生品持仓监控 - 问题诊断SQL
-- 生成日期: 2026-01-21
-- 说明: 诊断为什么前端返回空数据
-- =====================================================================

SELECT '========== 步骤1: 检查表是否存在 ==========' AS INFO;

-- 检查所有衍生品表
SELECT TABLE_NAME, NUM_ROWS FROM USER_TABLES
WHERE TABLE_NAME IN (
    'TBL_FORWARD_TRANSACTION',
    'TBL_OPTION_TRANSACTION',
    'TBL_FUTURES_TRANSACTION',
    'TBL_SWAP_TRANSACTION'
)
ORDER BY TABLE_NAME;

SELECT '========== 步骤2: 检查各表记录数 ==========' AS INFO;

-- 检查总记录数
SELECT 'TBL_FORWARD_TRANSACTION' AS 表名, COUNT(*) AS 总记录数,
       SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS 活跃,
       SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END) AS 待生效
FROM TBL_FORWARD_TRANSACTION
UNION ALL
SELECT 'TBL_OPTION_TRANSACTION', COUNT(*),
       SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END),
       SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END)
FROM TBL_OPTION_TRANSACTION
UNION ALL
SELECT 'TBL_FUTURES_TRANSACTION', COUNT(*),
       SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END),
       SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END)
FROM TBL_FUTURES_TRANSACTION
UNION ALL
SELECT 'TBL_SWAP_TRANSACTION', COUNT(*),
       SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END),
       SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END)
FROM TBL_SWAP_TRANSACTION;

SELECT '========== 步骤3: 检查ORG_ID=1的数据 ==========' AS INFO;

-- 检查ORG_ID=1的记录数
SELECT 'ORG_ID=1的总记录数: ' || COUNT(*) AS INFO FROM (
    SELECT 1 FROM TBL_FORWARD_TRANSACTION WHERE ORG_ID = 1 AND DEL_FLAG = '0'
    UNION ALL
    SELECT 1 FROM TBL_OPTION_TRANSACTION WHERE ORG_ID = 1 AND DEL_FLAG = '0'
    UNION ALL
    SELECT 1 FROM TBL_FUTURES_TRANSACTION WHERE ORG_ID = 1 AND DEL_FLAG = '0'
    UNION ALL
    SELECT 1 FROM TBL_SWAP_TRANSACTION WHERE ORG_ID = 1 AND DEL_FLAG = '0'
);

SELECT '========== 步骤4: 检查可查询的持仓数据 ==========' AS INFO;

-- 检查符合查询条件的记录(DEL_FLAG='0' AND STATUS IN ('ACTIVE','PENDING') AND ORG_ID=1)
SELECT '符合条件的持仓记录数: ' || COUNT(*) AS INFO FROM (
    SELECT 1 FROM TBL_FORWARD_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1
    UNION ALL
    SELECT 1 FROM TBL_OPTION_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1
    UNION ALL
    SELECT 1 FROM TBL_FUTURES_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1
    UNION ALL
    SELECT 1 FROM TBL_SWAP_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1
);

SELECT '========== 步骤5: 检查详细数据 ==========' AS INFO;

-- 查看远期交易详细数据
SELECT 'TBL_FORWARD_TRANSACTION 数据:' AS INFO;
SELECT CONTRACT_CODE, TRANSACTION_TYPE, UNDERLYING_ASSET, NOTIONAL_AMOUNT,
       CURRENCY, CURRENT_VALUE, PNL, STATUS, ORG_ID, DEL_FLAG
FROM TBL_FORWARD_TRANSACTION
ORDER BY TRANSACTION_ID
LIMIT 5;

-- 查看期权交易详细数据
SELECT 'TBL_OPTION_TRANSACTION 数据:' AS INFO;
SELECT CONTRACT_CODE, OPTION_TYPE, UNDERLYING_ASSET, CONTRACT_SIZE,
       THEORETICAL_VALUE, STATUS, ORG_ID, DEL_FLAG
FROM TBL_OPTION_TRANSACTION
ORDER BY TRANSACTION_ID
LIMIT 5;

-- 查看期货交易详细数据
SELECT 'TBL_FUTURES_TRANSACTION 数据:' AS INFO;
SELECT CONTRACT_CODE, FUTURES_TYPE, UNDERLYING_ASSET, CONTRACT_SIZE,
       CURRENT_PRICE, STATUS, ORG_ID, DEL_FLAG
FROM TBL_FUTURES_TRANSACTION
ORDER BY TRANSACTION_ID
LIMIT 5;

-- 查看掉期交易详细数据
SELECT 'TBL_SWAP_TRANSACTION 数据:' AS INFO;
SELECT CONTRACT_CODE, SWAP_TYPE, UNDERLYING_ASSET, NOTIONAL_AMOUNT,
       CURRENT_VALUE, STATUS, ORG_ID, DEL_FLAG
FROM TBL_SWAP_TRANSACTION
ORDER BY TRANSACTION_ID
LIMIT 5;

SELECT '========== 步骤6: 检查数据质量问题 ==========' AS INFO;

-- 检查NULL值问题
SELECT 'ORG_ID为NULL的记录数: ' || COUNT(*) AS CHECK_RESULT
FROM TBL_FORWARD_TRANSACTION WHERE ORG_ID IS NULL
UNION ALL
SELECT 'ORG_ID为NULL的记录数: ' || COUNT(*)
FROM TBL_OPTION_TRANSACTION WHERE ORG_ID IS NULL
UNION ALL
SELECT 'ORG_ID为NULL的记录数: ' || COUNT(*)
FROM TBL_FUTURES_TRANSACTION WHERE ORG_ID IS NULL
UNION ALL
SELECT 'ORG_ID为NULL的记录数: ' || COUNT(*)
FROM TBL_SWAP_TRANSACTION WHERE ORG_ID IS NULL;

-- 检查DEL_FLAG问题
SELECT 'DEL_FLAG不是0的记录数: ' || COUNT(*) AS CHECK_RESULT
FROM TBL_FORWARD_TRANSACTION WHERE DEL_FLAG <> '0' AND DEL_FLAG IS NOT NULL
UNION ALL
SELECT 'DEL_FLAG不是0的记录数: ' || COUNT(*)
FROM TBL_OPTION_TRANSACTION WHERE DEL_FLAG <> '0' AND DEL_FLAG IS NOT NULL
UNION ALL
SELECT 'DEL_FLAG不是0的记录数: ' || COUNT(*)
FROM TBL_FUTURES_TRANSACTION WHERE DEL_FLAG <> '0' AND DEL_FLAG IS NOT NULL
UNION ALL
SELECT 'DEL_FLAG不是0的记录数: ' || COUNT(*)
FROM TBL_SWAP_TRANSACTION WHERE DEL_FLAG <> '0' AND DEL_FLAG IS NOT NULL;

-- 检查STATUS问题
SELECT 'STATUS异常的记录数: ' || COUNT(*) AS CHECK_RESULT
FROM TBL_FORWARD_TRANSACTION WHERE STATUS NOT IN ('ACTIVE', 'PENDING', 'CLOSED', 'CANCELLED')
UNION ALL
SELECT 'STATUS异常的记录数: ' || COUNT(*)
FROM TBL_OPTION_TRANSACTION WHERE STATUS NOT IN ('ACTIVE', 'PENDING', 'EXERCISED', 'EXPIRED', 'CANCELLED')
UNION ALL
SELECT 'STATUS异常的记录数: ' || COUNT(*)
FROM TBL_FUTURES_TRANSACTION WHERE STATUS NOT IN ('ACTIVE', 'PENDING', 'OPEN', 'CLOSED', 'SETTLED', 'CANCELLED')
UNION ALL
SELECT 'STATUS异常的记录数: ' || COUNT(*)
FROM TBL_SWAP_TRANSACTION WHERE STATUS NOT IN ('ACTIVE', 'PENDING', 'MATURED', 'CANCELLED');

SELECT '========== 步骤7: 模拟Controller查询 ==========' AS INFO;

-- 模拟Controller的查询逻辑
SELECT PRODUCT_TYPE, COUNT(*) AS COUNT FROM (
    SELECT 'FORWARD' AS PRODUCT_TYPE FROM TBL_FORWARD_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND (1 = 1 OR 1 = 1)

    UNION ALL

    SELECT 'OPTION' FROM TBL_OPTION_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND (1 = 1 OR 1 = 1)

    UNION ALL

    SELECT 'FUTURES' FROM TBL_FUTURES_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND (1 = 1 OR 1 = 1)

    UNION ALL

    SELECT 'SWAP' FROM TBL_SWAP_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND (1 = 1 OR 1 = 1)
) GROUP BY PRODUCT_TYPE;

SELECT '========== 诊断完成 ==========' AS INFO;
SELECT '请查看以上结果确定问题所在:' AS INFO;
SELECT '1. 如果表不存在 -> 需要执行建表SQL' AS INFO;
SELECT '2. 如果记录数为0 -> 需要执行插入数据SQL' AS INFO;
SELECT '3. 如果ORG_ID不是1 -> 需要更新ORG_ID' AS INFO;
SELECT '4. 如果STATUS不是ACTIVE/PENDING -> 需要更新STATUS' AS INFO;
SELECT '5. 如果DEL_FLAG不是0 -> 需要更新DEL_FLAG' AS INFO;
