-- =============================================
-- 融资租赁管理表创建脚本
-- 数据库: 达梦数据库/MySQL/Oracle
-- 作者: 华博云开发团队
-- 日期: 2025-01-13
-- =============================================

-- 主表: 融资租赁信息表
CREATE TABLE TBL_FINANCIAL_LEASE (
    LEASE_ID BIGINT PRIMARY KEY,
    LEASE_NO VARCHAR(50) UNIQUE NOT NULL COMMENT '租赁编号',
    PLAN_ID BIGINT COMMENT '融资计划ID',
    LEASING_COMPANY VARCHAR(200) NOT NULL COMMENT '租赁公司',
    LEASING_TYPE VARCHAR(20) NOT NULL COMMENT '租赁类型(DIRECT-直接租赁,LEASEBACK-售后回租)',
    ASSET_TYPE VARCHAR(50) COMMENT '资产类型',
    ASSET_DESCRIPTION VARCHAR(500) COMMENT '资产描述',
    ASSET_VALUE DECIMAL(18,2) COMMENT '资产价值',
    LEASING_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '租赁金额',
    CURRENCY_CODE VARCHAR(10) NOT NULL COMMENT '币种',
    LEASING_TERM INT COMMENT '租赁期限',
    TERM_UNIT VARCHAR(10) COMMENT '期限单位(MONTH-月,YEAR-年)',
    INTEREST_RATE DECIMAL(10,6) COMMENT '利率',
    MONTHLY_RENT DECIMAL(18,2) COMMENT '月租金',
    RESIDUAL_VALUE DECIMAL(18,2) COMMENT '残值',
    SECURITY_DEPOSIT DECIMAL(18,2) COMMENT '保证金',
    APPLICATION_STATUS VARCHAR(20) COMMENT '申请状态(DRAFT-草稿,PENDING-待审批,APPROVED-已审批,ACTIVE-执行中,COMPLETED-已完成,TERMINATED-已终止)',
    APPLICATION_DATE DATE COMMENT '申请日期',
    CONTRACT_NO VARCHAR(50) COMMENT '合同编号',
    START_DATE DATE COMMENT '起租日期',
    END_DATE DATE COMMENT '到期日期',
    COMPANY_ID BIGINT COMMENT '公司ID',
    COMPANY_NAME VARCHAR(200) COMMENT '公司名称',
    DELETE_FLAG INT DEFAULT 0 COMMENT '删除标志(0-未删除,1-已删除)',
    CREATED_BY BIGINT COMMENT '创建人',
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_BY BIGINT COMMENT '更新人',
    UPDATED_TIME TIMESTAMP COMMENT '更新时间',
    REMARK VARCHAR(500) COMMENT '备注'
);

-- 添加索引
CREATE INDEX IDX_FL_LEASE_NO ON TBL_FINANCIAL_LEASE(LEASE_NO);
CREATE INDEX IDX_FL_COMPANY ON TBL_FINANCIAL_LEASE(COMPANY_ID);
CREATE INDEX IDX_FL_STATUS ON TBL_FINANCIAL_LEASE(APPLICATION_STATUS);
CREATE INDEX IDX_FL_TYPE ON TBL_FINANCIAL_LEASE(LEASING_TYPE);
CREATE INDEX IDX_FL_DELETE_FLAG ON TBL_FINANCIAL_LEASE(DELETE_FLAG);

-- 插入测试数据
INSERT INTO TBL_FINANCIAL_LEASE (
    LEASE_ID, LEASE_NO, PLAN_ID, LEASING_COMPANY, LEASING_TYPE,
    ASSET_TYPE, ASSET_DESCRIPTION, ASSET_VALUE, LEASING_AMOUNT,
    CURRENCY_CODE, LEASING_TERM, TERM_UNIT, INTEREST_RATE,
    MONTHLY_RENT, RESIDUAL_VALUE, SECURITY_DEPOSIT,
    APPLICATION_STATUS, APPLICATION_DATE, CONTRACT_NO,
    START_DATE, END_DATE, COMPANY_ID, COMPANY_NAME,
    DELETE_FLAG, CREATED_BY, CREATED_TIME, REMARK
) VALUES (
    1, 'FL202501130001', NULL, '华融金融租赁股份有限公司', 'DIRECT',
    '生产设备', '精密数控机床设备', 5000000.00, 4000000.00,
    'CNY', 36, 'MONTH', 0.056,
    120000.00, 200000.00, 400000.00,
    'ACTIVE', '2025-01-13', 'HT20250113001',
    '2025-01-15', '2028-01-15', 1001, '华博科技有限公司',
    0, 1, CURRENT_TIMESTAMP, '生产设备融资租赁'
);

INSERT INTO TBL_FINANCIAL_LEASE (
    LEASE_ID, LEASE_NO, PLAN_ID, LEASING_COMPANY, LEASING_TYPE,
    ASSET_TYPE, ASSET_DESCRIPTION, ASSET_VALUE, LEASING_AMOUNT,
    CURRENCY_CODE, LEASING_TERM, TERM_UNIT, INTEREST_RATE,
    MONTHLY_RENT, RESIDUAL_VALUE, SECURITY_DEPOSIT,
    APPLICATION_STATUS, APPLICATION_DATE, CONTRACT_NO,
    START_DATE, END_DATE, COMPANY_ID, COMPANY_NAME,
    DELETE_FLAG, CREATED_BY, CREATED_TIME, REMARK
) VALUES (
    2, 'FL202501130002', NULL, '远东宏信租赁有限公司', 'LEASEBACK',
    '办公设备', '服务器及网络设备', 1200000.00, 1000000.00,
    'CNY', 24, 'MONTH', 0.048,
    45000.00, 50000.00, 100000.00,
    'PENDING', '2025-01-13', 'HT20250113002',
    '2025-02-01', '2027-02-01', 1001, '华博科技有限公司',
    0, 1, CURRENT_TIMESTAMP, '办公设备售后回租'
);

COMMIT;
