-- 修复 TBL_SWAP_TRANSACTION 表中 CREATE_BY 字段的类型转换问题
-- 日期: 2026-01-21
-- 问题描述: CREATE_BY 字段可能包含 NULL 或空字符串,导致类型转换异常

-- 1. 清理 CREATE_BY 字段中的空字符串,将其转换为 NULL
UPDATE TBL_SWAP_TRANSACTION
SET CREATE_BY = NULL
WHERE CREATE_BY = '' OR CREATE_BY IS NULL;

-- 2. 如果 CREATE_BY 字段不是数值类型,需要修改字段类型(达梦数据库)
-- ALTER TABLE TBL_SWAP_TRANSACTION MODIFY CREATE_BY NUMBER(20);

-- 3. 为现有的记录设置默认的 CREATE_BY 值(可选)
-- UPDATE TBL_SWAP_TRANSACTION
-- SET CREATE_BY = 1
-- WHERE CREATE_BY IS NULL;

-- 4. 同样修复 UPDATE_BY 字段
UPDATE TBL_SWAP_TRANSACTION
SET UPDATE_BY = NULL
WHERE UPDATE_BY = '' OR UPDATE_BY IS NULL;

-- 提交
COMMIT;

-- 查询验证
SELECT TRANSACTION_ID, CONTRACT_CODE, CREATE_BY, UPDATE_BY
FROM TBL_SWAP_TRANSACTION;
