-- 资金计划相关表结构
-- 适配达梦数据库
-- 创建日期: 2025-01-19

-- 资金计划表
CREATE TABLE TBL_FUND_PLAN (
    PLAN_ID BIGINT PRIMARY KEY,
    PLAN_NO VARCHAR(50) UNIQUE NOT NULL,
    PLAN_NAME VARCHAR(200) NOT NULL,
    PLAN_TYPE VARCHAR(20),
    PLAN_STATUS VARCHAR(30),
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    TOTAL_INCOME DECIMAL(20,2),
    TOTAL_EXPENSE DECIMAL(20,2),
    NET_CASH_FLOW DECIMAL(20,2),
    COMPLETION_RATE DECIMAL(5,2),
    DESCRIPTION VARCHAR(500),
    REMARK VARCHAR(500),
    DELETE_FLAG INTEGER DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    ORG_ID BIGINT,
    ORG_NAME VARCHAR(200)
);

-- 资金计划明细表
CREATE TABLE TBL_FUND_PLAN_DETAIL (
    DETAIL_ID BIGINT PRIMARY KEY,
    PLAN_ID BIGINT NOT NULL,
    BUSINESS_TYPE VARCHAR(20),
    BUSINESS_ITEM VARCHAR(200),
    PLANNED_DATE TIMESTAMP,
    PLANNED_AMOUNT DECIMAL(20,2),
    ACTUAL_DATE TIMESTAMP,
    ACTUAL_AMOUNT DECIMAL(20,2),
    VARIANCE_AMOUNT DECIMAL(20,2),
    VARIANCE_RATE DECIMAL(5,2),
    EXECUTION_STATUS VARCHAR(20),
    EXECUTION_RATE DECIMAL(5,2),
    CURRENCY_CODE VARCHAR(10),
    DESCRIPTION VARCHAR(500),
    DELETE_FLAG INTEGER DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(50),
    UPDATED_TIME TIMESTAMP
);

-- 资金计划模板表
CREATE TABLE TBL_FUND_PLAN_TEMPLATE (
    TEMPLATE_ID BIGINT PRIMARY KEY,
    TEMPLATE_NO VARCHAR(50) UNIQUE NOT NULL,
    TEMPLATE_NAME VARCHAR(200) NOT NULL,
    TEMPLATE_TYPE VARCHAR(20),
    TEMPLATE_STATUS VARCHAR(20),
    TEMPLATE_VERSION VARCHAR(20),
    USAGE_COUNT INTEGER DEFAULT 0,
    QUALITY_SCORE INTEGER,
    LAST_USED_TIME TIMESTAMP,
    TEMPLATE_DESCRIPTION VARCHAR(500),
    TEMPLATE_CONTENT CLOB,
    DELETE_FLAG INTEGER DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    ORG_ID BIGINT,
    ORG_NAME VARCHAR(200)
);

-- 资金预测表
CREATE TABLE TBL_FUND_FORECAST (
    FORECAST_ID BIGINT PRIMARY KEY,
    FORECAST_NO VARCHAR(50) UNIQUE NOT NULL,
    FORECAST_TYPE VARCHAR(20),
    FORECAST_METHOD VARCHAR(30),
    FORECAST_DATE TIMESTAMP,
    FORECAST_AMOUNT DECIMAL(20,2),
    ACTUAL_AMOUNT DECIMAL(20,2),
    FORECAST_ACCURACY DECIMAL(5,2),
    CONFIDENCE_INTERVAL DECIMAL(5,2),
    FORECAST_PERIOD VARCHAR(20),
    DATA_SOURCE VARCHAR(20),
    DESCRIPTION VARCHAR(500),
    DELETE_FLAG INTEGER DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    ORG_ID BIGINT
);

-- 资金计划调整表
CREATE TABLE TBL_FUND_PLAN_ADJUSTMENT (
    ADJUSTMENT_ID BIGINT PRIMARY KEY,
    ADJUSTMENT_NO VARCHAR(50) UNIQUE NOT NULL,
    PLAN_ID BIGINT NOT NULL,
    ADJUSTMENT_TYPE VARCHAR(20),
    ORIGINAL_AMOUNT DECIMAL(20,2),
    ADJUSTED_AMOUNT DECIMAL(20,2),
    ADJUSTMENT_AMOUNT DECIMAL(20,2),
    APPROVAL_STATUS VARCHAR(20),
    ADJUSTMENT_REASON VARCHAR(500),
    IMPACT_ASSESSMENT VARCHAR(500),
    RISK_EVALUATION VARCHAR(20),
    APPROVE_TIME TIMESTAMP,
    APPROVER_ID BIGINT,
    APPROVER_NAME VARCHAR(50),
    APPROVE_COMMENT VARCHAR(500),
    DELETE_FLAG INTEGER DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    ORG_ID BIGINT
);

-- 资金计划分析表
CREATE TABLE TBL_FUND_PLAN_ANALYSIS (
    ANALYSIS_ID BIGINT PRIMARY KEY,
    ANALYSIS_NO VARCHAR(50) UNIQUE NOT NULL,
    PLAN_ID BIGINT NOT NULL,
    ANALYSIS_TYPE VARCHAR(20),
    ANALYSIS_PERIOD VARCHAR(20),
    QUALITY_SCORE INTEGER,
    IS_VALID INTEGER DEFAULT 0,
    VALID_UNTIL TIMESTAMP,
    VALUE_ASSESSMENT VARCHAR(20),
    TEMPLATE_ID BIGINT,
    ANALYSIS_CONTENT CLOB,
    VALIDATE_NOTES VARCHAR(500),
    DELETE_FLAG INTEGER DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    ORG_ID BIGINT
);

-- 资金计划执行表
CREATE TABLE TBL_FUND_PLAN_EXECUTION (
    EXECUTION_ID BIGINT PRIMARY KEY,
    EXECUTION_NO VARCHAR(50) UNIQUE NOT NULL,
    PLAN_ID BIGINT NOT NULL,
    DETAIL_ID BIGINT,
    EXECUTION_TYPE VARCHAR(20),
    EXECUTION_STATUS VARCHAR(20),
    PLANNED_AMOUNT DECIMAL(20,2),
    EXECUTED_AMOUNT DECIMAL(20,2),
    EXECUTION_RATE DECIMAL(5,2),
    PLANNED_DATE TIMESTAMP,
    ACTUAL_DATE TIMESTAMP,
    DELAY_DAYS INTEGER,
    EXECUTION_EFFICIENCY DECIMAL(5,2),
    RISK_LEVEL VARCHAR(20),
    EXECUTION_NOTES VARCHAR(500),
    DELETE_FLAG INTEGER DEFAULT 0,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(50),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    ORG_ID BIGINT
);

-- 创建索引
CREATE INDEX IDX_FUND_PLAN_TYPE ON TBL_FUND_PLAN(PLAN_TYPE);
CREATE INDEX IDX_FUND_PLAN_STATUS ON TBL_FUND_PLAN(PLAN_STATUS);
CREATE INDEX IDX_FUND_PLAN_DATE ON TBL_FUND_PLAN(START_DATE, END_DATE);
CREATE INDEX IDX_FUND_PLAN_ORG ON TBL_FUND_PLAN(ORG_ID);

CREATE INDEX IDX_FUND_PLAN_DETAIL_PLAN ON TBL_FUND_PLAN_DETAIL(PLAN_ID);
CREATE INDEX IDX_FUND_PLAN_DETAIL_TYPE ON TBL_FUND_PLAN_DETAIL(BUSINESS_TYPE);
CREATE INDEX IDX_FUND_PLAN_DETAIL_STATUS ON TBL_FUND_PLAN_DETAIL(EXECUTION_STATUS);

CREATE INDEX IDX_FUND_PLAN_TEMPLATE_TYPE ON TBL_FUND_PLAN_TEMPLATE(TEMPLATE_TYPE);
CREATE INDEX IDX_FUND_PLAN_TEMPLATE_ORG ON TBL_FUND_PLAN_TEMPLATE(ORG_ID);

CREATE INDEX IDX_FUND_FORECAST_TYPE ON TBL_FUND_FORECAST(FORECAST_TYPE);
CREATE INDEX IDX_FUND_FORECAST_DATE ON TBL_FUND_FORECAST(FORECAST_DATE);

CREATE INDEX IDX_FUND_PLAN_ADJUSTMENT_PLAN ON TBL_FUND_PLAN_ADJUSTMENT(PLAN_ID);
CREATE INDEX IDX_FUND_PLAN_ADJUSTMENT_STATUS ON TBL_FUND_PLAN_ADJUSTMENT(APPROVAL_STATUS);

CREATE INDEX IDX_FUND_PLAN_ANALYSIS_PLAN ON TBL_FUND_PLAN_ANALYSIS(PLAN_ID);
CREATE INDEX IDX_FUND_PLAN_ANALYSIS_TYPE ON TBL_FUND_PLAN_ANALYSIS(ANALYSIS_TYPE);

CREATE INDEX IDX_FUND_PLAN_EXECUTION_PLAN ON TBL_FUND_PLAN_EXECUTION(PLAN_ID);
CREATE INDEX IDX_FUND_PLAN_EXECUTION_DETAIL ON TBL_FUND_PLAN_EXECUTION(DETAIL_ID);
CREATE INDEX IDX_FUND_PLAN_EXECUTION_STATUS ON TBL_FUND_PLAN_EXECUTION(EXECUTION_STATUS);

-- 插入示例数据
INSERT INTO TBL_FUND_PLAN (PLAN_ID, PLAN_NO, PLAN_NAME, PLAN_TYPE, PLAN_STATUS, START_DATE, END_DATE, ORG_ID, ORG_NAME, CREATED_BY, CREATED_BY_NAME)
VALUES (1, 'FUND-2025001', '2025年度资金计划', 'ANNUAL', 'DRAFT', TIMESTAMP '2025-01-01 00:00:00', TIMESTAMP '2025-12-31 23:59:59', 1, '华博云总部', 1, '管理员');

INSERT INTO TBL_FUND_PLAN_DETAIL (DETAIL_ID, PLAN_ID, BUSINESS_TYPE, BUSINESS_ITEM, PLANNED_DATE, PLANNED_AMOUNT, EXECUTION_STATUS, CURRENCY_CODE, CREATED_BY, CREATED_BY_NAME)
VALUES (1, 1, 'INCOME', '销售收入', TIMESTAMP '2025-01-15', 1000000.00, 'PENDING', 'CNY', 1, '管理员');

INSERT INTO TBL_FUND_PLAN_DETAIL (DETAIL_ID, PLAN_ID, BUSINESS_TYPE, BUSINESS_ITEM, PLANNED_DATE, PLANNED_AMOUNT, EXECUTION_STATUS, CURRENCY_CODE, CREATED_BY, CREATED_BY_NAME)
VALUES (2, 1, 'EXPENSE', '采购支出', TIMESTAMP '2025-01-20', 500000.00, 'PENDING', 'CNY', 1, '管理员');

COMMIT;
