-- 创建持仓监控视图
-- 整合远期、期货、期权、掉期数据
-- 兼容达梦数据库
-- 日期: 2026-01-21

-- 删除视图(如果存在)
DROP VIEW IF EXISTS V_POSITION_MONITORING;

-- 创建持仓监控视图
CREATE VIEW V_POSITION_MONITORING AS
SELECT
    'FORWARD' AS PRODUCT_TYPE,
    CONTRACT_CODE,
    UNDERLYING_ASSET,
    NOTIONAL_AMOUNT AS POSITION_SIZE,
    CURRENT_VALUE AS MARKET_VALUE,
    PNL AS UNREALIZED_PNL,
    0.85 AS DELTA,
    0.02 AS GAMMA,
    MATURITY_DATE,
    CASE
        WHEN ABS(PNL) < 50000 THEN 'LOW'
        WHEN ABS(PNL) < 150000 THEN 'MEDIUM'
        WHEN ABS(PNL) < 300000 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS RISK_LEVEL,
    CURRENCY,
    CREATE_TIME AS UPDATE_TIME
FROM TBL_FORWARD_TRANSACTION
WHERE DEL_FLAG = 0 AND STATUS IN ('ACTIVE', 'PENDING')

UNION ALL

SELECT
    'FUTURES' AS PRODUCT_TYPE,
    CONTRACT_CODE,
    UNDERLYING_ASSET,
    CONTRACT_SIZE AS POSITION_SIZE,
    (CONTRACT_SIZE * CURRENT_PRICE) AS MARKET_VALUE,
    UNREALIZED_PNL,
    DIRECTION AS DELTA,
    0.01 AS GAMMA,
    EXPIRY_DATE AS MATURITY_DATE,
    CASE
        WHEN ABS(UNREALIZED_PNL) < 50000 THEN 'LOW'
        WHEN ABS(UNREALIZED_PNL) < 150000 THEN 'MEDIUM'
        WHEN ABS(UNREALIZED_PNL) < 300000 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS RISK_LEVEL,
    CURRENCY,
    CREATE_TIME AS UPDATE_TIME
FROM TBL_FUTURES_TRANSACTION
WHERE DEL_FLAG = 0 AND STATUS IN ('OPEN', 'PENDING')

UNION ALL

SELECT
    'OPTION' AS PRODUCT_TYPE,
    CONTRACT_CODE,
    UNDERLYING_ASSET,
    CONTRACT_SIZE AS POSITION_SIZE,
    CURRENT_VALUE AS MARKET_VALUE,
    PNL AS UNREALIZED_PNL,
    DELTA,
    GAMMA,
    EXERCISE_DATE AS MATURITY_DATE,
    CASE
        WHEN ABS(PNL) < 50000 THEN 'LOW'
        WHEN ABS(PNL) < 150000 THEN 'MEDIUM'
        WHEN ABS(PNL) < 300000 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS RISK_LEVEL,
    CURRENCY,
    CREATE_TIME AS UPDATE_TIME
FROM TBL_OPTION_TRANSACTION
WHERE DEL_FLAG = 0 AND STATUS IN ('ACTIVE', 'PENDING')

UNION ALL

SELECT
    'SWAP' AS PRODUCT_TYPE,
    CONTRACT_CODE,
    UNDERLYING_ASSET,
    NOTIONAL_AMOUNT AS POSITION_SIZE,
    CURRENT_VALUE AS MARKET_VALUE,
    PNL AS UNREALIZED_PNL,
    1.00 AS DELTA,
    0.00 AS GAMMA,
    MATURITY_DATE,
    CASE
        WHEN ABS(PNL) < 50000 THEN 'LOW'
        WHEN ABS(PNL) < 150000 THEN 'MEDIUM'
        WHEN ABS(PNL) < 300000 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS RISK_LEVEL,
    CURRENCY,
    CREATE_TIME AS UPDATE_TIME
FROM TBL_SWAP_TRANSACTION
WHERE DEL_FLAG = 0 AND STATUS = 'ACTIVE';

-- 查询验证数据
SELECT COUNT(*) AS TOTAL_POSITIONS FROM V_POSITION_MONITORING;
SELECT PRODUCT_TYPE, CONTRACT_CODE, UNDERLYING_ASSET, MARKET_VALUE, UNREALIZED_PNL, RISK_LEVEL
FROM V_POSITION_MONITORING
ORDER BY PRODUCT_TYPE, MATURITY_DATE;
