-- 金融分类管理表
CREATE TABLE TBL_FINANCIAL_CATEGORY (
    CATEGORY_ID VARCHAR2(64) PRIMARY KEY,
    CATEGORY_CODE VARCHAR2(50) NOT NULL UNIQUE,
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    PARENT_CATEGORY_ID VARCHAR2(64),
    CATEGORY_LEVEL NUMBER(2) DEFAULT 1,
    DESCRIPTION VARCHAR2(500),
    IS_ENABLED NUMBER(1) DEFAULT 1 CHECK (IS_ENABLED IN (0, 1)),
    SORT_ORDER NUMBER(4) DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR2(50),
    UPDATE_USER VARCHAR2(50)
);

-- 添加索引
CREATE INDEX IDX_CATEGORY_CODE ON TBL_FINANCIAL_CATEGORY(CATEGORY_CODE);
CREATE INDEX IDX_CATEGORY_PARENT ON TBL_FINANCIAL_CATEGORY(PARENT_CATEGORY_ID);
CREATE INDEX IDX_CATEGORY_LEVEL ON TBL_FINANCIAL_CATEGORY(CATEGORY_LEVEL);
CREATE INDEX IDX_CATEGORY_ENABLED ON TBL_FINANCIAL_CATEGORY(IS_ENABLED);
CREATE INDEX IDX_CATEGORY_SORT ON TBL_FINANCIAL_CATEGORY(SORT_ORDER);

-- 添加外键约束（自关联）
ALTER TABLE TBL_FINANCIAL_CATEGORY ADD CONSTRAINT FK_CATEGORY_PARENT
FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES TBL_FINANCIAL_CATEGORY(CATEGORY_ID);

-- 插入初始数据
INSERT INTO TBL_FINANCIAL_CATEGORY (
    CATEGORY_ID,
    CATEGORY_CODE,
    CATEGORY_NAME,
    PARENT_CATEGORY_ID,
    CATEGORY_LEVEL,
    DESCRIPTION,
    IS_ENABLED,
    SORT_ORDER,
    CREATE_USER
) VALUES (
    SYS_GUID(),
    'BANK_WEALTH',
    '银行理财',
    NULL,
    1,
    '银行发行的理财产品，包括保本型和非保本型理财产品',
    1,
    1,
    'SYSTEM'
);

INSERT INTO TBL_FINANCIAL_CATEGORY (
    CATEGORY_ID,
    CATEGORY_CODE,
    CATEGORY_NAME,
    PARENT_CATEGORY_ID,
    CATEGORY_LEVEL,
    DESCRIPTION,
    IS_ENABLED,
    SORT_ORDER,
    CREATE_USER
) VALUES (
    SYS_GUID(),
    'BOND_INVEST',
    '债券投资',
    NULL,
    1,
    '债券类投资产品，包括国债、企业债、金融债等',
    1,
    2,
    'SYSTEM'
);

INSERT INTO TBL_FINANCIAL_CATEGORY (
    CATEGORY_ID,
    CATEGORY_CODE,
    CATEGORY_NAME,
    PARENT_CATEGORY_ID,
    CATEGORY_LEVEL,
    DESCRIPTION,
    IS_ENABLED,
    SORT_ORDER,
    CREATE_USER
) VALUES (
    SYS_GUID(),
    'STOCK_INVEST',
    '股票投资',
    NULL,
    1,
    '股票类投资产品，包括A股、港股、美股等',
    1,
    3,
    'SYSTEM'
);

INSERT INTO TBL_FINANCIAL_CATEGORY (
    CATEGORY_ID,
    CATEGORY_CODE,
    CATEGORY_NAME,
    PARENT_CATEGORY_ID,
    CATEGORY_LEVEL,
    DESCRIPTION,
    IS_ENABLED,
    SORT_ORDER,
    CREATE_USER
) VALUES (
    SYS_GUID(),
    'FUND_INVEST',
    '基金投资',
    NULL,
    1,
    '基金类投资产品，包括公募基金、私募基金等',
    1,
    4,
    'SYSTEM'
);

INSERT INTO TBL_FINANCIAL_CATEGORY (
    CATEGORY_ID,
    CATEGORY_CODE,
    CATEGORY_NAME,
    PARENT_CATEGORY_ID,
    CATEGORY_LEVEL,
    DESCRIPTION,
    IS_ENABLED,
    SORT_ORDER,
    CREATE_USER
) VALUES (
    SYS_GUID(),
    'DERIVATIVE_INVEST',
    '衍生品投资',
    NULL,
    1,
    '衍生品类投资产品，包括期货、期权、掉期等',
    1,
    5,
    'SYSTEM'
);

-- 获取父分类ID（企业债券的父分类是债券投资）
DECLARE
    v_parent_id VARCHAR2(64);
BEGIN
    SELECT CATEGORY_ID INTO v_parent_id FROM TBL_FINANCIAL_CATEGORY WHERE CATEGORY_CODE = 'BOND_INVEST';

    INSERT INTO TBL_FINANCIAL_CATEGORY (
        CATEGORY_ID,
        CATEGORY_CODE,
        CATEGORY_NAME,
        PARENT_CATEGORY_ID,
        CATEGORY_LEVEL,
        DESCRIPTION,
        IS_ENABLED,
        SORT_ORDER,
        CREATE_USER
    ) VALUES (
        SYS_GUID(),
        'CORP_BOND',
        '企业债券',
        v_parent_id,
        2,
        '企业发行的债券产品',
        1,
        1,
        'SYSTEM'
    );
END;
/