-- =============================================================
-- 表名: TBL_GT_EXCHANGE_RATE
-- 描述: 全球司库-汇率配置表
-- 数据库: 达梦数据库兼容
-- 作者: Claude Code
-- 日期: 2025-01-21
-- =============================================================

-- 删除表(如果存在)
DROP TABLE IF EXISTS TBL_GT_EXCHANGE_RATE;

-- 创建表
CREATE TABLE TBL_GT_EXCHANGE_RATE (
    RATE_ID BIGINT IDENTITY(1,1) NOT NULL,
    FROM_CURRENCY VARCHAR(10) NOT NULL,
    TO_CURRENCY VARCHAR(10) NOT NULL,
    EXCHANGE_RATE DECIMAL(18,6) NOT NULL,
    MIDDLE_RATE DECIMAL(18,6),
    BUY_RATE DECIMAL(18,6),
    SELL_RATE DECIMAL(18,6),
    CASH_BUY_RATE DECIMAL(18,6),
    CASH_SELL_RATE DECIMAL(18,6),
    RATE_TYPE VARCHAR(20) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRE_DATE DATE,
    RATE_SOURCE VARCHAR(50),
    DATA_SOURCE VARCHAR(20),
    IS_ACTIVE INT DEFAULT 1 NOT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY VARCHAR(50),
    UPDATE_BY VARCHAR(50)
);

-- 添加表注释
COMMENT ON TABLE TBL_GT_EXCHANGE_RATE IS '全球司库-汇率配置表';

-- 添加字段注释
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.RATE_ID IS '汇率ID';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.FROM_CURRENCY IS '源币种(USD/CNY/EUR/JPY/GBP/HKD)';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.TO_CURRENCY IS '目标币种(USD/CNY/EUR/JPY/GBP/HKD)';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.EXCHANGE_RATE IS '汇率';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.MIDDLE_RATE IS '中间价';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.BUY_RATE IS '买入价';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.SELL_RATE IS '卖出价';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.CASH_BUY_RATE IS '现钞买入价';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.CASH_SELL_RATE IS '现钞卖出价';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.RATE_TYPE IS '汇率类型(SPOT-现汇/CASH-现钞/MIDDLE-中间价)';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.EFFECTIVE_DATE IS '生效日期';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.EXPIRE_DATE IS '失效日期';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.RATE_SOURCE IS '汇率来源(PBOC-央行/SAFE-外汇局/BANK-银行/THIRD_PARTY-第三方)';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.DATA_SOURCE IS '数据来源(MANUAL-手工录入/AUTO-自动获取/API-API接口)';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.IS_ACTIVE IS '是否启用(1-启用/0-停用)';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.STATUS IS '状态(1-正常/0-删除)';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.REMARK IS '备注';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_GT_EXCHANGE_RATE.UPDATE_BY IS '更新人';

-- 创建索引
CREATE INDEX IDX_RATE_CURRENCY_PAIR ON TBL_GT_EXCHANGE_RATE(FROM_CURRENCY, TO_CURRENCY);
CREATE INDEX IDX_RATE_EFFECTIVE_DATE ON TBL_GT_EXCHANGE_RATE(EFFECTIVE_DATE);
CREATE INDEX IDX_RATE_TYPE ON TBL_GT_EXCHANGE_RATE(RATE_TYPE);
CREATE INDEX IDX_RATE_SOURCE ON TBL_GT_EXCHANGE_RATE(RATE_SOURCE);
CREATE INDEX IDX_RATE_STATUS ON TBL_GT_EXCHANGE_RATE(STATUS, IS_ACTIVE);
CREATE INDEX IDX_RATE_CREATE_TIME ON TBL_GT_EXCHANGE_RATE(CREATE_TIME);

-- 插入测试数据
INSERT INTO TBL_GT_EXCHANGE_RATE (FROM_CURRENCY, TO_CURRENCY, EXCHANGE_RATE, MIDDLE_RATE, BUY_RATE, SELL_RATE, CASH_BUY_RATE, CASH_SELL_RATE, RATE_TYPE, EFFECTIVE_DATE, RATE_SOURCE, DATA_SOURCE, IS_ACTIVE, STATUS, CREATE_BY, UPDATE_BY) VALUES
('USD', 'CNY', 7.2456, 7.2456, 7.1100, 7.1368, 7.0950, 7.1518, 'SPOT', '2024-01-01', 'PBOC', 'API', 1, 1, 'admin', 'admin'),
('EUR', 'CNY', 7.8923, 7.8923, 7.9200, 7.9712, 7.8950, 7.9962, 'SPOT', '2024-01-01', 'PBOC', 'API', 1, 1, 'admin', 'admin'),
('JPY', 'CNY', 0.0489, 0.0489, 0.0476, 0.0480, 0.0474, 0.0482, 'SPOT', '2024-01-01', 'PBOC', 'API', 1, 1, 'admin', 'admin'),
('GBP', 'CNY', 9.1234, 9.1234, 9.1000, 9.1500, 9.0800, 9.1700, 'SPOT', '2024-01-01', 'PBOC', 'API', 1, 1, 'admin', 'admin'),
('HKD', 'CNY', 0.9278, 0.9278, 0.9250, 0.9300, 0.9230, 0.9320, 'SPOT', '2024-01-01', 'PBOC', 'API', 1, 1, 'admin', 'admin'),
('CNY', 'USD', 0.1380, 0.1380, 0.1375, 0.1385, 0.1370, 0.1390, 'SPOT', '2024-01-01', 'PBOC', 'API', 1, 1, 'admin', 'admin');

COMMIT;
