-- ============================================================
-- 融资审批表
-- 兼容达梦数据库/MySQL/Oracle
-- ============================================================

-- 达梦数据库/MySQL语法
CREATE TABLE TBL_FINANCING_APPROVAL (
    APPROVAL_ID DECIMAL(20,0) NOT NULL,                    -- 审批ID
    FINANCING_TYPE VARCHAR(50) NOT NULL,                   -- 融资类型(BANK_LOAN-银行贷款,BOND_ISSUANCE-债券发行,FINANCIAL_LEASE-融资租赁)
    FINANCING_ID DECIMAL(20,0) NOT NULL,                   -- 融资ID
    FINANCING_NO VARCHAR(64),                              -- 融资编号
    COMPANY_ID DECIMAL(20,0) NOT NULL,                     -- 公司ID
    COMPANY_NAME VARCHAR(255),                             -- 公司名称
    FINANCING_AMOUNT DECIMAL(20,4),                        -- 融资金额
    CURRENCY_CODE VARCHAR(10),                             -- 币种
    FINANCING_TERM INTEGER,                                -- 融资期限
    TERM_UNIT VARCHAR(20),                                 -- 期限单位(YEAR-年,MONTH-月,DAY-日)
    INTEREST_RATE DECIMAL(10,6),                           -- 利率(%)
    REPAYMENT_METHOD VARCHAR(50),                          -- 还款方式(EQUAL_INSTALLMENT-等额本息,EQUAL_PRINCIPAL-等额本金,BULLET-到期还本)
    GUARANTEE_METHOD VARCHAR(50),                          -- 担保方式(CREDIT-信用,MORTGAGE-抵押,PLEDGE-质押,GUARANTEE-保证)
    FUND_PURPOSE VARCHAR(500),                             -- 资金用途
    APPLICANT_ID DECIMAL(20,0),                            -- 申请人ID
    APPLICANT_NAME VARCHAR(100),                           -- 申请人姓名
    APPLICATION_TIME TIMESTAMP,                            -- 申请时间
    CURRENT_APPROVAL_NODE VARCHAR(50),                     -- 当前审批节点(APPLICANT-申请人,DEPT_MANAGER-部门经理,FINANCE_DIRECTOR-财务总监,GENERAL_MANAGER-总经理)
    APPROVAL_STATUS VARCHAR(20) NOT NULL,                  -- 审批状态(PENDING-待审批,APPROVED-已通过,REJECTED-已拒绝,CANCELLED-已撤销)
    ATTACHMENT_PATH VARCHAR(500),                          -- 附件路径
    REMARKS VARCHAR(1000),                                 -- 备注
    CREATE_BY DECIMAL(20,0),                               -- 创建人ID
    CREATE_TIME TIMESTAMP,                                 -- 创建时间
    UPDATE_BY DECIMAL(20,0),                               -- 更新人ID
    UPDATE_TIME TIMESTAMP,                                 -- 更新时间
    DELETED INTEGER DEFAULT 0,                             -- 删除标记(0-未删除,1-已删除)
    TENANT_ID DECIMAL(20,0),                               -- 租户ID
    PRIMARY KEY (APPROVAL_ID)
);

-- 创建索引
CREATE INDEX IDX_FINANCING_APPROVAL_01 ON TBL_FINANCING_APPROVAL(FINANCING_TYPE, FINANCING_ID);
CREATE INDEX IDX_FINANCING_APPROVAL_02 ON TBL_FINANCING_APPROVAL(COMPANY_ID);
CREATE INDEX IDX_FINANCING_APPROVAL_03 ON TBL_FINANCING_APPROVAL(APPLICANT_ID);
CREATE INDEX IDX_FINANCING_APPROVAL_04 ON TBL_FINANCING_APPROVAL(APPROVAL_STATUS);
CREATE INDEX IDX_FINANCING_APPROVAL_05 ON TBL_FINANCING_APPROVAL(APPLICATION_TIME);
CREATE INDEX IDX_FINANCING_APPROVAL_06 ON TBL_FINANCING_APPROVAL(FINANCING_NO);
CREATE INDEX IDX_FINANCING_APPROVAL_07 ON TBL_FINANCING_APPROVAL(DELETED);

-- 表注释
COMMENT ON TABLE TBL_FINANCING_APPROVAL IS '融资审批表';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.APPROVAL_ID IS '审批ID';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.FINANCING_TYPE IS '融资类型(BANK_LOAN-银行贷款,BOND_ISSUANCE-债券发行,FINANCIAL_LEASE-融资租赁)';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.FINANCING_ID IS '融资ID';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.FINANCING_NO IS '融资编号';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.COMPANY_ID IS '公司ID';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.COMPANY_NAME IS '公司名称';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.FINANCING_AMOUNT IS '融资金额';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.CURRENCY_CODE IS '币种';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.FINANCING_TERM IS '融资期限';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.TERM_UNIT IS '期限单位(YEAR-年,MONTH-月,DAY-日)';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.INTEREST_RATE IS '利率(%)';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.REPAYMENT_METHOD IS '还款方式(EQUAL_INSTALLMENT-等额本息,EQUAL_PRINCIPAL-等额本金,BULLET-到期还本)';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.GUARANTEE_METHOD IS '担保方式(CREDIT-信用,MORTGAGE-抵押,PLEDGE-质押,GUARANTEE-保证)';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.FUND_PURPOSE IS '资金用途';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.APPLICANT_ID IS '申请人ID';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.APPLICANT_NAME IS '申请人姓名';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.APPLICATION_TIME IS '申请时间';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.CURRENT_APPROVAL_NODE IS '当前审批节点(APPLICANT-申请人,DEPT_MANAGER-部门经理,FINANCE_DIRECTOR-财务总监,GENERAL_MANAGER-总经理)';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.APPROVAL_STATUS IS '审批状态(PENDING-待审批,APPROVED-已通过,REJECTED-已拒绝,CANCELLED-已撤销)';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.ATTACHMENT_PATH IS '附件路径';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.REMARKS IS '备注';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.CREATE_BY IS '创建人ID';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.UPDATE_BY IS '更新人ID';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.DELETED IS '删除标记(0-未删除,1-已删除)';
COMMENT ON COLUMN TBL_FINANCING_APPROVAL.TENANT_ID IS '租户ID';
