-- =============================================
-- 异常处理表创建脚本
-- 表名: TBL_EXCEPTION_HANDLING
-- 描述: 存储资金归集、下拨、借贷等业务中的异常处理记录
-- 数据库: 达梦数据库 (DM Database)
-- 创建日期: 2026-01-20
-- =============================================

-- 删除已存在的表（如果需要）
-- DROP TABLE IF EXISTS TBL_EXCEPTION_HANDLING;

-- 创建异常处理表
CREATE TABLE TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    EXCEPTION_NO VARCHAR(50) NOT NULL,
    EXCEPTION_TYPE VARCHAR(50),
    EXCEPTION_LEVEL VARCHAR(20),
    SOURCE_TYPE VARCHAR(20),
    SOURCE_ID VARCHAR(64),
    SOURCE_NO VARCHAR(50),
    POOL_ID VARCHAR(64),
    COMPANY_ID VARCHAR(64),
    COMPANY_NAME VARCHAR(200),
    EXCEPTION_TITLE VARCHAR(200),
    EXCEPTION_DESC CLOB,
    EXCEPTION_TIME TIMESTAMP,
    EXCEPTION_STATUS VARCHAR(20),
    HANDLE_METHOD VARCHAR(20),
    HANDLE_TIME TIMESTAMP,
    HANDLE_BY VARCHAR(100),
    HANDLE_RESULT VARCHAR(500),
    RETRY_COUNT INTEGER DEFAULT 0,
    MAX_RETRY INTEGER DEFAULT 3,
    NEXT_RETRY_TIME TIMESTAMP,
    REMARK VARCHAR(1000),
    CREATE_BY VARCHAR(100),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(100),
    UPDATE_TIME TIMESTAMP,
    DEL_FLAG VARCHAR(10) DEFAULT '0'
);

-- 创建索引
CREATE INDEX IDX_EXCEPTION_NO ON TBL_EXCEPTION_HANDLING(EXCEPTION_NO);
CREATE INDEX IDX_EXCEPTION_TYPE ON TBL_EXCEPTION_HANDLING(EXCEPTION_TYPE);
CREATE INDEX IDX_EXCEPTION_LEVEL ON TBL_EXCEPTION_HANDLING(EXCEPTION_LEVEL);
CREATE INDEX IDX_EXCEPTION_STATUS ON TBL_EXCEPTION_HANDLING(EXCEPTION_STATUS);
CREATE INDEX IDX_SOURCE_TYPE ON TBL_EXCEPTION_HANDLING(SOURCE_TYPE);
CREATE INDEX IDX_COMPANY_ID ON TBL_EXCEPTION_HANDLING(COMPANY_ID);
CREATE INDEX IDX_EXCEPTION_TIME ON TBL_EXCEPTION_HANDLING(EXCEPTION_TIME);
CREATE INDEX IDX_CREATE_TIME ON TBL_EXCEPTION_HANDLING(CREATE_TIME);

-- 添加表注释
COMMENT ON TABLE TBL_EXCEPTION_HANDLING IS '异常处理表';

-- =============================================
-- 插入测试数据
-- =============================================

-- 测试数据1: 归集转账失败 - 紧急
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC001', 'EXP2026012001', 'TRANSFER_FAILED', 'URGENT',
    'COLLECTION', 'COL001', 'COL20260120001', 'POOL001',
    'COMP001', '华博集团有限公司', '资金归集转账失败', '从子公司A归集资金到主账户时，银行接口返回超时错误，转账失败',
    TO_DATE('2026-01-20 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'PENDING', 'RETRY',
    NULL, NULL, NULL,
    0, 3, TO_DATE('2026-01-20 10:35:00', 'YYYY-MM-DD HH24:MI:SS'),
    '需要重试转账操作', 'system', TO_DATE('2026-01-20 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据2: 归集超时 - 重要
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC002', 'EXP2026012002', 'TIMEOUT', 'IMPORTANT',
    'COLLECTION', 'COL002', 'COL20260120002', 'POOL001',
    'COMP002', '子公司A', '归集任务超时', '执行资金归集任务时，超过预设时间限制（30分钟）未完成',
    TO_DATE('2026-01-20 09:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HANDLING', 'MANUAL',
    TO_DATE('2026-01-20 09:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '正在人工检查原因',
    1, 3, NULL,
    '需要人工介入处理', 'system', TO_DATE('2026-01-20 09:15:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据3: 数据错误 - 普通 - 已解决
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC003', 'EXP2026011901', 'DATA_ERROR', 'NORMAL',
    'ALLOCATION', 'ALL001', 'ALL20260119001', 'POOL001',
    'COMP003', '子公司B', '下拨金额数据异常', '下拨金额超过账户可用余额，系统检测到数据异常',
    TO_DATE('2026-01-19 14:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'RESOLVED', 'ROLLBACK',
    TO_DATE('2026-01-19 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '已回滚操作并修正数据',
    0, 3, NULL,
    '已修复数据问题', 'system', TO_DATE('2026-01-19 14:20:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据4: 系统错误 - 紧急 - 处理中
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC004', 'EXP2026012003', 'SYSTEM_ERROR', 'URGENT',
    'LOAN', 'LOA001', 'LOA20260120001', 'POOL001',
    'COMP001', '华博集团有限公司', '系统内部错误', '内部借贷处理时系统发生未知错误，错误代码: ERR-5001',
    TO_DATE('2026-01-20 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'HANDLING', 'MANUAL',
    TO_DATE('2026-01-20 11:10:00', 'YYYY-MM-DD HH24:MI:SS'), 'system', '技术团队正在排查',
    0, 1, NULL,
    '需要技术支持', 'system', TO_DATE('2026-01-20 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据5: 转账失败 - 普通 - 已关闭
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC005', 'EXP2026011801', 'TRANSFER_FAILED', 'NORMAL',
    'ALLOCATION', 'ALL002', 'ALL20260118001', 'POOL001',
    'COMP002', '子公司A', '银行接口临时故障', '下拨资金时银行接口返回临时故障，后自动恢复',
    TO_DATE('2026-01-18 16:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'CLOSED', 'RETRY',
    TO_DATE('2026-01-18 16:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'system', '重试成功后自动关闭',
    2, 3, NULL,
    '已自动恢复', 'system', TO_DATE('2026-01-18 16:45:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据6: 超时异常 - 重要
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC006', 'EXP2026012004', 'TIMEOUT', 'IMPORTANT',
    'COLLECTION', 'COL003', 'COL20260120003', 'POOL001',
    'COMP003', '子公司B', '批量归集任务超时', '批量归集100个账户时超时，已完成80个，剩余20个未完成',
    TO_DATE('2026-01-20 13:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'PENDING', 'RETRY',
    NULL, NULL, NULL,
    0, 3, TO_DATE('2026-01-20 13:25:00', 'YYYY-MM-DD HH24:MI:SS'),
    '需要继续处理剩余账户', 'system', TO_DATE('2026-01-20 13:20:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据7: 数据校验错误 - 普通
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC007', 'EXP2026012005', 'DATA_ERROR', 'NORMAL',
    'LOAN', 'LOA002', 'LOA20260120002', 'POOL001',
    'COMP001', '华博集团有限公司', '利率数据异常', '借贷利率设置错误，超出允许范围',
    TO_DATE('2026-01-20 15:10:00', 'YYYY-MM-DD HH24:MI:SS'), 'PENDING', 'MANUAL',
    NULL, NULL, NULL,
    0, 0, NULL,
    '需要修正利率数据', 'system', TO_DATE('2026-01-20 15:10:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据8: 银行接口错误 - 紧急 - 已解决
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC008', 'EXP2026011701', 'TRANSFER_FAILED', 'URGENT',
    'COLLECTION', 'COL004', 'COL20260117001', 'POOL001',
    'COMP002', '子公司A', '银行系统维护', '银行接口返回系统维护中，无法完成转账',
    TO_DATE('2026-01-17 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'RESOLVED', 'RETRY',
    TO_DATE('2026-01-17 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '银行维护结束后重试成功',
    3, 3, NULL,
    '等待银行维护完成后处理', 'system', TO_DATE('2026-01-17 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据9: 网络超时 - 重要 - 处理中
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC009', 'EXP2026012006', 'TIMEOUT', 'IMPORTANT',
    'ALLOCATION', 'ALL003', 'ALL20260120003', 'POOL001',
    'COMP003', '子公司B', '网络连接超时', '资金下拨时网络连接超时，无法连接到银行系统',
    TO_DATE('2026-01-20 14:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'HANDLING', 'RETRY',
    TO_DATE('2026-01-20 14:55:00', 'YYYY-MM-DD HH24:MI:SS'), 'system', '正在重试连接',
    1, 3, TO_DATE('2026-01-20 15:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    '网络不稳定，持续重试中', 'system', TO_DATE('2026-01-20 14:50:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据10: 账户余额不足 - 普通 - 已解决
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC010', 'EXP2026011902', 'TRANSFER_FAILED', 'NORMAL',
    'ALLOCATION', 'ALL004', 'ALL20260119002', 'POOL001',
    'COMP001', '华博集团有限公司', '账户余额不足', '下拨资金时主账户余额不足，无法完成下拨',
    TO_DATE('2026-01-19 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'RESOLVED', 'MANUAL',
    TO_DATE('2026-01-19 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '已补充资金后重新下拨',
    0, 0, NULL,
    '需要资金调度', 'system', TO_DATE('2026-01-19 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据11: 权限验证失败 - 普通
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC011', 'EXP2026012007', 'SYSTEM_ERROR', 'NORMAL',
    'COLLECTION', 'COL005', 'COL20260120004', 'POOL001',
    'COMP002', '子公司A', 'UKey权限验证失败', 'UKey数字证书验证失败，无权限执行该操作',
    TO_DATE('2026-01-20 16:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'PENDING', 'MANUAL',
    NULL, NULL, NULL,
    0, 0, NULL,
    '需要重新配置UKey权限', 'system', TO_DATE('2026-01-20 16:20:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据12: 并发冲突 - 重要 - 已解决
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC012', 'EXP2026012008', 'DATA_ERROR', 'IMPORTANT',
    'LOAN', 'LOA003', 'LOA20260120003', 'POOL001',
    'COMP001', '华博集团有限公司', '并发操作冲突', '多用户同时操作同一笔借贷业务导致数据冲突',
    TO_DATE('2026-01-20 09:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'RESOLVED', 'IGNORE',
    TO_DATE('2026-01-20 09:55:00', 'YYYY-MM-DD HH24:MI:SS'), 'system', '已忽略冲突操作',
    0, 0, NULL,
    '并发控制', 'system', TO_DATE('2026-01-20 09:50:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据13: 批量处理部分失败 - 重要
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC013', 'EXP2026012009', 'TRANSFER_FAILED', 'IMPORTANT',
    'COLLECTION', 'COL006', 'COL20260120005', 'POOL001',
    'COMP003', '子公司B', '批量归集部分失败', '批量归集50个账户，其中5个失败，45个成功',
    TO_DATE('2026-01-20 17:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'PENDING', 'RETRY',
    NULL, NULL, NULL,
    0, 3, TO_DATE('2026-01-20 17:35:00', 'YYYY-MM-DD HH24:MI:SS'),
    '需要重试失败的5个账户', 'system', TO_DATE('2026-01-20 17:30:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据14: 系统配置错误 - 紧急
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC014', 'EXP2026012010', 'SYSTEM_ERROR', 'URGENT',
    'ALLOCATION', 'ALL005', 'ALL20260120004', 'POOL001',
    'COMP001', '华博集团有限公司', '资金池配置错误', '资金池配置信息错误，导致无法执行下拨操作',
    TO_DATE('2026-01-20 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'HANDLING', 'MANUAL',
    TO_DATE('2026-01-20 18:10:00', 'YYYY-MM-DD HH24:MI:SS'), 'admin', '正在修正配置',
    0, 0, NULL,
    '需要重新配置资金池参数', 'system', TO_DATE('2026-01-20 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- 测试数据15: 数据同步失败 - 普通
INSERT INTO TBL_EXCEPTION_HANDLING (
    EXCEPTION_ID, EXCEPTION_NO, EXCEPTION_TYPE, EXCEPTION_LEVEL,
    SOURCE_TYPE, SOURCE_ID, SOURCE_NO, POOL_ID,
    COMPANY_ID, COMPANY_NAME, EXCEPTION_TITLE, EXCEPTION_DESC,
    EXCEPTION_TIME, EXCEPTION_STATUS, HANDLE_METHOD,
    HANDLE_TIME, HANDLE_BY, HANDLE_RESULT,
    RETRY_COUNT, MAX_RETRY, NEXT_RETRY_TIME,
    REMARK, CREATE_BY, CREATE_TIME, DEL_FLAG
) VALUES (
    'EXC015', 'EXP2026012011', 'DATA_ERROR', 'NORMAL',
    'COLLECTION', 'COL007', 'COL20260120006', 'POOL001',
    'COMP002', '子公司A', '银行对账单同步失败', '从银行系统获取对账单数据时失败，数据同步中断',
    TO_DATE('2026-01-20 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'PENDING', 'RETRY',
    NULL, NULL, NULL,
    0, 5, TO_DATE('2026-01-20 19:05:00', 'YYYY-MM-DD HH24:MI:SS'),
    '稍后重试同步', 'system', TO_DATE('2026-01-20 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), '0'
);

-- =============================================
-- 验证数据
-- =============================================
-- 查询插入的数据
-- SELECT EXCEPTION_NO, EXCEPTION_TITLE, EXCEPTION_TYPE, EXCEPTION_LEVEL,
--        EXCEPTION_STATUS, COMPANY_NAME, EXCEPTION_TIME
-- FROM TBL_EXCEPTION_HANDLING
-- ORDER BY EXCEPTION_TIME DESC;

-- 查看异常统计
-- SELECT EXCEPTION_TYPE, EXCEPTION_STATUS, COUNT(*) as CNT
-- FROM TBL_EXCEPTION_HANDLING
-- GROUP BY EXCEPTION_TYPE, EXCEPTION_STATUS;

-- 查看待处理异常
-- SELECT EXCEPTION_NO, EXCEPTION_TITLE, EXCEPTION_LEVEL, EXCEPTION_TIME
-- FROM TBL_EXCEPTION_HANDLING
-- WHERE EXCEPTION_STATUS = 'PENDING'
-- ORDER BY EXCEPTION_TIME DESC;

COMMIT;

-- =============================================
-- 说明
-- =============================================
-- 异常类型 (EXCEPTION_TYPE):
--   TRANSFER_FAILED - 转账失败
--   TIMEOUT - 超时
--   DATA_ERROR - 数据错误
--   SYSTEM_ERROR - 系统错误
--
-- 异常级别 (EXCEPTION_LEVEL):
--   NORMAL - 普通
--   IMPORTANT - 重要
--   URGENT - 紧急
--
-- 来源类型 (SOURCE_TYPE):
--   COLLECTION - 归集
--   ALLOCATION - 下拨
--   LOAN - 借贷
--
-- 异常状态 (EXCEPTION_STATUS):
--   PENDING - 待处理
--   HANDLING - 处理中
--   RESOLVED - 已解决
--   CLOSED - 已关闭
--
-- 处理方式 (HANDLE_METHOD):
--   RETRY - 重试
--   MANUAL - 人工处理
--   IGNORE - 忽略
--   ROLLBACK - 回滚
--
-- 删除标志 (DEL_FLAG):
--   '0' - 正常
--   '1' - 已删除
-- =============================================
