-- 衍生品预警表
-- 兼容达梦数据库
-- Author: AI Developer
-- Date: 2026-01-21

-- 删除表(如果存在)
DROP TABLE IF EXISTS TBL_DERIVATIVES_ALERT;

-- 创建预警表
CREATE TABLE TBL_DERIVATIVES_ALERT (
    ALERT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ALERT_TYPE VARCHAR(50) NOT NULL,
    ALERT_LEVEL VARCHAR(20) NOT NULL,
    ALERT_TITLE VARCHAR(200),
    ALERT_CONTENT VARCHAR(1000),
    TRANSACTION_ID BIGINT,
    TRANSACTION_TYPE VARCHAR(50),
    ALERT_THRESHOLD DECIMAL(20, 4),
    CURRENT_VALUE DECIMAL(20, 4),
    ALERT_STATUS VARCHAR(20) DEFAULT 'TRIGGERED',
    HANDLER_ID BIGINT,
    HANDLER_NAME VARCHAR(100),
    HANDLE_TIME TIMESTAMP,
    HANDLE_REMARK VARCHAR(500),
    DELETE_FLAG INTEGER DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATED_BY BIGINT,
    CREATED_BY_NAME VARCHAR(100),
    UPDATED_BY BIGINT,
    UPDATED_BY_NAME VARCHAR(100),
    ORG_ID BIGINT NOT NULL,
    DEL_FLAG VARCHAR(1) DEFAULT '0',
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100)
);

-- 添加注释
COMMENT ON TABLE TBL_DERIVATIVES_ALERT IS '衍生品预警表';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_ID IS '预警ID';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_TYPE IS '预警类型(RISK_LIMIT-风险限额, VAR-风险价值, MARGIN-保证金, MARKET-市场变化)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_LEVEL IS '预警级别(LOW-低, MEDIUM-中, HIGH-高, CRITICAL-严重)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_TITLE IS '预警标题';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_CONTENT IS '预警内容';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.TRANSACTION_ID IS '关联交易ID';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.TRANSACTION_TYPE IS '交易类型(FORWARD-远期, FUTURES-期货, OPTION-期权, SWAP-互换)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_THRESHOLD IS '预警阈值';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.CURRENT_VALUE IS '当前值';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ALERT_STATUS IS '预警状态(TRIGGERED-已触发, PROCESSED-已处理, IGNORED-已忽略)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.HANDLER_ID IS '处理人ID';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.HANDLER_NAME IS '处理人姓名';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.HANDLE_TIME IS '处理时间';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.HANDLE_REMARK IS '处理说明';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.DELETE_FLAG IS '删除标志(0-正常, 1-删除)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.CREATED_BY IS '创建人ID';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.CREATED_BY_NAME IS '创建人姓名';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.UPDATED_BY IS '更新人ID';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.UPDATED_BY_NAME IS '更新人姓名';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.ORG_ID IS '组织ID';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.DEL_FLAG IS '删除标识(0-正常, 1-删除)';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_DERIVATIVES_ALERT.UPDATE_BY IS '更新人';

-- 创建索引
CREATE INDEX IDX_ALERT_TYPE ON TBL_DERIVATIVES_ALERT(ALERT_TYPE);
CREATE INDEX IDX_ALERT_LEVEL ON TBL_DERIVATIVES_ALERT(ALERT_LEVEL);
CREATE INDEX IDX_ALERT_STATUS ON TBL_DERIVATIVES_ALERT(ALERT_STATUS);
CREATE INDEX IDX_ALERT_TRANSACTION ON TBL_DERIVATIVES_ALERT(TRANSACTION_ID);
CREATE INDEX IDX_ALERT_ORG ON TBL_DERIVATIVES_ALERT(ORG_ID);
CREATE INDEX IDX_ALERT_CREATE_TIME ON TBL_DERIVATIVES_ALERT(CREATE_TIME);

-- 插入测试数据(10条)
INSERT INTO TBL_DERIVATIVES_ALERT (
    ALERT_TYPE, ALERT_LEVEL, ALERT_TITLE, ALERT_CONTENT,
    TRANSACTION_ID, TRANSACTION_TYPE, ALERT_THRESHOLD, CURRENT_VALUE,
    ALERT_STATUS, ORG_ID, CREATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    'RISK_LIMIT', 'HIGH', '风险限额预警', '远期外汇交易FWD-2026-001风险敞口超过限额',
    1, 'FORWARD', 1000000.0000, 1500000.0000,
    'TRIGGERED', 1, '2026-01-21 10:00:00', '1', '1', '0'
);

INSERT INTO TBL_DERIVATIVES_ALERT (
    ALERT_TYPE, ALERT_LEVEL, ALERT_TITLE, ALERT_CONTENT,
    TRANSACTION_ID, TRANSACTION_TYPE, ALERT_THRESHOLD, CURRENT_VALUE,
    ALERT_STATUS, ORG_ID, CREATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    'VAR', 'MEDIUM', 'VaR超限预警', '期货组合VaR值超过警戒线',
    2, 'FUTURES', 500000.0000, 650000.0000,
    'TRIGGERED', 1, '2026-01-21 11:00:00', '1', '1', '0'
);

INSERT INTO TBL_DERIVATIVES_ALERT (
    ALERT_TYPE, ALERT_LEVEL, ALERT_TITLE, ALERT_CONTENT,
    TRANSACTION_ID, TRANSACTION_TYPE, ALERT_THRESHOLD, CURRENT_VALUE,
    ALERT_STATUS, ORG_ID, CREATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    'MARGIN', 'LOW', '保证金预警', '期权交易保证金不足',
    3, 'OPTION', 80000.0000, 75000.0000,
    'TRIGGERED', 1, '2026-01-21 12:00:00', '1', '1', '0'
);

INSERT INTO TBL_DERIVATIVES_ALERT (
    ALERT_TYPE, ALERT_LEVEL, ALERT_TITLE, ALERT_CONTENT,
    TRANSACTION_ID, TRANSACTION_TYPE, ALERT_THRESHOLD, CURRENT_VALUE,
    ALERT_STATUS, ORG_ID, CREATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    'MARKET', 'CRITICAL', '市场异常波动', '美元/人民币汇率波动超过2%',
    NULL, 'FX', 2.0000, 2.5000,
    'PROCESSED', 1, '2026-01-21 13:00:00', '1', '1', '0'
);

INSERT INTO TBL_DERIVATIVES_ALERT (
    ALERT_TYPE, ALERT_LEVEL, ALERT_TITLE, ALERT_CONTENT,
    TRANSACTION_ID, TRANSACTION_TYPE, ALERT_THRESHOLD, CURRENT_VALUE,
    ALERT_STATUS, ORG_ID, CREATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    'RISK_LIMIT', 'MEDIUM', '集中度预警', '单一交易对手敞口过大',
    4, 'SWAP', 5000000.0000, 6200000.0000,
    'TRIGGERED', 1, '2026-01-21 14:00:00', '1', '1', '0'
);

INSERT INTO TBL_DERIVATIVES_ALERT (
    ALERT_TYPE, ALERT_LEVEL, ALERT_TITLE, ALERT_CONTENT,
    TRANSACTION_ID, TRANSACTION_TYPE, ALERT_THRESHOLD, CURRENT_VALUE,
    ALERT_STATUS, ORG_ID, CREATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    'VAR', 'HIGH', 'VaR突破预警', '投资组合VaR达到历史新高',
    5, 'FUTURES', 800000.0000, 950000.0000,
    'IGNORED', 1, '2026-01-21 15:00:00', '1', '1', '0'
);

INSERT INTO TBL_DERIVATIVES_ALERT (
    ALERT_TYPE, ALERT_LEVEL, ALERT_TITLE, ALERT_CONTENT,
    TRANSACTION_ID, TRANSACTION_TYPE, ALERT_THRESHOLD, CURRENT_VALUE,
    ALERT_STATUS, ORG_ID, CREATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    'MARGIN', 'HIGH', '补充保证金通知', '期货账户需追加保证金',
    6, 'FUTURES', 100000.0000, 85000.0000,
    'TRIGGERED', 1, '2026-01-21 16:00:00', '1', '1', '0'
);

INSERT INTO TBL_DERIVATIVES_ALERT (
    ALERT_TYPE, ALERT_LEVEL, ALERT_TITLE, ALERT_CONTENT,
    TRANSACTION_ID, TRANSACTION_TYPE, ALERT_THRESHOLD, CURRENT_VALUE,
    ALERT_STATUS, ORG_ID, CREATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    'MARKET', 'MEDIUM', '利率波动预警', 'SHIBOR利率波动超过50BP',
    NULL, 'INTEREST_RATE', 0.5000, 0.6500,
    'TRIGGERED', 1, '2026-01-21 17:00:00', '1', '1', '0'
);

INSERT INTO TBL_DERIVATIVES_ALERT (
    ALERT_TYPE, ALERT_LEVEL, ALERT_TITLE, ALERT_CONTENT,
    TRANSACTION_ID, TRANSACTION_TYPE, ALERT_THRESHOLD, CURRENT_VALUE,
    ALERT_STATUS, ORG_ID, CREATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    'RISK_LIMIT', 'LOW', '止损预警', '期权组合接近止损线',
    7, 'OPTION', 200000.0000, 180000.0000,
    'PROCESSED', 1, '2026-01-21 18:00:00', '1', '1', '0'
);

INSERT INTO TBL_DERIVATIVES_ALERT (
    ALERT_TYPE, ALERT_LEVEL, ALERT_TITLE, ALERT_CONTENT,
    TRANSACTION_ID, TRANSACTION_TYPE, ALERT_THRESHOLD, CURRENT_VALUE,
    ALERT_STATUS, ORG_ID, CREATE_TIME, CREATE_BY, UPDATE_BY, DEL_FLAG
) VALUES (
    'VAR', 'CRITICAL', '极端风险预警', '压力测试下VaR超过限额',
    8, 'FORWARD', 1200000.0000, 1500000.0000,
    'TRIGGERED', 1, '2026-01-21 19:00:00', '1', '1', '0'
);

COMMIT;

-- 查询验证数据
SELECT COUNT(*) AS TOTAL_RECORDS FROM TBL_DERIVATIVES_ALERT;
SELECT ALERT_ID, ALERT_TYPE, ALERT_LEVEL, ALERT_TITLE, ALERT_STATUS, ORG_ID
FROM TBL_DERIVATIVES_ALERT
ORDER BY ALERT_ID;
