-- =============================================================
-- 表名: TBL_GT_DATA_SOURCE
-- 描述: 全球司库-数据源配置表
-- 数据库: 达梦数据库兼容
-- 作者: Claude Code
-- 日期: 2025-01-21
-- =============================================================

-- 删除表(如果存在)
DROP TABLE IF EXISTS TBL_GT_DATA_SOURCE;

-- 创建表
CREATE TABLE TBL_GT_DATA_SOURCE (
    DATA_SOURCE_ID BIGINT IDENTITY(1,1) NOT NULL,
    DATA_SOURCE_CODE VARCHAR(50) NOT NULL,
    DATA_SOURCE_NAME VARCHAR(200) NOT NULL,
    DATA_SOURCE_TYPE VARCHAR(50) NOT NULL,
    ENVIRONMENT VARCHAR(20),
    CONNECTION_URL VARCHAR(500),
    HOST VARCHAR(100),
    PORT INT,
    DATABASE_NAME VARCHAR(100),
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(200),
    DRIVER_CLASS VARCHAR(200),
    CONNECTION_STATUS VARCHAR(20),
    IS_ENABLED INT DEFAULT 1 NOT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    LAST_TEST_TIME TIMESTAMP,
    DESCRIPTION VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY VARCHAR(50),
    UPDATE_BY VARCHAR(50)
);

-- 添加表注释
COMMENT ON TABLE TBL_GT_DATA_SOURCE IS '全球司库-数据源配置表';

-- 添加字段注释
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.DATA_SOURCE_ID IS '数据源ID';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.DATA_SOURCE_CODE IS '数据源编码';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.DATA_SOURCE_NAME IS '数据源名称';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.DATA_SOURCE_TYPE IS '数据源类型(MYSQL/ORACLE/DAMENG/POSTGRESQL/API/FILE/REDIS)';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.ENVIRONMENT IS '环境类型(DEV-开发环境/TEST-测试环境/PROD-生产环境)';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.CONNECTION_URL IS '连接地址';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.HOST IS '主机地址';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.PORT IS '端口号';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.DATABASE_NAME IS '数据库名';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.USERNAME IS '用户名';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.PASSWORD IS '密码(加密存储)';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.DRIVER_CLASS IS '驱动类名';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.CONNECTION_STATUS IS '连接状态(NORMAL-正常/ERROR-异常/UNTESTED-未测试)';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.IS_ENABLED IS '是否启用(1-启用/0-停用)';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.STATUS IS '状态(1-正常/0-删除)';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.LAST_TEST_TIME IS '最后测试时间';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.DESCRIPTION IS '描述';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_GT_DATA_SOURCE.UPDATE_BY IS '更新人';

-- 创建索引
CREATE UNIQUE INDEX IDX_DATA_SOURCE_CODE ON TBL_GT_DATA_SOURCE(DATA_SOURCE_CODE);
CREATE INDEX IDX_DATA_SOURCE_TYPE ON TBL_GT_DATA_SOURCE(DATA_SOURCE_TYPE);
CREATE INDEX IDX_DATA_ENV ON TBL_GT_DATA_SOURCE(ENVIRONMENT);
CREATE INDEX IDX_DATA_CONNECTION_STATUS ON TBL_GT_DATA_SOURCE(CONNECTION_STATUS);
CREATE INDEX IDX_DATA_ENABLED ON TBL_GT_DATA_SOURCE(STATUS, IS_ENABLED);

-- 插入测试数据
INSERT INTO TBL_GT_DATA_SOURCE (DATA_SOURCE_CODE, DATA_SOURCE_NAME, DATA_SOURCE_TYPE, ENVIRONMENT, CONNECTION_URL, HOST, PORT, DATABASE_NAME, USERNAME, CONNECTION_STATUS, IS_ENABLED, STATUS, DESCRIPTION, CREATE_BY, UPDATE_BY) VALUES
('DS_MYSQL_MAIN', '主数据库MySQL', 'MYSQL', 'PROD', 'jdbc:mysql://192.0.2.200:3306/hbyun_treasury', '192.0.2.200', 3306, 'hbyun_treasury', 'treasury_user', 'NORMAL', 1, 1, '财资系统主数据库连接', 'admin', 'admin'),
('DS_DAMENG_BACKUP', '备份数据库达梦', 'DAMENG', 'PROD', 'jdbc:dm://192.0.2.200:5236/HBYUN_BACKUP', '192.0.2.200', 5236, 'HBYUN_BACKUP', 'backup_user', 'NORMAL', 1, 1, '财资系统备份数据库连接', 'admin', 'admin'),
('DS_API_BANK', '银行接口API', 'API', 'PROD', 'https://api.bank.com/treasury/v1', NULL, NULL, NULL, 'api_user', 'ERROR', 0, 1, '银行系统API接口连接', 'admin', 'admin'),
('DS_REDIS_CACHE', 'Redis缓存', 'REDIS', 'PROD', 'redis://192.0.2.200:6379', '192.0.2.200', 6379, NULL, 'cache_user', 'NORMAL', 1, 1, 'Redis缓存服务', 'admin', 'admin');

COMMIT;
