-- ============================================
-- 印鉴使用记录表 - 达梦数据库建表脚本
-- 兼容达梦数据库 DM8
-- 创建日期: 2025-12-25
-- ============================================

-- 印鉴使用记录表
CREATE TABLE TBL_SEAL_USAGE_RECORD (
    RECORD_ID VARCHAR2(50) NOT NULL,
    SEAL_ID VARCHAR2(50) NOT NULL,
    SEAL_NAME VARCHAR2(200),
    SEAL_CODE VARCHAR2(50),
    USAGE_TYPE VARCHAR2(50),
    BUSINESS_TYPE VARCHAR2(50),
    USAGE_STATUS VARCHAR2(20),
    OPERATOR_ID VARCHAR2(50),
    OPERATOR_NAME VARCHAR2(100),
    USAGE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    APPROVER_ID VARCHAR2(50),
    APPROVER_NAME VARCHAR2(100),
    APPROVE_TIME TIMESTAMP,
    DESCRIPTION VARCHAR2(1000),
    REMARK VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TBL_SEAL_USAGE_RECORD PRIMARY KEY (RECORD_ID)
);

-- 表注释
COMMENT ON TABLE TBL_SEAL_USAGE_RECORD IS '印鉴使用记录表';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.RECORD_ID IS '记录ID,主键';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_ID IS '印鉴ID,关联TC_SEAL_ARCHIVE_V2表';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_NAME IS '印鉴名称,冗余字段';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.SEAL_CODE IS '印鉴编码,冗余字段';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_TYPE IS '使用类型:单次盖章、多次盖章等';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.BUSINESS_TYPE IS '业务类型:合同、财务、行政等';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_STATUS IS '使用状态:SUCCESS-成功,FAILED-失败,PENDING-待审批';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.OPERATOR_ID IS '操作人ID';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.OPERATOR_NAME IS '操作人姓名';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.USAGE_TIME IS '使用时间';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.APPROVER_ID IS '审批人ID';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.APPROVER_NAME IS '审批人姓名';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.APPROVE_TIME IS '审批时间';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.DESCRIPTION IS '使用说明';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.REMARK IS '备注';
COMMENT ON COLUMN TBL_SEAL_USAGE_RECORD.CREATE_TIME IS '创建时间';

-- 创建索引
CREATE INDEX IDX_SEAL_USAGE_SEAL_ID ON TBL_SEAL_USAGE_RECORD(SEAL_ID);
CREATE INDEX IDX_SEAL_USAGE_TIME ON TBL_SEAL_USAGE_RECORD(USAGE_TIME);
CREATE INDEX IDX_SEAL_USAGE_OPERATOR ON TBL_SEAL_USAGE_RECORD(OPERATOR_NAME);
CREATE INDEX IDX_SEAL_USAGE_STATUS ON TBL_SEAL_USAGE_RECORD(USAGE_STATUS);

-- 插入测试数据
INSERT INTO TBL_SEAL_USAGE_RECORD (
    RECORD_ID, SEAL_ID, SEAL_NAME, SEAL_CODE,
    USAGE_TYPE, BUSINESS_TYPE, USAGE_STATUS,
    OPERATOR_ID, OPERATOR_NAME, USAGE_TIME, DESCRIPTION
)
SELECT
    'UR001', '1001', '华博云科技有限公司公章', 'SEAL001',
    '单次盖章', '合同签署', 'SUCCESS',
    'U001', '张三', TO_TIMESTAMP('2025-12-25 10:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    '签订销售合同'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TBL_SEAL_USAGE_RECORD WHERE RECORD_ID = 'UR001');

INSERT INTO TBL_SEAL_USAGE_RECORD (
    RECORD_ID, SEAL_ID, SEAL_NAME, SEAL_CODE,
    USAGE_TYPE, BUSINESS_TYPE, USAGE_STATUS,
    OPERATOR_ID, OPERATOR_NAME, USAGE_TIME, DESCRIPTION
)
SELECT
    'UR002', '1002', '华博云财务专用章', 'SEAL002',
    '单次盖章', '财务报销', 'SUCCESS',
    'U002', '李四', TO_TIMESTAMP('2025-12-25 11:15:00', 'YYYY-MM-DD HH24:MI:SS'),
    '费用报销单盖章'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TBL_SEAL_USAGE_RECORD WHERE RECORD_ID = 'UR002');

INSERT INTO TBL_SEAL_USAGE_RECORD (
    RECORD_ID, SEAL_ID, SEAL_NAME, SEAL_CODE,
    USAGE_TYPE, BUSINESS_TYPE, USAGE_STATUS,
    OPERATOR_ID, OPERATOR_NAME, USAGE_TIME, DESCRIPTION
)
SELECT
    'UR003', '1001', '华博云科技有限公司公章', 'SEAL001',
    '单次盖章', '行政管理', 'SUCCESS',
    'U003', '王五', TO_TIMESTAMP('2025-12-25 14:20:00', 'YYYY-MM-DD HH24:MI:SS'),
    '人事任命文件盖章'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TBL_SEAL_USAGE_RECORD WHERE RECORD_ID = 'UR003');

COMMIT;

-- 验证数据
SELECT '印鉴使用记录数据统计:' AS 统计类型, COUNT(*) AS 记录数 FROM TBL_SEAL_USAGE_RECORD;
