-- 掉期交易表
-- 兼容达梦数据库(MySQL/达梦/Oracle通用语法)
-- Author: AI Developer
-- Date: 2026-01-21

-- 删除表(如果存在)
DROP TABLE IF EXISTS TBL_SWAP_TRANSACTION;

-- 创建掉期交易表
CREATE TABLE TBL_SWAP_TRANSACTION (
    TRANSACTION_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CONTRACT_CODE VARCHAR(50) NOT NULL,
    SWAP_TYPE VARCHAR(50) NOT NULL,
    NOTIONAL_AMOUNT DECIMAL(20, 4),
    CURRENCY VARCHAR(10),
    EFFECTIVE_DATE DATE,
    MATURITY_DATE DATE,
    FIXED_RATE DECIMAL(10, 6),
    FLOATING_RATE_BASIS VARCHAR(50),
    SPREAD DECIMAL(10, 4),
    PAYMENT_FREQUENCY VARCHAR(50),
    DAY_COUNT_BASIS VARCHAR(50),
    PAY_DIRECTION VARCHAR(50),
    PAY_CURRENCY VARCHAR(10),
    RECEIVE_CURRENCY VARCHAR(10),
    PAY_NOTIONAL DECIMAL(20, 4),
    RECEIVE_NOTIONAL DECIMAL(20, 4),
    INITIAL_EXCHANGE_RATE DECIMAL(20, 8),
    EXCHANGE_PRINCIPAL INTEGER DEFAULT 0,
    CURRENT_VALUE DECIMAL(20, 4),
    NEXT_PAYMENT_DATE DATE,
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    COUNTERPARTY VARCHAR(200),
    COUNTERPARTY_RATING VARCHAR(10),
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY BIGINT,
    UPDATE_TIME TIMESTAMP,
    UPDATE_BY BIGINT,
    DEL_FLAG INTEGER DEFAULT 0,
    ORG_ID BIGINT
);

-- 添加注释
COMMENT ON TABLE TBL_SWAP_TRANSACTION IS '掉期交易表';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.TRANSACTION_ID IS '主键ID';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.CONTRACT_CODE IS '合约编号';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.SWAP_TYPE IS '掉期类型(INTEREST_RATE-利率掉期, CURRENCY-货币掉期, COMMODITY-商品掉期, CDS-信用违约掉期)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.NOTIONAL_AMOUNT IS '名义本金';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.CURRENCY IS '币种';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.EFFECTIVE_DATE IS '生效日期';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.MATURITY_DATE IS '到期日期';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.FIXED_RATE IS '固定利率';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.FLOATING_RATE_BASIS IS '浮动利率基准(SHIBOR, LPR, LIBOR, SOFR)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.SPREAD IS '利差';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.PAYMENT_FREQUENCY IS '支付频率(MONTHLY, QUARTERLY, SEMI_ANNUAL, ANNUAL)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.DAY_COUNT_BASIS IS '计息基准(ACT_360, ACT_365, 30_360)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.PAY_DIRECTION IS '支付方向(PAY_FIXED-支付固定/收取浮动, RECEIVE_FIXED-收取固定/支付浮动)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.PAY_CURRENCY IS '支付币种(货币掉期专用)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.RECEIVE_CURRENCY IS '收取币种(货币掉期专用)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.PAY_NOTIONAL IS '支付本金(货币掉期专用)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.RECEIVE_NOTIONAL IS '收取本金(货币掉期专用)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.INITIAL_EXCHANGE_RATE IS '初始汇率(货币掉期专用)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.EXCHANGE_PRINCIPAL IS '是否交换本金(货币掉期专用)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.CURRENT_VALUE IS '当前估值';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.NEXT_PAYMENT_DATE IS '下次支付日期';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.STATUS IS '状态(PENDING-待生效, ACTIVE-生效中, TERMINATED-已终止, MATURED-已到期, CANCELLED-已取消)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.COUNTERPARTY IS '交易对手';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.COUNTERPARTY_RATING IS '对手评级';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.REMARK IS '备注';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.DEL_FLAG IS '删除标志(0-正常, 1-删除)';
COMMENT ON COLUMN TBL_SWAP_TRANSACTION.ORG_ID IS '机构ID';

-- 创建索引
CREATE INDEX IDX_SWAP_CONTRACT_CODE ON TBL_SWAP_TRANSACTION(CONTRACT_CODE);
CREATE INDEX IDX_SWAP_TYPE ON TBL_SWAP_TRANSACTION(SWAP_TYPE);
CREATE INDEX IDX_SWAP_STATUS ON TBL_SWAP_TRANSACTION(STATUS);
CREATE INDEX IDX_SWAP_CURRENCY ON TBL_SWAP_TRANSACTION(CURRENCY);
CREATE INDEX IDX_SWAP_MATURITY_DATE ON TBL_SWAP_TRANSACTION(MATURITY_DATE);
CREATE INDEX IDX_SWAP_CREATE_TIME ON TBL_SWAP_TRANSACTION(CREATE_TIME);

-- 创建序列(达梦/Oracle)
-- CREATE SEQUENCE SEQ_SWAP_TRANSACTION START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- 插入测试数据(10条)
-- 利率掉期数据
INSERT INTO TBL_SWAP_TRANSACTION (
    CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY,
    EFFECTIVE_DATE, MATURITY_DATE, FIXED_RATE, FLOATING_RATE_BASIS,
    SPREAD, PAYMENT_FREQUENCY, DAY_COUNT_BASIS, PAY_DIRECTION,
    CURRENT_VALUE, NEXT_PAYMENT_DATE, STATUS, COUNTERPARTY,
    COUNTERPARTY_RATING, REMARK, CREATE_BY, UPDATE_BY, ORG_ID
) VALUES (
    'SWAP-2026-001', 'INTEREST_RATE', 10000000.00, 'CNY',
    '2026-01-01', '2027-12-31', 3.50, 'LPR',
    0.50, 'QUARTERLY', 'ACT_360', 'PAY_FIXED',
    150000.00, '2026-04-01', 'ACTIVE', '中国银行', 'AAA', '5年期LPR利率掉期',
    1, 1, 1
);

INSERT INTO TBL_SWAP_TRANSACTION (
    CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY,
    EFFECTIVE_DATE, MATURITY_DATE, FIXED_RATE, FLOATING_RATE_BASIS,
    SPREAD, PAYMENT_FREQUENCY, DAY_COUNT_BASIS, PAY_DIRECTION,
    CURRENT_VALUE, NEXT_PAYMENT_DATE, STATUS, COUNTERPARTY,
    COUNTERPARTY_RATING, REMARK, CREATE_BY, UPDATE_BY, ORG_ID
) VALUES (
    'SWAP-2026-002', 'INTEREST_RATE', 50000000.00, 'CNY',
    '2026-02-01', '2031-02-01', 4.20, 'SHIBOR',
    0.30, 'QUARTERLY', 'ACT_365', 'RECEIVE_FIXED',
    -850000.00, '2026-05-01', 'ACTIVE', '工商银行', 'AAA', '10年期利率掉期-收取固定',
    1, 1, 1
);

INSERT INTO TBL_SWAP_TRANSACTION (
    CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY,
    EFFECTIVE_DATE, MATURITY_DATE, FIXED_RATE, FLOATING_RATE_BASIS,
    SPREAD, PAYMENT_FREQUENCY, DAY_COUNT_BASIS, PAY_DIRECTION,
    CURRENT_VALUE, NEXT_PAYMENT_DATE, STATUS, COUNTERPARTY,
    COUNTERPARTY_RATING, REMARK, CREATE_BY, UPDATE_BY, ORG_ID
) VALUES (
    'SWAP-2026-003', 'INTEREST_RATE', 30000000.00, 'USD',
    '2026-03-15', '2029-03-15', 2.80, 'LIBOR',
    0.80, 'QUARTERLY', 'ACT_360', 'PAY_FIXED',
    420000.00, '2026-06-15', 'ACTIVE', '建设银行', 'AA+', '3年期USD LIBOR掉期',
    1, 1, 1
);

INSERT INTO TBL_SWAP_TRANSACTION (
    CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY,
    EFFECTIVE_DATE, MATURITY_DATE, FIXED_RATE, FLOATING_RATE_BASIS,
    SPREAD, PAYMENT_FREQUENCY, DAY_COUNT_BASIS, PAY_DIRECTION,
    CURRENT_VALUE, NEXT_PAYMENT_DATE, STATUS, COUNTERPARTY,
    COUNTERPARTY_RATING, REMARK, CREATE_BY, UPDATE_BY, ORG_ID
) VALUES (
    'SWAP-2026-004', 'INTEREST_RATE', 80000000.00, 'EUR',
    '2026-01-20', '2030-01-20', 3.10, 'EURIBOR',
    0.60, 'SEMI_ANNUAL', 'ACT_360', 'PAY_FIXED',
    920000.00, '2026-07-20', 'ACTIVE', '汇丰银行', 'AAA', '5年期EUR利率掉期',
    1, 1, 1
);

INSERT INTO TBL_SWAP_TRANSACTION (
    CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY,
    EFFECTIVE_DATE, MATURITY_DATE, FIXED_RATE, FLOATING_RATE_BASIS,
    SPREAD, PAYMENT_FREQUENCY, DAY_COUNT_BASIS, PAY_DIRECTION,
    CURRENT_VALUE, NEXT_PAYMENT_DATE, STATUS, COUNTERPARTY,
    COUNTERPARTY_RATING, REMARK, CREATE_BY, UPDATE_BY, ORG_ID
) VALUES (
    'SWAP-2026-005', 'INTEREST_RATE', 20000000.00, 'CNY',
    '2026-04-01', '2028-04-01', 3.75, 'LPR',
    0.45, 'MONTHLY', 'ACT_360', 'RECEIVE_FIXED',
    -180000.00, '2026-05-01', 'PENDING', '农业银行', 'AA+', '2年期LPR月度支付掉期',
    1, 1, 1
);

-- 货币掉期数据
INSERT INTO TBL_SWAP_TRANSACTION (
    CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY,
    EFFECTIVE_DATE, MATURITY_DATE, PAYMENT_FREQUENCY,
    PAY_CURRENCY, RECEIVE_CURRENCY, PAY_NOTIONAL, RECEIVE_NOTIONAL,
    INITIAL_EXCHANGE_RATE, EXCHANGE_PRINCIPAL, CURRENT_VALUE,
    NEXT_PAYMENT_DATE, STATUS, COUNTERPARTY, COUNTERPARTY_RATING,
    REMARK, CREATE_BY, UPDATE_BY, ORG_ID
) VALUES (
    'SWAP-2026-006', 'CURRENCY', 5000000.00, 'USD',
    '2026-01-15', '2028-01-15', 'SEMI_ANNUAL',
    'USD', 'CNY', 5000000.00, 35000000.00,
    7.00, 1, 1250000.00,
    '2026-07-15', 'ACTIVE', '工商银行', 'AAA', 'USD/CNY货币掉期-本金交换',
    1, 1, 1
);

INSERT INTO TBL_SWAP_TRANSACTION (
    CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY,
    EFFECTIVE_DATE, MATURITY_DATE, PAYMENT_FREQUENCY,
    PAY_CURRENCY, RECEIVE_CURRENCY, PAY_NOTIONAL, RECEIVE_NOTIONAL,
    INITIAL_EXCHANGE_RATE, EXCHANGE_PRINCIPAL, CURRENT_VALUE,
    NEXT_PAYMENT_DATE, STATUS, COUNTERPARTY, COUNTERPARTY_RATING,
    REMARK, CREATE_BY, UPDATE_BY, ORG_ID
) VALUES (
    'SWAP-2026-007', 'CURRENCY', 10000000.00, 'EUR',
    '2026-02-10', '2029-02-10', 'QUARTERLY',
    'EUR', 'USD', 10000000.00, 10800000.00,
    1.08, 1, -850000.00,
    '2026-05-10', 'ACTIVE', '花旗银行', 'AAA', 'EUR/USD货币掉期',
    1, 1, 1
);

INSERT INTO TBL_SWAP_TRANSACTION (
    CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY,
    EFFECTIVE_DATE, MATURITY_DATE, PAYMENT_FREQUENCY,
    PAY_CURRENCY, RECEIVE_CURRENCY, PAY_NOTIONAL, RECEIVE_NOTIONAL,
    INITIAL_EXCHANGE_RATE, EXCHANGE_PRINCIPAL, CURRENT_VALUE,
    NEXT_PAYMENT_DATE, STATUS, COUNTERPARTY, COUNTERPARTY_RATING,
    REMARK, CREATE_BY, UPDATE_BY, ORG_ID
) VALUES (
    'SWAP-2026-008', 'CURRENCY', 3000000.00, 'JPY',
    '2026-03-01', '2027-03-01', 'SEMI_ANNUAL',
    'JPY', 'CNY', 3000000.00, 1800000.00,
    0.06, 1, 95000.00,
    '2026-09-01', 'ACTIVE', '三菱UFJ银行', 'AA+', 'JPY/CNY货币掉期',
    1, 1, 1
);

INSERT INTO TBL_SWAP_TRANSACTION (
    CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY,
    EFFECTIVE_DATE, MATURITY_DATE, PAYMENT_FREQUENCY,
    PAY_CURRENCY, RECEIVE_CURRENCY, PAY_NOTIONAL, RECEIVE_NOTIONAL,
    INITIAL_EXCHANGE_RATE, EXCHANGE_PRINCIPAL, CURRENT_VALUE,
    NEXT_PAYMENT_DATE, STATUS, COUNTERPARTY, COUNTERPARTY_RATING,
    REMARK, CREATE_BY, UPDATE_BY, ORG_ID
) VALUES (
    'SWAP-2026-009', 'CURRENCY', 8000000.00, 'GBP',
    '2026-01-25', '2027-01-25', 'QUARTERLY',
    'GBP', 'USD', 8000000.00, 10000000.00,
    1.25, 1, -450000.00,
    '2026-04-25', 'PENDING', '巴克莱银行', 'AA', 'GBP/USD货币掉期-待生效',
    1, 1, 1
);

INSERT INTO TBL_SWAP_TRANSACTION (
    CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY,
    EFFECTIVE_DATE, MATURITY_DATE, FIXED_RATE, FLOATING_RATE_BASIS,
    SPREAD, PAYMENT_FREQUENCY, DAY_COUNT_BASIS, PAY_DIRECTION,
    CURRENT_VALUE, NEXT_PAYMENT_DATE, STATUS, COUNTERPARTY,
    COUNTERPARTY_RATING, REMARK, CREATE_BY, UPDATE_BY, ORG_ID
) VALUES (
    'SWAP-2026-010', 'INTEREST_RATE', 60000000.00, 'CNY',
    '2025-06-01', '2025-12-31', 3.25, 'LPR',
    0.55, 'QUARTERLY', 'ACT_360', 'PAY_FIXED',
    0.00, '2025-12-31', 'MATURED', '中国银行', 'AAA', '已到期的利率掉期合约',
    1, 1, 1
);

COMMIT;

-- 查询验证数据
SELECT COUNT(*) AS TOTAL_RECORDS FROM TBL_SWAP_TRANSACTION;
SELECT TRANSACTION_ID, CONTRACT_CODE, SWAP_TYPE, NOTIONAL_AMOUNT, CURRENCY, STATUS, CREATE_BY
FROM TBL_SWAP_TRANSACTION
ORDER BY TRANSACTION_ID;
