-- =============================================================
-- 表名: TBL_GT_MARKET_DATA
-- 描述: 全球司库-市场数据表
-- 数据库: 达梦数据库兼容
-- 作者: Claude Code
-- 日期: 2025-01-21
-- =============================================================

-- 删除表(如果存在)
DROP TABLE IF EXISTS TBL_GT_MARKET_DATA;

-- 创建表
CREATE TABLE TBL_GT_MARKET_DATA (
    DATA_ID BIGINT IDENTITY(1,1) NOT NULL,
    DATA_TYPE VARCHAR(50) NOT NULL,
    SYMBOL VARCHAR(50) NOT NULL,
    SYMBOL_NAME VARCHAR(200),
    DATA_VALUE DECIMAL(18,6) NOT NULL,
    DATA_DATE DATE NOT NULL,
    DATA_TIME TIMESTAMP,
    DATA_SOURCE VARCHAR(50),
    IS_ACTIVE INT DEFAULT 1 NOT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY VARCHAR(50),
    UPDATE_BY VARCHAR(50)
);

-- 添加表注释
COMMENT ON TABLE TBL_GT_MARKET_DATA IS '全球司库-市场数据表';

-- 添加字段注释
COMMENT ON COLUMN TBL_GT_MARKET_DATA.DATA_ID IS '数据ID';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.DATA_TYPE IS '数据类型(EXCHANGE_RATE-汇率/INTEREST_RATE-利率/BOND_YIELD-债券收益率/STOCK_PRICE-股价/COMMODITY-大宗商品)';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.SYMBOL IS '数据代码(如USDCNY/SHIBOR_1M/CN10Y)';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.SYMBOL_NAME IS '数据名称';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.DATA_VALUE IS '数据值';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.DATA_DATE IS '数据日期';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.DATA_TIME IS '数据时间';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.DATA_SOURCE IS '数据来源(PBOC-央行/CIBM-银行间市场/SSE-上交所/SZSE-深交所/BLOOMBERG-彭博/REUTERS-路透)';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.IS_ACTIVE IS '是否有效(1-有效/0-无效)';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.STATUS IS '状态(1-正常/0-删除)';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.REMARK IS '备注';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_GT_MARKET_DATA.UPDATE_BY IS '更新人';

-- 创建索引
CREATE INDEX IDX_MARKET_DATA_TYPE ON TBL_GT_MARKET_DATA(DATA_TYPE);
CREATE INDEX IDX_MARKET_SYMBOL ON TBL_GT_MARKET_DATA(SYMBOL);
CREATE INDEX IDX_MARKET_DATA_DATE ON TBL_GT_MARKET_DATA(DATA_DATE);
CREATE INDEX IDX_MARKET_DATA_SOURCE ON TBL_GT_MARKET_DATA(DATA_SOURCE);
CREATE INDEX IDX_MARKET_ACTIVE ON TBL_GT_MARKET_DATA(STATUS, IS_ACTIVE);
CREATE INDEX IDX_MARKET_CREATE_TIME ON TBL_GT_MARKET_DATA(CREATE_TIME);

-- 插入测试数据
INSERT INTO TBL_GT_MARKET_DATA (DATA_TYPE, SYMBOL, SYMBOL_NAME, DATA_VALUE, DATA_DATE, DATA_TIME, DATA_SOURCE, IS_ACTIVE, STATUS, CREATE_BY, UPDATE_BY) VALUES
('EXCHANGE_RATE', 'USDCNY', '美元兑人民币', 7.1234, '2024-09-25', '2024-09-25 09:30:00', 'PBOC', 1, 1, 'admin', 'admin'),
('INTEREST_RATE', 'SHIBOR_1M', '上海银行间同业拆放利率1个月', 2.3450, '2024-09-25', '2024-09-25 11:30:00', 'CIBM', 1, 1, 'admin', 'admin'),
('BOND_YIELD', 'CN10Y', '中国10年期国债收益率', 2.6780, '2024-09-25', '2024-09-25 15:00:00', 'CIBM', 1, 1, 'admin', 'admin'),
('STOCK_PRICE', 'SH000001', '上证指数', 3125.50, '2024-09-25', '2024-09-25 15:00:00', 'SSE', 1, 1, 'admin', 'admin'),
('COMMODITY', 'GOLD', '黄金价格', 568.50, '2024-09-25', '2024-09-25 15:00:00', 'BLOOMBERG', 1, 1, 'admin', 'admin');

COMMIT;
