-- =============================================================
-- 表名: TBL_GT_INTEREST_RATE
-- 描述: 全球司库-利率配置表
-- 数据库: 达梦数据库兼容
-- 作者: Claude Code
-- 日期: 2025-01-21
-- =============================================================

-- 删除表(如果存在)
DROP TABLE IF EXISTS TBL_GT_INTEREST_RATE;

-- 创建表
CREATE TABLE TBL_GT_INTEREST_RATE (
    RATE_ID BIGINT IDENTITY(1,1) NOT NULL,
    RATE_TYPE VARCHAR(20) NOT NULL,
    CURRENCY_CODE VARCHAR(10) NOT NULL,
    TERM INT NOT NULL,
    TERM_UNIT VARCHAR(10) NOT NULL,
    INTEREST_RATE DECIMAL(10,6) NOT NULL,
    RATE_DATE DATE NOT NULL,
    RATE_SOURCE VARCHAR(50),
    IS_ACTIVE INT DEFAULT 1 NOT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY VARCHAR(50),
    UPDATE_BY VARCHAR(50)
);

-- 添加表注释
COMMENT ON TABLE TBL_GT_INTEREST_RATE IS '全球司库-利率配置表';

-- 添加字段注释
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.RATE_ID IS '利率ID';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.RATE_TYPE IS '利率类型(DEPOSIT-存款/LOAN-贷款/INTERBANK-同业/BOND-债券)';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.CURRENCY_CODE IS '币种代码(CNY/USD/EUR/JPY/GBP/HKD)';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.TERM IS '期限';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.TERM_UNIT IS '期限单位(DAY-天/MONTH-月/YEAR-年)';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.INTEREST_RATE IS '利率值(%)';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.RATE_DATE IS '利率日期';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.RATE_SOURCE IS '利率来源(PBOC-央行/BANK-银行/MARKET-市场/THIRD_PARTY-第三方)';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.IS_ACTIVE IS '是否启用(1-启用/0-停用)';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.STATUS IS '状态(1-正常/0-删除)';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.REMARK IS '备注';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_GT_INTEREST_RATE.UPDATE_BY IS '更新人';

-- 创建索引
CREATE INDEX IDX_INTEREST_RATE_TYPE ON TBL_GT_INTEREST_RATE(RATE_TYPE);
CREATE INDEX IDX_INTEREST_CURRENCY ON TBL_GT_INTEREST_RATE(CURRENCY_CODE);
CREATE INDEX IDX_INTEREST_TERM ON TBL_GT_INTEREST_RATE(TERM, TERM_UNIT);
CREATE INDEX IDX_INTEREST_RATE_DATE ON TBL_GT_INTEREST_RATE(RATE_DATE);
CREATE INDEX IDX_INTEREST_SOURCE ON TBL_GT_INTEREST_RATE(RATE_SOURCE);
CREATE INDEX IDX_INTEREST_STATUS ON TBL_GT_INTEREST_RATE(STATUS, IS_ACTIVE);
CREATE INDEX IDX_INTEREST_CREATE_TIME ON TBL_GT_INTEREST_RATE(CREATE_TIME);

-- 插入测试数据
INSERT INTO TBL_GT_INTEREST_RATE (RATE_TYPE, CURRENCY_CODE, TERM, TERM_UNIT, INTEREST_RATE, RATE_DATE, RATE_SOURCE, IS_ACTIVE, STATUS, CREATE_BY, UPDATE_BY) VALUES
('DEPOSIT', 'CNY', 3, 'MONTH', 2.75, '2024-09-25', 'PBOC', 1, 1, 'admin', 'admin'),
('DEPOSIT', 'CNY', 6, 'MONTH', 2.95, '2024-09-25', 'PBOC', 1, 1, 'admin', 'admin'),
('DEPOSIT', 'CNY', 12, 'MONTH', 3.15, '2024-09-25', 'PBOC', 1, 1, 'admin', 'admin'),
('LOAN', 'CNY', 12, 'MONTH', 4.35, '2024-09-25', 'PBOC', 1, 1, 'admin', 'admin'),
('LOAN', 'CNY', 36, 'MONTH', 4.75, '2024-09-25', 'PBOC', 1, 1, 'admin', 'admin'),
('INTERBANK', 'CNY', 7, 'DAY', 2.15, '2024-09-25', 'MARKET', 1, 1, 'admin', 'admin'),
('INTERBANK', 'CNY', 30, 'DAY', 2.35, '2024-09-25', 'MARKET', 1, 1, 'admin', 'admin'),
('BOND', 'CNY', 120, 'MONTH', 2.68, '2024-09-25', 'CIBM', 1, 1, 'admin', 'admin');

COMMIT;
