-- =============================================================
-- 表名: TBL_GT_BUSINESS_RULE
-- 描述: 全球司库-业务规则配置表
-- 数据库: 达梦数据库兼容
-- 作者: Claude Code
-- 日期: 2025-01-21
-- =============================================================

-- 删除表(如果存在)
DROP TABLE IF EXISTS TBL_GT_BUSINESS_RULE;

-- 创建表
CREATE TABLE TBL_GT_BUSINESS_RULE (
    RULE_ID BIGINT IDENTITY(1,1) NOT NULL,
    RULE_CODE VARCHAR(50) NOT NULL,
    RULE_NAME VARCHAR(200) NOT NULL,
    RULE_TYPE VARCHAR(50) NOT NULL,
    MODULE_CODE VARCHAR(50),
    PRIORITY VARCHAR(20),
    RULE_STATUS VARCHAR(20),
    EFFECTIVE_TIME TIMESTAMP,
    EXPIRE_TIME TIMESTAMP,
    DESCRIPTION VARCHAR(1000),
    RULE_CONTENT CLOB,
    IS_ACTIVE INT DEFAULT 1 NOT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY VARCHAR(50),
    UPDATE_BY VARCHAR(50)
);

-- 添加表注释
COMMENT ON TABLE TBL_GT_BUSINESS_RULE IS '全球司库-业务规则配置表';

-- 添加字段注释
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.RULE_ID IS '规则ID';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.RULE_CODE IS '规则编码';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.RULE_NAME IS '规则名称';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.RULE_TYPE IS '规则类型(APPROVAL-审批规则/RISK_CONTROL-风控规则/BUSINESS-业务规则/CALCULATION-计算规则/VALIDATION-验证规则)';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.MODULE_CODE IS '适用模块(ACCOUNT-账户管理/FUND-资金管理/INVESTMENT-投资理财/RISK-风险管理)';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.PRIORITY IS '优先级(HIGH-高/MEDIUM-中/LOW-低)';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.RULE_STATUS IS '规则状态(ENABLED-启用/DISABLED-禁用/TESTING-测试中)';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.EFFECTIVE_TIME IS '生效时间';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.EXPIRE_TIME IS '失效时间';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.DESCRIPTION IS '规则描述';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.RULE_CONTENT IS '规则内容(JSON格式)';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.IS_ACTIVE IS '是否启用(1-启用/0-停用)';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.STATUS IS '状态(1-正常/0-删除)';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.CREATE_BY IS '创建人';
COMMENT ON COLUMN TBL_GT_BUSINESS_RULE.UPDATE_BY IS '更新人';

-- 创建索引
CREATE UNIQUE INDEX IDX_RULE_CODE ON TBL_GT_BUSINESS_RULE(RULE_CODE);
CREATE INDEX IDX_RULE_TYPE ON TBL_GT_BUSINESS_RULE(RULE_TYPE);
CREATE INDEX IDX_RULE_MODULE ON TBL_GT_BUSINESS_RULE(MODULE_CODE);
CREATE INDEX IDX_RULE_STATUS ON TBL_GT_BUSINESS_RULE(RULE_STATUS);
CREATE INDEX IDX_RULE_PRIORITY ON TBL_GT_BUSINESS_RULE(PRIORITY);
CREATE INDEX IDX_RULE_EFFECTIVE_TIME ON TBL_GT_BUSINESS_RULE(EFFECTIVE_TIME);
CREATE INDEX IDX_RULE_ACTIVE ON TBL_GT_BUSINESS_RULE(STATUS, IS_ACTIVE);

-- 插入测试数据
INSERT INTO TBL_GT_BUSINESS_RULE (RULE_CODE, RULE_NAME, RULE_TYPE, MODULE_CODE, PRIORITY, RULE_STATUS, EFFECTIVE_TIME, EXPIRE_TIME, DESCRIPTION, IS_ACTIVE, STATUS, CREATE_BY, UPDATE_BY) VALUES
('RULE_ACCOUNT_001', '账户余额不足检查规则', 'VALIDATION', 'ACCOUNT', 'HIGH', 'ENABLED', '2024-01-01 00:00:00', '2025-12-31 23:59:59', '检查账户余额是否足够支付', 1, 1, 'admin', 'admin'),
('RULE_RISK_002', '大额交易风险控制规则', 'RISK_CONTROL', 'FUND', 'HIGH', 'ENABLED', '2024-01-01 00:00:00', '2025-12-31 23:59:59', '对大额交易进行风险评估和控制', 1, 1, 'admin', 'admin'),
('RULE_APPROVAL_003', '投资审批流程规则', 'APPROVAL', 'INVESTMENT', 'MEDIUM', 'TESTING', '2024-09-01 00:00:00', '2025-12-31 23:59:59', '投资项目的审批流程和权限控制', 1, 1, 'admin', 'admin'),
('RULE_CALC_004', '利息计算规则', 'CALCULATION', 'ACCOUNT', 'MEDIUM', 'ENABLED', '2024-01-01 00:00:00', '2025-12-31 23:59:59', '账户利息自动计算规则', 1, 1, 'admin', 'admin'),
('RULE_VALIDATE_005', '交易时间验证规则', 'VALIDATION', 'FUND', 'LOW', 'ENABLED', '2024-01-01 00:00:00', '2025-12-31 23:59:59', '验证交易时间是否在允许范围内', 1, 1, 'admin', 'admin');

COMMIT;
