-- 财资公共模块 - 数据源配置管理表
-- 兼容达梦数据库规范
-- 创建时间: 2024-12-02
-- 创建人: HuaBo Cloud

-- 删除表（如果存在）
DROP TABLE IF EXISTS TC_DATA_SOURCE_CONFIG;

-- 创建数据源配置表（达梦数据库兼容）
CREATE TABLE TC_DATA_SOURCE_CONFIG (
    ID VARCHAR(32) PRIMARY KEY,
    SOURCE_CODE VARCHAR(64) NOT NULL UNIQUE,
    SOURCE_NAME VARCHAR(200) NOT NULL,
    SOURCE_TYPE VARCHAR(32) NOT NULL,
    DATA_TYPE VARCHAR(32) NOT NULL,
    CONNECTION_CONFIG VARCHAR(2000),
    API_CONFIG VARCHAR(2000),
    CONNECTION_URL VARCHAR(500),
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(500),
    ENVIRONMENT VARCHAR(32),
    CONNECTION_STATUS VARCHAR(32) DEFAULT 'UNTESTED',
    SYNC_FREQUENCY VARCHAR(64),
    LAST_SYNC_TIME TIMESTAMP,
    LAST_TEST_TIME TIMESTAMP,
    SYNC_STATUS VARCHAR(32) DEFAULT 'PENDING',
    ERROR_COUNT INT DEFAULT 0,
    MAX_ERROR_COUNT INT DEFAULT 3,
    TIMEOUT_SECONDS INT DEFAULT 30,
    RETRY_COUNT INT DEFAULT 3,
    IS_ENABLED VARCHAR(1) DEFAULT '1',
    IS_ACTIVE VARCHAR(1) DEFAULT '1',
    STATUS VARCHAR(1) DEFAULT '1',
    REMARK VARCHAR(1000),
    DESCRIPTION VARCHAR(1000),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR(64),
    UPDATE_USER VARCHAR(64),
    VERSION_NO INT DEFAULT 1
);

-- 创建索引（达梦数据库兼容）
CREATE INDEX IDX_TC_DATA_SOURCE_CODE ON TC_DATA_SOURCE_CONFIG(SOURCE_CODE);
CREATE INDEX IDX_TC_DATA_SOURCE_TYPE ON TC_DATA_SOURCE_CONFIG(SOURCE_TYPE);
CREATE INDEX IDX_TC_DATA_SOURCE_ENV ON TC_DATA_SOURCE_CONFIG(ENVIRONMENT);
CREATE INDEX IDX_TC_DATA_SOURCE_STATUS ON TC_DATA_SOURCE_CONFIG(CONNECTION_STATUS);
CREATE INDEX IDX_TC_DATA_SOURCE_ENABLED ON TC_DATA_SOURCE_CONFIG(IS_ENABLED);
CREATE INDEX IDX_TC_DATA_SOURCE_SYNC ON TC_DATA_SOURCE_CONFIG(SYNC_STATUS);
CREATE INDEX IDX_TC_DATA_SOURCE_CREATE_TIME ON TC_DATA_SOURCE_CONFIG(CREATE_TIME);

-- 达梦数据库表注释
COMMENT ON TABLE TC_DATA_SOURCE_CONFIG IS '财资公共模块 - 数据源配置管理表';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.ID IS '主键ID';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.SOURCE_CODE IS '数据源编码';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.SOURCE_NAME IS '数据源名称';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.SOURCE_TYPE IS '数据源类型';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.DATA_TYPE IS '数据类型';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CONNECTION_CONFIG IS '连接配置（JSON格式）';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.API_CONFIG IS 'API配置（JSON格式）';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CONNECTION_URL IS '连接地址';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.USERNAME IS '用户名';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.PASSWORD IS '密码';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.ENVIRONMENT IS '环境类型';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CONNECTION_STATUS IS '连接状态';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.SYNC_FREQUENCY IS '同步频率';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.LAST_SYNC_TIME IS '最后同步时间';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.LAST_TEST_TIME IS '最后测试时间';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.SYNC_STATUS IS '同步状态';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.ERROR_COUNT IS '错误次数';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.MAX_ERROR_COUNT IS '最大错误次数';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.TIMEOUT_SECONDS IS '超时时间（秒）';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.RETRY_COUNT IS '重试次数';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.IS_ENABLED IS '是否启用：1-是，0-否';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.IS_ACTIVE IS '是否激活：1-是，0-否';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.STATUS IS '状态：1-启用，0-停用';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.REMARK IS '备注';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.DESCRIPTION IS '描述';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.CREATE_USER IS '创建人';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.UPDATE_USER IS '更新人';
COMMENT ON COLUMN TC_DATA_SOURCE_CONFIG.VERSION_NO IS '版本号';

-- 插入初始数据（使用固定ID，兼容所有数据库类型）
INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, DESCRIPTION, CREATE_USER, CREATE_TIME
) VALUES (
    'DS001', 'DS_MYSQL_MAIN', '主数据库MySQL', 'MYSQL', 'DATABASE',
    'jdbc:mysql://192.0.2.200:3306/hbyun_treasury', 'treasury_user', 'PROD', 'NORMAL',
    '1', '财资系统主数据库连接', 'system', CURRENT_TIMESTAMP
);

INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, DESCRIPTION, CREATE_USER, CREATE_TIME
) VALUES (
    'DS002', 'DS_DAMENG_BACKUP', '备份数据库达梦', 'DAMENG', 'DATABASE',
    'jdbc:dm://192.0.2.200:5236/HBYUN_BACKUP', 'backup_user', 'PROD', 'NORMAL',
    '1', '财资系统备份数据库连接', 'system', CURRENT_TIMESTAMP
);

INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, DESCRIPTION, CREATE_USER, CREATE_TIME
) VALUES (
    'DS003', 'DS_API_BANK', '银行接口API', 'API', 'API',
    'https://api.bank.com/treasury/v1', 'api_user', 'PROD', 'ERROR',
    '0', '银行系统API接口连接', 'system', CURRENT_TIMESTAMP
);

INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, DESCRIPTION, CREATE_USER, CREATE_TIME
) VALUES (
    'DS004', 'DS_REDIS_CACHE', 'Redis缓存服务', 'REDIS', 'CACHE',
    'redis://192.0.2.200:6379/0', 'redis_user', 'TEST', 'NORMAL',
    '1', 'Redis缓存服务连接', 'system', CURRENT_TIMESTAMP
);

INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, DESCRIPTION, CREATE_USER, CREATE_TIME
) VALUES (
    'DS005', 'DS_POSTGRESQL_DEV', '开发环境PostgreSQL', 'POSTGRESQL', 'DATABASE',
    'jdbc:postgresql://192.0.2.200:5432/hbyun_dev', 'dev_user', 'DEV', 'NORMAL',
    '1', '开发环境PostgreSQL数据库', 'system', CURRENT_TIMESTAMP
);

INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, DESCRIPTION, CREATE_USER, CREATE_TIME
) VALUES (
    'DS006', 'DS_ORACLE_ERP', 'ERP系统Oracle', 'ORACLE', 'DATABASE',
    'jdbc:oracle:thin:@192.0.2.200:1521:ORCL', 'erp_user', 'PROD', 'UNTESTED',
    '1', 'ERP系统Oracle数据库连接', 'system', CURRENT_TIMESTAMP
);

INSERT INTO TC_DATA_SOURCE_CONFIG (
    ID, SOURCE_CODE, SOURCE_NAME, SOURCE_TYPE, DATA_TYPE,
    CONNECTION_URL, USERNAME, ENVIRONMENT, CONNECTION_STATUS,
    IS_ENABLED, DESCRIPTION, CREATE_USER, CREATE_TIME
) VALUES (
    'DS007', 'DS_FILE_INTERFACE', '文件数据源接口', 'FILE', 'FILE',
    '/data/interface/files/', 'file_user', 'PROD', 'NORMAL',
    '1', '文件数据源接口，用于处理文件导入导出', 'system', CURRENT_TIMESTAMP
);

-- 提交事务
COMMIT;