-- =============================================
-- 数据映射配置表 - 达梦数据库建表脚本
-- 表名: TBL_DATA_MAPPING_CONFIG
-- 说明: 用于管理系统间数据字段映射关系
-- 作者: 华博云开发团队
-- 日期: 2024-12-24
-- =============================================

-- 删除已存在的表(如果存在)
DROP TABLE IF EXISTS TBL_DATA_MAPPING_CONFIG;

-- 创建数据映射配置表
CREATE TABLE TBL_DATA_MAPPING_CONFIG (
    ID BIGINT PRIMARY KEY,
    MAPPING_NAME VARCHAR(200) NOT NULL,
    MAPPING_CODE VARCHAR(100) NOT NULL UNIQUE,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    TARGET_SYSTEM VARCHAR(50) NOT NULL,
    SOURCE_FIELD VARCHAR(500),
    TARGET_FIELD VARCHAR(500),
    MAPPING_TYPE VARCHAR(50) NOT NULL,
    MAPPING_RULE CLOB,
    DESCRIPTION VARCHAR(1000),
    STATUS INTEGER DEFAULT 1,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATE_USER VARCHAR(50),
    UPDATE_USER VARCHAR(50)
);

-- 添加字段注释
COMMENT ON TABLE TBL_DATA_MAPPING_CONFIG IS '数据映射配置表，用于管理系统间数据字段映射关系';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.ID IS '主键ID';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.MAPPING_NAME IS '映射名称';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.MAPPING_CODE IS '映射编码，唯一标识';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.SOURCE_SYSTEM IS '源系统(FINANCE-财务系统,BANK-银行系统,ERP-ERP系统,THIRD_PARTY-第三方系统)';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.TARGET_SYSTEM IS '目标系统(FINANCE-财务系统,BANK-银行系统,ERP-ERP系统,THIRD_PARTY-第三方系统)';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.SOURCE_FIELD IS '源字段名称';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.TARGET_FIELD IS '目标字段名称';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.MAPPING_TYPE IS '映射类型(FIELD-字段映射,VALUE-值映射,FUNCTION-函数映射)';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.MAPPING_RULE IS '映射规则(CLOB类型，存储JSON格式的转换规则)';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.DESCRIPTION IS '描述信息';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.STATUS IS '状态(1-启用,0-禁用)';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.CREATE_USER IS '创建人';
COMMENT ON COLUMN TBL_DATA_MAPPING_CONFIG.UPDATE_USER IS '更新人';

-- 创建索引
CREATE INDEX IDX_MAPPING_CODE ON TBL_DATA_MAPPING_CONFIG(MAPPING_CODE);
CREATE INDEX IDX_SOURCE_SYSTEM ON TBL_DATA_MAPPING_CONFIG(SOURCE_SYSTEM);
CREATE INDEX IDX_TARGET_SYSTEM ON TBL_DATA_MAPPING_CONFIG(TARGET_SYSTEM);
CREATE INDEX IDX_MAPPING_TYPE ON TBL_DATA_MAPPING_CONFIG(MAPPING_TYPE);
CREATE INDEX IDX_STATUS ON TBL_DATA_MAPPING_CONFIG(STATUS);
CREATE INDEX IDX_CREATE_TIME ON TBL_DATA_MAPPING_CONFIG(CREATE_TIME);

-- 插入测试数据
INSERT INTO TBL_DATA_MAPPING_CONFIG (ID, MAPPING_NAME, MAPPING_CODE, SOURCE_SYSTEM, TARGET_SYSTEM, SOURCE_FIELD, TARGET_FIELD, MAPPING_TYPE, MAPPING_RULE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) VALUES
(1735023456789, '用户ID映射', 'MAP_USER_ID', 'FINANCE', 'ERP', 'user_id', 'staff_id', 'FIELD', '直接映射', '将财务系统的用户ID映射到ERP系统的员工ID', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

INSERT INTO TBL_DATA_MAPPING_CONFIG (ID, MAPPING_NAME, MAPPING_CODE, SOURCE_SYSTEM, TARGET_SYSTEM, SOURCE_FIELD, TARGET_FIELD, MAPPING_TYPE, MAPPING_RULE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) VALUES
(1735023456790, '账户名称映射', 'MAP_ACCOUNT_NAME', 'BANK', 'FINANCE', 'account_name', 'account_name', 'VALUE', '{"个人储蓄账户":"SAVINGS","对公账户":"CORPORATE","基本账户":"BASIC"}', '将银行系统的账户类型映射到财务系统的账户类型', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

INSERT INTO TBL_DATA_MAPPING_CONFIG (ID, MAPPING_NAME, MAPPING_CODE, SOURCE_SYSTEM, TARGET_SYSTEM, SOURCE_FIELD, TARGET_FIELD, MAPPING_TYPE, MAPPING_RULE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) VALUES
(1735023456791, '金额格式转换', 'MAP_AMOUNT_FORMAT', 'THIRD_PARTY', 'FINANCE', 'amount', 'amount', 'FUNCTION', 'parseFloat(amount).toFixed(2)', '将第三方系统的金额转换为保留两位小数的格式', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

INSERT INTO TBL_DATA_MAPPING_CONFIG (ID, MAPPING_NAME, MAPPING_CODE, SOURCE_SYSTEM, TARGET_SYSTEM, SOURCE_FIELD, TARGET_FIELD, MAPPING_TYPE, MAPPING_RULE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) VALUES
(1735023456792, '日期时间映射', 'MAP_DATETIME', 'ERP', 'FINANCE', 'create_time', 'create_time', 'FUNCTION', 'new Date(create_time).getTime()', '将ERP系统的日期时间转换为时间戳格式', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

INSERT INTO TBL_DATA_MAPPING_CONFIG (ID, MAPPING_NAME, MAPPING_CODE, SOURCE_SYSTEM, TARGET_SYSTEM, SOURCE_FIELD, TARGET_FIELD, MAPPING_TYPE, MAPPING_RULE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) VALUES
(1735023456793, '部门编码映射', 'MAP_DEPT_CODE', 'FINANCE', 'ERP', 'dept_code', 'department_code', 'FIELD', '直接映射', '将财务系统的部门编码映射到ERP系统的部门编码', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

INSERT INTO TBL_DATA_MAPPING_CONFIG (ID, MAPPING_NAME, MAPPING_CODE, SOURCE_SYSTEM, TARGET_SYSTEM, SOURCE_FIELD, TARGET_FIELD, MAPPING_TYPE, MAPPING_RULE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) VALUES
(1735023456794, '交易状态映射', 'MAP_TXN_STATUS', 'BANK', 'FINANCE', 'status', 'txn_status', 'VALUE', '{"成功":"SUCCESS","失败":"FAILED","处理中":"PROCESSING","待处理":"PENDING"}', '将银行系统的交易状态映射到财务系统的交易状态', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

INSERT INTO TBL_DATA_MAPPING_CONFIG (ID, MAPPING_NAME, MAPPING_CODE, SOURCE_SYSTEM, TARGET_SYSTEM, SOURCE_FIELD, TARGET_FIELD, MAPPING_TYPE, MAPPING_RULE, DESCRIPTION, STATUS, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) VALUES
(1735023456795, '客户姓名映射', 'MAP_CUSTOMER_NAME', 'THIRD_PARTY', 'FINANCE', 'customer_name', 'client_name', 'FIELD', '直接映射', '将第三方系统的客户姓名映射到财务系统的客户姓名', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

-- 提交事务
COMMIT;

-- 查询验证
SELECT COUNT(*) AS total_records FROM TBL_DATA_MAPPING_CONFIG;
