-- =============================================
-- 市场数据表
-- 表名: TC_MARKET_DATA
-- 说明: 存储各类金融市场数据,包括汇率、利率、债券收益率、股价和大宗商品价格
-- =============================================

CREATE TABLE "REDACTED"."TC_MARKET_DATA"
(
    "DATA_ID" VARCHAR2(32) NOT NULL,                    -- 数据ID(主键)
    "DATA_TYPE" VARCHAR2(20) NOT NULL,                 -- 数据类型(EXCHANGE_RATE-汇率, INTEREST_RATE-利率, BOND_YIELD-债券收益率, STOCK_PRICE-股价, COMMODITY-大宗商品)
    "SYMBOL" VARCHAR2(50) NOT NULL,                    -- 数据代码(如USD/CNY, SHIBOR等)
    "SYMBOL_NAME" VARCHAR2(100),                       -- 数据名称
    "DATA_VALUE" NUMBER(20,8) NOT NULL,                -- 数据值
    "DATA_DATE" DATE NOT NULL,                         -- 数据日期
    "DATA_SOURCE" VARCHAR2(50),                        -- 数据来源(PBOC-央行, CIBM-银行间市场, SSE-上交所, SZSE-深交所, BLOOMBERG-彭博, REUTERS-路透)
    "IS_ACTIVE" NUMBER(1) DEFAULT 1,                   -- 是否有效(1-有效 0-无效)
    "CREATE_TIME" DATE DEFAULT SYSDATE,                -- 创建时间
    "UPDATE_TIME" DATE DEFAULT SYSDATE,                -- 更新时间
    "CREATE_USER" VARCHAR2(50),                        -- 创建人
    "UPDATE_USER" VARCHAR2(50),                        -- 更新人
    "VERSION_NO" NUMBER(10) DEFAULT 0,                 -- 版本号
    "REMARK" VARCHAR2(500),                            -- 备注
    CONSTRAINT "PK_TC_MARKET_DATA" PRIMARY KEY ("DATA_ID")
);

-- 添加注释
COMMENT ON TABLE "REDACTED"."TC_MARKET_DATA" IS '市场数据表';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."DATA_ID" IS '数据ID';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."DATA_TYPE" IS '数据类型';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."SYMBOL" IS '数据代码';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."SYMBOL_NAME" IS '数据名称';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."DATA_VALUE" IS '数据值';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."DATA_DATE" IS '数据日期';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."DATA_SOURCE" IS '数据来源';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."IS_ACTIVE" IS '是否有效';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."CREATE_USER" IS '创建人';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."UPDATE_USER" IS '更新人';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."VERSION_NO" IS '版本号';
COMMENT ON COLUMN "REDACTED"."TC_MARKET_DATA"."REMARK" IS '备注';

-- 创建索引
CREATE UNIQUE INDEX "IDX_MARKET_DATA_ID" ON "REDACTED"."TC_MARKET_DATA"("DATA_ID");
CREATE INDEX "IDX_MARKET_DATA_TYPE" ON "REDACTED"."TC_MARKET_DATA"("DATA_TYPE");
CREATE INDEX "IDX_MARKET_DATA_SYMBOL" ON "REDACTED"."TC_MARKET_DATA"("SYMBOL");
CREATE INDEX "IDX_MARKET_DATA_DATE" ON "REDACTED"."TC_MARKET_DATA"("DATA_DATE");
CREATE INDEX "IDX_MARKET_DATA_SOURCE" ON "REDACTED"."TC_MARKET_DATA"("DATA_SOURCE");
CREATE INDEX "IDX_MARKET_DATA_ACTIVE" ON "REDACTED"."TC_MARKET_DATA"("IS_ACTIVE");

-- 创建组合索引(用于常用查询)
CREATE INDEX "IDX_MARKET_DATA_TYPE_DATE" ON "REDACTED"."TC_MARKET_DATA"("DATA_TYPE", "DATA_DATE" DESC);
