-- =============================================
-- 市场数据测试数据
-- 表名: TC_MARKET_DATA
-- 生成时间: 2025-01-21
-- 说明: 包含10条不同类型的市场数据测试数据
-- =============================================

-- 1. 美元兑人民币汇率
INSERT INTO TC_MARKET_DATA (
    DATA_ID, DATA_TYPE, SYMBOL, SYMBOL_NAME, DATA_VALUE, DATA_DATE, DATA_SOURCE,
    IS_ACTIVE, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO, REMARK
) VALUES (
    SYS_GUID(), 'EXCHANGE_RATE', 'USD/CNY', '美元兑人民币', 7.2456, TO_DATE('2025-01-21', 'YYYY-MM-DD'),
    'PBOC', 1, SYSDATE, SYSDATE, 'admin', 'admin', 0, '央行中间价'
);

-- 2. 欧元兑人民币汇率
INSERT INTO TC_MARKET_DATA (
    DATA_ID, DATA_TYPE, SYMBOL, SYMBOL_NAME, DATA_VALUE, DATA_DATE, DATA_SOURCE,
    IS_ACTIVE, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO, REMARK
) VALUES (
    SYS_GUID(), 'EXCHANGE_RATE', 'EUR/CNY', '欧元兑人民币', 7.8123, TO_DATE('2025-01-21', 'YYYY-MM-DD'),
    'PBOC', 1, SYSDATE, SYSDATE, 'admin', 'admin', 0, '央行中间价'
);

-- 3. SHIBOR隔夜利率
INSERT INTO TC_MARKET_DATA (
    DATA_ID, DATA_TYPE, SYMBOL, SYMBOL_NAME, DATA_VALUE, DATA_DATE, DATA_SOURCE,
    IS_ACTIVE, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO, REMARK
) VALUES (
    SYS_GUID(), 'INTEREST_RATE', 'SHIBOR_O/N', '上海银行间同业拆放利率-隔夜', 1.8547, TO_DATE('2025-01-21', 'YYYY-MM-DD'),
    'CIBM', 1, SYSDATE, SYSDATE, 'admin', 'admin', 0, '银行间市场'
);

-- 4. 10年期国债收益率
INSERT INTO TC_MARKET_DATA (
    DATA_ID, DATA_TYPE, SYMBOL, SYMBOL_NAME, DATA_VALUE, DATA_DATE, DATA_SOURCE,
    IS_ACTIVE, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO, REMARK
) VALUES (
    SYS_GUID(), 'BOND_YIELD', 'CGB_10Y', '中国10年期国债收益率', 2.6834, TO_DATE('2025-01-21', 'YYYY-MM-DD'),
    'CIBM', 1, SYSDATE, SYSDATE, 'admin', 'admin', 0, '银行间市场'
);

-- 5. 上证指数
INSERT INTO TC_MARKET_DATA (
    DATA_ID, DATA_TYPE, SYMBOL, SYMBOL_NAME, DATA_VALUE, DATA_DATE, DATA_SOURCE,
    IS_ACTIVE, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO, REMARK
) VALUES (
    SYS_GUID(), 'STOCK_PRICE', 'SSEC', '上证综合指数', 3245.67, TO_DATE('2025-01-21', 'YYYY-MM-DD'),
    'SSE', 1, SYSDATE, SYSDATE, 'admin', 'admin', 0, '上交所收盘指数'
);

-- 6. 深证成指
INSERT INTO TC_MARKET_DATA (
    DATA_ID, DATA_TYPE, SYMBOL, SYMBOL_NAME, DATA_VALUE, DATA_DATE, DATA_SOURCE,
    IS_ACTIVE, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO, REMARK
) VALUES (
    SYS_GUID(), 'STOCK_PRICE', 'SZI', '深证成份指数', 10256.89, TO_DATE('2025-01-21', 'YYYY-MM-DD'),
    'SZSE', 1, SYSDATE, SYSDATE, 'admin', 'admin', 0, '深交所收盘指数'
);

-- 7. 黄金期货价格
INSERT INTO TC_MARKET_DATA (
    DATA_ID, DATA_TYPE, SYMBOL, SYMBOL_NAME, DATA_VALUE, DATA_DATE, DATA_SOURCE,
    IS_ACTIVE, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO, REMARK
) VALUES (
    SYS_GUID(), 'COMMODITY', 'GOLD_FUT', '黄金期货价格', 512.45, TO_DATE('2025-01-21', 'YYYY-MM-DD'),
    'SSE', 1, SYSDATE, SYSDATE, 'admin', 'admin', 0, '元/克'
);

-- 8. 原油期货价格
INSERT INTO TC_MARKET_DATA (
    DATA_ID, DATA_TYPE, SYMBOL, SYMBOL_NAME, DATA_VALUE, DATA_DATE, DATA_SOURCE,
    IS_ACTIVE, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO, REMARK
) VALUES (
    SYS_GUID(), 'COMMODITY', 'CRUDE_OIL', '原油期货价格', 568.90, TO_DATE('2025-01-21', 'YYYY-MM-DD'),
    'BLOOMBERG', 1, SYSDATE, SYSDATE, 'admin', 'admin', 0, '美元/桶'
);

-- 9. LPR利率(1年期)
INSERT INTO TC_MARKET_DATA (
    DATA_ID, DATA_TYPE, SYMBOL, SYMBOL_NAME, DATA_VALUE, DATA_DATE, DATA_SOURCE,
    IS_ACTIVE, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO, REMARK
) VALUES (
    SYS_GUID(), 'INTEREST_RATE', 'LPR_1Y', '贷款市场报价利率-1年期', 3.4500, TO_DATE('2025-01-21', 'YYYY-MM-DD'),
    'PBOC', 1, SYSDATE, SYSDATE, 'admin', 'admin', 0, '央行公布'
);

-- 10. 日元兑人民币汇率
INSERT INTO TC_MARKET_DATA (
    DATA_ID, DATA_TYPE, SYMBOL, SYMBOL_NAME, DATA_VALUE, DATA_DATE, DATA_SOURCE,
    IS_ACTIVE, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER, VERSION_NO, REMARK
) VALUES (
    SYS_GUID(), 'EXCHANGE_RATE', 'JPY/CNY', '日元兑人民币', 0.0489, TO_DATE('2025-01-21', 'YYYY-MM-DD'),
    'PBOC', 1, SYSDATE, SYSDATE, 'admin', 'admin', 0, '央行中间价'
);

-- =============================================
-- 数据说明
-- =============================================
-- 1. 数据类型包括: EXCHANGE_RATE(汇率), INTEREST_RATE(利率), BOND_YIELD(债券收益率), STOCK_PRICE(股价), COMMODITY(大宗商品)
-- 2. 数据来源包括: PBOC(央行), CIBM(银行间市场), SSE(上交所), SZSE(深交所), BLOOMBERG(彭博)
-- 3. IS_ACTIVE: 1-有效, 0-无效

-- =============================================
-- 查询验证SQL
-- =============================================
-- 查询所有市场数据
-- SELECT * FROM TC_MARKET_DATA ORDER BY DATA_DATE DESC;

-- 按数据类型统计
-- SELECT DATA_TYPE, COUNT(*) AS COUNT FROM TC_MARKET_DATA GROUP BY DATA_TYPE;

-- 按数据来源统计
-- SELECT DATA_SOURCE, COUNT(*) AS COUNT FROM TC_MARKET_DATA GROUP BY DATA_SOURCE;

-- 查询有效的数据
-- SELECT * FROM TC_MARKET_DATA WHERE IS_ACTIVE = 1;

-- 查询今日数据
-- SELECT * FROM TC_MARKET_DATA WHERE DATA_DATE = TRUNC(SYSDATE);
