-- =============================================
-- 印鉴档案表 V2 - 达梦数据库建表脚本
-- 表名: TC_SEAL_ARCHIVE_V2
-- 描述: 存储印鉴档案信息(印鉴编号、名称、类型、持有人等)
-- 作者: 华博云开发团队
-- 创建时间: 2024-12-24
-- 兼容性: 达梦数据库 (DM Database)
-- 版本: V2 (修复前后端字段不匹配问题)
-- =============================================

-- 创建印鉴档案表V2
CREATE TABLE TC_SEAL_ARCHIVE_V2 (
    ID DECIMAL(20,0) NOT NULL,
    SEAL_CODE VARCHAR(50) NOT NULL,
    SEAL_NAME VARCHAR(200) NOT NULL,
    SEAL_TYPE_ID DECIMAL(20,0),
    SEAL_TYPE_NAME VARCHAR(100),
    OWNER_NAME VARCHAR(100),
    OWNER_POSITION VARCHAR(100),
    OWNER_ID_CARD VARCHAR(50),
    EFFECTIVE_DATE DATE,
    EXPIRE_DATE DATE,
    SEAL_IMAGE_URL VARCHAR(500),
    IS_ACTIVE INTEGER DEFAULT 1,
    VERSION_NO INTEGER DEFAULT 1,
    DESCRIPTION VARCHAR(500),
    CREATE_BY VARCHAR(50),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(50),
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    CONSTRAINT PK_SEAL_ARCHIVE_V2 PRIMARY KEY (ID)
);

-- 添加表注释
COMMENT ON TABLE TC_SEAL_ARCHIVE_V2 IS '印鉴档案表 V2版本';

-- 添加列注释
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.ID IS '印鉴ID(主键)';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.SEAL_CODE IS '印鉴编号';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.SEAL_NAME IS '印鉴名称';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.SEAL_TYPE_ID IS '印鉴类型ID(关联TC_SEAL_TYPE表)';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.SEAL_TYPE_NAME IS '印鉴类型名称(冗余字段,方便查询)';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.OWNER_NAME IS '持有人姓名';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.OWNER_POSITION IS '持有人职位';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.OWNER_ID_CARD IS '持有人身份证号';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.EFFECTIVE_DATE IS '生效日期';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.EXPIRE_DATE IS '失效日期';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.SEAL_IMAGE_URL IS '印鉴图片URL';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.IS_ACTIVE IS '是否启用(1启用/0禁用)';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.VERSION_NO IS '版本号';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.DESCRIPTION IS '描述信息';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.CREATE_BY IS '创建人';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.UPDATE_BY IS '更新人';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TC_SEAL_ARCHIVE_V2.REMARK IS '备注信息';

-- 创建索引
CREATE UNIQUE INDEX IDX_SEAL_CODE_V2 ON TC_SEAL_ARCHIVE_V2(SEAL_CODE);
CREATE INDEX IDX_SEAL_TYPE_V2 ON TC_SEAL_ARCHIVE_V2(SEAL_TYPE_ID);
CREATE INDEX IDX_OWNER_V2 ON TC_SEAL_ARCHIVE_V2(OWNER_NAME);
CREATE INDEX IDX_STATUS_V2 ON TC_SEAL_ARCHIVE_V2(IS_ACTIVE);
CREATE INDEX IDX_CREATE_TIME_V2 ON TC_SEAL_ARCHIVE_V2(CREATE_TIME);

-- 插入测试数据 (5条)
INSERT INTO TC_SEAL_ARCHIVE_V2 (ID, SEAL_CODE, SEAL_NAME, SEAL_TYPE_ID, SEAL_TYPE_NAME,
    OWNER_NAME, OWNER_POSITION, OWNER_ID_CARD, EFFECTIVE_DATE, EXPIRE_DATE,
    SEAL_IMAGE_URL, IS_ACTIVE, VERSION_NO, DESCRIPTION, CREATE_TIME, CREATE_BY) VALUES
(1, 'SEAL20240001', '公司公章-总部', 1, '公章',
    '张三', '总经理', '110101199001011234', TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2025-12-31', 'YYYY-MM-DD'),
    '/seals/company_seal_hq.png', 1, 1, '总部使用的公司公章', CURRENT_TIMESTAMP, 'admin');

INSERT INTO TC_SEAL_ARCHIVE_V2 (ID, SEAL_CODE, SEAL_NAME, SEAL_TYPE_ID, SEAL_TYPE_NAME,
    OWNER_NAME, OWNER_POSITION, OWNER_ID_CARD, EFFECTIVE_DATE, EXPIRE_DATE,
    SEAL_IMAGE_URL, IS_ACTIVE, VERSION_NO, DESCRIPTION, CREATE_TIME, CREATE_BY) VALUES
(2, 'SEAL20240002', '财务专用章-财务部', 2, '财务章',
    '李四', '财务总监', '110101199002022345', TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2025-12-31', 'YYYY-MM-DD'),
    '/seals/finance_seal.png', 1, 1, '财务部专用章', CURRENT_TIMESTAMP, 'admin');

INSERT INTO TC_SEAL_ARCHIVE_V2 (ID, SEAL_CODE, SEAL_NAME, SEAL_TYPE_ID, SEAL_TYPE_NAME,
    OWNER_NAME, OWNER_POSITION, OWNER_ID_CARD, EFFECTIVE_DATE, EXPIRE_DATE,
    SEAL_IMAGE_URL, IS_ACTIVE, VERSION_NO, DESCRIPTION, CREATE_TIME, CREATE_BY) VALUES
(3, 'SEAL20240003', '合同专用章-法务部', 3, '合同章',
    '王五', '法务经理', '110101199003033456', TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2025-12-31', 'YYYY-MM-DD'),
    '/seals/contract_seal.png', 1, 1, '法务部合同专用章', CURRENT_TIMESTAMP, 'admin');

INSERT INTO TC_SEAL_ARCHIVE_V2 (ID, SEAL_CODE, SEAL_NAME, SEAL_TYPE_ID, SEAL_TYPE_NAME,
    OWNER_NAME, OWNER_POSITION, OWNER_ID_CARD, EFFECTIVE_DATE, EXPIRE_DATE,
    SEAL_IMAGE_URL, IS_ACTIVE, VERSION_NO, DESCRIPTION, CREATE_TIME, CREATE_BY) VALUES
(4, 'SEAL20240004', '法人章-备用', 4, '法人章',
    '赵六', '法定代表人', '110101199004044567', TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2025-12-31', 'YYYY-MM-DD'),
    '/seals/legal_seal.png', 0, 1, '法人章(暂时停用)', CURRENT_TIMESTAMP, 'admin');

INSERT INTO TC_SEAL_ARCHIVE_V2 (ID, SEAL_CODE, SEAL_NAME, SEAL_TYPE_ID, SEAL_TYPE_NAME,
    OWNER_NAME, OWNER_POSITION, OWNER_ID_CARD, EFFECTIVE_DATE, EXPIRE_DATE,
    SEAL_IMAGE_URL, IS_ACTIVE, VERSION_NO, DESCRIPTION, CREATE_TIME, CREATE_BY) VALUES
(5, 'SEAL20240005', '发票专用章-税务部', 5, '发票章',
    '孙七', '税务主管', '110101199005055678', TO_DATE('2024-05-01', 'YYYY-MM-DD'), TO_DATE('2025-12-31', 'YYYY-MM-DD'),
    '/seals/invoice_seal.png', 1, 1, '税务部发票专用章', CURRENT_TIMESTAMP, 'admin');

-- 提交事务
COMMIT;

-- 验证结果
-- SELECT * FROM TC_SEAL_ARCHIVE_V2;
-- SELECT COUNT(*) AS total_count FROM TC_SEAL_ARCHIVE_V2;
-- SELECT * FROM TC_SEAL_ARCHIVE_V2 WHERE IS_ACTIVE = 1;
