-- =============================================
-- 印鉴类型表 - 达梦数据库建表脚本
-- 表名: TC_SEAL_TYPE
-- 描述: 存储印鉴类型信息(公章、财务章、合同章等)
-- 作者: 华博云开发团队
-- 创建时间: 2024-12-24
-- 兼容性: 达梦数据库 (DM Database)
-- =============================================

-- 创建印鉴类型表
CREATE TABLE TC_SEAL_TYPE (
    TYPE_ID DECIMAL(20,0) NOT NULL,
    TYPE_NAME VARCHAR(100) NOT NULL,
    TYPE_CODE VARCHAR(50) NOT NULL,
    IS_ACTIVE INTEGER DEFAULT 1,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SEAL_TYPE PRIMARY KEY (TYPE_ID)
);

-- 添加表注释
COMMENT ON TABLE TC_SEAL_TYPE IS '印鉴类型表';

-- 添加列注释
COMMENT ON COLUMN TC_SEAL_TYPE.TYPE_ID IS '类型ID(主键)';
COMMENT ON COLUMN TC_SEAL_TYPE.TYPE_NAME IS '类型名称(公章/财务章/合同章/法人章/发票章)';
COMMENT ON COLUMN TC_SEAL_TYPE.TYPE_CODE IS '类型编码(OFFICIAL/FINANCE/CONTRACT/LEGAL/INVOICE)';
COMMENT ON COLUMN TC_SEAL_TYPE.IS_ACTIVE IS '是否启用(1启用/0禁用)';
COMMENT ON COLUMN TC_SEAL_TYPE.REMARK IS '备注信息';
COMMENT ON COLUMN TC_SEAL_TYPE.CREATE_TIME IS '创建时间';

-- 创建索引
CREATE INDEX IDX_SEAL_TYPE_CODE ON TC_SEAL_TYPE(TYPE_CODE);
CREATE INDEX IDX_SEAL_TYPE_ACTIVE ON TC_SEAL_TYPE(IS_ACTIVE);

-- 插入测试数据
INSERT INTO TC_SEAL_TYPE (TYPE_ID, TYPE_NAME, TYPE_CODE, IS_ACTIVE, REMARK, CREATE_TIME) VALUES
(1, '公章', 'OFFICIAL', 1, '公司公章，用于正式文件', CURRENT_TIMESTAMP),
(2, '财务章', 'FINANCE', 1, '财务专用章', CURRENT_TIMESTAMP),
(3, '合同章', 'CONTRACT', 1, '合同专用章', CURRENT_TIMESTAMP),
(4, '法人章', 'LEGAL', 1, '法定代表人章', CURRENT_TIMESTAMP),
(5, '发票章', 'INVOICE', 1, '发票专用章', CURRENT_TIMESTAMP);

-- 提交事务
COMMIT;

-- 验证结果
-- SELECT * FROM TC_SEAL_TYPE;
