-- 验证衍生品数据是否正确插入
-- 执行此SQL确认数据完整性

-- 1. 检查表是否存在
SELECT '========== 检查表是否存在 ==========' AS INFO;
SELECT TABLE_NAME FROM USER_TABLES
WHERE TABLE_NAME IN (
    'TBL_FORWARD_TRANSACTION',
    'TBL_OPTION_TRANSACTION',
    'TBL_FUTURES_TRANSACTION',
    'TBL_SWAP_TRANSACTION'
)
ORDER BY TABLE_NAME;

-- 2. 检查各表记录数
SELECT '========== 检查记录数 ==========' AS INFO;
SELECT
    '远期交易' AS 表名,
    COUNT(*) AS 总记录数,
    SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS 活跃记录,
    SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END) AS 待生效记录
FROM TBL_FORWARD_TRANSACTION
WHERE DEL_FLAG = '0'

UNION ALL

SELECT
    '期权交易',
    COUNT(*),
    SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END),
    SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END)
FROM TBL_OPTION_TRANSACTION
WHERE DEL_FLAG = '0'

UNION ALL

SELECT
    '期货交易',
    COUNT(*),
    SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END),
    SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END)
FROM TBL_FUTURES_TRANSACTION
WHERE DEL_FLAG = '0'

UNION ALL

SELECT
    '掉期交易',
    COUNT(*),
    SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END),
    SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END)
FROM TBL_SWAP_TRANSACTION
WHERE DEL_FLAG = '0';

-- 3. 检查可用于前端显示的持仓数据(ORG_ID=1)
SELECT '========== 可用持仓数据(ORG_ID=1) ==========' AS INFO;
SELECT PRODUCT_TYPE, COUNT(*) AS COUNT FROM (
    SELECT 'FORWARD' AS PRODUCT_TYPE FROM TBL_FORWARD_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1

    UNION ALL

    SELECT 'OPTION' FROM TBL_OPTION_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1

    UNION ALL

    SELECT 'FUTURES' FROM TBL_FUTURES_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1

    UNION ALL

    SELECT 'SWAP' FROM TBL_SWAP_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1
) GROUP BY PRODUCT_TYPE;

-- 4. 查看远期交易示例数据
SELECT '========== 远期交易示例数据 ==========' AS INFO;
SELECT CONTRACT_CODE, TRANSACTION_TYPE, UNDERLYING_ASSET,
       NOTIONAL_AMOUNT, CURRENCY, CURRENT_VALUE, PNL, STATUS
FROM TBL_FORWARD_TRANSACTION
WHERE DEL_FLAG = '0' AND ORG_ID = 1
ORDER BY TRANSACTION_ID;

-- 5. 查看期权交易示例数据
SELECT '========== 期权交易示例数据 ==========' AS INFO;
SELECT CONTRACT_CODE, OPTION_TYPE, UNDERLYING_ASSET,
       CONTRACT_SIZE, STRIKE_PRICE, THEORETICAL_VALUE, DELTA, GAMMA, STATUS
FROM TBL_OPTION_TRANSACTION
WHERE DEL_FLAG = '0' AND ORG_ID = 1
ORDER BY TRANSACTION_ID;

-- 6. 查看期货交易示例数据
SELECT '========== 期货交易示例数据 ==========' AS INFO;
SELECT CONTRACT_CODE, FUTURES_TYPE, UNDERLYING_ASSET, DIRECTION,
       CONTRACT_SIZE, CURRENT_PRICE, UNREALIZED_PNL, STATUS
FROM TBL_FUTURES_TRANSACTION
WHERE DEL_FLAG = '0' AND ORG_ID = 1
ORDER BY TRANSACTION_ID;

-- 7. 查看掉期交易示例数据
SELECT '========== 掉期交易示例数据 ==========' AS INFO;
SELECT CONTRACT_CODE, SWAP_TYPE, UNDERLYING_ASSET,
       NOTIONAL_AMOUNT, FIXED_RATE, CURRENT_VALUE, STATUS
FROM TBL_SWAP_TRANSACTION
WHERE DEL_FLAG = '0' AND ORG_ID = 1
ORDER BY TRANSACTION_ID;

-- 8. 统计总持仓数
SELECT '========== 总计 ==========' AS INFO;
SELECT COUNT(*) AS TOTAL_POSITIONS FROM (
    SELECT 1 FROM TBL_FORWARD_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1
    UNION ALL
    SELECT 1 FROM TBL_OPTION_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1
    UNION ALL
    SELECT 1 FROM TBL_FUTURES_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1
    UNION ALL
    SELECT 1 FROM TBL_SWAP_TRANSACTION
    WHERE DEL_FLAG = '0' AND STATUS IN ('ACTIVE', 'PENDING') AND ORG_ID = 1
);

-- 9. 检查是否有数据质量问题
SELECT '========== 数据质量检查 ==========' AS INFO;
SELECT '以下检查应该都返回0,如果不是需要修复:' AS INFO;

-- 检查NULL值的ORG_ID
SELECT 'ORG_ID为NULL的记录: ' || COUNT(*) AS CHECK_RESULT
FROM TBL_FORWARD_TRANSACTION
WHERE ORG_ID IS NULL AND DEL_FLAG = '0'
UNION ALL
SELECT 'ORG_ID为NULL的记录: ' || COUNT(*)
FROM TBL_OPTION_TRANSACTION
WHERE ORG_ID IS NULL AND DEL_FLAG = '0'
UNION ALL
SELECT 'ORG_ID为NULL的记录: ' || COUNT(*)
FROM TBL_FUTURES_TRANSACTION
WHERE ORG_ID IS NULL AND DEL_FLAG = '0'
UNION ALL
SELECT 'ORG_ID为NULL的记录: ' || COUNT(*)
FROM TBL_SWAP_TRANSACTION
WHERE ORG_ID IS NULL AND DEL_FLAG = '0';

-- 检查异常状态
SELECT '状态异常的记录: ' || COUNT(*) AS CHECK_RESULT
FROM TBL_FORWARD_TRANSACTION
WHERE STATUS NOT IN ('ACTIVE', 'PENDING', 'CLOSED', 'CANCELLED') AND DEL_FLAG = '0'
UNION ALL
SELECT '状态异常的记录: ' || COUNT(*)
FROM TBL_OPTION_TRANSACTION
WHERE STATUS NOT IN ('ACTIVE', 'PENDING', 'EXERCISED', 'EXPIRED', 'CANCELLED') AND DEL_FLAG = '0'
UNION ALL
SELECT '状态异常的记录: ' || COUNT(*)
FROM TBL_FUTURES_TRANSACTION
WHERE STATUS NOT IN ('ACTIVE', 'PENDING', 'OPEN', 'CLOSED', 'SETTLED', 'CANCELLED') AND DEL_FLAG = '0'
UNION ALL
SELECT '状态异常的记录: ' || COUNT(*)
FROM TBL_SWAP_TRANSACTION
WHERE STATUS NOT IN ('ACTIVE', 'PENDING', 'MATURED', 'CANCELLED') AND DEL_FLAG = '0';
