#系统上传的文件
uploadfilepath=/opt/ftp/uploadfile/
#系统通过发送自动生成的文件
sengfilepath=/opt/ftp/sengfile/

#流程图相关的xml文件
xmlfilepath=/opt/ftp/xmlfile/

#模板相关的文件
templatefilepath=/opt/ftp/templatefile/

#合同相关的文件
constractfilePath=/opt/ftp/constract/

systemImgFilePath=/opt/ftp/formimg/

pythonFlfgPaht=/opt/ftp/python/flfg/

#openoffice在本地的路径
openOfficePath=C:/Program Files (x86)/OpenOffice 4/
#openofficeurl
openOfficeip=127.0.0.1
#openoffice端口号
openOfficeport=8100

#ftp相关的配置
ftpip=127.0.0.1
username=ftpadmin
password=REDACTED
port=21

#ftpip=192.0.2.200
#username=ftpadmin
#password=123456
#port=21

#cmd 命令 cd 进入安装目录 C:\Program Files (x86)\OpenOffice 4\program
#openoffice window启动命令，启动成功后 会看到soffice.exe soffice.bin 进程
#soffice.exe -headless -accept="socket,host=127.0.0.1,port=8100;urp;" -nofirststartwizard

pythonFlfgPath=/python/flfg/


ssqHost=https://api.bestsign.info
clientId= 
clientSecret= 
privateKey=