
#企业画像
axnqyhx=http://192.0.2.200:9738/api2/huabo/companyFigure

#信用等级、信用得分
axnxydf=http://192.0.2.200:9738/api2/huabo/creditScore

#征信store（根据关键字查询企业列表 最多返回56条数据）
axnzx=http://192.0.2.200:9738/api2/huabo/searchCompany

#预警信息（工商数据是查询全部的，不支持按照日期查询，传递的开始日期和结束日期是查询司法信息的）
axnyjxx=http://192.0.2.200:9738/api2/huabo/warnInfo

#查看各类报告，返回报告的url 报告类型：（SWJCBGGK 商务基础报告公开版）（SWJCBG 商务基础报告收费版）
#（LXBG 立信报告）（SSDCBG 商事调查报告） （YJBG 预警报告) （GYSBG 供应商报告) （JXSBG 经销商报告 )）））
axnbg=http://192.0.2.200:9738/api2/huabo/reportUrl

#报告json数据（预警报告、供应商报告和经销商报告没有）
axnbgjson=http://192.0.2.200:9738/api2/huabo/reportData