
#上传文件
uploadfileurl=http://192.0.2.200:8035/V1/files/upload

#创建外部个人用户
createuserurl=http://192.0.2.200:8035/V1/accounts/outerAccounts/create

#查询内部机构信息
cxinnerurl=http://192.0.2.200:8035/V1/organizations/innerOrgans/query

#查询机构绑定监印员信息
cxjgxxurl=http://192.0.2.200:8035/V1/organizations/innerOrgans/queryHandler

#查询外部用户详情
cxuserurl=http://192.0.2.200:8035/V1/accounts/outerAccounts/query

#创建流程
createflowurl=http://192.0.2.200:8035/V1/signFlows/create

#获取签署流程文档下载地址
jqflowurl=http://192.0.2.200:8035/V1/signFlows/getSignFlowDocUrls