#端口
server:
 port: 8761

pring:
 application:
  name: hbyunEurekaServer

eureka:
 client:
  # 表示是否注册自身到eureka服务器，因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
  registerWithEureka: false
  # fetchRegistry表示是否从eureka服务器获取注册信息
  fetchRegistry: false
  # 表示eureka client间隔多久去拉取服务器注册信息,默认为30秒
  registry-fetch-interval-seconds: 30
  serviceUrl:
   # defaultZone就比较重要了，是设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址。
   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 
 server:
  # 是否开启保护模式，开发环境下关闭自我保护机制，保证不可用服务及时踢出，默认是 true，开启保护机制
  enableSelfPreservation: false
  # 清理不可用服务的间隔时间，默认是 60* 1000 （60秒）
  eviction-interval-timer-in-ms: 60000
 instance:
  # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
  preferIpAddress: true
  # 指定自己的ip信息，不指定的话会自己寻找
  ip-address: 127.0.0.1
  # 执行当前服务的应用ID  不可以重复  标识的是每一个具体的的服务
  instance-id: hbyuncloud-8761
  #地址
  hostname: 127.0.0.1

#配置登录用户名和密码
spring:
 security:
  user:
   name: hbyunadmin
   password: REDACTED
security:
 basic:
  enabled: false