#===================================PLUS
##Web服务的URL
#address=http://ekp.sz-expressway.com/sys/webservice/sysNotifyTodoWebService
##Web服务接口
#service_class=com.landray.kmss.sys.notify.webservice.ISysNotifyTodoWebService
##Web服务标识
#service_bean= 
##用户
#user=audit
##密码
#password= 

#====================================TEST
#Web\u670D\u52A1\u7684URL
address=http://ekptest.sz-expressway.com/sys/webservice/sysNotifyTodoWebService
#Web\u670D\u52A1\u63A5\u53E3
service_class=com.landray.kmss.sys.notify.webservice.ISysNotifyTodoWebService
#Web\u670D\u52A1\u6807\u8BC6
service_bean= 
#\u7528\u6237
user= 
#\u5BC6\u7801
password=REDACTED