#主数据平台访问IP：192.0.2.17  URL应设为可配置，因为测试环境的IP不是固定的
mainDataIP=http://192.0.2.17:9999

companyCode= 
sysCode= 
#objectType:1=公司和部门  2=人员
orgType=1
userType=2

getDepartUrl=/sysware/services/WSForSysnUsersAndDepts
getPositionUrl=/sysware/services/WSForSysnHR/WSForSysnHR.WSForSysnHRHttpSoap11Endpoint
getUserUrl=/sysware/services/WSForSysnUsersAndDepts
#主管领导
roleKeyWordsForG1:总经理,总工程师,总师,总会计师,董事长,主席,书记
#处长
roleKeyWordsForE:处长,主任,主持工作,经理
#科长
roleKeyWordsForC:部长,科长,主任,主持工作,科室正职

#上一次更新时间（增量更新需要添加此参数）
upTime=2025-07-01 08:00:00


#风控系统地址
loginUrl=http://127.0.0.1/


#门户系统IP
gwIp=http://127.0.0.1

#门户系统授权认证接口
gwAuthUrl=/api/qsaas-portal-404/public/oauth/authorize

#全量更新
gwsaveTask=/task/saveTask/public
#状态更新
gwchangeTaskStatus=/task/changeTaskStatus/public
#删除接口
gwdeleteTask=/task/deleteTask/public
#获取待办数字接口
gwcounttask=/task/counttask/public
#identity 唯一值
gwidentity="http-oabg-ddn-fkhfs"

#???
bigdataUrl1=http://127.0.0.1:28143/api/get/erp/bbmx
bigdataUrl2=http://127.0.0.1:28143/api/get/erp/vs202201
bigdataToken= 

#????????   ????????????
Fileurl = http://127.0.0.1/WebCore
getToknenIP = 192.0.2.15
#??Token ??
getToknenUrl = http://127.0.0.1:80/api/services/Org/UserLoginIntegrationByUserLoginName
IntegrationKey= 
#??token??????
isValidTokenToken = http://127.0.0.1:80/api/services/Org/CheckUserTokenValidity

