#\u5DE5\u4F5C\u6D41\u5BF9\u63A5\uFF1A
#
IP=http://127.0.0.1:89
#\u53C2\u6570\u662Fmodule \u548C file\u6D41\u7A0B\u6587\u4EF6
#\u6D41\u7A0B\u53D1\u5E03\u7684\u5730\u5740\uFF1Ahttp://127.0.0.1:8081/workFlow/process/deploy
fburl=http://127.0.0.1:89/workFlow/process/deploy

#\u542F\u52A8\u6D41\u7A0B\uFF1A
#http://127.0.0.1:8081/workFlow/process/start/{key}
#\u53C2\u6570\uFF1Atext  \u4F20\u6D41\u7A0B\u53D8\u91CF\u6570\u636E          key\uFF1A\u6D41\u7A0B\u56FE\u7684process\u7684id
qdurl=http://127.0.0.1:89/workFlow/process/start/


#\u67E5\u8BE2\u4EE3\u529E\u4EFB\u52A1    
#\u53C2\u6570  userId:\u542F\u52A8\u6D41\u7A0B\u7528\u6237\u7684id    groupId:\u6D41\u7A0B\u5BA1\u6279\u7EC4\u7684id    start:\u5206\u9875\u8D77\u59CB\u6570\u636E       pageSize:\u5206\u9875\u663E\u793A\u7684\u6761\u6570
rwurl=http://127.0.0.1:89/workFlow/process/todolist


#http://127.0.0.1:8081/workFlow/process//complete/{taskId}   \u6D41\u7A0B\u529E\u7406
#taskId:\u4EE3\u529E\u67E5\u8BE2\u8FD4\u56DE\u7684\u4EFB\u52A1id
blurl=http://127.0.0.1:89/workFlow/process/complete/


#http://127.0.0.1:8081/workFlow/process/runtime/picture/{processInstanceId}  \u6D41\u7A0B\u76D1\u63A7  
#processInstanceId\uFF1A\u4EE3\u529E\u67E5\u8BE2\u8FD4\u56DE\u7684processInstanceId\u503C
jkurl=http://127.0.0.1:89/workFlow/process/runtime/picture/


#http://127.0.0.1:8081/workFlow/process/runtime/getButtonsForTransition/{taskId} \u6D41\u7A0B\u8D70\u5411           
#taskId:\u4EE3\u529E\u67E5\u8BE2\u8FD4\u56DE\u7684\u4EFB\u52A1id
lczxurl=http://127.0.0.1:89/workFlow/process/runtime/getButtonsForTransition/


#\u5386\u53F2\u6D41\u7A0B\u5B9E\u4F8B
#http://127.0.0.1:8081/workFlow/process/history/queryprocessInstance
lslcslurl=http://127.0.0.1:89/workFlow/process/history/queryprocessInstance



#\u6D41\u7A0B\u5B9A\u4E49 
#http:/127.0.0.1:8081/workFlow/process/queryProcessDefinition   String processDefinitionKey,String processDefinitionId
lcdyurl=http://127.0.0.1:89/workFlow/process/queryProcessDefinition


#\u6D41\u7A0B\u5B9E\u4F8B
#http://127.0.0.1:8081/workFlow/process/runtime/queryProcessInstance
lcslurl=http://127.0.0.1:89/workFlow/process/runtime/queryProcessInstance



#\u5220\u9664\u6D41\u7A0B\u5B9A\u4E49  deploymentId  cascade true\u662F\u5F3A\u5236\u5220\u9664
sclcdy=http://127.0.0.1:89/workFlow/process/deleteProcessDefinition


#/runtime/deleteProcessInstance   processInstanceId deleteReason
sclcsl=http://127.0.0.1:89/workFlow/process/runtime/deleteProcessInstance


sxjm_suburl=http://127.0.0.1:8002/process/sxmt/tjsp_sjtbstring


sxjm_recordurl=http://127.0.0.1:8002/process/sxmt/cxalls

sxjm_entityurl=http://127.0.0.1:8002/process/sxmt/from

sxjm_blurl=http://127.0.0.1:8002/process/sxmt/blprocessstring

sxswglj_getkey=http://127.0.0.1:8080/sharedata/system/appinterface/getTime

acurl=http://127.0.0.1:8003

formurl=http://127.0.0.1:8001

redisurl=http://127.0.0.1:8379

wnaiUrl=http://127.0.0.1:8379
fin=http://127.0.0.1:8379
law=http://127.0.0.1:8379
doc=http://127.0.0.1:8379