#===================================================PLUS
#企业微信组织标识
qyweixin_corp_id= 
#企业微信组织密钥
qyweixin_corp_secret= 
#企业微信应用标识
qyweixin_agent_id= 
#企业微信接口前缀
qyweixin_url_prefix=https://qyapi.weixin.qq.com/cgi-bin
#企业微信访问令牌
qyweixin_get_token=/gettoken?corpid=CORPID&corpsecret=CORPSECRET
#企业微信消息发送
qyweixin_message_send=/message/send?access_token=ACCESS_TOKEN
#企业微信回调地址
call_back_url_prefix=http://sj.sz-expressway.com
#我的代办入口
call_back_url_wddb=/#/msg/wddb?token=TOKEN&v5ticket=mobile
#我的代办入口
call_back_url_reminder=/#/rectify/track?token=TOKEN&v5ticket=mobile
#消息内容模板
msg_temp=在智慧审计系统中，您有N条代办信息，请点击本消息进行审批
#系统设置微服务地址
setup_service_url=http://127.0.0.1:8763
#我的代办接口路径
wddb_url=/wddb/project_plan

#============================================TEST
##企业微信组织标识
#qyweixin_corp_id=
##企业微信组织密钥
#qyweixin_corp_secret=
##企业微信应用标识
#qyweixin_agent_id=
##企业微信接口前缀
#qyweixin_url_prefix=
##企业微信访问令牌
#qyweixin_get_token=
##企业微信消息发送
#qyweixin_message_send=
##企业微信回调地址
#call_back_url_prefix=
##我的代办入口
#call_back_url_wddb=
##消息内容模板
#msg_temp=
##系统设置微服务地址
#setup_service_url=
##我的代办接口路径
#wddb_url=


