##山西焦煤填报-工作流
sxjm_suburl=http://127.0.0.1:8002/process/sxmt/tjsp_sjtbstring

sxjm_recordurl=http://127.0.0.1:8002/process/sxmt/cxalls

sxjm_entityurl=http://127.0.0.1:8002/process/sxmt/from

sxjm_blurl=http://127.0.0.1:8002/process/sxmt/blprocessstring

sxjm_allrisk=http://127.0.0.1:8002/process/sxmt/allrisk

sxjm_xffxgl=http://127.0.0.1:8002/process/sxmt/xffxgl


sxjm_upfile=http://127.0.0.1:8002/process/sxmt/updafile

sxjm_deletefile=http://127.0.0.1:8002/process/sxmt/deletefile

sxjm_processDetail=http://127.0.0.1:8002/process/sxmt/processDetail

sxjm_tjsp_sctring=http://127.0.0.1:8002/process/sxmt/tjsp_sctring

sxjm_blprocessSc=http://127.0.0.1:8002/process/sxmt/blprocessSc




##山西焦煤填报-填报数据
sxjm_fromlisturl=http://127.0.0.1:8002/sxfxgl/selectriskList

sxjm_updateRiskurl=http://127.0.0.1:8002/sxfxgl/updateRiskList

sxjm_addriskurl=http://127.0.0.1:8002/sxfxgl/addriskList

sxjm_deleteurl=http://127.0.0.1:8002/sxfxgl/delete

sxjm_exporturl=http://127.0.0.1:8002/sxfxgl/expotList

sxjm_is_status=http://127.0.0.1:8002/sxfxgl/is_status

sxjm_importurl=http://127.0.0.1:8002/sxfxgl/importFxgl

sxjm_allrisklist=http://127.0.0.1:8002/sxfxgl/selecetallRiskList

sxjm_showallrisklist=http://127.0.0.1:8002/sxfxgl/selecetAllRiskListdetaile

sxjm_shrisklist=http://127.0.0.1:8002/sxfxgl/selecetshRiskList

sxjm_selecettwoRiskList=http://127.0.0.1:8002/sxfxgl/selecettwoRiskList

sxjm_selecetfrist=http://127.0.0.1:8002/sxfxgl/selecetfrist

sxjm_selecettwoscRiskList=http://127.0.0.1:8002/sxfxgl/selecettwoscRiskList

sxjm_select_allrisk=http://127.0.0.1:8002/sxfxgl/selecetAllRiskByFormId

sxjm_checksame_risknumber=http://127.0.0.1:8002/sxfxgl/checkSameRikeNumber

sxjm_selectbycount=http://127.0.0.1:8002/sxfxgl/selectbycount

sxjm_selectFxglBySelect=http://127.0.0.1:8002/sxfxgl/selectFxglBySelect

sxjm_selecetfristfrom=http://127.0.0.1:8002/sxfxgl/selecetfristfrom


##山西焦煤填报-风险分类
sxjm_selectrisk=http://127.0.0.1:8002/sxfxgl/allriskList

sxjm_bypanrent=http://127.0.0.1:8002/sxfxgl/byparent

sxjm_saverisk=http://127.0.0.1:8002/sxfxgl/saverisk

sxjm_deleterisk=http://127.0.0.1:8002/sxfxgl/deleterisk

sxjm_findone=http://127.0.0.1:8002/sxfxgl/onerisk

sxjm_exploreexcel=http://127.0.0.1:8002/sxfxgl/exploreRiskClassExcel


#山西焦煤报表
sxjm_riskcountListurl=http://127.0.0.1:8002/sxfxgl/riskcountList

#山西焦煤新增20191224
#统计图
sxjm_echartTheme=http://127.0.0.1:8002/sxfxgl/sxjm_echartTheme
#新审批列表页面
sxjm_fromlisturl1=http://127.0.0.1:8002/sxfxgl/selecetristfrom1
#新办理页面
sxjm_selecetfrist1=http://127.0.0.1:8002/sxfxgl/selecetfrist1

sxjm_selectExportRiskList=http://127.0.0.1:8002/sxfxgl/selectExportRiskList
