spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
   #数据库配置
  url: jdbc:dm://127.0.0.1:5236/SYSDBA?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  username: SYSDBA
  password: REDACTED
  driverClassName: dm.jdbc.driver.DmDriver
 druid: 
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatement: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall,log4j
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
 redis: 
  host: 127.0.0.1
  port: 6379
  password: REDACTED

#eureka服务注册中心配置
eureka:
 instance:
  ip-address: 127.0.0.1
  instance-id: hbyunFinance-8099
  prefer-ip-address: true
  hostname: hbyun-contract-service
 client:
  serviceUrl:
   defaultZone: http://hbyunadmin:REDACTED@127.0.0.1:8761/eureka
security:
 basic:
  enabled: false

# Swagger配置
swagger: 
 enabled: true
  # 是否开启swagger
  # 请求前缀
 pathMapping: 

logging: 
 level: 
  com: 
   huabo: 
    contract: 
     mapper: debug

fileUploadPath: http://127.0.0.1:80/api/file/file/upload