#doc.path=/home/hbfk/document/
#linux 文档路径
doc.path=/home/HBGRC/document/
image.url=http://127.0.0.1:8080/
file.path=C:\HBFK\PRO\www\apache-tomcat-7.0.65\webapps\ROOT\WEB-INF\
#审计项目列表查看权限(角色)
role.sjlbqx=审计责任人,审计负责人
role.fxyd=风险管理员
#空表示只查询当前公司否则查询集团
group.structure=集团

