#是否启用流程平台   0-启用 1-弃用
ymStatus=1

#流程平台用户默认密码
ymPassword=123456

#低代码开发平台数据库类型//源数据库连接类型，MySql、Oracle、sqlServer
dbType=MySql

dbMySqlDriver=com.mysql.cj.jdbc.Driver
mysqlUrl=jdbc:mysql://127.0.0.1:3306/jnpf_nacos_demo?characterEncoding=utf8&useSSL=true&useOldAliasMetadataBehavior=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
mysqlUser=root
mysqlPassword=HBGRC

dbOracleDriver=oracle.jdbc.driver.OracleDriver
oracleUrl=jdbc:oracle:thin:@127.0.0.1:1521:orcl
oracleUser=HBGRCTEST
oraclePassword=HBGRCTEST

#低代码开发平台调用路径
ymUrl=http://192.0.2.200:9100

#单点登录访问路径
loginUrl=/api/oauth/Login

saveOrgUrl=/