package com.huabo.know.mapper;

import org.apache.ibatis.annotations.Select;

import java.math.BigDecimal;
import java.util.Map;

/**
 * <p>
 * Mapper 接口
 * </p>
 *
 * @author huabo
 * @since 2022-04-27
 */
public interface YMFormDataMapper {

    @Select("SELECT CONTRACTID AS CONTRACTID,MATTERORG AS MATTERORG,ISBIGMATTER AS ISBIGMATTER,	CONTRACTNAME AS CONTRACTNAME,TCU.CONTRACTBD AS CONTRACTBD, CONTRACTNO AS CONTRACTNO,	CONTRACTMONEY AS CONTRACTMONEY,	DEPT.PKYMORGID AS CONTRACTDEPT,	TCU.STARTDATE AS STARTDATE,	TCU.ENDDATE AS ENDDATE,	TCU.CONTRACTITEM AS CONTRACTITEM,	TCU.CONTRACTTYPE AS CONTRACTTYPE,	TCU.CONTRACTDATETYPE AS CONTRACTDATETYPE,	BUDGET.BUDGETNAME AS CONTRACTXDFXINFO,	TCU.DCTYPE AS DCTYPE,	TCU.CONTRACTCHILDREN AS CONTRACTCHILDREN,	STAFF.PKYMSTAFFID AS CONTRACTSTAFF,	UNIT.PKYMORGID AS CONTRACTORG,	TCB.BANKACCOUNT AS BANKACCOUNT,	TCB.BANKKHYH AS BANKKHYH,	TCU.CONTRACTXZ AS CONTRACTXZ,	TCU.CONTRACTDATETYPE AS CONTRACTDATETYPE,	TCU.MONEYTYPE AS MONEYTYPE,	ENTRU.REALNAME AS REALNAME FROM TBL_CYHW_UNIT TCU	LEFT JOIN TBL_ORGANIZATION DEPT ON TCU.CONTRACTDEPT = DEPT.ORGID LEFT JOIN TBL_CYHW_PROJECTBUDGET BUDGET ON TCU.CONTRACTXDFXINFO = BUDGET.BUDGETID LEFT JOIN TBL_ORGANIZATION UNIT ON TCU.ZXUNIT = UNIT.ORGID LEFT JOIN TBL_STAFF STAFF ON TCU.CONTRACTSTAFF = STAFF.STAFFID LEFT JOIN TBL_COUNTERPART_BANKINFO TCB ON TCU.COUNTERPARTBANK = TCB.BANKID LEFT JOIN TBL_STAFF ENTRU ON TCU.ENTRUSTSTAFFID = ENTRU.STAFFID WHERE CONTRACTID = #{fromId} ")
    Map<String, Object> selectCyhwUnitMapById(Integer fromId) throws Exception;

    @Select("SELECT UNIT.CONTRACTNAME AS CONTRACTNAME,UNIT.CONTRACTNO AS CONTRACTNO,UNIT.CONTRACTTYPE AS CONTRACTTYPE,UNIT.CONTRACTMONEY AS CONTRACTMONEY,TCPB.BUDGETID AS BUDGETID,TCPB.PROJECTGOAL AS PROJECTGOAL, TCPB.COUNTERPARTCODE AS COUNTERPARTCODE, TCPB.COUNTERPARTHANK AS COUNTERPARTHANK,TCPB.CREATETIME AS CREATETIME FROM TBL_CYHW_PROJECTBUDGET TCPB LEFT JOIN TBL_CYHW_UNIT UNIT ON TCPB.RECORDPARENT = UNIT.CONTRACTID WHERE BUDGETID = #{fromId}")
    Map<String, Object> selectHTYYMapById(Integer fromId);

    @Select("SELECT CONTRACTID AS CONTRACTID , MATTERORG AS MATTERORG,ISBIGMATTER AS ISBIGMATTER  ,	CONTRACTNAME AS CONTRACTNAME,TCU.CONTRACTBD AS CONTRACTBD, CONTRACTNO AS CONTRACTNO,	CONTRACTMONEY AS CONTRACTMONEY,	DEPT.PKYMORGID AS CONTRACTDEPT,	TCU.STARTDATE AS STARTDATE,	TCU.ENDDATE AS ENDDATE,	TCU.CONTRACTITEM AS CONTRACTITEM,	TCU.CONTRACTTYPE AS CONTRACTTYPE,	TCU.CONTRACTDATETYPE AS CONTRACTDATETYPE,	BUDGET.BUDGETNAME AS CONTRACTXDFXINFO,	TCU.DCTYPE AS DCTYPE,	TCU.CONTRACTCHILDREN AS CONTRACTCHILDREN,	STAFF.PKYMSTAFFID AS CONTRACTSTAFF,	UNIT.PKYMORGID AS CONTRACTORG,	TCB.BANKACCOUNT AS BANKACCOUNT,	TCB.BANKKHYH AS BANKKHYH,	TCU.CONTRACTXZ AS CONTRACTXZ,	TCU.CONTRACTDATETYPE AS CONTRACTDATETYPE,	TCU.MONEYTYPE AS MONEYTYPE,	ENTRU.REALNAME AS REALNAME, TCU.CHANGETYPE AS CHANGETYPE,TCU.CHANGEDATE AS CHANGEDATE,TCU.CHANGEDESC AS CHANGEDESC FROM TBL_CYHW_UNIT TCU	LEFT JOIN TBL_ORGANIZATION DEPT ON TCU.CONTRACTDEPT = DEPT.ORGID LEFT JOIN TBL_CYHW_PROJECTBUDGET BUDGET ON TCU.CONTRACTXDFXINFO = BUDGET.BUDGETID LEFT JOIN TBL_ORGANIZATION UNIT ON TCU.ZXUNIT = UNIT.ORGID LEFT JOIN TBL_STAFF STAFF ON TCU.CONTRACTSTAFF = STAFF.STAFFID LEFT JOIN TBL_COUNTERPART_BANKINFO TCB ON TCU.COUNTERPARTBANK = TCB.BANKID LEFT JOIN TBL_STAFF ENTRU ON TCU.ENTRUSTSTAFFID = ENTRU.STAFFID WHERE CONTRACTID = #{fromId} ")
    Map<String, Object> selectCyhwUnitBGMapById(Integer fromId);

    @Select("SELECT BLACKTYPE AS BLACKTYPE,EFFECTDATE AS EFFECTDATE,BUDGETNAME AS BUDGETNAME,COUNTERPARTNO AS COUNTERPARTNO,PROJECTRISK AS PROJECTRISK,CRETIFICATENO AS CRETIFICATENO,TOTALTMONEY AS TOTALMONEY,PSTARTDATE AS PSTARTDATE,PENDDATE AS PENDDATE,PROJECTSTAGEGOAL AS PROJECTSTAGEGOAL,RESULTDESCRIPTION AS RESULTDESCRIPTION,CONTACTS AS CONTACTS,COUNTERPARTDESC AS COUNTERPARTDESC,SERVICETYPE AS SERVICETYPE FROM TBL_CYHW_PROJECTBUDGET WHERE BUDGETID = #{fromId}")
    Map<String, Object> selectHMDGLMapById(Integer fromId) throws Exception;

    @Select("SELECT  "
            + "	TNA.PLANID AS PLANID,  "
            + "	TNA.PLANCODE AS PLANCODE,  "
            + "	TNA.PLANNAME AS PLANNAME,  "
            + "	TNA.PALNYEAR AS PALNYEAR,  "
            + "	TNA.PLANTYPE AS PLANTYPE,  "
            + "	TNA.STARTTIME AS STARTTIME,  "
            + "	TNA.ENDTIME AS ENDTIME,  "
            + "	TNA.CREATETIME AS CREATETIME,  "
            + "	TS.PKYMSTAFFID AS REALNAME,  "
            + "	ORG.PKYMORGID AS AUDITORG   "
            + " FROM  TBL_NBSJ_AUDITPLAN TNA  "
            + "	LEFT JOIN TBL_STAFF TS ON TNA.CREATESTAFFID = TS.STAFFID  "
            + "	LEFT JOIN TBL_ORGANIZATION ORG ON TNA.AUDITORGID = ORG.ORGID "
            + " WHERE TNA.PLANID = #{fromId}")
    Map<String, Object> selectJHGLMapById(Integer fromId) throws Exception;

    @Select("SELECT TNP.PRJOECTNAME AS PROJECTNAME,	TNP.PROJECTTYPE AS PROJECTTYPE,	NVL( AUDITORG.ORGNAME, AUDITSTA.REALNAME ) AS AUDITOBJ,	TNP.PLANYEAR AS PLANYEAR,	TNP.AUDITTYPE AS AUDITTYPE,	TNP.PROJECTSOURCE AS PROJECTSOURCE,	TNP.STARTDATE AS STARTDATE,	TNP.ENDDATE AS ENDDATE,	PM.PKYMSTAFFID AS ITEMPM,	TNP.PRO_SJFS AS PROSJFS,	TNP.CNTTYPE AS CNTTYPE,	TNP.COSTS AS COSTS,	TNP.EXTERNALASSIG AS EXTERNALASSIG,	JBORG.PKYMORGID AS COSPOMSORDEPARTMENT,	TNP.IMPLEMENTAION AS IMPLEMENTAION,	TNP.AUDITREQUIREMENTS AS AUDITREQUIREMENTS,	TNP.IMPLEMENTAIONSTEPS AS IMPLEMENTAIONSTEPS,	TNP.PURPOSE AS PURPOSE,	TNP.SCOPES AS SCOPES,	TNP.PURSUANT AS PURSUANT FROM TBL_NBSJ_PROJECT TNP LEFT JOIN TBL_ORGANIZATION AUDITORG ON AUDITORG.ORGID = TNP.AUDITORG LEFT JOIN TBL_STAFF AUDITSTA ON AUDITSTA.STAFFID = TNP.AUDITSTAFFID	LEFT JOIN TBL_STAFF PM ON PM.STAFFID = TNP.PMID	LEFT JOIN TBL_ORGANIZATION JBORG ON JBORG.ORGID = TNP.COSPOMSORDEPARTMENT WHERE	TNP.PROJECTID = #{fromId}")
    Map<String, Object> selectXMGLMapById(Integer fromId);

    @Select("SELECT TFIA.INSTITUTIONAUDITID AS INSTITUTIONAUDITID,TFIA.MATTERSINFORMEDPERSONNEL AS MATTERSINFORMEDPERSONNEL,"
            + "	TFIA.MATTERSINSTRUCTIONS AS MATTERSINSTRUCTIONS,TFIA.HOSTDEPARTMENTOPINION AS HOSTDEPARTMENTOPINION,"
            + "	TFIA.RELATEDDEPARTMENTOPINION AS RELATEDDEPARTMENTOPINION,TFIA.TEAMLEADEROPINION AS TEAMLEADEROPINION,"
            + "	TFIA.FIRMLEADEROPINION AS FIRMLEADEROPINION,TFIA.CREATOR AS CREATOR,TFIA.CREATEDTIME AS CREATEDTIME"
            + "	FROM TBL_FWGL_INSTITUTION_AUDIT TFIA WHERE INSTITUTIONAUDITID = {fromId}")
    Map<String, Object> selectHTDLMapById(Integer fromId);

    @Select("SELECT "
            + "	TFIA.AUDITTYPE AS AUDITTYPE, "
            + "	TFIA.AUDITNAME AS AUDITNAME, "
            + "	TFIA.OPINIONNAME AS OPINIONNAME, "
            + "	TFIA.DRAFTADMINISTRATOROPINION AS DRAFTADMINISTRATOROPINION, "
            + "	TFIA.DRAFTDEPARTMENTOPINION AS DRAFTDEPARTMENTOPINION, "
            + "	TFIA.DEPARTMENTBELONGGROUPOPINION AS DEPARTMENTBELONGGROUPOPINION, "
            + "	TFIA.DRAFTDEPARTMENTOPINIONSUCK AS DRAFTDEPARTMENTOPINIONSUCK, "
            + "	TFIA.INSTITUTIONAUDITEXTID AS INSTITUTIONAUDITEXTID, "
            + "	TS.REALNAME AS REALNAME, "
            + "	(SELECT PKYMSTAFFID FROM TBL_STAFF WHERE  "
            + "	INSTR(','||ROLEIDSTRS||',', (SELECT ','||RID||',' FROM TBL_ROLE WHERE COMPANYID = #{orgid} AND RNAME = '合规管理员')) > 0 "
            + "	AND ORGID = TFIA.WORKUNIT ) AS COMPLIANCENAME, "
            + "	TOA.ORGNAME AS WORKUNIT "
            + " FROM "
            + "	TBL_FWGL_INSTITUTION_AUDIT TFIA "
            + "	LEFT JOIN TBL_STAFF TS ON TFIA.CREATOR = TS.STAFFID "
            + "	LEFT JOIN TBL_ORGANIZATION TOA ON TFIA.WORKUNIT = TOA.ORGID  "
            + " WHERE "
            + "	INSTITUTIONAUDITID = #{fromId}")
    Map<String, Object> selectZDSHMapById(Integer fromId, BigDecimal orgid);

    @Select("SELECT "
            + "	TFIA.AUDITTYPE AS AUDITTYPE, "
            + "	TFIA.AUDITNAME AS AUDITNAME, "
            + "	TFIA.OPINIONNAME AS OPINIONNAME, "
            + "	TFIA.MATTERSINFORMEDPERSONNEL AS MATTERSINFORMEDPERSONNEL, "
            + "	TFIA.MATTERSINSTRUCTIONS AS MATTERSINSTRUCTIONS, "
            + "	TFIA.HOSTDEPARTMENTOPINION AS HOSTDEPARTMENTOPINION, "
            + "	TFIA.RELATEDDEPARTMENTOPINION AS RELATEDDEPARTMENTOPINION, "
            + "	TFIA.TEAMLEADEROPINION AS TEAMLEADEROPINION, "
            + "	TFIA.FIRMLEADEROPINION AS FIRMLEADEROPINION, "
            + "	TFIA.CREATEDTIME AS CREATEDTIME, "
            + "	TS.REALNAME AS CREATOR, "
            + "	(SELECT PKYMSTAFFID  FROM TBL_STAFF  "
            + "	WHERE "
            + "	INSTR( ',' || ROLEIDSTRS || ',', ( SELECT ',' || RID || ',' FROM TBL_ROLE WHERE COMPANYID = #{orgid} AND RNAME = '合规管理员' ) ) > 0  "
            + "	AND ORGID = TFIA.WORKUNIT  ) AS COMPLIANCENAME, "
            + "	TOA.ORGNAME AS WORKUNITNAME  "
            + " FROM "
            + "	TBL_FWGL_INSTITUTION_AUDIT TFIA "
            + "	LEFT JOIN TBL_STAFF TS ON TFIA.CREATOR = TS.STAFFID "
            + "	LEFT JOIN TBL_ORGANIZATION TOA ON TFIA.WORKUNIT = TOA.ORGID  "
            + " WHERE "
            + "	INSTITUTIONAUDITID =  #{fromId}")
    Map<String, Object> selectJYSXSHMapById(Integer fromId, BigDecimal orgid);

    @Select("SELECT "
            + "	tst.REALNAME AS DISPUTEUNDERTAKERNAME, "
            + "	tld.DISPUTENO AS DISPUTENO, "
            + "	tld.DISPUTEITEM AS DISPUTEITEM, "
            + "	tld.DISPUTETYPE AS DISPUTETYPE, "
            + "	tld.DISPUTEID AS DISPUTEID, "
            + " CASE "
            + "		WHEN tld.ISUEGENT = '1' THEN "
            + "		'是' ELSE '否'  "
            + "	END AS ISUEGENT, "
            + "	tld.PLAINTIFF AS PLAINTIFF, "
            + " CASE "
            + "		WHEN tld.WHETHERSUED = '1' THEN "
            + "		'原告'  "
            + "		WHEN tld.WHETHERSUED = '2' THEN "
            + "		'被告' ELSE '第三人'  "
            + "	END AS LITIGATIONPOS, "
            + "	tld.DEFENDANT AS DEFENDANT, "
            + "	tld.ISUEGENT AS ISUEGENT, "
            + "	tld.DISPUTESTATUS AS DISPUTESTATUS, "
            + "	tld.DISPUTECOURS AS DISPUTECOURS, "
            + "	tld.SOLUTIONSUGGESTIONS AS SOLUTIONSUGGESTIONS, "
            + "	tld.URGENTMEMO AS URGENTMEMO, "
            + "	tld.LEGALEXAM AS LEGALEXAM, "
            + "	tld.COUNSELEXAM AS COUNSELEXAM, "
            + "	tld.CHAIRMANEXAM AS CHAIRMANEXAM, "
            + "	tld.GMANEXAM AS GMANEXAM, "
            + "	tld.LEGALEXAM AS LEGALEXAM, "
            + "	tcu.CONTRACTNAME AS CONTRACTNAME  "
            + " FROM "
            + "	TBL_LEGAL_DISPUTREGISTRATION tld "
            + "	LEFT JOIN TBL_STAFF tst ON tld.DISPUTEUNDERTAKER = tst.STAFFID "
            + "	LEFT JOIN TBL_CYHW_UNIT tcu ON tld.CONTRACTINFO = tcu.CONTRACTID"
            + " WHERE "
            + "	tld.DISPUTEID = #{fromId}")
    Map<String, Object> selectJFDJMapById(Integer fromId);

    @Select("SELECT "
            + "	TLN.COUNTERPART AS COUNTERPART, "
            + "	TLN.COUNTERPARTPHONE AS COUNTERPARTPHONE, "
            + "	TLN.NEGETIARESULT AS NEGETIARESULT, "
            + "	TLN.MEDIATIONSCHEME AS MEDIATIONSCHEME, "
            + "CASE "
            + "		WHEN TLN.ISAGGREE = '1' THEN "
            + "		'是' ELSE '否'  "
            + "	END AS ISAGGREE, "
            + "CASE "
            + "		WHEN TLN.ISPRESETCASE = '1' THEN "
            + "		'是' ELSE '否'  "
            + "	END AS ISPRESETCASE, "
            + "CASE "
            + "		WHEN TLN.SOLUTIONMODE = '1' THEN "
            + "		'私下调解' ELSE '司法调解'  "
            + "	END AS SOLUTIONMODE, "
            + "	TLD.DISPUTETYPE AS DISPUTETYPE, "
            + "	TLD.DISPUTEID AS DISPUTEID, "
            + "CASE "
            + "		WHEN TLD.ISUEGENT = '1' THEN "
            + "		'是' ELSE '否'  "
            + "	END AS ISUEGENT, "
            + "CASE "
            + "		WHEN TLD.WHETHERSUED = '1' THEN "
            + "		'原告'  "
            + "		WHEN TLD.WHETHERSUED = '2' THEN "
            + "		'被告' ELSE '第三人'  "
            + "	END AS LITIGATIONPOS, "
            + "	TLD.DISPUTEITEM AS DISPUTEITEM  "
            + " FROM "
            + "	TBL_LEGAL_NEGOTIATEDSETTLEMEN TLN "
            + "	LEFT JOIN TBL_LEGAL_DISPUTREGISTRATION TLD ON TLN.DISPUINFO = tld.DISPUTEID WHERE NEGOTIAID =#{fromId}")
    Map<String, Object> selectXSGCMapById(Integer fromId);

    @Select("SELECT  	TLAP.ANNUALPLANID AS ANNUALPLANID,TLAP.ANNUALPLANNAME AS ANNUALPLANNAME, "
            + "	TLAP.ANNUALPLANCREATOR AS ANNUALPLANCREATOR,"
            + "	TLAP.ANNUALPLANCREATEDTIME AS ANNUALPLANCREATEDTIME  FROM  TBL_FWGL_ANNUAL_PLAN TLAP "
            + "WHERE  ANNUALPLANID = #{fronId}")
    Map<String, Object> selectNDJHMapById(Integer fromId);

    @Select("SELECT  TC.PRACTICEAPPLYID AS PRACTICEAPPLYID,  TC.PRACTICEAPPLYNAME AS PRACTICEAPPLYNAME, "
            + "TC.SEX AS SEX,  TC.AGE AS AGE,  TC.NATION AS NATION,  TC.IDENTITYCARD AS IDENTITYCARD, "
            + "TC.POLITICSSTATUS AS POLITICSSTATUS,  TC.CERTIFICATIONNUMBER AS CERTIFICATIONNUMBER, "
            + "TC.PHONE AS PHONE,  TC.TECHNICALPOSITION AS TECHNICALPOSITION,  TC.AWARD AS AWARD, "
            + "TC.PUNISHMENT AS PUNISHMENT,  TS.REALNAME AS REALNAME FROM "
            + "	TBL_FWGL_PRACTICE_APPLY  TC  	LEFT JOIN TBL_STAFF TS ON TC.STAFFID = TS.STAFFID WHERE "
            + "	PRACTICEAPPLYID =#{ fromId }")
    Map<String, Object> selectZYSQMapById(Integer fromId);

    @Select("SELECT  "
            + "	ADVISERID AS ADVISERID,ADVISERNAME AS ADVISERNAME,BELONGGROUPID AS BELONGGROUPID, WORKUNITID AS WORKUNITID,"
            + "	POSITION AS POSITION,EMAIL AS EMAIL,SEX AS SEX,ITEMRANK AS ITEMRANK,FILLINPERSON AS FILLINPERSON,FILLINTIME AS FILLINTIME,"
            + "	AUDITPERSON AS AUDITPERSON,STATE AS STATE,ISHIRE AS ISHIRE,CERTIFICATENUMBER AS CERTIFICATENUMBER,"
            + "	MOBILEPHONE AS MOBILEPHONE,CREATEDTIME AS CREATEDTIME FROM  TBL_FWGL_LEGAL_ADVISER  WHERE 	ADVISERID = #{fromId}")
    Map<String, Object> selectZFLGWMapById(Integer fromId);

    @Select("SELECT  "
            + "	ORGANIZATIONNAME AS ORGANIZATIONNAME,  "
            + "	TOA.PKYMORGID AS BELONGGROUPID,  "
            + "	TOB.PKYMORGID AS WORKUNITNAME,  "
            + "	RESPONSIBLEPERSON AS RESPONSIBLEPERSON,  "
            + "	RESPONSIBLEPERSONPHONE AS RESPONSIBLEPERSONPHONE,  "
            + "	CONTACT AS CONTACT,  "
            + "	CONTACTMOBILEPHONE AS CONTACTMOBILEPHONE,  "
            + "	CONTACTEMAIL AS CONTACTEMAIL,  "
            + "	MAKINGPEOPLE AS MAKINGPEOPLE,  "
            + "	TS.PKYMSTAFFID AS AUDITPERSON,  "
            + "	AUDITTIME AS AUDITTIME,  "
            + "	STATE AS STATE "
            + " FROM  "
            + "	TBL_FWGL_LEGAL_ORGANIZATION TFL  "
            + "	LEFT JOIN TBL_ORGANIZATION TOA ON TFL.BELONGGROUPID = TOA.ORGID  "
            + "	LEFT JOIN TBL_ORGANIZATION TOB ON TFL.WORKUNITID = TOB.ORGID  "
            + "	LEFT JOIN TBL_STAFF TS ON TFL.AUDITPERSON = TS.STAFFID  WHERE ORGANIZATIONID = #{fromId}")
    Map<String, Object> selectFWJGJFZRMapById(Integer fromId);

    @Select("SELECT "
            + "	TFLP.PERSONNELID AS PERSONNELID, "
            + "	TFLP.PERSONNELNAME AS PERSONNELNAME, "
            + "	TFLP.BELONGGROUPID AS BELONGGROUPID, "
            + "	TFLP.PHONE AS PHONE, "
            + " CASE "
            + "		WHEN TFLP.SEX = '1' THEN "
            + "		'男' ELSE '女' "
            + "	END SEX, "
            + "	TFLP.JOBNATURE AS JOBNATURE, "
            + "	TFLP.POSITION AS POSITION, "
            + "	TFLP.BIRTHDAY AS BIRTHDAY, "
            + "	TFLP.JOBNATURE AS JOBNATURE, "
            + "	TFLP.IDENTITYCARD AS IDENTITYCARD, "
            + "	TFLP.STARTWORKTIME AS STARTWORKTIME, "
            + "	TFLP.POLITICSSTATUS AS POLITICSSTATUS, "
            + "	TFLP.DEGREE AS DEGREE, "
            + "	TFLP.DUTY AS DUTY, "
            + "	TFLP.DUTYTITLE AS DUTYTITLE, "
            + "	TFLP.STARTWORKTIME AS STARTWORKTIME, "
            + "	TFLP.STARTYEAR AS STARTYEAR, "
            + " CASE "
            + "		WHEN TFLP.EDUCATION = '1' THEN '博士研究生' "
            + "		WHEN TFLP.EDUCATION = '2' THEN '硕士研究生' "
            + "		WHEN TFLP.EDUCATION = '3' THEN '大学本科' "
            + "		WHEN TFLP.EDUCATION = '4' THEN '大学专科' "
            + "		WHEN TFLP.EDUCATION = '5' THEN '中专' "
            + "		WHEN TFLP.EDUCATION = '6' THEN '大学及以下' "
            + "	END EDUCATION, "
            + " CASE "
            + "		WHEN TFLP.ISLAWSPECIALTY = '1' THEN "
            + "		'是' ELSE '否' "
            + "	END ISLAWSPECIALTY, "
            + " CASE "
            + "	WHEN TFLP.ISLAWOCCUPATIONAL = '1' THEN "
            + "	'是' ELSE '否' "
            + "	END ISLAWOCCUPATIONAL, "
            + "	TFLP.QUALIFICATIONS AS QUALIFICATIONS, "
            + " CASE "
            + "		WHEN TFLP.ISLAWADVISER = '1' THEN "
            + "		'是' ELSE '否' "
            + "	END ISLAWADVISER, "
            + "	TFLP.CERTIFICATIONNUMBER AS CERTIFICATIONNUMBER, "
            + "	TFLP.GRADUATIONGRADUATE AS GRADUATIONGRADUATE, "
            + "	TFLP.STARTHIRETIME AS STARTHIRETIME, "
            + "	TFLP.ENDHIRETIME AS ENDHIRETIME, "
            + "	TS.PKYMSTAFFID AS AUDITPERSONNAME, "
            + "	TFLP.AUDITTIME AS AUDITTIME, "
            + "	TFLP.FILLINTIME AS FILLINTIME, "
            + "	TS.REALNAME AS CREATORNAME, "
            + "	TOA.PKYMORGID AS BELONGGROUPNAME, "
            + "	TOB.PKYMORGID AS WORKUNITNAME "
            + " FROM "
            + "	TBL_FWGL_LEGAL_PERSONNEL TFLP "
            + "	LEFT JOIN TBL_ORGANIZATION TOA ON TFLP.BELONGGROUPID = TOA.ORGID "
            + "	LEFT JOIN TBL_ORGANIZATION TOB ON TFLP.WORKUNITID = TOB.ORGID "
            + "	LEFT JOIN TBL_STAFF TS ON TFLP.CREATOR = TS.STAFFID "
            + "	LEFT JOIN TBL_STAFF TSA ON TFLP.AUDITPERSON = TS.STAFFID WHERE	PERSONNELID = #{fromId}")
    Map<String, Object> selectFWRYMapById(Integer fromId);

    @Select("SELECT   "
            + "	TFOFM.OTHERFILEMESSAGEID AS OTHERFILEMESSAGEID,  "
            + "	TFOFM.FILENAME AS FILENAME,  "
            + "	TFOFM.CREATEDTIME AS CREATEDTIME,  "
            + "	TFOFM.STATE AS STATE,  "
            + "	TFOFM.CONTENT AS CONTENT,  "
            + "	TS.PKYMSTAFFID AS OTHERFILEMESSAGECREATOR   "
            + " FROM  "
            + "	TBL_FWGL_OTHER_FILE_MESSAGE TFOFM  "
            + "	LEFT JOIN TBL_STAFF TS ON TFOFM.CREATOR = TS.STAFFID "
            + " WHERE "
            + "	OTHERFILEMESSAGEID =#{fromId}")
    Map<String, Object> selectQTWJBSMapById(Integer fromId);

    @Select("SELECT "
            + "	TNP.PROJECTID AS PROJECTID, "
            + "	TNP.PROJECTCODE AS PROJECTCODE, "
            + "	TNP.PRJOECTNAME AS PRJOECTNAME, "
            + "	TNP.PROJECTTYPE AS PROJECTTYPE, "
            + "	TS.PKYMSTAFFID AS PMID, "
            + "	TSA.PKYMSTAFFID AS AUDITSTAFFNAME, "
            + "	TNP.PLANYEAR AS PLANYEAR, "
            + "	TNP.AUDITTYPE AS AUDITTYPE, "
            + "	TNP.PROJECTSOURCE AS PROJECTSOURCE, "
            + "	TNP.CNTTYPE  AS CNTTYPE, "
            + "	TNP.STARTDATE AS STARTDATE, "
            + "	TNP.PRO_SJFS AS PRO_SJFS, "
            + "	TNP.COSTS AS COSTS, "
            + "	CASE  "
            + "	  WHEN TNP.EXTERNALASSIG = '1' THEN '是'"
            + "  ELSE '否' END  AS EXTERNALASSIG, "
            + "	TNP.TEMPID AS TEMPID, "
            + "	TNP.IMPLEMENTAION AS IMPLEMENTAION, "
            + "	TOG.PKYMORGID AS COSPOMSORDEPARTMENT, "
            + "	TSAA.PKYMSTAFFID AS COSPOMSORDEPARTMENTSTAFFID, "
            + "	TNP.AUDITREQUIREMENTS AS AUDITREQUIREMENTS, "
            + "	TNP.IMPLEMENTAIONSTEPS AS IMPLEMENTAIONSTEPS, "
            + "	TNP.PURPOSE AS PURPOSE, "
            + "	TNP.SCOPES AS SCOPES, "
            + "	TNP.PURSUANT AS PURSUANT, "
            + "	TNP.COMMENTS AS COMMENTS, "
            + "	TNP.PRO_DESC AS PRO_DESC  "
            + " FROM "
            + "	TBL_NBSJ_PROJECT TNP "
            + "	LEFT JOIN TBL_STAFF TS ON TNP.PMID = TS.STAFFID "
            + "	LEFT JOIN TBL_STAFF TSA ON TNP.AUDITSTAFFID = TSA.STAFFID "
            + "	LEFT JOIN TBL_STAFF TSAA ON TNP.COSPOMSORDEPARTMENTSTAFFID = TSAA.STAFFID "
            + "	LEFT JOIN TBL_ORGANIZATION TOG ON TNP.COSPOMSORDEPARTMENT = TOG.ORGID"
            + " WHERE TNP.PROJECTID = #{fromId} ")
    Map<String, Object> selectSJXMGLapById(Integer fromId);

    @Select("SELECT "
            + "	tnc.CERTIFICATEID AS CERTIFICATEID,"
            + "	tnc.AUDITABSTRACT AS AUDITABSTRACT,"
            + "	tnc.EVIDENCEOPINION AS EVIDENCEOPINION,"
            + "	tnc.CERTIFICATEDATE AS CERTIFICATEDATE,"
            + "	tszbsj.PKYMSTAFFID AS ASSISTEDZBUSER,"
            + "	tsfgld.PKYMSTAFFID AS ASSISTEDFGLD,"
            + "	tsbmfzr.PKYMSTAFFID AS ASSISTEDBMFZR,"
            + "	tsyjfh.PKYMSTAFFID AS YJFH,"
            + "	tsejfh.PKYMSTAFFID AS EJFH,"
            + "	zjtgz.PKYMSTAFFID AS CERTIFICATEUSER,"
            + "	tnc.AUDITMATTER AS AUDITMATTER,"
            + "	tnc.AUDITUSERID AS AUDITUSERID,"
            + "	tnc.CREATEDATE AS CREATEDATE,"
            + "	tnp.PRJOECTNAME AS PROJECTNAME,"
            + "	ts.PKYMSTAFFID AS AUDITUSERNAME "
            + " FROM"
            + "	TBL_NBSJ_CERTIFICATE tnc"
            + "	LEFT JOIN TBL_NBSJ_PROJECT tnp ON tnc.PROJECTID = tnp.PROJECTID"
            + "	LEFT JOIN TBL_STAFF ts ON tnc.AUDITUSERID = ts.STAFFID"
            + "	LEFT JOIN TBL_STAFF tsbmfzr ON tnc.ASSISTEDBMFZRID = tsbmfzr.STAFFID"
            + "	LEFT JOIN TBL_STAFF tsfgld ON tnc.ASSISTEDFGLDID = tsfgld.STAFFID"
            + "	LEFT JOIN TBL_STAFF tszbsj ON tnc.ASSISTEDZBUSERID = tszbsj.STAFFID "
            + "	LEFT JOIN TBL_STAFF tsyjfh ON tnc.FIRSTSTAFFID = tsyjfh.STAFFID"
            + "	LEFT JOIN TBL_STAFF tsejfh ON tnc.SECONDSTAFFID = tsejfh.STAFFID "
            + "	LEFT JOIN TBL_STAFF zjtgz ON tnc.CERTIFICATESTAFFID = zjtgz.STAFFID "
            + " WHERE"
            + "	tnc.CERTIFICATEID = #{ fromId}")
    Map<String, Object> selectSJQZDMapById(Integer fromId);

    @Select("SELECT "
            + "	TNS.SHEETID AS SHEETID, "
            + "	TNS.SHEETCODE AS SHEETCODE, "
            + "	TNS.SHEETNAME AS SHEETNAME, "
            + "	TNS.CREATESTAFF AS CREATESTAFF, "
            + "	TNS.CREATETIME AS CREATETIME, "
            + "	TNS.PROJECTID AS PROJECTID, "
            + "	TNS.UPDATETIME AS UPDATETIME, "
            + "	TNS.RISKATTRBUTION AS RISKATTRBUTION, "
            + "	TNS.BUSINESSAFFILIATION AS BUSINESSAFFILIATION, "
            + "	TNS.AUDITCOURSE AS AUDITCOURSE, "
            + "	TNS.AUDITDISCOVERABLE AS AUDITDISCOVERABLE, "
            + "	TNS.APPROVER AS APPROVER, "
            + "	TNS.RISKLEVEL AS RISKLEVEL, "
            + "	TNS.QUESTITLE AS QUESTITLE, "
            + "	TNS.TARGETNAME AS TARGETNAME, "
            + "	TNS.BUSINESSTYPE AS BUSINESSTYPE, "
            + "	TNS.BELONGTYPE AS BELONGTYPE, "
            + "	TNS.NOZGREASION AS NOZGREASION, "
            + "	TNS.HGDETAILTYPE AS HGDETAILTYPE, "
            + "	TNS.PROCATEGORIES AS PROCATEGORIES, "
            + "	TNS.INTERNALTYPE AS INTERNALTYPE, "
            + "	TSA.PKYMSTAFFID AS REALNAME, "
            + "	ts.PKYMSTAFFID AS YJFH, "
            + "	tsej.PKYMSTAFFID AS EJFH "
            + "	FROM TBL_NBSJ_SHEET TNS  "
            + "	LEFT JOIN TBL_STAFF ts ON TNS.FIRSTSTAFFID = ts.STAFFID  "
            + "	LEFT JOIN TBL_STAFF tsej ON TNS.SECONDSTAFFID = tsej.STAFFID "
            + "	LEFT JOIN TBL_STAFF TSA ON TNS.auditstaffid = TSA.STAFFID "
            + "	WHERE "
            + "	TNS.SHEETID = #{fromId} ")
    Map<String, Object> selectWDDGMapById(Integer fromId);

    @Select("SELECT "
            + "	s.JYKID AS JYKID, "
            + "	s.TATLE AS TATLE, "
            + "	s.CODE AS CODE, "
            + "	s.EXPERIENCETYPE AS EXPERIENCETYPE, "
            + "	s.EXPERIENCETATLE AS EXPERIENCETATLE, "
            + "	s.OVERVIEW AS OVERVIEW, "
            + "	s.JYKID AS JYKID, "
            + "	STA.PKYMSTAFFID AS REALNAME "
            + " FROM "
            + "	TBL_NBSJ_SJJYK s "
            + "	LEFT JOIN TBL_STAFF sta ON s.STAFFID = STA.STAFFID  WHERE JYKID = #{fromId}")
    Map<String, Object> selectSJJYKMapById(Integer fromId);

    @Select("SELECT  "
            + "	S.SOLUTIONID AS SOLUTIONID,  "
            + "	S.SOLUTIONCODE AS SOLUTIONCODE,  "
            + "	S.SOLUTIONNAME AS SOLUTIONNAME,  "
            + "	S.ZGSTATUS AS ZGSTATUS,  "
            + "	S.CREATEDATE AS CREATEDATE,  "
            + "	S.ENDDATE AS ENDDATE,  "
            + "	S.RUNSTATUS AS RUNSTATUS,  "
            + "	S.MEMO AS MEMO,  "
            + "	STA.PKYMSTAFFID AS REALNAME,  "
            + "	ST.PKYMSTAFFID AS REFORMUSERID,  "
            + "	PR.PROJECTID AS PROJECTID,  "
            + "	PR.PRJOECTNAME AS PRJOECTNAME,  "
            + "	S.BSJDWZFR AS BSJDWZFR,  "
            + "	STF.PKYMSTAFFID AS BSJDWZRRID,  "
            + "	STFA.PKYMSTAFFID AS PMID  "
            + " FROM  "
            + "	TBL_NBSJ_REFORM_SOLUTION S  "
            + "	LEFT JOIN TBL_NBSJ_PROJECT PR ON S.PROJECTID = PR.PROJECTID  "
            + "	LEFT JOIN TBL_STAFF STA ON S.STAFFID = STA.STAFFID  "
            + "	LEFT JOIN TBL_STAFF ST ON S.REFORMUSERID = ST.STAFFID  "
            + "	LEFT JOIN TBL_STAFF STF ON S.BSJDWZRRID = STF.STAFFID   "
            + "	LEFT JOIN TBL_STAFF STFA ON S.PMID = STFA.STAFFID  "
            + " WHERE"
            + "	SOLUTIONID =  #{fromId}")
    Map<String, Object> selectZGLSMapById(Integer fromId);

    @Select("SELECT "
            + "	SS.STAFFSCORE_ID AS STAFFSCORE_ID,"
            + "	ts.REALNAME AS REALNAME,"
            + "	TP.PRJOECTNAME AS AUDITPROJECTNAME,"
            + "	TSF.PKYMSTAFFID AS PMID"
            + " FROM"
            + "	TBL_NBSJ_STAFFSCORE SS"
            + "	LEFT JOIN TBL_STAFF TS ON SS.AUDITORS = TS.STAFFID"
            + "	LEFT JOIN TBL_NBSJ_PROJECT TP ON TP.PROJECTID = SS.PROJECTID "
            + "	LEFT JOIN TBL_STAFF TSF ON TP.PMID= TSF.STAFFID"
            + " WHERE "
            + "	STAFFSCORE_ID = #{fromId}")
    Map<String, Object> selectPJGLMapById(Integer fromId);

    @Select("SELECT "
            + "CASE  "
            + "	WHEN TS.PERSONTYPE = '0' THEN '审计中心人员' "
            + "	WHEN TS.PERSONTYPE = '1' THEN '外聘人员' "
            + "	WHEN TS.PERSONTYPE = '2' THEN '临时借调人员' "
            + " END  AS PERSONTYPE, "
            + " TS.PKYMSTAFFID AS REALNAME, "
            + " TS.MIBLEPHONE AS MIBLEPHONE, "
            + " TS.BIRTHDAY AS BIRTHDAY, "
            + " TS.POLITICALOUTLOOK AS POLITICALOUTLOOK, "
            + " TS.EDUCATION AS EDUCATION, "
            + " TS.MAJOR AS MAJOR, "
            + " TS.SCHOOL AS SCHOOL, "
            + " TS.OFFICEPHONE AS OFFICEPHONE, "
            + " TS.WORKTIME AS WORKTIME, "
            + " TS.AUDITORTYPE AS AUDITORTYPE, "
            + " TS.ISAUDIT AS ISAUDIT, "
            + " TS.PERSONTYPE AS PERSONTYPE, "
            + " TS.GENDER AS GENDER, "
            + " TS.JOBEXPERIENCES AS JOBEXPERIENCES, "
            + " TS.MEMO AS MEMO, "
            + " TS.TITLE AS TITLE, "
            + " TS.QUALIFICATION AS QUALIFICATION, "
            + " TOR.ORGNAME AS ORGNAME, "
            + " TOR.ORGMENO AS ORGMENO  "
            + " FROM "
            + " TBL_STAFF TS  "
            + "	LEFT JOIN TBL_ORGANIZATION TOR ON TOR.ORGID = TS.ORGID"
            + "	WHERE"
            + "	TS.STAFFID = #{fromId} ")
    Map<String, Object> selectSJRNGLMapById(Integer fromId);

    @Select("SELECT TLE.DISPUTENAME AS DISPUTENAME,TLE.EXECUNO AS EXECUNO,TLE.EXECUCOURT AS EXECUCOURT,"
            + "TLE.EXECUTYPE AS EXECUTYPE,TLE.EXECUEDAMOUNT AS EXECUEDAMOUNT,"
            + "TLE.NOEXECUAMOUNT AS NOEXECUAMOUNT,TLE.LITIGATIONID AS LITIGATIONID,"
            + "TLE.ARBITRAID AS ARBITRAID,TLE.CREATETIME AS CREATETIME,TLE.CREATESTAFFID AS CREATESTAFFID,"
            + "TS.REALNAME AS USERNAME FROM TBL_LEGAL_EXECUMGR TLE"
            + " LEFT JOIN TBL_STAFF  ts ON TLE.CREATESTAFFID = ts.STAFFID WHERE ID = #{ fromId}")
    Map<String, Object> selectZXGLMapById(Integer fromId);

    @Select("SELECT TLP.PROCEEDNO AS PROCEEDNO,TLP.PROCEEDID AS PROCEEDID,"
            + "TLP.PORCEEDSTAGE AS PORCEEDSTAGE,TLP.COURT AS COURT,TLP.COURTLINK AS COURTLINK,"
            + "TLP.COURTCONTACT AS COURTCONTACT,TLP.FILINGTIME AS FILINGTIME,"
            + "TLP.PAYMENTREMINDTIME AS PAYMENTREMINDTIME,TLP.OPENINGTIME AS OPENINGTIME,"
            + "TLP.JUDGETIEM AS JUDGETIEM,TLP.ISEXTERNALLAWYER AS ISEXTERNALLAWYER,"
            + "TLP.CREATETIME AS CREATETIME,TLP.CASEPROMOTION AS CASEPROMOTION,"
            + "TLP.EXISTINGDIFFICULTIES AS EXISTINGDIFFICULTIES,ts.REALNAME AS REALNAME,"
            + "TLP.MEASURESPROMOTE AS MEASURESPROMOTE FROM TBL_LEGAL_PROCEEDINGSRECORD TLP"
            + " LEFT JOIN TBL_STAFF  ts ON TLP.CREATESTAFF = ts.STAFFID WHERE PROCEEDID = #{fromId}")
    Map<String, Object> selectSSHZSMapById(Integer fromId);

    @Select("SELECT	TNB.STATUS AS STATUS,	TNB.CREATEDATE AS CREATEDATE,"
            + "	TNB.RETURNDATE AS RETURNDATE,	TNB.BORROWID AS BORROWID,	TNB.MEMO AS MEMO,"
            + "	TNP.PROJECTID AS PROJECTID,	TNP.PRJOECTNAME AS PRJOECTNAME,"
            + "	TNP.PROJECTCODE AS PROJECTCODE 	FROM	TBL_NBSJ_BORROWRECORD TNB"
            + "	LEFT JOIN TBL_NBSJ_PROJECT TNP ON TNB.PROJECTID = TNP.PROJECTID  WHERE 	BORROWID = #{fromId}")
    Map<String, Object> selectDAJYMapById(Integer fromId);

    @Select("SELECT  "
            + "	TLP.POPULARIZELAWPLANNAME AS POPULARIZELAWPLANNAME,  "
            + "	TLP.CREATEDTIME AS CREATEDTIME,  "
            + "	TLP.PLANYEAR AS PLANYEAR,  "
            + "	TS.PKYMSTAFFID AS CREATOR  "
            + " FROM  "
            + "	TBL_FWGL_POPULARIZE_LAW_PLAN TLP  "
            + "	LEFT JOIN TBL_STAFF TS ON TS.STAFFID = TLP.CREATOR  "
            + " WHERE  "
            + "	TLP.POPULARIZELAWPLANID = #{fromId}")
    Map<String, Object> selectPFJHMapById(Integer fromId);

    @Select("SELECT TC.TRANID AS TRANID, "
            + "TC.LEGALMEMO AS LEGALMEMO, "
            + "TC.TRANSTATUS AS TRANSTATUS, "
            + "TC.CONTRACTNAME AS CONTRACTNAME, "
            + "TC.CONTRACTNO AS CONTRACTNO, "
            + "TC.CONTRACTID AS CONTRACTID, "
            + "TC.CONTRACTCNT AS CONTRACTCNT, "
            + "TS.PKYMSTAFFID AS HANDSTAFFNAME, "
            + "ORG.PKYMORGID AS TRANORGNAME, "
            + "DORG.PKYMORGID AS HANDDEPTNAME "
            + "FROM TBL_CONTRACT_TRAN  TC  "
            + "LEFT JOIN TBL_STAFF TS ON TS.STAFFID = TC.HANDSTAFFID "
            + "LEFT JOIN TBL_ORGANIZATION ORG ON ORG.ORGID = TC.TRANORGID "
            + "LEFT JOIN TBL_ORGANIZATION DORG ON DORG.ORGID = TC.HANDDEPTID "
            + "WHERE TC.TRANID = #{fromId}")
    Map<String, Object> selectHTYJMapById(Integer fromId);

    @Select("SELECT  "
            + " TF.ANNUALEXAMINEID AS ANNUALEXAMINEID,"
            + " TF.ANNUALEXAMINENAME AS ANNUALEXAMINENAME,"
            + " TF.TYPE AS TYPE,"
            + " TF.EXAMINETIME AS EXAMINETIME,"
            + " TS.PKYMSTAFFID AS ANNUALEXAMINECREATOR   "
            + " FROM TBL_FWGL_ANNUAL_EXAMINE TF "
            + " LEFT JOIN TBL_STAFF TS ON TS.STAFFID = TF.CREATOR "
            + " WHERE TF.ANNUALEXAMINEID = #{fromId}")
    Map<String, Object> selectNDKHMapById(Integer fromId);

    @Select("SELECT " +
            "TCPL.ID, " +
            "TCPL.STAFFID, " +
            "TCPL.STAFFNUMBER, " +
            "TCPL.LEAVEPERIODTIMESTART, " +
            "TCPL.LEAVEPERIODTIMEEND, " +
            "TCPL.LEAVEREASON, " +
            "TCPL.REMARK, " +
            "TCPL.STATE, " +
            "TCPL.CREATOR, " +
            "TCPL.WORKUNIT, " +
            "TCPL.BELONGGROUP, " +
            "TCPL.CREATEDTIME, " +
            "TCPL.UPDATEDTIME " +
            "FROM " +
            "TBL_CEA_PEOPLE_LEAVE TCPL " +
            "WHERE TCPL.ID = #{fromId}")
    Map<String, Object> selectRYQJDById(Integer fromId);


    @Select("SELECT " +
            "TCSF.ID, " +
            "TCSF.SEALNAME, " +
            "TCSF.SEALREASONS, " +
            "TCSF.SEALNUM, " +
            "TCSF.SEALWORKUNIT, " +
            "TCSF.TRANSACTOR, " +
            "TCSF.AUDITWORKUNIT, " +
            "TCSF.REMARK, " +
            "TCSF.FILEIDS, " +
            "TCSF.STATE, " +
            "TCSF.CREATOR, " +
            "TCSF.WORKUNIT, " +
            "TCSF.BELONGGROUP, " +
            "TCSF.CREATEDTIME, " +
            "TCSF.UPDATEDTIME " +
            "FROM TBL_CEA_SEAL_FORM TCSF" +
            "WHERE TCSF.ID = #{fromId}")
    Map<String, Object> selectYXSYDById(Integer fromId);

    @Select("SELECT " +
            "TCAA.ID, " +
            "TCAA.ASSETMGTID, " +
            "TCAA.QUANTITY, " +
            "TCAA.USEAGETIME, " +
            "TCAA.UTILITYAGETIME, " +
            "TCAA.USEBELONGGROUP, " +
            "TCAA.ORIGINALBELONGGROUP, " +
            "TCAA.ORIGINALUSEBELONGGROUP, " +
            "TCAA.STAYADJUSTEDBELONGGROUP, " +
            "TCAA.ORIGINALVALUE, " +
            "TCAA.REMARK, " +
            "TCAA.FILEIDS, " +
            "TCAA.STATE, " +
            "TCAA.CREATOR, " +
            "TCAA.WORKUNIT, " +
            "TCAA.BELONGGROUP, " +
            "TCAA.CREATEDTIME, " +
            "TCAA.UPDATEDTIME " +
            "FROM TBL_CEA_ASSET_ADJUSTMENT TCAA" +
            "WHERE TCAA.ID = #{fromId}")
    Map<String, Object> selectZCTJSQById(Integer fromId);

    @Select("SELECT " +
            "TCOE.ID, " +
            "TCOE.REASON, " +
            "TCOE.DETAILS, " +
            "TCOE.AMOUNT, " +
            "TCOE.SUPPLYBELONGGROUP, " +
            "TCOE.OFFICEEXPENSESTIME, " +
            "TCOE.TRANSACTOR, " +
            "TCOE.DEPARTMENTHEAD, " +
            "TCOE.FILEIDS, " +
            "TCOE.STATE, " +
            "TCOE.CREATOR, " +
            "TCOE.WORKUNIT, " +
            "TCOE.BELONGGROUP, " +
            "TCOE.CREATEDTIME, " +
            "TCOE.UPDATEDTIME " +
            "FROM TBL_CEA_OFFICE_EXPENSES TCOE" +
            "WHERE TCOE = #{fromId}")
    Map<String, Object> selectBGJYZCById(Integer fromId);

    @Select("SELECT " +
            "TCRE.ID, " +
            "TCRE.REPAIRBELONGGROUP, " +
            "TCRE.VIN, " +
            "TCRE.REPAIRTIME, " +
            "TCRE.AMOUNT, " +
            "TCRE.REPAIRMANUFACTURER, " +
            "TCRE.TRANSACTOR, " +
            "TCRE.FAULTCONDITION, " +
            "TCRE.REPAIRPROJECT, " +
            "TCRE.STATE, " +
            "TCRE.CREATOR, " +
            "TCRE.WORKUNIT, " +
            "TCRE.BELONGGROUP, " +
            "TCRE.CREATEDTIME, " +
            "TCRE.UPDATEDTIME " +
            "FROM TBL_CEA_REPAIR_EXPENSES TCRE" +
            "WHERE TCRE = #{fromId}")
    Map<String, Object> selectXLFZCById(Integer fromId);

    //===================================================风险管控BEGIN
    @Select("SELECT TR.RISKID AS RISKID, "
            + "TR.RISKNUMBER AS RISKNUMBER, "
            + "TR.RISKNAME AS RISKNAME, "
            + "TR.RISKDES AS RISKDES, "
            + "TR.BELONGSTO AS BELONGSTO, "
            + "TR.MEMO AS MEMO, "
            + "TR.RISKCATID AS RISKCATID, "
            + "TR.VERSION AS VERSION, "
            + "TR.UNIT AS UNIT, "
            + "TR.REORG AS REORG, "
            + "TR.RISKCREATEDT AS RISKCREATEDT, "
            + "TR.YDUSERID AS YDUSERID, "
            + "TR.RISKPROGRAM AS RISKPROGRAM, "
            + "TR.RISKLEVEL AS RISKLEVEL, "
            + "TR.STATUS AS STATUS, "
            + "TRC.RISKCATNAME AS RISKCATNAME, "
            + "ZRBM.ORGNAME AS ZRBMNAME "
//				+ "TCM.CONMATID AS CONMATID, "
//				+ "TCM.FLOWNAME AS FLOWNAME, "
//				+ "TCM.CONTROLTARGET AS CONTROLTARGET, "
//				+ "TCM.CONTROLNAME AS CONTROLNAME, "
//				+ "TCM.CONTROLMANAGER AS CONTROLMANAGER, "
//				+ "TCM.CONTROLFREQUENCY AS CONTROLFREQUENCY, "
//				+ "TCM.CONTROLTYPE AS CONTROLTYPE, "
//				+ "TCM.CONTROLMETHOD AS CONTROLMETHOD, "
//				+ "TCM.CONTROLDES AS CONTROLDES, "
//				+ "TCM.INSIDECONTROLTARGET AS INSIDECONTROLTARGET, "
//				+ "TCM.KEYCONTROL AS KEYCONTROL, "
//				+ "TCM.EFFECTIVE AS EFFECTIVE, "
//				+ "TCM.CONTROLTEST AS CONTROLTEST, "
//				+ "TCM.FINANCIALREPORTIDENTIFY AS FINANCIALREPORTIDENTIFY, "
//				+ "TCM.CONKZCS AS CONKZCS, "
//				+ "TCM.VERSIONTYPE AS VERSIONTYPE "
            + "FROM TBL_RISK TR  "
            + "LEFT JOIN TBL_RISKCATEGORY TRC ON TRC.RISKCATID = TR.RISKCATID "
            + "LEFT JOIN TBL_ORGANIZATION ZRBM ON ZRBM.ORGID = TR.BELONGSTO "
//				+ "LEFT JOIN TBL_CONTROLMATRIX TCM ON TCM.RISKID = TR.RISKID "
            + "WHERE TR.RISKID = #{fromId}")
    Map<String, Object> selectFXCJMapById(Integer fromId);

    @Select("SELECT TRA.ASSPLANID AS ASSPLANID, "
            + "TRA.PLANCODE AS PLANCODE, "
            + "TRA.PLANNAME AS PLANNAME, "
            + "TRA.STARTDATE AS STARTDATE, "
            + "TRA.ENDDATE AS ENDDATE, "
            + "TRA.PLANSTATUS AS PLANSTATUS, "
            + "TRA.APRSTATUS AS APRSTATUS, "
            + "TRA.UNIT AS UNIT, "
            + "TRA.MEMO AS MEMO, "
            + "TRA.PLANDES AS PLANDES, "
            + "TRA.PLANTYPE AS PLANTYPE "

            + "FROM TBL_RISK_ASSPLAN TRA  "

            + "WHERE TRA.ASSPLANID = #{fromId}")
    Map<String, Object> selectPGJHMapById(Integer fromId);

    @Select("SELECT TRC.RISKCOPINGID AS RISKCOPINGID, "
            + "TRC.COPINGPLOT AS COPINGPLOT, "
            + "TRC.COPINGSTATUS AS COPINGSTATUS, "
            + "TRC.COPINGHEAD AS COPINGHEAD, "
            + "TRC.COPINGDES AS COPINGDES, "
            + "TRC.RISKID AS RISKID, "
            + "TRC.COPINGSOURCE AS COPINGSOURCE, "
            + "TRC.RISKHOPEVALUE AS RISKHOPEVALUE, "
            + "TRC.YDDES AS YDDES, "
            + "TRC.STATUS AS STATUS, "
            + "TRC.REVIEWER AS REVIEWER, "
            + "TRC.REVIEWER2 AS REVIEWER2 "

            + "FROM TBL_RISK_COPING TRC  "

            + "WHERE TRC.RISKCOPINGID = #{fromId}")
    Map<String, Object> selectFXYDMapById(Integer fromId);

    @Select("SELECT TRE.RISEVEID AS RISEVEID, "
            + "TRE.RISKEVENTCODE AS RISKEVENTCODE, "
            + "TRE.RISKEVENTNAME AS RISKEVENTNAME, "
            + "TRE.RISKEVENTDESCRIPTION AS RISKEVENTDESCRIPTION, "
            + "TRE.INDIRECTLOSS AS INDIRECTLOSS, "
            + "TRE.DIRECTLOSS AS DIRECTLOSS, "
            + "TRE.RISKFACTOR1 AS RISKFACTOR1, "
            + "TRE.RISKFACTOR2 AS RISKFACTOR2, "
            + "TRE.MEMO AS MEMO, "
            + "TRE.OCCUREDDATE AS OCCUREDDATE, "
            + "TRE.OCCUREDDEPARTMENT AS OCCUREDDEPARTMENT, "
            + "TRE.LOSSEVENTCATEGORY AS LOSSEVENTCATEGORY, "
            + "TRE.DISCOVEREDDATE AS DISCOVEREDDATE, "
            + "TRE.INRISKEVENTDB AS INRISKEVENTDB, "
            + "TRE.INDIRECTLOSSDES AS INDIRECTLOSSDES, "
            + "TRE.DIRECTLOSSDES AS DIRECTLOSSDES, "
            + "TRE.UNIT AS UNIT, "
            + "TRE.EVENTSTATUS AS EVENTSTATUS, "
            + "TRE.RECORDORG AS RECORDORG, "
            + "TRE.RECORDDEPART AS RECORDDEPART, "
            + "TRE.SUBSYSTEM AS SUBSYSTEM, "
            + "TRE.BUSSINESS AS BUSSINESS, "
            + "TRE.MAXESTIMATELOSS AS MAXESTIMATELOSS, "
            + "TRE.CONFIRMEDDIRECTLOSS AS CONFIRMEDDIRECTLOSS, "
            + "TRE.CONFIRMEDDIRECTLOSSA AS CONFIRMEDDIRECTLOSSA, "
            + "TRE.RISKCATID AS RISKCATID, "
            + "TRE.STATUS AS STATUS "

            + "FROM TBL_RISKEVENT TRE  "

            + "WHERE TRE.RISEVEID = #{fromId}")
    Map<String, Object> selectFXSJKMapById(Integer fromId);


    @Select("SELECT TR.REPORTID AS REPORTID, "
            + "TR.REPORTNAME AS REPORTNAME, "
            + "TR.REPORTTIME AS REPORTTIME, "
            + "TR.REPORTTYPE AS REPORTTYPE, "
            + "TR.REPORTMODE AS REPORTMODE, "
            + "TR.REPORTER AS REPORTER, "
            + "TR.REPORTDEPARTMENT AS REPORTDEPARTMENT, "
            + "TR.REPORTTEMPID AS REPORTTEMPID, "
            + "TR.REPORTSTATUS AS REPORTSTATUS, "
            + "TR.REPORTFILE AS REPORTFILE, "
            + "TR.MEMO AS MEMO, "
            + "TR.TYPE AS TYPE, "
            + "TR.REPDESC AS REPDESC, "
            + "TR.PROJECTID AS PROJECTID, "
            + "TR.ORGID AS ORGID, "
            + "TR.YJDES AS YJDES, "
            + "TR.FHSTAFFID AS FHSTAFFID, "
            + "TR.ZQYJSTAFFID AS ZQYJSTAFFID, "
            + "TR.REPORTCODE AS REPORTCODE, "
            + "TR.SENDTIME AS SENDTIME, "
            + "TR.FHSTAFFNAME AS FHSTAFFNAME, "
            + "TR.REPORTERID AS REPORTERID, "
            + "TR.REPORTDEPARTMENTID AS REPORTDEPARTMENTID, "
            + "TR.ZQYJSTAFFNAME AS ZQYJSTAFFNAME, "
            + "TR.REPORTLEVEL AS REPORTLEVEL, "
            + "TR.STATUS AS STATUS "

            + "FROM TBL_REPORT TR  "

            + "WHERE TR.REPORTID = #{fromId}")
    Map<String, Object> selectFXBGMapById(Integer fromId);

    //===================================================风险管控END

    //===================================================内控管理BEGIN
    @Select("SELECT TR.ASSID AS ASSID, "
            + "TR.STATUS AS STATUS "

            + "FROM TBL_ASSESS_PLAN TR  "

            + "WHERE TR.ASSID = #{fromId}")
    Map<String, Object> selectPJLXMapById(Integer fromId);

    @Select("SELECT TR.REPORTID AS REPORTID, "
            + "TR.REPORTNAME AS REPORTNAME, "
            + "TR.REPORTTIME AS REPORTTIME, "
            + "TR.REPORTTYPE AS REPORTTYPE, "
            + "TR.REPORTMODE AS REPORTMODE, "
            + "TR.REPORTER AS REPORTER, "
            + "TR.REPORTDEPARTMENT AS REPORTDEPARTMENT, "
            + "TR.REPORTTEMPID AS REPORTTEMPID, "
            + "TR.REPORTSTATUS AS REPORTSTATUS, "
            + "TR.REPORTFILE AS REPORTFILE, "
            + "TR.MEMO AS MEMO, "
            + "TR.TYPE AS TYPE, "
            + "TR.REPDESC AS REPDESC, "
            + "TR.PROJECTID AS PROJECTID, "
            + "TR.ORGID AS ORGID, "
            + "TR.YJDES AS YJDES, "
            + "TR.FHSTAFFID AS FHSTAFFID, "
            + "TR.ZQYJSTAFFID AS ZQYJSTAFFID, "
            + "TR.REPORTCODE AS REPORTCODE, "
            + "TR.SENDTIME AS SENDTIME, "
            + "TR.FHSTAFFNAME AS FHSTAFFNAME, "
            + "TR.REPORTERID AS REPORTERID, "
            + "TR.REPORTDEPARTMENTID AS REPORTDEPARTMENTID, "
            + "TR.ZQYJSTAFFNAME AS ZQYJSTAFFNAME, "
            + "TR.REPORTLEVEL AS REPORTLEVEL, "
            + "TR.STATUS AS STATUS "

            + "FROM TBL_REPORT TR  "

            + "WHERE TR.REPORTID = #{fromId}")
    Map<String, Object> selectPJBGMapById(Integer fromId);

    @Select("SELECT TR.FINDID AS FINDID, "
            + "TR.TESTTASKID AS TESTTASKID, "
            + "TR.CREATESTAFFID AS CREATESTAFFID, "
            + "TR.CREATETIME AS CREATETIME, "
            + "TR.ONEPROCESS AS ONEPROCESS, "
            + "TR.PROBLEMMEMO AS PROBLEMMEMO, "
            + "TR.DEFECTMEMO AS DEFECTMEMO, "
            + "TR.PROBLEMTYPE AS PROBLEMTYPE, "
            + "TR.DEFECTLEVEL AS DEFECTLEVEL, "
            + "TR.QUABASIS AS QUABASIS, "
            + "TR.MAINORG AS MAINORG, "
            + "TR.FEEDBACK AS FEEDBACK, "
            + "TR.REFORMPLAN AS REFORMPLAN, "
            + "TR.ESTFINISHDATE AS ESTFINISHDATE, "
//				+ "TR.REFORMSTAFFID AS REFORMSTAFFID, "
            + "TS.PKYMSTAFFID AS REFORMSTAFFID, "
            + "TR.STATUS AS STATUS "

            + "FROM TBL_TESTTASK_PROBLEMFIND TR  "
            + "LEFT JOIN TBL_STAFF TS ON TS.STAFFID=TR.REFORMSTAFFID  "

            + "WHERE TR.FINDID = #{fromId}")
    Map<String, Object> selectWTFXMapById(Integer fromId);

    @Select("SELECT PKYMSTAFFID AS BMFZRID FROM TBL_STAFF WHERE MANAGEORGS like #{orgid} ")
    Map<String, Object> selectBMFZRByOrgId(String orgid);
    //===================================================内控管理END


    @Select("SELECT TR.ID AS ID, "
            + "TR.CLUENABER AS CLUENABER, "
            + "TR.CLUENAME AS CLUENAME, "
            + "TR.STATUS AS STATUS "
            + "FROM TBL_WGZZ_WGHS TR  "
            + "WHERE TR.ID = #{fromId}")
    Map<String, Object> selectWGHSMapById(Integer fromId);

    @Select("SELECT TR.ID AS ID, "
            + "TR.CLUENABER AS CLUENABER, "
            + "TR.STATUS AS STATUS "
            + "FROM TBL_WGZZ_SHBG TR  "
            + "WHERE TR.ID = #{fromId}")
    Map<String, Object> selectSHBGMapById(Integer fromId);

    @Select("SELECT TR.ID AS ID, "
            + "TR.CLUEZRDX AS CLUEZRDX, "
            + "TR.CLUESSRD AS CLUESSRD, "
            + "TR.CLUECLJY AS CLUECLJY, "
            + "TR.STATUS AS STATUS "
            + "FROM TBL_WGZZ_WGHC TR  "
            + "WHERE TR.ID = #{fromId}")
    Map<String, Object> selectWGHCMapById(Integer fromId);

    @Select("SELECT TR.ID AS ID, "
            + "TR.WGHCID AS WGHCID, "
            + "TR.CLUENABER AS CLUENABER, "
            + "TR.YSSTUTS AS YSSTUTS, "
            + "TR.CLUERESOURCE AS CLUERESOURCE "
            + "FROM TBL_WGZZ_WGJY_YS TR  "
            + "WHERE TR.ID = #{fromId}")
    Map<String, Object> selectWGYSMapById(Integer fromId);

    //合规报告
    @Select("SELECT TR.ID AS ID, "
            + "TR.REPORTNAME AS REPORTNAME, "
            + "TR.CONTENT AS CONTENT, "
            + "TR.HIERARCHY AS HIERARCHY, "
            + "TR.REPORTTTYPE AS REPORTTTYPE, "
            + "TR.REPORTSTAGE AS REPORTSTAGE, "
            + "TR.DEPARTMENTHEAD AS DEPARTMENTHEAD, "
            + "TR.DRAFTSMAN AS DRAFTSMAN, "
            + "TR.STATE AS STATE, "
            + "TR.CREATOR AS CREATOR, "
            + "TR.WORKUNIT AS WORKUNIT, "
            + "TR.BELONGGROUP AS BELONGGROUP, "
            + "TR.CREATEDTIME AS CREATEDTIME, "
            + "TR.UPDATEDTIME AS UPDATEDTIME "
            + "FROM TBL_COMPLIANCE_REPORT TR  "
            + "WHERE TR.ID = #{fromId}")
    Map<String, Object> selectHGBGBMapById(Integer fromId);


    //合规手册
    @Select("SELECT TR.ID AS ID, "
            + "TR.MANUALNAME AS MANUALNAME, "
            + "TR.VERSIONNUMBER AS VERSIONNUMBER, "
            + "TR.TRANSACTOR AS TRANSACTOR, "
            + "TR.DEPARTMENTHEAD AS DEPARTMENTHEAD, "
            + "TR.STATE AS STATE, "
            + "TR.CREATOR AS CREATOR, "
            + "TR.WORKUNIT AS WORKUNIT, "
            + "TR.BELONGGROUP AS BELONGGROUP, "
            + "TR.CREATEDTIME AS CREATEDTIME, "
            + "TR.UPDATEDTIME AS UPDATEDTIME "
            + "FROM TBL_COMPLIANCE_MANUAL_MGT TR  "
            + "WHERE TR.ID = #{fromId}")
    Map<String, Object> selectHGSCGLMapById(Integer fromId);


    //合规计划审批表
    @Select("SELECT TR.ID AS ID, "
            + "TR.PLANSERIALNUMBER AS PLANSERIALNUMBER, "
            + "TR.PLANNAME AS PLANNAME, "
            + "TR.FILEIDS AS FILEIDS, "
            + "TR.COMPLIANCEPROCESS AS COMPLIANCEPROCESS, "
            + "TR.HIERARCHY AS HIERARCHY, "
            + "TR.COMPILER AS COMPILER, "
            + "TR.DEPARTMENTHEAD AS DEPARTMENTHEAD, "
            + "TR.STATE AS STATE, "
            + "TR.CREATOR AS CREATOR, "
            + "TR.WORKUNIT AS WORKUNIT, "
            + "TR.BELONGGROUP AS BELONGGROUP, "
            + "TR.CREATEDTIME AS CREATEDTIME, "
            + "TR.UPDATEDTIME AS UPDATEDTIME "
            + "FROM TBL_COMPLIANCE_PLAN_MGT TR  "
            + "WHERE TR.ID = #{fromId}")
    Map<String, Object> selectHGJHSPBMapById(Integer fromId);


    //重点岗位合规责任
    @Select("SELECT TR.ID AS ID, "
            + "TR.DEPARTMENT AS DEPARTMENT, "
            + "TR.POSTNAME AS POSTNAME, "
            + "TR.COMPLIANCETDR AS COMPLIANCETDR, "
            + "TR.REMARK AS REMARK, "
            + "TR.STATE AS STATE, "
            + "TR.CREATOR AS CREATOR, "
            + "TR.WORKUNIT AS WORKUNIT, "
            + "TR.BELONGGROUP AS BELONGGROUP, "
            + "TR.CREATEDTIME AS CREATEDTIME, "
            + "TR.UPDATEDTIME AS UPDATEDTIME "

            + "FROM TBL_COMPLIANCE_DTY TR  "
            + "WHERE TR.ID = #{fromId}")
    Map<String, Object> selectZDGWHGZRMapById(Integer fromId);

    //合规管理员信息管理
    @Select("SELECT TR.ID AS ID, "
            + "TR.DEPARTMENT AS DEPARTMENT, "
            + "TR.ADMINISTRATORNAME AS ADMINISTRATORNAME, "
            + "TR.CONTACTINFORMATION AS CONTACTINFORMATION, "
            + "TR.REMARK AS REMARK, "
            + "TR.STATE AS STATE, "
            + "TR.CREATOR AS CREATOR, "
            + "TR.WORKUNIT AS WORKUNIT, "
            + "TR.BELONGGROUP AS BELONGGROUP, "
            + "TR.CREATEDTIME AS CREATEDTIME, "
            + "TR.UPDATEDTIME AS UPDATEDTIME "

            + "FROM TBL_COMPLIANCE_IM TR  "
            + "WHERE TR.ID = #{fromId}")
    Map<String, Object> selectHGGLYXXGLMapById(Integer fromId);


    @Select("SELECT\n" +
            "\tKW.REVIEWID AS REVIEWID,\n" +
            "\tKW.RISKREVIEWCODE AS RISKREVIEWCODE,\n" +
            "\tKW.STAFFID AS STAFFID,\n" +
            "\tKW.STAFFDEPT AS STAFFDEPT,\n" +
            "\tKW.CREATETIME AS CREATETIME,\n" +
            "\tKW.MATTERNAME AS MATTERNAME,\n" +
            "\tKW.MATTERPROJECTCODE AS MATTERPROJECTCODE,\n" +
            "\tKW.MATTERCODE AS MATTERCODE,\n" +
            "\tKW.MATTERCONTEXT AS MATTERCONTEXT,\n" +
            "\tKW.CREATESTAFFID AS CREATESTAFFID \n" +
            "FROM\n" +
            "\tTBL_RISK_REVIEW KW \n" +
            "WHERE\n" +
            "\tKW.REVIEWID = #{ fromId}")
    Map<String, Object> selectFXSCTZMapById(Integer fromId);

    @Select("SELECT\n" +
            "\tLCIP.ID AS ID,\n" +
            "\tLCIP.PLANCODE AS PLANCODE,\n" +
            "\tLCIP.PLANNAME AS PLANNAME,\n" +
            "\tLCIP.PLANYEAR AS PLANYEAR,\n" +
            "\tLCIP.INSPECTTYPE AS INSPECTTYPE,\n" +
            "\tLCIP.PLANTIMESTART AS PLANTIMESTART,\n" +
            "\tLCIP.PLANTIMEEND AS PLANTIMEEND,\n" +
            "\tLCIP.INSPECTCOMPANY AS INSPECTCOMPANY,\n" +
            "\tLCIP.INSPECTDEPARTMENT AS INSPECTDEPARTMENT,\n" +
            "\tLCIP.CREATEDTIME AS CREATEDTIME\n" +
            "FROM\n" +
            "\tTBL_COMPLIANCE_INSPECT_PLAN LCIP\n" +
            "WHERE\n" +
            "\tLCIP.ID = #{fromId}")
    Map<String, Object> selectHGGLJCFAMapById(Integer fromId);

    @Select("SELECT\n" +
            "\tLCII.ID AS ID,\n" +
            "\tLCII.SUSPECTEDISSUE AS SUSPECTEDISSUE,\n" +
            "\tLCII.QUESTIONTYPE AS QUESTIONTYPE,\n" +
            "\tLCII.DISCOVERTIME AS DISCOVERTIME,\n" +
            "\tLCII.BUSINESSAREA AS BUSINESSAREA,\n" +
            "\tLCII.ISCONFIRM AS ISCONFIRM,\n" +
            "\tLCII.ISRECTIFICATION AS ISRECTIFICATION \n" +
            "FROM\n" +
            "\tTBL_COMPLIANCE_INSPECT_IMP LCII \n" +
            "WHERE\n" +
            "\tLCII.ID = #{fromId}")
    Map<String, Object> selectHGGLJCSSMapById(Integer fromId);

    @Select("SELECT\n" +
            "\tLCR.ID AS ID,\n" +
            "\tLCR.IMPID AS IMPID,\n" +
            "\tLCR.RECTIFICATIONSTATE AS RECTIFICATIONSTATE,\n" +
            "\tLCR.CONTENT AS CONTENT \n" +
            "FROM\n" +
            "\tTBL_COMPLIANCE_RECTIFICATION LCR \n" +
            "WHERE\n" +
            "\tLCR.ID = #{ fromId }")
    Map<String, Object> selectHGGLWTZGMapById(Integer fromId);

    @Select("SELECT\n" +
            "\tLEK.ID AS ID,\n" +
            "\tLEK.RISKNUMBER AS RISKNUMBER,\n" +
            "\tLEK.RISKNAME AS RISKNAME,\n" +
            "\tLEK.DEPARTMENT AS DEPARTMENT,\n" +
            "\tLEK.FINDTIME AS FINDTIME,\n" +
            "\tLEK.DISCOVERYTIME AS DISCOVERYTIME,\n" +
            "\tLEK.RISKTYPE AS RISKTYPE \n" +
            "FROM\n" +
            "\tTBL_COMPLIANCE_RISK LEK \n" +
            "WHERE\n" +
            "\tLEK.ID = #{ fromid }")
    Map<String, Object> selectHGGLFXSJTZMapById(Integer fromId);

    @Select("SELECT\n" +
            "\tTYRS. ID,\n" +
            "\tTYRS.CONCERNS,\n" +
            "\tTYRS.CONCERNS_CONTENT,\n" +
            "\tTYRS.UNIT_ID,\n" +
            "\tTYRS.PROJECT_TYPE,\n" +
            "\tTYRS.DRAFT_ID,\n" +
            "\tTYRS.REMARK,\n" +
            "\tTYRS.CREATE_USER,\n" +
            "\tTYRS.CREATE_TIME,\n" +
            "\tTYRS.PERSON_IDS,\n" +
            "\tTYRS.STATUS\n" +
            "FROM\n" +
            "\tTBL_YQNS_REQUIRE_SUGGESTION TYRS")
    Map<String, Object> selectXQJYBMapById(Integer fromId);

    @Select("SELECT\n" +
            "\tTYSR. ID,\n" +
            "\tTYSR.AUDIT_ITEM,\n" +
            "\tTYSR.AUDIT_PURPOSE,\n" +
            "\tTYSR.UNIT_ID,\n" +
            "\tTYSR.CONCERNS_CONTENT,\n" +
            "\tTYSR.UNIT_RANGE,\n" +
            "\tTYSR.TIME_RANGE,\n" +
            "\tTYSR.PROJECT_TYPE,\n" +
            "\tTYSR.REMARK,\n" +
            "\tTYSR.CREATE_USER,\n" +
            "\tTYSR.CREATE_TIME,\n" +
            "\tTYSR.PERSON_IDS,\n" +
            "\tTYSR.STATUS\n" +
            "FROM\n" +
            "\tTBL_YQNS_SERVICE_REQUIREMENT TYSR")
    Map<String, Object> selectFWXQBMapById(Integer fromId);

    @Select("SELECT\n" +
            "\tTYPS. ID,\n" +
            "\tTYPS.PROJECT_NAME,\n" +
            "\tTYPS.PROJECT_PURPOSE,\n" +
            "\tTYPS.CONCERNS_CONTENT,\n" +
            "\tTYPS.UNIT_RANGE,\n" +
            "\tTYPS.TIME_RANGE,\n" +
            "\tTYPS.PROJECT_TYPE,\n" +
            "\tTYPS.REMARK,\n" +
            "\tTYPS.CREATE_USER,\n" +
            "\tTYPS.CREATE_TIME,\n" +
            "\tTYPS.PERSON_IDS,\n" +
            "\tTYPS.STATUS\n" +
            "FROM\n" +
            "\tTBL_YQNS_PROJECT_SUGGESTION TYPS")
    Map<String, Object> selectLXJYBMapById(Integer fromId);

    @Select("SELECT\n" +
            "\tTYF.FGLDHZID,\n" +
            "\tTYF.CJR,\n" +
            "\tTYF.CJSJ,\n" +
            "\tTYF.EXT1,\n" +
            "\tTYF.EXT2,\n" +
            "\tTYF.EXT3,\n" +
            "\tTYF.ORGID,\n" +
            "\tTYF.GXR,\n" +
            "\tTYF.GXSJ,\n" +
            "\tTYF.SPZT,\n" +
            "\tTYF.BZ,\n" +
            "\tTYF.GSLDID,\n" +
            "\tTYF.GSLDXM,\n" +
            "\tTYF.LXYQ,\n" +
            "\tTYF.LSJY,\n" +
            "\tTYF.STATUS\n" +
            "FROM\n" +
            "\tTBL_YQNS_FGLDHZ TYF")
    Map<String, Object> selectFGLDHZMapById(Integer fromId);

    Map<String, Object> selectGCXMZJMapById(Integer fromId);

    Map<String, Object> selectGCXMZJZJBMapById(Integer fromId);

    Map<String, Object> selectGCJGYSJHMapById(Integer fromId);

    @Select("SELECT\n" +
            "\tTCNA.ID,\n" +
            "\tTCNA.IPADDRESS,\n" +
            "\tTCNA.MACADDRESS,\n" +
            "\tTCNA.DEPARTMENTSNAME,\n" +
            "\tTCNA.USEPEOPLE,\n" +
            "\tTCNA.CONTACTPHONE,\n" +
            "\tTCNA.MAILADDRESS,\n" +
            "\tTCNA.ANTIVIRUSSOFTWARE,\n" +
            "\tTCNA.ANTIVIRUSMANUFACTURER,\n" +
            "\tTCNA.STATE,\n" +
            "\tTCNA.CREATOR,\n" +
            "\tTCNA.WORKUNIT,\n" +
            "\tTCNA.BELONGGROUP\n" +
            "FROM\n" +
            "\tTBL_CEA_NETWORK_AGENT TCNA " +
            "WHERE TCNA.ID = #{fromId}")
    Map<String, Object> selectWWDLFWGLById(Integer fromId);

    @Select("SELECT TCCA.ID, TCCA.CONFERENCENAME, TCCA.CONFERENCECOMPERE, TCCA.ATTENDEES, TCCA.CONFERENCETIMESTART, TCCA.CONFERENCETIMEEND, \n" +
            "TCCA.CONFERENCEPLACE, TCCA.CONFERENCECONTENT, TCCA.CONFERENCEREQUIRE, TCCA.FILEIDS, TCCA.STATE, TCCA.CREATOR,\n" +
            "TCCA.WORKUNIT, TCCA.BELONGGROUP FROM TBL_CEA_CONFERENCE_APPLY TCCA WHERE TCCA.ID = #{fromId}")
    Map<String, Object> selectHYSQById(Integer fromId);

    @Select("SELECT\n" +
            "\tTCCM. ID,\n" +
            "\tTCCM.CONFERENCENAME,\n" +
            "\tTCCM.CONFERENCECOMPERE,\n" +
            "\tTCCM.ATTENDEES,\n" +
            "\tTCCM.CONFERENCEPLACE,\n" +
            "\tTCCM.CONFERENCEREQUIRE,\n" +
            "\tTCCM.CONFERENCECONTENT,\n" +
            "\tTCCM.FILEIDS,\n" +
            "\tTCCM.STATE,\n" +
            "\tTCCM.CREATOR,\n" +
            "\tTCCM.WORKUNIT,\n" +
            "\tTCCM.BELONGGROUP\n" +
            "FROM\n" +
            "\tTBL_CEA_CONFERENCE_MGT TCCM WHERE TCCM.ID = #{fromId}")
    Map<String, Object> selectHYGLById(Integer fromId);

    @Select("SELECT\n" +
            "\tTCIM.ID,\n" +
            "\tTCIM.APPLYPEOPLE,\n" +
            "\tTCIM.APPLYBELONGGROUP,\n" +
            "\tTCIM.APPLYWORKUNIT,\n" +
            "\tTCIM.NETWORKINTERFACE,\n" +
            "\tTCIM.OFFICEAREA,\n" +
            "\tTCIM.ROOMNUMBER,\n" +
            "\tTCIM.PURPOSE,\n" +
            "\tTCIM.EQUIPMENTTYPE,\n" +
            "\tTCIM.EXTERNALNETWORKPERMISSIONS,\n" +
            "\tTCIM.STATE,\n" +
            "\tTCIM.CREATOR,\n" +
            "\tTCIM.WORKUNIT,\n" +
            "\tTCIM.BELONGGROUP\n" +
            "FROM\n" +
            "\tTBL_CEA_IP_MANAGE TCIM WHERE TCIM.ID = #{fromId}")
    Map<String, Object> selectIPDZGLById(Integer fromId);

    @Select("SELECT\n" +
            "\tTCIW.ID,\n" +
            "\tTCIW.INFOTITLE,\n" +
            "\tTCIW.INFOPROVIDERWORKUNIT,\n" +
            "\tTCIW.PROVIDERPEOPLE,\n" +
            "\tTCIW.CONTACT,\n" +
            "\tTCIW.FAX,\n" +
            "\tTCIW.MAILADDRESS,\n" +
            "\tTCIW.INFORELEASECOLUMN,\n" +
            "\tTCIW.EXPECTONLINETIME,\n" +
            "\tTCIW.FAILURETIME,\n" +
            "\tTCIW.CONTENTABSTRACT,\n" +
            "\tTCIW.STATE,\n" +
            "\tTCIW.CREATOR,\n" +
            "\tTCIW.WORKUNIT,\n" +
            "\tTCIW.BELONGGROUP,\n" +
            "\tTCIW.CREATEDTIME,\n" +
            "\tTCIW.UPDATEDTIME\n" +
            "FROM\n" +
            "\tTBL_CEA_INTERNAL_WEBSITE_APPLY TCIW WHERE TCIW.ID = #{fromId}")
    Map<String, Object> selectNBWZSQDById(Integer fromId);

    @Select("SELECT\n" +
            "\tTCEA.ID,\n" +
            "\tTCEA.APPLYPEOPLE,\n" +
            "\tTCEA.APPLYWORKUNIT,\n" +
            "\tTCEA.POST,\n" +
            "\tTCEA.APPLYEXPATRIATETIME,\n" +
            "\tTCEA.APPLYRETURNTIME,\n" +
            "\tTCEA.ACTUALRETURNTIME,\n" +
            "\tTCEA.EXPATRIATEREASON,\n" +
            "\tTCEA.STATE,\n" +
            "\tTCEA.CREATOR,\n" +
            "\tTCEA.WORKUNIT,\n" +
            "\tTCEA.BELONGGROUP,\n" +
            "\tTCEA.CREATEDTIME,\n" +
            "\tTCEA.UPDATEDTIME\n" +
            "FROM\n" +
            "\tTBL_CEA_EXPATRIATE_APPLY TCEA WHERE TCEA.ID = #{fromId}")
    Map<String, Object> selectWPSQDById(Integer fromId);

    @Select("SELECT\n" +
            "\tTCCH.ID,\n" +
            "\tTCCH.PEOPLE,\n" +
            "\tTCCH.PEOPLEWORKUNIT,\n" +
            "\tTCCH.FILLFORMTIME,\n" +
            "\tTCCH.CANCELHOLIDAYTYPE,\n" +
            "\tTCCH.REASONS,\n" +
            "\tTCCH.STATE,\n" +
            "\tTCCH.CREATOR,\n" +
            "\tTCCH.WORKUNIT,\n" +
            "\tTCCH.BELONGGROUP,\n" +
            "\tTCCH.CREATEDTIME,\n" +
            "\tTCCH.UPDATEDTIME\n" +
            "FROM\n" +
            "\tTBL_CEA_CANCEL_HOLIDAY TCCH WHERE TCCH.ID = #{fromId}")
    Map<String, Object> selectXJDById(Integer fromId);

    @Select("SELECT\n" +
            "\tTCSN.ID,\n" +
            "\tTCSN.NOTICENUMBER,\n" +
            "\tTCSN.NOTICENAME,\n" +
            "\tTCSN.NOTICETIME,\n" +
            "\tTCSN.SUPERVISIONWORKUNIT,\n" +
            "\tTCSN.TRANSACTOR,\n" +
            "\tTCSN.REMARK,\n" +
            "\tTCSN.FILEIDS,\n" +
            "\tTCSN.STATE,\n" +
            "\tTCSN.CREATOR,\n" +
            "\tTCSN.WORKUNIT,\n" +
            "\tTCSN.BELONGGROUP,\n" +
            "\tTCSN.CREATEDTIME,\n" +
            "\tTCSN.UPDATEDTIME\n" +
            "FROM\n" +
            "\tTBL_CEA_SUPERVISION_NOTICE TCSN WHERE TCSN.ID = #{fromId}")
    Map<String, Object> selectDBTZDById(Integer fromId);

    @Select("SELECT\n" +
            "\tTCMM.ID,\n" +
            "\tTCMM.APPLYID,\n" +
            "\tTCMM.STAFFCODE,\n" +
            "\tTCMM.SERVICETYPE,\n" +
            "\tTCMM.CONTACTPHONE,\n" +
            "\tTCMM.MAILSUFFIX,\n" +
            "\tTCMM.LOGINNAME,\n" +
            "\tTCMM.LOGINNAMEONE,\n" +
            "\tTCMM.LOGINNAMETWO,\n" +
            "\tTCMM.LOGINNAMETHREE,\n" +
            "\tTCMM.CHANGETYPE,\n" +
            "\tTCMM.APPLYMAIL,\n" +
            "\tTCMM.CHANGECONTENT,\n" +
            "\tTCMM.LOGOUTREASON,\n" +
            "\tTCMM.STATE,\n" +
            "\tTCMM.CREATOR,\n" +
            "\tTCMM.WORKUNIT,\n" +
            "\tTCMM.BELONGGROUP,\n" +
            "\tTCMM.CREATEDTIME,\n" +
            "\tTCMM.UPDATEDTIME,\n" +
            "\tTCMM.APPLYBELONGGROUP\n" +
            "FROM\n" +
            "\tTBL_CEA_MAIL_MGT TCMM WHERE TCMM.ID = #{fromId}")
    Map<String, Object> selectZSYYXGLById(Integer fromId);

    @Select("SELECT\n" +
            "\tTCDC.ID,\n" +
            "\tTCDC.SERVICETYPE,\n" +
            "\tTCDC.USERNAME,\n" +
            "\tTCDC.EMAIL,\n" +
            "\tTCDC.STAFFCODE,\n" +
            "\tTCDC.ORGANIZATIONNAME,\n" +
            "\tTCDC.ORGANIZATIONNUM,\n" +
            "\tTCDC.CONTACTPHONE,\n" +
            "\tTCDC.REMARK,\n" +
            "\tTCDC.ISAGENCY,\n" +
            "\tTCDC.STATE,\n" +
            "\tTCDC.CREATOR,\n" +
            "\tTCDC.WORKUNIT,\n" +
            "\tTCDC.BELONGGROUP,\n" +
            "\tTCDC.CREATEDTIME,\n" +
            "\tTCDC.UPDATEDTIME,\n" +
            "\tTCDC.AGENCYNAME,\n" +
            "\tTCDC.AGENCYBELONGGROUP,\n" +
            "\tTCDC.AGENCYMAIL,\n" +
            "\tTCDC.AGENCYCONTACTPHONE\n" +
            "FROM\n" +
            "\tTBL_CEA_DIGITAL_CERTIFICATE TCDC WHERE TCDC.ID = #{fromId}")
    Map<String, Object> selectSZZSGLById(Integer fromId);


    @Select("SELECT\n" +
            "\tTCVM.ID,\n" +
            "\tTCVM.STAFFID,\n" +
            "\tTCVM.MAIL,\n" +
            "\tTCVM.MOBILEPHONE,\n" +
            "\tTCVM.STAFFNUMBER,\n" +
            "\tTCVM.SERVICETYPE,\n" +
            "\tTCVM.APPLYTIME,\n" +
            "\tTCVM.REMARK,\n" +
            "\tTCVM.STATE,\n" +
            "\tTCVM.CREATOR,\n" +
            "\tTCVM.WORKUNIT,\n" +
            "\tTCVM.BELONGGROUP,\n" +
            "\tTCVM.CREATEDTIME,\n" +
            "\tTCVM.UPDATEDTIME,\n" +
            "\tTCVM.POST,\n" +
            "\tTCVM.STATUS\n" +
            "FROM\n" +
            "\tTBL_CEA_VPN_MGT TCVM WHERE TCVM.ID = #{fromId}")
    Map<String, Object> selectVPNZHGLById(Integer fromId);

    @Select("SELECT\n" +
            "\tTCIR.ID,\n" +
            "\tTCIR.SYMBOL,\n" +
            "\tTCIR.INSIDEREPORTEDNAME,\n" +
            "\tTCIR.FILEIDS,\n" +
            "\tTCIR.STATE,\n" +
            "\tTCIR.CREATOR,\n" +
            "\tTCIR.WORKUNIT,\n" +
            "\tTCIR.BELONGGROUP,\n" +
            "\tTCIR.CREATEDTIME,\n" +
            "\tTCIR.UPDATEDTIME,\n" +
            "\tTCIR.STATUS\n" +
            "FROM\n" +
            "\tTBL_CEA_INSIDE_REPORTED TCIR WHERE TCIR.ID = #{fromId}")
    Map<String, Object> selectNBWJCBById(Integer fromId);

    @Select("SELECT\n" +
            "\tTCAA.ID,\n" +
            "\tTCAA.APPLYID,\n" +
            "\tTCAA.APPLYWORKUNIT,\n" +
            "\tTCAA.APPLYROLE,\n" +
            "\tTCAA.APPLYTIME,\n" +
            "\tTCAA.STATE,\n" +
            "\tTCAA.CREATOR,\n" +
            "\tTCAA.WORKUNIT,\n" +
            "\tTCAA.BELONGGROUP,\n" +
            "\tTCAA.CREATEDTIME,\n" +
            "\tTCAA.UPDATEDTIME,\n" +
            "\tTCAA.REMARK,\n" +
            "\tTCAA.STATUS\n" +
            "FROM\n" +
            "\tTBL_CEA_AUTHORITY_APPLY TCAA WHERE TCAA.ID = #{fromId}")
    Map<String, Object> selectQXSQById(Integer fromId);

    @Select("SELECT\n" +
            "\tTYJJ.JHCGID,\n" +
            "\tTYJJ.CJR,\n" +
            "\tTYJJ.CJSJ,\n" +
            "\tTYJJ.EXT1,\n" +
            "\tTYJJ.EXT2,\n" +
            "\tTYJJ.EXT3,\n" +
            "\tTYJJ.ORGID,\n" +
            "\tTYJJ.GXR,\n" +
            "\tTYJJ.GXSJ,\n" +
            "\tTYJJ.SPZT,\n" +
            "\tTYJJ.JHMC,\n" +
            "\tTYJJ.SJ,\n" +
            "\tTYJJ.BZ,\n" +
            "\tTYJJ.LXDWID,\n" +
            "\tTYJJ.LXDWMC,\n" +
            "\tTYJJ.BSJDWID,\n" +
            "\tTYJJ.BSJDWMC,\n" +
            "\tTYJJ.SSLX,\n" +
            "\tTYJJ.JWXM,\n" +
            "\tTYJJ.SSSJJGID,\n" +
            "\tTYJJ.XMND,\n" +
            "\tTYJJ.XMFZCKSID,\n" +
            "\tTYJJ.XMFZCKSMC,\n" +
            "\tTYJJ.JHSSYF,\n" +
            "\tTYJJ.SSXMLX,\n" +
            "\tTYJJ.LXYJ,\n" +
            "\tTYJJ.SJXMMC,\n" +
            "\tTYJJ.JHLX,\n" +
            "\tTYJJ.JHTRRR,\n" +
            "\tTYJJ.SFDQBJYHDSJ,\n" +
            "\tTYJJ.BGYY,\n" +
            "\tTYJJ.SSSJJGMC,\n" +
            "\tTYJJ.STATUS,\n" +
            "\tTYJJ.STATUSS\n" +
            "FROM\n" +
            "\tTBL_YQNS_JHGL_JHCG TYJJ WHERE TYJJ.JHCGID = #{fromId}")
    Map<String, Object> selectJHCGById(Integer fromId);

    @Select("SELECT\n" +
            "\tTYJJ.JHCHUGID,\n" +
            "\tTYJJ.CJR,\n" +
            "\tTYJJ.CJSJ,\n" +
            "\tTYJJ.EXT1,\n" +
            "\tTYJJ.EXT2,\n" +
            "\tTYJJ.EXT3,\n" +
            "\tTYJJ.ORGID,\n" +
            "\tTYJJ.GXR,\n" +
            "\tTYJJ.GXSJ,\n" +
            "\tTYJJ.SPZT,\n" +
            "\tTYJJ.JHMC,\n" +
            "\tTYJJ.SJ,\n" +
            "\tTYJJ.BZ,\n" +
            "\tTYJJ.LXDWID,\n" +
            "\tTYJJ.LXDWMC,\n" +
            "\tTYJJ.BSJDWID,\n" +
            "\tTYJJ.BSJDWMC,\n" +
            "\tTYJJ.SSLX,\n" +
            "\tTYJJ.JWXM,\n" +
            "\tTYJJ.SSSJJGID,\n" +
            "\tTYJJ.XMND,\n" +
            "\tTYJJ.XMFZCKSID,\n" +
            "\tTYJJ.XMFZCKSMC,\n" +
            "\tTYJJ.JHSSYF,\n" +
            "\tTYJJ.SSXMLX,\n" +
            "\tTYJJ.LXYJ,\n" +
            "\tTYJJ.SJXMMC,\n" +
            "\tTYJJ.JHLX,\n" +
            "\tTYJJ.JHTRRR,\n" +
            "\tTYJJ.SFDQBJYHDSJ,\n" +
            "\tTYJJ.BGYY,\n" +
            "\tTYJJ.SSSJJGMC,\n" +
            "\tTYJJ.STATUS\n" +
            "FROM\n" +
            "\tTBL_YQNS_JHGL_JHCHUG TYJJ WHERE TYJJ.JHCHUGID = #{fromId}")
    Map<String, Object> selectJHCHUGById(Integer fromId);

    @Select("SELECT\n" +
            "\tTYJJ.JHID,\n" +
            "\tTYJJ.CJR,\n" +
            "\tTYJJ.CJSJ,\n" +
            "\tTYJJ.EXT1,\n" +
            "\tTYJJ.EXT2,\n" +
            "\tTYJJ.EXT3,\n" +
            "\tTYJJ.ORGID,\n" +
            "\tTYJJ.GXR,\n" +
            "\tTYJJ.GXSJ,\n" +
            "\tTYJJ.SPZT,\n" +
            "\tTYJJ.JHMC,\n" +
            "\tTYJJ.SJ,\n" +
            "\tTYJJ.BZ,\n" +
            "\tTYJJ.LXDWID,\n" +
            "\tTYJJ.LXDWMC,\n" +
            "\tTYJJ.BSJDWID,\n" +
            "\tTYJJ.BSJDWMC,\n" +
            "\tTYJJ.SSLX,\n" +
            "\tTYJJ.JWXM,\n" +
            "\tTYJJ.SSSJJGID,\n" +
            "\tTYJJ.XMND,\n" +
            "\tTYJJ.XMFZCKSID,\n" +
            "\tTYJJ.XMFZCKSMC,\n" +
            "\tTYJJ.JHSSYF,\n" +
            "\tTYJJ.SSXMLX,\n" +
            "\tTYJJ.LXYJ,\n" +
            "\tTYJJ.SJXMMC,\n" +
            "\tTYJJ.JHLX,\n" +
            "\tTYJJ.JHTRRR,\n" +
            "\tTYJJ.SFDQBJYHDSJ,\n" +
            "\tTYJJ.BGYY,\n" +
            "\tTYJJ.SSSJJGMC,\n" +
            "\tTYJJ.STATUS\n" +
            "FROM\n" +
            "\tTBL_YQNS_JHGL_JH TYJJ WHERE TYJJ.JHID = #{fromId}")
    Map<String, Object> selectJHById(Integer fromId);

    @Select("SELECT\n" +
            "\tTYJ.JHXQID,\n" +
            "\tTYJ.CJR,\n" +
            "\tTYJ.CJSJ,\n" +
            "\tTYJ.EXT1,\n" +
            "\tTYJ.EXT2,\n" +
            "\tTYJ.EXT3,\n" +
            "\tTYJ.ORGID,\n" +
            "\tTYJ.GXR,\n" +
            "\tTYJ.GXSJ,\n" +
            "\tTYJ.SPZT,\n" +
            "\tTYJ.JHXQMC,\n" +
            "\tTYJ.SJXMLX,\n" +
            "\tTYJ.BZ,\n" +
            "\tTYJ.XMLXR,\n" +
            "\tTYJ.LXDH,\n" +
            "\tTYJ.TBDW,\n" +
            "\tTYJ.TBSJ,\n" +
            "\tTYJ.ZZFS,\n" +
            "\tTYJ.JYSJSSSJ,\n" +
            "\tTYJ.SJYJ,\n" +
            "\tTYJ.SJMB,\n" +
            "\tTYJ.SJFW,\n" +
            "\tTYJ.QTQKSM,\n" +
            "\tTYJ.XMTZQD,\n" +
            "\tTYJ.GSPFTZJE,\n" +
            "\tTYJ.XYWCTZJE,\n" +
            "\tTYJ.YJZTZJE,\n" +
            "\tTYJ.QZXTWDWCJE,\n" +
            "\tTYJ.NJGYSSJ,\n" +
            "\tTYJ.SYXHGSJ,\n" +
            "\tTYJ.JSWCSJ,\n" +
            "\tTYJ.JUESWCSJ,\n" +
            "\tTYJ.STATUS\n" +
            "FROM\n" +
            "\tTBL_YQNS_JHXQ TYJ WHERE TYJ.JHXQID = #{fromId}")
    Map<String, Object> selectJHXQById(Integer fromId);
}
