-- =============================================================
-- AI 数据治理 - 元数据存储 DDL（达梦 DM8 语法；自动建表失败时手工执行）
-- MySQL 版本：CLOB 改 LONGTEXT，BIGINT 不变，VARCHAR 加长度即可
-- =============================================================
CREATE TABLE IF NOT EXISTS GOV_DATA_SOURCE (
  ID             VARCHAR(64)  PRIMARY KEY,
  USER_ID        VARCHAR(64),
  NAME           VARCHAR(200),
  DB_TYPE        VARCHAR(20),
  HOST           VARCHAR(200),
  PORT           INT,
  DB_NAME        VARCHAR(200),
  USERNAME       VARCHAR(200),
  PASSWORD_B64   VARCHAR(800),
  DOMAIN         VARCHAR(100),
  TABLE_COUNT    INT DEFAULT 0,
  DOMAIN_STATS   CLOB,
  LAST_SCAN_TIME VARCHAR(40),
  CREATE_TIME    VARCHAR(40),
  UPDATE_TIME    VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS GOV_TABLE_META (
  SOURCE_ID     VARCHAR(64)  NOT NULL,
  TABLE_NAME    VARCHAR(200) NOT NULL,
  TABLE_COMMENT VARCHAR(1000),
  DOMAIN        VARCHAR(100),
  TABLE_ROWS    BIGINT DEFAULT 0,
  COLUMN_COUNT  INT DEFAULT 0,
  COLUMNS_JSON  CLOB,
  UPDATE_TIME   VARCHAR(40),
  PRIMARY KEY (SOURCE_ID, TABLE_NAME)
);

CREATE TABLE IF NOT EXISTS GOV_CONTEXT (
  USER_ID     VARCHAR(64) PRIMARY KEY,
  CTX_JSON    CLOB,
  UPDATE_TIME VARCHAR(40)
);
