package com.huabo.monitor.mysql.mapper;

import org.apache.ibatis.annotations.Select;

import java.util.Map;

/**
 * <p>
 *  Mapper 接口
 * </p>
 *
 * @author huabo
 * @since 2022-04-27
 */
public interface YMFormDataMySqlMapper{

	@Select("SELECT CONTRACTID AS CONTRACTID,	CONTRACTNAME AS CONTRACTNAME,TCU.CONTRACTBD AS CONTRACTBD, CONTRACTNO AS CONTRACTNO,	CONTRACTMONEY AS CONTRACTMONEY,	DEPT.PKYMORGID AS CONTRACTDEPT,	TCU.STARTDATE AS STARTDATE,	TCU.ENDDATE AS ENDDATE,	TCU.CONTRACTITEM AS CONTRACTITEM,	TCU.CONTRACTTYPE AS CONTRACTTYPE,	TCU.CONTRACTDATETYPE AS CONTRACTDATETYPE,	BUDGET.BUDGETNAME AS CONTRACTXDFXINFO,	TCU.DCTYPE AS DCTYPE,	TCU.CONTRACTCHILDREN AS CONTRACTCHILDREN,	STAFF.PKYMSTAFFID AS CONTRACTSTAFF,	UNIT.PKYMORGID AS CONTRACTORG,	TCB.BANKACCOUNT AS BANKACCOUNT,	TCB.BANKKHYH AS BANKKHYH,	TCU.CONTRACTXZ AS CONTRACTXZ,	TCU.CONTRACTDATETYPE AS CONTRACTDATETYPE,	TCU.MONEYTYPE AS MONEYTYPE,	ENTRU.REALNAME AS REALNAME FROM TBL_CYHW_UNIT TCU	LEFT JOIN TBL_ORGANIZATION DEPT ON TCU.CONTRACTDEPT = DEPT.ORGID LEFT JOIN TBL_CYHW_PROJECTBUDGET BUDGET ON TCU.CONTRACTXDFXINFO = BUDGET.BUDGETID LEFT JOIN TBL_ORGANIZATION UNIT ON TCU.ZXUNIT = UNIT.ORGID LEFT JOIN TBL_STAFF STAFF ON TCU.CONTRACTSTAFF = STAFF.STAFFID LEFT JOIN TBL_COUNTERPART_BANKINFO TCB ON TCU.COUNTERPARTBANK = TCB.BANKID LEFT JOIN TBL_STAFF ENTRU ON TCU.ENTRUSTSTAFFID = ENTRU.STAFFID WHERE CONTRACTID = #{fromId} ")
	Map<String, Object> selectCyhwUnitMapById(Integer fromId) throws Exception;

	@Select("SELECT UNIT.CONTRACTNAME AS CONTRACTNAME,UNIT.CONTRACTNO AS CONTRACTNO,UNIT.CONTRACTTYPE AS CONTRACTTYPE,UNIT.CONTRACTMONEY AS CONTRACTMONEY,TCPB.BUDGETID AS BUDGETID,TCPB.PROJECTGOAL AS PROJECTGOAL, TCPB.COUNTERPARTCODE AS COUNTERPARTCODE, TCPB.COUNTERPARTHANK AS COUNTERPARTHANK,TCPB.CREATETIME AS CREATETIME FROM TBL_CYHW_PROJECTBUDGET TCPB LEFT JOIN TBL_CYHW_UNIT UNIT ON TCPB.RECORDPARENT = UNIT.CONTRACTID WHERE BUDGETID = #{fromId}")
	Map<String, Object> selectHTYYMapById(Integer fromId);

	@Select("SELECT CONTRACTID AS CONTRACTID,	CONTRACTNAME AS CONTRACTNAME,TCU.CONTRACTBD AS CONTRACTBD, CONTRACTNO AS CONTRACTNO,	CONTRACTMONEY AS CONTRACTMONEY,	DEPT.PKYMORGID AS CONTRACTDEPT,	TCU.STARTDATE AS STARTDATE,	TCU.ENDDATE AS ENDDATE,	TCU.CONTRACTITEM AS CONTRACTITEM,	TCU.CONTRACTTYPE AS CONTRACTTYPE,	TCU.CONTRACTDATETYPE AS CONTRACTDATETYPE,	BUDGET.BUDGETNAME AS CONTRACTXDFXINFO,	TCU.DCTYPE AS DCTYPE,	TCU.CONTRACTCHILDREN AS CONTRACTCHILDREN,	STAFF.PKYMSTAFFID AS CONTRACTSTAFF,	UNIT.PKYMORGID AS CONTRACTORG,	TCB.BANKACCOUNT AS BANKACCOUNT,	TCB.BANKKHYH AS BANKKHYH,	TCU.CONTRACTXZ AS CONTRACTXZ,	TCU.CONTRACTDATETYPE AS CONTRACTDATETYPE,	TCU.MONEYTYPE AS MONEYTYPE,	ENTRU.REALNAME AS REALNAME, TCU.CHANGETYPE AS CHANGETYPE,TCU.CHANGEDATE AS CHANGEDATE,TCU.CHANGEDESC AS CHANGEDESC FROM TBL_CYHW_UNIT TCU	LEFT JOIN TBL_ORGANIZATION DEPT ON TCU.CONTRACTDEPT = DEPT.ORGID LEFT JOIN TBL_CYHW_PROJECTBUDGET BUDGET ON TCU.CONTRACTXDFXINFO = BUDGET.BUDGETID LEFT JOIN TBL_ORGANIZATION UNIT ON TCU.ZXUNIT = UNIT.ORGID LEFT JOIN TBL_STAFF STAFF ON TCU.CONTRACTSTAFF = STAFF.STAFFID LEFT JOIN TBL_COUNTERPART_BANKINFO TCB ON TCU.COUNTERPARTBANK = TCB.BANKID LEFT JOIN TBL_STAFF ENTRU ON TCU.ENTRUSTSTAFFID = ENTRU.STAFFID WHERE CONTRACTID = #{fromId} ")
	Map<String, Object> selectCyhwUnitBGMapById(Integer fromId);

	@Select("SELECT BLACKTYPE AS BLACKTYPE,EFFECTDATE AS EFFECTDATE,BUDGETNAME AS BUDGETNAME,COUNTERPARTNO AS COUNTERPARTNO,PROJECTRISK AS PROJECTRISK,CRETIFICATENO AS CRETIFICATENO,TOTALTMONEY AS TOTALMONEY,PSTARTDATE AS PSTARTDATE,PENDDATE AS PENDDATE,PROJECTSTAGEGOAL AS PROJECTSTAGEGOAL,RESULTDESCRIPTION AS RESULTDESCRIPTION,CONTACTS AS CONTACTS,COUNTERPARTDESC AS COUNTERPARTDESC,SERVICETYPE AS SERVICETYPE FROM TBL_CYHW_PROJECTBUDGET WHERE BUDGETID = #{fromId}")
	Map<String, Object> selectHMDGLMapById(Integer fromId) throws Exception;

	@Select("SELECT TNA.PLANID AS PLANID,TNA.PLANCODE AS PLANCODE,TNA.PLANNAME AS PLANNAME,TNA.PALNYEAR AS PALNYEAR ,TNA.PLANTYPE AS PLANTYPE ,TNA.STARTTIME AS STARTTIME,TNA.ENDTIME AS ENDTIME ,TNA.CREATETIME AS CREATETIME, TS.PKYMSTAFFID AS CREATESTAFF ,ORG.PKYMORGID AS AUDITORG  FROM TBL_NBSJ_AUDITPLAN TNA LEFT JOIN TBL_STAFF TS ON TNA.CREATESTAFFID = TS.STAFFID LEFT JOIN TBL_ORGANIZATION ORG ON TNA.AUDITORGID = ORG.ORGID WHERE PLANID = #{fromId}")
	Map<String, Object> selectJHGLMapById(Integer fromId) throws Exception;

	@Select("SELECT TNP.PRJOECTNAME AS PROJECTNAME,	TNP.PROJECTTYPE AS PROJECTTYPE,	IFNULL( AUDITORG.ORGNAME, AUDITSTA.REALNAME ) AS AUDITOBJ,	TNP.PLANYEAR AS PLANYEAR,	TNP.AUDITTYPE AS AUDITTYPE,	TNP.PROJECTSOURCE AS PROJECTSOURCE,	TNP.STARTDATE AS STARTDATE,	TNP.ENDDATE AS ENDDATE,	PM.PKYMSTAFFID AS ITEMPM,	TNP.PRO_SJFS AS PROSJFS,	TNP.CNTTYPE AS CNTTYPE,	TNP.COSTS AS COSTS,	TNP.EXTERNALASSIG AS EXTERNALASSIG,	JBORG.PKYMORGID AS COSPOMSORDEPARTMENT,	TNP.IMPLEMENTAION AS IMPLEMENTAION,	TNP.AUDITREQUIREMENTS AS AUDITREQUIREMENTS,	TNP.IMPLEMENTAIONSTEPS AS IMPLEMENTAIONSTEPS,	TNP.PURPOSE AS PURPOSE,	TNP.SCOPES AS SCOPES,	TNP.PURSUANT AS PURSUANT FROM TBL_NBSJ_PROJECT TNP LEFT JOIN TBL_ORGANIZATION AUDITORG ON AUDITORG.ORGID = TNP.AUDITORG LEFT JOIN TBL_STAFF AUDITSTA ON AUDITSTA.STAFFID = TNP.AUDITSTAFFID	LEFT JOIN TBL_STAFF PM ON PM.STAFFID = TNP.PMID	LEFT JOIN TBL_ORGANIZATION JBORG ON JBORG.ORGID = TNP.COSPOMSORDEPARTMENT WHERE	TNP.PROJECTID = #{fromId}")
	Map<String, Object> selectXMGLMapById(Integer fromId);

	@Select("SELECT TFIA.INSTITUTIONAUDITID AS INSTITUTIONAUDITID,TFIA.MATTERSINFORMEDPERSONNEL AS MATTERSINFORMEDPERSONNEL,"
			+ "	TFIA.MATTERSINSTRUCTIONS AS MATTERSINSTRUCTIONS,TFIA.HOSTDEPARTMENTOPINION AS HOSTDEPARTMENTOPINION,"
			+ "	TFIA.RELATEDDEPARTMENTOPINION AS RELATEDDEPARTMENTOPINION,TFIA.TEAMLEADEROPINION AS TEAMLEADEROPINION,"
			+ "	TFIA.FIRMLEADEROPINION AS FIRMLEADEROPINION,TFIA.CREATOR AS CREATOR,TFIA.CREATEDTIME AS CREATEDTIME"
			+ "	FROM TBL_FWGL_INSTITUTION_AUDIT TFIA WHERE INSTITUTIONAUDITID = {fromId}")
	Map<String, Object> selectHTDLMapById(Integer fromId);
	@Select("SELECT TFIA.INSTITUTIONAUDITID AS INSTITUTIONAUDITID,TFIA.AUDITNAME AS AUDITNAME,TFIA.OPINIONNAME AS OPINIONNAME,TFIA.AUDITBELONGGROUPID AS AUDITBELONGGROUPID,TFIA.DRAFTADMINISTRATOROPINION AS DRAFTADMINISTRATOROPINION,TFIA.DRAFTDEPARTMENTOPINION AS DRAFTDEPARTMENTOPINION,TFIA.DRAFTDEPARTMENTOPINIONSUCK AS DRAFTDEPARTMENTOPINIONSUCK FROM TBL_FWGL_INSTITUTION_AUDIT TFIA WHERE INSTITUTIONAUDITID = #{fromId}")
	Map<String, Object> selectZDSHMapById(Integer fromId);

	@Select("SELECT" + "TLDT.INSTITUTIONAUDITID AS INSTITUTIONAUDITID,"
			+ "	TLDT.MATTERSINFORMEDPERSONNEL AS MATTERSINFORMEDPERSONNEL,"
			+ "	TLDT.MATTERSINSTRUCTIONS AS MATTERSINSTRUCTIONS,"
			+ "	TLDT.HOSTDEPARTMENTOPINION AS HOSTDEPARTMENTOPINION,"
			+ "	TLDT.RELATEDDEPARTMENTOPINION AS RELATEDDEPARTMENTOPINION,"
			+ "	TLDT.TEAMLEADEROPINION AS TEAMLEADEROPINION," + "	TLDT.FIRMLEADEROPINION AS FIRMLEADEROPINION,"
			+ "	TLDT.CREATOR AS CREATOR," + "TLDT.CREATEDTIME AS CREATEDTIME" + "FROM"
			+ "	TBL_LEGAL_DISPUTREGISTRATION TLDT" + "WHERE" + "	INSTITUTIONAUDITID = #{fromId}")
	Map<String, Object> selectJYSXSHMapById(Integer fromId);

	@Select("SELECT tst.REALNAME AS ZXSTAFFNAME, "
			+ "			tld.DISPUTEID AS DISPUTEID, tld.DISPUTESTATUS AS DISPUTESTATUS, tld.DISPUTETYPE AS DISPUTETYPE,tld.ISUEGENT AS ISUEGENT, "
			+ "			tld.WHETHERSUED AS WHETHERSUED, tld.LASTDEALDATE AS LASTDEALDATE, tld.SOLUTIONSUGGESTIONS AS SOLUTIONSUGGESTIONS, tld.PLAINTIFF AS PLAINTIFF, "
			+ "			tld.DEFENDANT AS DEFENDANT, tld.ATTORNEY AS, "
			+ "			tld.ISATTORNEY AS ISATTORNEY,tld.URGENTMEMO AS, "
			+ "			tld.COUNSELEXAM AS COUNSELEXAM,tld.LEGALEXAM AS LEGALEXAM, "
			+ "			tld.CHAIRMANEXAM AS CHAIRMANEXAM, tld.GMANEXAM AS GMANEXAM, "
			+ "			tld.*, ts.REALNAME AS REALNAME,tcu.*,org.* "
			+ "	FROM TBL_LEGAL_DISPUTREGISTRATION "
			+ "	tld LEFT "
			+ "	JOIN TBL_STAFF "
			+ "	tst on tld.DISPUTEUNDERTAKER= "
			+ "	tst.STAFFID LEFT "
			+ "	JOIN TBL_CYHW_UNIT "
			+ "	tcu ON tld.CONTRACTINFO= "
			+ "	tcu.CONTRACTID LEFT "
			+ "	JOIN TBL_STAFF "
			+ "	ts ON tld.CREATESTAFF= "
			+ "	ts.STAFFID INNER "
			+ "	JOIN TBL_ORGANIZATION "
			+ "	org ON ts.ORGID= "
			+ "	org.ORGID WHERE tld.DISPUTEID=#{fromId}")
	Map<String, Object> selectJFDJMapById(Integer fromId);
	
	@Select("SELECT "
			+ "	TLND.COUNTERPART AS COUNTERPART, "
			+ "	TLND.COUNTERPARTPHONE AS COUNTERPARTPHONE, "
			+ "	TLND.ISAGGREE AS ISAGGREE, "
			+ "	TLND.NEGETIARESULT AS NEGETIARESULT, "
			+ "	TLND.SOLUTIONMODE AS SOLUTIONMODE "
			+ "FROM "
			+ "	TBL_LEGAL_NEGOTIATEDSETTLEMEN TLND "
			+ "WHERE "
			+ "	NEGOTIAID = #{fronId}")
	Map<String, Object> selectXSGCMapById(Integer fromId);
	
	@Select("SELECT "
			+ "	TLAP.ANNUALPLANID AS ANNUALPLANID, "
			+ "	TLAP.ANNUALPLANNAME AS ANNUALPLANNAME, "
			+ "	TLAP.ANNUALPLANCREATOR AS ANNUALPLANCREATOR, "
			+ "	TLAP.ANNUALPLANCREATEDTIME AS ANNUALPLANCREATEDTIME "
			+ "FROM "
			+ "	TBL_FWGL_ANNUAL_PLAN TLAP "
			+ "WHERE "
			+ "	ANNUALPLANID = #{fronId}")
	Map<String, Object> selectNDJHMapById(Integer fromId);

	@Select("SELECT "
			+ "TC.PRACTICEAPPLYID AS PRACTICEAPPLYID, "
			+ "TC.PRACTICEAPPLYNAME AS PRACTICEAPPLYNAME, "
			+ "TC.SEX AS SEX, "
			+ "TC.AGE AS AGE, "
			+ "TC.NATION AS NATION, "
			+ "TC.IDENTITYCARD AS IDENTITYCARD, "
			+ "TC.POLITICSSTATUS AS POLITICSSTATUS, "
			+ "TC.CERTIFICATIONNUMBER AS CERTIFICATIONNUMBER, "
			+ "TC.PHONE AS PHONE, "
			+ "TC.TECHNICALPOSITION AS TECHNICALPOSITION, "
			+ "TC.AWARD AS AWARD, "
			+ "TC.PUNISHMENT AS PUNISHMENT, "
			+ "TS.REALNAME AS REALNAME  "
			+ "FROM "
			+ "	TBL_FWGL_PRACTICE_APPLY  TC "
			+ "	LEFT JOIN TBL_STAFF TS ON TC.STAFFID = TS.STAFFID  "
			+ "WHERE "
			+ "	PRACTICEAPPLYID =#{ fromId }")
	Map<String, Object> selectZYSQMapById(Integer fromId);
	
	@Select("SELECT * FROM TBL_FWGL_LEGAL_ADVISER WHERE ADVISERID =#{fromId}")
	Map<String, Object> selectZFLGWMapById(Integer fromId);


}
