spring:
 application:
  name: hbyunSystemSetting #应用名称
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:dm://192.0.2.200:5236/REDACTED?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  username: REDACTED
  password: REDACTED
  driverClassName: dm.jdbc.driver.DmDriver
 druid:
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatement: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall,log4j
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
 redis:
  host: 192.0.2.200
  port: 6379
  password: 

#日志配置
logging:
 level:
  org:
   springframework: WARN
   spring:
    springboot:
     dao: info
  com:
   dc:
    pcasweb:
     mapper: debug
 file: logs/spring-boot-logging.log
 
 # 文件保存目录
file:
 ca:
  secret: b8e9a1c7d4f265a830e7b1f4d8a9c6e2
 upload:
  path: E:\datafile
 previewUrl: http://192.0.2.200:8012/onlinePreview?url=
 downloadUrl: https://www.wenxin.example.com/api/file/file/download/decrypt?fileId=
 
#eureka服务注册中心配置
eureka:
 instance:
  ip-address: 192.0.2.200
  instance-id: hbyunSystemSetting-8763
  prefer-ip-address: true
  hostname: hbyun-systemSetting-service
 client:
  serviceUrl:
   defaultZone: http://hbyunadmin:hbEureka12345@192.0.2.200:8761/eureka
security:
  basic:
    enabled: false

 # 文件保存目录
file:
 ca:
  secret: b8e9a1c7d4f265a830e7b1f4d8a9c6e2
 upload:
  path: D:\datafile
 previewUrl: http://192.0.2.200:8012/onlinePreview?url=
 downloadUrl: https://www.wenxin.example.com/api/file/file/download/decrypt?fileId=

acurl: http://192.0.2.200:8003
formurl: http://192.0.2.200:8001
activitiModelerUrl: http://192.0.2.200:8137
getOrgChildrenUrl: http://192.0.2.200:8379
insertOrgOneUrl: http://192.0.2.200:8379
redisurl: http://192.0.2.200:8379

mybatis:
 configuration:
  map-underscore-to-camel-case: true
application:
 #文件上传
 file-upload:
  base-dir: D:\nginx-1.20.2\html\hbfk
  #base-url: http://192.0.2.200/hbfk
  base-url: http://192.0.2.200/hbfk
 #图片上传前缀域名
 file-url: http://cn-gz-txy.starryfrp.example:64108
 #上帝视角用户名称
 admin-name: 张孝昆