server:
  port: 8681
  max-http-header-size: 50MB

spring:
  application:
    name: hbyunExchangeRateService

# 日志配置
logging:
  level:
    com:
      global:
        treasurer: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 简化版不需要数据库连接
mybatis:
  enabled: false