package com.huabo.audit.oracle.mapper;

import com.hbfk.util.PageInfo;
import com.huabo.audit.oracle.entity.TblYqnsSqdcbg;

import java.math.BigDecimal;

import org.apache.commons.lang3.StringUtils;

/**
 * @author wangys
 * @description 针对表【TBL_YQNS_SQDCBG(审前调查报告表)】的数据库操作Mapper
 * @Entity TblYqnsSqdcbg
 */
public class TblYqnsXmdqMapperSqlConfig {
	
	public String selectAuditControlAnalysisService(Integer choiceType, BigDecimal staffId, String staffName) throws Exception {
		
		StringBuffer sb = new StringBuffer("");
		if(choiceType == 1) {
			//维度 ：年度
			sb.append("SELECT YEARCOL AS XMND,(SELECT COUNT(0) FROM TBL_YQNS_XMQD TYX LEFT JOIN TBL_YQNS_JHGL_JH TYJJ ON TYX.PLANID = TYJJ.JHID LEFT JOIN TBL_STAFF TS ON TYX.CREATESTAFFID = TS.STAFFID WHERE TYX.STATUS = 1 AND TYJJ.XMND = YV.YEARCOL) AS ITEMCOUNT ," + 
					" (SELECT COUNT(0) FROM TBL_YQNS_AUDIT_MY_MANUSCRIPT WHERE TO_CHAR(CREATETIME, 'YYYY') = YV.YEARCOL AND PROBLEMDRAFT = 1) AS WORKSHEETQUCOUNT," + 
					" (SELECT COUNT(0) FROM TBL_YQNS_AUDIT_MY_MANUSCRIPT WHERE TO_CHAR(CREATETIME, 'YYYY') = YV.YEARCOL AND PROBLEMDRAFT = 0) AS WORKSHEETFHCOUNT," + 
					" (SELECT COUNT(0) FROM TBL_YQNS_GZFA WHERE SPZT = 6 AND TO_CHAR(CJSJ, 'YYYY') = YV.YEARCOL ) AS WORKPLANCOUNT," + 
					" (SELECT COUNT(0) FROM TBL_YQNS_IMPLEMENT_PLAN WHERE SPZT = 6 AND PLAN_YEAR = YV.YEARCOL) AS IMPLSUPERCOUNT," + 
					" (SELECT COUNT(0) FROM TBL_YQNS_AUDIT_OVERSEE_RECORDS WHERE STATUS = 6 AND TO_CHAR(CREATETIME, 'YYYY') = YV.YEARCOL) AS AOVERCOUNT " + 
					" FROM YEAV_VIEW  YV " + 
					" ORDER BY YEARCOL ASC ");
		}else { 
			//维度 ： 人员和年度
			sb.append("SELECT PV.STAFFID AS STAFFID,PV.STAFFNAME AS STAFFNAME,YV.YEARCOL AS XMND," + 
					" (SELECT COUNT(0) FROM TBL_YQNS_XMQD TYX LEFT JOIN TBL_YQNS_JHGL_JH TYJJ ON TYX.PLANID = TYJJ.JHID LEFT JOIN TBL_STAFF TS ON TYX.CREATESTAFFID = TS.STAFFID WHERE TYX.STATUS = 1 AND TYJJ.XMND = YV.YEARCOL AND TYX.CREATESTAFFID = PV.STAFFID) AS ITEMCOUNT ," + 
					" (SELECT COUNT(0) FROM TBL_YQNS_AUDIT_MY_MANUSCRIPT WHERE TO_CHAR(CREATETIME, 'YYYY') = YV.YEARCOL AND PROBLEMDRAFT = 1 AND (CREATEUSER = PV.STAFFID OR THEDEPTSTAFFID = PV.STAFFID)) AS WORKSHEETQUCOUNT," + 
					" (SELECT COUNT(0) FROM TBL_YQNS_AUDIT_MY_MANUSCRIPT WHERE TO_CHAR(CREATETIME, 'YYYY') = YV.YEARCOL AND PROBLEMDRAFT = 0 AND (CREATEUSER = PV.STAFFID OR THEDEPTSTAFFID = PV.STAFFID)) AS WORKSHEETFHCOUNT," + 
					" (SELECT COUNT(0) FROM TBL_YQNS_GZFA WHERE SPZT = 6 AND TO_CHAR(CJSJ, 'YYYY') = YV.YEARCOL AND EXT1 = PV.STAFFID) AS WORKPLANCOUNT," + 
					" (SELECT COUNT(0) FROM TBL_YQNS_IMPLEMENT_PLAN WHERE SPZT = 6 AND PLAN_YEAR = YV.YEARCOL AND ( ZSSTAFFID = PV.STAFFID  OR CREATESTAFFID = PV.STAFFID OR PROJECT_ORDER_ID = PV.STAFFID)) AS IMPLSUPERCOUNT," + 
					" (SELECT COUNT(0) FROM TBL_YQNS_AUDIT_OVERSEE_RECORDS WHERE STATUS = 6 AND TO_CHAR(CREATETIME, 'YYYY') = YV.YEARCOL AND ( CREATESTAFFID = PV.STAFFID OR SUPERVISIONPARTICIPANTSID = PV.STAFFID OR ECONOMICID = PV.STAFFID )) AS AOVERCOUNT" + 
					" FROM PERSON_VIEW PV LEFT JOIN YEAV_VIEW YV ON 1 = 1 WHERE 1 = 1 and PV.STAFFID IS not NULL ");
			if(staffId != null) {
				sb.append(" AND PV.STAFFID = ").append(staffId);
			}
			
			if(StringUtils.isNotBlank(staffName)) {
				sb.append(" AND PV.STAFFNAME LIKE '%").append(staffName).append("%'");
			}
			
			sb.append(" ORDER BY PV.STAFFID ASC,YV.YEARCOL ASC");
		}
		
		
		
		
		String sql = sb.toString();
		return sql;
	}

    public String selectAuditProjectPlanAnalysisList(Integer xmnd) {
        StringBuffer sb = new StringBuffer("SELECT XMND,YWCCOUNT,SSZCOUNT,(GLZSJ+ALLOACOUNT-YWCCOUNT-SSZCOUNT) AS WQDCOUNT, CASE WHEN (NCCOUNT+NCCOACOUNT) = 0 THEN 0 ELSE ROUND(((YWCCOUNT+SSZCOUNT)/(NCCOUNT+NCCOACOUNT))*100, 2) END AS ZXL FROM (")
        		.append(" SELECT XMND, (SELECT COUNT(0) FROM TBL_YQNS_XMQD TYX LEFT JOIN TBL_YQNS_JHGL_JH TYJ ON TYX.PLANID = TYJ.JHID WHERE TYJ.XMND = TYJJ.XMND AND SYSDATE > SITEENDTIME) AS YWCCOUNT , ")
        		.append(" (SELECT COUNT(0) FROM TBL_YQNS_XMQD TYX LEFT JOIN TBL_YQNS_JHGL_JH TYJ ON TYX.PLANID = TYJ.JHID WHERE TYJ.XMND = TYJJ.XMND AND SYSDATE <= SITEENDTIME) AS SSZCOUNT ,")
        		.append(" (SELECT COUNT(0) FROM TBL_YQNS_OTHERAUDIT WHERE DRAFTPLANID IN (SELECT JHID FROM TBL_YQNS_JHGL_JH WHERE XMND = TYJJ.XMND)) AS ALLOACOUNT,")
        		.append(" (SELECT COUNT(0) FROM TBL_YQNS_JHGL_JH_GL WHERE JHID IN (SELECT JHID FROM TBL_YQNS_JHGL_JH WHERE XMND = TYJJ.XMND)) AS GLZSJ,")
        		.append(" (SELECT COUNT(0) FROM TBL_YQNS_OTHERAUDIT WHERE DRAFTPLANID IN (SELECT JHID FROM TBL_YQNS_JHGL_JH WHERE XMND = TYJJ.XMND AND JHLX = 1)) AS NCCOACOUNT,")
        		.append(" (SELECT COUNT(0) FROM TBL_YQNS_JHGL_JH_GL WHERE JHID IN (SELECT JHID FROM TBL_YQNS_JHGL_JH WHERE XMND = TYJJ.XMND AND JHLX = 1 )) AS NCCOUNT")
        		.append(" FROM TBL_YQNS_JHGL_JH TYJJ ");
        if(xmnd != null) {
        	sb.append(" WHERE TYJJ.XMND = ").append(xmnd);
        }

        sb.append(" GROUP BY TYJJ.XMND ORDER BY TYJJ.XMND DESC ) T1 ");
        return sb.toString();
    }
    
    public String selectPlanAnalysisXmList(Integer xmnd, Integer dataType) {
    	StringBuffer sb = new StringBuffer("SELECT TYX.* FROM TBL_YQNS_XMQD TYX LEFT JOIN TBL_YQNS_JHGL_JH TYJ ON TYX.PLANID = TYJ.JHID WHERE TYJ.XMND = "+xmnd);
    	if(dataType == 1){
    		sb.append(" AND SYSDATE > SITEENDTIME");
    	}else {
    		sb.append(" AND SYSDATE <= SITEENDTIME");
    	}
        return sb.toString();
    	
    }


}




