/*
 Navicat Premium Data Transfer

 Source Server         : 192.0.2.200
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 192.0.2.200:1521
 Source Schema         : REDACTED

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 09/05/2024 21:35:52
*/


-- ----------------------------
-- Table structure for TBL_GBI_APPLICATION_CONFIG
-- ----------------------------
DROP TABLE "REDACTED"."TBL_GBI_APPLICATION_CONFIG";
CREATE TABLE "REDACTED"."TBL_GBI_APPLICATION_CONFIG" (
                                                          "ID" VARCHAR2(255 BYTE) NOT NULL ,
                                                          "CONTINUOUS_QUESTIONING" VARCHAR2(255 BYTE) NOT NULL ,
                                                          "USER_ID" NUMBER(11) NOT NULL ,
                                                          "CREATE_TIME" DATE NOT NULL ,
                                                          "UPDATE_TIME" DATE ,
                                                          "DELETED" NUMBER(1) DEFAULT 0  NOT NULL ,
                                                          "CREATE_COMPANY" VARCHAR2(255 BYTE) ,
                                                          "CREATE_DEPT" VARCHAR2(255 BYTE)
)
    TABLESPACE "HBGRCZZ_DATA"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "REDACTED"."TBL_GBI_APPLICATION_CONFIG"."CONTINUOUS_QUESTIONING" IS '1-自动联系上下文回答，2仅基于当前提问回答';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_APPLICATION_CONFIG"."USER_ID" IS '用户id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_APPLICATION_CONFIG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_APPLICATION_CONFIG"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_APPLICATION_CONFIG"."DELETED" IS '是否删除';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_APPLICATION_CONFIG"."CREATE_COMPANY" IS '创建企业';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_APPLICATION_CONFIG"."CREATE_DEPT" IS '创建部门';
COMMENT ON TABLE "REDACTED"."TBL_GBI_APPLICATION_CONFIG" IS '应用配置表';

-- ----------------------------
-- Table structure for TBL_GBI_BATCH
-- ----------------------------
DROP TABLE "REDACTED"."TBL_GBI_BATCH";
CREATE TABLE "REDACTED"."TBL_GBI_BATCH" (
                                             "ID" VARCHAR2(255 BYTE) NOT NULL ,
                                             "APP_ID" VARCHAR2(255 BYTE) ,
                                             "BATCH_NO" VARCHAR2(255 BYTE) NOT NULL ,
                                             "ATTNAME" VARCHAR2(255 BYTE) NOT NULL ,
                                             "ATTPATH" VARCHAR2(255 BYTE) NOT NULL ,
                                             "ATTSIZE" NUMBER(38,4) NOT NULL ,
                                             "USER_ID" NUMBER(11) NOT NULL ,
                                             "CREATE_TIME" DATE NOT NULL ,
                                             "CREATE_COMPANY" VARCHAR2(255 BYTE) ,
                                             "CREATE_DEPT" VARCHAR2(255 BYTE)
)
    TABLESPACE "HBGRCZZ_DATA"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "REDACTED"."TBL_GBI_BATCH"."ID" IS '主键id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_BATCH"."APP_ID" IS 'appId';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_BATCH"."BATCH_NO" IS '批次编号，目前暂时和id一样，之后可支持批次多文件';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_BATCH"."ATTNAME" IS '原文件名称';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_BATCH"."ATTPATH" IS '文件ftp地址';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_BATCH"."ATTSIZE" IS '文件大小';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_BATCH"."USER_ID" IS '用户id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_BATCH"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_BATCH"."CREATE_COMPANY" IS '企业';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_BATCH"."CREATE_DEPT" IS '部门';
COMMENT ON TABLE "REDACTED"."TBL_GBI_BATCH" IS 'GBI导入批次表';

-- ----------------------------
-- Table structure for TBL_GBI_COLUMNS
-- ----------------------------
DROP TABLE "REDACTED"."TBL_GBI_COLUMNS";
CREATE TABLE "REDACTED"."TBL_GBI_COLUMNS" (
                                               "ID" VARCHAR2(255 BYTE) NOT NULL ,
                                               "APP_ID" VARCHAR2(255 BYTE) ,
                                               "BATCH_NO" VARCHAR2(255 BYTE) NOT NULL ,
                                               "COLUMN_NAME" VARCHAR2(255 BYTE) NOT NULL ,
                                               "COLUMN_COMMENT" VARCHAR2(255 BYTE) ,
                                               "DATA_BASE" VARCHAR2(255 BYTE) ,
                                               "DATA_SOURCE_ID" VARCHAR2(255 BYTE) ,
                                               "DEMO" VARCHAR2(255 BYTE) ,
                                               "INDEXED" NUMBER(1) DEFAULT 0  NOT NULL ,
                                               "LABELS" VARCHAR2(255 BYTE) ,
                                               "PARENT_COLUMN" VARCHAR2(255 BYTE) ,
                                               "CELL_TYPE" VARCHAR2(255 BYTE) NOT NULL ,
                                               "USER_ID" NUMBER(11) NOT NULL ,
                                               "CREATE_TIME" DATE NOT NULL ,
                                               "UPDATE_TIME" DATE ,
                                               "DELETED" NUMBER(1) DEFAULT 0  NOT NULL ,
                                               "CREATE_COMPANY" VARCHAR2(255 BYTE) ,
                                               "CREATE_DEPT" VARCHAR2(255 BYTE) ,
                                               "BATCH_ID" VARCHAR2(255 BYTE) NOT NULL ,
                                               "TABLE_ID" VARCHAR2(255 BYTE) NOT NULL ,
                                               "MAPPING_COLUMN" VARCHAR2(255 BYTE) NOT NULL ,
                                               "SORT" NUMBER(8) ,
                                               "INDEX_NAME" VARCHAR2(255 BYTE) ,
                                               "FIELD_TYPE" VARCHAR2(255 BYTE) NOT NULL
)
    TABLESPACE "HBGRCZZ_DATA"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."ID" IS '主键id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."APP_ID" IS 'appid';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."BATCH_NO" IS '批次号';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."COLUMN_NAME" IS '字段名称';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."COLUMN_COMMENT" IS '字段描述';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."DEMO" IS '字段样例';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."INDEXED" IS '是否索引1-是，0-否';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."LABELS" IS '标签数组格式[""]';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."PARENT_COLUMN" IS '父级字段';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."CELL_TYPE" IS '页面展示字段类型';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."USER_ID" IS '用户id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."DELETED" IS '是否删除1-是，0-否';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."CREATE_COMPANY" IS '创建企业';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."CREATE_DEPT" IS '创建部门';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."BATCH_ID" IS '批次记录id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."TABLE_ID" IS 'gbi表信息id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."MAPPING_COLUMN" IS '数据库真实字段名';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."SORT" IS '顺序';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."INDEX_NAME" IS '索引名称';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_COLUMNS"."FIELD_TYPE" IS '字段类型';
COMMENT ON TABLE "REDACTED"."TBL_GBI_COLUMNS" IS 'Gbi字段信息表';

-- ----------------------------
-- Table structure for TBL_GBI_KNOWLEDGE
-- ----------------------------
DROP TABLE "REDACTED"."TBL_GBI_KNOWLEDGE";
CREATE TABLE "REDACTED"."TBL_GBI_KNOWLEDGE" (
                                                 "ID" VARCHAR2(255 BYTE) NOT NULL ,
                                                 "KNOWLEDGE_KEY" VARCHAR2(255 BYTE) NOT NULL ,
                                                 "KNOWLEDGE_VALUE" VARCHAR2(255 BYTE) NOT NULL ,
                                                 "USER_ID" NUMBER(11) NOT NULL ,
                                                 "CREATE_TIME" DATE NOT NULL ,
                                                 "UPDATE_TIME" DATE ,
                                                 "DELETED" NUMBER(1) DEFAULT 0  NOT NULL ,
                                                 "CREATE_COMPANY" VARCHAR2(255 BYTE) ,
                                                 "CREATE_DEPT" VARCHAR2(255 BYTE)
)
    TABLESPACE "HBGRCZZ_DATA"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "REDACTED"."TBL_GBI_KNOWLEDGE"."ID" IS '主键id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_KNOWLEDGE"."KNOWLEDGE_KEY" IS '自定义知识';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_KNOWLEDGE"."KNOWLEDGE_VALUE" IS '对大模型解释这条知识';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_KNOWLEDGE"."USER_ID" IS '用户id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_KNOWLEDGE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_KNOWLEDGE"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_KNOWLEDGE"."DELETED" IS '是否删除1-是，0-否';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_KNOWLEDGE"."CREATE_COMPANY" IS '创建企业';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_KNOWLEDGE"."CREATE_DEPT" IS '创建部门';
COMMENT ON TABLE "REDACTED"."TBL_GBI_KNOWLEDGE" IS 'GBI知识表';

-- ----------------------------
-- Table structure for TBL_GBI_TABLE
-- ----------------------------
DROP TABLE "REDACTED"."TBL_GBI_TABLE";
CREATE TABLE "REDACTED"."TBL_GBI_TABLE" (
                                             "ID" VARCHAR2(255 BYTE) NOT NULL ,
                                             "APP_ID" VARCHAR2(255 BYTE) ,
                                             "BATCH_ID" VARCHAR2(255 BYTE) NOT NULL ,
                                             "BATCH_NO" VARCHAR2(255 BYTE) NOT NULL ,
                                             "CUSTOM_TABLE" VARCHAR2(255 BYTE) NOT NULL ,
                                             "DESCRIPTION" VARCHAR2(255 BYTE) ,
                                             "TABLE_NAME" VARCHAR2(255 BYTE) NOT NULL ,
                                             "USER_ID" NUMBER(11) NOT NULL ,
                                             "CREATE_TIME" DATE NOT NULL ,
                                             "CREATE_COMPANY" VARCHAR2(255 BYTE) ,
                                             "CREATE_DEPT" VARCHAR2(255 BYTE) ,
                                             "UPDATE_TIME" DATE ,
                                             "SORT" NUMBER(8)
)
    TABLESPACE "HBGRCZZ_DATA"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."ID" IS '主键id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."APP_ID" IS 'APPID';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."BATCH_ID" IS '批次id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."BATCH_NO" IS '批次编号';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."CUSTOM_TABLE" IS '客户定义表名称';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."TABLE_NAME" IS '真实库定义的表名称';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."USER_ID" IS '用户id';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."CREATE_COMPANY" IS '企业';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."CREATE_DEPT" IS '部门';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."UPDATE_TIME" IS '修改日期';
COMMENT ON COLUMN "REDACTED"."TBL_GBI_TABLE"."SORT" IS '顺序';
COMMENT ON TABLE "REDACTED"."TBL_GBI_TABLE" IS 'GBI上传的表信息';

-- ----------------------------
-- Primary Key structure for table TBL_GBI_APPLICATION_CONFIG
-- ----------------------------
ALTER TABLE "REDACTED"."TBL_GBI_APPLICATION_CONFIG" ADD CONSTRAINT "SYS_C00377863" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TBL_GBI_APPLICATION_CONFIG
-- ----------------------------
ALTER TABLE "REDACTED"."TBL_GBI_APPLICATION_CONFIG" ADD CONSTRAINT "SYS_C00377859" CHECK ("CONTINUOUS_QUESTIONING" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_APPLICATION_CONFIG" ADD CONSTRAINT "SYS_C00377860" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_APPLICATION_CONFIG" ADD CONSTRAINT "SYS_C00377861" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_APPLICATION_CONFIG" ADD CONSTRAINT "SYS_C00377862" CHECK ("DELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table TBL_GBI_APPLICATION_CONFIG
-- ----------------------------
CREATE INDEX "REDACTED"."GBI_APPLICATION_CONFIG_USER_ID"
  ON "REDACTED"."TBL_GBI_APPLICATION_CONFIG" ("USER_ID" ASC)
  LOGGING
  TABLESPACE "HBGRCZZ_DATA"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table TBL_GBI_BATCH
-- ----------------------------
ALTER TABLE "REDACTED"."TBL_GBI_BATCH" ADD CONSTRAINT "SYS_C00377923" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TBL_GBI_BATCH
-- ----------------------------
ALTER TABLE "REDACTED"."TBL_GBI_BATCH" ADD CONSTRAINT "SYS_C00377918" CHECK ("BATCH_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_BATCH" ADD CONSTRAINT "SYS_C00377919" CHECK ("ATTNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_BATCH" ADD CONSTRAINT "SYS_C00377920" CHECK ("ATTPATH" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_BATCH" ADD CONSTRAINT "SYS_C00377921" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_BATCH" ADD CONSTRAINT "SYS_C00377922" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_BATCH" ADD CONSTRAINT "SYS_C00377924" CHECK ("ATTSIZE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table TBL_GBI_BATCH
-- ----------------------------
CREATE INDEX "REDACTED"."gbi_batch_no"
  ON "REDACTED"."TBL_GBI_BATCH" ("BATCH_NO" ASC)
  LOGGING
  TABLESPACE "HBGRCZZ_DATA"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "REDACTED"."gbi_batch_user_id"
  ON "REDACTED"."TBL_GBI_BATCH" ("USER_ID" ASC)
  LOGGING
  TABLESPACE "HBGRCZZ_DATA"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table TBL_GBI_COLUMNS
-- ----------------------------
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00377882" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TBL_GBI_COLUMNS
-- ----------------------------
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00377868" CHECK ("BATCH_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00377869" CHECK ("COLUMN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00377875" CHECK ("INDEXED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00377878" CHECK ("CELL_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00377879" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00377880" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00377881" CHECK ("DELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00377934" CHECK ("BATCH_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00377935" CHECK ("TABLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00378575" CHECK ("MAPPING_COLUMN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_COLUMNS" ADD CONSTRAINT "SYS_C00378705" CHECK ("FIELD_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table TBL_GBI_COLUMNS
-- ----------------------------
CREATE INDEX "REDACTED"."GBI_TABLE_SETTINGS_BETCH_ID"
  ON "REDACTED"."TBL_GBI_COLUMNS" ("BATCH_ID" ASC) LOCAL
  LOGGING
  ONLINE
  TABLESPACE "HBGRCZZ_DATA"
  NOSORT
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table TBL_GBI_KNOWLEDGE
-- ----------------------------
ALTER TABLE "REDACTED"."TBL_GBI_KNOWLEDGE" ADD CONSTRAINT "SYS_C00377858" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TBL_GBI_KNOWLEDGE
-- ----------------------------
ALTER TABLE "REDACTED"."TBL_GBI_KNOWLEDGE" ADD CONSTRAINT "SYS_C00377853" CHECK ("KNOWLEDGE_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_KNOWLEDGE" ADD CONSTRAINT "SYS_C00377854" CHECK ("KNOWLEDGE_VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_KNOWLEDGE" ADD CONSTRAINT "SYS_C00377855" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_KNOWLEDGE" ADD CONSTRAINT "SYS_C00377856" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_KNOWLEDGE" ADD CONSTRAINT "SYS_C00377857" CHECK ("DELETED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table TBL_GBI_KNOWLEDGE
-- ----------------------------
CREATE INDEX "REDACTED"."GBI_KNOWLEDGE_USER"
  ON "REDACTED"."TBL_GBI_KNOWLEDGE" ("USER_ID" ASC) LOCAL
  LOGGING
  ONLINE
  TABLESPACE "HBGRCZZ_DATA"
  NOSORT
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table TBL_GBI_TABLE
-- ----------------------------
ALTER TABLE "REDACTED"."TBL_GBI_TABLE" ADD CONSTRAINT "SYS_C00377932" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TBL_GBI_TABLE
-- ----------------------------
ALTER TABLE "REDACTED"."TBL_GBI_TABLE" ADD CONSTRAINT "SYS_C00377926" CHECK ("BATCH_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_TABLE" ADD CONSTRAINT "SYS_C00377927" CHECK ("BATCH_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_TABLE" ADD CONSTRAINT "SYS_C00377928" CHECK ("CUSTOM_TABLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_TABLE" ADD CONSTRAINT "SYS_C00377930" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_TABLE" ADD CONSTRAINT "SYS_C00377931" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "REDACTED"."TBL_GBI_TABLE" ADD CONSTRAINT "SYS_C00377933" CHECK ("TABLE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table TBL_GBI_TABLE
-- ----------------------------
CREATE INDEX "REDACTED"."gbi_table_betch_id"
  ON "REDACTED"."TBL_GBI_TABLE" ("BATCH_ID" ASC)
  LOGGING
  ONLINE
  TABLESPACE "HBGRCZZ_DATA"
  NOSORT
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "REDACTED"."gbi_table_user_id"
  ON "REDACTED"."TBL_GBI_TABLE" ("USER_ID" ASC) LOCAL
  LOGGING
  TABLESPACE "HBGRCZZ_DATA"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
