-- 达梦数据库财务交易表建表语句
-- 注意：达梦数据库语法特点
-- 1. 使用 COMMENT ON 语句添加注释
-- 2. 默认值语法略有不同
-- 3. 时间戳字段需要特殊处理

-- 删除表（如果存在）
DROP TABLE IF EXISTS FINANCE_TRANSACTION;

-- 创建财务交易表
CREATE TABLE FINANCE_TRANSACTION (
    ID VARCHAR(32) NOT NULL,
    TRANSACTION_NO VARCHAR(50) NOT NULL,
    TRANSACTION_TYPE INTEGER NOT NULL,
    TRANSACTION_CATEGORY INTEGER,
    PROJECT_ID VARCHAR(32),
    AMOUNT DECIMAL(15,2) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    ACCOUNT_SUBJECT VARCHAR(100),
    COUNTERPART_ACCOUNT VARCHAR(100),
    PAYMENT_METHOD VARCHAR(50),
    BANK_NAME VARCHAR(100),
    ACCOUNT_NUMBER VARCHAR(50),
    TRANSACTION_STATUS INTEGER DEFAULT 1,
    APPROVAL_STATUS INTEGER DEFAULT 1,
    APPROVER_ID VARCHAR(32),
    APPROVER_NAME VARCHAR(50),
    APPROVAL_DATE DATE,
    APPROVAL_COMMENTS CLOB,
    INVOICE_NO VARCHAR(50),
    INVOICE_AMOUNT DECIMAL(15,2),
    TAX_AMOUNT DECIMAL(15,2),
    DESCRIPTION CLOB,
    ATTACHMENT_PATH VARCHAR(500),
    MANAGER_ID VARCHAR(32),
    MANAGER_NAME VARCHAR(50),
    REMARKS CLOB,
    CREATE_BY VARCHAR(32),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE,
    UPDATE_BY VARCHAR(32),
    UPDATE_TIME TIMESTAMP DEFAULT SYSDATE,
    DEL_FLAG INTEGER DEFAULT 0,
    VERSION INTEGER DEFAULT 1,
    CONSTRAINT PK_FINANCE_TRANSACTION PRIMARY KEY (ID)
);

-- 添加表注释
COMMENT ON TABLE FINANCE_TRANSACTION IS '财务交易表';

-- 添加字段注释
COMMENT ON COLUMN FINANCE_TRANSACTION.ID IS '主键ID';
COMMENT ON COLUMN FINANCE_TRANSACTION.TRANSACTION_NO IS '交易编号';
COMMENT ON COLUMN FINANCE_TRANSACTION.TRANSACTION_TYPE IS '交易类型：1-收入，2-支出';
COMMENT ON COLUMN FINANCE_TRANSACTION.TRANSACTION_CATEGORY IS '交易分类：1-合同收款，2-材料采购，3-人工费用，4-设备租赁，5-其他费用';
COMMENT ON COLUMN FINANCE_TRANSACTION.PROJECT_ID IS '关联项目ID';
COMMENT ON COLUMN FINANCE_TRANSACTION.AMOUNT IS '交易金额';
COMMENT ON COLUMN FINANCE_TRANSACTION.TRANSACTION_DATE IS '交易日期';
COMMENT ON COLUMN FINANCE_TRANSACTION.ACCOUNT_SUBJECT IS '会计科目';
COMMENT ON COLUMN FINANCE_TRANSACTION.COUNTERPART_ACCOUNT IS '对方账户';
COMMENT ON COLUMN FINANCE_TRANSACTION.PAYMENT_METHOD IS '支付方式';
COMMENT ON COLUMN FINANCE_TRANSACTION.BANK_NAME IS '银行名称';
COMMENT ON COLUMN FINANCE_TRANSACTION.ACCOUNT_NUMBER IS '账户号码';
COMMENT ON COLUMN FINANCE_TRANSACTION.TRANSACTION_STATUS IS '交易状态：1-待审核，2-已审核，3-已完成，4-已取消';
COMMENT ON COLUMN FINANCE_TRANSACTION.APPROVAL_STATUS IS '审批状态：1-待审批，2-审批中，3-已审批，4-已拒绝';
COMMENT ON COLUMN FINANCE_TRANSACTION.APPROVER_ID IS '审批人ID';
COMMENT ON COLUMN FINANCE_TRANSACTION.APPROVER_NAME IS '审批人姓名';
COMMENT ON COLUMN FINANCE_TRANSACTION.APPROVAL_DATE IS '审批日期';
COMMENT ON COLUMN FINANCE_TRANSACTION.APPROVAL_COMMENTS IS '审批意见';
COMMENT ON COLUMN FINANCE_TRANSACTION.INVOICE_NO IS '发票号码';
COMMENT ON COLUMN FINANCE_TRANSACTION.INVOICE_AMOUNT IS '发票金额';
COMMENT ON COLUMN FINANCE_TRANSACTION.TAX_AMOUNT IS '税额';
COMMENT ON COLUMN FINANCE_TRANSACTION.DESCRIPTION IS '交易描述';
COMMENT ON COLUMN FINANCE_TRANSACTION.ATTACHMENT_PATH IS '附件路径';
COMMENT ON COLUMN FINANCE_TRANSACTION.MANAGER_ID IS '管理员ID';
COMMENT ON COLUMN FINANCE_TRANSACTION.MANAGER_NAME IS '管理员姓名';
COMMENT ON COLUMN FINANCE_TRANSACTION.REMARKS IS '备注';
COMMENT ON COLUMN FINANCE_TRANSACTION.CREATE_BY IS '创建人';
COMMENT ON COLUMN FINANCE_TRANSACTION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN FINANCE_TRANSACTION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN FINANCE_TRANSACTION.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN FINANCE_TRANSACTION.DEL_FLAG IS '删除标志：0-未删除，1-已删除';
COMMENT ON COLUMN FINANCE_TRANSACTION.VERSION IS '版本号';

-- 创建索引（达梦数据库语法）
CREATE INDEX IDX_FINANCE_TRANSACTION_NO ON FINANCE_TRANSACTION(TRANSACTION_NO);
CREATE INDEX IDX_FINANCE_TRANSACTION_TYPE ON FINANCE_TRANSACTION(TRANSACTION_TYPE);
CREATE INDEX IDX_FINANCE_TRANSACTION_PROJECT ON FINANCE_TRANSACTION(PROJECT_ID);
CREATE INDEX IDX_FINANCE_TRANSACTION_DATE ON FINANCE_TRANSACTION(TRANSACTION_DATE);
CREATE INDEX IDX_FINANCE_TRANSACTION_STATUS ON FINANCE_TRANSACTION(TRANSACTION_STATUS);
CREATE INDEX IDX_FINANCE_TRANSACTION_CREATE_TIME ON FINANCE_TRANSACTION(CREATE_TIME);

-- 创建序列（用于生成主键）
CREATE SEQUENCE SEQ_FINANCE_TRANSACTION
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    CACHE 20;

-- 插入测试数据（达梦数据库语法）
INSERT INTO FINANCE_TRANSACTION (
    ID, TRANSACTION_NO, TRANSACTION_TYPE, TRANSACTION_CATEGORY, PROJECT_ID, AMOUNT, TRANSACTION_DATE,
    TRANSACTION_STATUS, APPROVAL_STATUS, BANK_NAME, ACCOUNT_SUBJECT, DESCRIPTION,
    CREATE_TIME, CREATE_BY
) VALUES
('FT001', 'TXN202501210001', 1, 1, 'PRJ001', 100000.00, DATE '2025-01-21',
 1, 1, '中国银行', '银行存款', '项目启动资金收入',
 SYSDATE, 'admin');

INSERT INTO FINANCE_TRANSACTION (
    ID, TRANSACTION_NO, TRANSACTION_TYPE, TRANSACTION_CATEGORY, PROJECT_ID, AMOUNT, TRANSACTION_DATE,
    TRANSACTION_STATUS, APPROVAL_STATUS, BANK_NAME, ACCOUNT_SUBJECT, DESCRIPTION,
    CREATE_TIME, CREATE_BY
) VALUES
('FT002', 'TXN202501210002', 2, 2, 'PRJ001', 50000.00, DATE '2025-01-21',
 2, 2, '工商银行', '办公费用', '办公设备采购支出',
 SYSDATE, 'admin');

INSERT INTO FINANCE_TRANSACTION (
    ID, TRANSACTION_NO, TRANSACTION_TYPE, TRANSACTION_CATEGORY, PROJECT_ID, AMOUNT, TRANSACTION_DATE,
    TRANSACTION_STATUS, APPROVAL_STATUS, BANK_NAME, ACCOUNT_SUBJECT, DESCRIPTION,
    CREATE_TIME, CREATE_BY
) VALUES
('FT003', 'TXN202501210003', 1, 1, 'PRJ002', 80000.00, DATE '2025-01-20',
 3, 3, '建设银行', '服务收入', '技术服务费收入',
 SYSDATE, 'admin');

-- 提交事务
COMMIT;
