server: 
  port: 8085
  
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      #maxFileSize  单文件大小限制
      max-file-size: 200MB
      #maxRequestSize   总上传大小限制
      max-request-size: 200000MB

#角色权限
role1: 内控管理人员