spring:
  application:
    name: hbyunMonitor #应用名称
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #Oracle数据库配置
    oracle:
      url: jdbc:oracle:thin:@192.0.2.200:1521/ORCLPDB
      username: HBGRCPLUS
      password: HBGRCPLUS
      driverClassName: oracle.jdbc.driver.OracleDriver
  druid:
    oracle:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatement: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    #Mysql数据库配置
    mysql:
      url: jdbc:mysql://192.0.2.200:3306/HBGRCPLUS?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: ROOT
      password: HBGRC
      driverClassName: com.mysql.jdbc.Driver
    druid:
      mysql:
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatement: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#eureka服务注册中心配置
eureka:
  instance:
    ip-address: 192.0.2.200
    instance-id: hbyunContractModule-8064
    prefer-ip-address: true
    hostname: hbyun-contract-service
  client:
    serviceUrl:
      defaultZone: http://hbyunadmin:hbEureka12345@192.0.2.200:8761/eureka
swagger:
  enabled: true
  pathMapping:

logging:
  level:
    com:
      huabo:
        monitor:
           mapper: debug
#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.extension.incrementer.OracleKeyGenerator
#导出报表临时文件目录
filedir: d:/temp

file:
  path: C:\HBFK\PRO\www\apache-tomcat-7.0.65\webapps\ROOT\WEB-INF\
  
  
#redis配置
redisAddressIp: 127.0.0.1
redisAddressPort: 6379
redisPwd: lfredis@123
redisMaxTotal: 512
redisMaxIdle: 100
redisMaxWait: 10000
redisTimeOut: 1000
redisTextonBorrow: true