-- =====================================================
-- 会计期间管理表创建脚本
-- 创建日期：2025-12-08
-- 说明：创建会计期间管理相关表
-- =====================================================

-- 1. 会计期间表
CREATE TABLE IF NOT EXISTS TBL_ACCOUNTING_PERIOD (
    PERIOD_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    YEAR_NO INT NOT NULL,
    MONTH_NO INT NOT NULL,
    PERIOD_CODE VARCHAR(20) NOT NULL,
    PERIOD_NAME VARCHAR(50) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    PERIOD_STATUS VARCHAR(20) DEFAULT 'OPEN',
    IS_CURRENT TINYINT DEFAULT 0,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    BOOK_ID BIGINT NOT NULL,
    TENANT_ID BIGINT NOT NULL,
    VERSION INT DEFAULT 1,
    IS_DELETED TINYINT DEFAULT 0,
    REMARK VARCHAR(500)
);

-- 创建唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS UK_YEAR_MONTH_BOOK ON TBL_ACCOUNTING_PERIOD(YEAR_NO, MONTH_NO, BOOK_ID, TENANT_ID, IS_DELETED);
CREATE UNIQUE INDEX IF NOT EXISTS UK_PERIOD_CODE ON TBL_ACCOUNTING_PERIOD(PERIOD_CODE, BOOK_ID, TENANT_ID, IS_DELETED);

-- 创建普通索引
CREATE INDEX IF NOT EXISTS IDX_BOOK_ID ON TBL_ACCOUNTING_PERIOD(BOOK_ID);
CREATE INDEX IF NOT EXISTS IDX_TENANT_ID ON TBL_ACCOUNTING_PERIOD(TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_PERIOD_STATUS ON TBL_ACCOUNTING_PERIOD(PERIOD_STATUS);
CREATE INDEX IF NOT EXISTS IDX_IS_CURRENT ON TBL_ACCOUNTING_PERIOD(IS_CURRENT);

-- 2. 期间状态变更日志表
CREATE TABLE IF NOT EXISTS TBL_ACCOUNTING_PERIOD_LOG (
    LOG_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    PERIOD_ID BIGINT NOT NULL,
    OLD_STATUS VARCHAR(20),
    NEW_STATUS VARCHAR(20) NOT NULL,
    OPERATION_TYPE VARCHAR(20) NOT NULL,
    OPERATION_REASON VARCHAR(500),
    OPERATOR_ID VARCHAR(50) NOT NULL,
    OPERATOR_NAME VARCHAR(100) NOT NULL,
    OPERATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BOOK_ID BIGINT NOT NULL,
    TENANT_ID BIGINT NOT NULL,
    REMARK VARCHAR(500)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS IDX_PERIOD_ID ON TBL_ACCOUNTING_PERIOD_LOG(PERIOD_ID);
CREATE INDEX IF NOT EXISTS IDX_OPERATION_TIME ON TBL_ACCOUNTING_PERIOD_LOG(OPERATION_TIME);
CREATE INDEX IF NOT EXISTS IDX_BOOK_ID_LOG ON TBL_ACCOUNTING_PERIOD_LOG(BOOK_ID);
CREATE INDEX IF NOT EXISTS IDX_TENANT_ID_LOG ON TBL_ACCOUNTING_PERIOD_LOG(TENANT_ID);

-- 添加表注释
COMMENT ON TABLE TBL_ACCOUNTING_PERIOD IS '会计期间表';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.PERIOD_ID IS '期间ID';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.YEAR_NO IS '年度';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.MONTH_NO IS '月份';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.PERIOD_CODE IS '期间编码';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.PERIOD_NAME IS '期间名称';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.START_DATE IS '开始日期';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.END_DATE IS '结束日期';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.PERIOD_STATUS IS '期间状态(OPEN-开启,CLOSED-关闭,LOCKED-锁定)';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.IS_CURRENT IS '是否当前期间(0-否,1-是)';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.BOOK_ID IS '账簿ID';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.TENANT_ID IS '租户ID';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.VERSION IS '版本号';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD.IS_DELETED IS '删除标识(0-否,1-是)';

COMMENT ON TABLE TBL_ACCOUNTING_PERIOD_LOG IS '会计期间状态变更日志表';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD_LOG.LOG_ID IS '日志ID';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD_LOG.PERIOD_ID IS '期间ID';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD_LOG.OLD_STATUS IS '原状态';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD_LOG.NEW_STATUS IS '新状态';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD_LOG.OPERATION_TYPE IS '操作类型';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD_LOG.OPERATION_REASON IS '操作原因';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD_LOG.OPERATOR_ID IS '操作人ID';
COMMENT ON COLUMN TBL_ACCOUNTING_PERIOD_LOG.OPERATOR_NAME IS '操作人姓名';