-- =====================================================
-- 代理委托权限表字段补充脚本
-- 执行时间: 2026-02-09
-- 说明: 为 TBL_PROXY_DELEGATION_PERMISSION 表添加缺失的字段
-- =====================================================

-- 1. 添加权限级别字段 (READ/EDIT/FULL)
ALTER TABLE TBL_PROXY_DELEGATION_PERMISSION 
ADD PERMISSION_LEVEL VARCHAR(50);

-- 2. 添加金额限制字段
ALTER TABLE TBL_PROXY_DELEGATION_PERMISSION 
ADD AMOUNT_LIMIT DECIMAL(18,2);

-- 3. 为现有数据设置默认值（如果表中已有数据）
UPDATE TBL_PROXY_DELEGATION_PERMISSION 
SET PERMISSION_LEVEL = 'READ' 
WHERE PERMISSION_LEVEL IS NULL;

UPDATE TBL_PROXY_DELEGATION_PERMISSION 
SET AMOUNT_LIMIT = 0 
WHERE AMOUNT_LIMIT IS NULL;

-- 4. 验证字段是否添加成功
-- SELECT * FROM TBL_PROXY_DELEGATION_PERMISSION;

COMMIT;

