-- =====================================================
-- 修改 TBL_BILL_AUDIT_RULE 表结构（达梦数据库）
-- 添加稽核规则详细信息字段
-- 执行时间: 2026-02-06
-- =====================================================

-- 检查表是否存在
-- SELECT * FROM USER_TABLES WHERE TABLE_NAME = 'TBL_BILL_AUDIT_RULE';

-- 添加规则名称字段
ALTER TABLE TBL_BILL_AUDIT_RULE ADD RULE_NAME VARCHAR(200);
COMMENT ON COLUMN TBL_BILL_AUDIT_RULE.RULE_NAME IS '规则名称';

-- 添加规则类型字段
ALTER TABLE TBL_BILL_AUDIT_RULE ADD RULE_TYPE VARCHAR(50);
COMMENT ON COLUMN TBL_BILL_AUDIT_RULE.RULE_TYPE IS '规则类型(AMOUNT_CHECK-金额校验,DUPLICATE_CHECK-重复检查,INVOICE_CHECK-发票校验,TIME_CHECK-时间校验,OTHER-其他)';

-- 添加规则表达式字段
ALTER TABLE TBL_BILL_AUDIT_RULE ADD RULE_EXPRESSION VARCHAR(1000);
COMMENT ON COLUMN TBL_BILL_AUDIT_RULE.RULE_EXPRESSION IS '规则表达式';

-- 添加警告消息字段
ALTER TABLE TBL_BILL_AUDIT_RULE ADD WARNING_MESSAGE VARCHAR(500);
COMMENT ON COLUMN TBL_BILL_AUDIT_RULE.WARNING_MESSAGE IS '警告消息';

-- 添加是否启用字段
ALTER TABLE TBL_BILL_AUDIT_RULE ADD IS_ENABLED INTEGER DEFAULT 1;
COMMENT ON COLUMN TBL_BILL_AUDIT_RULE.IS_ENABLED IS '是否启用(0-禁用,1-启用)';

-- 添加规则描述字段
ALTER TABLE TBL_BILL_AUDIT_RULE ADD DESCRIPTION VARCHAR(1000);
COMMENT ON COLUMN TBL_BILL_AUDIT_RULE.DESCRIPTION IS '规则描述';

-- 验证表结构（达梦数据库语法）
SELECT
    INFO_SCHEM AS SCHEMA_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    TYPE_NAME AS DATA_TYPE,
    LENGTH AS DATA_LENGTH,
    NULLABLE,
    DATA_DEFAULT
FROM SYSCOLUMNS
WHERE TABLE_NAME = 'TBL_BILL_AUDIT_RULE'
ORDER BY COLID;

COMMIT;

