-- 辅助核算项表 - 达梦数据库版本
-- 创建时间：2024-12-19
-- 说明：辅助核算项基础信息表，支持多级树形结构

-- 删除表（如果存在）
DROP TABLE IF EXISTS T_AUXILIARY_ITEM;

-- 创建辅助核算项表
CREATE TABLE T_AUXILIARY_ITEM (
    AUXILIARY_ID BIGINT PRIMARY KEY,        -- 主键ID
    AUXILIARY_CODE VARCHAR(50) NOT NULL,    -- 核算项编码
    AUXILIARY_NAME VARCHAR(200) NOT NULL,   -- 核算项名称
    AUXILIARY_TYPE VARCHAR(20) NOT NULL,    -- 核算类型
    PARENT_ID BIGINT,                       -- 上级ID
    IS_LEAF NUMBER(1) DEFAULT 1,            -- 是否末级：0否 1是
    IS_ENABLED NUMBER(1) DEFAULT 1,         -- 启用状态：0禁用 1启用
    SORT_ORDER NUMBER(4) DEFAULT 0,         -- 排序号
    BOOK_ID NUMBER(20) NOT NULL,            -- 账簿ID
    TENANT_ID NUMBER(20) NOT NULL,          -- 租户ID
    VERSION NUMBER(10) DEFAULT 0,           -- 版本号（乐观锁）
    IS_DELETED NUMBER(1) DEFAULT 0,         -- 删除标识：0否 1是
    CREATE_TIME DATE DEFAULT SYSDATE,       -- 创建时间
    UPDATE_TIME DATE,                       -- 更新时间
    CREATOR NUMBER(20),                    -- 创建人
    UPDATER NUMBER(20)                     -- 更新人
);

-- 添加注释
COMMENT ON TABLE T_AUXILIARY_ITEM IS '辅助核算项表';
COMMENT ON COLUMN T_AUXILIARY_ITEM.AUXILIARY_ID IS '主键ID';
COMMENT ON COLUMN T_AUXILIARY_ITEM.AUXILIARY_CODE IS '核算项编码';
COMMENT ON COLUMN T_AUXILIARY_ITEM.AUXILIARY_NAME IS '核算项名称';
COMMENT ON COLUMN T_AUXILIARY_ITEM.AUXILIARY_TYPE IS '核算类型';
COMMENT ON COLUMN T_AUXILIARY_ITEM.PARENT_ID IS '上级ID';
COMMENT ON COLUMN T_AUXILIARY_ITEM.IS_LEAF IS '是否末级：0否 1是';
COMMENT ON COLUMN T_AUXILIARY_ITEM.IS_ENABLED IS '启用状态：0禁用 1启用';
COMMENT ON COLUMN T_AUXILIARY_ITEM.SORT_ORDER IS '排序号';
COMMENT ON COLUMN T_AUXILIARY_ITEM.BOOK_ID IS '账簿ID';
COMMENT ON COLUMN T_AUXILIARY_ITEM.TENANT_ID IS '租户ID';
COMMENT ON COLUMN T_AUXILIARY_ITEM.VERSION IS '版本号';
COMMENT ON COLUMN T_AUXILIARY_ITEM.IS_DELETED IS '删除标识：0否 1是';
COMMENT ON COLUMN T_AUXILIARY_ITEM.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_AUXILIARY_ITEM.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN T_AUXILIARY_ITEM.CREATOR IS '创建人';
COMMENT ON COLUMN T_AUXILIARY_ITEM.UPDATER IS '更新人';

-- 创建索引
CREATE INDEX IDX_AUXILIARY_CODE ON T_AUXILIARY_ITEM(AUXILIARY_CODE, AUXILIARY_TYPE, TENANT_ID, BOOK_ID);
CREATE INDEX IDX_PARENT_ID ON T_AUXILIARY_ITEM(PARENT_ID);
CREATE INDEX IDX_AUXILIARY_TYPE ON T_AUXILIARY_ITEM(AUXILIARY_TYPE, TENANT_ID, BOOK_ID);
CREATE INDEX IDX_TENANT_BOOK ON T_AUXILIARY_ITEM(TENANT_ID, BOOK_ID);
CREATE INDEX IDX_IS_DELETED ON T_AUXILIARY_ITEM(IS_DELETED);

-- 插入测试数据
INSERT INTO T_AUXILIARY_ITEM (
    AUXILIARY_ID, AUXILIARY_CODE, AUXILIARY_NAME, AUXILIARY_TYPE,
    PARENT_ID, IS_LEAF, IS_ENABLED, SORT_ORDER,
    BOOK_ID, TENANT_ID, CREATOR, UPDATER
) VALUES
-- 部门类型
(1, 'DEPT_ROOT', '部门根节点', 'DEPT', NULL, 0, 1, 0, 1, 1, 1, 1),
(2, 'DEPT001', '财务部', 'DEPT', 1, 1, 1, 1, 1, 1, 1, 1),
(3, 'DEPT002', '技术部', 'DEPT', 1, 1, 1, 2, 1, 1, 1, 1),
(4, 'DEPT003', '人事部', 'DEPT', 1, 1, 1, 3, 1, 1, 1, 1),

-- 人员类型
(10, 'PERSON_ROOT', '人员根节点', 'PERSON', NULL, 0, 1, 0, 1, 1, 1, 1),
(11, 'PERSON001', '张三', 'PERSON', 10, 1, 1, 1, 1, 1, 1, 1),
(12, 'PERSON002', '李四', 'PERSON', 10, 1, 1, 2, 1, 1, 1, 1),
(13, 'PERSON003', '王五', 'PERSON', 10, 1, 0, 3, 1, 1, 1, 1),

-- 项目类型
(20, 'PROJECT_ROOT', '项目根节点', 'PROJECT', NULL, 0, 1, 0, 1, 1, 1, 1),
(21, 'PROJ001', '财务系统项目', 'PROJECT', 20, 1, 1, 1, 1, 1, 1, 1),
(22, 'PROJ002', 'ERP升级项目', 'PROJECT', 20, 1, 1, 2, 1, 1, 1, 1),

-- 客户类型
(30, 'CUSTOMER_ROOT', '客户根节点', 'CUSTOMER', NULL, 0, 1, 0, 1, 1, 1, 1),
(31, 'CUST001', '华博云客户A', 'CUSTOMER', 30, 1, 1, 1, 1, 1, 1, 1),
(32, 'CUST002', '华博云客户B', 'CUSTOMER', 30, 1, 1, 2, 1, 1, 1, 1),

-- 供应商类型
(40, 'SUPPLIER_ROOT', '供应商根节点', 'SUPPLIER', NULL, 0, 1, 0, 1, 1, 1, 1),
(41, 'SUPP001', '供应商A', 'SUPPLIER', 40, 1, 1, 1, 1, 1, 1, 1),
(42, 'SUPP002', '供应商B', 'SUPPLIER', 40, 1, 1, 2, 1, 1, 1, 1),

-- 产品类型
(50, 'PRODUCT_ROOT', '产品根节点', 'PRODUCT', NULL, 0, 1, 0, 1, 1, 1, 1),
(51, 'PROD001', '财务软件', 'PRODUCT', 50, 1, 1, 1, 1, 1, 1, 1),
(52, 'PROD002', 'ERP系统', 'PRODUCT', 50, 1, 1, 2, 1, 1, 1, 1),

-- 地区类型
(60, 'AREA_ROOT', '地区根节点', 'AREA', NULL, 0, 1, 0, 1, 1, 1, 1),
(61, 'AREA001', '华北地区', 'AREA', 60, 0, 1, 1, 1, 1, 1, 1),
(62, 'AREA002', '华南地区', 'AREA', 60, 0, 1, 2, 1, 1, 1, 1),
(63, 'AREA003', '北京', 'AREA', 61, 1, 1, 1, 1, 1, 1, 1),
(64, 'AREA004', '天津', 'AREA', 61, 1, 1, 2, 1, 1, 1, 1),
(65, 'AREA005', '广东', 'AREA', 62, 1, 1, 1, 1, 1, 1, 1),

-- 其他类型
(70, 'OTHER_ROOT', '其他根节点', 'OTHER', NULL, 0, 1, 0, 1, 1, 1, 1),
(71, 'OTHER001', '其他项目A', 'OTHER', 70, 1, 1, 1, 1, 1, 1, 1);

-- 提交事务
COMMIT;