-- =====================================================
-- 辅助核算模块数据库脚本
-- 创建日期：2025-12-08
-- 说明：创建完整的辅助核算相关表，支持层级结构
-- =====================================================

-- 1. 删除旧的简单辅助核算表（如果存在）
DROP TABLE IF EXISTS T_AUXILIARY_ITEM;

-- 2. 创建新的辅助核算项表（支持层级结构）
CREATE TABLE T_AUXILIARY_ITEM (
    AUXILIARY_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    AUXILIARY_CODE VARCHAR(50) NOT NULL,
    AUXILIARY_NAME VARCHAR(200) NOT NULL,
    AUXILIARY_TYPE VARCHAR(50) NOT NULL,
    PARENT_ID BIGINT,
    IS_LEAF INTEGER DEFAULT 1,
    IS_ENABLED INTEGER DEFAULT 1,
    SORT_ORDER INTEGER DEFAULT 0,
    BOOK_ID BIGINT NOT NULL,
    TENANT_ID BIGINT NOT NULL,
    VERSION INTEGER DEFAULT 1,
    IS_DELETED INTEGER DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATOR BIGINT,
    UPDATER BIGINT
);

-- 3. 创建辅助核算类型表（可选）
CREATE TABLE T_AUXILIARY_TYPE (
    TYPE_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    TYPE_CODE VARCHAR(50) NOT NULL UNIQUE,
    TYPE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    IS_ENABLED INTEGER DEFAULT 1,
    BOOK_ID BIGINT NOT NULL,
    TENANT_ID BIGINT NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_TIME TIMESTAMP
);

-- 4. 创建索引
CREATE INDEX IDX_AUXILIARY_CODE ON T_AUXILIARY_ITEM(AUXILIARY_CODE);
CREATE INDEX IDX_AUXILIARY_TYPE ON T_AUXILIARY_ITEM(AUXILIARY_TYPE);
CREATE INDEX IDX_PARENT_ID ON T_AUXILIARY_ITEM(PARENT_ID);
CREATE INDEX IDX_BOOK_ID ON T_AUXILIARY_ITEM(BOOK_ID);
CREATE INDEX IDX_TENANT_ID ON T_AUXILIARY_ITEM(TENANT_ID);
CREATE INDEX IDX_IS_DELETED ON T_AUXILIARY_ITEM(IS_DELETED);
CREATE UNIQUE INDEX UK_CODE_TYPE_BOOK ON T_AUXILIARY_ITEM(AUXILIARY_CODE, AUXILIARY_TYPE, BOOK_ID, TENANT_ID);

-- 5. 插入基础辅助核算类型
INSERT INTO T_AUXILIARY_TYPE (TYPE_CODE, TYPE_NAME, DESCRIPTION, BOOK_ID, TENANT_ID, CREATED_BY)
VALUES
('DEPT', '部门', '部门辅助核算', 1, 1, 'SYSTEM'),
('PERSON', '人员', '人员辅助核算', 1, 1, 'SYSTEM'),
('PROJECT', '项目', '项目辅助核算', 1, 1, 'SYSTEM'),
('CUSTOMER', '客户', '客户辅助核算', 1, 1, 'SYSTEM'),
('SUPPLIER', '供应商', '供应商辅助核算', 1, 1, 'SYSTEM'),
('PRODUCT', '产品', '产品辅助核算', 1, 1, 'SYSTEM'),
('AREA', '地区', '地区辅助核算', 1, 1, 'SYSTEM'),
('OTHER', '其他', '其他辅助核算', 1, 1, 'SYSTEM');

-- 6. 插入示例辅助核算项数据
INSERT INTO T_AUXILIARY_ITEM (AUXILIARY_CODE, AUXILIARY_NAME, AUXILIARY_TYPE, PARENT_ID, IS_LEAF, IS_ENABLED, SORT_ORDER, BOOK_ID, TENANT_ID, CREATOR)
VALUES
-- 部门层级示例
('DEPT001', '总公司', 'DEPT', NULL, 0, 1, 1, 1, 1, 1),
('DEPT001001', '财务部', 'DEPT', 1, 1, 1, 1, 1, 1, 1),
('DEPT001002', '人事部', 'DEPT', 1, 1, 1, 2, 1, 1, 1),
('DEPT001003', '技术部', 'DEPT', 1, 0, 1, 3, 1, 1, 1),
('DEPT001003001', '开发组', 'DEPT', 4, 1, 1, 1, 1, 1, 1),
('DEPT001003002', '测试组', 'DEPT', 4, 1, 1, 2, 1, 1, 1),

-- 客户示例
('CUST001', 'ABC公司', 'CUSTOMER', NULL, 1, 1, 1, 1, 1, 1),
('CUST002', 'XYZ集团', 'CUSTOMER', NULL, 1, 1, 2, 1, 1, 1),
('CUST003', 'DEF科技', 'CUSTOMER', NULL, 1, 1, 3, 1, 1, 1),

-- 供应商示例
('SUPP001', '供应商A', 'SUPPLIER', NULL, 1, 1, 1, 1, 1, 1),
('SUPP002', '供应商B', 'SUPPLIER', NULL, 1, 1, 2, 1, 1, 1),

-- 项目示例
('PROJ001', '项目A', 'PROJECT', NULL, 1, 1, 1, 1, 1, 1),
('PROJ002', '项目B', 'PROJECT', NULL, 1, 1, 2, 1, 1, 1),

-- 人员示例
('PERSON001', '张三', 'PERSON', NULL, 1, 1, 1, 1, 1, 1),
('PERSON002', '李四', 'PERSON', NULL, 1, 1, 2, 1, 1, 1);

-- 7. 更新序列（如果需要）
-- 注意：达梦数据库的IDENTITY会自动管理序列