-- ==================== 成本归集相关表 ====================
-- 成本归集主表
CREATE TABLE "REDACTED"."T_COST_COLLECTION"
(
"COLLECTION_ID" BIGINT NOT NULL,
"COLLECTION_NO" VARCHAR(50) NOT NULL,
"COLLECTION_PERIOD" VARCHAR(20) NOT NULL,
"COST_CENTER_ID" BIGINT NOT NULL,
"COLLECTION_TYPE" INT NOT NULL,
"COLLECTION_AMOUNT" DECIMAL(18,2) NOT NULL DEFAULT 0.00,
"COLLECTION_STATUS" INT DEFAULT 1,
"COLLECTION_METHOD" INT DEFAULT 1,
"COLLECTION_DATE" DATE,
"AUDITOR_ID" BIGINT,
"AUDITOR_NAME" VARCHAR(100),
"AUDIT_TIME" DATETIME,
"AUDIT_REMARK" TEXT,
"BOOK_ID" BIGINT NOT NULL,
"TENANT_ID" BIGINT NOT NULL,
"REMARK" TEXT,
"VERSION" INT DEFAULT 1,
"IS_DELETED" TINYINT DEFAULT 0,
"CREATE_TIME" DATETIME(6) DEFAULT SYSDATE,
"UPDATE_TIME" DATETIME(6) DEFAULT SYSDATE,
"CREATOR" BIGINT,
"UPDATER" BIGINT,
CONSTRAINT "PK_COST_COLLECTION" NOT CLUSTER PRIMARY KEY("COLLECTION_ID"),
CONSTRAINT "FK_COST_COLLECTION_CENTER" FOREIGN KEY("COST_CENTER_ID") REFERENCES "REDACTED"."T_COST_CENTER"("CENTER_ID") WITH INDEX,
CONSTRAINT "UK_COST_COLLECTION_NO" UNIQUE("COLLECTION_NO")
) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE REDACTED.T_COST_COLLECTION IS '成本归集表';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."COLLECTION_ID" IS '归集ID';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."COLLECTION_NO" IS '归集单号';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."COLLECTION_PERIOD" IS '归集期间，格式：YYYY-MM';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."COST_CENTER_ID" IS '成本中心ID';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."COLLECTION_TYPE" IS '归集类型：1-直接成本，2-间接成本，3-制造费用';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."COLLECTION_AMOUNT" IS '归集金额';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."COLLECTION_STATUS" IS '归集状态：1-待归集，2-归集中，3-已归集，4-已审核';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."COLLECTION_METHOD" IS '归集方式：1-手工归集，2-自动归集';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."COLLECTION_DATE" IS '归集日期';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."AUDITOR_ID" IS '审核人ID';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."AUDITOR_NAME" IS '审核人姓名';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."AUDIT_TIME" IS '审核时间';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."AUDIT_REMARK" IS '审核备注';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."BOOK_ID" IS '账簿ID';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."TENANT_ID" IS '租户ID';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."REMARK" IS '备注';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."VERSION" IS '版本号';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."IS_DELETED" IS '删除标识(0否1是)';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."CREATOR" IS '创建人';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION."UPDATER" IS '更新人';

CREATE OR REPLACE  INDEX "IX_COST_COLLECTION_PERIOD" ON "REDACTED"."T_COST_COLLECTION"("COLLECTION_PERIOD" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "IX_COST_COLLECTION_TYPE" ON "REDACTED"."T_COST_COLLECTION"("COLLECTION_TYPE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "IX_COST_COLLECTION_STATUS" ON "REDACTED"."T_COST_COLLECTION"("COLLECTION_STATUS" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "IX_COST_COLLECTION_CENTER" ON "REDACTED"."T_COST_COLLECTION"("COST_CENTER_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "IX_COST_COLLECTION_BOOK" ON "REDACTED"."T_COST_COLLECTION"("BOOK_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

-- 成本归集明细表
CREATE TABLE "REDACTED"."T_COST_COLLECTION_DETAIL"
(
"DETAIL_ID" BIGINT NOT NULL,
"COLLECTION_ID" BIGINT NOT NULL,
"COST_ELEMENT_CODE" VARCHAR(50),
"COST_ELEMENT_NAME" VARCHAR(200),
"VOUCHER_ID" BIGINT,
"VOUCHER_NO" VARCHAR(50),
"ACCOUNT_CODE" VARCHAR(50),
"ACCOUNT_NAME" VARCHAR(200),
"ORIGINAL_AMOUNT" DECIMAL(18,2) DEFAULT 0.00,
"ALLOCATION_RATE" DECIMAL(10,6) DEFAULT 1.000000,
"ALLOCATED_AMOUNT" DECIMAL(18,2) DEFAULT 0.00,
"DEPARTMENT_NAME" VARCHAR(200),
"PROJECT_NAME" VARCHAR(200),
"BUSINESS_TYPE" VARCHAR(50),
"REMARK" TEXT,
"BOOK_ID" BIGINT NOT NULL,
"TENANT_ID" BIGINT NOT NULL,
"VERSION" INT DEFAULT 1,
"IS_DELETED" TINYINT DEFAULT 0,
"CREATE_TIME" DATETIME(6) DEFAULT SYSDATE,
"UPDATE_TIME" DATETIME(6) DEFAULT SYSDATE,
CONSTRAINT "PK_COST_COLLECTION_DETAIL" NOT CLUSTER PRIMARY KEY("DETAIL_ID"),
CONSTRAINT "FK_COLL_DETAIL_COLLECTION" FOREIGN KEY("COLLECTION_ID") REFERENCES "REDACTED"."T_COST_COLLECTION"("COLLECTION_ID") WITH INDEX

) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE REDACTED.T_COST_COLLECTION_DETAIL IS '成本归集明细表';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."DETAIL_ID" IS '明细ID';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."COLLECTION_ID" IS '归集ID';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."COST_ELEMENT_CODE" IS '成本要素编码';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."COST_ELEMENT_NAME" IS '成本要素名称';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."VOUCHER_ID" IS '凭证ID';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."VOUCHER_NO" IS '凭证号';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."ACCOUNT_CODE" IS '会计科目编码';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."ACCOUNT_NAME" IS '会计科目名称';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."ORIGINAL_AMOUNT" IS '原始金额';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."ALLOCATION_RATE" IS '分摊率';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."ALLOCATED_AMOUNT" IS '分摊金额';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."DEPARTMENT_NAME" IS '部门名称';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."PROJECT_NAME" IS '项目名称';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."REMARK" IS '备注';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."BOOK_ID" IS '账簿ID';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."TENANT_ID" IS '租户ID';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."VERSION" IS '版本号';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."IS_DELETED" IS '删除标识(0否1是)';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN REDACTED.T_COST_COLLECTION_DETAIL."UPDATE_TIME" IS '更新时间';
