-- =====================================================
-- 华博云财务共享系统 - 成本分摊表结构设计
-- 兼容达梦数据库语法
-- 创建时间: 2024-12-06
-- 功能描述: 成本分摊专用数据表，支持多种分摊方法和状态管理
-- =====================================================

-- 创建成本分摊主表
-- 说明: 存储成本分摊的基本信息和状态
CREATE TABLE T_COST_ALLOCATION (
    -- 主键字段
    ALLOCATION_ID BIGINT PRIMARY KEY,
    ALLOCATION_NO VARCHAR(50) UNIQUE NOT NULL,

    -- 业务字段
    ALLOCATION_PERIOD VARCHAR(20) NOT NULL,               -- 分摊期间 (格式: YYYY-MM)
    SOURCE_CENTER_ID VARCHAR(20) NOT NULL,               -- 源成本中心ID
    ALLOCATION_METHOD VARCHAR(50) NOT NULL,              -- 分摊方法 (QUANTITY_BASED, AMOUNT_BASED, RATIO_BASED, HOUR_BASED)
    TOTAL_AMOUNT DECIMAL(18,2) NOT NULL,                 -- 分摊总额
    ALLOCATION_STATUS INTEGER DEFAULT 1,                 -- 分摊状态 (1:待分摊 2:分摊中 3:已分摊 4:已审核)
    ALLOCATION_DATE DATE NOT NULL,                       -- 分摊日期
    IS_GENERATE_VOUCHER INTEGER DEFAULT 0,               -- 是否生成凭证 (0:否 1:是)
    VOUCHER_ID BIGINT,                                   -- 凭证ID
    REMARK VARCHAR(500),                                 -- 备注

    -- 多租户字段
    BOOK_ID VARCHAR(20) NOT NULL,                        -- 账簿ID
    TENANT_ID VARCHAR(20) NOT NULL,                      -- 租户ID

    -- 乐观锁和软删除字段
    VERSION INTEGER DEFAULT 1,                           -- 版本号
    IS_DELETED INTEGER DEFAULT 0,                        -- 是否删除 (0:未删除 1:已删除)

    -- 审计字段
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,     -- 创建时间
    UPDATE_TIME TIMESTAMP,                               -- 更新时间
    CREATOR BIGINT,                                      -- 创建人
    UPDATER BIGINT                                       -- 更新人
);

-- 创建成本分摊明细表
-- 说明: 存储每个目标成本中心的分摊明细信息
CREATE TABLE T_COST_ALLOCATION_DETAIL (
    -- 主键字段
    DETAIL_ID BIGINT PRIMARY KEY,
    ALLOCATION_ID BIGINT NOT NULL,                       -- 关联主表ID

    -- 业务字段
    TARGET_CENTER_ID VARCHAR(20) NOT NULL,               -- 目标成本中心ID
    ALLOCATION_BASIS_VALUE DECIMAL(18,4) NOT NULL,       -- 分摊基础值
    ALLOCATION_RATIO DECIMAL(8,4) NOT NULL,              -- 分摊比例
    ALLOCATED_AMOUNT DECIMAL(18,2) NOT NULL,             -- 分摊金额
    REMARK VARCHAR(500),                                 -- 备注

    -- 多租户字段
    BOOK_ID VARCHAR(20) NOT NULL,                        -- 账簿ID
    TENANT_ID VARCHAR(20) NOT NULL,                      -- 租户ID

    -- 乐观锁和软删除字段
    VERSION INTEGER DEFAULT 1,                           -- 版本号
    IS_DELETED INTEGER DEFAULT 0,                        -- 是否删除 (0:未删除 1:已删除)

    -- 审计字段
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,     -- 创建时间
    UPDATE_TIME TIMESTAMP,                               -- 更新时间
    CREATOR BIGINT,                                      -- 创建人
    UPDATER BIGINT,                                      -- 更新人

    -- 外键约束
    FOREIGN KEY (ALLOCATION_ID) REFERENCES T_COST_ALLOCATION(ALLOCATION_ID)
);

-- 创建索引以提升查询性能

-- 成本分摊主表索引
CREATE INDEX IDX_CA_PERIOD ON T_COST_ALLOCATION(ALLOCATION_PERIOD);           -- 按期间查询
CREATE INDEX IDX_CA_SOURCE_CENTER ON T_COST_ALLOCATION(SOURCE_CENTER_ID);     -- 按源成本中心查询
CREATE INDEX IDX_CA_STATUS ON T_COST_ALLOCATION(ALLOCATION_STATUS);           -- 按状态查询
CREATE INDEX IDX_CA_BOOK_ID ON T_COST_ALLOCATION(BOOK_ID);                    -- 按账簿查询
CREATE INDEX IDX_CA_TENANT_ID ON T_COST_ALLOCATION(TENANT_ID);                -- 按租户查询
CREATE INDEX IDX_CA_ALLOCATION_DATE ON T_COST_ALLOCATION(ALLOCATION_DATE);    -- 按分摊日期查询
CREATE INDEX IDX_CA_CREATE_TIME ON T_COST_ALLOCATION(CREATE_TIME);            -- 按创建时间查询
CREATE INDEX IDX_CA_IS_DELETED ON T_COST_ALLOCATION(IS_DELETED);              -- 软删除查询

-- 成本分摊明细表索引
CREATE INDEX IDX_CAD_ALLOCATION_ID ON T_COST_ALLOCATION_DETAIL(ALLOCATION_ID);       -- 按主表ID查询
CREATE INDEX IDX_CAD_TARGET_CENTER ON T_COST_ALLOCATION_DETAIL(TARGET_CENTER_ID);     -- 按目标成本中心查询
CREATE INDEX IDX_CAD_BOOK_ID ON T_COST_ALLOCATION_DETAIL(BOOK_ID);                     -- 按账簿查询
CREATE INDEX IDX_CAD_TENANT_ID ON T_COST_ALLOCATION_DETAIL(TENANT_ID);                 -- 按租户查询
CREATE INDEX IDX_CAD_CREATE_TIME ON T_COST_ALLOCATION_DETAIL(CREATE_TIME);             -- 按创建时间查询
CREATE INDEX IDX_CAD_IS_DELETED ON T_COST_ALLOCATION_DETAIL(IS_DELETED);               -- 软删除查询

-- 创建视图以简化查询
-- 成本分摊汇总视图（包含成本中心名称）
CREATE VIEW V_COST_ALLOCATION_SUMMARY AS
SELECT
    a.ALLOCATION_ID,
    a.ALLOCATION_NO,
    a.ALLOCATION_PERIOD,
    a.SOURCE_CENTER_ID,
    sc.CENTER_NAME as SOURCE_CENTER_NAME,
    a.ALLOCATION_METHOD,
    a.TOTAL_AMOUNT,
    a.ALLOCATION_STATUS,
    a.ALLOCATION_DATE,
    a.IS_GENERATE_VOUCHER,
    a.VOUCHER_ID,
    a.REMARK,
    a.BOOK_ID,
    a.TENANT_ID,
    a.CREATE_TIME,
    a.UPDATE_TIME,
    -- 统计信息
    d.TARGET_CENTER_COUNT,
    d.TOTAL_ALLOCATED_AMOUNT,
    -- 状态描述
    CASE a.ALLOCATION_STATUS
        WHEN 1 THEN '待分摊'
        WHEN 2 THEN '分摊中'
        WHEN 3 THEN '已分摊'
        WHEN 4 THEN '已审核'
        ELSE '未知状态'
    END as ALLOCATION_STATUS_NAME,
    -- 分摊方法描述
    CASE a.ALLOCATION_METHOD
        WHEN 'QUANTITY_BASED' THEN '数量基础'
        WHEN 'AMOUNT_BASED' THEN '金额基础'
        WHEN 'RATIO_BASED' THEN '比例基础'
        WHEN 'HOUR_BASED' THEN '工时基础'
        ELSE '未知方法'
    END as ALLOCATION_METHOD_NAME
FROM T_COST_ALLOCATION a
LEFT JOIN T_COST_CENTER sc ON a.SOURCE_CENTER_ID = sc.CENTER_ID AND sc.IS_DELETED = 0
LEFT JOIN (
    SELECT
        ALLOCATION_ID,
        COUNT(*) as TARGET_CENTER_COUNT,
        SUM(ALLOCATED_AMOUNT) as TOTAL_ALLOCATED_AMOUNT
    FROM T_COST_ALLOCATION_DETAIL
    WHERE IS_DELETED = 0
    GROUP BY ALLOCATION_ID
) d ON a.ALLOCATION_ID = d.ALLOCATION_ID
WHERE a.IS_DELETED = 0;

-- 成本分摊明细视图（包含成本中心名称）
CREATE VIEW V_COST_ALLOCATION_DETAIL AS
SELECT
    d.DETAIL_ID,
    d.ALLOCATION_ID,
    a.ALLOCATION_NO,
    a.ALLOCATION_PERIOD,
    a.SOURCE_CENTER_ID,
    sc.CENTER_NAME as SOURCE_CENTER_NAME,
    d.TARGET_CENTER_ID,
    tc.CENTER_NAME as TARGET_CENTER_NAME,
    d.ALLOCATION_BASIS_VALUE,
    d.ALLOCATION_RATIO,
    d.ALLOCATED_AMOUNT,
    d.REMARK,
    d.BOOK_ID,
    d.TENANT_ID,
    d.CREATE_TIME,
    d.UPDATE_TIME
FROM T_COST_ALLOCATION_DETAIL d
LEFT JOIN T_COST_ALLOCATION a ON d.ALLOCATION_ID = a.ALLOCATION_ID AND a.IS_DELETED = 0
LEFT JOIN T_COST_CENTER sc ON a.SOURCE_CENTER_ID = sc.CENTER_ID AND sc.IS_DELETED = 0
LEFT JOIN T_COST_CENTER tc ON d.TARGET_CENTER_ID = tc.CENTER_ID AND tc.IS_DELETED = 0
WHERE d.IS_DELETED = 0;

-- 添加表注释
COMMENT ON TABLE T_COST_ALLOCATION IS '成本分摊主表 - 存储成本分摊的基本信息和状态';
COMMENT ON TABLE T_COST_ALLOCATION_DETAIL IS '成本分摊明细表 - 存储每个目标成本中心的分摊明细信息';
COMMENT ON VIEW V_COST_ALLOCATION_SUMMARY IS '成本分摊汇总视图 - 包含成本中心名称和统计信息';
COMMENT ON VIEW V_COST_ALLOCATION_DETAIL IS '成本分摊明细视图 - 包含源成本中心和目标成本中心名称';

-- 添加字段注释（达梦数据库支持COMMENT ON COLUMN语法）
-- 成本分摊主表字段注释
COMMENT ON COLUMN T_COST_ALLOCATION.ALLOCATION_ID IS '分摊ID - 主键';
COMMENT ON COLUMN T_COST_ALLOCATION.ALLOCATION_NO IS '分摊单号 - 唯一标识';
COMMENT ON COLUMN T_COST_ALLOCATION.ALLOCATION_PERIOD IS '分摊期间 - 格式YYYY-MM';
COMMENT ON COLUMN T_COST_ALLOCATION.SOURCE_CENTER_ID IS '源成本中心ID';
COMMENT ON COLUMN T_COST_ALLOCATION.ALLOCATION_METHOD IS '分摊方法 - QUANTITY_BASED/AMOUNT_BASED/RATIO_BASED/HOUR_BASED';
COMMENT ON COLUMN T_COST_ALLOCATION.TOTAL_AMOUNT IS '分摊总额';
COMMENT ON COLUMN T_COST_ALLOCATION.ALLOCATION_STATUS IS '分摊状态 - 1:待分摊 2:分摊中 3:已分摊 4:已审核';
COMMENT ON COLUMN T_COST_ALLOCATION.ALLOCATION_DATE IS '分摊日期';
COMMENT ON COLUMN T_COST_ALLOCATION.IS_GENERATE_VOUCHER IS '是否生成凭证 - 0:否 1:是';
COMMENT ON COLUMN T_COST_ALLOCATION.VOUCHER_ID IS '凭证ID';
COMMENT ON COLUMN T_COST_ALLOCATION.REMARK IS '备注';

-- 成本分摊明细表字段注释
COMMENT ON COLUMN T_COST_ALLOCATION_DETAIL.DETAIL_ID IS '明细ID - 主键';
COMMENT ON COLUMN T_COST_ALLOCATION_DETAIL.ALLOCATION_ID IS '分摊主表ID - 外键';
COMMENT ON COLUMN T_COST_ALLOCATION_DETAIL.TARGET_CENTER_ID IS '目标成本中心ID';
COMMENT ON COLUMN T_COST_ALLOCATION_DETAIL.ALLOCATION_BASIS_VALUE IS '分摊基础值';
COMMENT ON COLUMN T_COST_ALLOCATION_DETAIL.ALLOCATION_RATIO IS '分摊比例';
COMMENT ON COLUMN T_COST_ALLOCATION_DETAIL.ALLOCATED_AMOUNT IS '分摊金额';
COMMENT ON COLUMN T_COST_ALLOCATION_DETAIL.REMARK IS '备注';

-- =====================================================
-- 示例数据插入（可选，用于测试）
-- =====================================================

-- 插入示例成本分摊主记录
INSERT INTO T_COST_ALLOCATION (
    ALLOCATION_ID, ALLOCATION_NO, ALLOCATION_PERIOD, SOURCE_CENTER_ID,
    ALLOCATION_METHOD, TOTAL_AMOUNT, ALLOCATION_STATUS, ALLOCATION_DATE,
    IS_GENERATE_VOUCHER, BOOK_ID, TENANT_ID, CREATOR
) VALUES (
    202412001, 'CA202412001', '2024-12', '1001',
    'QUANTITY_BASED', 100000.00, 3, TO_DATE('2024-12-06', 'YYYY-MM-DD'),
    1, '1', '1000', 1
);

-- 插入示例成本分摊明细记录
INSERT INTO T_COST_ALLOCATION_DETAIL (
    DETAIL_ID, ALLOCATION_ID, TARGET_CENTER_ID, ALLOCATION_BASIS_VALUE,
    ALLOCATION_RATIO, ALLOCATED_AMOUNT, BOOK_ID, TENANT_ID, CREATOR
) VALUES
(202412001001, 202412001, '1002', 30.00, 0.6000, 60000.00, '1', '1000', 1),
(202412001002, 202412001, '1003', 20.00, 0.4000, 40000.00, '1', '1000', 1);

-- =====================================================
-- 数据迁移脚本（从内部结算表迁移现有成本分摊数据）
-- =====================================================

-- 迁移现有成本分摊数据（settlementType = 1）到新表
-- 注意：执行前请确保目标表为空，并且备份好原数据
/*
INSERT INTO T_COST_ALLOCATION (
    ALLOCATION_ID, ALLOCATION_NO, ALLOCATION_PERIOD,
    SOURCE_CENTER_ID, ALLOCATION_METHOD, TOTAL_AMOUNT,
    ALLOCATION_STATUS, ALLOCATION_DATE, IS_GENERATE_VOUCHER,
    BOOK_ID, TENANT_ID, CREATE_TIME, CREATOR
)
SELECT
    SETTLEMENT_ID,
    'CA_' || SUBSTR(SETTLEMENT_NO, 1, 30),
    ACCOUNTING_PERIOD,
    FROM_CENTER_ID,
    CASE
        WHEN SETTLEMENT_BASIS LIKE 'AMOUNT_BASED%' THEN 'AMOUNT_BASED'
        WHEN SETTLEMENT_BASIS LIKE 'RATIO_BASED%' THEN 'RATIO_BASED'
        WHEN SETTLEMENT_BASIS LIKE 'HOUR_BASED%' THEN 'HOUR_BASED'
        ELSE 'QUANTITY_BASED'
    END,
    SETTLEMENT_AMOUNT,
    CASE
        WHEN SETTLEMENT_STATUS = 1 THEN 1  -- 待分摊
        WHEN SETTLEMENT_STATUS = 2 THEN 3  -- 已分摊
        ELSE 1
    END,
    SETTLEMENT_DATE,
    CASE WHEN VOUCHER_ID IS NOT NULL THEN 1 ELSE 0 END,
    BOOK_ID,
    TENANT_ID,
    CREATE_TIME,
    CREATOR
FROM T_INTERNAL_SETTLEMENT
WHERE SETTLEMENT_TYPE = 1
  AND IS_DELETED = 0;
*/

-- =====================================================
-- 性能优化建议
-- =====================================================

-- 1. 定期清理已删除的数据（根据业务需求设置清理策略）
-- DELETE FROM T_COST_ALLOCATION_DETAIL WHERE IS_DELETED = 1 AND UPDATE_TIME < ADD_MONTHS(SYSDATE, -6);
-- DELETE FROM T_COST_ALLOCATION WHERE IS_DELETED = 1 AND UPDATE_TIME < ADD_MONTHS(SYSDATE, -6);

-- 2. 定期统计和分析查询性能，根据实际使用情况调整索引
-- 3. 大数据量分页查询建议使用基于ID的分页策略
-- 4. 考虑在高峰期对历史数据进行分区处理