-- =====================================================
-- 会计凭证表 - 达梦数据库版本
-- 创建日期：2025-12-17
-- 说明：创建会计凭证主表
-- =====================================================

-- 创建会计凭证表
CREATE TABLE T_ACCOUNTING_VOUCHER (
    VOUCHER_ID NUMBER(20) NOT NULL PRIMARY KEY COMMENT '凭证ID',
    VOUCHER_NO VARCHAR2(50) NOT NULL COMMENT '凭证编号',
    VOUCHER_TYPE_ID NUMBER(20) COMMENT '凭证类型ID',
    VOUCHER_DATE DATE COMMENT '凭证日期',
    ACCOUNTING_PERIOD VARCHAR2(20) COMMENT '会计期间',
    VOUCHER_DESC VARCHAR2(500) COMMENT '凭证摘要',
    TOTAL_DEBIT NUMBER(18,2) COMMENT '借方金额合计',
    TOTAL_CREDIT NUMBER(18,2) COMMENT '贷方金额合计',
    ENTRY_COUNT NUMBER(10) COMMENT '分录数量',
    VOUCHER_STATUS NUMBER(2) DEFAULT 0 COMMENT '凭证状态(0草稿1已生成2已过账3已取消)',
    SOURCE_TRANSACTION_ID NUMBER(20) COMMENT '来源事项ID',
    SOURCE_SYSTEM VARCHAR2(50) COMMENT '来源系统',
    PREPARER NUMBER(20) COMMENT '制单人',
    REVIEWER NUMBER(20) COMMENT '审核人',
    REVIEW_TIME TIMESTAMP COMMENT '审核时间',
    POSTER NUMBER(20) COMMENT '过账人',
    POST_TIME TIMESTAMP COMMENT '过账时间',
    ATTACHMENT_COUNT NUMBER(10) DEFAULT 0 COMMENT '附件数量',
    REMARK VARCHAR2(1000) COMMENT '备注',
    BOOK_ID NUMBER(20) NOT NULL COMMENT '账簿ID',
    TENANT_ID NUMBER(20) NOT NULL COMMENT '租户ID',
    IS_DELETED NUMBER(1) DEFAULT 0 COMMENT '删除标识(0否1是)',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    CREATOR NUMBER(20) COMMENT '创建人',
    UPDATER NUMBER(20) COMMENT '更新人'
);

-- 添加表注释
COMMENT ON TABLE T_ACCOUNTING_VOUCHER IS '会计凭证表';

-- 添加字段注释
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.VOUCHER_ID IS '凭证ID';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.VOUCHER_NO IS '凭证编号';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.VOUCHER_TYPE_ID IS '凭证类型ID';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.VOUCHER_DATE IS '凭证日期';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.ACCOUNTING_PERIOD IS '会计期间';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.VOUCHER_DESC IS '凭证摘要';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.TOTAL_DEBIT IS '借方金额合计';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.TOTAL_CREDIT IS '贷方金额合计';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.ENTRY_COUNT IS '分录数量';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.VOUCHER_STATUS IS '凭证状态(0草稿1已生成2已过账3已取消)';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.SOURCE_TRANSACTION_ID IS '来源事项ID';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.SOURCE_SYSTEM IS '来源系统';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.PREPARER IS '制单人';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.REVIEWER IS '审核人';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.REVIEW_TIME IS '审核时间';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.POSTER IS '过账人';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.POST_TIME IS '过账时间';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.ATTACHMENT_COUNT IS '附件数量';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.REMARK IS '备注';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.BOOK_ID IS '账簿ID';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.TENANT_ID IS '租户ID';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.IS_DELETED IS '删除标识(0否1是)';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.CREATOR IS '创建人';
COMMENT ON COLUMN T_ACCOUNTING_VOUCHER.UPDATER IS '更新人';

-- 创建索引
CREATE INDEX IDX_VOUCHER_NO ON T_ACCOUNTING_VOUCHER(VOUCHER_NO);
CREATE INDEX IDX_VOUCHER_DATE ON T_ACCOUNTING_VOUCHER(VOUCHER_DATE);
CREATE INDEX IDX_BOOK_ID ON T_ACCOUNTING_VOUCHER(BOOK_ID);
CREATE INDEX IDX_TENANT_ID ON T_ACCOUNTING_VOUCHER(TENANT_ID);
CREATE INDEX IDX_VOUCHER_STATUS ON T_ACCOUNTING_VOUCHER(VOUCHER_STATUS);
CREATE INDEX IDX_CREATE_TIME ON T_ACCOUNTING_VOUCHER(CREATE_TIME);

-- 创建唯一约束
ALTER TABLE T_ACCOUNTING_VOUCHER ADD CONSTRAINT UK_VOUCHER_NO UNIQUE (VOUCHER_NO, BOOK_ID, TENANT_ID);