-- 创建成本预算表
-- 适配达梦数据库语法
-- 表名: T_COST_BUDGET

-- 删除表（如果存在）
DROP TABLE IF EXISTS T_COST_BUDGET;

-- 创建成本预算表
CREATE TABLE T_COST_BUDGET (
    BUDGET_ID NUMBER(20) PRIMARY KEY,
    CENTER_ID NUMBER(20) NOT NULL,                    -- 成本中心ID
    BUDGET_YEAR VARCHAR2(10) NOT NULL,                -- 预算年度
    BUDGET_QUARTER VARCHAR2(2),                       -- 预算季度（1-4）
    TOTAL_BUDGET DECIMAL(20,2) DEFAULT 0,             -- 总预算金额
    ACTUAL_COST DECIMAL(20,2) DEFAULT 0,              -- 实际成本
    REMAINING_BUDGET DECIMAL(20,2) DEFAULT 0,         -- 剩余预算
    COST_CATEGORY VARCHAR2(50),                       -- 成本类别
    STATUS NUMBER(1) DEFAULT 1,                       -- 状态：1-启用，0-停用
    REMARK VARCHAR2(500),                             -- 备注
    IS_DELETED NUMBER(1) DEFAULT 0,                   -- 删除标记：0-未删除，1-已删除
    BOOK_ID VARCHAR2(50),                             -- 账簿ID
    TENANT_ID VARCHAR2(50),                           -- 租户ID
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 创建时间
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 更新时间
    CREATOR VARCHAR2(50),                             -- 创建人
    UPDATER VARCHAR2(50)                              -- 更新人
);

-- 添加外键约束（如果成本中心表存在）
-- ALTER TABLE T_COST_BUDGET ADD CONSTRAINT FK_COST_BUDGET_CENTER
-- FOREIGN KEY (CENTER_ID) REFERENCES T_COST_CENTER(CENTER_ID);

-- 创建索引
CREATE INDEX IDX_COST_BUDGET_CENTER ON T_COST_BUDGET(CENTER_ID);
CREATE INDEX IDX_COST_BUDGET_YEAR ON T_COST_BUDGET(BUDGET_YEAR);
CREATE INDEX IDX_COST_BUDGET_YEAR_QUARTER ON T_COST_BUDGET(BUDGET_YEAR, BUDGET_QUARTER);
CREATE INDEX IDX_COST_BUDGET_DELETED ON T_COST_BUDGET(IS_DELETED);
CREATE INDEX IDX_COST_BUDGET_BOOK_TENANT ON T_COST_BUDGET(BOOK_ID, TENANT_ID);
CREATE INDEX IDX_COST_BUDGET_STATUS ON T_COST_BUDGET(STATUS);

-- 添加注释
COMMENT ON TABLE T_COST_BUDGET IS '成本预算表';
COMMENT ON COLUMN T_COST_BUDGET.BUDGET_ID IS '预算ID';
COMMENT ON COLUMN T_COST_BUDGET.CENTER_ID IS '成本中心ID';
COMMENT ON COLUMN T_COST_BUDGET.BUDGET_YEAR IS '预算年度';
COMMENT ON COLUMN T_COST_BUDGET.BUDGET_QUARTER IS '预算季度';
COMMENT ON COLUMN T_COST_BUDGET.TOTAL_BUDGET IS '总预算金额';
COMMENT ON COLUMN T_COST_BUDGET.ACTUAL_COST IS '实际成本';
COMMENT ON COLUMN T_COST_BUDGET.REMAINING_BUDGET IS '剩余预算';
COMMENT ON COLUMN T_COST_BUDGET.COST_CATEGORY IS '成本类别';
COMMENT ON COLUMN T_COST_BUDGET.STATUS IS '状态：1-启用，0-停用';
COMMENT ON COLUMN T_COST_BUDGET.REMARK IS '备注';
COMMENT ON COLUMN T_COST_BUDGET.IS_DELETED IS '删除标记：0-未删除，1-已删除';
COMMENT ON COLUMN T_COST_BUDGET.BOOK_ID IS '账簿ID';
COMMENT ON COLUMN T_COST_BUDGET.TENANT_ID IS '租户ID';
COMMENT ON COLUMN T_COST_BUDGET.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_COST_BUDGET.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN T_COST_BUDGET.CREATOR IS '创建人';
COMMENT ON COLUMN T_COST_BUDGET.UPDATER IS '更新人';

-- 创建序列（用于自动生成ID）
CREATE SEQUENCE SEQ_COST_BUDGET_ID
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999999999999999
MINVALUE 1
CACHE 20;

-- 创建触发器（自动设置ID）
CREATE OR REPLACE TRIGGER TRG_COST_BUDGET_ID
BEFORE INSERT ON T_COST_BUDGET
FOR EACH ROW
WHEN (NEW.BUDGET_ID IS NULL)
BEGIN
    SELECT SEQ_COST_BUDGET_ID.NEXTVAL INTO :NEW.BUDGET_ID FROM DUAL;
END;
/

-- 创建触发器（自动更新UPDATE_TIME）
CREATE OR REPLACE TRIGGER TRG_COST_BUDGET_UPDATE_TIME
BEFORE UPDATE ON T_COST_BUDGET
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/;

-- 插入测试数据（可选）
INSERT INTO T_COST_BUDGET (BUDGET_ID, CENTER_ID, BUDGET_YEAR, BUDGET_QUARTER, TOTAL_BUDGET, ACTUAL_COST, REMAINING_BUDGET, COST_CATEGORY, STATUS, REMARK, BOOK_ID, TENANT_ID, CREATOR, UPDATER)
VALUES (SEQ_COST_BUDGET_ID.NEXTVAL, 1, '2025', '1', 100000.00, 0.00, 100000.00, '办公费用', 1, '2025年第一季度预算', '1', '1000', 'admin', 'admin');

INSERT INTO T_COST_BUDGET (BUDGET_ID, CENTER_ID, BUDGET_YEAR, BUDGET_QUARTER, TOTAL_BUDGET, ACTUAL_COST, REMAINING_BUDGET, COST_CATEGORY, STATUS, REMARK, BOOK_ID, TENANT_ID, CREATOR, UPDATER)
VALUES (SEQ_COST_BUDGET_ID.NEXTVAL, 2, '2025', '1', 150000.00, 25000.00, 125000.00, '人力成本', 1, '2025年第一季度人力预算', '1', '1000', 'admin', 'admin');

INSERT INTO T_COST_BUDGET (BUDGET_ID, CENTER_ID, BUDGET_YEAR, BUDGET_QUARTER, TOTAL_BUDGET, ACTUAL_COST, REMAINING_BUDGET, COST_CATEGORY, STATUS, REMARK, BOOK_ID, TENANT_ID, CREATOR, UPDATER)
VALUES (SEQ_COST_BUDGET_ID.NEXTVAL, 1, '2024', '4', 80000.00, 75000.00, 5000.00, '差旅费用', 1, '2024年第四季度预算', '1', '1000', 'admin', 'admin');

COMMIT;