-- =====================================================
-- 辅助核算模块测试脚本
-- 创建日期：2025-12-08
-- 说明：测试辅助核算模块的数据库操作
-- =====================================================

-- 1. 检查表是否存在
SELECT TABLE_NAME FROM ALL_TABLES WHERE TABLE_NAME = 'T_AUXILIARY_ITEM';

-- 2. 检查表结构
DESC T_AUXILIARY_ITEM;

-- 3. 插入测试数据
INSERT INTO T_AUXILIARY_ITEM (AUXILIARY_CODE, AUXILIARY_NAME, AUXILIARY_TYPE, PARENT_ID, IS_LEAF, IS_ENABLED, SORT_ORDER, BOOK_ID, TENANT_ID, CREATOR)
VALUES
('TEST001', '测试部门', 'DEPT', NULL, 0, 1, 1, 1, 1, 1);

-- 4. 查询测试数据
SELECT * FROM T_AUXILIARY_ITEM WHERE AUXILIARY_CODE = 'TEST001';

-- 5. 按类型查询
SELECT * FROM T_AUXILIARY_ITEM WHERE AUXILIARY_TYPE = 'DEPT' AND IS_DELETED = 0;

-- 6. 树形结构查询
SELECT
    AUXILIARY_ID,
    AUXILIARY_CODE,
    AUXILIARY_NAME,
    AUXILIARY_TYPE,
    PARENT_ID,
    IS_LEAF,
    IS_ENABLED,
    SORT_ORDER
FROM T_AUXILIARY_ITEM
WHERE IS_DELETED = 0
ORDER BY AUXILIARY_TYPE ASC, SORT_ORDER ASC, AUXILIARY_CODE ASC;

-- 7. 清理测试数据
DELETE FROM T_AUXILIARY_ITEM WHERE AUXILIARY_CODE = 'TEST001';