-- ============================================================
-- ALTER TABLE：补充前端业务所需字段
-- 数据库：达梦DM8  Schema：REDACTED
-- ============================================================

-- ============================================================
-- 1. TBL_BUDGET_VERSION 补充字段
-- 前端需要：versionCode / fiscalYear / versionDescription /
--           isActive / creator / totalAmount / lastModifyTime
-- ============================================================
ALTER TABLE "REDACTED"."TBL_BUDGET_VERSION"
    ADD "VERSION_CODE"        VARCHAR2(100);
ALTER TABLE "REDACTED"."TBL_BUDGET_VERSION"
    ADD "FISCAL_YEAR"         INTEGER;
ALTER TABLE "REDACTED"."TBL_BUDGET_VERSION"
    ADD "VERSION_DESCRIPTION" VARCHAR2(500);
ALTER TABLE "REDACTED"."TBL_BUDGET_VERSION"
    ADD "IS_ACTIVE"           NUMBER(1,0) DEFAULT 0;
-- creator 直接用 CREATOR_NAME，前端 creator 字段映射到此列，无需新增
-- totalAmount 直接用 BUDGET_AMOUNT，前端 totalAmount 映射到此列，无需新增
-- lastModifyTime 直接用 UPDATE_TIME，前端 lastModifyTime 映射到此列，无需新增

COMMENT ON COLUMN REDACTED.TBL_BUDGET_VERSION.VERSION_CODE IS '版本编号（唯一标识，如 V2026-001）';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_VERSION.FISCAL_YEAR IS '预算年度';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_VERSION.VERSION_DESCRIPTION IS '版本描述';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_VERSION.IS_ACTIVE IS '是否激活(0否1是)';

-- ============================================================
-- 2. TBL_BUDGET_TEMPLATE 补充字段
-- 前端需要：templateStatus / categoryId / applicableYear /
--           fieldCount / usageCount / isPublic / allowCopy
-- ============================================================
ALTER TABLE "REDACTED"."TBL_BUDGET_TEMPLATE"
    ADD "TEMPLATE_STATUS"  VARCHAR2(50)  DEFAULT 'DRAFT';
ALTER TABLE "REDACTED"."TBL_BUDGET_TEMPLATE"
    ADD "CATEGORY_ID"      VARCHAR2(64);
ALTER TABLE "REDACTED"."TBL_BUDGET_TEMPLATE"
    ADD "APPLICABLE_YEAR"  INTEGER;
ALTER TABLE "REDACTED"."TBL_BUDGET_TEMPLATE"
    ADD "FIELD_COUNT"      INTEGER       DEFAULT 0;
ALTER TABLE "REDACTED"."TBL_BUDGET_TEMPLATE"
    ADD "USAGE_COUNT"      INTEGER       DEFAULT 0;
ALTER TABLE "REDACTED"."TBL_BUDGET_TEMPLATE"
    ADD "IS_PUBLIC"        NUMBER(1,0)   DEFAULT 0;
ALTER TABLE "REDACTED"."TBL_BUDGET_TEMPLATE"
    ADD "ALLOW_COPY"       NUMBER(1,0)   DEFAULT 1;
-- creator 直接用 CREATOR_NAME，前端 creator 字段映射到此列，无需新增

COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.TEMPLATE_STATUS IS '模板状态(DRAFT草稿/PUBLISHED已发布/ARCHIVED已归档)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.CATEGORY_ID IS '所属分类ID';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.APPLICABLE_YEAR IS '适用年度';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.FIELD_COUNT IS '字段数量';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.USAGE_COUNT IS '使用次数';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.IS_PUBLIC IS '是否公开(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.ALLOW_COPY IS '是否允许复制(0否1是)';

COMMIT;

