-- ============================================================
-- 高级功能模块 - 达梦DM8建表脚本
-- 共7张新表，对应advancedFeatures模块新增的Entity
-- ============================================================

-- 1. 高级报表表
CREATE TABLE "REDACTED"."TBL_ADVANCED_REPORT" (
    "REPORT_ID"             VARCHAR2(64) NOT NULL,
    "REPORT_NAME"           VARCHAR2(200),
    "REPORT_TYPE"           VARCHAR2(50),
    "DATA_SOURCE"           VARCHAR2(200),
    "GENERATION_FREQUENCY"  VARCHAR2(50),
    "REPORT_STATUS"         VARCHAR2(50) DEFAULT 'DRAFT',
    "DESCRIPTION"           VARCHAR2(500),
    "CREATE_BY"             VARCHAR2(100),
    "CREATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"             VARCHAR2(100),
    "UPDATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"              INTEGER DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("REPORT_ID")
);
COMMENT ON TABLE REDACTED.TBL_ADVANCED_REPORT IS '高级报表表';

-- 2. 自动化工作流表
CREATE TABLE "REDACTED"."TBL_AUTOMATION_WORKFLOW" (
    "WORKFLOW_ID"           VARCHAR2(64) NOT NULL,
    "WORKFLOW_NAME"         VARCHAR2(200),
    "WORKFLOW_TYPE"         VARCHAR2(50),
    "TRIGGER_TYPE"          VARCHAR2(50),
    "EXECUTION_COUNT"       INTEGER DEFAULT 0,
    "LAST_EXECUTION"        TIMESTAMP(6),
    "STATUS"                VARCHAR2(50) DEFAULT 'INACTIVE',
    "CREATOR"               VARCHAR2(100),
    "DESCRIPTION"           VARCHAR2(500),
    "CREATE_BY"             VARCHAR2(100),
    "CREATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"             VARCHAR2(100),
    "UPDATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"              INTEGER DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("WORKFLOW_ID")
);
COMMENT ON TABLE REDACTED.TBL_AUTOMATION_WORKFLOW IS '自动化工作流表';

-- 3. 预算优化表
CREATE TABLE "REDACTED"."TBL_BUDGET_OPTIMIZATION" (
    "OPTIMIZATION_ID"       VARCHAR2(64) NOT NULL,
    "TASK_NAME"             VARCHAR2(200),
    "OPTIMIZATION_TYPE"     VARCHAR2(50),
    "OPTIMIZATION_STATUS"   VARCHAR2(50) DEFAULT 'PENDING',
    "TARGET_BUDGET"         VARCHAR2(200),
    "OPTIMIZATION_RESULT"   CLOB,
    "EXECUTION_TIME"        INTEGER,
    "DESCRIPTION"           VARCHAR2(500),
    "CREATE_BY"             VARCHAR2(100),
    "CREATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"             VARCHAR2(100),
    "UPDATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"              INTEGER DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("OPTIMIZATION_ID")
);
COMMENT ON TABLE REDACTED.TBL_BUDGET_OPTIMIZATION IS '预算优化表';

-- 4. 协同预算项目表
CREATE TABLE "REDACTED"."TBL_COLLABORATIVE_PROJECT" (
    "PROJECT_ID"            VARCHAR2(64) NOT NULL,
    "PROJECT_NAME"          VARCHAR2(200),
    "COLLABORATION_TYPE"    VARCHAR2(50),
    "PROJECT_STATUS"        VARCHAR2(50) DEFAULT 'ACTIVE',
    "PARTICIPANT_COUNT"     INTEGER DEFAULT 0,
    "DESCRIPTION"           VARCHAR2(500),
    "CREATE_BY"             VARCHAR2(100),
    "CREATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"             VARCHAR2(100),
    "UPDATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"              INTEGER DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("PROJECT_ID")
);
COMMENT ON TABLE REDACTED.TBL_COLLABORATIVE_PROJECT IS '协同预算项目表';

-- 5. 数据挖掘任务表
CREATE TABLE "REDACTED"."TBL_DATA_MINING_TASK" (
    "TASK_ID"               VARCHAR2(64) NOT NULL,
    "TASK_NAME"             VARCHAR2(200),
    "MINING_TYPE"           VARCHAR2(50),
    "ALGORITHM"             VARCHAR2(100),
    "DATA_SOURCE"           VARCHAR2(200),
    "MIN_SUPPORT"           NUMBER(10,4),
    "MIN_CONFIDENCE"        NUMBER(10,4),
    "FEATURE_SELECTION"     VARCHAR2(500),
    "ALGORITHM_PARAMETERS"  CLOB,
    "TASK_STATUS"           VARCHAR2(50) DEFAULT 'PENDING',
    "DESCRIPTION"           VARCHAR2(500),
    "CREATE_BY"             VARCHAR2(100),
    "CREATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"             VARCHAR2(100),
    "UPDATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"              INTEGER DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("TASK_ID")
);
COMMENT ON TABLE REDACTED.TBL_DATA_MINING_TASK IS '数据挖掘任务表';

-- 6. 版本比较表
CREATE TABLE "REDACTED"."TBL_VERSION_COMPARISON" (
    "COMPARISON_ID"         VARCHAR2(64) NOT NULL,
    "COMPARISON_NAME"       VARCHAR2(200),
    "COMPARISON_TYPE"       VARCHAR2(50),
    "SOURCE_VERSION"        VARCHAR2(100),
    "TARGET_VERSION"        VARCHAR2(100),
    "COMPARISON_SCOPE"      VARCHAR2(200),
    "COMPARISON_STATUS"     VARCHAR2(50) DEFAULT 'PENDING',
    "DIFFERENCE_COUNT"      INTEGER DEFAULT 0,
    "DESCRIPTION"           VARCHAR2(500),
    "CREATE_BY"             VARCHAR2(100),
    "CREATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"             VARCHAR2(100),
    "UPDATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"              INTEGER DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("COMPARISON_ID")
);
COMMENT ON TABLE REDACTED.TBL_VERSION_COMPARISON IS '版本比较表';

-- 7. 风险评估表
CREATE TABLE "REDACTED"."TBL_RISK_ASSESSMENT" (
    "ASSESSMENT_ID"         VARCHAR2(64) NOT NULL,
    "RISK_NAME"             VARCHAR2(200),
    "RISK_TYPE"             VARCHAR2(50),
    "RISK_LEVEL"            VARCHAR2(50),
    "PROBABILITY"           NUMBER(10,4),
    "IMPACT"                NUMBER(10,4),
    "RISK_SCORE"            NUMBER(10,4),
    "STATUS"                VARCHAR2(50) DEFAULT 'ACTIVE',
    "ASSESSOR"              VARCHAR2(100),
    "ASSESSMENT_DATE"       TIMESTAMP(6),
    "MITIGATION_PLAN"       CLOB,
    "DESCRIPTION"           VARCHAR2(500),
    "CREATE_BY"             VARCHAR2(100),
    "CREATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"             VARCHAR2(100),
    "UPDATE_TIME"           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"              INTEGER DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("ASSESSMENT_ID")
);
COMMENT ON TABLE REDACTED.TBL_RISK_ASSESSMENT IS '风险评估表';
