-- ============================================================
-- 预算管理系统 - 缺失表建表脚本
-- 数据库：达梦DM8  Schema：REDACTED
-- 包含：TBL_BUDGET_PARAMETER / TBL_BUDGET_VERSION / TBL_BUDGET_TEMPLATE
-- ============================================================

-- ============================================================
-- 1. 预算参数表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_PARAMETER"
(
    "PARAMETER_ID"          VARCHAR2(64)    NOT NULL,
    "PARAMETER_CODE"        VARCHAR2(100),
    "PARAMETER_NAME"        VARCHAR2(200),
    "PARAMETER_TYPE"        VARCHAR2(50),
    "PARAMETER_CATEGORY"    VARCHAR2(100),
    "PARAMETER_VALUE"       VARCHAR2(500),
    "DEFAULT_VALUE"         VARCHAR2(500),
    "PARAMETER_UNIT"        VARCHAR2(50),
    "IS_REQUIRED"           NUMBER(1,0)     DEFAULT 0,
    "IS_ENABLED"            NUMBER(1,0)     DEFAULT 1,
    "SORT_ORDER"            INTEGER         DEFAULT 0,
    "PARAMETER_DESCRIPTION" VARCHAR2(500),
    "REMARK"                VARCHAR2(500),
    "CREATE_BY"             VARCHAR2(100),
    "CREATE_TIME"           TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"             VARCHAR2(100),
    "UPDATE_TIME"           TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"              INTEGER         DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("PARAMETER_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_PARAMETER IS '预算参数表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_ID IS '参数ID';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_CODE IS '参数编码';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_NAME IS '参数名称';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_TYPE IS '参数类型(STRING/NUMBER/DATE/BOOLEAN/JSON)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_CATEGORY IS '参数分类';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_VALUE IS '参数值';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.DEFAULT_VALUE IS '默认值';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.IS_ENABLED IS '是否启用(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.DEL_FLAG IS '删除标志(0未删除1已删除)';

-- ============================================================
-- 2. 预算版本表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_VERSION"
(
    "VERSION_ID"          VARCHAR2(64)    NOT NULL,
    "VERSION_CODE"        VARCHAR2(100),
    "VERSION_NAME"        VARCHAR2(200),
    "VERSION_NO"          VARCHAR2(50),
    "BUDGET_YEAR"         INTEGER,
    "BUDGET_ID"           VARCHAR2(64),
    "BUDGET_AMOUNT"       NUMBER(20,2)    DEFAULT 0,
    "VERSION_TYPE"        VARCHAR2(50),
    "VERSION_STATUS"      VARCHAR2(50),
    "PARENT_VERSION_ID"   VARCHAR2(64),
    "IS_CURRENT"          NUMBER(1,0)     DEFAULT 0,
    "IS_LOCKED"           NUMBER(1,0)     DEFAULT 0,
    "EFFECTIVE_DATE"      TIMESTAMP(6),
    "EXPIRY_DATE"         TIMESTAMP(6),
    "VERSION_DESCRIPTION" VARCHAR2(500),
    "CHANGE_LOG"          CLOB,
    "REMARK"              VARCHAR2(500),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "CREATE_BY"           VARCHAR2(100),
    "UPDATE_BY"           VARCHAR2(100),
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    "TENANT_ID"           VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("VERSION_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_VERSION IS '预算版本表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_VERSION.VERSION_ID IS '版本ID';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_VERSION.VERSION_TYPE IS '版本类型(INITIAL/ADJUSTMENT/FORECAST/FINAL)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_VERSION.VERSION_STATUS IS '版本状态(DRAFT/ACTIVE/ARCHIVED/LOCKED)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_VERSION.IS_CURRENT IS '是否当前版本(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_VERSION.IS_LOCKED IS '是否锁定(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_VERSION.DEL_FLAG IS '删除标志(0未删除1已删除)';

-- ============================================================
-- 3. 预算模板表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_TEMPLATE"
(
    "TEMPLATE_ID"          VARCHAR2(64)    NOT NULL,
    "ID"                   VARCHAR2(64),
    "TEMPLATE_CODE"        VARCHAR2(100),
    "TEMPLATE_NAME"        VARCHAR2(200),
    "TEMPLATE_TYPE"        VARCHAR2(50),
    "APPLICABLE_SCOPE"     VARCHAR2(200),
    "TEMPLATE_STRUCTURE"   CLOB,
    "FIELD_CONFIG"         CLOB,
    "CALCULATION_RULES"    CLOB,
    "IS_DEFAULT"           NUMBER(1,0)     DEFAULT 0,
    "IS_ENABLED"           NUMBER(1,0)     DEFAULT 1,
    "IS_SYSTEM"            NUMBER(1,0)     DEFAULT 0,
    "STATUS"               VARCHAR2(20)    DEFAULT '1',
    "SORT_ORDER"           INTEGER         DEFAULT 0,
    "TEMPLATE_DESCRIPTION" VARCHAR2(500),
    "REMARK"               VARCHAR2(500),
    "CREATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "CREATE_BY"            VARCHAR2(100),
    "UPDATE_BY"            VARCHAR2(100),
    "DEL_FLAG"             INTEGER         DEFAULT 0,
    "TENANT_ID"            VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("TEMPLATE_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_TEMPLATE IS '预算模板表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.TEMPLATE_ID IS '模板ID';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.TEMPLATE_TYPE IS '模板类型(STANDARD/CUSTOM/INDUSTRY)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.IS_DEFAULT IS '是否默认模板(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.IS_ENABLED IS '是否启用(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.STATUS IS '状态(1启用0禁用)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_TEMPLATE.DEL_FLAG IS '删除标志(0未删除1已删除)';

COMMIT;

