-- ============================================================
-- 预算管理系统 - 核心表建表脚本
-- 数据库：达梦DM8  Schema：REDACTED
-- 包含：TBL_BUDGET_ACCOUNT / TBL_BUDGET_ACCOUNT_MAPPING /
--       TBL_BUDGET_YEAR / TBL_BUDGET_PERIOD /
--       TBL_BUDGET_DATA / TBL_BUDGET_ADJUSTMENT /
--       TBL_BUDGET_ALLOCATION / TBL_BUDGET_CONSOLIDATION /
--       TBL_BUDGET_FORMULA / TBL_BUDGET_RULE /
--       TBL_BUDGET_SCENARIO / TBL_BUDGET_WORKFLOW /
--       TBL_BUDGET_APPROVAL / TBL_BUDGET_DIMENSION /
--       TBL_BUDGET_DIMENSION_VALUE / TBL_BUDGET_ORGANIZATION /
--       TBL_PERIOD_HISTORY / TBL_PERIOD_SETTING
-- ============================================================

-- ============================================================
-- 1. 预算科目表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_ACCOUNT"
(
    "ACCOUNT_ID"          VARCHAR2(64)    NOT NULL,
    "ACCOUNT_CODE"        VARCHAR2(100),
    "ACCOUNT_NAME"        VARCHAR2(200),
    "ACCOUNT_TYPE"        VARCHAR2(50),
    "ACCOUNT_CATEGORY"    VARCHAR2(100),
    "PARENT_ID"           VARCHAR2(64),
    "ACCOUNT_LEVEL"       INTEGER         DEFAULT 1,
    "IS_LEAF"             NUMBER(1,0)     DEFAULT 1,
    "IS_ACTIVE"           NUMBER(1,0)     DEFAULT 1,
    "SORT_ORDER"          INTEGER         DEFAULT 0,
    "ACCOUNT_DESCRIPTION" VARCHAR2(500),
    "REMARK"              VARCHAR2(500),
    "CREATE_BY"           VARCHAR2(100),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"           VARCHAR2(100),
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    "TENANT_ID"           VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("ACCOUNT_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_ACCOUNT IS '预算科目表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ACCOUNT.ACCOUNT_ID IS '科目ID';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ACCOUNT.ACCOUNT_CODE IS '科目编码';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ACCOUNT.ACCOUNT_NAME IS '科目名称';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ACCOUNT.ACCOUNT_TYPE IS '科目类型(REVENUE/COST/EXPENSE/ASSET/LIABILITY)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ACCOUNT.IS_ACTIVE IS '是否启用(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ACCOUNT.DEL_FLAG IS '删除标志(0未删除1已删除)';

-- ============================================================
-- 2. 科目映射表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_ACCOUNT_MAPPING"
(
    "MAPPING_ID"          VARCHAR2(64)    NOT NULL,
    "ACCOUNT_ID"          VARCHAR2(64),
    "SOURCE_SYSTEM"       VARCHAR2(100),
    "SOURCE_CODE"         VARCHAR2(100),
    "SOURCE_NAME"         VARCHAR2(200),
    "MAPPING_TYPE"        VARCHAR2(50),
    "IS_ACTIVE"           NUMBER(1,0)     DEFAULT 1,
    "REMARK"              VARCHAR2(500),
    "CREATE_BY"           VARCHAR2(100),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"           VARCHAR2(100),
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("MAPPING_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_ACCOUNT_MAPPING IS '科目映射表';

-- ============================================================
-- 3. 预算年度表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_YEAR"
(
    "YEAR_ID"             VARCHAR2(64)    NOT NULL,
    "YEAR_CODE"           VARCHAR2(20),
    "YEAR_NAME"           VARCHAR2(100),
    "BUDGET_YEAR"         INTEGER,
    "YEAR_STATUS"         VARCHAR2(20)    DEFAULT 'DRAFT',
    "IS_CURRENT"          NUMBER(1,0)     DEFAULT 0,
    "START_DATE"          TIMESTAMP(6),
    "END_DATE"            TIMESTAMP(6),
    "YEAR_DESCRIPTION"    VARCHAR2(500),
    "REMARK"              VARCHAR2(500),
    "CREATE_BY"           VARCHAR2(100),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"           VARCHAR2(100),
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    "TENANT_ID"           VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("YEAR_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_YEAR IS '预算年度表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_YEAR.YEAR_STATUS IS '年度状态(DRAFT/OPEN/CLOSED)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_YEAR.IS_CURRENT IS '是否当前年度(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_YEAR.DEL_FLAG IS '删除标志(0未删除1已删除)';

-- ============================================================
-- 4. 预算期间表（已存在，跳过）
-- ============================================================
-- TBL_BUDGET_PERIOD 已在系统中存在

-- ============================================================
-- 5. 期间历史表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_PERIOD_HISTORY"
(
    "HISTORY_ID"          VARCHAR2(64)    NOT NULL,
    "PERIOD_ID"           VARCHAR2(64),
    "OPERATION_TYPE"      VARCHAR2(50),
    "OPERATION_DESC"      VARCHAR2(500),
    "BEFORE_STATUS"       VARCHAR2(20),
    "AFTER_STATUS"        VARCHAR2(20),
    "OPERATOR_ID"         VARCHAR2(64),
    "OPERATOR_NAME"       VARCHAR2(100),
    "OPERATION_TIME"      TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "REMARK"              VARCHAR2(500),
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("HISTORY_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_PERIOD_HISTORY IS '期间操作历史表';

-- ============================================================
-- 6. 期间设置表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_PERIOD_SETTING"
(
    "SETTING_ID"          VARCHAR2(64)    NOT NULL,
    "DEFAULT_PERIOD_TYPE" VARCHAR2(20)    DEFAULT 'MONTHLY',
    "AUTO_OPEN"           NUMBER(1,0)     DEFAULT 0,
    "AUTO_CLOSE"          NUMBER(1,0)     DEFAULT 0,
    "ALLOW_ADJUSTMENT"    NUMBER(1,0)     DEFAULT 1,
    "LOCK_DAYS"           INTEGER         DEFAULT 0,
    "REMARK"              VARCHAR2(500),
    "CREATE_BY"           VARCHAR2(100),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"           VARCHAR2(100),
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    NOT CLUSTER PRIMARY KEY("SETTING_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_PERIOD_SETTING IS '期间设置表';



-- ============================================================
-- 7. 预算数据表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_DATA"
(
    "DATA_ID"             VARCHAR2(64)    NOT NULL,
    "TASK_ID"             VARCHAR2(64),
    "BUDGET_ID"           VARCHAR2(64),
    "BUDGET_YEAR"         INTEGER,
    "BUDGET_PERIOD"       VARCHAR2(50),
    "ORGANIZATION_ID"     VARCHAR2(64),
    "DEPARTMENT_ID"       VARCHAR2(64),
    "PROJECT_ID"          VARCHAR2(64),
    "PRODUCT_ID"          VARCHAR2(64),
    "INDICATOR_ID"        VARCHAR2(64),
    "INDICATOR_CODE"      VARCHAR2(100),
    "INDICATOR_NAME"      VARCHAR2(200),
    "BUDGET_VALUE"        NUMBER(20,2)    DEFAULT 0,
    "ACTUAL_VALUE"        NUMBER(20,2)    DEFAULT 0,
    "VARIANCE_VALUE"      NUMBER(20,2)    DEFAULT 0,
    "VARIANCE_RATE"       NUMBER(10,4)    DEFAULT 0,
    "CURRENCY"            VARCHAR2(10)    DEFAULT 'CNY',
    "DATA_SOURCE"         VARCHAR2(20)    DEFAULT 'MANUAL',
    "DATA_STATUS"         VARCHAR2(20)    DEFAULT 'DRAFT',
    "VERSION_NO"          VARCHAR2(50),
    "SCENARIO_ID"         VARCHAR2(64),
    "DIMENSION_VALUES"    CLOB,
    "IS_LOCKED"           NUMBER(1,0)     DEFAULT 0,
    "REMARK"              VARCHAR2(500),
    "CREATE_BY"           VARCHAR2(100),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"           VARCHAR2(100),
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    "TENANT_ID"           VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("DATA_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_DATA IS '预算数据表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_DATA.DATA_SOURCE IS '数据来源(MANUAL/IMPORT/CALCULATION/SYSTEM)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_DATA.DATA_STATUS IS '数据状态(DRAFT/SUBMITTED/APPROVED/REJECTED)';

-- ============================================================
-- 8. 预算调整表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_ADJUSTMENT"
(
    "ADJUSTMENT_ID"       VARCHAR2(64)    NOT NULL,
    "ADJUSTMENT_CODE"     VARCHAR2(100),
    "ADJUSTMENT_TYPE"     VARCHAR2(50),
    "ORIGINAL_BUDGET_ID"  VARCHAR2(64),
    "ADJUSTMENT_AMOUNT"   NUMBER(20,2)    DEFAULT 0,
    "ORIGINAL_AMOUNT"     NUMBER(20,2)    DEFAULT 0,
    "ADJUSTED_AMOUNT"     NUMBER(20,2)    DEFAULT 0,
    "ADJUSTMENT_REASON"   VARCHAR2(500),
    "ADJUSTMENT_STATUS"   VARCHAR2(20)    DEFAULT 'DRAFT',
    "BUDGET_YEAR"         INTEGER,
    "BUDGET_PERIOD"       VARCHAR2(50),
    "ORGANIZATION_ID"     VARCHAR2(64),
    "ORGANIZATION_NAME"   VARCHAR2(200),
    "APPLICANT_ID"        VARCHAR2(64),
    "APPLICANT_NAME"      VARCHAR2(100),
    "APPLY_DATE"          TIMESTAMP(6),
    "APPROVER_ID"         VARCHAR2(64),
    "APPROVER_NAME"       VARCHAR2(100),
    "APPROVE_DATE"        TIMESTAMP(6),
    "APPROVE_COMMENT"     VARCHAR2(500),
    "REMARK"              VARCHAR2(500),
    "CREATE_BY"           VARCHAR2(100),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"           VARCHAR2(100),
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    "TENANT_ID"           VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("ADJUSTMENT_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_ADJUSTMENT IS '预算调整表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ADJUSTMENT.ADJUSTMENT_TYPE IS '调整类型(INCREASE/DECREASE/TRANSFER)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ADJUSTMENT.ADJUSTMENT_STATUS IS '调整状态(DRAFT/PENDING/APPROVED/REJECTED/CANCELLED)';

-- ============================================================
-- 9. 预算分配表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_ALLOCATION"
(
    "ALLOCATION_ID"       VARCHAR2(64)    NOT NULL,
    "ALLOCATION_CODE"     VARCHAR2(100),
    "ALLOCATION_NAME"     VARCHAR2(200),
    "ALLOCATION_TYPE"     VARCHAR2(50),
    "ALLOCATION_METHOD"   VARCHAR2(50),
    "SOURCE_BUDGET_ID"    VARCHAR2(64),
    "TOTAL_AMOUNT"        NUMBER(20,2)    DEFAULT 0,
    "ALLOCATED_AMOUNT"    NUMBER(20,2)    DEFAULT 0,
    "REMAINING_AMOUNT"    NUMBER(20,2)    DEFAULT 0,
    "ALLOCATION_STATUS"   VARCHAR2(20)    DEFAULT 'DRAFT',
    "BUDGET_YEAR"         INTEGER,
    "BUDGET_PERIOD"       VARCHAR2(50),
    "DIMENSION_TYPE"      VARCHAR2(50),
    "ALLOCATION_RULES"    CLOB,
    "REMARK"              VARCHAR2(500),
    "CREATE_BY"           VARCHAR2(100),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"           VARCHAR2(100),
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    "TENANT_ID"           VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("ALLOCATION_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_ALLOCATION IS '预算分配表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ALLOCATION.ALLOCATION_STATUS IS '分配状态(DRAFT/CONFIRMED/CANCELLED)';


-- ============================================================
-- 10. 预算合并表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_CONSOLIDATION"
(
    "CONSOLIDATION_ID"    VARCHAR2(64)    NOT NULL,
    "CONSOLIDATION_CODE"  VARCHAR2(100),
    "CONSOLIDATION_NAME"  VARCHAR2(200),
    "CONSOLIDATION_TYPE"  VARCHAR2(50),
    "CONSOLIDATION_STATUS" VARCHAR2(20)   DEFAULT 'DRAFT',
    "BUDGET_YEAR"         INTEGER,
    "BUDGET_PERIOD"       VARCHAR2(50),
    "TOTAL_AMOUNT"        NUMBER(20,2)    DEFAULT 0,
    "CONSOLIDATION_RULES" CLOB,
    "EXECUTE_TIME"        TIMESTAMP(6),
    "REMARK"              VARCHAR2(500),
    "CREATE_BY"           VARCHAR2(100),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"           VARCHAR2(100),
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    "TENANT_ID"           VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("CONSOLIDATION_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_CONSOLIDATION IS '预算合并表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_CONSOLIDATION.CONSOLIDATION_STATUS IS '合并状态(DRAFT/EXECUTING/COMPLETED/FAILED)';

-- ============================================================
-- 11. 预算公式表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_FORMULA"
(
    "FORMULA_ID"          VARCHAR2(64)    NOT NULL,
    "FORMULA_CODE"        VARCHAR2(100),
    "FORMULA_NAME"        VARCHAR2(200),
    "FORMULA_TYPE"        VARCHAR2(50),
    "FORMULA_CATEGORY"    VARCHAR2(100),
    "FORMULA_EXPRESSION"  CLOB,
    "FORMULA_STATUS"      VARCHAR2(20)    DEFAULT 'ACTIVE',
    "IS_ENABLED"          NUMBER(1,0)     DEFAULT 1,
    "SORT_ORDER"          INTEGER         DEFAULT 0,
    "FORMULA_DESCRIPTION" VARCHAR2(500),
    "REMARK"              VARCHAR2(500),
    "CREATE_BY"           VARCHAR2(100),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"           VARCHAR2(100),
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    "TENANT_ID"           VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("FORMULA_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_FORMULA IS '预算公式表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_FORMULA.FORMULA_STATUS IS '公式状态(ACTIVE/INACTIVE/DRAFT)';

-- ============================================================
-- 12. 预算规则表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_RULE"
(
    "RULE_ID"             VARCHAR2(64)    NOT NULL,
    "RULE_CODE"           VARCHAR2(100),
    "RULE_NAME"           VARCHAR2(200),
    "RULE_TYPE"           VARCHAR2(50),
    "RULE_CATEGORY"       VARCHAR2(100),
    "RULE_CONDITION"      CLOB,
    "RULE_ACTION"         CLOB,
    "RULE_STATUS"         VARCHAR2(20)    DEFAULT 'ACTIVE',
    "IS_ENABLED"          NUMBER(1,0)     DEFAULT 1,
    "PRIORITY"            INTEGER         DEFAULT 0,
    "RULE_DESCRIPTION"    VARCHAR2(500),
    "REMARK"              VARCHAR2(500),
    "CREATE_BY"           VARCHAR2(100),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"           VARCHAR2(100),
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    "TENANT_ID"           VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("RULE_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_RULE IS '预算规则表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_RULE.RULE_STATUS IS '规则状态(ACTIVE/INACTIVE/DRAFT)';

-- ============================================================
-- 13. 预算场景表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_SCENARIO"
(
    "SCENARIO_ID"         VARCHAR2(64)    NOT NULL,
    "SCENARIO_CODE"       VARCHAR2(100),
    "SCENARIO_NAME"       VARCHAR2(200),
    "SCENARIO_TYPE"       VARCHAR2(50),
    "SCENARIO_STATUS"     VARCHAR2(20)    DEFAULT 'DRAFT',
    "IS_BASELINE"         NUMBER(1,0)     DEFAULT 0,
    "BASE_SCENARIO_ID"    VARCHAR2(64),
    "BUDGET_YEAR"         INTEGER,
    "TOTAL_AMOUNT"        NUMBER(20,2)    DEFAULT 0,
    "SCENARIO_DESCRIPTION" VARCHAR2(500),
    "ASSUMPTIONS"         CLOB,
    "REMARK"              VARCHAR2(500),
    "CREATE_BY"           VARCHAR2(100),
    "CREATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"           VARCHAR2(100),
    "UPDATE_TIME"         TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"            INTEGER         DEFAULT 0,
    "TENANT_ID"           VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("SCENARIO_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_SCENARIO IS '预算场景表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_SCENARIO.SCENARIO_STATUS IS '场景状态(DRAFT/ACTIVE/ARCHIVED)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_SCENARIO.IS_BASELINE IS '是否基准场景(0否1是)';


-- ============================================================
-- 14. 预算工作流表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_WORKFLOW"
(
    "WORKFLOW_ID"          VARCHAR2(64)    NOT NULL,
    "WORKFLOW_CODE"        VARCHAR2(100),
    "WORKFLOW_NAME"        VARCHAR2(200),
    "WORKFLOW_TYPE"        VARCHAR2(50),
    "WORKFLOW_DEFINITION"  CLOB,
    "NODE_CONFIG"          CLOB,
    "IS_ENABLED"           NUMBER(1,0)     DEFAULT 1,
    "WORKFLOW_DESCRIPTION" VARCHAR2(500),
    "REMARK"               VARCHAR2(500),
    "CREATE_BY"            VARCHAR2(100),
    "CREATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"            VARCHAR2(100),
    "UPDATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"             INTEGER         DEFAULT 0,
    "TENANT_ID"            VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("WORKFLOW_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_WORKFLOW IS '预算工作流表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.WORKFLOW_TYPE IS '工作流类型(APPROVAL/NOTIFICATION/AUTOMATION)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.IS_ENABLED IS '是否启用(0否1是)';

-- 新增字段
ALTER TABLE "REDACTED"."TBL_BUDGET_WORKFLOW" ADD "VERSION"             INTEGER         DEFAULT 1;
ALTER TABLE "REDACTED"."TBL_BUDGET_WORKFLOW" ADD "WORKFLOW_STATUS"     VARCHAR2(20)    DEFAULT 'DRAFT';
ALTER TABLE "REDACTED"."TBL_BUDGET_WORKFLOW" ADD "CATEGORY_ID"        VARCHAR2(64);
ALTER TABLE "REDACTED"."TBL_BUDGET_WORKFLOW" ADD "ALLOW_PARALLEL"     NUMBER(1,0)     DEFAULT 0;
ALTER TABLE "REDACTED"."TBL_BUDGET_WORKFLOW" ADD "ALLOW_SKIP"         NUMBER(1,0)     DEFAULT 0;
ALTER TABLE "REDACTED"."TBL_BUDGET_WORKFLOW" ADD "AUTO_START"         NUMBER(1,0)     DEFAULT 0;
ALTER TABLE "REDACTED"."TBL_BUDGET_WORKFLOW" ADD "NOTIFY_ON_START"    NUMBER(1,0)     DEFAULT 0;
ALTER TABLE "REDACTED"."TBL_BUDGET_WORKFLOW" ADD "NOTIFY_ON_COMPLETE" NUMBER(1,0)     DEFAULT 1;
ALTER TABLE "REDACTED"."TBL_BUDGET_WORKFLOW" ADD "INSTANCE_COUNT"     INTEGER         DEFAULT 0;
ALTER TABLE "REDACTED"."TBL_BUDGET_WORKFLOW" ADD "AVG_DURATION"       INTEGER         DEFAULT 0;
ALTER TABLE "REDACTED"."TBL_BUDGET_WORKFLOW" ADD "SUCCESS_RATE"       NUMBER(5,2)     DEFAULT 0;

COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.VERSION IS '版本号';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.WORKFLOW_STATUS IS '工作流状态(DRAFT/PUBLISHED/ACTIVE/SUSPENDED/ARCHIVED)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.CATEGORY_ID IS '分类ID';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.ALLOW_PARALLEL IS '是否允许并行(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.ALLOW_SKIP IS '是否允许跳过(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.AUTO_START IS '是否自动启动(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.NOTIFY_ON_START IS '启动时通知(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.NOTIFY_ON_COMPLETE IS '完成时通知(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.INSTANCE_COUNT IS '实例数量';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.AVG_DURATION IS '平均耗时(分钟)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_WORKFLOW.SUCCESS_RATE IS '成功率(百分比)';

-- ============================================================
-- 15. 预算审批表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_APPROVAL"
(
    "APPROVAL_ID"          VARCHAR2(64)    NOT NULL,
    "APPROVAL_CODE"        VARCHAR2(100),
    "BUDGET_ID"            VARCHAR2(64),
    "TASK_ID"              VARCHAR2(64),
    "APPROVAL_TYPE"        VARCHAR2(50),
    "APPROVAL_STATUS"      VARCHAR2(20)    DEFAULT 'PENDING',
    "CURRENT_NODE"         VARCHAR2(100),
    "CURRENT_APPROVER_ID"  VARCHAR2(64),
    "CURRENT_APPROVER_NAME" VARCHAR2(100),
    "SUBMITTER_ID"         VARCHAR2(64),
    "SUBMITTER_NAME"       VARCHAR2(100),
    "SUBMIT_TIME"          TIMESTAMP(6),
    "APPROVAL_COMMENT"     VARCHAR2(500),
    "REJECT_REASON"        VARCHAR2(500),
    "APPROVAL_TIME"        TIMESTAMP(6),
    "WORKFLOW_INSTANCE_ID" VARCHAR2(64),
    "ATTACHMENTS"          CLOB,
    "REMARK"               VARCHAR2(500),
    "CREATE_BY"            VARCHAR2(100),
    "CREATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"            VARCHAR2(100),
    "UPDATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"             INTEGER         DEFAULT 0,
    "TENANT_ID"            VARCHAR2(64),
    NOT CLUSTER PRIMARY KEY("APPROVAL_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_APPROVAL IS '预算审批表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_APPROVAL.APPROVAL_TYPE IS '审批类型(BUDGET_SUBMIT/BUDGET_ADJUSTMENT/BUDGET_TRANSFER)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_APPROVAL.APPROVAL_STATUS IS '审批状态(PENDING/APPROVED/REJECTED/WITHDRAWN/CANCELLED)';

-- ============================================================
-- 16. 预算维度表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_DIMENSION"
(
    "DIMENSION_ID"         VARCHAR2(64)    NOT NULL,
    "DIMENSION_NAME"       VARCHAR2(200),
    "DIMENSION_CODE"       VARCHAR2(100),
    "DIMENSION_TYPE"       VARCHAR2(50),
    "PARENT_ID"            VARCHAR2(64),
    "SORT_ORDER"           INTEGER         DEFAULT 0,
    "IS_REQUIRED"          NUMBER(1,0)     DEFAULT 0,
    "DIMENSION_DESCRIPTION" VARCHAR2(500),
    "CREATOR_ID"           VARCHAR2(64),
    "CREATOR_NAME"         VARCHAR2(100),
    "CREATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATER_ID"           VARCHAR2(64),
    "UPDATER_NAME"         VARCHAR2(100),
    "UPDATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "IS_ACTIVE"            NUMBER(1,0)     DEFAULT 1,
    "IS_DELETED"           INTEGER         DEFAULT 0,
    "COMPANY_ID"           VARCHAR2(64),
    "COMPANY_NAME"         VARCHAR2(200),
    NOT CLUSTER PRIMARY KEY("DIMENSION_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_DIMENSION IS '预算维度表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_DIMENSION.DIMENSION_TYPE IS '维度类型(ORGANIZATION/TIME/ACCOUNT/PROJECT/PRODUCT/CUSTOM)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_DIMENSION.IS_ACTIVE IS '是否启用(0否1是)';


-- ============================================================
-- 17. 预算维度值表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_DIMENSION_VALUE"
(
    "VALUE_ID"             VARCHAR2(64)    NOT NULL,
    "DIMENSION_ID"         VARCHAR2(64),
    "VALUE_CODE"           VARCHAR2(100),
    "VALUE_NAME"           VARCHAR2(200),
    "VALUE_DESCRIPTION"    VARCHAR2(500),
    "PARENT_ID"            VARCHAR2(64),
    "LEVEL_NUM"            INTEGER         DEFAULT 1,
    "PATH_INFO"            VARCHAR2(500),
    "IS_LEAF"              NUMBER(1,0)     DEFAULT 1,
    "SORT_ORDER"           INTEGER         DEFAULT 0,
    "IS_ENABLED"           NUMBER(1,0)     DEFAULT 1,
    "ATTRIBUTES"           CLOB,
    "CREATOR_ID"           VARCHAR2(64),
    "CREATOR_NAME"         VARCHAR2(100),
    "CREATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATER_ID"           VARCHAR2(64),
    "UPDATER_NAME"         VARCHAR2(100),
    "UPDATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "IS_DELETED"           INTEGER         DEFAULT 0,
    "COMPANY_ID"           VARCHAR2(64),
    "COMPANY_NAME"         VARCHAR2(200),
    "REMARK"               VARCHAR2(500),
    NOT CLUSTER PRIMARY KEY("VALUE_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_DIMENSION_VALUE IS '预算维度值表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_DIMENSION_VALUE.IS_LEAF IS '是否叶子节点(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_DIMENSION_VALUE.IS_ENABLED IS '是否启用(0否1是)';

-- ============================================================
-- 18. 预算组织体系表
-- ============================================================
CREATE TABLE "REDACTED"."TBL_BUDGET_ORGANIZATION"
(
    "ORGANIZATION_ID"      VARCHAR2(64)    NOT NULL,
    "ORGANIZATION_CODE"    VARCHAR2(100),
    "ORGANIZATION_NAME"    VARCHAR2(200),
    "ORGANIZATION_TYPE"    VARCHAR2(50),
    "CONTROL_MODE"         VARCHAR2(50),
    "PARENT_ID"            VARCHAR2(64),
    "ORGANIZATION_LEVEL"   INTEGER         DEFAULT 1,
    "MAX_LEVELS"           INTEGER         DEFAULT 5,
    "ORGANIZATION_PATH"    VARCHAR2(500),
    "SORT_ORDER"           INTEGER         DEFAULT 0,
    "IS_ENABLED"           NUMBER(1,0)     DEFAULT 1,
    "ORGANIZATION_DESCRIPTION" VARCHAR2(500),
    "REMARK"               VARCHAR2(500),
    "CREATOR_ID"           VARCHAR2(64),
    "CREATOR_NAME"         VARCHAR2(100),
    "CREATE_BY"            VARCHAR2(100),
    "CREATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATER_ID"           VARCHAR2(64),
    "UPDATER_NAME"         VARCHAR2(100),
    "UPDATE_BY"            VARCHAR2(100),
    "UPDATE_TIME"          TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "COMPANY_ID"           VARCHAR2(64),
    "COMPANY_NAME"         VARCHAR2(200),
    "STATUS"               VARCHAR2(20)    DEFAULT '1',
    "DEL_FLAG"             INTEGER         DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("ORGANIZATION_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_ORGANIZATION IS '预算组织体系表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ORGANIZATION.ORGANIZATION_TYPE IS '组织类型(single/multi/hierarchical/matrix/hybrid)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ORGANIZATION.CONTROL_MODE IS '控制模式(centralized/decentralized/hybrid)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_ORGANIZATION.DEL_FLAG IS '删除标志(0未删除1已删除)';

COMMIT;
