-- ============================================================
-- TBL_BUDGET_PARAMETER 建表语句（完整版，含实体类所有字段）
-- 数据库：达梦DM8  Schema：REDACTED
-- 如果表已存在，先执行 DROP TABLE "REDACTED"."TBL_BUDGET_PARAMETER";
-- ============================================================

CREATE TABLE "REDACTED"."TBL_BUDGET_PARAMETER"
(
    "PARAMETER_ID"          VARCHAR2(64)    NOT NULL,
    "PARAMETER_CODE"        VARCHAR2(100),
    "PARAMETER_NAME"        VARCHAR2(200),
    "PARAMETER_TYPE"        VARCHAR2(50),
    "PARAMETER_CATEGORY"    VARCHAR2(100),
    "PARAMETER_VALUE"       VARCHAR2(500),
    "DEFAULT_VALUE"         VARCHAR2(500),
    "PARAMETER_UNIT"        VARCHAR2(50),
    "PARAMETER_SCOPE"       VARCHAR2(50),
    "CURRENT_VALUE"         VARCHAR2(500),
    "VALIDATION_RULE"       VARCHAR2(500),
    "IS_READONLY"           NUMBER(1,0)     DEFAULT 0,
    "IS_ENCRYPTED"          NUMBER(1,0)     DEFAULT 0,
    "EFFECTIVE_SCOPE"       VARCHAR2(200),
    "LAST_MODIFY_TIME"      TIMESTAMP(6),
    "IS_REQUIRED"           NUMBER(1,0)     DEFAULT 0,
    "IS_ENABLED"            NUMBER(1,0)     DEFAULT 1,
    "SORT_ORDER"            INTEGER         DEFAULT 0,
    "PARAMETER_DESCRIPTION" VARCHAR2(500),
    "REMARK"                VARCHAR2(500),
    "CREATE_BY"             VARCHAR2(100),
    "CREATE_TIME"           TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_BY"             VARCHAR2(100),
    "UPDATE_TIME"           TIMESTAMP(6)    DEFAULT CURRENT_TIMESTAMP,
    "DEL_FLAG"              INTEGER         DEFAULT 0,
    NOT CLUSTER PRIMARY KEY("PARAMETER_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE  REDACTED.TBL_BUDGET_PARAMETER IS '预算参数表';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_ID IS '参数ID';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_CODE IS '参数编码';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_NAME IS '参数名称';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_TYPE IS '参数类型(STRING/NUMBER/DATE/BOOLEAN/JSON)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_CATEGORY IS '参数分类';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_VALUE IS '参数值';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.DEFAULT_VALUE IS '默认值';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_UNIT IS '参数单位';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_SCOPE IS '参数范围(SYSTEM/BUSINESS/CUSTOM)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.CURRENT_VALUE IS '当前值';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.VALIDATION_RULE IS '验证规则(正则表达式)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.IS_READONLY IS '是否只读(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.IS_ENCRYPTED IS '是否加密存储(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.EFFECTIVE_SCOPE IS '生效范围(逗号分隔,如GLOBAL,COMPANY)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.LAST_MODIFY_TIME IS '最后修改时间';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.IS_REQUIRED IS '是否必填(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.IS_ENABLED IS '是否启用(0否1是)';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.SORT_ORDER IS '排序序号';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.PARAMETER_DESCRIPTION IS '参数描述';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.REMARK IS '备注';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.CREATE_BY IS '创建人';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.UPDATE_BY IS '更新人';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN REDACTED.TBL_BUDGET_PARAMETER.DEL_FLAG IS '删除标志(0未删除1已删除)';

-- ============================================================
-- 20条测试数据
-- ============================================================
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP001','SYS_BUDGET_YEAR','预算年度','NUMBER','系统参数','2025','2024',NULL,'SYSTEM','2025',NULL,1,0,'GLOBAL',CURRENT_TIMESTAMP,1,1,1,'当前预算年度',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP002','SYS_BUDGET_CURRENCY','预算币种','STRING','系统参数','CNY','CNY',NULL,'SYSTEM','CNY','^[A-Z]{3}$',1,0,'GLOBAL',CURRENT_TIMESTAMP,1,1,2,'系统默认币种',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP003','SYS_DECIMAL_PLACES','金额小数位数','NUMBER','系统参数','2','2','位','SYSTEM','2','^[0-9]$',1,0,'GLOBAL',CURRENT_TIMESTAMP,1,1,3,'金额字段保留小数位数',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP004','SYS_AMOUNT_UNIT','金额单位','STRING','系统参数','元','元',NULL,'SYSTEM','元',NULL,1,0,'GLOBAL',CURRENT_TIMESTAMP,1,1,4,'金额显示单位','可选：元/万元/百万元','admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP005','BIZ_BUDGET_SUBMIT_DEADLINE','预算提交截止日','DATE','业务参数','2025-03-31','2025-03-31',NULL,'BUSINESS','2025-03-31',NULL,0,0,'COMPANY',CURRENT_TIMESTAMP,1,1,5,'年度预算提交截止日期',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP006','BIZ_BUDGET_APPROVE_LEVEL','预算审批层级','NUMBER','业务参数','3','3','级','BUSINESS','3','^[1-5]$',0,0,'COMPANY',CURRENT_TIMESTAMP,1,1,6,'预算审批所需层级数',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP007','BIZ_OVER_BUDGET_RATE','超预算预警比例','NUMBER','业务参数','0.1','0.1','%','BUSINESS','0.1','^0\.[0-9]+$',0,0,'COMPANY',CURRENT_TIMESTAMP,1,1,7,'超预算金额占比超过此值时触发预警',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP008','BIZ_ADJUST_ALLOW','允许预算调整','BOOLEAN','业务参数','1','1',NULL,'BUSINESS','1',NULL,0,0,'COMPANY',CURRENT_TIMESTAMP,1,1,8,'是否允许在执行期间调整预算',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP009','BIZ_ROLLOVER_ENABLE','结转功能开关','BOOLEAN','业务参数','0','0',NULL,'BUSINESS','0',NULL,0,0,'COMPANY',CURRENT_TIMESTAMP,1,1,9,'是否启用预算结转功能',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP010','BIZ_FREEZE_THRESHOLD','预算冻结阈值','NUMBER','业务参数','0.95','0.95','%','BUSINESS','0.95',NULL,0,0,'COMPANY',CURRENT_TIMESTAMP,1,1,10,'预算使用率超过此值时自动冻结',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP011','SYS_LOG_RETENTION_DAYS','日志保留天数','NUMBER','系统参数','180','180','天','SYSTEM','180','^[0-9]+$',1,0,'GLOBAL',CURRENT_TIMESTAMP,1,1,11,'操作日志保留天数',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP012','SYS_EXPORT_MAX_ROWS','导出最大行数','NUMBER','系统参数','10000','10000','行','SYSTEM','10000','^[0-9]+$',1,0,'GLOBAL',CURRENT_TIMESTAMP,1,1,12,'单次导出Excel最大行数限制',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP013','SYS_SESSION_TIMEOUT','会话超时时间','NUMBER','系统参数','30','30','分钟','SYSTEM','30','^[0-9]+$',1,0,'GLOBAL',CURRENT_TIMESTAMP,1,1,13,'用户会话超时时间',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP014','SYS_NOTIFY_EMAIL','系统通知邮箱','STRING','系统参数','dev@example.com','dev@example.com',NULL,'SYSTEM','dev@example.com',NULL,0,0,'GLOBAL',CURRENT_TIMESTAMP,0,1,14,'系统通知发送邮箱地址',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP015','SYS_DB_BACKUP_CRON','数据库备份计划','STRING','系统参数','0 2 * * *','0 2 * * *',NULL,'SYSTEM','0 2 * * *',NULL,1,1,'GLOBAL',CURRENT_TIMESTAMP,1,1,15,'数据库自动备份Cron表达式',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP016','CUSTOM_DEPT_BUDGET_LIMIT','部门预算上限','NUMBER','自定义参数','5000000','5000000','元','CUSTOM','5000000','^[0-9]+$',0,0,'COMPANY',CURRENT_TIMESTAMP,0,1,16,'单个部门年度预算上限',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP017','CUSTOM_PROJECT_BUDGET_LIMIT','项目预算上限','NUMBER','自定义参数','1000000','1000000','元','CUSTOM','1000000',NULL,0,0,'COMPANY',CURRENT_TIMESTAMP,0,1,17,'单个项目预算上限',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP018','BIZ_REPORT_PERIOD','报表统计周期','STRING','业务参数','MONTHLY','MONTHLY',NULL,'BUSINESS','MONTHLY','^(MONTHLY|QUARTERLY|YEARLY)$',0,0,'COMPANY',CURRENT_TIMESTAMP,1,1,18,'预算报表默认统计周期',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP019','BIZ_MULTI_CURRENCY_ENABLE','多币种支持','BOOLEAN','业务参数','0','0',NULL,'BUSINESS','0',NULL,0,0,'COMPANY',CURRENT_TIMESTAMP,0,1,19,'是否启用多币种预算管理',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);
INSERT INTO "REDACTED"."TBL_BUDGET_PARAMETER" VALUES ('BP020','CUSTOM_ALERT_NOTIFY_CONFIG','预警通知配置','JSON','自定义参数','{"email":true,"sms":false,"wechat":true}','{"email":true,"sms":false,"wechat":true}',NULL,'CUSTOM','{"email":true,"sms":false,"wechat":true}',NULL,0,0,'COMPANY',CURRENT_TIMESTAMP,0,1,20,'预警通知渠道配置(JSON格式)',NULL,'admin',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP,0);

COMMIT;

